### ISSUE TITLE
AutoScale does scale NodeHeight manually, but TotalHeight is not scaled

### ISSUE THREAD

**Issue by modersohn** [JAM-Software/Virtual-TreeView#1000]
Unfortunately I was not able to reproduce with either the Minimal or the Advanced demo, but hopefully the code is obvious.

In my app, when I move a form with a tree view to a monitor with higher DPI and expand a previously unexpanded, i.e. uninitialized node, the vertical scrollbar that is shown is not sufficient to scroll to the bottom. The tree does not use variable node heights.

The fix you introduced for #748 and later fine-tuned for #861 scales NodeHeight manually for uninitialized nodes. TotalHeight however is left unchanged, so when that node is later expanded, the vertical scrollbar range is insufficiently increased by the old unscaled TotalHeight.

Would you have an idea how to reproduce this with the demos? Even if I commented out the expansion of newly created child nodes in the Minimal demo, I could not reproduce it.

**Comment by joachimmarder** [comment]
> Would you have an idea how to reproduce this with the demos? 

Sorry, no.  

> TotalHeight however is left unchanged, so when that node is later expanded, the vertical scrollbar range is insufficiently increased by the old unscaled TotalHeight.

I would have expected that it should be quite easy to reproduce in case this is a general problem.

You can try if scaling `fTotalHeight` in `TBaseVirtualTree.ChangeScale()` makes any difference.

**Comment by modersohn** [comment]
Scaling TotalHeight in AutoScale similar to NodeHeight did indeed fix the issue for me:

```
          Run := GetFirst();
          while Assigned(Run) do
          begin
            if vsInitialized in Run.States then
              SetNodeHeight(Run, MulDiv(Run.NodeHeight, M, D))
            else // prevent initialization of non-initialzed nodes
            begin
              Run.NodeHeight := MulDiv(Run.NodeHeight, M, D);
              //my fix for issue #1000
              Run.TotalHeight := MulDiv(Run.TotalHeight, M, D);
            end;
            Run := GetNextNoInit(Run);
          end; // while

```

I'd understand that you'd be reluctant to incorporate a fix without being able to reproduce the problem - that's why I was asking for ideas on how to reproduce.

**Comment by joachimmarder** [comment]
> I'd understand that you'd be reluctant to incorporate a fix without being able to reproduce the problem

Yeah, one part is verifying the fix using the repro steps, another part is making sure that it does not to break anything. The fix looks good and makes sense. I will incorporate it.

**Comment by modersohn** [comment]
Thanks for incorporating the fix so quickly.

However, I'm wondering if this approach would be problematic due to rounding errors. If you scale a `NodeHeight` of 18 to 125%, the result of 22.5 is rounded, but a `TotalHeight` of e.g. 10 nodes of 180 is not rounded and results in 225.

So I was looking for a different fix, but that proved to be difficult. Calling `FixupTotalHeight` for the uninitialized nodes is no solution, because at that point, the child nodes of the uninitialized nodes still have their old unscaled `NodeHeight`.

For my app, a call to `FixUpNodeHeight(FRoot)` after the while loop in `.ChangeScale` works, but I suspect this is not a viable solution for large trees? I'm also not sure if it wouldn't initialize all nodes.

In addition, to be able to reproduce this, I'm still looking for a way to have uninitialized nodes with either the `Minimal` or the `Advanced` demo - but I have not found a way yet. When you fine-tuned your fix in #861 you mentioned 

"Can be seen with `Advanced` sample project, page "General Abilities"."

So you must have been able to reproduce this. Do you remember how you did this? Because when I open the General Abilities page and move the demo form to another monitor, the while loop in `.ChangeScale` does not encounter uninitialized nodes?!

Also, I'm not seeing how and why calling SetNodeHeight would initialize the nodes. I'd appreciate if you could point me in the right direction why that is the case.

**Comment by joachimmarder** [comment]
> In addition, to be able to reproduce this, I'm still looking for a way to have uninitialized nodes with either the Minimal or the Advanced demo

You need to take care that no method is called that initializes all node, like `Sort()` or the getter of the `TotalCount` property. Removing the option `toAutoSort`in the Spped demo of the Advanced project and removing the calls to `TotalHeight` produces unintialized nodes and shows the problem you describe above.

**Comment by joachimmarder** [comment]
The commit listed here was for #1001.

**Comment by modersohn** [comment]
Thanks for the hint - that allowed me to reproduce it with the `SpeedDemo` form of the `Advanced` demo!

For later reference, here are the exact steps:

1. In the `SpeedDemo` form, uncheck `VST1.AutoOptions.toAutoSort`
2. In `AddButtonClick` uncomment the two lines with setting `Expanded` and `InvalidateToBottom` after `ChildCount` was set
3. In `AddButtonClick` uncomment the line querying `TotalCount`
4. In `DeleteSelectionButtonClick` uncomment the line querying `TotalCount`
5. Run the app, switch to the `SpeedDemo` (first icon)
6. Create 20 root nodes, select one of the last ones, e.g. 18 and create 20 child nodes - note that the child nodes cannot be seen because we no longer expand the focused node
7. Resize the form so the 20 root nodes barely fit into the tree without a scrollbar being shown
8. Move the form to a window with different DPI settings
9. Expand the node with the child nodes
10. Expected: scrollbar should allow scrolling to the exact end of the tree. Actual: scrollbar range is not correctly determined, leaving you either with extra empty space or not allowing you to scroll to the end - depends on the DPI change.

This allowed me to experiment a bit and I think simply scaling the `TotalHeight` here is no problem. Because we're talking about uninitialized nodes, none of these can be expanded and have a `TotalHeight > NodeHeight`. That's why the rounding error does not come into play and we can leave the original fix. 

I leave it up to you to close the issue in case you agree.

**Comment by joachimmarder** [comment]
I was able to fix this issue for SpeedDemo with the line commented that access the `TotalHeight`. Commenting this line produces non-initialized nodes.
