### ISSUE TITLE
Prevent ImageList notifications after destruction

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1002]
I had [this issue](https://github.com/TurboPack/MustangpeakVirtualshellTools/issues/16) with VirtualshellTools which is descends from TBase.

Basically an ImageList that was connected to a VirtualTree Images was sending change notifications to a destroyed ChangeLink of the VirtualTree.  This can only be detected by FastMM in debug mode (accessing a freed object), so it may occur in other uses of VirtualTrees and go unnoticed.

I suggest the following code is added to  TBaseVirtualTree.Destroy

```pascal
  Images := nil;
  StateImages := nil;
  CheckImages := nil;
```

That should take care of the removal of notifications.

**Comment by joachimmarder** [comment]
Done. I guess you meant `CustomCheckImages`.

**Comment by landrix** [comment]
sry, but this changes results in memory leaks, if imagelists are assigned

i use FastMM

are you shure, that is the right way?

this works, but i don't know, if it helps you

 // Fixes issue #1002
  FImages := nil;
  FStateImages := nil;
  FCustomCheckImages := nil;

**Comment by landrix** [comment]
ok, i have the solution, you should place your code before freeing the changelinks

  // Fixes issue #1002
  Images := nil;
  StateImages := nil;
  CustomCheckImages := nil;

  FImageChangeLink.Free;
  FStateChangeLink.Free;
  FCustomCheckChangeLink.Free;

**Comment by joachimmarder** [comment]
Thanks @landrix, I changed the code accordingly.

**Comment by Corvus5Pl** [comment]
I updated to this version and with this change the ImageList is freed twice. First by the the VST control, then when destroying form (ImageList is placed on form). This results in FastMM5 reporting error.

**Comment by joachimmarder** [comment]
> I updated to this version and with this change the ImageList is freed twice.

@Corvus5Pl: Which of the image lists? And can you please send the call stacks of those calls to `Destroy()`.
