### ISSUE TITLE
Please change source file format to UTF-8 to avoid merge conflicts

### ISSUE THREAD

**Issue by modersohn** [JAM-Software/Virtual-TreeView#1006]
VirtualTrees.pas and possibly others contain non-ANSI characters and because these files are not saved in UTF-8 format, they sometimes show up as changed and cause merge conflicts, even though the actual file content hasn't changed. 

See pull request #1005 for an example.

It would be nice if all source files could be switched to UTF-8 so git can handle them correctly. I'm not sure though if all supported compilers can already handle UTF-8 sources.

**Comment by joachimmarder** [comment]
I haven't received any complaints about merge conflicts due to the file encoding in the past, but this is now done.

>  I'm not sure though if all supported compilers can already handle UTF-8 sources.

The file `VirtualTrees.Export.pas` was already UTF8 encoded for some time, so I don't expect any problems.
