### ISSUE TITLE
TWorkerThread.Dispose closes WorkEvent handle prematurely

### ISSUE THREAD

**Issue by modersohn** [JAM-Software/Virtual-TreeView#1007]
In `TWorkerThread.Dispose`, the global `WorkEvent` is closed without ensuring that the `WorkerThread` has actually terminated:

```
class procedure TWorkerThread.Dispose;
var
  LRef: TThread;
begin
  WorkerThread.FreeOnTerminate := not CanBlock;
  WorkerThread.Terminate();
  SetEvent(WorkEvent);
  LRef := WorkerThread;
  WorkerThread := nil; //Will be freed usinf TThreaf.FreeOnTerminate
  CloseHandle(WorkEvent);
  if CanBlock then
    LRef.Free;
end;
```

While calling `Terminate` and setting the event will eventually terminate the thread, it might still be waiting for the event by the time `CloseHandle(WorkEvent)` is called.

This could be an explanation for some of the exceptions in Kernelbase.dll I have seen while running the tests from #1001 on Win32 in the debugger.

IMO, the best solution would be to turn WorkEvent into an instance variable of TWorkerThread, create the event in the constructor **before** calling inherited and destroying it after calling inherited.

**Comment by luebbe** [comment]
I always do something like this when I destroy a worker thread:

**Inside** the thread.

```
destructor TMyWorkerThread.Destroy;
begin
  Terminate;
  FWaitEvent.SetEvent;
  WaitFor;
  FWaitEvent.Free;
  // Now free the thread's data
  FMyThreadData.Free; 
  inherited;
end;
```

I know that you are terminating the worker thread from the outside. Wouldn't a `WorkerThread.WaitFor` after `SetEvent(WorkEvent)` solve the problem?

```
class procedure TWorkerThread.Dispose;
var
  LRef: TThread;
begin
  WorkerThread.FreeOnTerminate := not CanBlock;
  WorkerThread.Terminate();
  SetEvent(WorkEvent);
*** WorkerThread.WaitFor; ***
  LRef := WorkerThread;
  WorkerThread := nil; //Will be freed usinf TThreaf.FreeOnTerminate
  CloseHandle(WorkEvent);
  if CanBlock then
    LRef.Free;
end;

```

**Comment by modersohn** [comment]
The `Dispose` method has a `CanBlock` parameter. If you `WaitFor` that would be pointless.

Also, calling `Terminate` and `WaitFor` in an overridden destructor seems odd, because that is exactly what the inherited constructor would call. If you free your event and your data after the call to the inherited destructor you wouldn't need to call neither `Terminate` nor `WaitFor`.

**Comment by luebbe** [comment]
You're right. Learned something again. But when would I call SetEvent in my case? Isn't this necessary? The thread may still be waiting for the event and never notice that it is terminated.

Like this?

```
destructor TMyWorkerThread.Destroy;
begin
  inherited;
  FWaitEvent.SetEvent;
  // Now free the thread's data
  FWaitEvent.Free;
  FMyThreadData.Free; 
  inherited;
end;
```

**Comment by modersohn** [comment]
@luebbe: no that code would make the WaitFor called in inherited potentially deadlock. 

Actually, the best place for `FWaitEvent.SetEvent` would be in an overridden `TerminatedSet`!

**Comment by joachimmarder** [comment]
> the best solution would be to turn WorkEvent into an instance variable of TWorkerThread

Agreed, I also thought about doing so earlier.

**Comment by joachimmarder** [comment]
Sorry, the commit referenced the wrong issue number #1006, too many new issues these days.
