### ISSUE TITLE
Missing exception handling of TWorkerThread

### ISSUE THREAD

**Issue by modersohn** [JAM-Software/Virtual-TreeView#1009]
TWorkerThread.Execute currently does not handle exceptions. That means, that in case of an exception, the thread will terminate and because FreeOnTerminate will destroy the thread, this will result in the global WorkerThread variable to become invalid.

See https://stackoverflow.com/a/5443127/386473 for a good approach how this could be done.

This is another reason for the exceptions I've seen while running the tests from #1001.

**Comment by modersohn** [comment]
I'll gladly provide a pull request, but could you please consider #1006 first? That would hopefully solve those messy pull requests for my fork and here too...

**Comment by modersohn** [comment]
Just added pull request #1010 

Sorry I forgot to add the issue number to the commit message.

**Comment by joachimmarder** [comment]
Thanks for the PR!
