### ISSUE TITLE
Removed copied code from TVclStyleScrollBarsHook for 10.4 and later

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#1016]
The Virtual TreeView class TVclStyleScrollBarsHook contains a lot of code copied from the base class TScrollingStyleHook. This was necessary because relevant member of TScrollingStyleHook were private. This has changed in RAD Studio 10.4. The copied code caused a lot of problems in the past, like #390  or #852.

**Comment by vincentparrett** [comment]
Agreed, this makes sense. The vcl stylehook code has changed a lot over the last few versions (not always in a good way) and keeping a single stylehook compatible with multiple delphi versions is difficult enough without also maintaining a copy of the base class methods.

**Comment by vectoris** [comment]
The problem is still there.
Vertical scrolling does not work correctly in some cases.

**Comment by pyscripter** [comment]
For reference https://quality.embarcadero.com/browse/RSP-23147?filter=-2
This apparently has been fixed in Delphi Alexandria.  It is worth finding out what was changed.
