### ISSUE TITLE
[v 7.4.0] Drawing of ttStatic text in TCustomVirtualStringTree.PaintStaticText

### ISSUE THREAD

**Issue by zarkogajic** [JAM-Software/Virtual-TreeView#1018]
Hi,

When toShowStaticText in TreeOptions.StringOptions, ttStatic text should be drawn after ttNormal in OnGetText. In 7.4.0 this is not working - static text is drawn over normal text.

In TCustomVirtualStringTree.PaintStaticText, commenting line 33667 dirty-fixes the issue: "if PaintInfo.Alignment = taRightJustify then", so have the following line not under the above if:
Inc(R.Left, NodeWidth); // room for node text

-žarko

**Comment by joachimmarder** [comment]
This is a duplicate of #978 and already fixed in master branch.
