### ISSUE TITLE
Suggestion for the vague 'insert point marker' in a drag-N-drop operation

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#102]
_From [MindVisualizer@gmail.com](https://code.google.com/u/MindVisualizer@gmail.com/) on January 19, 2010 14:59:41_

See the screenshot attached or open this link: http://dl.dropbox.com/u/367923/Screenshots/Virtual&#37;20TreeView&#37;20insert&#37;20point &#37;20marker.png

The problem: Currently during a drag-N-drop operation, since in both cases the 
'insert point marker' has the same length, users don't know whether the 
dragging node will be inserted above 'Getting started' or inserted as the last 
child of 'chapter 1'.

The suggestion: in case 2, the 'insert point marker' (the lower one) should be 
shortened so that can be distinguished from the upper one, the left end should 
be aligned to the left of the target node (i.e. The Word document icon on the 
left of 'Getting started'.

**Attachment:** [Virtual TreeView insert point marker.png](http://code.google.com/p/virtual-treeview/issues/detail?id=102)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=102_

**Comment by vincentparrett** [comment]
_From [barrystaes](https://code.google.com/u/barrystaes/) on September 25, 2013 02:39:18_

I also think drop visualization should respect the items ident.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 18, 2013 13:46:35_

I agree. I will be happy to integrate suggested code changes to the repository, but currently do not have the time to address this bug myself.

**Comment by joachimmarder** [comment]
Unfortunately the original images are no longer available. It would be great if someone could upload them again to GitHub. Otherwise I would like to close this old Google Code issue.

**Comment by joachimmarder** [comment]
Closing this bug as previously proposed. Please open an new issue at GitHub if you still feel this should be changed.
