### ISSUE TITLE
Improve PgUp/PgDown handling in in-place editor scenarios

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1020]
One can currently implement an "in-place" editor via implementing the IVTEditLink interface.
If done so and using a TEdit for the editing one can navigate the list (VT is used as list in that case) with the cursor keys. After a second or so it will switch the current cell to this editing mode if allowed for that column.

Pressing arrow up/down ends editing and selects previous or next row. That works well.
But the same thing done with PgUp/PgDown (and Pos1/End) does not work well. Editing mode is started when a row is focused for one second or more but PgUp/PgDown do not end editing and continue to scroll, which is quite different to the cursor keys.

They should be treated the same.

**Comment by joachimmarder** [comment]
> If done so and using a TEdit for the editing one can navigate the list (VT is used as list in that case) with the cursor keys. After a second or so it will switch the current cell to this editing mode if allowed for that column.

I never used that feature myself or looked at the code. Are you able to supply a sample project or tell me how I need to modify one of the demo projects to achieve this? That did not work out-of-the-box with the grid sample in the "Advanced" project.

**Comment by MHumm** [comment]
As I asked in delphipraxis.net and only got an answer to provide a sample project I guess I'll have to make one...
But that will be in the evening only. How can I share this so it doesn't get lost? I can provide a "cloud" link using my e-mail provider but that would only be valid for 30 days.

**Comment by joachimmarder** [comment]
>How can I share this so it doesn't get lost?

GitHub allows uploading Zip files to issues using drag&drop or by pasting them.

**Comment by MHumm** [comment]
Ok, we can close this. I found a failure/problem in some code I had taken from Delphipraxis as basis for my implementation. That code contained some special key handling for the edit already which contained a case for the arrow keys which I could extend to PgUp/PgDown by just adding those key codes to the case. Works as expected now.
