### ISSUE TITLE
Double-Click on a CheckBox toggles the selected nodes

### ISSUE THREAD

**Issue by attikov** [JAM-Software/Virtual-TreeView#1023]
This creates a rather strange effect and can not be considered as any standard UI behavior.
Reproduce: Fire up a tree with some nodes with checkboxes, select one node with clicking on its text, the focus and highlight appears on the node. Now start double-clicking the checkbox of a different node continuously.
The (still) selected node will be toggled, plus the one with the checkbox clicked on.

Did not try with multiselect but as I read it from the code, it would toggle all the selected nodes, but the one clicked on.

As this behavior is not by accident, I'm wondering what was its initial intention, and how should it work?

**Comment by joachimmarder** [comment]
Can be seen in Advanced demo project on "General Abilites" page.

**Comment by attikov** [comment]
I see. If it's a feature, how can I turn it off? hx

**Comment by joachimmarder** [comment]
Fixed in master. @attikov: Could you please verify this issue in your application?

**Comment by attikov** [comment]
Looks good. Thank you Joachim!
