### ISSUE TITLE
Improve default values for "Touch" property

### ISSUE THREAD

**Issue by attikov** [JAM-Software/Virtual-TreeView#1024]
please add this 2 lines to the constructor to be able to scroll the component with fingers on a touchscreen:

  Touch.InteractiveGestures := [igPan];
  Touch.InteractiveGestureOptions := [igoPanInertia, igoPanSingleFingerHorizontal, igoPanSingleFingerVertical, igoPanGutter, igoParentPassthrough];

**Comment by joachimmarder** [comment]
Good idea. I copied the initiliation of the `Touch` member from TCustomTreeview:

```
  Touch.InteractiveGestures := [igPan, igPressAndTap];
  Touch.InteractiveGestureOptions := [igoPanInertia,
    igoPanSingleFingerHorizontal, igoPanSingleFingerVertical,
    igoPanGutter, igoParentPassthrough];

```
