### ISSUE TITLE
LibSuffix values are non standard

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#1025]
Ok, now that I have said they are non standard, I'll admit there is no actual standard ;)

But that said, the libsuffix value used on pretty much every other library I use either uses 

a) the Rad Studio version (e.g, XE2, 10_4)
or
b) the Delphi Package Version ( e.g 260 for 10.3.x,  270 for 10.4.x) 

VT uses a truncated Delphi Package version, ie 27 (for 10.4) rather than 270. 

This is an ambiguous number, since it could also be the Compiler version for XE7.  

See [Compiler Versions](http://docwiki.embarcadero.com/RADStudio/Sydney/en/Compiler_Versions)

Please consider changing it, my preference would be for (b) as it matches how the rtl/vcl etc packages are named. 

The impact should be minimal since you are actually using libsuffix - the only thing people would need to change is if they are deploying runtime packages, change their installer or deploy scripts to pick up the new package name.

**Comment by joachimmarder** [comment]
> VT uses a truncated Delphi Package version, ie 27 (for 10.4) rather than 270.
> This is an ambiguous number, since it could also be the Compiler version for XE7.

I don't see why 270 is less ambiguous than 27 as both refers to a version 27.0.

> The impact should be minimal since you are actually using libsuffix - the only thing people would need to change is if they are deploying runtime packages, change their installer or deploy scripts to pick up the new package name.

I don't see much benefit in making this breaking change for all old versions. I originally intended to use **LibSuffix Auto** for the packages of RAD Studio 10.4, but this was somewhat broken in 10.4.0. I will try again now. With LibSuffix Auto we should have the standard for RAD Studio 10.4 and above, whatever this standard is.

**Comment by vincentparrett** [comment]
> I don't see why 270 is less ambiguous than 27 as both refers to a version 27.0.

27.0 is XE6, 270 is 10.4 if you look at the link above to the compiler versions page.

LibSuffix Auto will solve this for the future, I believe it works in 10.4.2
