### ISSUE TITLE
Static text display

### ISSUE THREAD

**Issue by NicolasD71** [JAM-Software/Virtual-TreeView#1026]
![VTV_StaticText](https://user-images.githubusercontent.com/81573429/112849798-afe7aa00-90a9-11eb-88d8-5956ee256e85.PNG)
Hi, 
When displaying Static text with taCenter or taLeftJustify alignmement, the static text is displayed on the cell text. 
This can be reproduced in the Advanced.dproj demo in the GeneralAbilities form.

Best regards

**Comment by joachimmarder** [comment]
This is a duplicate of #978.
