### ISSUE TITLE
Header scaling with High dpi Per Monitor v2 and Vcl Styles.

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#1027]
Hi

I'm working through getting my application working correctly with high dpi on 10.4.2, and I'm seeing issues with header scaling when vcl styles are enabled. I spent some time trying to debug this but not gotten any closer to figuring out what is going on. 

I have a bunch of VT's on frames on the form and what happens is.

Moving from 96 to 144 dpi  - most VT's scale fine, but 1 doesn't.

Moving from 144dpi to 96 - the headers do not scale back down... except for that one that didn't scale. 

If I put a breakpoint in header.SetHeight I can see the value changing multiple times, and it seems to flip flop between the two values. It seems like it is scaling correctly, and then that is being undone. 

I see strange this in the advanced demo too, but not consistently. I'm currently trying to put a test app together with a single VT to help figure this out, but any input or advice on where to look would be helpful.

**Comment by vincentparrett** [comment]
One thing I found is that TVTHeader.SetHeight is called from TVTHeader.ChangeScale - and then it does calculations based on the FixAreaConstraints

````pascal
EffectiveMinHeight := IfThen(FMaxHeightPercent > 0, Min(RelativeMaxHeight, FMinHeight), FMinHeight);
EffectiveMaxHeight := IfThen(FMinHeightPercent > 0, Max(RelativeMinHeight, FMaxHeight), FMaxHeight);
````
which is problematic, because while the height value passed in has been scaled in ChangeScale, the FMinHeight and FMaxHeight have not. 

I modified it to 

````pascal
procedure TVTHeader.ChangeScale(M, D: Integer);
var
  I: Integer;
begin
  // This method is only executed if toAutoChangeScale is set
  FMinHeight := MulDiv(FMinHeight, M, D); //<< Added
  FMaxHeight := MulDiv(FMaxHeight, M, D); //<< Added
  Self.Height := MulDiv(FHeight, M, D);
...
````
and now the header scales correctly both ways. At least is does in my test app. Sadly this doesn't fix it for my real app. The problem there seems to be that AutoScale is then called which then undoes all the work done before. 

I have attached my sample app (you will need to adjust the search path for VT) - try it with and without the change above.

[VTScaling.zip](https://github.com/JAM-Software/Virtual-TreeView/files/6225282/VTScaling.zip)

**Comment by vincentparrett** [comment]
So the one VT that wasn't scaling had toAutoChangeScale unchecked.. it scales the same as the others now. 

With the added lines in ChangeScale, and commenting out the call to AutoScale in ChangeScale, it appears to be scaling correctly in my application for all the VT's.

**Comment by joachimmarder** [comment]
Thank you for the suggested fix, scaling `FMinHeight` and `FMaxHeight` as well makes a lot of sense.

**Comment by joachimmarder** [comment]
> commenting out the call to AutoScale in ChangeScale, it appears to be scaling correctly in my application for all the VT's.

@vincentparrett: But this problem can't be replicated using your demo app, right?
So this occurs only when scaling down?
Do you have set `TVTHeader.ParentFont` set to `True` or `False`?

**Comment by joachimmarder** [comment]
I wonder if `TVirtualTreeColumn.Spacing` should be scaled as well?

**Comment by joachimmarder** [comment]
I think I know what's going on: The problem only manifests if the header height is very small. The font, which is used for auto-scaling, is updated after the dpi-scaling and so is too large when `AutoScale()` is called with a dpi scale down.

**Comment by vincentparrett** [comment]
> > commenting out the call to AutoScale in ChangeScale, it appears to be scaling correctly in my application for all the VT's.
> 
> @vincentparrett: But this problem can't be replicated using your demo app, right?

Partially, moving from low to high dpi, the header is not scaled up, it's too small
> So this occurs only when scaling down?
In my actually application it was scaling ok when moving from low to high, but not scaling down when moving from high to low
> Do you have set `TVTHeader.ParentFont` set to `True` or `False`?

True,

**Comment by vincentparrett** [comment]
> I think I know what's going on: The problem only manifests if the header height is very small. The font, which is used for auto-scaling, is updated after the dpi-scaling and so is too large when `AutoScale()` is called with a dpi scale down.

Yes,  the whole autoscale thing seems to me to be a hack for pre-highdpi support. 

With my change I tested moving between monitors with different dpi's, and when changing the font size via the monitor settings and it seems to work fine in all those cases.
