### ISSUE TITLE
TVTHeaderPopupMenu.OnMenuItemClick: DoColumnChange is never called

### ISSUE THREAD

**Issue by raketenwurm69** [JAM-Software/Virtual-TreeView#1030]
Unit: VirtualTrees.HeaderPopup.pas

I think the virtual method "DoColumnChange" from TVTHeaderPopupMenu is never called.
```
procedure TVTHeaderPopupMenu.OnMenuItemClick(Sender: TObject);
begin
  if Assigned(PopupComponent) and (PopupComponent is TBaseVirtualTree) then begin
    with TBaseVirtualTree(PopupComponent).Header.Columns.Items[TVTMenuItem(Sender).Tag] do
    begin
      if TVTMenuItem(Sender).Checked then
        Options := Options - [coVisible]
      else
        Options := Options + [coVisible];

      // This line is missing in the current version of VirtualTrees.HeaderPopup
      **DoColumnChange(TVTMenuItem(Sender).Tag, coVisible in Options);**

    end;
  end;
end;
```

**Comment by joachimmarder** [comment]
Thanks @raketenwurm69 for reporting this issue and suggesting a fix.

**Comment by joachimmarder** [comment]
@raketenwurm69, a user reported that in V7.6 the event OnColumnVisibilityChanged is now fired twice as a result of this change. Can you please supply repro steps for the originally reported issue?

**Comment by raketenwurm69** [comment]
I installed V7.6 today. When commenting out the line in question , my event handler is not called anymore.

However, my event handler is OnColumnChange() of TVTHeaderPopupMenu. There is another ColumnChange event in TBaseVirtualTree called OnColumnVisibilityChanged which is called in line 6951 of unit VirtualTrees.pas. OnColumnVisibilityChanged is triggered by TVTHeaderPopupMenu when the visibility of the Options property changes, when  hoAutoColumnPopupMenu is set in Header.Options.

Finally I can confirm that if I would switch to using the OnColumnVisibilityChanged of TBaseVirtualTree instead of TVTHeaderPopupMenu.OnColumnChange, the newly added line would be obsolete.  

Is this the correct way to go?

**Comment by raketenwurm69** [comment]
As both OnColumnChange-Events are only called when hoAutoColumnPopupMenu is in Header.Options, this might be an alternative solution:

```
procedure TVTHeaderPopupMenu.OnMenuItemClick(Sender: TObject);
begin
  if Assigned(PopupComponent) and (PopupComponent is TBaseVirtualTree) then begin
    with TBaseVirtualTree(PopupComponent).Header.Columns.Items[TVTMenuItem(Sender).Tag] do
    begin
      if TVTMenuItem(Sender).Checked then
        Options := Options - [coVisible]
      else
        Options := Options + [coVisible];
      if not (hoAutoColumnPopupMenu in TBaseVirtualTree(PopupComponent).Header.Options) then
        DoColumnChange(TVTMenuItem(Sender).Tag, coVisible in Options);
    end;
  end;
end;
```

**Comment by joachimmarder** [comment]
> However, my event handler is OnColumnChange() of TVTHeaderPopupMenu. 

OK, good to know.

> Finally I can confirm that if I would switch to using the OnColumnVisibilityChanged of TBaseVirtualTree instead of TVTHeaderPopupMenu.OnColumnChange, the newly added line would be obsolete.

That switch should make sense, as it allows to centralize your code. Or do you care how the visibility was changed?

I think it is not necessary that `TVirtualTreeColumns.HandleClick()` registers for the `TVTHeaderPopupMenu.OnColumnChange` event. This also fixes the duplicate firing of the event.

**Comment by raketenwurm69** [comment]
I personally would prefer using the OnColumnChange() of TVTHeaderPopupMenu because it only triggers when the user wants to change the visibility of a column. As I am creating the columns of my treeviews completely on runtime the event from TBaseVirtualTree is triggered a lot during creation and initialization, which leads to many unnessessary calls of the ColumnChange-Handler and on times when my tree is not completely initialized.

Therefore the 
`procedure TVTHeaderPopupMenu.DoColumnChange(Column: TColumnIndex; Visible: Boolean);`
is exactly what I need. But I need it to be triggered inside 
`procedure TVTHeaderPopupMenu.OnMenuItemClick(Sender: TObject);`

Maybe it would be possible to add a 
`procedure TVTHeaderPopupMenu.DoMenuItemClick(Sender: TObject); virtual;`
so I could overide it and call the DoOnColumnChange solely in my own implementation?

```
procedure TVTHeaderPopupMenu.OnMenuItemClick(Sender: TObject);
begin
  DoMenuItemClick(sender);
end;

procedure TVTHeaderPopupMenu.DoMenuItemClick(Sender: TObject);
begin
  if Assigned(PopupComponent) and (PopupComponent is TBaseVirtualTree) then begin
    with TBaseVirtualTree(PopupComponent).Header.Columns.Items[TVTMenuItem(Sender).Tag] do
    begin
      if TVTMenuItem(Sender).Checked then
        Options := Options - [coVisible]
      else
        Options := Options + [coVisible];
    end;
  end;
end;
```

But please keep in mind that TVTHeaderPopupMenu.DoOnColumnChange will never be called from inside TVTHeaderPopupMenu and therefore might not be neccessary anymore.

**Comment by joachimmarder** [comment]
> I personally would prefer using the OnColumnChange() of TVTHeaderPopupMenu because it only triggers when the user wants to change the **visibility** of a column. 

Since you are looking for visibility chnages, the `OnColumnVisibilityChanged` should be fine for you.

> But I need it to be triggered inside procedure TVTHeaderPopupMenu.OnMenuItemClick(Sender: TObject);

`OnMenuItemClick()` calls `TVirtualTreeColumn.SetOptions()` which fires the `OnColumnVisibilityChanged`event. So this is the case. If it helps, I will declare `OnMenuItemClick()` virtual.

**Comment by raketenwurm69** [comment]
`OnMenuItemClick()` virtual is fine for me. 

I think you could also remove 
`property OnColumnChange: TColumnChangeEvent read FOnColumnChange write FOnColumnChange;`
and
`procedure DoColumnChange(Column: TColumnIndex; Visible: Boolean); virtual;`
from `TVTHeaderPopupMenu` because it is not called from anywhere.

Thanks for your time.
