### ISSUE TITLE
Possible typecast problem in VirtualTrees.StyleHooks.pas

### ISSUE THREAD

**Issue by luebbe** [JAM-Software/Virtual-TreeView#1031]
Hi Folks, I just came accross this discussion in the Delphipraxis forum:
https://en.delphipraxis.net/topic/4825-range-check-error-erangeerror/
The error may be caused by casting to integer insterad of WPARAM in a PostMessage call.
VirtualTrees.StyleHooks.pas has two of these dangerous calls. Just wanted to drop a note.

**Comment by joachimmarder** [comment]
@luebbe : Thank you for pointing this out!

**Comment by joachimmarder** [comment]
The original wasn't from me and casted `SmallPoint` to  `Integer`  (since `SmallPoint` has a fixed size of 32Bit as far as I know, I don't think anything could go wrong here). 

I am now casting like this: `WPARAM(UInt32(SmallPoint(`

@luebbe: I would appreciate a review of this cast.

**Comment by luebbe** [comment]
Looks good to me.
I'm with you that probably nothing would have gone wrong, because the values could never enter the danger zone.
TSmallpoint contains two SmallInt, which are Int16.
