### ISSUE TITLE
VT 7.5 can't be installed on CBuilder 10.3.3

### ISSUE THREAD

**Issue by mercedwang** [JAM-Software/Virtual-TreeView#1033]
Because no package project file for CBuilder 10.3 exists, I have to use package project files for CBuilder 10.2. However when I try to build VirtualTreesCR.cbproj in Win32, the following link error encountered:
[ilink32 Error] Error: Unresolved external 'OpenThemeDataForDpi' referenced from C:\USERS\PUBLIC\DOCUMENTS\EMBARCADERO\STUDIO\DELPHICOMP\VIRTUALTREEVIEW\PACKAGES\CBUILDER 10.2\RELEASE\VIRTUALTREES.OBJ
[ilink32 Error] Error: Unable to perform link
Failed

BTW VT 7.4 can be installed on CBuilder 10.3.3 successfully by using package project files for CBuilder 10.2.

**Comment by joachimmarder** [comment]
> Because no package project file for CBuilder 10.3 exists

Yes, for years I did not succeed in finding a volunteer who takes care of the C++ Builder stuff. But I don't think the project file matters for your problem.

> BTW VT 7.4 can be installed on CBuilder 10.3.3 successfully 

The reason is most likely that V7.4 did not use `OpenThemeDataForDPI()`.

> Error: Unresolved external 'OpenThemeDataForDpi' 

There are two possible reasons for this error:

1. `uxtheme.h` is not included in the build
2. `OpenThemeDataForDPI()` is missing the Windows API header files, it was introduced with Windows 10 1703.

Reason 1 can be fixed by adding the missing include in line 66 of VirtualTrees.pas. Please give it a try.

**Comment by mercedwang** [comment]
> There are two possible reasons for this error:
> 
> 1. `uxtheme.h` is not included in the build
> 2. `OpenThemeDataForDPI()` is missing the Windows API header files, it was introduced with Windows 10 1703.
> 
> Reason 1 can be fixed by adding the missing include in line 66 of VirtualTrees.pas. Please give it a try.

I insert a line "{$HPPEMIT '#include <uxtheme.h>'}" at line 66, but the link error remains.
It's very strange that VirtualTreesCR.cbproj can be successfully built when target is changed to Win64.

**Comment by joachimmarder** [comment]
You could try if a hello-world project with a call to `OpenThemeDataForDPI()` compiles successfully for Win32.

**Comment by mercedwang** [comment]
> You could try if a hello-world project with a call to `OpenThemeDataForDPI()` compiles successfully for Win32.

Yes. I created a simple app which calls 'OpenThemeDataForDPI()', which compiles successfully on Win64 but gets the same error on Win32. I found this API function is imported in uxtheme.lib/uxtheme.a . So I tried to add '#pragma comment(lib, "uxtheme")' then comiles successfully on both platforms. Then I add the same line into VirtualTreesCR.cpp in VT 7.5 too now the package can be installed on C++Builder 10.3 successfully!  ;-)

**Comment by joachimmarder** [comment]
OK, I added this link demand using a `$HPPEMIT` statement in `VirtualTrees.pas`.

**Comment by mercedwang** [comment]
> OK, I added this link demand using a `$HPPEMIT` statement in `VirtualTrees.pas`.

I'm sorry to say that that inserting the $HPPEMIT line into 'VirtualTrees.pas' is not enough. The reason is that the link comment is needed not only in the app which includes 'VirtualTrees.hpp', but also in the link stage of VT package itself. One of the following 2 methods is needed:
1) Add '#pragma comment(lib, "uxtheme")' into 'VirtualTreesCR.cpp';
2) For 'VirtualTreesCR.cbproj': add 'uxtheme.dll;' into <ILINK_DelayLoadDll> in line 60, and insert 'LibFiles' items for uxtheme.lib and uxtheme.a at line 142.
I prefer method 2), because it's consistent with the import of 'shell32.lib/shell32.a', and OpenThemeDataForDPI() needs delay-loading indeed.

**Comment by joachimmarder** [comment]
Thank you for suggesting the changes. I would appreciate a review and test of the changes.
