### ISSUE TITLE
Incorrect size of + - images for many Vcl Styles

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1035]
See for example:
Zircon
![image](https://user-images.githubusercontent.com/1311616/114811705-43fa8680-9db7-11eb-83c1-01447939aa49.png)
Slate Classico
![image](https://user-images.githubusercontent.com/1311616/114811739-58d71a00-9db7-11eb-9dc2-ebbbaeae2882.png)
Vapor
![image](https://user-images.githubusercontent.com/1311616/114812053-ec104f80-9db7-11eb-9eaf-4bc61cd4a1d3.png)
Tablet Dark
![image](https://user-images.githubusercontent.com/1311616/114812092-ff231f80-9db7-11eb-8507-2b5af6d4258a.png)

This is how Tablet Dark should look:
![image](https://user-images.githubusercontent.com/1311616/114812189-2a0d7380-9db8-11eb-81fc-b9d6eea0ae32.png)

The problem is that StyleServices.GetElementSize always returns size 9x9 (the DPI argument is not taken into account).
However a number of styles have images of size 10.  Clearly this is a Vcl  styles bug.

As it stands just using a fixed size 10 (dpi scaled of course) under Vcl styles works well for all styles.

**Comment by joachimmarder** [comment]
>  Clearly this is a Vcl styles bug.

https://quality.embarcadero.com/browse/RSP-33715

**Comment by joachimmarder** [comment]
I commited a workaround. @pyscripter: Could you please give it a try?

**Comment by pyscripter** [comment]
> I commited a workaround. @pyscripter: Could you please give it a try?

Yes that's good.

**Comment by sglienke** [comment]
10 is not enough - this is how the VTV looks in the IDE (notice the cropped bottom and right border)

![image](https://user-images.githubusercontent.com/6238697/115166477-b28b5d00-a0b3-11eb-910f-a49bdd7e6925.png) ![image](https://user-images.githubusercontent.com/6238697/115166485-bf0fb580-a0b3-11eb-81d7-69c556f04b45.png)

With 11 it looks fine.

**Comment by joachimmarder** [comment]
Thanks, @sglienke, I changed this accordingly. Commit messages unfortunately had a type in the issue number.

**Comment by luebbe** [comment]
> 10 is not enough - this is how the VTV looks in the IDE (notice the cropped bottom and right border)
> 
> ![image](https://user-images.githubusercontent.com/6238697/115166477-b28b5d00-a0b3-11eb-910f-a49bdd7e6925.png) ![image](https://user-images.githubusercontent.com/6238697/115166485-bf0fb580-a0b3-11eb-81d7-69c556f04b45.png)
> 
> With 11 it looks fine.

@sglienke You make me looking forward to an update of TestInsight now ;)

**Comment by sglienke** [comment]
Whooops, TEASER! 😉
