### ISSUE TITLE
Expand icons like in the IDE

### ISSUE THREAD

**Issue by sglienke** [JAM-Software/Virtual-TreeView#1036]
I recently implemented drawing of the expand icons like they are done in the IDE since 10.3.

I used the OnPrepareButtonBitmaps event and called the following routine on the bitmaps - maybe it's useful for anyone or you can integrate this into the component somehow.

```
  procedure DrawArrow(bitmap: TBitmap; color: TColor; expanded: Boolean);
  const
    Size: TRect = (Left: 0; Top: 0; Right: 12; Bottom: 12);
    ArrowPoints: array[Boolean, 0..5] of TPoint = (
      ((X:3; Y:1), (X:8; Y:6), (X:3; Y:11), (X:4; Y:11), (X:9; Y:6), (X:3; Y:0)),
      ((X:1; Y:3), (X:6; Y:8), (X:11; Y:3), (X:11; Y:4), (X:6; Y:9), (X:0; Y:3))
    );
  var
    canvas: TCanvas;
  begin
    bitmap.SetSize(Size.Width, Size.Height);
    canvas := bitmap.Canvas;
    canvas.FillRect(Size);
    canvas.Pen.Color := color;
    canvas.Pen.Width := 1;
    canvas.Polyline(ArrowPoints[expanded]);
  end;
```

For the color I used `StyleServices.GetSystemColor(clGrayText);` which is not 100% the same color as in the IDE but close enough and I did not care to look further. Also, the IDE draws the icon a little darker when the line is being selected which seems to not be possible with the bitmaps provided to the event.

**Comment by joachimmarder** [comment]
Thanks @sglienke for this code. Unfortunately it does not support dpi-scaling. So it cannot be used out-of-the-box in normal apps and RAD Studio 10.5.

It would be good if the IDE theme supplies a `tcbCategoryGlyphClosed` / `tcbCategoryGlyphOpened` style element, which is what we normally use.

I added the code as `VirtualTrees.StyleHooks.TVclStyleScrollBarsHook.DrawExpandArrow()`.
