### ISSUE TITLE
Add sdNone to TSortDirection and provide optional support for this in sorted columns

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1037]
In some applications containing a grid there are three sort options for a columns:

1. Sort ascending
2. Sort descending
3. Do not sort/use original sort order as it was when the data had been loaded

This would be good to have in my eyes for multi column sorting as well (#441).

If implemented for single column sort it should be tied to some new option which controls
whether the DoNotSort state exists or not. If implemented for multi column sorting this should 
be a new option for the settings of each column.

**Comment by joachimmarder** [comment]
@MHumm: What would be the difference of `sdNone` and not calling the `Sort()` method? This is how we handle this case.

**Comment by MHumm** [comment]
One could iterate through the enumeration...

**Comment by joachimmarder** [comment]
> use original sort order as it was when the data had been loaded

I don't think this original sort order is available anymore, once the tree has been sorted. So the only option to achieve this is not to call `Sort()`.

> One could iterate through the enumeration...

To do what?

**Comment by joachimmarder** [comment]
No further input from reporter, so I am closing this issue for now.

**Comment by MHumm** [comment]
Ok, I achieved what I wanted by some "manual" implementation now and it works. The data needs to know its original sort order.
