### ISSUE TITLE
Refactoring - removed friend field access.

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#1039]
A few years back I made a start on refactoring this code, in the hope that it would be easier to work on. I'd like to continue that effort. This is such a fantastic control, but the code is incredibly difficult to navigate (not helped by the delphi IDE either!). 

The first thing that needs to be fixed is the heavy use of friend access to private fields and methods of other classes - as this really makes extracting classes etc impossible.  

I'll focus on fields first. A quick grep shows 500+ instances. Many of them already have properties that could have been used (sot it's literally a delete 1 char refactor, remove the F).  

FWIW, there is a lot that can be moved out to separate files (header, columns, options etc) once the dependencies between the classes is cleaned up. 

I'll push a PR for consideration soon.

**Comment by joachimmarder** [comment]
PR #1040 has been merged.
