### ISSUE TITLE
Header height scaling on dynamically created trees not correct

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#1043]
When a VT is on a dynamically created frame, and the parent form is on a monitor with higher than 96 dpi when the frame is created, the header height is scaled incorrectly. 

If the form is on a 96 dpi monitor when the frame is created, it's fine. 

ChangeScale is called when created on the high dpi screen, as you would expect, however the calculated header height turns out larger than if it was created on 96dpi and then moved across. 

I spent a while trying to figure this out but got nowhere. 

Sample app shows the issue. In the form create I set the form position to the high dpi monitor - click on button 1 to create the frame with the VT (adds it to a page control). Notice the header height. Move the window to a normal dpi monitor and click the button again to create another instance (on a new tab) and then move the form back and forth and compare the scaling of the headers. 

Button 2 creates a grid control - I added that just to see if this issue was a general vcl problem (it's not) or specific to VT (it is). 

Any ideas? 

[VTScaling.zip](https://github.com/JAM-Software/Virtual-TreeView/files/6424959/VTScaling.zip)

**Comment by vincentparrett** [comment]
This issue is caused by TVTHeader.AutoScale being called from FontChanged and StyleChanged, which are called before ChangeScale, so the header is getting scaled multiple times. 

It seems to me like the autoscale code is there to deal with scaling in older versions of delphi that didn't handle dpi changes.  Simply commenting out the calls to AutoScale solves the problems as far as  I can tell. It will scale correctly when moving between monitors, when changing themes, and when changing the monitor font size.

**Comment by vincentparrett** [comment]
To solve this issue here (with 10.4.2) I did the following

````delphi
procedure TVTHeader.AutoScale(isDpiChange: Boolean);
var
  I          : Integer;
  lMaxHeight : Integer;
begin
  if (toAutoChangeScale in TBaseVirtualTreeCracker(Tree).TreeOptions.AutoOptions) and not isDpiChange then
...
````

````delphi
procedure TVTHeader.FontChanged(Sender : TObject);
begin
  inherited;
  {$IF CompilerVersion < 31}
  AutoScale(false);
  {$ENDIF}
end;

````

````delphi
procedure TVTHeader.StyleChanged();
begin
  {$IF CompilerVersion < 31}
  AutoScale(False); //Elements may have changed in size
  {$ENDIF}
end;
````
I have not tested this with earlier versions.

**Comment by joachimmarder** [comment]
I think the order in which the methods get called during dpi scaling has changed in 10.4, which might be the reason for the misbehavior.

**Comment by vincentparrett** [comment]
Thanks.
