### ISSUE TITLE
Scrollbar Increment oddity

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#1044]
I was looking into something else today and came across this 

````delphi
procedure TBaseVirtualTree.WMHScroll(var Message: TWMHScroll);
...
    SB_LINELEFT:
      SetOffsetX(FOffsetX + RTLFactor * FScrollBarOptions.HorizontalIncrement);
    SB_LINERIGHT:
      SetOffsetX(FOffsetX - RTLFactor * FScrollBarOptions.VerticalIncrement); <<<????
````
Surely that VerticalIncrement should be HorizontalIncrement? I guess this wouldn't affect many as most people probably just leave them at their default values which are the same.

**Comment by joachimmarder** [comment]
> Surely that VerticalIncrement should be HorizontalIncrement? 

I never looked at this code before, but only HorizontalIncrement seems to make sense here. Thanks for submitting the PR.
