### ISSUE TITLE
Unloading .dll's with VirtualTrees in them.

### ISSUE THREAD

**Issue by darinamdata** [JAM-Software/Virtual-TreeView#1046]
Hi,
Been using VirtualTrees for well over a decade. Recently upgraded from Delphi XE2 to Sindney 10.4.1.  Everything seemed fine until the latest release of my enterprise software.  There is a problem with with VirtualTrees still cleaning up after a form is destroyed. Once a form is closed and all cleanup is done the .dll unloads and then there will be an AV (in 7.4 VirtualTrees, in 7.5 the application disappears).  This does not happen every time, it usually takes multiple attempts. Plus, it occurs more often with users' running on  terminal servers where they do not have the resources and speed of a stand alone machine. This was testing to ensure the culprit was VirtualTrees. We created a .dll with a form with just a TVirtualStringGrid on it. No other code. The call stack is very vague (since the .dll is gone) but there is a reference to VirtualTrees.WorkerThread still working in it and MY.exe (32 bit) does not have a VirtualTree in it:

exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 17890163 in module 'MY.exe'. Execution of address 17890163.

>thread $81a8 (TWorkerThread):
17890163 +00 ???
004706df +2b MY.exe      madExcept HookedTThreadExecute
004705c5 +0d MY.exe      madExcept CallThreadProcSafe
0047062a +32 MY.exe      madExcept ThreadExceptFrame
75fd343b +10 kernel32.dll           BaseThreadInitThunk
 created by thread $3da4 at:
5017d564 +18 rtl270.bpl   System    Classes.TThread.Create
......
......
thread $2cec (TWorkerThread):
77a5f8ca +0e ntdll.dll                                       NtWaitForSingleObject
76bf1623 +92 KERNELBASE.dll                                  WaitForSingleObjectEx
75fd118f +3e kernel32.dll                                    WaitForSingleObjectEx
75fd1143 +0d kernel32.dll                                    WaitForSingleObject
005ff003 +23 MY.exe        VirtualTrees.WorkerThread 150 +4 TWorkerThread.Execute
004706df +2b MY.exe        madExcept                        HookedTThreadExecute
004705c5 +0d MY.exe        madExcept                        CallThreadProcSafe
0047062a +32 MY.exe        madExcept                        ThreadExceptFrame
75fd343b +10 kernel32.dll                                    BaseThreadInitThunk
 created by thread $3da4 at:
>5017d564 +18 rtl270.bpl     System                           Classes.TThread.Create

We inserted a hack into the TBaseVirtualTree destructor to alleviate the problem, but a real fix would be appreciated.

//----------------------------------------------------------------------------------------------------------------------
destructor TBaseVirtualTree.Destroy;

begin
......
......
  FSelectedHotPlusBM.Free;
  FSelectedHotMinusBM.Free;

  Sleep(100); //HACK! Somehow it is falling through to here before all cleanup is done. 100 is a magic number but wanted to give it enough time to clean up.

  inherited;
end;

**Comment by joachimmarder** [comment]
Please try if the latest code from master solves the problem, it contains on change in this area compared to V7.5, see issue #1001.

> This was testing to ensure the culprit was VirtualTrees. We created a .dll with a form with just a TVirtualStringGrid on it. No other code.

Can you please supply this project with repro steps?

**Comment by joachimmarder** [comment]
I am closing this issue as no repro steps were provided and maybe the latest version solves the issue.
