### ISSUE TITLE
Multiline hints draws incorrectly

### ISSUE THREAD

**Issue by TommySlokky** [JAM-Software/Virtual-TreeView#1048]
I have a peculiar problem. I have a cell with two lines of text. But when the default (I do nothing custom) hint window shows it draws the lines too far down its hint window. What could cause this?

As far as I can tell the overall height of the hint window appears correct, it is simply the placement of the text that seems off.

ATreeView.OnGetText  := retrieves line1 + linebreak + line2
ATreeView.OnGetHint := retrieves the above
ATreeView.OnDrawText := draws text correctly in cells (and draws first line at CellRect Top 0 )

I will upload screenshot first. If you need a more complete example I will try make it.

![example](https://user-images.githubusercontent.com/3811494/121743459-ad6deb80-cb01-11eb-9471-cf66ad2fbac6.png)

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting bugs on the porject homepage. Please include the version of Virtual TreeView and Delphi, and a sample projects or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by TommySlokky** [comment]
At the time of submission it was the newest sources available (within 24 hours) and XE4 but I will get back with exact version.

I will try see if I can recreate the problem in one of the sample projects. I will try do it tonight

**Comment by TommySlokky** [comment]
Still working on it. 

So far tried in Advanced>WindowsXPStyleDemo:
1)

 OnMeasureItem random nodeheight and in FormCreate added
```
  xptree.treeoptions.MiscOptions := xptree.treeoptions.MiscOptions + [toVariableNodeHeight];
  xptree.ReinitNode(nil, True);

```

2)
Different newlines in OnGetText handler (XPTreeGetText)



So far tried in in my own software:

1)
Exit after setting DefaultDraw := True in OnDrawText handler


Problem driving me nuts, but I am document my attempt at duplicating the issue in case other persons stumble into this at a later point. (And if I do not solve it they have a starting point.)

**Comment by TommySlokky** [comment]
**There**

In
procedure TWindowsXPForm.FormCreate(Sender: TObject);

Add
XPTree.HintMode := hmTooltip;

-----


And problem occurs in XE4 Virtual Treeview 7.5 from 11th June 20201

I can try in newest version. If I recall the problem is also there in the Lazarus port, but I will check and submit for that as well.


![screenshot](https://user-images.githubusercontent.com/3811494/125370412-afd09900-e37e-11eb-8c43-e08706ac8d53.png)

**Comment by joachimmarder** [comment]
`TWindowsXPForm.XPTreeGetHint()` uses a multiline hint but does not set `LineBreakStyle` to `hlbForceMultiLine`. Doing so should fix the issue.

But I will add an auto-detection of line-breaks to `TVirtualTreeHintWindow.CalcHintRect()` as well.

**Comment by joachimmarder** [comment]
Just noticed one more thing: According to documentation `hmTooltip` is meant to show the text of the node if it isn't already fully shown. But in this case completely different text is shown, so the display rect may be unexpected, which is not a bug.
