### ISSUE TITLE
Removing columns leads to wrong rendering and column reordering

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#1049]
Hello,

Using the latest GIT content, we are seeing some strange behavior when removing a column that is not the last one.
Here is a sample application: [RemoveGridColumn.zip](https://github.com/JAM-Software/Virtual-TreeView/files/6783551/RemoveGridColumn.zip)

And here is the first thing we noticed:

1. Enter 1 in the position field
2. Click on the "Remove position" button

We would have expected Column "2nd" to disappear but instead we get this:
![image](https://user-images.githubusercontent.com/1314739/124904904-c628ce80-dfe5-11eb-9697-05adcfa8bf1f.png)

Then we have this even weirder behavior:

1. Enter "Test" in the name field
2. Enter 4 in the position field
3. Click the "Add" button
4. Enter 1 in the position field
5. Click the "Remove position" button

Once again we would have expected Column "2nd" to disappear but instead we get this even weirder rendering:
![image](https://user-images.githubusercontent.com/1314739/124904968-d5a81780-dfe5-11eb-8c77-24286008fb97.png)

Investigating a bit, we found that removing the code introduced by commit https://github.com/JAM-Software/Virtual-TreeView/commit/0a419f138ef5e615bb919e6e9a5d3db937c785cb fixes the issue.
The demo project has range checking activated and we do not get range check exceptions with BeginUpdate/EndUpdate activated.

The reporter for issue https://github.com/JAM-Software/Virtual-TreeView/issues/959 mentioned in a later comment that the fix introduces display issues which are quite similar to those reported here.

I thus believe the code introduced in `TVirtualTreeColumns.Notify` should be at least reviewed, if not completely removed.

**Comment by obones** [comment]
FWIW, I tried reversing the order of the loop in side `TVirtualTreeColumns.Notify`, making it go from `Count - 1` down to `0`.
While it fixed the first set of steps above, it changed the result for the second set:
![image](https://user-images.githubusercontent.com/1314739/124917549-435b4000-dff4-11eb-8a09-455fa4a81188.png)

**Comment by joachimmarder** [comment]
Could you please try again with latest source from master?

**Comment by antsiparovich** [comment]
Hi. I'm 'intensely' working with columns :) - change visibility, positions etc. 
And found my application can freezes in **TVirtualTreeColumns.GetPreviousVisibleColumn**
I reproduced the problem on a test case
[1.zip](https://github.com/JAM-Software/Virtual-TreeView/files/6891090/1.zip)
Installed VirtualTree 7.6 with [249f2ab](https://github.com/JAM-Software/Virtual-TreeView/commit/249f2abc8f1d5135e7c99b55723c00a60b9639a0)

**Comment by joachimmarder** [comment]
> Hi. I'm 'intensely' working with columns :)

Well, seems to be a difficult area. Every fix seems to introduce a new issue.

Thanks for the test project. I noticed that `TVirtualTreeColumns.Notify()` is called two times for a deleted column (once for `cnDeleting` and once for `cnExtracting`). Now that this method works correctly, the second call produces unexpected results. @antsiparovich: Please try if removing `cnExtracting` in `TVirtualTreeColumns.Notify()` fixes your issues.

**Comment by antsiparovich** [comment]
> Please try if removing cnExtracting in TVirtualTreeColumns.Notify() fixes your issues.

It works. Can I use this fix issue before v. 8.0 is released?
And from Embarcadero help for `System.Classes.TCollection.Notify`

> As implemented in TCollection, Notify calls Added when Action is cnAdded and calls Deleting when Action is cnDeleting. **TCollection ignores the cnExtracting action**. Descendant classes can override Notify to modify this behavior.

**Comment by joachimmarder** [comment]
> Can I use this fix issue before v. 8.0 is released?

Yes, it is now also part of the V7_Stable branch.
