### ISSUE TITLE
AutoFitColumns and BeginUpdate

### ISSUE THREAD

**Issue by JanikSachs** [JAM-Software/Virtual-TreeView#1050]
While using BeginUpdate the AutoFitColumns animation still takes time.
In my Example with 1 Node and 2 Headers with some Text in them it took 999923 ms.
What I expected was that the Animation would be supressed by BeginUpdate.
I believe in the Version 5 the behavior differs.
Using the first Parameter Animated with the value false the Animation takes no time as expected.

```
void __fastcall TForm1::VirtualStringTreeExpanded(TBaseVirtualTree *Sender, PVirtualNode Node)
{
   Sender->BeginUpdate();
   Sender->Header->AutoFitColumns();
   Sender->EndUpdate();
}
```
I am using RAD Studio with c++.

**Comment by joachimmarder** [comment]
The first parameter of `AutoFitColumns()` is `Animated` with the default value `True`. Passing `False` should achieve the desired behavior. I don't think it is a good idea to let `BeginUpdate()` implicitly override an explicit method parameter.

**Comment by joachimmarder** [comment]
OK, I found a way so that the value for the optional parameter `Animated` is determined in a smarter way, by taking the updating state of the tree into account.
