### ISSUE TITLE
Memory leak in Cut&Paste nodes [Delphi 7 + VT 5.5.3]

### ISSUE THREAD

**Issue by salvadorbs** [JAM-Software/Virtual-TreeView#1052]
Hi all, I am using Delphi 7 + VirtualTree 5.5.3 and I have discovered a memory leak when trying to copy and paste a node. The OLE demo has this problem.

Steps:
1. Use fastmm4 and enable reporting
2. Run the demo OLE
3. Cut and paste (using hotkeys) any node from Tree2 (the right tree)
4. Exit app

Result:
![immagine](https://user-images.githubusercontent.com/3731721/126369592-d2e73e8d-1c14-4564-b39d-e18615320820.png)

I am well aware of using extremely old VT and Delphi, but I wanted to understand if recent versions of VT also have the same problem (right now I can't do the same test with recent versions). Doing a quick version comparison (5.5.3 vs branch Master), it seems to me that this piece of code hasn't changed that much in the last few years.

Thanks a lot to everyone.

**Comment by joachimmarder** [comment]
After setting the global `ReportMemoryLeaksOnShutdown := True;` in RAD Studio 10.4 I also see the mem leak. It origins from `TBaseVirtualTree.CutToClipboard()`. Since `TVTDataObject` is a ref counted data interfaced object, I don't see anything that is wrong with the code. Any comments are welcome.

**Comment by joachimmarder** [comment]
The mem leak is no longer reported when I clear the clipboard before I close the application. So I guess it is partly by design of Windows that this clipboard object is freed after it was removed from the clipboard. So this is not a true leak.
