### ISSUE TITLE
Styles: ContentToRTF does not respect the background color

### ISSUE THREAD

**Issue by utzelberlin** [JAM-Software/Virtual-TreeView#1054]
When using a themed dark style, the correct font color is used in ContentToRTF, but not the correct background color. Thus, white font appears on a white background.

In ContentToHTML, both colors are set correctly.

**Comment by joachimmarder** [comment]
I tried to replicate the issue using the `Advanced` demo project, enabled the dark theme  "Glow" in the Project Options, opened the second page "General abilities" and saved the tree as RTF using the button on the top right. The result looks OK to me:
![grafik](https://user-images.githubusercontent.com/10615289/127733281-dad1ce33-00f7-43ae-b1ae-04baf4836993.png)

**Comment by utzelberlin** [comment]
Sorry, after a lengthy search I have now identified the package "vcl-styles-utils" as the culprit.  When this package is active, the font color is output incorrectly. Strangely enough only in ContentToRTF.
