### ISSUE TITLE
Could not compile the VirtualTrees components with RAD Studio 10.3 Rio and 10.4 Sydney

### ISSUE THREAD

**Issue by Jeanmilost** [JAM-Software/Virtual-TreeView#1055]
Hello,

Compiling the VirtualTrees components with RAD Studio 10.3 Rio and 10.4 Sydney, I faced the following issues:

In **10.3 Rio**, I needed to add the following include in VirtualTrees.Header.pas:
`
  {$IF CompilerVersion >= 33}
    System.Generics.Collections,
  {$IFEND}
`

In **10.4 Sydney**, I needed to modify the VirtualTreesD.dpk in the following manner:
`{$LIBSUFFIX AUTO} => {$LIBSUFFIX '270'}`

and modify the VirtualTreesD.dproj in the following manner:
`<DllSuffix>$(Auto)</DllSuffix> => <DllSuffix>270</DllSuffix>`

Can you please fix that?

Regards

**Comment by joachimmarder** [comment]
I added `System.Generics.Collections` to the uses of the unit `VirtualTrees.Header`.

10.4 Sydney officially supports `{$LIBSUFFIX AUTO}` and I cannot see a problem under 10.4.2. Please include the exact version number and more detailed repro steps.

**Comment by Jeanmilost** [comment]
My current version is: Embarcadero® RAD Studio 10.4 Version 27.0.37889.9797

I have also the following third-party installed products:
- GExperts (experimental)
- CnPack IDE Wizards 1.2.0.1035

My Windows version is: Windows 10 Professional (Version 10.0, Build 19043, 64-bit edition)

I not used any particular protocol, I just opened the VirtualTreeView.groupproj in my RAD Studio application, I changed the build configuration to Release and the target platforms to Windows 32-bit in the both projects, I built the VirtualTreesR270.bpl one, and I tried to install the VirtualTreesDS(Auto).bpl one. This gave me the following error:
[Fatal Error] Can't load package VirtualTreesD$(Auto).bpl. The system cannot find the file specified

And I applied the above described process to fix that issue.

**Comment by Jeanmilost** [comment]
About the 10.3 Rio issue, I failed to compile the project until I added the above mentioned include. I got several errors saying me that several objects were not declared. I added an ifdef because I had no issues with the previous versions I tested, which were: XE7, XE8, 10.0 Seattle, 10.1 Berlin and 10.2 Tokyo. I have all these compilers installed side by side on my working computer, plus 10.3 Rio and 10.4 Sydney, for your info.

**Comment by joachimmarder** [comment]
Well, it doesn't make much sense that it compiles in 10.4 and 10.2 and before, but fails for 10.3. But since I have no 10.3 for testing at hand, I added this uses, which should be uncritical even if not used. I generally avoid $IFDEFs if possible.

**Comment by joachimmarder** [comment]
> My current version is: Embarcadero® RAD Studio 10.4 Version 27.0.37889.9797

In this version `{$LIBSUFFIX AUTO}` seems to be buggy, updating to 10.4.2 should solve the problem for you.

**Comment by Jeanmilost** [comment]
Ok, thank you very much
