### ISSUE TITLE
Event for the automatically generated Header PopupMenu clicks

### ISSUE THREAD

**Issue by utzelberlin** [JAM-Software/Virtual-TreeView#1056]
Hello,

is it possible to give us a TreeView event after clicking on a MenuItem from the automatically generated PopupMenu of header columns?

I use hoAutoColumnPopupMenu in Header.Options and get a nice automatically generated PopupMenu. This and switching columns works fine. But to save the settings that the end user has chosen in this menu (visible/invisible columns), there is no matching event for these clicks.

The DoColumnVisibilityChanged event does react to the visibility change, but it also reacts to any programmatic change.

I only want to react to the changes made by the end user so that I can save their settings. I think this would be useful for other users of the TreeView as well.

Best regards

**Comment by joachimmarder** [comment]
> The DoColumnVisibilityChanged event does react to the visibility change, but it also reacts to any programmatic change.

In a well-designed code, it should not matter how the change was made. If truly needed, you can use a member variable in your form to signal that the event should not be processed, or you can temporarily detach the event handler.

I think such an event in the virtual tree control is too far away from the `TVTHeaderPopupMenu` class. If something is missing in the `TVTHeaderPopupMenu` class itself, I will be glad to add it.

**Comment by utzelberlin** [comment]
I think the proposal is consistent with the virtual paradigm of the VirtualTreeview component, and thus the best programming style, if from the built-in popup menu an event is provided in the main component to respond to a user's manual adjustments. Fiddling around with variables or event assignments to make/break inappropriate events appropriate at all deviant moments, on the other hand, I think is patchwork.

I wouldn't know how to override the TVTHeaderPopupMenu's OnClick handling in the current state to implement this feature in a derived component. I would have to override the entire TVirtualTreeColumns.HandleClick method, which would only be error prone when changes are made in future updates.

The solution to the issue raised would be very easy for you to implement and adds value to all users by retrofitting a missing feature.

Unit "VirtualTrees.Header":
```
Line 225: 
procedure HeaderPopupMenuColumnChange(const Sender : TObject; const Column : TColumnIndex; Visible : Boolean); virtual;

Line 4590: 
TVTHeaderPopupMenu(FColumnPopupMenu).OnColumnChange := HeaderPopupMenuColumnChange;`

Line 4619:
procedure TVirtualTreeColumns.HeaderPopupMenuColumnChange(const Sender : TObject; const Column : TColumnIndex; Visible : Boolean);
begin
  TBaseVirtualTreeCracker(Sender).DoColumnManualVisibilityChanged(Column, Visible);
end;
```

Unit "VirtualTrees":
```
Line 1240:
FOnColumnManualVisibilityChanged: TColumnChangeEvent;

Line 1555:
procedure DoColumnManualVisibilityChanged(const Column: TColumnIndex; Visible: Boolean); virtual;

Line 1878:
property OnColumnManualVisibilityChanged: TColumnChangeEvent read FOnColumnVisibilityChanged write FOnColumnVisibilityChanged;

Line 2516:
property OnColumnManualVisibilityChanged; 

Line 11306:
procedure TBaseVirtualTree.DoColumnManualVisibilityChanged(const Column: TColumnIndex; Visible: Boolean);
  // Triggers the OnColumnManualVisibilityChanged event.</summary>
begin
  if Assigned(FOnColumnManualVisibilityChanged) then
    FOnColumnManualVisibilityChanged(Self, Column, Visible);
end;
```

**Comment by joachimmarder** [comment]
> I would have to override the entire TVirtualTreeColumns.HandleClick method, which would only be error prone when changes are made in future updates

No, you can use the event `TVTHeader.OnGetPopupMenu` to supply a popup menu that suits you. Let me know if anything needs to be changed in `TVTHeaderPopupMenu` so that you can achieve your task with your derived class.
