### ISSUE TITLE
Expand/Collapse buttons disappeared if BottomSpace is not 0

### ISSUE THREAD

**Issue by edwinyzh** [JAM-Software/Virtual-TreeView#1057]
I discovered that the virtual treeview's Expand/Collapse buttons are disappeared if `BottomSpace` is not 0. There might be other issues related to this property too...

**Comment by joachimmarder** [comment]
I cannot confirm this. I opened the `Advacned` sample project and in unit `GeneralAbilitiesDemo` I set the property `BottomSpace` to 3:
![2021-08-13 15_48_39-Advanced - Delphi 10 4 - GeneralAbilitiesDemo](https://user-images.githubusercontent.com/10615289/129370874-a13b681b-7695-4824-b189-25978f3900f6.png)

After starting the project, the expand / collpase buttons were visible:
![2021-08-13 15_32_04-Virtual Treeview features demo](https://user-images.githubusercontent.com/10615289/129370719-cd74dec2-51ef-481a-bf15-3192c7825915.png)

**Comment by joachimmarder** [comment]
@edwinyzh: Please respect our guidelines for submitting bugs on the project homepage. Please include the version of Virtual TreeView and Delphi, and a sample projects or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by edwinyzh** [comment]
Sorry, I somehow missed the github notification after the github front page no longer including recent updates for issues I participate...
I'll try to provide a demo that reproduces the issue.

**Comment by joachimmarder** [comment]
> I'll try to provide a demo that reproduces the issue.

@edwinyzh: Did you succeed in ding so, or may I close the issue?

**Comment by joachimmarder** [comment]
After 5 months with no progress in providing repro steps, I am closing this issue.
