### ISSUE TITLE
toCenterScrollIntoView option causes Access Violation when editing nodes

### ISSUE THREAD

**Issue by borisneubert** [JAM-Software/Virtual-TreeView#1058]
This issue occured after updating VirtualTreeview to current V7_stable commit d31647022525ae90c12071ee63ebffa596949afa from 7.4.

Coming from` TBaseVirtualTree.EditNode DoEdit` (line 26869) is called. In `TBaseVirtualTree.DoEdit` `FFocusedNode `is still set. If `toCenterScrollIntoView in FOptions.SelectionOptions` and only in certain cases,` ScrollIntoView()` in line 20037 kills the focus such that `FFocusedNode `is `nil `when returning. Any subsequent processing that relies on the assertion in line 26856 that the edited note is assigned will fail.

Workaround: turn `toCenterScrollIntoView `option off.

**Comment by joachimmarder** [comment]
>  ScrollIntoView() in line 20037 kills the focus 

Somehow `ScrollIntoView()` does not cover line 20037 in my source code. I would be good to know where exaxctly `ScrollIntoView()` kills the focus.

> Coming from TBaseVirtualTree.EditNode DoEdit

So `EditNode()` is called with the parameter `Node` being `nil`? If so, from where was `EditNode()` called?

Please respect our guidelines for submitting bugs on the project homepage. Please include a sample project or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by borisneubert** [comment]
I was referring to [this file](https://github.com/JAM-Software/Virtual-TreeView/blob/d31647022525ae90c12071ee63ebffa596949afa/Source/VirtualTrees.pas).

The issue should also occur in the PropertiesDemo of the Advanced demo but it does not. I therefore fully stepped through the code and found that I shot me in the foot with setting `FocusedNode `to `nil `in the `OnScroll `event handler of the tree and calling `EndEditNode`. This is to stop editing if the user moves the edited property out of view. It has been working well over the last 10 years but some internal change in VirtualTrees.pas obviously broke that.

This is embarassing. Sorry for bothering you. I guess this can be closed.
