### ISSUE TITLE
"VirtualTrees.Types.pas" is lost in "Packages\CBuilder 10.X\VirtualTreesCR.cbproj"

### ISSUE THREAD

**Issue by mercedwang** [JAM-Software/Virtual-TreeView#1059]
I think "VirtualTrees.Types.pas" should be added to "Packages\CBuilder 10.X\VirtualTreesCR.cbproj". If it is lost, the following problem is encountered in C++Builder 10.4.2:
1) Create a new C++Builder VCL project and add a TVirtualStringTree or TVirtualDrawTree control to the form,
2) Disable "Packages > Runtime Packages > Link with runtime packages" and "C++ Linker > Link with Dynamic RTL" in Project Options
3) Build the project and we will get a link error "VirtualTrees.Types.obj not found"

**Comment by mercedwang** [comment]
However it seems that this problem does not exist in C++Builder 10.3.3. So strange.

**Comment by joachimmarder** [comment]
I think  "VirtualTrees.Types.pas" should be part of the project files, this was simply forgotten for C++ Builder as there is no official maintainer for C++ Builder. I just commited the chnages, please give them a try - thanks.
