### ISSUE TITLE
Support for Delphi 11

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1060]
As per title.

My suggestion:

1.  Rename folder Packages\RAD Studio 10.4 to Packages\RAD Studio 10.4+
2.  For some reason LIBSFFIX AUTO is only set in the design package VirtualTreesD.  Change LIBSFFIX to AUTO in the runtime package and project.
3. Update Installation instructions

That is all needed.

**Comment by joachimmarder** [comment]
> For some reason LIBSFFIX AUTO is only set in the design package VirtualTreesD. Change LIBSFFIX to AUTO in the runtime package and project.

I cannot confirm. Can you please provide more details?

**Comment by pyscripter** [comment]
The above two commits were applied to the V7 stable branch but not the master.

In the master branch you still have the "RAD Studio 10.4" folder.  Inside that folder, https://github.com/JAM-Software/Virtual-TreeView/blob/master/Packages/RAD%20Studio%2010.4/VirtualTreesR.dpk has the following:

{$LIBSUFFIX '270'}

**Comment by joachimmarder** [comment]
Thanks, should be all fixed now.
