### ISSUE TITLE
'FCheckImages' leaks GDI-Handles when 'FCheckImageKind' is not 'ckSystemDefault'

### ISSUE THREAD

**Issue by lennartjohnen** [JAM-Software/Virtual-TreeView#1062]
Leak happens in 'TBaseVirtualTree' because FCheckImages gets created either way, while only being destroyed when 'FCheckImageKind = ckSystemDefault'. Fixed it locally by only setting 'FCheckImages'  in 'TBaseVirtualTree.CreateWnd' using 'CreateSystemImageSet' when 'FCheckImageKind = ckSystemDefault'.
![Bildschirmfoto 20210913 125838](https://user-images.githubusercontent.com/90446642/133072431-7b45b935-5d9d-4ea4-9aa0-ab7e325bdb48.png)

**Comment by joachimmarder** [comment]
This looks very similar to #987.

Can the issue be replicated with one of the included demo projects?

**Comment by joachimmarder** [comment]
No further information was provided by reported, so I am closing the issue for now.
