### ISSUE TITLE
Access Violation when VCLStyles enabled 

### ISSUE THREAD

**Issue by jdorlon-Quest** [JAM-Software/Virtual-TreeView#1073]
Hello,

  In my case:
  When VCL Styles are enabled.  The error does not occur when VCL Styles are not enabled.
  The TVirtualStringTree has 20 or so columns.   It is on a TFrame which gets created in a form's constuctor.
  
  I got an Access Violation in TBaseVirtualTree.PrepareBitmaps, at this line:
`          Brush.Color := FHeader.Columns[FHeader.MainColumn].GetEffectiveColor`

The weird thing is that FHeader.MainColumn=1, so it should not produce an AV.  However, if I debug, FHeader.Columns.Count=1 at this time, even though at design time there are about 20 columns in this VST.

  Anyway, to fix, I added the indicated line below.  Maybe something else is needed so that the value of FHeader.Columns.Count is correct.

`
procedure TBaseVirtualTree.PrepareBitmaps(NeedButtons, NeedLines: Boolean);
(snip)
  procedure FillBitmap (ABitmap: TBitmap);
(snip)

      if IsWinVistaOrAbove and (tsUseThemes in FStates) and (toUseExplorerTheme in FOptions.PaintOptions) or VclStyleEnabled then
      begin
        if (FHeader.MainColumn > NoColumn) and
           (FHeader.Columns.Count > FHeader.MainColumn) then // ADDED THIS LINE
          Brush.Color := FHeader.Columns[FHeader.MainColumn].GetEffectiveColor
`

**Comment by joachimmarder** [comment]
Which version of Virtual TreeView are you using?

> (FHeader.Columns.Count > FHeader.MainColumn) then // ADDED THIS LINE

Well, `MainColumn` should never be larger than `Columns.Count`. While this added line fixes one symptom, it does not fix the cause.

Can you provide a sample project that allows to replicate the problem?

**Comment by jdorlon-Quest** [comment]
Hi Joachim,

  Version 7.6.0.

I am under a bit of a time crunch and not able to create a demo right now.   When I get more caught up I will try to make a demo.  Sorry about that.

**Comment by jdorlon-Quest** [comment]
OK, you can reproduce it with the attached sample app.

I am building this under Delphi 10.2, 32 bit.
Just run the app and then click the first toolbar button.
The VST is in the FArguments unit.  

[MDISample.zip](https://github.com/JAM-Software/Virtual-TreeView/files/7523043/MDISample.zip)

Thank you for maintaining VirtualStringTree.

**Comment by joachimmarder** [comment]
Thank you, I can replicate the exception now.

What's happening: The DFM is loaded, within that the property `MainColumn` is loaded, then the window handle is created (while the DFM is still loaded), before the `Columns` property was loaded.

**Comment by joachimmarder** [comment]
`TVirtualTreeColumn.SetWidth()` potentially accessed `ClientWidth` of the control, which triggers the creation of the control hanlde, which isn't the best thing happening while havhing partially read the control from the DFM.

We now prevent the creation of the control handle, please check if everything else with the column widths is as expected.
