### ISSUE TITLE
TVTHeader.SetMainColumn is invoked during destruction causes AV in user code [FIX INCLUDED]

### ISSUE THREAD

**Issue by iankrigsman** [JAM-Software/Virtual-TreeView#1079]
I have an application that hooks into various events within **TVirtualStringTree** and owned classes. My code was based on an older commit of VT when **VirtualTrees.pas** contained most of the classes, prior to the separation of units (eg. **VirtualTrees.Header.pas**) mid 2021.

After recently updating to the latest VT code, AVs started appearing in the destruction in a few instances with the `OnFocusChanged` event handler. That is, the AV was occurring in my code when it normally expects the parent to be assigned.

Example stack trace:
```
MyUnit                TMyComponent.DoFocusChange << AV here when not expected to be invoked during destruction
VirtualTrees          TBaseVirtualTree.SetFocusedColumn
VirtualTrees.Header   TVTHeader.SetMainColumn
VirtualTrees.Header   TVirtualTreeColumns.Clear
VirtualTrees.Header   TVTHeader.Destroy
```

Setter `TVTHeader.SetMainColumn` is shown here (**VirtualTrees.Header.pas**, line 826) with the `Tree.FocusedColumn` assignment. I could patch my code as a workaround, but I presume this whole method should be bypassed in this instance. That is, just include a test for csDestroying along with csLoading as indicated.

```
unit VirtualTrees.Header;
<snip>
procedure TVTHeader.SetMainColumn(Value : TColumnIndex);

begin
  if (csLoading in Tree.ComponentState)  
  or (csDestroying in Tree.ComponentState) then   //+++ <<< ADD THIS LINE
    FMainColumn := Value
  else
  begin
    if Value < 0 then
      Value := 0;
    if Value > FColumns.Count - 1 then
      Value := FColumns.Count - 1;
    if Value <> FMainColumn then
    begin
      FMainColumn := Value;
      if not (csLoading in Tree.ComponentState) then    //??? THIS LOOKS REDUNDANT
      begin
        Tree.MainColumnChanged;
        if not (toExtendedFocus in Tree.TreeOptions.SelectionOptions) then
          Tree.FocusedColumn := FMainColumn;   //!!! <<<<<<<< AV WAS TRIGGERED HERE
        Tree.Invalidate;
      end;
    end;
  end;
end;
```

If this looks acceptable then I'd appreciate anyone with write access to apply the change. See also redundant test for csLoading which I expect can be removed.

Cheers, Ian

**Comment by joachimmarder** [comment]
> but I presume this whole method should be bypassed in this instance. 

I agree.

**Comment by iankrigsman** [comment]
That was quick, thanks @joachimmarder !
