### ISSUE TITLE
Problem with compiling on CBuilder 10 TVTColors::TVTColorEnum

### ISSUE THREAD

**Issue by novakalex** [JAM-Software/Virtual-TreeView#1080]
My project compiles on CBuilder RAD Studio 10. I get too many warning as 
[bcc32 Warning] ********.cpp(39): W8006 Initializing const TVTColors::TVTColorEnum with int

My code
VST1->Colors->GridLineColor = clWindowText;

I haven't found a way to get rid of this. Help me please.

Below part of "Virtualtrees.hpp"
====================================================================================
#pragma pack(pop)
#pragma pack(push,4)
class PASCALIMPLEMENTATION TVTColors : public System::Classes::TPersistent
{
	typedef System::Classes::TPersistent inherited;
	
	
private:
	enum DECLSPEC_DENUM TVTColorEnum : unsigned char { cDisabledColor, cDropMarkColor, cDropTargetColor, cFocusedSelectionColor, cGridLineColor, cTreeLineColor, cUnfocusedSelectionColor, cBorderColor, cHotColor, cFocusedSelectionBorderColor, cUnfocusedSelectionBorderColor, cDropTargetBorderColor, cSelectionRectangleBlendColor, cSelectionRectangleBorderColor, cHeaderHotColor, cSelectionTextColor, cUnfocusedColor };
	
	
private:
	static System::StaticArray<System::Uitypes::TColor, 17> cDefaultColors;
	TBaseVirtualTree* FOwner;
	System::StaticArray<System::Uitypes::TColor, 17> FColors;
	System::Uitypes::TColor __fastcall GetColor(const TVTColorEnum Index);
	void __fastcall SetColor(const TVTColorEnum Index, const System::Uitypes::TColor Value);
	System::Uitypes::TColor __fastcall GetBackgroundColor(void);
	System::Uitypes::TColor __fastcall GetHeaderFontColor(void);
	System::Uitypes::TColor __fastcall GetNodeFontColor(void);
	System::Uitypes::TColor __fastcall GetSelectedNodeFontColor(bool Focused);
	
public:
	__fastcall TVTColors(TBaseVirtualTree* AOwner);
	virtual void __fastcall Assign(System::Classes::TPersistent* Source);
	__property System::Uitypes::TColor BackGroundColor = {read=GetBackgroundColor, nodefault};
	__property System::Uitypes::TColor HeaderFontColor = {read=GetHeaderFontColor, nodefault};
	__property System::Uitypes::TColor NodeFontColor = {read=GetNodeFontColor, nodefault};
	
__published:
	__property System::Uitypes::TColor BorderColor = {read=GetColor, write=SetColor, index=7, default=-16777201};
	__property System::Uitypes::TColor DisabledColor = {read=GetColor, write=SetColor, index=0, default=-16777200};
	__property System::Uitypes::TColor DropMarkColor = {read=GetColor, write=SetColor, index=1, default=-16777203};
	__property System::Uitypes::TColor DropTargetColor = {read=GetColor, write=SetColor, index=2, default=-16777203};
	__property System::Uitypes::TColor DropTargetBorderColor = {read=GetColor, write=SetColor, index=11, default=-16777203};
	__property System::Uitypes::TColor FocusedSelectionColor = {read=GetColor, write=SetColor, index=3, default=-16777203};
	__property System::Uitypes::TColor FocusedSelectionBorderColor = {read=GetColor, write=SetColor, index=9, default=-16777203};
	__property System::Uitypes::TColor GridLineColor = {read=GetColor, write=SetColor, index=4, default=-16777201};
	__property System::Uitypes::TColor HeaderHotColor = {read=GetColor, write=SetColor, index=14, default=-16777200};
	__property System::Uitypes::TColor HotColor = {read=GetColor, write=SetColor, index=8, default=-16777208};
	__property System::Uitypes::TColor SelectionRectangleBlendColor = {read=GetColor, write=SetColor, index=12, default=-16777203};
	__property System::Uitypes::TColor SelectionRectangleBorderColor = {read=GetColor, write=SetColor, index=13, default=-16777203};
	__property System::Uitypes::TColor SelectionTextColor = {read=GetColor, write=SetColor, index=15, default=-16777202};
	__property System::Uitypes::TColor TreeLineColor = {read=GetColor, write=SetColor, index=5, default=-16777200};
	__property System::Uitypes::TColor UnfocusedColor = {read=GetColor, write=SetColor, index=16, default=-16777197};
	__property System::Uitypes::TColor UnfocusedSelectionColor = {read=GetColor, write=SetColor, index=6, default=-16777213};
	__property System::Uitypes::TColor UnfocusedSelectionBorderColor = {read=GetColor, write=SetColor, index=10, default=-16777213};
public:
	/* TPersistent.Destroy */ inline __fastcall virtual ~TVTColors(void) { }
	
};

**Comment by joachimmarder** [comment]
> CBuilder RAD Studio 10

Is it C++ Builder 10 Seattle?

This HPP file is created by C++ Builder, so I guess it is a bug in C++ Builder 10 Seattle that is most likely solved in a later version. In any case, it is just a compiler warning and it seems save to me to simply ignore this warning.

**Comment by novakalex** [comment]
Yes, it is Seattle.
Now I ignore this warning. Can someone give Virtualtrees.HPP is compiling from later version Builder, like 10.2 for comparison?

**Comment by joachimmarder** [comment]
I'm not sure if this will compile in 10.0 as here are breaking changes in VCL and C++ Builder.
Please respect that this is a bug tracker for Virtual Treeview. You may have mire success in getting help on StackOverflow.com.
