### ISSUE TITLE
ScrollIntoView not working in FormCreate event

### ISSUE THREAD

**Issue by raelb** [JAM-Software/Virtual-TreeView#1081]
Hi,
I have just moved from v6.7 to v7.6.1, and now ScrollIntoView is not working.

I attach a simple demo. I expect VTV to scroll the last node into view but this does not occur.

Is this a bug or do I need to enable a new option?

[VST Scroll Test.zip](https://github.com/JAM-Software/Virtual-TreeView/files/7964785/VST.Scroll.Test.zip)

Thanks

**Comment by raelb** [comment]
After further investigation, I see that `ScrollIntoView` does work in general, however, specifically in the FormCreate event calling:

>    FillTree;
VST.ScrollIntoView(VST.GetLast(), True);


Does not work. (If called in a button click, then it does work)

This same code would work fine in v6.7.

**Comment by joachimmarder** [comment]
`FormCreate()` does not seem the right place to call `ScrollIntoView()`, typically no window handle exists here and so the view is kind of unknown. Please move your code to the `TForm.OnShow` event. A not recommend workaround is to call the `HandleNeeded()` method on the control before calling `ScrollIntoView()`.

In V7 there was a bug fixed that was caused by a premature creation of the window handle and so form handle. This may have caused the change in behavior.

**Comment by raelb** [comment]
In my project I am actually using a number of nested frames, so my code looks something like this:

>  ContainerFrame.SetupTreeFrame;
    begin
    TreeFrame := TTreeFrame.Create;
    TreeFrame.FillTree;
    TreeFrame.Parent  := TreePanel;
    TreeFrame.Align   := alClient;
    TreeFrame.Visible := True;
    ...
    end;

Moving FillTree after Parent is assigned does not make a difference.
Adding call to `VST.HandleNeeded` in TreeFrame.FillTree does solve the problem.

Can you elaborate on why it is problematic to call HandleNeeded? or in what cases it should be safe.

**Comment by joachimmarder** [comment]
> Can you elaborate on why it is problematic to call HandleNeeded?

It's a general best practise to avoid creating handles until the control is actually shown. If a form stays hidden, it uses far less resources. And several property setters of controls, which are called frequently during control creation, cause a recreation of a handle if the new value differs from the old one.

Therefore, it makes sense to have code which requires a handle in the OnShow event.
