### ISSUE TITLE
Selection not properly updated after changing font style

### ISSUE THREAD

**Issue by 7even11** [JAM-Software/Virtual-TreeView#1084]
This bug is a long standing one, even since 4.7.*. It should be finally fixed!

To reproduce:

1) drop a VirtualStringTree named **VirtualStringTree3** and TTimer named **Timer1** on a form.

2) add code:

```delphi
procedure TForm1.FormCreate(Sender: TObject);
begin
  VirtualStringTree3.Tag            := 0;
  VirtualStringTree3.RootNodeCount  := 5;
  VirtualStringTree3.OnGetText      := VirtualStringTree3GetText;
  VirtualStringTree3.OnPaintText    := VirtualStringTree3PaintText;
  VirtualStringTree3.TreeOptions.SelectionOptions := VirtualStringTree3.TreeOptions.SelectionOptions + [toMultiSelect];
  VirtualStringTree3.SelectAll(false);
  Timer1.Interval                   := 5000;
end;

procedure TForm1.Timer1Timer(Sender: TObject);
begin
  VirtualStringTree3.Tag := 1;
  VirtualStringTree3.Invalidate;
end;

procedure TForm1.VirtualStringTree3GetText(Sender: TBaseVirtualTree;
  Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType;
  var CellText: string);
begin
  case TextType of
    ttNormal: CellText := 'example';
    ttStatic: CellText := '(123)';
  end;
end;

procedure TForm1.VirtualStringTree3PaintText(Sender: TBaseVirtualTree;
  const TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
  TextType: TVSTTextType);
begin
  case TextType of
    ttNormal: begin
              if (VirtualStringTree3.Tag = 0) then
                begin
                  TargetCanvas.Font.Style := [fsBold];
                end
              else
                begin
                  TargetCanvas.Font.Style := [];
                end;
              end;
    ttStatic:	begin
                TargetCanvas.Font.Color := clBlue;
              end;
  end;
end;

```

The tree initially shows "example" in bold font and all is selected.

![before](https://i.imgur.com/oMq9UsR.png)

After 5 seconds the timer changes **VirtualStringTree3.Tag** and invalidates the tree - so in the **VirtualStringTree3PaintText** it removes the **[fsBold]** style. After refreshing extra spacing is shown behind the previously bold items which now occupy less space:

![after 1](https://i.imgur.com/gN1l03z.png)

If you now hover with mouse over the first 2 items for example, they will be redrawn with proper width but the rest of items won't be which they should have been in the first place:

![after 2](https://i.imgur.com/h8l6IBG.png)

I initially thought it happens only when **toShowStaticText** option was enabled, but it shows even when it is disabled.

Note - the same issue happens when **ttNormal** case is reversed to show Bold when **Tag := 1**:

```delphi

procedure TForm1.VirtualStringTree3PaintText(Sender: TBaseVirtualTree;
  const TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
  TextType: TVSTTextType);
begin
  case TextType of
    ttNormal: begin
              if (VirtualStringTree3.Tag = 0) then
                begin
                  TargetCanvas.Font.Style := [];
                end
              else
                begin
                  TargetCanvas.Font.Style := [fsBold];
                end;
              end;
    ttStatic:	begin
                TargetCanvas.Font.Color := clBlue;
              end;
  end;
end;

```

The result after the timer kicks in is:

![after 3](https://i.imgur.com/KM40d5d.png)

Again hovering over with mouse refreshes and fixes it.

**Comment by joachimmarder** [comment]
> This bug is a long standing one, even since 4.7.*. It should be finally fixed!

Well, to achieve this, first someone has to report the bug. Has this been done by you or someone else?

Secondly, please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project to your report, or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by 7even11** [comment]
The version of VirtualTreeview is the latest 7.61. The reference to 4.7.* was just to emphasize this has been a bug for a very long time. Delphi is 10.4.2. The reproduction code is up there to copy paste into a project. Would you like me to upload it somewhere?

**Comment by joachimmarder** [comment]
> Would you like me to upload it somewhere?

Yes, that's what I meant with "attach".

> The reference to 4.7.* was just to emphasize this has been a bug for a very long time

I understood that. I wanted to emphasize that is has not been reported for a very long time. And it doesn't matter how long a bug has been there, it matters when it is reported the first time.

**Comment by 7even11** [comment]
Sorry, the readme is referring 7.1 but the latest one is 7.61. I am using 7.61, the latest one. Attached is a combined project file reproduction of both bugs I've reported today. Also the older version I was using was 5.5.3, not 4.7.* like I wrote before.

[VSTBugs.zip](https://github.com/JAM-Software/Virtual-TreeView/files/8011385/VSTBugs.zip)

**Comment by joachimmarder** [comment]
May be related to #1077.

**Comment by 7even11** [comment]
Can't tell if it is related but it is most definitely a bug and the above code most definitely reproduces it.

**Comment by joachimmarder** [comment]
Yes, it is a bug and reproducible, but I have not yet a clue where it origins from.

**Comment by joachimmarder** [comment]
Reason is that selection is painted before the font is changed. We need to invalidate the node after the font has changed.
