### ISSUE TITLE
Fix for #1084 causes side effects when doing custom painting

### ISSUE THREAD

**Issue by beNative** [JAM-Software/Virtual-TreeView#1087]
The call to InvalidateNode(Node); in PaintNormalText that was introduced to fix #1084  causes recursive calls to the OnPaintText event if this event is used to apply some custom font and background coloring to the target canvas.
I tried to do this in the OnDrawText event instead but this results in the selection to be drawn incorrectly. 
Can you please advise how I could apply some custom text/color formatting for a node without affecting the painting of the selection?

**Comment by joachimmarder** [comment]
> The call to InvalidateNode(Node); in PaintNormalText that was introduced to fix https://github.com/JAM-Software/Virtual-TreeView/issues/1084 causes recursive calls to the OnPaintText event if this event is used to apply some custom font and background coloring to the target canvas.

I guess you are referring to endless recursions? The sample of #1084 (that is attached to #1083) is using the `OnPaintText` and does not make endless recursive calls. What are the exact steps to replicate the problem with the sample attached to #1083?

**Comment by beNative** [comment]
I attached the VSTBugs project with only one adjustment. I added an `UpdateActions` method so you can see the difference. When you start up the project and set a breakpoint in the `UpdateActions `method it will get in there immediately as it should. If you do the same however after 5 seconds when the `OnPaintText` change kicks in it will not. 

[VSTBugs.zip](https://github.com/JAM-Software/Virtual-TreeView/files/8078929/VSTBugs.zip)

**Comment by joachimmarder** [comment]
OK, I am now comparing the new and the old width of the node and a repaint is only triggered if they differ.
