### ISSUE TITLE
Better visualize Fixed columns

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#1088]
Use a darker line, like Excel does, for visualizing that a column is fixed.

![grafik](https://user-images.githubusercontent.com/10615289/154446572-e156b19e-7063-4dd7-b5cb-b0261d6e4f63.png)

**Comment by MHumm** [comment]
Yes, this indeed removes the black line. Haven't noticed any negative effect yet in my real project.
