### ISSUE TITLE
Binary packages for C++ Builder?

### ISSUE THREAD

**Issue by eelke-at-bolt** [JAM-Software/Virtual-TreeView#1089]
Are there any binaries downloadable for C++ Builder? We do not have the Delphi Personality to build from source.

**Comment by joachimmarder** [comment]
We do not distribute any binaries. A C++ builder only package is included. [`INSTALL.TXT`](https://raw.githubusercontent.com/JAM-Software/Virtual-TreeView/master/INSTALL.txt) has its own chapter for C++ Builder.

Please respect that this is a bug tracker, not a support forum.
