### ISSUE TITLE
Problem using VirtualStringTree with C++Builder Classic compiler

### ISSUE THREAD

**Issue by Asger-P** [JAM-Software/Virtual-TreeView#1092]
Hi
I have been told that the VirtualTree in the GetIt manager just is a copy of this version and that problems should be fixed here, that's the reason for this issue post.

I get this error:
[C++ Error] VirtualTrees.Types.hpp(93, 4): E2019 'TWithSafeRect:: :: :: ()' cannot be declared in an anonymous union
when trying to use TVirtualStringTree with the C++Classic compiler.

The Pascall reason for the error is: ( in VirtualTrees.types.pas line 137 )

```
  TWithSafeRect = record
   case Integer of
    0 :   (Left, Top, Right, Bottom : Integer);
    1 :   (TopLeft, BottomRight : TPoint); // This line 
  end;
```
That translates to (in VirtualTrees.types.hpp line 83)

```
struct DECLSPEC_DRECORD TWithSafeRect
{
   union{ 
      struct{
         System::Types::TPoint TopLeft;    // this line
         System::Types::TPoint BottomRight;   // and this line
      };   // **Error here**
      struct{
         int Left;
         int Top;
         int Right;
         int Bottom;
      };
   };
}; 

```
But as far as I can see in the VirtualTree source code, the TopLeft or BottomRight of the TWithSafeRect is never used, you only use TWithSafeRect to cast other TRects to get Left, Top, Right and Bottom.
If I comment out the top struct everything works fine, but it would be more elegant if you removed it from the pas files, since it is not used anyway, just a suggestion though for the next version.

For now it works fine for me.
Best regards
Asger

**Comment by joachimmarder** [comment]
> I have been told that the VirtualTree in the GetIt manager just is a copy of this version and that problems should be fixed here, 

I don't think this is an issue in Virtual TreeView, but in the part of RAD Studio that generates the HPP files from the Delphi code. 

It is True that `TWithSafeRect` could be eliminated in the code, but it is however valid code with that the tool chain should work. It would in my opinion only cure one specific symptom, but not the root cause.

This record must have been there for quite a long time (and so C++ Builder should work with it), I don't really understand its need.

**Comment by Asger-P** [comment]
First of all thank you for all your great work.
And yes you are right, TWithSafeRect have been there for a long time, but recently the file structure was changed, so that all types got their own file. This change made the TWithSafeRect end up in VirtualTrees.types.hpp. Previously TWithSafeRect was not translated because it was only used locally in the VirtualTrees.pas, maybe it was even in a private section, I'm not that good at reading pascall, so the only thing I know for a fact is that TWithSafeRect is not part of the .hpp files in old Sidney version.
No one of the c++ users would ever have to use the TWithSafeRect, so maybe it is possible to put something around it, preventing it from ending up in the .hpp file.
Thanks in advance
Best regards
Asger

**Comment by joachimmarder** [comment]
>  but recently the file structure was changed, so that all types got their own file. 

So you are using the V8 development branch? You (and Embarcadero) should switch to the V7 stable branch.

> Previously TWithSafeRect was not translated because it was only used locally in the VirtualTrees.pas

Ah, good to know. I don't use C++ Builder so its always a bit difficult for me if problem come up there. 

I have no idea what the exact purpose of TWithSafeRect is, it was simply there when I took over the project. I think I will remove the record and remove the `with` statements where it was used.
