### ISSUE TITLE
Indent of children of vsFiltered node (toShowFilteredNodes = false)

### ISSUE THREAD

**Issue by zarkogajic** [JAM-Software/Virtual-TreeView#1093]
Hi,

I was not able to find if the following was discussed (and if so, please disregard and please provide link to past discussion).

Here's the "problem":

Child nodes of a filtered (not visible) (parent) node will be drawn at their natural position / indentation -> as if they are a children of a "missing" node.

Suggestion:  draw such child nodes with "-1 + Node.Indent".

In images for better visual clue:

In the below image, the "\0142" node is not filtered:

![image](https://user-images.githubusercontent.com/44092708/162450798-3c54b5d8-9962-45fa-8c8d-95ccafb50734.png)

When that "\0142" node is filtered the rendering/painting is:

![image](https://user-images.githubusercontent.com/44092708/162451257-033dadda-395e-42a3-9d39-fb85433f2fa1.png)

If the offset / indent of all child-nodes elements (lines, image, text) would be decreased by 1 (or needed number depending on parent nodes), the look would be more natural.

-žarko

**Comment by joachimmarder** [comment]
> I was not able to find if the following was discussed (and if so, please disregard and please provide link to past discussion).

This was discussed in #701 

Drawing a node on a different level than its actual level does not seem a good and consistent solution to me.
