### ISSUE TITLE
Clicking a selected node in multiselect mode.

### ISSUE THREAD

**Issue by MShark67** [JAM-Software/Virtual-TreeView#1095]
Currently when there are multiple nodes selected, clicking on a selected node clears the selection and selects that node.  This makes drag and drop a bit difficult and it seems to differ from how other multiselect controls work.  It can be worked around using hittesting and the SelectionLocked property, so it's not critical, but it seems like the default behavior could be improved.

**Comment by joachimmarder** [comment]
> it seems to differ from how other multiselect controls work. 

The behavior I see here is pretty much like the behavior I see in Windows Explorer or in Delphi's TListView control, so I do not agree.

**Comment by MShark67** [comment]
@joachimmarder To clarify.  The VTV clears the selection on mousedown.  You should see that if you hold the mousedown in Explorer the selected items stay selected so they can be dragged.  As far as I can tell VTV doesn't do that by default and I had to use the workarounds I mentioned above.  If I'm missing a setting or option I'd love to know about it.

**Comment by joachimmarder** [comment]
>  The VTV clears the selection on mousedown.

Yes, like Windows Explorer and TListView do this. So I think the behavior is as expected and hasn't changed in years.
