### ISSUE TITLE
entry point to paint custom scrollbar

### ISSUE THREAD

**Issue by mebo** [JAM-Software/Virtual-TreeView#1099]
I'm trying to implement a modern 'floating' scrollbar into VirtualTrees (like seen in for example Microsoft Teams, a semi transparant scrollbar which is drawn over the content instead of using screen space on the side).

For this my plan was to either override Paint() or DoAfterPaint(), and draw the scrollbar stuff on the canvas there.

I can paint, but it seems clip regions on the canvas mess up updates after the inital call to paint. I do get calls to Paint(), and I do draw in those calls, but whatever I paint is not visible. I tried resetting any clip regions by calling SelectClipRgn(Canvas.Handle, 0), but that doesn't seem to have effect.

Any tips on how to approach this?

**Comment by joachimmarder** [comment]
Sorry, I can't help here. Never tried something like this after adopting the project some years ago.

However, this is not s support forum, but a bug tracker. Please respect the guidelines for using this bug tracker on the project homepage.

**Comment by joachimmarder** [comment]
Thank you. The demo projects are unfortunately not well maintained.
