### ISSUE TITLE
[Request New Feature] Support for Lazarus and Free Pascal

### ISSUE THREAD

**Issue by gwiethaus** [JAM-Software/Virtual-TreeView#1100]
It would be very interesting if the project could be used in Lazarus and Free Pascal. The components are great and I've always liked these, but with Delphi's sinful prices it would be nice for people who use or are thinking about using Lazarus to have these components. This even includes those who want to migrate and don't want to convert the entire project by swapping one treeview for another. I've been waiting for something about this for a long time, as Free Pascal and Lazarus are currently very strong.

**Comment by joachimmarder** [comment]
Duplicate, see #641
You may try or fork [blikblum/VirtualTreeView-Lazarus](https://github.com/blikblum/VirtualTreeView-Lazarus) which is also linked on the [Virtual Treeview project page](https://github.com/JAM-Software/Virtual-TreeView).

**Comment by gwiethaus** [comment]
Thanks for showing me the way. however I see the following: First the version is not the most recent and it is light years behind the newest version of Virtual TreeView. I believe it would be better if I had the compilation in the same distribution for Lazarus and Delphi. This could be done using compiler directives. I see that there are not many files to convert or adapt. I believe it would be possible. It could start slowly and slowly, but slowly and steadily. So we would have a single project that would be available for both pascal tools. I am grateful for this wonderful component that I have been sweating for years in my projects.
