### ISSUE TITLE
Wrong Class for new function GetLastSelected()

### ISSUE THREAD

**Issue by StefanGrube** [JAM-Software/Virtual-TreeView#1101]
VirtualTrees.pas could not be compiled anymore since the latest revision R1835(SVN).
The class for the new function GetLastSelected() should be TBaseVirtualTree instead of TVirtualStringTree:

function TVirtualStringTree.GetLastSelected(ConsiderChildrenAbove: Boolean = False): PVirtualNode;
->
function TBaseVirtualTree.GetLastSelected(ConsiderChildrenAbove: Boolean = False): PVirtualNode;

**Comment by joachimmarder** [comment]
Is the problem still there for you?

**Comment by StefanGrube** [comment]
Nope, disappeared with R1841 (SVN), as you changed VirtualTrees.pas as proposed by me above on 2022-06-03.
