### ISSUE TITLE
Unnecessary DrawDisabled code in VirtualTrees.Utils with undesirable side effects.

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1104]
VirtualTrees.Utils DrawImage:

```pascal
procedure DrawImage(ImageList: TCustomImageList; Index: Integer; Canvas: TCanvas; X, Y: Integer; Style: Cardinal; Enabled: Boolean);

  procedure DrawDisabledImage(ImageList: TCustomImageList; Canvas: TCanvas; X, Y, Index: Integer);
  var
    Params: TImageListDrawParams;
  begin
    FillChar(Params, SizeOf(Params), 0);
    Params.cbSize := SizeOf(Params);
    Params.himl := ImageList.Handle;
    Params.i := Index;
    Params.hdcDst := Canvas.Handle;
    Params.x := X;
    Params.y := Y;
    Params.fState := ILS_SATURATE;
    ImageList_DrawIndirect(@Params);
  end;

begin
  if Enabled then
    TCustomImageListCast(ImageList).DoDraw(Index, Canvas, X, Y, Style, Enabled)
  else
    DrawDisabledImage(ImageList, Canvas, X, Y, Index);
end;
```

What VirtualTrees does is totally unnecessary since TCustomImageList.DoDraw uses the exact same routine if appropriate and GrayscaleFactor = 0 (default).  See local routine DrawDisabled of TCustomImageList.DoDraw.  It is better to let the ImageList to draw disabled images as appropriate.

This has undesirable side effects if for example you use TCustomImageList descendents.  See for example https://github.com/TurboPack/MustangpeakVirtualshellTools/issues/21.

I suggest that you just use:

```pascal
procedure DrawImage(ImageList: TCustomImageList; Index: Integer; Canvas: TCanvas; X, Y: Integer; Style: Cardinal; Enabled: Boolean);
begin
    TCustomImageListCast(ImageList).DoDraw(Index, Canvas, X, Y, Style, Enabled)
end;
```

**Comment by joachimmarder** [comment]
> What VirtualTrees does is totally unnecessary since TCustomImageList.DoDraw uses the exact same routine if appropriate 

Does this apply to all supported Delphi versions? I have in mind that there used to be a bug in the VCL that made this workaround necessary...

**Comment by pyscripter** [comment]
Not sure.  Vcl.ImgList has not changed in the last many versions,  but it is worth checking XE3 (minimum supported version).  I have no access to XE3.  I suspect, if there was a bug, it was fixed before XE3.

In any case it the job of the ImageList to decide how disabled icons are displayed.

**Comment by pyscripter** [comment]
Thanks!
