### ISSUE TITLE
Add which mouse button was clicked to DoNodeClick Parameters

### ISSUE THREAD

**Issue by Dave-Novo** [JAM-Software/Virtual-TreeView#1107]
Depending on the FOptions.FSelectionOptions, the HandleMouseUp can be called from Left/Middle or Right buttons. HandleMouseUp gets the var Message:TWMMouse so it knows which button was pressed. But it does not pass this information to DoNodeClick. This is very useful if you want different behavior on the right click vs left click.

In our case, we are using the virtual tree as a drop down for a compbo box. So if the user left clicks on a node, they "selected it" and we should close the virtual tree. But if they right click on the node, they just selected it for the purposes of having the correct selection for the popup menu and we should not close it.

The code change is trivial. Now we have to do it in the regular mouse up and GetHitTestInfoAt. Not such a big deal, but it might be helpful to add this for others.

**Comment by joachimmarder** [comment]
> But it does not pass this information to DoNodeClick.

So is your suggestion to extend the record `THitInfo` with a new member  of the type `TMouseButton`?

> The code change is trivial.

Feel free to send a pull request.

**Comment by Dave-Novo** [comment]
I am not sure if THitInfo is the correct spot. THitInfo basically translates an X,Y coordinate to information about what is under that X,Y location in the Treeview. Certainly, one should be able to get a THitInfo without any mouse information.

Also, there are many places where THitInfo is used that I would have to update with relevant mouse information if possible. Certainly, if THitInfo had a .MouseDown property, a developer would expect it to be correct under all circumstances.

I can see from a backwards compatibility perspective, this seems like a good answer, since you do not have to change the method signature of OnNodeClick. But I do think that changing the signature of OnNodeClick to include a Button:TMouseButton parameter is the proper solution.

**Comment by joachimmarder** [comment]
Changing the signature of an event in a widely used library is a no-go in Delphi, this is why there are so many "Ex" events around.

I don't think a new `OnNodeClickEx` event is justified, but I will open this issue for discussion.

**Comment by TommiPrami** [comment]
Sure you can change the Event signature, means little bit work, if clearly better, I would do it, not sure is this the case tough.

Someone will complain if you do braking change, but generally keeping backwards compatibility means that code will not improve.

I think there should be more breaking changes if it means we have better code than without change. 

We still have CreateFmt and so code in RTL, from the times when there was no overloads.

**Comment by Dave-Novo** [comment]
This is practically a religious argument, whether or not to "break" previous code. Some people come on the side that new versions should never break previous code, and it suffers from the drawback that either new features are not put in, or you get confusing sets of event with multiple versions for the same events. Again, the religious argument is that it is better to have X versions of a particular event, with resulting mental confusion which version to use for what and what order everything is fired in, in order to keep old users happy.

I am in favor of breaking backwards compatibility as long as the changes required are straightforward and well documented, but again, it is a religious argument.

**Comment by livius2** [comment]
It will be breaking change. 
Why do you simply do not use MouseDown/Up event and call for GetNodeAt?

**Comment by Dave-Novo** [comment]
Why make OnNodeClick at all then? If users can just use MouseDown/Up and call GetNodeAt.  IIRC The point being that the OnNodeClick stuff does some checking for you to make sure the click started/and ended on the same node, the node has certain permissions etc etc.

**Comment by livius2** [comment]
I understand your point. But ask self, what Embarcadero would say if you ask them for extending `OnClick` and `OnDbClick`?
They have only a `Sender: TObject` already. You even do not know the X and Y coordinates. You must read them from the mouse position inside your event handler.
I like to have all at hand, but we must think also to do not make too many problems for current working code.
You can read mouse buttons by GetKeyboardState.

**Comment by joachimmarder** [comment]
I will repeat my suggestion from above: `OnNodeClick` has `THitInfo` as parameter. `THitInfo` already has a member `HitPoint: TPoint`. Another member for mouse button shouldn't hurt and this change would be non-breaking.

Fell free to send a pull request.

**Comment by livius2** [comment]
Looking into the code there are 361 occurences of `HitInfo` but most of them use already accuired info from other methods.
So it should be quite simple to suport it by changing THitInfo and few places where it is setup.

But the most important is `GetHitTestInfoAt` which do not get information form mouse message, only it have parameter X, Y
and to it parameters are passed as e.g. `Message.XPos`, `Message.YPos`. Then i do not know if reading inside `GetHitTestInfoAt` from `GetKeyboardState` is valid or we should change parameters of this virtual method which is public.

So both methods of change have side effects.

**Comment by joachimmarder** [comment]
> But the most important is GetHitTestInfoAt which do not get information form mouse message, only it have parameter X, Y

We could add a new optional parameter for the mouse button to `GetHitTestInfoAt()`. In case we do this using an overloaded method, we can read the value e.g. using `GetKeyboardState()` in case no value was supplied.

> So both methods of change have side effects.

I don't see a side effect here, but more important, this is not a breaking change.

**Comment by Dave-Novo** [comment]
If you are going to go the route of adding it to the THitInfo, you may also consider adding the shiftState to THitInfo as well, while you are at it.

**Comment by Dave-Novo** [comment]
> I understand your point. But ask self, what Embarcadero would say if you ask them for extending `OnClick` and `OnDbClick`? They have only a `Sender: TObject` already. You even do not know the X and Y coordinates. You must read them from the mouse position inside your event handler. I like to have all at hand, but we must think also to do not make too many problems for current working code. You can read mouse buttons by GetKeyboardState.

Again, this is simply a religious argument. When Delphi put OnClick, they also put OnMouseDown and OnMouseUp. If you feel OnNodeClick is used so much and developers will have a freak out, then fine, that is your feeling. Since you are the maintainers, your feelings win!

**Comment by livius2** [comment]
> Since you are the maintainers

I am not, i am only contributor ;-) I do not have commit privilege. Currently i am working on merging my FMX fork to the official repo.
But i use extensively VT, so my concern is to do not broke something.
Especially public virtual methods  and the events which IDE will monit to remove :/

But proposition of @joachimmarder looks good to have default parameter, and looking at this as a whole
i do not know why VCL have `TMouseButton` if `TShiftState` contain already `ssLeft, ssRight, ssMiddle`.
So my proposition is to add `ShiftState: TShiftState` with default `[]` and do resign from the `TMouseButton`.
Opinions?

**Comment by gmnevton** [comment]
if i'm not mistaken, shiftstate might be empty while mousebutton indicates
which button was pressed.

**Comment by joachimmarder** [comment]
> So my proposition is to add ShiftState: TShiftState with default [] and do resign from the TMouseButton.
> Opinions?

Since events like `OnMouseDown` have a `TShiftState` I think this is a good idea.

**Comment by joachimmarder** [comment]
I agree with @livius2. Since `ShiftState` is now included in THitInfo and indicates the mouse button, I am considering this issue as resolved as long a no one explains why `ShiftState` is not sufficient.

**Comment by Dave-Novo** [comment]
thank you for your work considering this issue!
