### ISSUE TITLE
Latest Virtual Tree View version Crashes Delphi 10.4 and Delphi 11.1 with designtime IDE access violations

### ISSUE THREAD

**Issue by wpostma** [JAM-Software/Virtual-TreeView#1108]
Using the latest master branch commit the Delphi 10.4 and Delphi 11 IDEs crash when opening a project. Sample project included in this report and in the RSP-38745 loggd on quality centerla. The QC report is because this bug also occurs when using the BPLs installed via GETIT which I assume are somewhat behind the latest  master branch on github.

commit d9bffe4ff4b4f08ac397dab8e4a092ac3e65436b (HEAD -> origin/master, origin/HEAD, master)
Author: Joachim Marder <joachim.marder@outlook.com>
Date:   Sat Jul 16 09:18:33 2022 +0200

    Fixed issue #1106: Ensure Endupdate() is called if an exception occurs within DoStateChange

https://quality.embarcadero.com/browse/RSP-38745

To reproduce open the attached project  TreeViewBugDemo.dproj

[VirtualTreeCrashIDE - Copy.zip](https://github.com/JAM-Software/Virtual-TreeView/files/9201482/VirtualTreeCrashIDE.-.Copy.zip)

**Comment by wpostma** [comment]
This is the WRONG WAY TO RETIRE/RENAME/REDIRECT/DEPRECATE/MIGRATE a designtime PROPERTY.

procedure TVirtualTreeColumn.DefineProperties(Filer : TFiler);

begin
  inherited;

  // These properites are remains from non-Unicode Delphi versions, readers remain for backward compatibility.
  Filer.DefineProperty('WideText', ReadText, nil, False);
  Filer.DefineProperty('WideHint', ReadHint, nil, False);
end;

**Comment by joachimmarder** [comment]
> WRONG WAY TO RETIRE/RENAME/REDIRECT/DEPRECATE/MIGRATE a designtime PROPERTY.

No need to write in uppercase letters, it seems to have worked for many years at least. It would be more helpful to explain why this is wrong and what is the correct way to do this.

**Comment by joachimmarder** [comment]
If I change `WideText` to `Text` and `WideHint` to `Hint` in the DFM the problem still occurs. Where does this DFM file origin from? What are the repro steps to create such a file in the IDE?

**Comment by wpostma** [comment]
What I said above may be wrong.  While I was not familiar with this coding pattern it is apparently valid.

Filer.DefineProperty('WideText', ReadText, nil, False);
Filer.DefineProperty('WideHint', ReadHint, nil, False);

However what I'm seeing is that even with the latest Git sources built and loaded in Delphi 10.4 and 11 its not retiring the old WideHint and WideTExt.

If you are able to open a dfm with widehint and see it save to hint and remove widehint, then the code in git is right.

**Comment by wpostma** [comment]
The alternative way to deprecate a property and have delphi remove it is to declare it as a public unpublished property which will then allow the old dfms to load.  

public
   property WideText:string read GetWideTest write SetWideText

etc and implement SetWideText and GetWideText to set Text or return Text

**Comment by wpostma** [comment]
Perhaps the ONLY problem is that the Getit package in the Delphi 10.4 and 11 GetIt catalog is not up to your fixes in Git?

**Comment by joachimmarder** [comment]
> The alternative way to deprecate a property and have delphi remove it is to declare it as a public unpublished property which will then allow the old dfms to load.

That does not deprecate the property, it just removes it from the DFMs. So as long as the used coding pattern is valid, it seems superior to me.

> Perhaps the ONLY problem is that the Getit package in the Delphi 10.4 and 11 GetIt catalog is not up to your fixes in Git?

I can't comment much on this, the decision is up to Embarcadero which version they use. I would recommend the V7_stable branch.

But I still do not understand this issue, especially:

- Since when does it exist? / Which commit caused it?
- What are the repro steps in an entirely new project?

**Comment by wpostma** [comment]
Open the provided DFM to see the issue.

It's a migration issue.

If you create a new project the old property WideText will never exist in any columns added to it.

If you create a new project and then add a form copied from an old project, the old property will exist.

Expected: Quietly converted without error.

Actual: Can blow up with an access violation in Delphi 10.4.2 and 11.1 when I build from latest git sources but need to open old DFMs still and have them convert.

**Comment by joachimmarder** [comment]
> It's a migration issue.

As I wrote in a previous comment, the problem also occurs if I use the values for the new properties. At least in my tests.

**Comment by joachimmarder** [comment]
Since there are no repro steps on how to create within the IDE the DFMs that contains garbage, I am going to close this issue for now.
