### ISSUE TITLE
HitInfo.Column always -1 in OnHeaderClick when TComboBox editor's combo is open

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1110]
A VST used in reportmode with a column where the editor is a TCombobox always returns -1 in HitInfo.Column when clicking on the header of that column and the Combobox is "expanded"/"dropped down".

For all other columns using other controls as editor (like TEdit) HitInfo.COlumn returns the right column index.

How to reproduce?
1. Unzip attached file into empty directory
2. Open dpr and press F9
3. select one of the items in the 2nd column, they're named ComboItem X
4. Press F2 to start editing
5. Click dropdown to open combo
6. Click on *any* column header

Exp.: Label below the VST shows 1 as column index
Act.: label shows -1

7. Select a node of the 3rd column
8. Press F2 to start editing
9. Click dropdown to open combo
10. Click on *any* column header

Exp.: Label below the VST shows 2 as column index
Act.: as expected

[VSTEditorSample.zip](https://github.com/JAM-Software/Virtual-TreeView/files/9228973/VSTEditorSample.zip)

**Comment by joachimmarder** [comment]
> 6. Click on any column header
>
> Exp.: Label below the VST shows 1 as column index

Shouldn't that be the index of the clicked column?

Besides that this is quite a corner case issue that may have existed since the beginning of this control.

**Comment by joachimmarder** [comment]
A different code path is chosen in `TVirtualTreeColumns.HandleClick()` for the repro steps, because `FDownIndex` differs in both scenarios. Need to check this in detail.

**Comment by MHumm** [comment]
It should be the column index of the clicked column. And it happens when the header is clicked while the combo box is dropped down. Not sure if it happens when it is closed.
