### ISSUE TITLE
Integer overflow in ScaleNodeHeights

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#1112]
https://github.com/JAM-Software/Virtual-TreeView/blob/4924906a2be49c781786ae5ac6fcd45419f78015/Source/VirtualTrees.pas#L10071

I can reproduce this, if the form is first opened on a high dpi monitor (4K), then moved to a 96 dpi monitor then I see the integer overflow exception as mentioned in the comment. If the form first opens on the 96 dpi monitor I can move it back and forth with no issues. 

I have no idea how to fix it though.

**Comment by joachimmarder** [comment]
> I have no idea how to fix it though.

@vincentparrett : The only option that comes to my mind would be to do the calculation based on `Int64`. Would you mind testing this, as I don't have a 4K monitor at hand.

If that doesn't help, it would be great if you could take a look at the values of `FRoot.TotalHeight` and `lNewNodeTotalHeight`

**Comment by vincentparrett** [comment]
Doing the calcs based on Int64 didn't help.
Edit. removed bogus theory:)

**Comment by vincentparrett** [comment]
Actually scrap that theory. Int64 calcs do fix it, I will submit a PR.

That said, there are a ton of implicit casts using MulDiv (which operates on integer) which could potentially cause problems,

**Comment by joachimmarder** [comment]
Thank you for the PR.

> That said, there are a ton of implicit casts using MulDiv (which operates on integer) which could potentially cause problems,

It operates on Int64 according to Microsoft Docs:

> Multiplies two 32-bit values and then divides the 64-bit result by a third 32-bit value. The final result is rounded to the nearest integer.
https://docs.microsoft.com/de-de/windows/win32/api/winbase/nf-winbase-muldiv
