### ISSUE TITLE
Strange "Data: record end;" and out of memory access

### ISSUE THREAD

**Issue by andb24** [JAM-Software/Virtual-TreeView#1114]
UPDATE:  I asked people how to add item to this list;
BUT. As you can see, AddNode for TTVirtualTreeView uses record-based container for user data.
I'am sure this is violation of responsibility development pattern, because:
1. Here is Double (nested) containerization (class inside record)
2. Component allocates memory for this structure.

Component shall not allocate memory for user data. It is not his task!
It stores pointers to data and handle structure of tree. Data allocation is the task for other part of code!

type
 // Item for TVirtualTreeView
  TTVItem = record
  public
    Item: TObjectDataRecord;
  end;
  PTVItem = ^TTVItem;

--------------------------
PREVIOUS TEXT:

### Possible out-structure access.

I guess declaration of "empty" Data field is a very erroneous.
It should be Data:pointer to be a pointer to a custom user storage structure, record, class etc.

```
  TVirtualNode = packed record
    ....
      FirstChild,              // link to the node's first child...
      LastChild: PVirtualNode; // link to the node's last child...
  private
     **Data: record end;**        // this is a placeholder, each node gets extra data determined by NodeDataSize
  public
     function IsAssigned(): Boolean; inline;
     function GetData(): Pointer; overload; inline;
     function GetData<T>(): T; overload; inline;
...
end;
```

The method that used by you looks like microsoft-way to declare a variable array at the end of structure in WinAPI.
But in that case memory number of items is known value and  their size is being calculated in that manner:

```
type
PMSWinApiStructure=^TMSWinApiStructure;
TMSWinApiStructure=packed record
  a:integer;
  b:integer;
  c: pointer;
  **items : packed array[0..0] of TSomeStructure;**
end;

var data:^TMSWinApiStructure;

data:=allocMem(sizeof(TMSWinApiStructure)+sizeof(TSomeStructure)*N), 

```
where N - number of elements in array, which known before;

```
  private
    Data: record end;        // this is a placeholder, each node gets extra data determined by NodeDataSize
```

BUT your Data field  has zero bytes size, used as variable and possibly use unused memory at the end of TVirtualNode record; You maybe know about memory align - some structures in memory should/could be aligned to 2-8 bytes margin in memory, so this DATA is just a label in memory - it is could not contain any data. I guess procedure and other methods in this record are situated in code segment of program while fields in Data segment, so this field is probably the last in this record, so it has some extra bytes of memory after it;

TListView, TTreeView and other classes have Data:pointer in theirs items; 
Delphi classes are by nature are pointer too (for example:
```
 var btn: TButton;   
btn:=TButton.Create;
```
btn is a true pointer;

So, please make Data field :pointer and deprecate NodeSize property and memory sizing calculations. They are useless; 

### NEXT. usage of this structure:
As you see in this code (VirtualTrees.pas) code accesses (read and write) to the memory _starting from_ beginning of empty Data field **+ 4 bytes after it.**

```
function TVirtualNode.GetData(): Pointer;
// Returns the associated data converted to the class given in the generic part of the function.
begin
  Result := @Self.Data;
  Include(States, vsOnFreeNodeCallRequired);
end;

function TVirtualNode.GetData<T>: T;
// Returns the associated data converted to the class given in the generic part of the function.
begin
  Result := T(Pointer((PByte(@(Self.Data))))^);
  Include(States, vsOnFreeNodeCallRequired);
end;

function TVirtualNode.IsAssigned: Boolean;
// Returns False if this node is nil, True otherwise
begin
  Exit(@Self <> nil);
end;

procedure TVirtualNode.SetData(pUserData: Pointer);
  // Can be used to set user data of a PVirtualNode with the size of a pointer, useful for setting
  // A pointer to a record or a reference to a class instance.
var
  NodeData: PPointer;
begin
  NodeData := PPointer(@Self.Data);
  NodeData^ := pUserData;
  Include(Self.States, vsOnFreeNodeCallRequired);
end;
```

**Comment by andb24** [comment]
I could not understand this activities during adding new node.
Why someone should set NodeDataSize ? Does TVirtualNode pre-allocate its own piece of memory ?
Many datatypes have non-obvious structure, for example,  modern string type which is dynamic array and pointer too, instead of old classic shortstring[100];

![image](https://user-images.githubusercontent.com/31127262/182811650-c0a8a2a2-d6bc-43e9-86b7-43483f30d377.png)

**Comment by andb24** [comment]
Instead of this strange type conversion:
```procedure TVirtualNode.SetData(pUserData: Pointer);
  // Can be used to set user data of a PVirtualNode with the size of a pointer, useful for setting
  // A pointer to a record or a reference to a class instance.
var
  NodeData: PPointer;
begin
  NodeData := PPointer(@Self.Data);
  NodeData^ := pUserData;
Include(Self.States, vsOnFreeNodeCallRequired);

^^^ I guess this code came from old delphi programming style.
Now pointer assignment can be used without "^" operator.
```

you should just write:
(but this is incorrect because Data field has zero-bytes size and using it as a pointer is out-of-record memory access which is potentially buggy!!!! )
```
procedure TVirtualNode.SetData(pUserData: Pointer);
begin
     Self.Data:=pUserData; // Thats ALL!
     Include(Self.States, vsOnFreeNodeCallRequired);
end;
```

**Comment by andb24** [comment]
Instead of this piece of sheet
![image](https://user-images.githubusercontent.com/31127262/182820897-672c805a-3773-4498-933c-4b9d444253af.png)

You should use this code:
```
procedure TForm1.Button3Click(Sender: TObject);
var I: Integer;
      TreeData: PTreeData;
begin
  VST.BeginUpdate;
  for I:=0 to 100 do
  begin
    //alloc memory in heap
   New(TreeData);
     //fill this record fields
    TreeData.FCaption:='Node-Nummer: '+IntToStr(I);
    TreeData.FColumn1:='Nummer: '+IntToStr(I*I);
    //Add new node
   AVST.AddChild(nil, TreeData);
  end;
  VST.EndUpdate;
end;
```

**Comment by andb24** [comment]
In my development I widely use small classes with fields+TObjectList instead of records and TList. 
TObjectList automatically call Free for items when its collection are being freed using Clear method call.
(no more **new** and **dispose** calls)

**Comment by joachimmarder** [comment]
> AddNode for TTVirtualTreeView uses record-based container for user data.

It is this way for more than 20 years. I just adopted this project. I guess it was done for performance reasons and I don't think this can be reasonably changed. 

I personally just store pointers to interfaced objects in the virtual node user data, which works great. These objects are under my control and lifetime is managed through reference counting. There are convenience methods in `TVirtualNode` with generics that do this with some type-safety. 

I would indeed not recommend to store more than a pointer to an object in the user data of a virtual node.
