### ISSUE TITLE
OnChange event firing seems slightly inconsequent

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1118]
I have an application which displays items in a TVirtualString tree used in report mode. 
With buttons one can add items and delete the selected item. 

Another button should save what one has added/what's in the list. Now I wanted to add 
some logic to enable/disable the button depending whether RootNodeCount is 0 or not, 
so whether there is something in the list.

I added an OnChangehandler thus with this code:
Button.Enabled := vst.RootNodeCount <> 0;

When adding a first item I see RootNodeCount is 1 already in OnChange,
when deleting that first and only item via vst.DeleteNode(vst.FocusedNode); 
I see that RootNodeCount is still 1 in OnChange but 0 afterwards when I'm back in 
the OnClick handler of my delete button.

This looks like some slightly inconsequent handling of RootNodeCount or rather 
calling the OnChange event.

**Comment by joachimmarder** [comment]
> so whether there is something in the list.

You may use the convenience function `IsEmpty()` to query this.

> I added an OnChangehandler thus with this code

Please note that the OnChnage event is fired whenever the selection changes. So it is not tied to adding or removing nodes.

To disable buttons when the list is empty, the `OnStructureChange` might be more suitable.

**Comment by joachimmarder** [comment]
> I see that RootNodeCount is still 1 in OnChange but 0 afterwards when I'm back in
the OnClick handler of my delete button.

This is intended. First the node to be deleted is removed from the selection (which fires `OnChange`), then it is removed from the tree. Reversing this order would clearly cause problems.
