### ISSUE TITLE
Cannot instal On D10.2.3

### ISSUE THREAD

**Issue by limelect** [JAM-Software/Virtual-TreeView#1120]
![Screenshot - 24_09_2022 , 18_20_36](https://user-images.githubusercontent.com/4199131/192106090-0d66e604-b102-428d-b3ac-ffc1bf981129.jpg)

**Comment by joachimmarder** [comment]
I don't have a RAD Studio 10.2.3 at hand for testing.

Which version of Virtual TreeView are you using?

Can you please check if the package for RAD Studio 10.4 works for you?

**Comment by limelect** [comment]
Sorry, I do not have 10.4 only 10.2
I downloaded the last version from here (git)
Your installation comment refers to 10.2

**Comment by joachimmarder** [comment]
> I do not have 10.4 only 10.2.

I just asked to try the packages for 10.4. and see if those work for you.

**Comment by limelect** [comment]
Running 4+ error
[dcc32 Error] VirtualTreesR.dpk(28): E1030 Invalid compiler directive: 'LIBSUFFIX'

**Comment by limelect** [comment]
Disabled above trying to compile R

Checking project dependencies...
Compiling VirtualTreesR.dproj (Release, Win32)
dcc32 command line for "VirtualTreesR.dpk"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc32.exe -$D0 -$L- -$Y- --no-config -M -Q -Z -TX.bpl 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DRELEASE -I..\..\source;.\Win32\Release;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win32\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" 
  -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp -NU.\Win32\Release -NSWinapi;
  System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell; 
  -O..\..\source;.\Win32\Release;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win32\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" -R..\..\source;.\Win32\Release;"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win32\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" -U..\..\source;.\Win32\Release;"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win32\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" -K00400000 -JL 
  -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp -NH..\..\Source -NOC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp   VirtualTreesR.dpk 
    
Can't load package VirtualTreesR$(Auto).bpl.
The system cannot find the file specified
[Fatal Error] Can't load package VirtualTreesR$(Auto).bpl.
The system cannot find the file specified

**Comment by luebbe** [comment]
IIRC the libsuffix auto directive only started to work properly from 10.4. on upwards.

**Comment by limelect** [comment]
I disabled it see my comment still cannot compile 4
I am stack

**Comment by joachimmarder** [comment]
> E1030 Invalid compiler directive: 'LIBSUFFIX'

Sorry, I forgot, this is new to 10.4. You may then try the 10.3 package. But we never had an issue like this before, so I don't think it is a bug in the packages. Please check carefully if you maybe have older / other versions of Virtual TreeView on your disk. You may also try if the "V7_stable" branch makes a difference if you used the "master" branch.

**Comment by livius2** [comment]
@limelect do you have virtualTree installed from GetIt package Manager? It will conflict then with package from here.

I have tried on 10.2.3 and no problems with build and installation do you have installed **Update 3?** And which version?, Enterprise, Professional ....
![image](https://user-images.githubusercontent.com/14888294/193410573-73273c6c-26e7-44ed-a9bd-10ecc7308885.png)


![image](https://user-images.githubusercontent.com/14888294/193410639-3c1f0d9c-72b6-4230-a50b-53906bcadad1.png)

**Comment by limelect** [comment]
After 30+ years with Delphi, I had to think about your solution.
I had an older BPL.
Thanks and sorry.
