### ISSUE TITLE
TCustomVirtualStringTree.InternalData may return wrong values.

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1136]
The memory allocated for each node consists of three parts.

- [TVirtualNode - Size TreeNodeSize] 
- [User Data - Size set by NodeDataSize and Validate(NodeDataSize)] 
- [InternalNodeData - Size set with AllocateInternalDataArea]

Except for the Root node which only has two parts.  (No User Data are allocated for the Root node.)

TCustomVirtualStringTree.InternalData is defined as:
```pascal
function TCustomVirtualStringTree.InternalData(Node: PVirtualNode): Pointer;
begin
  if (Node = nil) or (FInternalDataOffset = 0) then
    Result := nil
  else
    Result := PByte(Node) + Self.NodeDataSize + FInternalDataOffset;  // FInternalDataOffset always equal to TreeNodeSize
end;
```

There are a couple of issues:

1.  It will give wrong results for the RootNode which may have internal data, but no user data.
2. Self.NodeDataSize may be  -1 (default Value) if you have no user data and you have not created any nodes yet, or you are in design mode.

**Suggestion 1:**
Change TCustomVirtualStringTree.InternalData to:

```pascal
function TCustomVirtualStringTree.InternalData(Node: PVirtualNode): Pointer;
begin
  if (Node = nil) or (FInternalDataOffset = 0) then
    Result := nil
  else if Node = RootNode then
    Result := PByte(Node) + FInternalDataOffset
  else
    Result := PByte(Node) + Self.NodeDataSize + FInternalDataOffset;
end;
```

This resolves the first and partially the second issue.

ValidateNodeDataSize is defined as 
``` pascal
procedure TBaseVirtualTree.ValidateNodeDataSize(var Size: Integer);
begin
  Size := SizeOf(Pointer);
  if Assigned(FOnGetNodeDataSize) then
    FOnGetNodeDataSize(Self, Size);
end;
```
and it is called by MakeNewNode:
```pascal
  if not (csDesigning in ComponentState) then
  begin  // Make sure FNodeDataSize is valid.
    if FNodeDataSize <= 0 then
      ValidateNodeDataSize(FNodeDataSize);
```

**Suggestion 2:**
Change ValidateNodeDataSize to:
```pascal
procedure TBaseVirtualTree.ValidateNodeDataSize(var Size: Integer);
begin
  if Size <= 0 then
    Size := 0
  else
    Size := (Size + (SizeOf(Pointer) - 1)) and not (SizeOf(Pointer) - 1);

  if Assigned(FOnGetNodeDataSize) then
    FOnGetNodeDataSize(Self, Size);
end;
```
If you do not need user data there is no need to waste memory for each node.  NodeDataSize should be 0.   Optionally make it aligned to 8 bits.

I would also remove the call to ValidateNodeDataSize from MakeNewNode and move it to SetNodeDataSize.  Finally I suggest that the default value of NodeDataSize is changed to 0, which is also a valid value if you do not have user data.

The above would also resolve the second issue with InternalData and the VirtualTree would function properly at design time.   This is important for descendants such as TVirtualExplorerTree (from MustangpeakVirtualShellTools), which have a live preview at design time.

Finally, TreeNodeSize allocates node memory aligned at an 8 bytes boundary, but this does not help when you access user data since this is done via the Data field of TVirtualNode and SizeOf(TVirtualNode) is 68 bytes in 64bits.  It should be done by shifting the node pointer by TreeNodeSize bytes.

BTW I was bitten by this issue when I got memory leaks in TVirtualExplorerTree which were quite hard to trace.  This VirtualStringTree descendent. has no user data but uses internal data.

**Comment by joachimmarder** [comment]
> Self.NodeDataSize may be -1 (default Value) 

-1 is just the initial value, the default value is the size of the pointer in bytes, which is set as soon as the first node is created. This is a good default value, because in an average user scenario a pointer to a record, object or interface is stored. so this works out of the box in a 32Bit and 64Bit environment. Because of this, I won't change the default value to 0.

> It will give wrong results for the RootNode which may have internal data, but no user data.

Maybe it would be more consistent to allocate use data for the root node as well? It would waste just a few bytes bur make code more readable and consistent.

**Comment by pyscripter** [comment]
> -1 is just the initial value, the default value is the size of the pointer in bytes, which is set as soon as the first node is created

So if you try to access the internal data of the Root object before any node is created the result is wrong.

The other problem is Design time.   ValidateTreeNodeDataSize is not called at design time (the value of NodeDataSize stays -1), so creating nodes at Design time will lead to errors.  VirtualExplorerTree does create nodes at design time.  (live preview).

Please consider calling ValidateTreeNodeData in the NodeDataSize setter and not in MakeNewNode.  It is also more efficient.

Setting the NodeDataSize to 4 wastes memory for every node, when no user data are needed.  0 is a perfectly valid value.  If you do use user data (in most cases you do), **you need to set NodeDataSize before accessing user data**.  Setting it by default to 4 will not save the day.  It may just mask errors.


> Maybe it would be more consistent to allocate use data for the root node as well? It would waste just a few bytes bur make code more readable and consistent.

I would certainly agree with that.   It came as a surprise when I found out that this was not the case.  I think most users are not aware of that.

**Comment by joachimmarder** [comment]
> Setting the NodeDataSize to 4 wastes memory for every node, when no user data are needed. 0 is a perfectly valid value. 

It is a valid value but no a good default value.

> If you do use user data (in most cases you do), you need to set NodeDataSize before accessing user data. Setting it by default to 4 will not save the day. 

A good default value for a property is a value that does not need to be changed in an average case. Having stored a pointer in the user data is an average case, but having no user data and only internal data is for sure a corner case. Also, changing the dafault value from pointer size to zero would break all those average case projects. 


> Please consider calling ValidateTreeNodeData in the SetNodeDataSize setter and not in MakeNewNode.

SetNodeDataSize() may never be called, if the value matches the default value of the property. Also the code around ValidateTreeNodeData() is designed, so that ValidateTreeNodeData() is called only in case NodeDataSize is -1. But it seems unlikly the SetNodeDataSize() is called with a value < 0, as this is not a valid value, and -1 just indicates that the member variable is uninizialized.

> I would certainly agree with that.

OK, maybe let's start here. A bonus could be that we can create the root also by calling MakeNewNode() and would so call ValidateTreeNodeData() early enough. What do you think?

**Comment by pyscripter** [comment]
> OK, maybe let's start here. A bonus could be that we can create the root also by calling MakeNewNode() and would so call ValidateTreeNodeData() early enough. What do you think?

Great idea!  I think that would work.

There is the issue with design time that needs to be sorted.  If there are no nodes created removing the condition would do no harm and if there are nodes created at design time removing the conditions is necessary. Oh! I see a problem in conjunction with the above.  I think the Root node is always created (AfterConstruction) and will change the default value of NodeDataSize.


> Finally, TreeNodeSize allocates node memory aligned at an 8 bytes boundary, but this does not help when you access user data since this is done via the Data field of TVirtualNode and SizeOf(TVirtualNode) is 68 bytes in 64bits. It should be done by shifting the node pointer by TreeNodeSize bytes.

Also think about this comment.

**Comment by joachimmarder** [comment]
> Finally, TreeNodeSize allocates node memory aligned at an 8 bytes boundary, but this does not help when you access user data since this is done via the Data field of TVirtualNode and SizeOf(TVirtualNode) is 68 bytes in 64bits. 

One option to solve this would be to define `TVirtualNode.TotalCount` as `NativeUInt`. Then `SizeOf(TVirtualNode)` is 72 bytes in 64bits. As bonus, the following pointers `Parent, PrevSibling, NextSibling, FirstChild, LastChild` would be 8 byte aligned too.

What do you think?

**Comment by pyscripter** [comment]
> One option to solve this would be to define `TVirtualNode.TotalCount` as `NativeUInt`. Then `SizeOf(TVirtualNode)` is 72 bytes in 64bits. As bonus, the following pointers `Parent, PrevSibling, NextSibling, FirstChild, LastChild` would be 8 byte aligned too.
> 
> What do you think?

Sounds good!

**Comment by pyscripter** [comment]
Regarding the default for NodeDataSize.

The fact that -1 is converted to SizeOf(Pointer) is not obvious to users, unless they study the code (implementation detail).  
I can see one reason where the current state helps.  If the size of the user date is indeed SizeOf(Pointer) and the user does not set the NodeDateSize explicitily (which I think they should be encouraged to do), it helps maintain 32-bit 64-bit compatibility.

But the default value does actually complicate the implementation of your other suggestion:  Root node has user data and is created with MakeNewNode.

**Comment by pyscripter** [comment]
> One option to solve this would be to define `TVirtualNode.TotalCount` as `NativeUInt`. Then `SizeOf(TVirtualNode)` is 72 bytes in 64bits. As bonus, the following pointers `Parent, PrevSibling, NextSibling, FirstChild, LastChild` would be 8 byte aligned too.

Ideally all count properties should be of the same type (Index, ChildCount etc.). One alternative to the above would be to add to TVirtualNode a TDWordFiller.

**Comment by pyscripter** [comment]
Let's be practical:

Minimal changes:

1. Design time issue:  I can  resolve that by setting NodeDataSize (to 0) in the constructor of TVirtualExplorerTree.  (just thought of that).

2. Root node has no user data issue:  

Change TCustomVirtualStringTree.InternalData to

```pascal
function TCustomVirtualStringTree.InternalData(Node: PVirtualNode): Pointer;
begin
  if (Node = nil) or (FInternalDataOffset = 0) then
    Result := nil
  else if Node = RootNode then
    Result := PByte(Node) + FInternalDataOffset
  else
    Result := PByte(Node) + Self.NodeDataSize + FInternalDataOffset;
end;
```


Then I think my issue is resolved.

Optionally you can do something about the alignment, but this is a separate issue.

**Comment by joachimmarder** [comment]
>  One alternative to the above would be to add to TVirtualNode a TDWordFiller.

Good idea, I just committed that.

**Comment by joachimmarder** [comment]
> The fact that -1 is converted to SizeOf(Pointer) is not obvious to users, unless they study the code (implementation detail).

While this is true, I don't see any benefit in breaking thousands of projects and forcing their developers to explicitly set a value that was a good default value before.

**Comment by joachimmarder** [comment]
> There is the issue with design time that needs to be sorted.

How about simply removing the condition for `csDesigning` in `MakeNewNode()`?

```
  if not (csDesigning in ComponentState) then
  begin  // Make sure FNodeDataSize is valid.
    if FNodeDataSize <= 0 then
      ValidateNodeDataSize(FNodeDataSize);

    // Take record alignment into account.
    System.Inc(Size, FNodeDataSize);
  end//not csDesigning
  else
    System.Inc(Size, SizeOf(Pointer));
```

**Comment by joachimmarder** [comment]
> But the default value does actually complicate the implementation of your other suggestion: Root node has user data and is created with MakeNewNode.

Can you please further elaborate on this? I don't see why.

**Comment by pyscripter** [comment]
> > But the default value does actually complicate the implementation of your other suggestion: Root node has user data and is created with MakeNewNode.
> 
> Can you please further elaborate on this? I don't see why.

Think of the following:

At design time the component is created
- FNodeDataSize set to -1 by the constructor.
- After construction creates FRoot by MakeNewNode as suggested
- ValidateNodeDataSize is called which changes the FNodeDataSize
- Save the form.  FNodeDataSize is saved with a non-default value
- Reopen the form.  FNodeDataSize is no longer -1.

If you do not call ValidateNodeDataSize at design time FRoot will created with the wrong memory allocated.  This is likely to lead to problems, especially if there is live preview at design time.

My suggestion is to keep everything as is except for TCustomVirtualStringTree.InternalData and optionally deal with the alignment inserting TDWordFiller in TVirtualNode.

**Comment by joachimmarder** [comment]
> * Save the form. FNodeDataSize is saved with a non-default value
> * Reopen the form. FNodeDataSize is no longer -1.

That would be easy to overcome by using the `stored` modifier for the property instead of the current `default` modifier.

**Comment by pyscripter** [comment]
> That would be easy to overcome by using the `stored` modifier for the property instead of the current `default` modifier.

I thought of that:

Something like:

```pascal
function TBaseVirtualTree.IsNodeDataSizeStored: Boolean;
begin
  Result :=  FNodeDataSize <> SizeOf(Pointer);
end;
```

This is also problematic.   Think about a user that wants 4 bytes, irrespective of size of Pointer.  (a record with two integer values).   They set NodeDataSize to 4.  But this is not saved.  At runtime in 64 bits NodeDataSize becomes 8.  This may not be a disaster, but still...

Why fix something if it works?  And you convinced me that it works.  It has been like this for a very long time.  

Besides, there may be  reasons why FRoot contains no user data.  And it is always created as initialized, so the user never gets the opportunity to place user data at the Root node.   If you  change that, you will need to change other things as well e.g.

```pascal
procedure TBaseVirtualTree.ReinitNode(Node: PVirtualNode; Recursive: Boolean);

// Forces the given node and all its children (if recursive is True) to be initialized again without
// modifying any data in the nodes nor deleting children (unless the application requests a different amount).

begin
  if Assigned(Node) and (Node <> FRoot) then
  begin


```

**Comment by joachimmarder** [comment]
OK, then let's leave `NodeDataSize` aside and focus on the internal data problem of the root node. 

I found your argument convincing that the root node should also have node data. I prefer consistency over conditional code. To change this, the minimal change would be to add `FNodeDataSize` to the memory size in `TBaseVirtualTree.InitRootNode()`, after calling `ValidateNodeSize()` there. We could then eliminate the call to `ValidateNodeSize()` in `MakeNewNode()` for efficiency, as you suggested. What do you think?

>  If you change that, you will need to change other things as well e.g.

Sorry, but I don't see what needs to be changed in `ReinitNode()`.

**Comment by pyscripter** [comment]
> Sorry, but I don't see what needs to be changed in `ReinitNode()`.

The root node currently is always created initialized (see InitRootNode).  Even, when you call ReInitNode(FRoot, Yes),  InitNode is never called on the Root node  (Node <> FRoot).  So, unless you change other things, there is no point in having user data at the Root Node, since the user will never get the opportunity to assign user data to the root node.

Also the RootNode is created at construction (in AfterConstruction be precise).  You would have to assign a valid value to FNodeDataSize at construction, for that to work, which creates problems with the default value as I explained above.  I like consistency, and I like the idea of making the Root node a standard node, but it gets complicated, requires quite a few changes (TBaseVirtualTree.GetNodeData would also need to be changed) and it risks breaking things.

And even if you do all the required changes, all existing code using VirtualTrees was written with the assumption that InitNode will not be called with FRoot (e.g. Node.Parent <> nil always).  So, if you start calling InitNode(FRoot), who knows what will break?

Hence, my suggestion is to keep everything as is, except for TCustomVirtualStringTree.InternalData and optionally deal with the alignment inserting TDWordFiller in TVirtualNode.

**Comment by livius2** [comment]
Small question, i do not dig into the detail.
But why do you need that root node have a data? 
In your descendant class you can store data everywhere in the object itself about the root node.

**Comment by pyscripter** [comment]
In VirtualExplorerTree (originally developed by Jim Kueneman), the internal data are used to store info about the namespace (PIDL) of the corresponding file object.   If the root folder is hidden, the namespace of the hidden root folder is stored in the Root node of the VirtualTree.  It does not have to, but it is a natural place to store it.

**Comment by livius2** [comment]
I don't feel it as natural way ;-)

**Comment by pyscripter** [comment]
> and optionally deal with the alignment inserting TDWordFiller in TVirtualNode.

@joachimmarder I have just seen you implemented that (thanks).   Missed your message above.

**Comment by joachimmarder** [comment]
> I don't feel it as natural way ;-)

I agree, the natural place would be a strongly typed member variable in the control,

**Comment by joachimmarder** [comment]
> You would have to assign a valid value to FNodeDataSize at construction, for that to work, which creates problems with the default value as I explained above.

@pyscripter : My intention was not to make the node data of the root node usable, but just to have a consistent memory layout across all nodes, so that we don't need the additional `else if` in `InternalData()`.

**Comment by pyscripter** [comment]
> My intention was not to make the node data of the root node usable, but just to have a consistent memory layout across all nodes, so that we don't need the additional `else if` in `InternalData()`.

Is that not a lot of trouble, just to avoid a couple of lines in one function? `if Node <> FRoot` appears 93 times in the VirtualTrees.pas!  Why worry about increasing that to 94?
I think I explained above that calling ValidateNodeDataSize at construction time would create conflict with the default value of -1. You would also have to reconstruct the Root node when the NodeDataSize changes.   And if you do not allow access to the root node user data, the inconsistency still remains.  The root node will not be like the other nodes.   Compare InitRootNode to InitNode.  They are very different.   A better design might have been to make all nodes including the root the same (same memory footprint, initialization , avoiding all the `if Node <> FRoot` stuff, etc.).  But I think now it is too late to change that or at least beyond the scope of this issue report.

IMHO changing TCustomVirtualStringTree.InternalData is the simplest and safest solution to this issue.  

> How about simply removing the condition for `csDesigning` in `MakeNewNode()`?

I would certainly agree with that.  This would prevent errors in derivative controls that have a live preview in the designer.  In all other cases, it would not harm, since MakeNewNode would not be called at design time.

**Comment by joachimmarder** [comment]
And how about my suggestion to use a strongly typed member variable for the root PIDL? I still find it off that the root node should have a usable internal data but no node data. It seems that it was OK way for ~24 years that the root node did not have internal data.

**Comment by pyscripter** [comment]
> I still find it off that the root node should have a usable internal data but no node data. It seems that this OK that way for ~24 years.

Let me reverse that.   As you say, for 24 years, the root node had InternalData and the means to access them.   Why change that now and potentially break existing code?  It would certainly break the Turbopack.VirtualShellTools (instlallable through GetIt), which I no longer maintain.

The design of VirtualExplorerTree or other descendent controls, is not the issue here.   It is fixing an obvious error in TCustomVirtualStringTree.InternalData.

**Comment by pyscripter** [comment]
Thanks!!
