### ISSUE TITLE
Draw drag header - windows zoom

### ISSUE THREAD

**Issue by ElRicoB21** [JAM-Software/Virtual-TreeView#1137]
Draw drag a header when using Windows zoom (Win 10, zoom by combo items) is Incorrect. See video attachment.

https://user-images.githubusercontent.com/116547342/197475127-24729a63-94fc-4e1e-ab41-9c6fa67a374c.mp4

**Comment by livius2** [comment]
Hi, isn't this issue with zoom itself?

**Comment by joachimmarder** [comment]
While during drag&drop of nodes VTV lets the system do the drawing of the drag image (via `IDataObject` and `IDragSourceHelper`), during header drag the VTV control does the drawing on its own. So some dummy `IDataObject` could improve the situation and allow us to eliminate those old code paths.
Methods to look into:
* `TVTDragImage.PrepareDrag()`
* `TVTHeader.DragTo()`
* `TBaseVirtualTree.UpdateWindowAndDragImage()`

Issue #1138 was created to prepare for this issue.

**Comment by joachimmarder** [comment]
Should now be fixed in the latest code in the master branch. @ElRicoB21 : Could you please test this?
