### ISSUE TITLE
Still problems when creating nodes at Design time.

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1140]
MakeNewNode was recently changed to:

```pascal
function TBaseVirtualTree.MakeNewNode: PVirtualNode;
var
  Size: Cardinal;
begin
  Size := TreeNodeSize;
  if (csDesigning in ComponentState) and (FNodeDataSize < SizeOf(Pointer)) then
    System.Inc(Size, SizeOf(Pointer)) // Fixes #702
  else
  begin  // Make sure FNodeDataSize is valid.
    if FNodeDataSize <= 0 then
      ValidateNodeDataSize(FNodeDataSize);

    // Take record alignment into account.
    System.Inc(Size, FNodeDataSize);
  end;
```

This still creates problems at Design time, since FNodeDataSize is not updated.   So access to InternalData for all nodes except the root (see code) will be wrong, leading to design-time crashes.  If you change the memory allocated to a node, this needs to be matched with FNodeDataSize, What is wrong with?

```pascal
function TBaseVirtualTree.MakeNewNode: PVirtualNode;
var
  Size: Cardinal;
begin
  Size := TreeNodeSize;
  if FNodeDataSize <= 0 then 
    ValidateNodeDataSize(FNodeDataSize);

  // Take record alignment into account.
  System.Inc(Size, FNodeDataSize);
```

This does not affect controls that do not make nodes at design time (the vast majority of use cases) and works correctly for controls (descendents) that make nodes at design time - works the same way as in run time -.   

Please consider also changing 

    'if FNodeDataSize <= 0 then'

to

    'if FNodeDataSize < 0 then '

as  FNodeDataSize = 0 is initialized and valid.  

BTW, I just noticed your change to ValidateNodeDataSize and now I understand what you were saying in the other thread.

**Comment by joachimmarder** [comment]
> This still creates problems at Design time, since FNodeDataSize is not updated

Yes, it is not updated intentionally, see discussion in #1136.

> What is wrong with?

It changes `FNodeDataSize` and so the default value of the `NodeDataSize` property, see discussion in #1136. This is why I proposed to use the `stored` modifier there.

**Comment by pyscripter** [comment]
We are only talking here about descendent controls, that create nodes at design time.   Users of TVirtualStringTree are not affected since they do not create nodes at design time. In #1136, I was referring to the problems in adding user data to the root node, which is always created. 

The least you would expect from those descendent controls is to set NodeDataSize explicitly before creating nodes and possibly avoid publishing NodeDataSize or change the default of NodeDataSize. More so, since until the recent change in ValidateNodeDataSize,  if you did not set  NodeDataSize, FNodeDataSize would become 0 and lead to crashes anyway, when you access user data or internal data. 

As it stands, if FNodeDataSize = -1

` if (csDesigning in ComponentState) and (FNodeDataSize < SizeOf(Pointer))`

will  keep FNodeDataSize = -1 and is guaranteed to lead to crashes at Design time.

In any case, could we please at least change the two if statements to

` if (csDesigning in ComponentState) and (FNodeDataSize < 0)`

and

`if FNodeDataSize < 0 then`

if FNodeDataSize is initialized, there would be no reason to mess with it.

**Comment by pyscripter** [comment]
Thanks you for committing the change!

I still think, that you should get rid of the first "if,".  I am not sure what purpose it severs.  It is about preserving FNodeDataSize=-1 in descendent controls, that do not set NodeDataSize and create nodes at design time.  But with that statement those controls will most likely crash in design time anyway.

At least now, descendent controls with live preview at design time, can prevent errors by setting NodeDataSize,
