### ISSUE TITLE
Problematic behavior of TBaseVirtualTree.ReinitNode

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1145]
TBaseVirtualTree.ReinitNode is defined as follows:

``` pascal
procedure TBaseVirtualTree.ReinitNode(Node: PVirtualNode; Recursive: Boolean);

// Forces the given node and all its children (if recursive is True) to be initialized again without
// modifying any data in the nodes nor deleting children (unless the application requests a different amount).

begin
  if Assigned(Node) and (Node <> FRoot) then
  begin
    // Remove dynamic styles.
    Node.States := Node.States - [vsChecking, vsCutOrCopy, vsDeleting, vsHeightMeasured];
    if vsInitialized in Node.States then
      InitNode(Node);
  end;

  if Recursive then
    ReinitChildren(Node, True);
end;
```

The node is reinitialized only if it has already been initialized.  But then and irrespective of whether the node is initialized, ReInitChildren is called, which then creates the node children recursively.   This beats the basic concept of VirtualTrees which is to only create nodes when they are needed.  Also calling InitChildren (in ReinitChildrent) on nodes that have not been initialized, may lead to hard-to-trace bugs.

I think it would make sense to replace the last two statements with:

```pascal
  if Recursive and (Node.ChildCount > 0) then
    ReinitChildren(Node, True);
```

**Comment by joachimmarder** [comment]
Well, this all depends on the purpose of this method. I never used this method and a grep search did not show any call of this method. Why do you call it?

> The node is reinitialized only if it has already been initialized. But then and irrespective of whether the node is initialized, ReInitChildren is called

This seems indeed strange, as I think a non-initialized node cannot have initialized children. Therefore I would like to propose this change:

```
    if vsInitialized in Node.States then
    begin
      InitNode(Node);
      if Recursive then
        ReinitChildren(Node, True);
    end;
```

**Comment by pyscripter** [comment]
I use this method in PyScripter, for things like Code Explorer, Watches Window etc., when the underlying data structure changes.  It preserves the current state and is more efficient than creating the tree from scratch, since it avoids destroying and recreating nodes.  It can also be used in a File Explorer setting, when for example you are notified of a directory change.

Your proposal has two drawbacks:

- When Node = Root or nil you still want to call ReInitChildren (see code)
- It would still unnecessarily create uninitialized children when for instance the Node has vsHasChildrent, but has not been expanded yet and has no child nodes.   In that case you do not want to create new uninitialized children.   What would be the point?  Nodes should be created on demand. (*)

(*) Just to elaborate on this.  In a File Explorer you link nodes to PIDLs and say one of the nodes is a subdirectory.   When you Reinit that node you don't want the child nodes created if this node is not expanded and currently has no children.  The subdirectory may contain hundreds of files.

In PyScripter I also have another couple of methods ForcedReinitNode, ForcedReinitChildren which Reinit everything, whether or not it has been already initialized or not.  I use those with smaller data structures, when I need all the nodes to be initialized.

```pascal
procedure TVirtualStringTreeHelper.ForcedReinitNode(Node: PVirtualNode;
  Recursive: Boolean);
begin
  if Assigned(Node) and (Node <> RootNode) then
  begin
    // Remove dynamic styles.
    Node.States := Node.States - [vsChecking, vsCutOrCopy, vsDeleting, vsHeightMeasured];
    InitNode(Node);  // Always reinitialize
  end;

  if Recursive then
    ForcedReinitChildren(Node, True);
end;
```

Maybe this ReInitNode and ReinitChildren could accept an optional `const ForceReinit: Boolean = False`  parameter to that effect.
