### ISSUE TITLE
Sorting happens even when OnCompareNodes is not assigned

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1146]
Firstly, toAutoSort is on by default.   This is debatable.

But the main issue is that even when the OnCompareNodes event is not assigned (DoCompareNodes always returns 0 and the order would not change), Sort is still called every time you add child nodes and goes through the motions (MergeSortAscending etc.).
This a serious waste of CPU resources.

See SetChildCount, EndUpdate, InsertNode.

Proposal:
Do not call Sort if OnCompareNodes is not assigned, especially since toAutoSort is on by default.
Alternatively, Sort should exit immediately if OnCompareNodes is not assigned.

**Comment by joachimmarder** [comment]
> Sort should exit immediately if OnCompareNodes is not assigned.

That makes sense, since I couldn't see how an effective sorting could take place if `OnCompareNodes` is not assigned. Although a default implementation for the `TVirtualStringTree` would be possible based on the node text.

**Comment by pyscripter** [comment]
Thanks!

**Comment by raketenwurm69** [comment]
**Problem:** With the new behaviour, sorting does not work anymore when DoCompare() is overriden by a derived class.

**Explanation:** 
I am only using derived classes of VTV in my program. I also override DoCompare() to handle the sorting internaly. I would never have a OnDoCompare event, so the new enhancement in TBaseVirtualTree.SortTree() renders my derived function useless. 
Can the new behaviour be bound to some other criteria, so the old behaviour with a derived funcation will work again?

**Comment by joachimmarder** [comment]
Ok, I propose the following change: Do not turn on `toAutoSort` by default, but turn it on in case an event handler is assigned to `OnCompareNodes` at runtime. Use only `toAutoSort` to decide whether or not to sort the tree. What do you think, @pyscripter ?

**Comment by pyscripter** [comment]
I agree toAutoSort should not be on by default.

> but turn it on in case an event handler is assigned to `OnCompareNodes` at runtime

Is this necessary?   I can foresee cases in which you assign OnCompareNodes, but you want to keep control if and when the list is sorted.

To get a sorted list you would need to both turn on toAutoSort and set OnCompareNodes,  which is also the current case.

**Comment by joachimmarder** [comment]
>  I can foresee cases in which you assign OnCompareNodes, but you want to keep control if and when the list is sorted.

Me too, but we should optimize the default settings for the average case and new users, while making sure the chosen solution does not prevent from doing anything.

**Comment by pyscripter** [comment]
@joachimmarder 

Shouldn't this 

```pascal
procedure TBaseVirtualTree.SetOnCompareNodes(const Value: TVTCompareEvent);
begin
  FOnCompareNodes := Value;
  Self.TreeOptions.AutoOptions := TreeOptions.AutoOptions + [TVTAutoOption.toAutoSort]; // See issue #1146
end;
```
be

 ```pascal
procedure TBaseVirtualTree.SetOnCompareNodes(const Value: TVTCompareEvent);
begin
  FOnCompareNodes := Value;
  if Value <> nil then
    Self.TreeOptions.AutoOptions := TreeOptions.AutoOptions + [TVTAutoOption.toAutoSort]; // See issue #1146
end;
```

**Comment by joachimmarder** [comment]
Yes, you are right, something like that. I improved the commit.

**Comment by joachimmarder** [comment]
The latest change causes `toAutoSort` to be enabled for controls at runtime for that it wasn't before. This causes trouble because it changes the order in which the control is initialized. More exactly, Auto-sorting now initializes the trees node in EndUpdate(), e.g. after dpi-scaling, which previously did not happen.

The bottom line for me is: `toAutoSort` turned on is a good initial value for a new control at runtime, anyone can switch it off and then no useless sorting should take place.
