### ISSUE TITLE
Add an optional parameter to ReinitNode and ReinitChildren to force node initialization

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1147]
The use of that was explained in #1145.

There are situations in which you want to reinitialize nodes and make sure that the whole tree is reinitialized.

**Comment by pyscripter** [comment]
A PR was submitted. (#1148)
Minimal changes and backward compatible.

**Comment by joachimmarder** [comment]
Thanks!

**Comment by pyscripter** [comment]
Thank you!
