### ISSUE TITLE
Error when copying new row text

### ISSUE THREAD

**Issue by Hickokk** [JAM-Software/Virtual-TreeView#1150]
Hi.

I am adding a new row to a treeview, with Insert key. I write some text and I try to copy this text before adding the row. So I press Shift + home to select all the text. It results in an Exception. The procedure is ToggleSelection

In this part of the code:

 // 2) toggle all nodes within the range
      NodeFrom := GetNextVisible(NodeFrom, True);
      while NodeFrom <> NodeTo do
      begin
        if not (vsSelected in NodeFrom.States) then
          InternalCacheNode(NodeFrom)
        else
          InternalRemoveFromSelection(NodeFrom);
        NodeFrom := GetNextVisible(NodeFrom, True);
      end;

there's a moment when NodeFrom is nil, it's not controlled and it gives the Access Violation error. We tried to control it but we couldn't find the way, 'cause other strange behaviours followed.

Could you please help me with this? 

Thanks in advance

**Comment by joachimmarder** [comment]
Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project to your report, or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by Hickokk** [comment]
Please, accept my apology. I didn't mean to be unrespectful. I didn't find the rules. I'll try to make a little project to show.

Thank you very much.

**Comment by Hickokk** [comment]
It srill happens but we managed to avoid it.
