### ISSUE TITLE
Consistent line-endings in the repo

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1151]
In the past all source files had Windows line endings.   Currently some source files have unix line endings (e.g. VirtualTrees.BaseTree.pas) and some (e.g. VirtualTrees.Accessibility,pas) have Window endings.   Even worse, some files have mixed line endings.  (I use WinMerge for diff which reports that).

Delphi does not like Unix line endings and LSP may malfunction as a result.  

Git has an option to automatically convert line endings.  In Windows, when you commit line endings are converted to Unix and when you checkout, unix line endings are converted to Windows ones.   This may make sense for projects that can be used in either Windows or Linux, but for Delphi projects it does not make sense.   In my Delphi projects I disable automatic git line conversions and keep all source files with Windows line endings.

There is also an issue with the change history, since converting line endings, creates unnecessary noise.  In any case it would be good to adopt a policy on this and enforce it.  Either keep all files in Windows format (which I would recommend) or all files in Linux format.

You can also use add .gitattributes file to help enforce the policy.  See the [documentation](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) of this.

**Comment by pyscripter** [comment]
If it helps I can create a PR converting all files to Windows line endings.

**Comment by joachimmarder** [comment]
> Even worse, some files have mixed line endings. 

I have no idea how that happened, I suspect the various pull requests.

> Git has an option to automatically convert line endings.

I use GitHub Desktop and am not aware of any option here. Ideally this should be an option of the repository, not the client.

> If it helps I can create a PR converting all files to Windows line endings.

That would be very welcome.

**Comment by pyscripter** [comment]
#1152 submitted.

I suspect @livius2 has core.autocrlf set to true, so all his commits are saved with unix line endings.  The .gitattributes file added should now prevent that.

**Comment by livius2** [comment]
Hi

where do you see LF only? I have looked and search with regex in `VirtualTrees.BaseTree.pas` and no single line with LF only.
Also opened directly on the web and copied to notepad++.
Below file created by me from cloned repository on Windows:
![CRLF](https://user-images.githubusercontent.com/14888294/204721258-b3b05a15-88d3-4d0f-8d55-14de3e78dfd1.png)

**Comment by pyscripter** [comment]
@livius2 
If that was before the last commit, then you may have autocrlf set to yes.   When you checkout the file is automatically converted to crlf.  But when you checkin the file is converted back to lf.   

Anyone with autorcrlf set to false that checks the file out, would have gotten it with lf line endings.

You can check you setting by opening a terminal and running outside the repo.
`git config core.autocrlf`

`core.autocrlf` is a user setting and not a repo setting.  The added .gitattributes file, should now prevent the conversion to lf from happening.   We can confirm that next time you commit.

**Comment by livius2** [comment]
But i have also copied file content from the web (github.com) and looked at it in Notepad++.
Maybe github also recognized that i work on Windows and Windows use crlf.
And all users worked on Windows have crlf ok.

**Comment by pyscripter** [comment]
When did you do that?  Now everything is crlf inside the repo.

What is your core.autocrlf setting?

**Comment by pyscripter** [comment]
> And all users worked on Windows have crlf ok.

Not those with core.autocrlf set to false.

**Comment by livius2** [comment]
> When did you do that? Now everything is crlf inside the repo.

before merge
but yes i have `autocrlf = true` as i work on Windows

**Comment by pyscripter** [comment]
Merged PR #1152 

> but yes i have `autocrlf = true` as i work on Windows

So everything you committed was saved with unix line endings inside the repo.

From https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration
> core.autocrlf
> If you’re programming on Windows and working with people who are not (or vice-versa), you’ll probably run into line-ending issues at some point. This is because Windows uses both a carriage-return character and a linefeed character for newlines in its files, whereas macOS and Linux systems use only the linefeed character. This is a subtle but incredibly annoying fact of cross-platform work; many editors on Windows silently replace existing LF-style line endings with CRLF, or insert both line-ending characters when the user hits the enter key.
> 
> **_Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index_**, and vice versa when it checks out code onto your filesystem. You can turn on this functionality with the core.autocrlf setting. If you’re on a Windows machine, set it to true — this converts LF endings into CRLF when you check out code:

This makes sense for cross-platform projects.  But Delphi projects are Windows-only.

> **_If you’re a Windows programmer doing a Windows-only project,_** then you can turn off this functionality, recording the carriage returns in the repository by setting the config value to false:
> 
> $ git config --global core.autocrlf false

But from now on, the .gitattributes should prevent that from happening, whatever the developer core.autoconfig may be. Let's see.

**Comment by livius2** [comment]
> This makes sense for cross-platform projects. But Delphi projects are Windows-only.

Consider that Embarcadero is working on different platform for IDE supprort, and also usage in e.g. FPC.
Now it is stored inside repo as CRLF, i am against such not necessary changes, but @joachimmarder decided.

**Comment by pyscripter** [comment]
Unnecessary?

You prefer inconsistent line endings and Delphi issues for anyone having autorcrlf set to false?

**Comment by livius2** [comment]
Why someone on Windows will have set it to false? What now someone need to do if he need to compile on Linux? Again setup it to true ;-)

**Comment by pyscripter** [comment]
Reasons why storing the files with unix line endings and relying on autocrlf is a bad idea in this and other Delphi projects:

- Firstly, the default for autocrlf is false.  Depending on users setting it to true is not a good idea.  
- Unfortunately, Delphi does not handle files with unix line endings well.
- Anyone cloning the project with autocrlf set to false would face issues.
- Anyone downloading the sources as a zip file would face issues.
- Anyone committing with autocrlf set to false, would create inconsistencies and mess up the git history.
- The Delphi IDE only works on Windows.  And even if say the project was fpc/Lazarous compatible, fpc can handle files with CRLF fine on all platforms.
- There is no point in constantly coverting from crlf to lf and back.
- The conversion from CRLF to LF is not without risks.  See the documentation of core.safecrlf.
- This project has always saved files with crlf,  until you started committing.

**Comment by livius2** [comment]
i am not against introducing gitattributes file but shouldn't it looks like this?

```
* text=auto

# text files to always be normalized and converted to native line endings on checkout.
*.pas text diff=pascal
*.dfm text
*.fmx text
*.groupproj text
*.dpr text
*.dproj text
*.inc text
*.rc text

# binary and should not be modified.
*.exe binary
*.dll binary
*.res binary
*.bmp binary
*.jpg binary
*.jpeg binary
*.cur binary
```

But maybe i am too much fixed to store always as LF and fetching only in format needed on the other side e.g. crlf.

**Comment by pyscripter** [comment]
> i am not against introducing gitattributes file but shouldn't it looks like this?

No, that would enable line ending conversions depending on the developer autocrlf settings.

**Comment by livius2** [comment]
Yes, this is my point, store as LF, checkout whatever someone need.

**Comment by pyscripter** [comment]
> Yes, this is my point, store as LF, checkout whatever someone need.

I think I explained above that storing the files with Unix line endings and relying on auto conversions is a very bad idea, at least for Delphi projects.

**Comment by livius2** [comment]
Risky is only inconsistent settings like was with not exists `gitattributes` file.
Must say i missed that this project do not have one, i start every new repo from `gitattributes` and `gitignore` files.
And then automatic conversion is not the problem at all.

**Comment by pyscripter** [comment]
> And then automatic conversion is not the problem at all.

Storing the files with unix line endings and relying on automatic conversion is a big problem with Delphi projects.  I have listed many reasons why this is the case.  Do you disagree with the reasons listed?

Even when you have  .gitattributes file, what happens still depends on the user/developer autocrlf setting.  Unfortunately, there is no repo-specific way to set autocrlf.  Unless you disable all auto conversions, as I did in the added .gitattributes file,

**Comment by TommiPrami** [comment]
> Reasons why storing the files with unix line endings and relying on autocrlf is a bad idea in this and other Delphi projects:
> 
> * Firstly, the default for autocrlf is false.  Depending on users setting it to true is not a good idea.
> * Unfortunately, Delphi does not handle files with unix line endings well.
> * Anyone cloning the project with autocrlf set to false would face issues.
> * Anyone downloading the sources as a zip file would face issues.
> * Anyone committing with autocrlf set to false, would create inconsistencies and mess up the git history.
> * The Delphi IDE only works on Windows.  And even if say the project was fpc/Lazarous compatible, fpc can handle files with CRLF fine on all platforms.
> * There is no point in constantly coverting from crlf to lf and back.
> * The conversion from CRLF to LF is not without risks.  See the documentation of core.safecrlf.
> * This project has always saved files with crlf,  until you started committing.

Very good points.

Worst thing is that if single file has mixed line endings and Delphi will go haywire. 

I would keep all Delphi projects as CRRF in server and on clients. just my 0.02€

-Tee-

**Comment by livius2** [comment]
Do not read my sentence as criticism, only as questions. **I am not a git expert** and also my english is not good enough to describe sometimes my POV.
