### ISSUE TITLE
sliding of the cursor relative to the splitter when changing the width of the columns

### ISSUE THREAD

**Issue by ipalex-ua** [JAM-Software/Virtual-TreeView#1153]
the problem occurs when the total width of the columns is greater than the width of the control and horizontal scrolling to the right to the end. if you start reducing the width of the column, the cursor slides to the left relative to the splitter.
![зображення](https://user-images.githubusercontent.com/119502904/204801981-c736e12a-2f76-4a20-a165-b05162270feb.png)

I propose the following solution:
function TVTHeader.HandleHeaderMouseMove(var Message: TWMMouseMove): Boolean;
...
  NextColumn,
  I: TColumnIndex;
  NewWidth: Integer;
+  iOffsetX: Integer;
...
+            iOffsetX := Treeview.FEffectiveOffsetX;

            // The autosized column cannot be resized using the mouse normally. Instead we resize the next
            // visible column, so it look as we directly resize the autosized column.
            if (hoAutoResize in FOptions) and (FColumns.TrackIndex = FAutoSizeIndex) and
               (NextColumn > NoColumn) and (coResizable in FColumns[NextColumn].Options) and
               (FColumns[FColumns.TrackIndex].MinWidth < NewWidth) and
               (FColumns[FColumns.TrackIndex].MaxWidth > NewWidth) then
              FColumns[NextColumn].Width := FColumns[NextColumn].Width - NewWidth
                                            + FColumns[FColumns.TrackIndex].Width
            else
              FColumns[FColumns.TrackIndex].Width := NewWidth; // 1 EListError seen here (List index out of bounds (-1)) since 10/2013

+            if (iOffsetX > 0) and (iOffsetX <> Treeview.FEffectiveOffsetX) then
+              FTrackPoint.X := FTrackPoint.X + iOffsetX - Treeview.FEffectiveOffsetX;

**Comment by joachimmarder** [comment]
Would you mind sending a pull request or [patch](https://github.com/JAM-Software/Virtual-TreeView/wiki/Create-a-Patch) for the master branch?

**Comment by joachimmarder** [comment]
Any chance to get a pull request or a proper [patch file](https://github.com/JAM-Software/Virtual-TreeView/wiki/Create-a-Patch), @ipalex-ua?
