### ISSUE TITLE
Columname text with € sign display wrongly in Delphi collection editor

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1154]
When I put q € at the end of the .Text proeprty of a column definition, the name shown in the columns list floating popup changes from the text I entered to Column4 or Column5, depending on the column I edit. It doesn't happen when entering a @ isntead of a € sign.

**Comment by joachimmarder** [comment]
Strange. Which version of Delphi and Virtual TreeView are you using?

> When I put q € at the end of the .Text proeprty of a column definition

In the Delphi designer, in the code (at runtime), or both?

**Comment by MHumm** [comment]
Sorry for being a bit short in my description yesterday evening.
I'm using 11.2 and the version currently distributed via GetIt (yes, I'm a bit lazy on that one).

I checked now andf the issue only happens in form designer, not at runtime!

Here are two screenshots from form designer showing the issue:

![Euro1](https://user-images.githubusercontent.com/29703069/205446988-8cf9f7ea-7566-4977-921a-72aec541f00d.PNG)
![Euro2](https://user-images.githubusercontent.com/29703069/205446989-2f4f727f-a422-43dc-86c4-42a150c96d01.PNG)

**Comment by joachimmarder** [comment]
I think this is a duplicate of your issue #1111?

**Comment by joachimmarder** [comment]
Everything is working well except displaying in the collection view:

![grafik](https://user-images.githubusercontent.com/10615289/205484712-b85ef8d9-bdd4-420e-8223-8bbd327256e1.png)

I didn't care too much about this so far. But I saw that `TVirtualTreeColumn.GetDisplayName()` filters all chars >Ord(255).

```
function TVirtualTreeColumn.GetDisplayName: string;

// Returns the column text if it only contains ANSI characters, otherwise the column id is returned because the IDE
// still cannot handle Unicode strings.

var
  I: Integer;

begin
  // Check if the text of the column contains characters > 255
  I := 1;
  while I <= Length(FText) do
  begin
    if Ord(FText[I]) > 255 then
      Break;
    Inc(I);
  end;

  if I > Length(FText) then
    Result := FText // implicit conversion
  else
    Result := Format('Column %d', [Index]);
end;
```
That must be ancients code from the time when Delphi did not support Unicode.

**Comment by MHumm** [comment]
If the help for Ord is correct, ord has Byte as result type:
function Ord(X: Ordinal): Byte;
So a check of > 255 wouldn't help. Now since ord is too low level I cannot look up its actual implementation. It jumps into System.pas but lands nowhere there.

WHat if this check loop would be commented out and we'd test it with some chars known to cause the issue?
