### ISSUE TITLE
Vertical scrollbar position not updated during scrolling when a theme is used

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1155]
When a VCL Theme is used, e.g. Charcoral Dark Slate, the vertical scroll bar position is not updated during scrolling. It is updated as soon as scrolling is over, means: it jumps to the correct position. This happens for mouse and keyboard scrolling alike.

It doesn't happen if the original Windows style is used. Another test shows that it happens for all styles.

**Comment by joachimmarder** [comment]
I was only able to repro this in the branch V7_stable with the cursor keys, which is now fixed. But not with the mouse / mouse wheel:

![ScrollDemo](https://user-images.githubusercontent.com/10615289/205486459-c25249c4-92d8-44a7-8ec5-bdee645ff975.gif)

Please provide more detailed repro steps for the mouse.

**Comment by MHumm** [comment]
Thanks for fixing the keyboard part of the issue!
I revisited it now and found out: it's not the mouse wheel, it's mous scrolling via the arrow buttons at the end of the scroll bar!

**Comment by joachimmarder** [comment]
> it's mous scrolling via the arrow buttons at the end of the scroll bar!

OK, this is now also fixed.
