### ISSUE TITLE
TV is slow when RootNodeCount>15.000.000 

### ISSUE THREAD

**Issue by duytuanvn** [JAM-Software/Virtual-TreeView#1159]
I have tested width large nodes. When I assign RootNodeCount = 16000000 VT run pretty slow.
Please tell me how to fix this?
Thank you!

**Comment by joachimmarder** [comment]
Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project to your report, or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by joachimmarder** [comment]
Adding 16000000 root nodes in the Advanced sample (speed demo) takes less than a second.

**Comment by duytuanvn** [comment]
> Adding 16000000 root nodes in the Advanced sample (speed demo) takes less than a second.

**Comment by duytuanvn** [comment]
> Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project to your report, or instructions how to modify one of the included sample projects to reproduce the problem.

I use Delphi 10.4,  TVirtualStringTree is the newest ( in file VirtualTrees.pas, version: 7.6.2).

**My sample:**

```pascal
type

  TNodeData = record
    Field1: Boolean;
    Field2: array[0..255] of string; //This make TVirtualStringTree run slow!
  end;

  TfrmMain = class(TForm)
    VirtualStringTree1: TVirtualStringTree;
    btnAddNode: TButton;
    procedure btnAddNodeClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmMain: TfrmMain;

implementation

{$R *.dfm}

procedure TfrmMain.btnAddNodeClick(Sender: TObject);
begin
  VirtualStringTree1.NodeDataSize := Sizeof(TNodeData );
  VirtualStringTree1.RootNodeCount := 16000000;
end;

```

I found:
  TNodeData = record
    Field1: Boolean;
    Field2: array[0..255] of string; //This make TVirtualStringTree run slow!
  end;
If I remove Field2 in TNodeData then the speed is faster. How to keep Field2 and still fast TV speed?

Thank you!

**Comment by TommiPrami** [comment]
TNodeData = record
  Field1: Boolean;
   Field2: array[0..255] of string; //This make TVirtualStringTree run slow!
 end;

That is most likely due the Array initialization.

I would bet it has nothing to do with virtual tree. (the slowness) 

Add that many of those records to TList<T> and it will take quite long I think.

**Comment by joachimmarder** [comment]
In your sample, the record type is declared but not used, I find it a little strange that it causes the slowness. But yes, most likely this problem is not related to Virtual TreeView.

**Comment by duytuanvn** [comment]
> In your sample, the record type is declared but not used, I find it a little strange that it causes the slowness. But yes, most likely this problem is not related to Virtual TreeView.

In my project record type with Field2: array[0..255] used. 
I suspect Is there something related to the node's memory allocation that is causing the slow speed?

**Comment by TommiPrami** [comment]
Could you just initialize that array in some other structure.

  TNodeData = record
    ID: Ineger;
    Field1: Boolean;
  end;

  TNodeData = record
    ID: Ineger;
    Field2: array[0..255] of string; //This make TVirtualStringTree run slow!
  end;
  
  And fetch the Field2 if / when needed from elsewhere? So the GUI would stay fast.

-Tee-
