### ISSUE TITLE
OnShortenString Event "Done" parameter docs incorrect

### ISSUE THREAD

**Issue by gwideman** [JAM-Software/Virtual-TreeView#1160]
The Help doc says " If Done is set to true (default value is false) the tree view takes over the shortening. This is useful if not all nodes or columns need"

However:

-  **Done = False** results in VTV performing the shortening, whereas 
- **Done = True** tells VTV to use the shortening provided in this event handler.

This accords with the way other event handlers signal the host control not to perform default processing.

**Comment by joachimmarder** [comment]
I'm sorry, but the help file is not maintained and out of date. I added an XmlDoc to the `TVSTShortenStringEvent`.
