### ISSUE TITLE
Request: Type Definition in Unit VirtualTrees.pas

### ISSUE THREAD

**Issue by kxMaxx** [JAM-Software/Virtual-TreeView#1162]
Hi,

I would like to inquire on the [Breaking Changes](https://github.com/JAM-Software/Virtual-TreeView/wiki/Breaking-Changes-in-upcoming-V8) are really necessary.

The VirtualTree V8 code includes a new unit VirtualTrees.BaseTree.pas, which defines basic types (e.g. TVirtualNode and PVirtualNode). These types were previously in the VirtualTrees.pas unit.

If you install the current VirtualTree V8 state into the IDE and want to build old existing projects with it, this is not possible anymore, because these basic types are not found anymore. You have to adjust manually and add the new unit VirtualTrees.BaseTree.pas in the uses clause. This means: change of all old projects.

I would like to bypass this task and ask for a compatible solution in the VirtualTree project.
This would be a lot of work that will affect many projects worldwide.

Suggestion: use Include files in VirtualTrees.pas.

Thanks.

**Comment by joachimmarder** [comment]
These changes were done by @livius2 for creating the FMX port of Virtual TreeView. Please use issue #1134 for discussion of changes in this context.

**Comment by livius2** [comment]
We probably can add alias in VirtualTrees.pas

```
  PVirtualNode = VirtualTrees.BaseTree.PVirtualNode;
  TVirtualNode = VirtualTrees.BaseTree.TVirtualNode;
```

@joachimmarder what do you think? Any drawbacks?

**Comment by joachimmarder** [comment]
I'm not aware of any drawbacks and use aliases frequently.

**Comment by joachimmarder** [comment]
Let me know if there is any other important type affected.

**Comment by joachimmarder** [comment]
@livius2 : Many simple types are defined in the unit `VirtualTrees.BaseTree`, but simple types should better be placed in unit `VirtualTrees.Types` in my opinion. Is there anything that speaks against this?

That would make switching between V7 and V8 much easier.

**Comment by livius2** [comment]
> Is there anything that speaks against this?

Only circular unit reference nothing more.

**Comment by joachimmarder** [comment]
It should be possible to reduce the amount of breaking changes to what is already documented in the [Wiki](https://github.com/JAM-Software/Virtual-TreeView/wiki/Breaking-Changes-in-upcoming-V8).
