### ISSUE TITLE
Suggested feature: OnBeforePopupmenu

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1163]
The suggestion is to add another event. It would be called when somebody wants to open the assigned popup menu by right clicking on the VST and would provide the node which was clicked on.

It might be used for actions like closing the popup menu if opened on a node where it shouldn't get opened or to disable some items in the popup menu which should not be available for the node clicked etc.

**Comment by livius2** [comment]
Use current OnPopup event of your Popupmenu and use VT.FocusedNode to check what was clicked.

**Comment by joachimmarder** [comment]
Can you cancel / prevent a popup that way?

**Comment by livius2** [comment]
yes, use `abort`

**Comment by MHumm** [comment]
Ok, if I can cancel the popup that way that would be usable and not require any VST modification.

**Comment by joachimmarder** [comment]
Yes, that should work. And there are alternatives: We have an application that has a special popup menu for the root node, a normal popup menu and some nodes for that no popup should be shown, and we simply assign the `PopupMenu` property accordingly in the `OnChange` event.
