### ISSUE TITLE
Error when closing the window/application

### ISSUE THREAD

**Issue by jBitHub** [JAM-Software/Virtual-TreeView#1164]
I have updated to the latest version. Since then, there is always an error when closing windows or the application. Our application is very complex. The error is not traceable in simple test applications.

Project Archikart.exe raised exception class EOSError with message:
	'Systemfehler.  Code: 87. Falscher Parameter'
	'System error.  Code: 87. wrong parameter'

:7678e292 KERNELBASE.RaiseException + 0x62
System.SysUtils.RaiseLastOSError
:00be79d8 RaiseLastOSError + $C
System.SysUtils.RaiseLastOSError
Vcl.Controls.TWinControl.CreateWnd
Vcl.Controls.TWinControl.CreateHandle
Vcl.Controls.TWinControl.HandleNeeded
Vcl.Controls.TWinControl.GetHandle
Vcl.Forms.TScrollingStyleHook.InitScrollBars
VirtualTrees.StyleHooks.TVclStyleScrollBarsHook.Create($7E2C0930)
Vcl.Styles.CreateStyleHook($7D8B8E00)
Vcl.Styles.TStyleEngine.HandleMessage($7E2C0930,(130, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()),(VirtualTrees.BaseTree.TBaseVirtualTree.WndProc,$7E2C0930))
Vcl.Themes.TStyleManager.HandleMessage($7E2C0930,(130, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()),(VirtualTrees.BaseTree.TBaseVirtualTree.WndProc,$7E2C0930))
Vcl.Controls.TWinControl.DoHandleStyleMessage(???)
Vcl.Controls.TWinControl.WndProc((130, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
VirtualTrees.BaseTree.TBaseVirtualTree.WndProc((130, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Controls.TWinControl.MainWndProc(???)
System.Classes.StdWndProc(1183260,130,0,0)
:76db148b user32.AddClipboardFormatListener + 0x4b
:76da844a ; C:\Windows\SysWOW64\user32.dll
:76da804a ; C:\Windows\SysWOW64\user32.dll
:76daf987 user32.GetClassNameW + 0x67
:77404fbd ntdll.KiUserCallbackDispatcher + 0x4d
Vcl.Controls.TWinControl.Destroy
Vcl.Controls.TCustomControl.Destroy
System.TObject.Free
J0004VCLExtCtrlsClients.J0004ClientProperty.Destroy
System.TObject.Free
System.Contnrs.TObjectList.Notify($71EECBD0,lnDeleted)
System.Classes.TList.Delete(???)
J0004VCLExtCtrlsClients.J0004ClientProperties.Delete(1)
J0004VCLExtCtrlsClients.J0004ClientProperties.Clear
L0000VCLDesktopWindowPageU.TDesktopWindowPage.AK_removeViewParts
L0000VCLDesktopWindowPageU.TDesktopWindowPage.Destroy
System.TInterfacedObject._Release
System._IntfClear(???)
Vcl.Forms.TCustomForm.DoClose(???)
Vcl.Forms.TCustomForm.Close
C0000VCLDesktopWindowFU.TAk4Desktop.acCloseExecute($6DFD4850)
System.Classes.TBasicAction.Execute
Vcl.ActnList.TCustomAction.Execute
System.Classes.TBasicActionLink.Execute(???)
Vcl.ActnMenus.TCustomActionMenuBar.ExecAction(???)
Vcl.ActnMenus.TCustomActionMenuBar.TrackMenu
Vcl.ActnMenus.TCustomActionMainMenuBar.TrackMenu
Vcl.ActnMenus.TCustomActionMenuBar.CMItemClicked(???)
Vcl.Controls.TControl.WndProc((2326, 0, 2128045232, 0, 0, 0, (), 25776, 32471, (), 0, 0, ()))
Vcl.Controls.TWinControl.WndProc((2326, 0, 2128045232, 0, 0, 0, (), 25776, 32471, (), 0, 0, ()))
Vcl.ActnMenus.TCustomActionMenuBar.WndProc((2326, 0, 2128045232, 0, 0, 0, (), 25776, 32471, (), 0, 0, ()))
Vcl.Controls.TWinControl.MainWndProc(???)
System.Classes.StdWndProc(1249710,2326,0,2128045232)
Vcl.Forms.TApplication.ProcessMessage(???)
:001f654e TWinControl.Destroy + $AE

**Comment by joachimmarder** [comment]
> I have updated to the latest version

The V7.6.3 release or the master branch?

Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project as ZIP to your report, or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by joachimmarder** [comment]
What I can see from the call stack: The root cause seems to be that the control is destroyed, and then a style hook is created for the destroyed control:
```
Vcl.Styles.CreateStyleHook($7D8B8E00)
Vcl.Styles.TStyleEngine.HandleMessage($7E2C0930,(130, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()),$7E2C0930)
[...]
Vcl.Controls.TWinControl.Destroy
Vcl.Controls.TCustomControl.Destroy
```
It doesn't surprise me that this causes trouble. Virtual TreeView code is not involved in this call stack, except for inherited calls to base classes.

**Comment by jBitHub** [comment]
Thank you for the quick reply.
It is the "master" version of 29 December 22. I think that is version 7.6.2. Delphi 11.2. We have been using VirtualTree for years. But it is only with the version from 29.12. that it always crashes. In small test applications I cannot reproduce the problem. But I have already written that. So I can't upload a project.
The code (VirtualTrees) from us is unchanged for years. The code in the stack is from VirtualTree and from Delphi. Nothing from us. 
I don't know what the point of their statement is:
 "It doesn't surprise me that this causes trouble. Virtual TreeView code is not involved in this call stack, except for inherited calls to base classes."
The VirtualTree code before (before 29.12.) still ran with Delphi 11.2.
In this case, a scroll event is triggered. However, nothing is scrolled. The program or a window is closed.

**Comment by joachimmarder** [comment]
> It is the "master" version of 29 December 22. I think that is version 7.6.2

If you use the master branch, then you are using the unstable development version V8. Using the last stable version V7.6.3 should fix the problem for now.

> The VirtualTree code before (before 29.12.) still ran with Delphi 11.2

I guess the changes for #1016 are responsible for the problem. These changes are important as they replace code for VCL themes, that was copied many years ago from VCL, by inherited calls, that call the current code. This fixes issues like #1155, that result from this copied code, but are already fixed in the VCL.

> In small test applications I cannot reproduce the problem.

If I don't have a test project, I cannot analyze the problem and find a fix for it.

**Comment by jBitHub** [comment]
It is the "master" version from 29 December 2022. I think that is version 7.6.2. We have been using VirtualTree for years. But it is only with the version from 29.12. that it always crashes. In small test applications I cannot reproduce the problem. But I have already written that. So I can't upload a project.

**Comment by jBitHub** [comment]
Thank you very much for your efforts. With stable v7.6.3 our programme works.
