### ISSUE TITLE
toRestoreSelection won't work for items selected with Shift+click

### ISSUE THREAD

**Issue by iyudincev** [JAM-Software/Virtual-TreeView#1166]
When multiple adjacent items are selected with the option `toRestoreSelection` on, then after refill the selection is restored for only one of the items. Selection with dotted frame works the same way. Ctrl+click works fine.

**Comment by joachimmarder** [comment]
Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project as ZIP to your report, or instructions how to modify one of the included sample projects to reproduce the problem.

**Comment by joachimmarder** [comment]
I was able to replicate the issue in my own project. The reason is, that there are two overloads of `AddSelection()`, and the one that receives multiple items does not take care of `toRestoreSelection`.

**Comment by joachimmarder** [comment]
Can you please confirm that the added fix solves the problem for you?

**Comment by iyudincev** [comment]
> Can you please confirm that the added fix solves the problem for you?

A corner case is left uncovered, when no selection exist (when the app has just started) and the user shift-clicks on the control or starts selecting items with a dotted frame. In this case the app generates an access violation.

**Comment by iyudincev** [comment]
The problem has been solved, thanks!
