### ISSUE TITLE
Column text does not get translated

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1168]
I use dxgnugettext for translation support and the column text property does not get translated.  This is a side effect of

```pascal
    property Columns              : TVirtualTreeColumns read FColumns write SetColumns stored False; //Stored by the owner tree to support VFI.
```

The TVTHeader Columns property is not strored with the header and instead is stored by the tree's DefineProperties.   This is according to the comments to support Visual Form Inheritance.

Is VFI still an issue and is the way it is done the correct solution?  This does make it quite hard to support translations of UI,

**Comment by joachimmarder** [comment]
I can't comment much on this property and the problems it caused with form inheritance, as far as I remember the code was that way when I took over the project a few years ago.

I am open to change this for V8. We at JAM Software use GnuGetText, but create columns at runtime and are so not affected by the problem.

**Comment by joachimmarder** [comment]
Can you please try if a call to `TGnuGettextInstance.TranslateComponent()` successfully translates the header?

I have not good test project at hand. Feel free to send a pull request.

**Comment by pyscripter** [comment]
Well this is the problem. TranslateComponent() calls TranslateProperties and if a class property (Columns) is not stored, it does not get translated.   

I will try to see whether VFI is still an issue,  but even if it isn't,  changing the Columns property to stored and removing it from DefineProperties would create backward incompatibilities at the dfm level.

A workaround is to manually translate Column.Text for all columns, every time there is a language change.  Not good either. 
Another option is to register a custom translator for TVTHeader with TP_GlobalHandleClass and this is probably the easiest way if you have many VirtualTrees as in PyScripter.

**Comment by joachimmarder** [comment]
The idea was to call `TGnuGettextInstance.TranslateComponent()` on the `Columns` property, but I just recognized it is only a `TPersistent`, not a `TComponent`, so that won't work.

If you send a sample project with visual form inheritance, GnuGetText and designtime columns I can see what I can do. But since it is that way for >15 years, it is somewhat low priority.

**Comment by pyscripter** [comment]
I found a solution which is simple and backward compatible:

```pascal
  TVTHeader = class(TPersistent)
  private
    FStoreColumns                : Boolean;
  public
    property StoreColumns: Boolean read FStoreColumns write FStoreColumns;
  published
    property Columns              : TVirtualTreeColumns read FColumns write SetColumns stored FStoreColumns; //Stored by the owner tree to support VFI.
```

and in TBaseVirtualTree.Loaded add:

```pascal
  if not (csDesigning in ComponentState) then
    FHeader.StoreColumns := True;
```

@joachimmarder  It works and  I don't see any undesirable side effects.  What do you think?

**Comment by joachimmarder** [comment]
The workaround looks OK and was easier than I expected. But that makes me wonder, why GnuGetText does not translate a property, in case `stored` is `False`?! 

If a property is not stored, is still may have a default value assigned via constructor, or it may be serialized in some other way, like the `Columns` property here. But in both cases it should not be excluded from translation. I think this is more a bug in GnuGetText.

**Comment by pyscripter** [comment]
> The workaround looks OK and was easier than I expected. But that makes me wonder, why GnuGetText does not translate a property, in case `stored` is `False`

There are good reasons for that.  For instance:

```pascal
  TControl = class(TComponent)
    property Caption: TCaption read GetText write SetText stored IsCaptionStored;

function TControl.IsCaptionStored: Boolean;
begin
  Result := (ActionLink = nil) or not ActionLink.IsCaptionLinked;
end;
```
You don't want to translate twice an Action linked caption.  Also, if you  were to translate the Control Caption by assigning a translated value, you would break the link to the Action.

**Comment by pyscripter** [comment]
Even simpler solution!
Thanks!

**Comment by joachimmarder** [comment]
> You don't want to translate twice an Action linked caption. Also, if you were to translate the Control Caption by assigning a translated value, you would break the link to the Action.

Sure! But is this done by checking if `stored` is `False`? And is it correct to *not* translate all `stored false` properties?
