### ISSUE TITLE
Increase width of splitter column, which is nearly invisible

### ISSUE THREAD

**Issue by chuacw** [JAM-Software/Virtual-TreeView#1172]
Increase the width of the splitter column, which is nearly invisible, on high resolution screens.

Provide a property to increase the width, as SplitterHitTolerance doesn't do anything with regards to visibility, since in order to move your mouse over the splitter, you have to see it first.

**Comment by joachimmarder** [comment]
I agree that ideally the line thickness of the splitter should depend on the dpi, which seems currently not to be the case. 

But this can get tricky, as the actual painting is done by a call to `StyleServices.DrawElement()` with `thHeaderItem*`. In Delphi 10.4 and higher, this call takes the dpi as parameter, but it seems not to make any difference. `TListView` columns and the VCL `THeaderControl` behave the same way. Also Windows File Explorer and the File Open dialogs do not scale the splitter line, it is 1 pixel on a screen scaled to 200%.

My conclusion is that this would be better solved on the level of VCL styles or the OS. 

I added a hack to the master branch which doubles the width of the splitter line on scaled screens.
