### ISSUE TITLE
Drop support for Windows "classic mode"

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#1173]
Windows 7 was the last version of the operating system that supported the classic mode, which is the look introduced with Windows 95, that does not support theming. Most methods that do painting have two code paths, one for the old classic mode and one that uses the theming engine of Windows / the style services of the VCL. With the many refactorings that have been done for Virtual TreeView V8 there is a high likelihood some code paths for the classic modes are broken. However, no active testing takes places as all operating systems are outdated which still have the classic mode.

Therefore, I think the best option for those that still need to support the Windows classic mode, is to stick with the stable V7 branch and to officially deprecate the support for the classic mode in V8.

**Comment by gwideman** [comment]
It would be helpful to state explicitly that Classic Mode is the mode set by Property XYZ = abc.  Otherwise it's not so clear whether an existing application does or does not use VTV in "Classic Mode". Thanks.

**Comment by joachimmarder** [comment]
There is no such property, just several places where code is used as fallback if no theme / style support is available, like on old Windows Server versions. The problem is that this code is neither tested nor maintained for years.
