### ISSUE TITLE
Changing SortDirection works in 32bit, but not in 64bit

### ISSUE THREAD

**Issue by buddyworks** [JAM-Software/Virtual-TreeView#1175]
Hi, 

using: C++ Builder 10.2 Update 3 + VirtualTreeView 7.6.3

I create a new application, drop a new VST on it, add two columns, activate `hoVisible` to see the column headers and implement the `OnHeaderClick` method as

```
Sender->SortDirection = (Sender->SortDirection == sdAscending) ? sdDescending : sdAscending;
Sender->SortColumn = HitInfo.Column;
```

In 32bit, everything is fine, the sort directions changes with every header click as expected.

Same app in 64bit changes only once. After it stays at the last direction and will not change anymore.

Any ideas?

Regards,
Michael

**Comment by buddyworks** [comment]
"Unfortunately" the problem does not occur in Delphi, just BCB.

**Comment by joachimmarder** [comment]
I don't use C++ Builder and can only suspect it has to do with code generation of the c++ compiler or the generated HPP files. On the Delphi side, you could experimenmt with [`$MINENUMSIZE 4`](https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Minimum_enumeration_size_(Delphi)) or [`$ALIGN 8`](https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Align_fields_(Delphi)).

Please send a pull request once you solved the problem.
