### ISSUE TITLE
Strange behaviour within OnEdited

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#118]
_From [co...@gmx.net](https://code.google.com/u/117529545742351141745/) on February 19, 2010 09:25:53_

What steps will reproduce the problem? 1. Place a TVirtualStringTree on a form
2. Create two columns, set Header.MainColumn = 1
3. OnInitNode: Include(InitialStates, ivsMultiline);
4. OnEdited: Sender.EditNode(Sender.GetNext(Node), Column);
5. Go into Editmode, push Ctrl+Enter What is the expected output? What do you see instead? When editing is completed, the event OnEdited will be raised once. But if 
you call EditNode within OnEdited, the event will occour twice and start 
editing two nodes below. It should edit the next node, but it always skips 
that - because the event is called twice. What version of the product are you using? On what operating system? Latest SVN-Build r250 . Windows 7 Ultimate x64. Please provide any additional information below. The strange part about this is that the second call only appears if 
EditNode is called within OnEdited. And what bugs me even more is the fact 
that it is called EXACTLY twice. I would expect it to go into an 
indefinate loop.
I guess the event is not called as a last step but rather the last step is 
called after the event which in return finishes the newly started editmode 
(and calls the event) but does not interfere with anything else after that.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=118_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 18, 2013 13:49:46_

Is this problem still present in the latest version?

**Owner:** joachim....@gmail.com  
  **Labels:** -Priority-Medium Priority-Low

**Comment by vincentparrett** [comment]
_From [co...@gmx.net](https://code.google.com/u/117529545742351141745/) on December 19, 2013 03:07:31_

I've got a very full schedule at the moment, but I'll try to test it before
the end of the year.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on June 01, 2014 13:28:19_

Would you mind checking if this issue is still present in V5.4.1?

**Comment by vincentparrett** [comment]
_From [co...@gmx.net](https://code.google.com/u/117529545742351141745/) on June 02, 2014 04:56:01_

Just had a look. The issue still exists.

Sorry about not answering sooner, but by the time I could have done it, I
had completely forgotten about the issue.

**Comment by sanjayssk** [comment]
> 5. Go into Editmode, push Ctrl+Enter What is the expected output? What do you see instead?
I see that it correctly goes back into editing the same node. I even tried doing it with the old 5.4.1 source just to confirm, suspecting a fixed bug. There also, I see the same behavior.
Why would someone call EditNode in OnEdited? For validation of the edited text. I think I will just make a small validation case and check that the tree reenters the edit for the same node till canceled. As long as that works, there is no need to go deeper than that.

**Comment by joachimmarder** [comment]
> Why would someone call EditNode in OnEdited?

Maybe if the entered test did not pass validation and one wants to force the user to correct the entered text.

**Comment by sanjayssk** [comment]
Yes, I already mentioned that: For validation of the edited text. What I mean is, since I CAN NOT recreate this problem, I will just test the validation and reedit feature once and then leave it at that.

**Comment by sanjayssk** [comment]
Oops, missed typing "CAN NOT" recreate the problem in previous comment. Corrected.

**Comment by sanjayssk** [comment]
I created a proper validation sequence. Set the new text in an OnNewText event. Then in OnEdited, if a certain string "reedit" is found, call Sender.EditNode(Sender.GetNext(Node), Column) as described in the issue. This works fine and the editing starts again in the same cell.
Conclusion: Can not recreate this problem. Closing.
