### ISSUE TITLE
Issue with default color properties saving into dfm

### ISSUE THREAD

**Issue by MShark67** [JAM-Software/Virtual-TreeView#1184]
The current version appears to be saving the Colors property to the dfm file as actual colors instead of as system tcolor values.

Steps:
New vcl project
Drop a TVirtualStringTree on the form.
Save the project.

Note that the dfm file will contain the following for the colors property.   It shouldn't save them at all since they should be the defaults, but if they do have to save they should be saving using the system color entries (e.g. clHighlight) so they will theme properly.

    Colors.BorderColor = 15987699
    Colors.DisabledColor = clGray
    Colors.DropMarkColor = 15385233
    Colors.DropTargetColor = 15385233
    Colors.DropTargetBorderColor = 15385233
    Colors.FocusedSelectionColor = 15385233
    Colors.FocusedSelectionBorderColor = 15385233
    Colors.GridLineColor = 15987699
    Colors.HeaderHotColor = clBlack
    Colors.HotColor = clBlack
    Colors.SelectionRectangleBlendColor = 15385233
    Colors.SelectionRectangleBorderColor = 15385233
    Colors.SelectionTextColor = clBlack
    Colors.TreeLineColor = 9471874
    Colors.UnfocusedColor = clGray
    Colors.UnfocusedSelectionColor = clWhite
    Colors.UnfocusedSelectionBorderColor = clWhite

Let me know if you need additional details.  Using Delphi 11.3.

**Comment by MShark67** [comment]
It looks like this problem was introduced with commit ed760f8 where support for Delphi 11's design time styles was introduced.  Since TVTColors uses styles for colors at the property level it causes issues both with setting colors in the designer and with writing colors to the dfm file.  It looks like standard Delphi components handle this by only styling colors while painting and not when properties that will be stored are accessed.

**Comment by joachimmarder** [comment]
In case design-time theming is enabled in newer RAD Studio versions, `TVTColors.GetColor()` returns colors of the development system and so the default values are overwritten and hence stored in the DFM file. Hard to say what design-time theming should do here and what not. The old behavior can easily be restored by adding an additional condition `not (csDesigning in FOwner.ComponentState)` in `GetColor()`.
