### ISSUE TITLE
TVirtualStringTree shows previously selected items as grayed

### ISSUE THREAD

**Issue by Molochnik** [JAM-Software/Virtual-TreeView#1185]
The test project is attached, steps to reproduce the behaviour
1) Press "Button1" to show a modal form Form2
2) Select some items in VirtualStringTree (MultiSelect is true)
3) Press "btnClose" button to hide Form2
4) Press "Button1" to show the modal form Form2 again
5) All previously selected items look grayed. Why?

I have no idea if such behavior is intended or not, but I can't remember if the older (1-2 years ago maybe) versions acted like that.

[1.zip](https://github.com/JAM-Software/Virtual-TreeView/files/11064730/1.zip)

**Comment by MShark67** [comment]
It appears this is directly related to the issue I entered yesterday.  #1184 .   You can temporarily fix it by changing your TForm2.FromCreate as follows:

```
procedure TForm2.FormCreate(Sender: TObject);
begin
  VirtualStringTree1.RootNodeCount := 200;
  // Fixing a bug related to how the VTree saves its colors:
  VirtualStringTree1.Colors.BorderColor := clBtnFace;
  VirtualStringTree1.Colors.DisabledColor := clBtnShadow;
  VirtualStringTree1.Colors.DropMarkColor := clHighlight;
  VirtualStringTree1.Colors.DropTargetColor := clHighlight;
  VirtualStringTree1.Colors.DropTargetBorderColor := clHighlight;
  VirtualStringTree1.Colors.FocusedSelectionColor := clHighlight;
  VirtualStringTree1.Colors.FocusedSelectionBorderColor := clHighlight;
  VirtualStringTree1.Colors.GridLineColor := clBtnFace;
  VirtualStringTree1.Colors.HeaderHotColor := clBtnShadow;
  VirtualStringTree1.Colors.HotColor := clWindowText;
  VirtualStringTree1.Colors.SelectionRectangleBlendColor := clHighlight;
  VirtualStringTree1.Colors.SelectionRectangleBorderColor := clHighlight;
  VirtualStringTree1.Colors.SelectionTextColor := clHighlightText;
  VirtualStringTree1.Colors.TreeLineColor := clBtnShadow;
  VirtualStringTree1.Colors.UnfocusedColor := clInactiveCaptionText;
  VirtualStringTree1.Colors.UnfocusedSelectionColor := clInactiveCaption;
  VirtualStringTree1.Colors.UnfocusedSelectionBorderColor := clInactiveCaption;
end;
```
-Mark

**Comment by Molochnik** [comment]
Probably, I noticed it 2-3 months ago though didn't consider it as an issue, just a nuisance maybe. I'll better wait for an internal fix.

**Comment by joachimmarder** [comment]
Can you please confirm that the issue is fixed with the latest changes?

**Comment by Molochnik** [comment]
Yes, the issue is fixed. Thanks!
