### ISSUE TITLE
Lines with different bg colors

### ISSUE THREAD

**Issue by Molochnik** [JAM-Software/Virtual-TreeView#1186]
It's easier to view than to explain, the code is attached
1) Press Button1 to show the window Form2 with the TVirtualStringTree object
2) **Odd** and **Even** rows are colored and painted differently. The idea is that **Even** rows have light green color in non-selected state and thick green in selected state. I have not been able to find a way other than presented in the example to make it work and it works fine.
3) Also there is a timer on the form Form2 that constantly switches the three Actions between Enabled and Disabled state. Each of the Actions is presented on the toolbar Toolbar1. When the Form2 is shown Toolbar1 starts blinking with 2 sec period (buttons are enabled for 1 sec and disabled for 1 sec).
4) Now the issue. If you select an **Odd** row everything works fine but if you select an **Even** row (colored) the Toolbar1 stops blinking. It looks as if the toolbar stops being repainted, selecting an **Odd** row unfreezes the toolbar.  I have no idea why and how painting of the tree affects the completely independent toolbar.
[2.zip](https://github.com/JAM-Software/Virtual-TreeView/files/11081603/2.zip)

**Comment by joachimmarder** [comment]
Very strange. I was able to replicate the problem with Delphi 11.3 Virtual TreeView V7.6.4. 

>  I have no idea why and how painting of the tree affects the completely independent toolbar.

It seems not the painting that is not working, but the timer.
Commenting the line 

`Colors.FocusedSelectionColor := COLOR_GOOD_THICK;
`

makes the problem disappear. Can you confirm?

**Comment by joachimmarder** [comment]
In each paint you are changing the FocusedSelectionColor twice (once in `SetDefaultColors()`), this causes a repaint, and here you are changing the FocusedSelectionColor again. This ends up in a repaint loop and so timer messages don't get through.

**Comment by Molochnik** [comment]
Thanks for clarification. Is there a workaround to make the TVirtualStringTree to colorize lines like I want but without entering the loop or better to wait for another version?

**Comment by joachimmarder** [comment]
The issue is fixed and the repaint loop prevented.

**Comment by Molochnik** [comment]
:))  that was fast!
