### ISSUE TITLE
Error when closing the window/application (2) - V7_stable

### ISSUE THREAD

**Issue by jBitHub** [JAM-Software/Virtual-TreeView#1187]
Version V7_stable (27.03.2023)
I have already reported the error (origin/master) once.
Error when closing the window/application #1164 

At that time I was referred to the stable version of VirtualTree. Now, however, the error has been merged into the stable.
I either close a window or the application with a VirtualTree. 
Event 130 (WM_NCDESTROY) is triggered.
---   VirtualTrees.BaseTree.TBaseVirtualTree.WndProc((130, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
A TVclStyleScrollBarsHook (VirtualTrees.StyleHooks.pas) is then created.
---   VirtualTrees.StyleHooks.TVclStyleScrollBarsHook.Create($7E2C0930)
Creating was also done earlier. Even though I think this is already wrong, it did not lead to an error earlier. 
1. error stack
2. code differences leading to the error listed.
	Previously, the code from "VirtualTrees.StyleHooks.pas" would be executed. Then the compiler directive: NOT_USE_VCL_STYLEHOOK was introduced and the original Delphi code is executed.

(1.)
![grafik](https://user-images.githubusercontent.com/39560844/231140179-b99983c1-5592-4182-97d8-e9e66f68bbd3.png)

(2.)
![grafik](https://user-images.githubusercontent.com/39560844/231140321-d8aa2ac7-f0ff-4687-9065-4d6408c5af9e.png)
Code that was executed earlier.
![grafik](https://user-images.githubusercontent.com/39560844/231140371-3a68ae1c-2fc9-4179-a451-3e4812146347.png)

Code that is now being executed. The border shows the error.
![grafik](https://user-images.githubusercontent.com/39560844/231140422-3ac9519d-837d-40c6-8e29-e757bd0fb86d.png)

**Comment by joachimmarder** [comment]
> At that time I was referred to the stable version of VirtualTree. Now, however, the error has been merged into the stable.

The merge was necessary to fix issues in the derived style hook in newer Delphi versions. And therefore my answer won't be very different compared to the other issue:

Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Delphi, and attach a sample compiling project as ZIP to your report, or instructions how to modify one of the included sample projects to reproduce the problem.

What I can see from the call stack: The root cause seems to be that the control is destroyed, and then a style hook is created for the destroyed control:
```
Vcl.Styles.CreateStyleHook($7D8B8E00)
Vcl.Styles.TStyleEngine.HandleMessage($7E2C0930,(130, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()),$7E2C0930)
[...]
Vcl.Controls.TWinControl.Destroy
Vcl.Controls.TCustomControl.Destroy
```
It doesn't surprise me that this causes trouble. Virtual TreeView code is not involved in this call stack, except for inherited calls to base classes.

**Comment by joachimmarder** [comment]
> Code that is now being executed. The border shows the error.

This is code from unit `Vcl.Forms`, not of Virtual Treeview.

**Comment by jBitHub** [comment]
After hours of searching, I found the error. I have uploaded a small project (Delphi 11.3)
[J9075 VirtualTree-Error.zip](https://github.com/JAM-Software/Virtual-TreeView/files/11220547/J9075.VirtualTree-Error.zip)

- Adjust search path (maybe)
- Press button: "Panel.Free"
- Exception

Problem:
- Styles switched on
- Delete parent.

It would be convenient to insert some code for debugging. Then unimportant events are skipped.
Methode:
VirtualTrees.pas: procedure TBaseVirtualTree.WndProc(var Message: TMessage); [25853]
![grafik](https://user-images.githubusercontent.com/39560844/231716410-ae5e9fda-c5e9-4090-b9bd-8edb3df9827e.png)

**Comment by joachimmarder** [comment]
> After hours of searching, I found the error. I have uploaded a small project (Delphi 11.3)

Thank you for this. I hope you understand, that with the information I had, it would be impossible to track down the problem.

> VirtualTrees.pas: procedure TBaseVirtualTree.WndProc(var Message: TMessage); 

The exception occurs even if I comment `TBaseVirtualTree.WndProc()`, then without any VTV unit in the call stack. I am still convinced that the VCL should not create a style hook for destroyed control in the first place, maybe I can find some workaround.

**Comment by joachimmarder** [comment]
Can you confirm that the latest source fixes the issue for you?

**Comment by jBitHub** [comment]
Thank you very much for the quick help.
The error no longer occurs with me.

>Thank you for this. I hope you understand, that with the information I had, it would be impossible to track down the problem.

Yes, I understand. I had hoped you would find the mistake anyway. The combination of style and parent-destroy is quite unique.
