### ISSUE TITLE
Incorrect function signature in C++

### ISSUE THREAD

**Issue by 7even11** [JAM-Software/Virtual-TreeView#1188]
1) place VirtualStringTree on a form

2) add 2 events by double clicking in the event list. The following signatures are added:

```
void __fastcall VirtualStringTree1HeaderClick(TVTHeader *Sender, TVTHeaderHitInfo &HitInfo);
void __fastcall VirtualStringTree1MouseWheel(TObject *Sender, TShiftState Shift, int WheelDelta, TPoint &MousePos, bool &Handled);
```
3) now try assigning directly to the tree those events (for example it may be another tree using the exact same events):

```
VirtualStringTree1->OnHeaderClick = VirtualStringTree1HeaderClick;
VirtualStringTree1->OnMouseWheel = VirtualStringTree1MouseWheel;
```

4) the errors:

[bcc32c Error] Unit1.cpp(14): assigning to 'Virtualtrees::TVTHeaderClickEvent' (aka
```
'void ((__closure *))(Virtualtrees::TVTHeader *, const Virtualtrees::TVTHeaderHitInfo &) __attribute__((fastcall))'
```
) from incompatible type
```
'void (__closure *)(Virtualtrees::TVTHeader *, Virtualtrees::TVTHeaderHitInfo &) __attribute__((fastcall))'
```

[bcc32c Error] Unit1.cpp(15): assigning to 'Vcl::Controls::TMouseWheelEvent' (aka
```
'void ((__closure *))(System::TObject *, System::Classes::TShiftState, int, const System::Types::TPoint &, bool &) __attribute__((fastcall))'
```
) from incompatible type
```
'void (__closure *)(System::TObject *, System::Classes::TShiftState, int, System::Types::TPoint &, bool &) __attribute__((fastcall))'
```

The errors happen because the function signatures are not identical in C++. When the event is inserted by double clicking the name of the event in the Object Inspector / Events, the event is inserted with the wrong signature, or at least the signature doesn't match what the header (.hpp) file contains.

The header file (**VirtualTrees.hpp**) contains:

```
typedef void __fastcall (__closure *TVTHeaderClickEvent)(TVTHeader* Sender, const TVTHeaderHitInfo &HitInfo);
```
So ```Virtualtrees::TVTHeaderHitInfo``` is a **const** value, however, when assigning via object inspector it adds without the const.

The same for **TMouseWheelEvent**

```
const System::Types::TPoint
```

The signatures should be correctly assigned when using object inspector.

The bug can be workarounded by manually modifying the signature after object inspector has inserted it into the code:

```void __fastcall TForm1::VirtualStringTree1HeaderClick(TVTHeader *Sender, TVTHeaderHitInfo &HitInfo)```
into
```void __fastcall TForm1::VirtualStringTree1HeaderClick(TVTHeader *Sender, const TVTHeaderHitInfo &HitInfo)```

and

```void __fastcall TForm1::VirtualStringTree1MouseWheel(TObject *Sender, TShiftState Shift, int WheelDelta, TPoint &MousePos, bool &Handled)```
into
```void __fastcall TForm1::VirtualStringTree1MouseWheel(TObject *Sender, TShiftState Shift, int WheelDelta, const TPoint &MousePos, bool &Handled)```

But the object inspector should be inserting correct signatures regardless and this should be fixed in Virtual-TreeView code.

Example attached.

I checked also Delphi, it seems to me that in Delphi too the function signature should contain const for HitInfo and TPoint if these are meant to be really const. Otherwise it is likely picking that up from:

TBaseVirtualTree.DoHeaderClick(const HitInfo: TVTHeaderHitInfo);

Where it is declared as const, but in C++ that has likely to be explicit where in Delphi, it might be accepted if implicit because the following works just fine in Delphi:

```
procedure TForm1.Button1Click(Sender: TObject);
begin
VirtualStringTree1.OnHeaderClick := VirtualStringTree1HeaderClick;
end;

procedure TForm1.VirtualStringTree1HeaderClick(Sender: TVTHeader; HitInfo: TVTHeaderHitInfo);
begin
//
end;
```

If this is not supposed to be const, then the .hpp file should contain the correct signature without the const, then it is not the issue with Object Inpector inserting wrong signature but the issue with the .hpp file.

[_VTREE-BUG-FnDef.ZIP](https://github.com/JAM-Software/Virtual-TreeView/files/11233004/_VTREE-BUG-FnDef.ZIP)

**Comment by joachimmarder** [comment]
Which version of C++ Builder and Virtual TreeView are you using?

> If this is not supposed to be const, then the .hpp file should contain the correct signature without the const

I agree, but the .HPP files are generated by your RAD Studio when installing the package, so I'm not sure if we can do anything about it.

**Comment by 7even11** [comment]
I am using RAD Studio 10.4.2. VirtualTreeView is the latest.

The .HPP files can be modified to emit proper output, if needed, by using https://docwiki.embarcadero.com/RADStudio/Sydney/en/Delphi_Compiler_Directives_(List)_Index

Such as HPPEMIT, NODEFINE, EXTERNALSYM, IF, IFDEF...

**Comment by zencode1** [comment]
This is a bug in the IDE Object Inspector when an event handler is added for an event containing a record parameter without `var`, `const`, or `out` modifiers.

The Delphi compiler generates the same signature for C++ code whether the parameter is declared `HitInfo: TVTHeaderHitInfo` or `const HitInfo: TVTHeaderHitInfo`.  One way to fix this to work in both Delphi and C++Builder is to change the event declaration to:
```
  TVTHeaderClickEvent = procedure(Sender: TVTHeader; const HitInfo: TVTHeaderHitInfo) of object;
```

However, I don't know if this will break any existing code.  An acceptable workaround is for the C++ event handler to be manually altered the way @7even11 mentioned as their workaround.

TMouseWheelEvent is not a VirtualTree type.  It is declared in Vcl.Controls.pas.
