### ISSUE TITLE
OnEditCancelled not fired any more

### ISSUE THREAD

**Issue by haraldhuth** [JAM-Software/Virtual-TreeView#1189]
After Changing to Delphi 11.3 the OnEditCancelled Event is not fired any more. Everything worked fine in Delphi 10.4.

**Comment by joachimmarder** [comment]
Please respect our rules for submitting bug reports and include the version number of Virtual TreeVire that you are using, and if the issue can be replicated with one of the included sample projects.

**Comment by joachimmarder** [comment]
I tested this with V7.6.5 and the `Advanced` sample project, form `PropertiesDemo`, and the event was fired. Please provide more info on this issue, @haraldhuth.

**Comment by joachimmarder** [comment]
Closing this issue due to a missing response of the reporter regarding repro steps.
