### ISSUE TITLE
Method `TBaseVirtualTree.GetOffsets` unnecessarily applies `FImagesMargin` in most cases

### ISSUE THREAD

**Issue by hermannoffen** [JAM-Software/Virtual-TreeView#1191]
### Problem

Method `TBaseVirtualTree.GetOffsets` (introduced in #369) incorrectly applies `FImagesMargin` for `TVTElement.ofsCheckBox` when no check image is needed. Thus, its _out_-param `pOffsets` then contains values two pixels too high for `TVTElement.ofsCheckBox` and all following elements.

### Observations

This can, for example, cause a wrong result of `TBaseVirtualTree.GetMaxColumnWidth`, making autosized columns wider than necessary.
It might also be causing #811, I guess.

### Reproduction

It's nicely reproducible by extending _Minimal_ demo project:

1. Get write access to private field `FImagesMargin` using the _`with Self do` class helper hack_:
```
type
  TVirtualTreeHelper = class helper for TBaseVirtualTree
    procedure SetImagesMargin(const AValue: Integer);
  end;

procedure TVirtualTreeHelper.SetImagesMargin(const AValue: Integer);
begin
  with Self do
    FImagesMargin := AValue;
end;
```
2. Add a `TSpinEdit` control to `TMainForm.dfm` and set its `Value` to `2` as it is the hard coded value of `FImagesMargin`:
```
  object SpinEdit1: TSpinEdit
    Value = 2
  end
```
3. Implement the spin edit's `OnChangeEvent` to apply its value to `FImagesMargin`:
```
procedure TMainForm.SpinEdit1Change(Sender: TObject);
begin
  VST.SetImagesMargin(SpinEdit1.Value);
  VST.Invalidate;
end;
```
4. Compile and start to initially see the unchanged behavior:
![image](https://github.com/JAM-Software/Virtual-TreeView/assets/25772356/7f7b8ab0-bc1b-4ea1-b9cf-3d96d09aac67)
5. Use the spin edit to change `FImagesMargin` and unexpectibly see the nodes' labels move to the right when increasing it or to the left when decreasing it:
![Animation](https://github.com/JAM-Software/Virtual-TreeView/assets/25772356/9f1ad669-647c-4f80-b046-9b313ca977e5)
6. As there are no images visible at all, `FImagesMargin` shouldn't change the display at all.

**Comment by joachimmarder** [comment]
Thank you for sending the pull request. I didn't repro the issue myself, but your changes look well-thought-out.
