### ISSUE TITLE
Feature Request: SelectNode(ANode: PVirtualNode)

### ISSUE THREAD

**Issue by BigAl66** [JAM-Software/Virtual-TreeView#1195]
I use very often the following sequence:
```
vst.ClearSelection;
vst.Selected[Node] := True;
vst.ScrollIntoView(Node, True);
vst.UpdateScrollBars(True);
```
It would be great to have function for that. The function could look like:
`SelectNode(ANode: PVirtualNode; AScrollIntoView: Boolean = True; AScrollToCenter: Boolean = False);`

**Comment by joachimmarder** [comment]
I just tested this with the `Advanced` sample, `SpeedDemo`, and added a button with:

`  VST1.Selected[VST1.GetLast()] := True;`

It scrolled to the right position. So I don't see a real need for this method. You can however add it as class helper in your code.

**Comment by BigAl66** [comment]
Thanks for your answer!

Your suggestion does not deselect already selected items. Further it jumps only to the position when no other item was selected before.  What I want to achive is, that everything is deselected, except the node I like to select. Finally this node should be visible.
I use this often when I make a selection dialog. During initialization the content is generated. By setting a property a specific node should be selected (and of course visible). I do this usually in the OnShow event of the form, because if I do it earlier it does not work. My OnShow contains then the following code:

```
  if Assigned(vstCnv.FocusedNode) then
    vstCnv.ScrollIntoView(vstCnv.FocusedNode, True);
```

But: It was only an idea. I can live with the current situation. And if it bothers me too much, I can always write a ClassHelper. No Problem.
