### ISSUE TITLE
function AddToSelection() no longer public

### ISSUE THREAD

**Issue by AlexSTHfg** [JAM-Software/Virtual-TreeView#1196]
Hi,
i use V7.6.2 and have function calls like this:

myVst.AddToSelection(Node, False);

Now i want to update to newest version V7.6.5 and this function doesn't exist anymore as a public function so i can't call them.
Is there a way to use this function again?

**Comment by radioboss** [comment]
myVst.Selected[Node] := True?

**Comment by joachimmarder** [comment]
TCustomVirtualStringTree.AddToSelection() is still public in V7.6.5, VirtualTrees.pas, line number 3524.
Please supply more details.

**Comment by AlexSTHfg** [comment]
> myVst.Selected[Node] := True?

Hm, i'm not really sure, where is the different between Selected[Node] := True or AddToSelection.
I only know, that AddToSelection was used before. I have to check the difference



> TCustomVirtualStringTree.AddToSelection() is still public in V7.6.5, VirtualTrees.pas, line number 3524. Please supply more details.

7.6.5 is still public?
My virtualTrees.pas has only 2011 loc.
My virtualTrees.BaseTree has the function AddToSelection but as protected (declared in line 919 and 920).
It is also declared in "TBaseVirtualTree", not in "TCustomVirtualStringTree".
Did you really check the version 7.6.5?

**Comment by joachimmarder** [comment]
I'm sorry, the 7.6.5 release was accidentally built on the master branch. I just created 7.6.5a to correct this.

In the master branch I am going to make this method public again.

**Comment by AlexSTHfg** [comment]
Thank you :-)
