### ISSUE TITLE
Untie BaseTree from VirtualTrees

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [JAM-Software/Virtual-TreeView#1201]
There's possibility to reduce number of circular links by untying BaseTree from VirtualTrees. It would require:
1) adding empty method DoPaintText to BaseTree and call it unconditionally in TVirtualTreeHintWindow.CalcHintRect (or adding some flag to TVirtualTreeHintWindow)
2) calling RegisterVTClipboardFormat related to TCustomVirtualStringTree from VirtualTrees

Benefit of this change is not only reducing circular links but also extracting independent layer of BaseTree with its dependents and DrawTree independent from StringTree with Export, Accessibility and EditLink thus reducing binary size.

**Comment by joachimmarder** [comment]
> adding empty method DoPaintText to BaseTree and call it unconditionally in TVirtualTreeHintWindow.CalcHintRect

Yes, that makes sense. We have to move `TVSTTextType` to unit `VirtualTrees.Types`, but that seems acceptable.

**Comment by joachimmarder** [comment]
> calling RegisterVTClipboardFormat related to TCustomVirtualStringTree from VirtualTrees

Done.
