### ISSUE TITLE
Use solid lines instead of dotted lines as grid lines

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#1202]
It is quite unusual in year 2023 to use dotted lines instead of solid lines for visualizing grid lines. They add extra complexity, e.g. in the FMX port, see #1135, or when better visualizing fixed colors, see #1088.

I will therefore remove the dotted brush and use solid lines instead. They can also be easier scaled on displays >=175%, see issue #1203.

Furthermore, we should respect the theme when painting the grid lines, like we already do in the column header for the column separators.

**Comment by pyscripter** [comment]
Dotted lines are also very slow to draw with DirectX, which FMΧ uses on Windows.

**Comment by livius2** [comment]
Hi

I don't know if removing functionality that has been available for years is good.
I used custom patterns myself sometimes. And the scaling problem would have to be solved in a different way. Although the argument about slow line drawing cannot be ignored, but today's devices are getting more and more powerful ;-)
P.S. I thought I would be active this year, but it didn't work out, a lot of work. I hope I will find time to get back to the topic of FMX.

**Comment by joachimmarder** [comment]
> I don't know if removing functionality that has been available for years is good.

We sometimes have to move on, especially to keep the code maintainable. We can discuss about the tree lines, this issue covers only the grid lines, which should be handled separately from the tree lines.

**Comment by joachimmarder** [comment]
I separated drawing grid lines from drawing tree lines, we should not mix this. The change can still be reverted easily. I tested with some VCL themes and it looked good. Let me know what you think.

**Comment by livius2** [comment]
Splitting them is good concept.
