### ISSUE TITLE
TVTHeader.AutoScale() never decreases height.

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1206]
Both VT and Header AutoScale may only increase height, but never decrease it.

In my application (PyScripter), I have an option to change the UI content font size.   When a user increases font size both default node height and header height* are automatically adjusting (increasing),  which is good, but if a user decreases font size, the node height and header height stay at their previous high values and do not look good.

Is there a reason for this behaviour?  I would think that if toAutoChangeScale is set, you let VT manage the node and header heights for better or worse.

* regarding the header only if you remove the conditional compilation in FontChanged (see #1205)

### Changes needed

in TVTHeader.AutoScale remove the lines below:

```pascal
    //Get the maximum of the scaled original value and the minimum needed header height.
    lMaxHeight := Max(lMaxHeight, FHeight);
```

In TBaseVirtualTree.AutoScale  change the > to <>.

**Comment by joachimmarder** [comment]
> Is there a reason for this behaviour?

Well, I guess the original idea was to let the developer decide about the header height, but prevent cut off text which never makes sense.

Furthermore, changing the font is not the same as dpi-scaling. In dpi-scaling you have `M` and `D` and so can keep the relations between header height and other elements of the control. 

How about tying the header height to `DefaultNodeHieght`?

**Comment by pyscripter** [comment]
> I guess the original idea was to let the developer decide about the header height,

In that case the developer should not set toAutoChangeScale.  Especially now that it is decoupled from DPI scaling.  Setting this flag means that you allow VT to optimize node and header height, based on the font size.   

> How about tying the header height to `DefaultNodeHieght`?

This would not work when the header ParentFont is False.  And in any case DefaultNodeHeight is also incorrect when  you decrease the font size.  The suggested changes fix both DefaultNodeHeight and header height.

Just think what needs to be done otherwise, if a user assigns a font with smaller size at run time:
- Change DefaultNodeSize manually
- Change the height of existing nodes.
- Change the header height manually

**Comment by pyscripter** [comment]
Thanks!

But, shouldn't TBaseVirtualTree.AutoScale behave in a similar way?
