### ISSUE TITLE
Possible double scaling of unitialized nodes

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1208]
In ChangeScale currently,  the default node height is changed and the existing nodes are scaled.

```pascal
procedure TBaseVirtualTree.ChangeScale(M, D: Integer{$if CompilerVersion >= 31}; isDpiChange: Boolean{$ifend});
begin
  if (M <> D) then
  begin
    BeginUpdate();
    try
      SetDefaultNodeHeight(MulDiv(FDefaultNodeHeight, M, D));
      Indent := MulDiv(Indent, M, D);
      FTextMargin := MulDiv(FTextMargin, M, D);
      FMargin := MulDiv(FMargin, M, D);
      FImagesMargin := MulDiv(FImagesMargin, M, D);
      ScaleNodeHeights(M, D);
    finally
      EndUpdate();
    end;//try..finally
  end;// if M<>D
```

This caused double scaling in the following situation:

- The scaled tree was invisible and no node was initialized.   
- ScaleNodeHeights calls GetFirst, which initialized the first node, called InitChildren, and created Uninitialized childrent with the **new DefaultNodeHeight**
- Then the uninitialized children were scaled again

**Solutions:**

Either of the following solves the problem:

a)  In TBaseVirtualTree.ScaleNodeHeights use GetFirstNoInit instead of GetFirst.

```pascal
procedure TBaseVirtualTree.ScaleNodeHeights(M, D: Integer);
var
  Run: PVirtualNode;
  lNewNodeTotalHeight: Cardinal;
begin
  // Scale also node heights
  BeginUpdate();
  try
    Run := GetFirstNoInit();
    while Assigned(Run) do
```

b)  In TBaseVirtualTree.ChangeScale above call ScaleNodeHeights before SetDefaultNodeHeight

```pascal
procedure TBaseVirtualTree.ChangeScale(M, D: Integer{$if CompilerVersion >= 31}; isDpiChange: Boolean{$ifend});
begin
  if (M <> D) then
  begin
    BeginUpdate();
    try
      ScaleNodeHeights(M, D);
      SetDefaultNodeHeight(MulDiv(FDefaultNodeHeight, M, D));
      Indent := MulDiv(Indent, M, D);
      FTextMargin := MulDiv(FTextMargin, M, D);
      FMargin := MulDiv(FMargin, M, D);
      FImagesMargin := MulDiv(FImagesMargin, M, D);
    finally
      EndUpdate();
    end;//try..finally
  end;// if M<>D
```

It may be worth doing both!   In AutoScale SetDefaultNodeHeight is called after  ScaleNodeHeights, so b) would be consistent with what happens in AutoScale.

**Comment by joachimmarder** [comment]
Thanks. We rarely work with PArentFont = False.

**Comment by pyscripter** [comment]
Thanks!
