### ISSUE TITLE
Keep current selection when right-clicking a selected node (toRightClickSelect enabled)

### ISSUE THREAD

**Issue by PatmanSan** [JAM-Software/Virtual-TreeView#1214]
When toMultiSelect and toRightClickSelect are enabled, it would be great to allow right-clicking one of the selected nodes without deselecting the current selection. Currently it simply deselects all, and selects the right-clicked node, even if the right-clicked node is already selected. It's all initiated from TBaseVirtualTree.WMRButtonDown, and the actual deselection takes place in  TBaseVirtualTree.HandleMouseDown, so there no event fired to lock the selection beforehand (i.e. the tree's OnMouseDown is triggered later).

I did some testing with the following change, and it seems to do the job:

```
procedure TBaseVirtualTree.WMRButtonDown(var Message: TWMRButtonDown);

var
  HitInfo: THitInfo;
  RemoveSynchMode: Boolean; // Needed to restore tsSynchMode correctly
  SavedSelectionLocked: Boolean;

begin
  DoStateChange([tsRightButtonDown]);

  if FHeader.States = [] then
  begin
    inherited;

    // get information about the hit
    if toRightClickSelect in FOptions.SelectionOptions then
    begin
      GetHitTestInfoAt(Message.XPos, Message.YPos, True, HitInfo);
      // Go temporarily into sync mode to avoid a delayed change event for the node when selecting. #679
      RemoveSynchMode := not (tsSynchMode in FStates);
      Include(FStates, tsSynchMode);

      SavedSelectionLocked := FSelectionLocked;
      if (HitInfo.HitNode <> nil) and Selected[HitInfo.HitNode] then
        FSelectionLocked := True;

      HandleMouseDown(Message, HitInfo);

      FSelectionLocked := SavedSelectionLocked;

      if RemoveSynchMode then
        Exclude(FStates, tsSynchMode);
    end;
  end;
end;
```

It will lock the current selection before HandleMouseDown, but only when the following criteria are met:

- Option toRightClickSelect is enabled (check was already in original code)
- HitNode is valid
- HitNode is selected

The current state of FSelectionLocked is saved and restored.
If right-clicking a non selected node, it will behave like usual (deselecting all and selecting the right-clicked node).
Not sure if checking for existing popup assignment is required or useful. If so, then this could be added to the criteria:

`and not HasPopupMenu(HitInfo.HitNode, HitInfo.HitColumn, Point(Message.XPos, Message.YPos))
`

I populate my popups dynamically, depending on the data the node(s) represent. Having or not having the extra check does not affect my tree.  It might be necessary for reasons I can't oversee though.

**Comment by joachimmarder** [comment]
> When toMultiSelect and toRightClickSelect are enabled, it would be great to allow right-clicking one of the selected nodes without deselecting the current selection. Currently it simply deselects all, and selects the right-clicked node, even if the right-clicked node is already selected.

I cannot confirm this. I just tested this in TreeSize and in the Advanced sample on the "General abilities and features" page: If multi-select several nodes and right click on one of the selected, the selection stays as it is. Only if I click an unselected node, the currently selected nodes are deselected. This is the behavior you see in many Windows common controls and in Windows Explorer, and therefore I wouldn't change it.

**Comment by PatmanSan** [comment]
Thanks for the response. I found the problem. I was using the OnMouseUp event to populate and activate my popup menu. I should have picked the OnGetPopupMenu event, because that's what HandleMouseDown is calling (via HasPopupMenu) to check if it's OK to clear the selection. After switching events all is fine now. Thanks again.
