### ISSUE TITLE
Setting LineStyle to lsDotted does not work

### ISSUE THREAD

**Issue by MPannier** [JAM-Software/Virtual-TreeView#1217]
Hello,

I use Delphi 11.3 with the Virtual-TreeView from today. If I change the LineStyle of the component, it will not change any "painting".
You can try it by using the Advanced demo and the unit HeaderCustomDrawDemo. The initial LineStyle is lsSolid and it will show "solid lines". If I change the value to lsDotted the lines will be solid.

Regards
Mathias

**Comment by joachimmarder** [comment]
This is a result of issue #1202, the change is by design. The property LineStyle applies to tree lines only, not to grid lines. This fixes some issues with VCL theming and dpi scaling.
