### ISSUE TITLE
TBaseVirtualTree.AddChild( ) fails for toReadOnly

### ISSUE THREAD

**Issue by gwideman** [JAM-Software/Virtual-TreeView#1218]
TBaseVirtualTree.AddChild returns nil if toReadOnly is set.

```  
function TBaseVirtualTree.AddChild(Parent: PVirtualNode; UserData: Pointer = nil): PVirtualNode;
begin
  if not (toReadOnly in FOptions.MiscOptions) then
    Result := InsertNode(Parent, TVTNodeAttachMode.amAddChildLast, UserData)
  else
    Result := nil;
end;
```

That makes no sense to me.  While we might want toReadOnly to prevent users editing nodes, why would we want to prevent programmatic construction of the tree using AddChild()? 

Or am I misunderstanding the meaning of "Read Only" ?

**Comment by joachimmarder** [comment]
> Or am I misunderstanding the meaning of "Read Only" ?

Yes, it seem so. `toReadOnly` is documented as follows:

**The tree does not allow to be modified in any way. No action is executed and node editing is not possible.**

This was already the case when I took over the project years ago. 

> ... to prevent users editing nodes

To achieve this, remove the flag `toEditable`.

**Comment by gwideman** [comment]
Thanks for your reply. 

I see in other places in VirtualTrees.pas that indeed toReadOnly prevents changes, whether initiated by users or by code.

So apparently this means that toReadOnly is a property that makes sense to be operated only by code. Setting it in the IDE Properties Inspector renders the VirtualTree disabled, essentially. Unless runtime code disables toReadOnly and makes some changes to the tree.

OK, I guess I talked myself into seeing how this is could be useful.  It's just the name is a little under-descriptive, because it doesn't convey whether the setting means ReadOnly for users or ReadOnly for code as well.

A name like "FreezeStructure" would be more helpful.

Anyhow, it is what it is, and too late to change now!
