### ISSUE TITLE
OnShortenString not called for column headers

### ISSUE THREAD

**Issue by gwideman** [JAM-Software/Virtual-TreeView#1220]
`procedure TVirtualTreeColumns.DrawButtonText(...)`     calls VTV's ShortenString directly:
```
    if TextSpace < Size.cx then
      Caption := ShortenString(DC, Caption, TextSpace);
```
... instead of calling DoShortenString --> OnShortenString to let the user supply a different algorithm. (Possibly using an actual ellipsis character).

This is in v7.6.5a.

**Comment by joachimmarder** [comment]
`OnShortenString` is an event of the Virtual String Tree, while the header and columns only know about `TBaseVirtualTree`. `DoShortenString()` calls some other methods that are specific to the Virtual String Tree. That means we would need to move relevant portions of the Virtual String Tree to the base class to achieve what you are proposing. Especially with the [changes made for V8](https://github.com/JAM-Software/Virtual-TreeView/wiki/Breaking-Changes-in-upcoming-V8) this si not easy and there are no other good options.

You may use custom drawing (`OnHeaderDraw`) or the event `OnColumnResize` to set a new caption that fits the new size.

**Comment by gwideman** [comment]
Ah, OK, more complicated than I first appreciated. Fair enough.
