### ISSUE TITLE
How to get lighter/finer GridLines; GridLineColor not used.

### ISSUE THREAD

**Issue by MPannier** [JAM-Software/Virtual-TreeView#1227]
Is it possible to get lighter grid lines in VirtualStringTree?
In the screenshot you can see the difference between TListView, TDBGrid and TVirtualStringTree. 
I have also tried a rather "GridLineColor". But this color is not used.

Regards
Mathias

![GridLines_ListView_DBGrid_VirtualStringTree](https://github.com/JAM-Software/Virtual-TreeView/assets/17467699/80a2e55e-7f8b-4301-b9a1-5bf27602c093)

**Comment by joachimmarder** [comment]
From which version have you taken the screenshots? V7 or from the master branch?

**Comment by MPannier** [comment]
Hello, from the master branch.

**Comment by joachimmarder** [comment]
OK, you can now adjust the grid color using `Colors.GridLineColor`. The initial value is `clBtnFace`. I'm not sure that the VCL grids are using, let me know if you find out.

**Comment by MPannier** [comment]
It works for me. Thank You.
