### ISSUE TITLE
AutoScale is setting wrong node height

### ISSUE THREAD

**Issue by TextEditorPro** [JAM-Software/Virtual-TreeView#1230]
Should that difference condition be greater than? Otherwise if I set DefaultNodeHeight 20 and TextHeight is 15, it will use 15.

```
procedure TBaseVirtualTree.AutoScale();
...
if LTextHeight > Self.DefaultNodeHeight then // <> => >
...
```

**Comment by pyscripter** [comment]
Clearly you are not using the master branch:
https://github.com/JAM-Software/Virtual-TreeView/blob/master/Source/VirtualTrees.BaseTree.pas#L15920

**Comment by pyscripter** [comment]
> Otherwise if I set DefaultNodeHeight 20 and TextHeight is 15

If you want DefaultNodeHeight to be used instead of TextHeight do not use toAutoChangeScale.  Note that DefaultNodeHeight is DPI scaled.

https://github.com/JAM-Software/Virtual-TreeView/blob/aa218047536025911e9ed4077f4546f35e2e7fc7/Source/VirtualTrees.Types.pas#L335

**Comment by TextEditorPro** [comment]
I see, it was mentioned as a breaking change too. I removed all toAutoChangeScale options, tested scaling, and it is ok. I am not sure about the naming of that option now... a slightly peculiar feature.

Btw. Those Integer to TDimension changes in events were not mentioned in breaking changes. Delphi can easily lose the event when types are not correct. So maybe something worth mentioning.
