### ISSUE TITLE
Update to Delphi 12

### ISSUE THREAD

**Issue by davetrafford** [JAM-Software/Virtual-TreeView#1233]
Is there going to be an update for  delphi 11 and 12.cannot install version 10.4

**Comment by joachimmarder** [comment]
> Is there going to be an update for delphi 11 and 12.

Since V7 works fine on Delphi 11 and V8 on Delphi 11+12 there are no such plans.

> cannot install version 10.4

Can you please describe more detailed why you cannot install?

**Comment by davetrafford** [comment]
Hi,thanks for your reply.
It is all working now.First time I tried to install it came up with a lot
of errors but has now been installed(Delphi 12);
No idea why.
Thanks for getting back to me anyway.
