### ISSUE TITLE
8.0.1 compile error

### ISSUE THREAD

**Issue by Dzyszla** [JAM-Software/Virtual-TreeView#1237]
Delphi 10

[dcc32 Error] VirtualTrees.BaseTree.pas(11545): E2034 Too many actual parameters
(on ```CurrentPPI``` parameter in ```DrawElement``` in ```TBaseVirtualTree.DrawGridVLine```)

**Comment by Dzyszla** [comment]
(sorry, wrong button :) )

It's something corresponding with Delphi version?

**Comment by joachimmarder** [comment]
A conditional compiler command was missing.

**Comment by Dzyszla** [comment]
Thanks for your immediate fix :)
