### ISSUE TITLE
Is 7.6.6 an alias of 8.0?

### ISSUE THREAD

**Issue by mercedwang** [JAM-Software/Virtual-TreeView#1238]
It seems that 7.6.6 is not the successor of 7.6.5, but an alias of 8.0. Almost all files are same.

**Comment by joachimmarder** [comment]
I'm very sorry, I created the V7.6.6. release on the wrong branch. This is now corrected in V7.6.6a.

**Comment by mercedwang** [comment]
-)

Thx.













Ou Wang


***@***.***


13910034497







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Joachim Marder  ***@***.***>
 

 
 发送时间: 2024-02-03 14:42:47
 

 
 收件人:JAM-Software/Virtual-TreeView ***@***.***> 

 
 抄送:ouwang ***@***.***>,Author ***@***.***> 

 
 主题: Re: [JAM-Software/Virtual-TreeView] Is 7.6.6 an alias of 8.0? (Issue#1238)
 





 I'm very sorry, I created the V7.6.6. release on the wrong branch. This is now corrected in V7.6.6a.

**Comment by mercedwang** [comment]
下载视频



投屏



复制链接




Hello,
Does the 7.6.x version of VT support Delphi 12 officially? If so, will the GetDoubleBuffered member function become a virtual/override function in Delphi 12 (by using $if directive) in future releases of 7.6.x? Will its visibility be changed from private to protected? i.e. just like the definition of GetDoubleBuffered function in 8.0.3, and the definition of it in TWinControl class in Delphi 12. 
Thanks!











Ou Wang


***@***.***


13910034497







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Joachim Marder  ***@***.***>
 

 
 发送时间: 2024-02-03 14:42:47
 

 
 收件人:JAM-Software/Virtual-TreeView ***@***.***> 

 
 抄送:ouwang ***@***.***>,Author ***@***.***> 

 
 主题: Re: [JAM-Software/Virtual-TreeView] Is 7.6.6 an alias of 8.0? (Issue#1238)
 





 I'm very sorry, I created the V7.6.6. release on the wrong branch. This is now corrected in V7.6.6a.

**Comment by joachimmarder** [comment]
> Does the 7.6.x version of VT support Delphi 12 officially

@mercedwang : No, it doesn't. Only V8 officially supports Delphi 12.
