### ISSUE TITLE
Can't Install VirtualTreesD280.bpl

### ISSUE THREAD

**Issue by GrooverMD** [JAM-Software/Virtual-TreeView#1239]
Have been trying to install VirtualTreesD280.bpl but get an error

Cannot load package 'VirtualTreesR280.' It contains unit 'VirtualTrees.WorkerThread', which is also contained in package 'VirtualTreesDR280'.

**Comment by joachimmarder** [comment]
Which version of Virtual TreeView are you using? I cannot reproduce this.

> ... package 'VirtualTreesR280.' It contains unit 'VirtualTrees.WorkerThread', which is also contained in package 'VirtualTreesDR280'

This is not the case if you look into the source code. Most likely there some old VT packages in your Delphi search path.
