### ISSUE TITLE
IDataObject replaced by TVTDragDataObject?

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#1241]
After updating to the latest VTV version after switching to Delphi 12, it wants to remove all OnDragDrop references:
`The *DragDrop method referenced by vst*.OnDragDrop has an incompatible parameter list. Remove the reference?`

It appears that the parameter `DataObject: IDataObject` was changed to `DataObject: TVTDragDataObject` but I cannot find this documented anywhere in this issue tracker. This seems to be either a breaking change or a bug. Did I miss something?

**Comment by joachimmarder** [comment]
This change was done intentionally as part of the Firemonkey port in issue #841. However, I didn't recognize that the change is breaking, because `TVTDragDataObject` is just an alias for `IDataObject`.

**Comment by joachimmarder** [comment]
I added an additional alias for `IDataObject` in unit `VirtualTrees.Types` which fixed the problem for me. A rebuild and install of the package is necessary.

**Comment by IgitBuh** [comment]
Thank you!
In the meantime I replaced all occurrences of IDataObject to TVTDragDataObject to continue working. Would you recommend to change it back or is this irrelevant for the future and I can leave it with TVTDragDataObject?

**Comment by joachimmarder** [comment]
I think we will stick with `TVTDragDataObject`, if not other problems are reported.
