### ISSUE TITLE
Header DblClickResize and HeaderClickAutoSort

### ISSUE THREAD

**Issue by MShark67** [JAM-Software/Virtual-TreeView#1243]
It seems that with both of these header options turned on a double-click to autosize a column will also cause a sort on whichever column the mouse is over.  It also causes an onHeaderClick event (which may be intended) however it's not currently possible to detect why the click is happening.  This is an issue for pure virtual controls which (I believe) need to use onHeaderCLick to handle the sort.  Also the onHeaderclick event that occurs will have the Hitinfo from after the resize which can be on a different column.  That makes it impossible to try to detect if the click is in the SplitterHitTolerance area.

**Comment by joachimmarder** [comment]
It seems that Windows send two different messages here (first `WM_NCLBUTTONDBLCLK` and  then `WM_NCLBUTTONUP`), and you can't see if the `WM_NCLBUTTONUP` occurs after a single or a double click. I guess we need to store this information.

**Comment by joachimmarder** [comment]
@MShark67: Could you please check if the previous commit fixes your issue?

**Comment by MShark67** [comment]
All my tests show you've completely fixed this issue.  Thank you and well done!
