### ISSUE TITLE
DefaultNodeHeight not working anymore

### ISSUE THREAD

**Issue by BigAl66** [JAM-Software/Virtual-TreeView#1244]
Since the last update (commit 7ba3d29cefa905f2d925723e6934f44d9501516e, 16.03.2024) the DefaultNodeHeight does not work anymore. Changing the value has no effect.

**Comment by pyscripter** [comment]
See #1230 and #1198 (at the end of the discussion).

**Comment by BigAl66** [comment]
Thanks for the information. If the whole thing is on purpose, then I can live with it very well (I've already changed my sources). I was just afraid that it would be corrected at some point and then stop working again...

**Comment by joachimmarder** [comment]
Yes, just remove `toAutoChnageScale` fro m `AutoOptions`.
