### ISSUE TITLE
Threads in VST

### ISSUE THREAD

**Issue by Dzyszla** [JAM-Software/Virtual-TreeView#1245]
I have very hard problem - in some case, when I have window with VST in DLL, and I close it, whole application sometimes crash with AV error in unloaded DLL (especially on slow computers).

If I add sleep (f.ex. 500 ms) after window free, but before end of DLL's procedure (witch open and free my form with VST), then looks work good.

So, I think it can be some mistake in some thread... But where?

I look on ```VirtualTrees.WorkerThread``` file and ```Dispose``` procedure and have question: why is there terminate and setevent, but not waiting for really terminate thread (```WaitFor```)? But I'm not sure this applies to my case or this is true mistake.

It's applies to 7.x and 8.0 version.

**Comment by joachimmarder** [comment]
What exactly make you think that the thread of Virtual TreeView causes the crash?

**Comment by Dzyszla** [comment]
I attach demo code (two projects: exe and dll):
[VST_Test.zip](https://github.com/JAM-Software/Virtual-TreeView/files/14647298/VST_Test.zip)

On my computer have no errors, but when I run it on Windows 2012/2016/2019 Server, click button and close window (by shortcut, by mouse click - no matter) in 1 on 10 times crash (but sometime can be 10 times without error, and next every 3 run and close ends with crash).
here attach system logs:
[VSTerrors.zip](https://github.com/JAM-Software/Virtual-TreeView/files/14647412/VSTerrors.zip)

**Comment by Dzyszla** [comment]
PS - When I made changes in dispose method, then works good:
```delphi
class procedure TWorkerThread.Dispose(CanBlock: Boolean);
var
  LRef: TThread;
begin
  WorkerThread.FreeOnTerminate := False;   // << NEVR USE FREE ON TERMINATE
  //WorkerThread.FreeOnTerminate := not CanBlock;  // << -- " --
  WorkerThread.Terminate();
  SetEvent(WorkerThread.FWorkEvent);
  LRef := WorkerThread;
  WorkerThread.WaitFor; // << ADD WAITING  FOR TERMINATE
  WorkerThread := nil; //Will be freed usinf TThread.FreeOnTerminate
  //if CanBlock then   << DISABLE THIS LINE - OBJECT MUST BE ALWAYS FREE
	LRef.Free;
end;
```

**Comment by joachimmarder** [comment]
I didn't get a single crash in 30 tries with your demo project.

Can you please check if the following change makes any difference in your case: In `TBaseVirtualTree.Destroy()` change the call to `TWorkerThread.ReleaseThreadReference` to:

`TWorkerThread.ReleaseThreadReference(IsLibrary);`

**Comment by Dzyszla** [comment]
I try my demo on my own system, and it's crash after about 1 on 60-80 trials (very infrequently, but possible). I think, it depends on cpu cores load.

I made the changes as suggested (and I rolled back my own previous changes) and looks all right - no more crashes.
