### ISSUE TITLE
DefaultNodeHeight has no effect since 8.0.2

### ISSUE THREAD

**Issue by Delphichem** [JAM-Software/Virtual-TreeView#1246]
Changing DefaultNodeHeight has no effect since 8.0.2.
Step
Open GeneralAbilitiesDemo
Change DefaultNodeHeight to another value (ex: 40)
run

The value has no effect
desabling AutoScale() in line 8761 fix the issue.

**Comment by luebbe** [comment]
possibly a duplicate of #1244

**Comment by Delphichem** [comment]
Yes it is, thanks, I close this issue.
