### ISSUE TITLE
Fixed columns are broken in V7.6.6 and V8.0.2

### ISSUE THREAD

**Issue by DGH2112** [JAM-Software/Virtual-TreeView#1248]
Having moved my VTV version up to the latest V7.6.6 and noticed that the fixed columns support is broken. The column headers honour the fixed columns however the data does not (I'm using RS 12.1).

You can see this issue in the Advanced demo if you slightly change the demo by:

- Making the columns "Customer ID" and "First Name" fixed at design time in the Grid Demo;
- Running the demo and go to the Grid demo;
- Widen the columns "Last Name" and "Order Date" to force a horizontal scroll bar;
- Scroll to the right...

The fixed column headers stay in place but the data underneath moves the first 3 columns which should be fixed.

regards
Dave.

**Comment by DGH2112** [comment]
I've also just tested with the latest master (V8.0.2+) and the same issue exists.

**Comment by DGH2112** [comment]
I think I've tracked down the commit where this happens as follows:
- 1258e88 @ 11 Nov 2023 - okay
- 1aac7ef @ 14 Nov 2023 - broken
The only changes I can see are that GetDoubleBuffered as an override added in the later commit. When I check the method there is no call to Inherited, so I suspect the chain is broken. Adding Inherited to the method does not fix the issue however commenting out the override does. I'm not familiar enough with the code to understand why this would be the case.
regards
Dave

**Comment by joachimmarder** [comment]
Thanks for bisecting the responsible commit. I just noticed that painting the control is done through the `WM_PRINTCLIENT` message, typically this was `WM_PAINT`. Maybe this is new in Delphi 12, or the commit https://github.com/JAM-Software/Virtual-TreeView/commit/1aac7ef7185d53929634e83b8c37066257116ef4 changed the call chain.

Anyway, I have no idea why Virtual TreeView got its own `WMPrintClient()` method. Using the inherited one makes the problem go away. I wonder if this breaks something else.
