### ISSUE TITLE
As of the September 22, 2023 release, the C++Builder version is not compatible with the previous version

### ISSUE THREAD

**Issue by wg0517** [JAM-Software/Virtual-TreeView#1249]
TVSTTextType is written as TVstTextType, which is considered different because C++ Builder is case-sensitive, resulting in the OnGetText event in the previous code being considered invalid.

**Comment by joachimmarder** [comment]
Sorry, I don't use C++ Builder and don't have it installed. For a long time, we are looking for someone who maintains C++ Builder compatibility. Are you interested?

> As of the September 22, 2023 release

I don't think there was a release on Sep 22 2023. Which version do you mean? Or do you refer to a certain commit?

In any case, feel free to send a pull request or attach a [patch file](https://github.com/JAM-Software/Virtual-TreeView/wiki/Create-a-Patch) to this issue that fixes the problem

**Comment by wg0517** [comment]
![image](https://github.com/JAM-Software/Virtual-TreeView/assets/24564220/a2374598-350a-4fe9-b4cf-27810c690ec3)
![image](https://github.com/JAM-Software/Virtual-TreeView/assets/24564220/44a109fd-d36a-43b4-9d43-7ba72f5f5ce4)
Please modify TVstTextType to TVSTTextType to maintain compatibility with historical codes, thanks

I may only git the latest code once in a few months or a year.
