### ISSUE TITLE
Cannot compile 8.0.3 package in Delphi XE3

### ISSUE THREAD

**Issue by alanccw** [JAM-Software/Virtual-TreeView#1256]
Hi,

I try to open the project group under D:\Program Files (x86)\VCL\VirtualTreeView\Packages\RAD Studio 10.2, then select "VirtualTreeR25.bpl" and then "Build" it, but get the following errors:

[dcc32 Error] VirtualTrees.StyleHooks.pas(108): E2029 $ENDIF expected but $IFEND found
[dcc32 Error] VirtualTrees.StyleHooks.pas(113): E2029 $ENDIF expected but $IFEND found
[dcc32 Fatal Error] VirtualTrees.Header.pas(19): F2063 Could not compile used unit 'VirtualTrees.Utils.pas'

Why?

**Comment by joachimmarder** [comment]
I'm sorry, but the support for RAD Studio XE3 was dropped in V8: https://github.com/JAM-Software/Virtual-TreeView/issues/1169

Please continue using V7 or update your RAD Studio.
