### ISSUE TITLE
GetNodeData returns invalid data when (Node = Pointer(Self))

### ISSUE THREAD

**Issue by chuacw** [JAM-Software/Virtual-TreeView#1265]
When Node is Pointer(Self) in GetNodeData, it should return nil, instead of returning @Node.Data, ie...
the code for GetNodeData should be updated to:

```
function TBaseVirtualTree.GetNodeData(Node: PVirtualNode): Pointer;
// Returns the address of the user defined data area in the node.
begin
  Assert((FNodeDataSize > 0) or not Assigned(Node), 'NodeDataSize not initialized.');
  if (FNodeDataSize <= 0) or (Node = nil) or (Node = FRoot) or (Node = Pointer(Self)) then
    Result := nil
  else
  begin
    Result := @Node.Data;
    Include(Node.States, vsOnFreeNodeCallRequired); // We now need to call OnFreeNode, see bug #323
  end;
end;
```

**Comment by joachimmarder** [comment]
>  it should return nil, instead of returning @Node.Data

@chuacw : Can you please explain *why* you think that?

`Self` (the object pointer to a virtual tree instance) is not a valid input for `GetNodeData()` and the pointer type of the parameter does not match. So why should we care?
