### ISSUE TITLE
Get a warning "W1075" when compiling

### ISSUE THREAD

**Issue by BigAl66** [JAM-Software/Virtual-TreeView#1267]
When compiling the current version I receive the following warning:

[dcc32 Warning] VirtualTrees.Header.pas(280): W1075 Overloading a similar index type by declaring an array property 'Items'
  VirtualTrees.Header.pas(280): Related member: property TVirtualTreeColumns.Items[TColumnIndex]: TVirtualTreeColumn;
  VirtualTrees.Header.pas(280): Related member: property TCollection.Items[Integer]: TCollectionItem;

Everything runs finde so I can ignore the warning. If everything is correct it would be good to adapt the code as follows:

File VirtualTrees.Header.pas
[280]    {$WARN OVERLOADING_ARRAY_PROPERTY OFF}
[281]    property Header: TVTHeader read FHeader;
[282]    {$WARN OVERLOADING_ARRAY_PROPERTY ON}

This ignores the warning and does not give any message again...

**Comment by pyscripter** [comment]
> [280] {$WARN OVERLOADING_ARRAY_PROPERTY OFF}
> [281] property Header: TVTHeader read FHeader;
> [282] {$WARN OVERLOADING_ARRAY_PROPERTY ON}

This would result in errors when compiling with earlier versions.
See https://en.delphipraxis.net/topic/12148-new-warning-in-122-overloading-a-similar-index-type-by-declaring-an-array-property-items/

The warning goes away if you change the definition of TColumnIndex to

  TColumnIndex = {type} Integer;

but then you lose some of the type checking.

**Comment by pyscripter** [comment]
I recommend the following which is backward compatible and future-proof.

```pascal
    {$IF (CompilerVersion > 36) or Declared(RTLVersion122)}{$WARN OVERLOADING_ARRAY_PROPERTY OFF}{$ENDIF}
    property Items[Index : TColumnIndex] : TVirtualTreeColumn read GetItem write SetItem; default;
    property Header: TVTHeader read FHeader;
    property TrackIndex : TColumnIndex read FTrackIndex write FTrackIndex;
    property TreeView : TCustomControl read GetTreeView;
    property UpdateCount;
    {$IF (CompilerVersion > 36) or Declared(RTLVersion122)}{$WARN OVERLOADING_ARRAY_PROPERTY ON}{$ENDIF}
end;
```
Notes:
- If the $WARN OFF comes immediately after the Items declaration you still get the warning.
- Delphi 12.2 still defines RTLVersion121.  Presumably if there is a Delphi 12.3 etc.  RTLVersion122 will be defined.

**Comment by joachimmarder** [comment]
This warning is new in RAD Studio 12.2. The reason for the warning is that `TColumnIndex` is defined as a new type, not an alias.:

`  TColumnIndex = type Integer;`

Removing `type` makes the warning disappear. I can't imagine any reason why `TColumnIndex` needs to be a new type.
