### ISSUE TITLE
Vcl Styles, Win7 Issues

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1269]
I have a user on Win7 reporting that the background color in a VirtualTreeView is black under any theme in Win7 (see image below).  The app is compiled with Delphi 12 and a recent version of VT from the master branch.   Earlier versions of my app, compiled with Delphi 11 and the VirtualTreeView from the master branch as of 10 months earlier appear to work fine  in Win7.

![image](https://github.com/user-attachments/assets/b31d879b-c818-4f85-b459-678560fc1f50)

I know this is not a proper issue report and you may close it.   It may not even be a VT issue, but rather a Vcl issue. However, if you do have any idea whether a change in VT may have caused this, please let me know.

**Comment by joachimmarder** [comment]
A possible reason could be: https://github.com/JAM-Software/Virtual-TreeView/issues/1173

Make sure to also check: https://github.com/JAM-Software/Virtual-TreeView/wiki/Breaking-Changes-in-V8

If Win7 is still important to you, I would stick with VTV V7.

**Comment by pyscripter** [comment]
Thanks for the quick response.

> A possible reason could be: #1173

But the app is using Vcl Styles as you see in the screen shot, not the classic mode.  It was painting fine with Vcl styles in Win7 before.  The rest of the components appear to paint well with Vcl styles in Win 7.   

What are the commits related to closing #1173?

Does anyone have access to Win 7?  Can anyone reproduce this with the master branch and one of the demos?

**Comment by pyscripter** [comment]
I got another screenshot from the user:

![image](https://github.com/user-attachments/assets/760ad1d2-b541-4b9b-a7ee-8a983a18505a)

All other controls are painted fine with Vcl styles.  It is just the VTs that exhibit the problem.

**Comment by joachimmarder** [comment]
It would still be interesting to know if the customer uses the classic mode. But anyway, the best solution to support Win7 is to stick with VTV 7 and Delphi 11.

**Comment by pyscripter** [comment]
> It would still be interesting to know if the customer uses the classic mode.

"My system Win7 x32, Windows theme Classic
The problem is independent of the Windows theme setting (change themes - problem exist)."

But if you use Vcl styles rendering should not depend on the Windows theme.  Isn't that right?

It would be nice if VTV 8 supported Windows 7 at least when using Vcl styles.   I will try to figure out what the problem is, but it would help if you give some clues.   In which commit(s) was the support for Classic mode removed?

**Comment by pyscripter** [comment]
The user reported that VTV display correctly on Win7 with Aero themes enabled.   That is good news.
