### ISSUE TITLE
TColumnIndex in headers

### ISSUE THREAD

**Issue by Dzyszla** [JAM-Software/Virtual-TreeView#1276]
In 8.0.4 (after update from 8.0.3) if I create f.ex. OnBeforeCellPaint or OnGetText, IDE create method with `integer` type, not `TColumnIndex` for `Column` parameter. If I have old method with `TColumnIndex` all works until I try save any change of form - then IDE says:
_The vstDokAfterCellPaint method referenced by vstDok.OnAfterCellPaint has an incompatible parameter list. Remove the reference?_

Changed in: https://github.com/JAM-Software/Virtual-TreeView/commit/299e29136623b84fd734559ca1135f327576c098

**Comment by joachimmarder** [comment]
Which version of RAD Studio are you using?

**Comment by Dzyszla** [comment]
10.0 and 11.3.
In 12.1 works right.
