### ISSUE TITLE
Wrong library paths are suggested in install.txt

### ISSUE THREAD

**Issue by ImperatorZurg** [JAM-Software/Virtual-TreeView#1277]
If the library paths are set to the ‘Source’ directory as specified, Delphi always recompiles the Virtual-TreeView units because it cannot find any DCU in this directory. It does this with the current project settings and then e.g. BOOLEVAL is ON, which causes problems in the Virtual-TreeView.
So "Packages\RAD Studio 10.4+\Win32\Release" for 32bit and "Packages\RAD Studio 10.4+\Win64\Release" for 64bit must be specified as library paths. Used resource files must also be copied to these paths.

**Comment by joachimmarder** [comment]
The instructions Install.txt are that way for many years now, I will therefore only change it for the newer versions. Please let me know what you think.

**Comment by ImperatorZurg** [comment]
Yes, in my opinion that should be quite sufficient.

 

But the description is still not quite right.

2. Right click on root elelment "VirtualTreeView" and click "Build All". This builds only the selected target of all projects. With the current changes, the project will only be compiled for the Win64 platform and not for the Win32 platform. So for new installations there will be no „Packages\RAD Studio 10.4+\Win32\Release“ directory and for updates it would still contain the old Win32 version.

 

In my opinion, it would also be a good idea to change the unit output directory of Delphi from „.\$(Platform)\$(Config)“ to „..\..\Library\RAD Studio 10.4+\$(Platform)\$(Config)“ to have a separate library directory for the DCUs. The library path would then be „Library\RAD Studio 10.4+\Win64\Release“

 

 

Von: Joachim Marder ***@***.***> 
Gesendet: Donnerstag, 21. November 2024 18:28
An: JAM-Software/Virtual-TreeView ***@***.***>
Cc: ImperatorZurg ***@***.***>; Author ***@***.***>
Betreff: Re: [JAM-Software/Virtual-TreeView] Wrong library paths are suggested in install.txt (Issue #1277)

 

The instructions Install.txt are that way for many years now, I will therefore only change it for the newer versions. Please let me know what you think.

**Comment by joachimmarder** [comment]
> With the current changes, the project will only be compiled for the Win64 platform and not for the Win32 platform. 

Are you sure? In my tests this worked, because the design time package is (must be) Win32 and has a dependency to the runtime package, which is then compiled automatically for the correct platform in my tests.

> In my opinion, it would also be a good idea to change the unit output directory of Delphi from „.\$(Platform)\$(Config)“ to „..\..\Library\RAD Studio 10.4+\$(Platform)\$(Config)“ to have a separate library directory for the DCUs. 

Sorry, but I don's see any true advantage here. Maybe It's a matter of taste. Since the change may cause trouble for existing installations I won't do such a change unless there is a true advantage.
