### ISSUE TITLE
`TBaseVirtualTreeView.GetDisplayRect` may run into an infinite loop and crashes with an integer overflow shortly after

### ISSUE THREAD

**Issue by hermannoffen** [JAM-Software/Virtual-TreeView#1278]
The method `TBaseVirtualTreeView.GetDisplayRect` can – under certain circumstances – run into an infinite loop when aggregating the visible nodes' heights:
```pascal
  if tsUseCache in FStates then
  begin
    // If we can use the position cache then do a binary search to find a cached node which is as close as possible
    // to the current node. Iterate then through all following and visible nodes and sum up their heights.
    Temp := FindInPositionCache(Node, TopOffset);
    CacheIsAvailable := Assigned(Temp);
    while Assigned(Temp) and (Temp <> Node) do
    begin
      Inc(TopOffset, NodeHeight[Temp]);
      Temp := GetNextVisibleNoInit(Temp, True); // ⚡ <---- can wrongly return `Temp` again causing `TopOffset` to overflow eventually
    end;
  end;
  if not CacheIsAvailable then
  begin
    // If the cache is not available then go straight through all nodes up to the root and sum up their heights.
    Temp := Node;
    repeat
      Temp := GetPreviousVisibleNoInit(Temp, True); // ⚡ <---- can wrongly return `Temp` again causing `TopOffset` to overflow eventually
      if Temp = nil then
        Break;
      Inc(TopOffset, NodeHeight[Temp]);
    until False;
  end;
```

Methods `GetNextVisibleNoInit` and `GetPreviousVisibleNoInit` normally shouldn't return the node they've been called with. But, when they do, `TopOffset` is incremented over and over again and eventually overflows. This might be a regression from my recently merged PRs #1274 and #1275, though I am not completely sure.

The problem occurs when node `Temp` is marked as visible (i.e. has state `vsVisible`) itself but is effectively invisible by a collapsed or invisible ancestor node. In these cases, the optimization shortcut of `GetNextVisibleNoInit` and `GetPreviousVisibleNoInit` (as well as their initializing analogues `GetNextVisible` and `GetPreviousVisible`) to skip effectively invisible subtrees can lead their algorithms to find the original node again.

I am going to provide new pull requests for V7 and V8 branches in near term.

**Comment by DGH2112** [comment]
I saw this last week when using the latest commits but didn't have time to isolate the issue as I was supposed to be on holiday.

**Comment by pyscripter** [comment]
When I see a fix to a fix to a fix..., I become a bit unsettled, especially when the latest fix is quite extensive, complex and affects core functionality (GetDisplayRect  is used everywhere) and not some corner case. 

Is there at least an explanation of what exactly caused this issue and hence what this new fix is trying to fix?

**Comment by hermannoffen** [comment]
> ## I saw this last week when using the latest commits but didn't have time to isolate the issue as I was supposed to be on holiday.

Is the problem still reproducible with the proposed changes?

----

> ## When I see a fix to a fix to a fix..., I become a bit unsettled, especially when the latest fix is quite extensive, complex and affects core functionality (GetDisplayRect is used everywhere) and not some corner case.

Yes, absolutely. In this case, imho, the need to fix it again and again, results from the fact, that most to all fixes before always tried to change only a small part, which either left the unchanged rest to stay bugged or at least led to the fact that those methods deteriorated to the point where their algorithms differ significantly. However, they shouldn't differ that much because there are mainly two things to consider:
1. In which direction are we looking for another visible node: previous or next? That is, which way shall the tree be traversed – up or down.
2. On which side are children expanded to: above or below?

This in mind, the search for the next or previous visible node should've been implemented pretty symmetrically, which wasn't the case anymore.
Therefore, I consider the changes being extensive not to be a bad thing but a good one instead, to finally end the fixing back and forth.

Please also note, that the most of the perceived extensity comes from reducing indentation. If those whitespace changes are ignored, the diff shows that a lot less changed actually.

*A third thing to consider on traversal is whether nodes shall be initialized or not. That does not change the algorithm of traversal substantially but only requires some additional calls of `InitNode`. Because of this I do not really differentiate between `GetNextVisible` and `GetNextVisibleNoInit` (nor between `GetPreviousVisible` and `GetPreviousVisibleNoInit`, respectively) above and below.*

----

> ## Is there at least an explanation of what exactly caused this issue and hence what this new fix is trying to fix?

Let me try to explain, starting with what went wrong with `TBaseVirtualTreeView.GetLastVisible` in the past. The malfunctions of that method lead us here.

One important thing to know is that VT supports filtering nodes and hiding those which are filtered out, as you already know for sure. The interesting fact is how this is reflected in a node's internal state. A node hidden by filtering does remain visible according to the `vsVisible` flag but gets the `vsFiltered` flag as well. Thus, it is hidden only when the `toShowFilteredNodes` option isn't set, as you can see in methods `TBaseVirtualTree.GetEffectivelyVisible` and `TBaseVirtualTree.GetEffectivelyFiltered`. Importantly, if such a node is hidden, that does _not_ need to result in its children to be hidden, too. In conclusion, when looking for another visible node traversing top-down one must _not_ skip a subtree because a parent node is effectively hidden because filtered nodes aren't shown. On the other hand a nodes children are effectively not visible when one of their ancestors is collapsed despite still having the `vsVisible` flag set themselves.

Commit 3cd3660 (version 6.0.0) presumably fixed this to be considered (again?) in `TBaseVirtualTreeView.GetLastVisible`. Otherwise, `nil` would've been returned despite some effectively visible sub-nodes. Unfortunately, it did this in a very slow way. Which has been discussed in issue #725.

PR #836 did in fact restore performance but missed this exact case and thereby reintroduced the bug. It went unnoticed until recently, when we provided PRs #1274 and #1275 (we fixed it in V7, too, as we couldn't update to V8 yet).

### So, how did that change affect `GetPreviousVisible` and `GetNextVisible`?

`GetPreviousVisible` called `GetLastVisible` to go down into a subtree. Not in all cases, but in some. When the latter (wrongly) returned `nil`, the former used other means to look for a previous visible node or just exited with `nil`, too. This was no critical problem for `GetDisplayRect` because its loops could handle that result very well. It's result could've been supposedly wrong as well.

But since `GetLastVisible` now has got a (correct) significant result in some more cases by #1274/#1275, `GetPreviousVisible` might return the original node when `GetVisibleParent` was called beforehand. Because, for a last child the traversal goes up and when it goes down again, it finds the node itself again.

The main aspect of the fix is harmonizing the methods in general and the implementation of the optimization to completely skip invisible subtrees in particular. I considered the usage of `GetVisibleParent` for that to be wrong anyway. We can use the general approach looking for visible siblings and go up or down the tree when needed if only we do not lose the information from which effectively invisible subtree we came there. Therefore the new method `GetTopInvisibleParent` goes up only this far, so we can handle the resulting node just like a node with virtually no children at all.

----

I hope this clarifies a bit. I would appreciate a more in-depth discussion of the particular changes a lot.

**Comment by pyscripter** [comment]
Thanks for the explanations.

> Importantly, if such a node is hidden, that does _not_ need to result in its children to be hidden, too.

How can that be in a tree structure?  How can you show children without showing their parent?
I am thinking about say a File Explorer tree.  If a folder is hidden then the contents of the folder are not shown too.

**Comment by hermannoffen** [comment]
In our software _Virtual TreeView_ is used extensively to display hierarchically structured financial/economical data. (Hence, we also developed and often use the otherwise presumably more seldomly used `toChildrenAbove` option.) Imagine something spreadsheet-like. In such a use case it can be totally acceptable and maybe even desired to hide some intermediate levels of the tree.

A structure like this
```
┌ Bank X            :  1,000
│ └ Company A       :  1,000
|   ├ Account 1234  :  1,500
|   └ Account 6789  : -  500
└ Bank Y            :  5,000
  ├ Company A       :  2,000
  | └ Account 3333  :  2,000
  └ Company B       :  3,000
    ├ Account 1100  :    600
    └ Account 2244  :  2,400
```
can needed to be displayed like that without losing its truth:
```
┌ Bank X            :  1,000
|   ┌ Account 1234  :  1,500
|   └ Account 6789  : -  500
└ Bank Y            :  5,000
    - Account 3333  :  2,000
    ┌ Account 1100  :    600
    └ Account 2244  :  2,400
```
*Virtual TreeView* would actually paint it pretty much like this.

But even in a file explorer tree one could think of such a functionality: Imagine having a file structure and an attached edit field input to filter it's elements. Instead of just highlight items that comply to the input filter condition you may like to show only those but keeping the item's indentation, etc.. Thus the TreeView can easily behave like a list view.
You see, it's not mandatory up to the TreeView itself to apply the filter to its nodes recursively but to the data structures providing the nodes and their states.

**Comment by luebbe** [comment]
That was an interesting read!

**Comment by joachimmarder** [comment]
> But even in a file explorer tree one could think of such a functionality: Imagine having a file structure and an attached edit field input to filter it's elements. Instead of just highlight items that comply to the input filter condition you may like to show only those but keeping the item's indentation, etc.. Thus the TreeView can easily behave like a list view.

In my opinion it should be a list then, the filtered results should not be displayed as a "damaged" tree to the user.

Regarding the pull request: I have no time for a review at the moment, so I will merge it in the hope that it does not damage anything in average cases and improves this edge case.
