### ISSUE TITLE
Simplify the Panning code

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#1284]
This is a follow-up to the discussion in #1270.

After spending a couple of days trying to use some of the VT  panning code to add panning to [SynEdit](https://github.com/pyscripter/SynEdit), I discovered that Vcl contains everything needed in the Vcl.IMouse unit.  It works just like in the Delphi IDE, which I presume uses the exact same code.  **_It took just 3-4 lines of code to add panning_** to SynEdit.

What you need to do is add Vcl.IMouse to the uses clause and either:
- add csPannable to ControlStyle and then TControl.WndProc starts panning when the middle button is pressed
- or manually call IMouse.StartPan when you want to start panning.

csPanning is added to the ControlState while panning.   Panning automatically stops, when you press the mouse buttons, kill focus etc. but you can also stop it when appropriate by calling Mouse.PanningWindow.StopPanning.

It works really well, just by using the information from the Scrollbars (quite clever).

If for some reason you don't want to use the Vcl.IMouse unit then I have a couple of suggestions for simpifying the current code.

- You do not need the field FPanningImage.  You can destroy the panning image inside CreatePanningWindow after assigning it to Image.
- You do not need both flags tsWheelPanning, tsWheelScrolling.  Just one, say tsPanning flag is enough.   You just need to remove the panning code from WMMButtonUp. so that if the user lifts the middle button panning carries on, until the user presses the middle button or any other mouse button again.  The Vcl.IMouse code works fine with just one flag csPanning.

If you want I could submit a PR either using the Vcl.IMouse, or just implementing the simplications suggested above.

**Comment by joachimmarder** [comment]
Do you have any idea since when the unit `Vcl.IMouse` is part of the VCL?

> If you want I could submit a PR either using the Vcl.IMouse, or just implementing the simplications suggested above.

That would be great! Thanks!

**Comment by pyscripter** [comment]
> Do you have any idea since when the unit `Vcl.IMouse` is part of the VCL?

Certainly since Seattle https://docwiki.embarcadero.com/Libraries/Seattle/en/Vcl.IMouse

> That would be great! Thanks!

Will do.

**Comment by pyscripter** [comment]
@joachimmarder 
There are two bugs in Vcl.IMouse:
- https://embt.atlassian.net/servicedesk/customer/portal/1/RSS-2521
- https://embt.atlassian.net/servicedesk/customer/portal/1/RSS-2519

The second one can be easily addressed by destroying the panning window manually.   There is no easy fix for the first one, but it is a minor one.   The size of the panning window image is system dpi scaled and not per-monitor dpi scaled.   

In the light of the above, I suggest we keep the existing code.   I will send a PR that addresses only the simplifications of the code.  Do you agree?

**Comment by joachimmarder** [comment]
> In the light of the above, I suggest we keep the existing code. I will send a PR that addresses only the simplifications of the code. Do you agree?

Yes, I fully agree and would appreciate a PR with the code simplifications.

**Comment by pyscripter** [comment]
Submitted the PR.  If/when Embarcadero fixes the above issues, I will provide another PR to remove all panning code and use the Vcl one.

**Comment by joachimmarder** [comment]
>  If/when Embarcadero fixes the above issues, I will provide another PR to remove all panning code and use the Vcl one.

The problem here is that you will need it `$ifdef` the old code since we still support the older RAD Studio versions that contain the bugs. Maybe not worth the effort.
