### ISSUE TITLE
DeleteNodes throwing exception if list of nodes to delete is empty

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1288]
The DeleteNodes method expects a list of nodes to delete.
If one passes an empty list (length = 0) the method throws an exception
as it doesn't check if the list contains items. It would be nice if it would first 
check this and just leave the method if the array passed is empty.

**Comment by joachimmarder** [comment]
Done

**Comment by MHumm** [comment]
Thanks for this quick fix!
