### ISSUE TITLE
Enhancement: Add a toFullHorizGridLines

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#136]
_From [azzaazz...@hotmail.com](https://code.google.com/u/109856590183353766835/) on April 27, 2010 09:08:50_

The toFullVertGridLines works well but there is no toFullHorizGridLines to
complement it to take up the no-columns remaining area.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=136_

**Comment by vincentparrett** [comment]
_From [timotegt...@googlemail.com](https://code.google.com/u/100346166526305102504/) on April 27, 2010 21:56:49_

**Labels:** -Type-Defect Type-Enhancement

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 23, 2014 13:58:00_

**Status:** New

**Comment by joachimmarder** [comment]
Closing this issue as WontDo after more than 10 years.
