### ISSUE TITLE
Backround image supports only bitmaps

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#148]
_From [an...@rambler.ru](https://code.google.com/u/112596839914873516355/) on May 25, 2010 22:33:09_

Background property somewhy supports only BMP images, though it is 
declared as TPicture which supports JPG, GIF, PNG and many other formats. 
Having taken a look into the code I found massive usage of 
FBackground.Bitmap so it will be not so easy to fix. So, there are 3 ways:
1) _the best but probably the hardest_ Get rid of Bitmap, use only Canvas
2) Convert any image loaded to TBitmap internally
3) _the worst but the easiest_ Change FBackground type to TBitmap to avoid 
further confusions

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=148_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on September 23, 2014 12:32:04_

I guess we need to choose way 3 due to a lack of time and developers. We could use code like this in TBaseVirtualTree.SetBackground() (suggested by another user)

 var
   B: TBitmap;
 begin
   if Value.Graphic is TBitmap then
     FBackground.Assign(Value)
   else
   begin
     B:= TBitmap.Create;
     try
       //SZ 2014-09-23 Avoid using B.SetSize in order to keep D7 compatibility!
       B.Width  := Value.Width;
       B.Height := Value.Height;
       B.Canvas.Draw(0,0, Value.Graphic);
       FBackground.Assign(B)
     finally
       B.Free
     end;
   end;

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [fr0st.br...@gmail.com](https://code.google.com/u/108120151676755512560/) on November 18, 2014 03:17:58_

Yep, it's the 2nd way. Quite fine decision.

**Comment by sanjayssk** [comment]
Short issue description for changes.txt:
Backround image property can now load files other than bmp. Tested png, gif and jpg.
