### ISSUE TITLE
Shift+End does not work as expected with toGridExtension + toFullRowSelect options set

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#161]
_From [Dr.David...@gmail.com](https://code.google.com/u/107471269721655878703/) on June 24, 2010 07:01:44_

What steps will reproduce the problem? 1. make a grid with toGridExtension option set
2. click on the first node
3. Press SHIFT+END What is the expected output? What do you see instead? I would expect all nodes selected What version of the product are you using? On what operating system? 4.86 Please provide any additional information below. this is happening because the FocusedNode is not being set in WMKeyDown in 

```
              if not ActAsGrid or (ssCtrl in Shift) then
                FocusedNode := Node;
              if ActAsGrid and not (toFullRowSelect in FOptions.FSelectionOptions) then
                FocusedColumn := NewColumn;
            end;
```

because ActAsGrid=True....

Is this the desired behaviour? I presume Shift+End should work even with toGridExtension on? I think the code should be 

if not ActAsGrid or (ssCtrl in Shift) or (ssShift in Shift) then
  FocusedNode := Node;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=161_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 18, 2013 13:29:08_

Is this problem still present in V5.2.2?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [Dr.David...@gmail.com](https://code.google.com/u/107471269721655878703/) on December 18, 2013 15:42:41_

It is still a problem. I have attached a sample program demonstrating the issue.

**Attachment:** [temp.zip](http://code.google.com/p/virtual-treeview/issues/detail?id=161#hc2)

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 19, 2013 11:15:53_

I think this behavior is by design. Like typical grids pressing the END key selects the last cell in the current row. The VCL TStringGrid does it that way too.

Without grid extensions it behaves like a list and the END-key jumps to the last item/node.

In your sample it makes no real sense to activate the grid extensions.

**Status:** Invalid

**Comment by vincentparrett** [comment]
_From [Dr.David...@gmail.com](https://code.google.com/u/107471269721655878703/) on December 19, 2013 11:22:59_

Hi Joachiom,

I am not talking about END, I am talking about SHIFT+END. Go to windows explorer, click on the first entry, and do SHIFT+END, it will select everything until the end. Go to Word, press SHIFT+END and it selects everything from the cursor to the end. That is very standard windows behavior.

As for my example, I went through a lot of effort to make a very simple example that reproduced the problem. Of course that example does not need gridExtensions, it is designed to show you a bug, not to be a standalone application. The real application I use does benefit from toGridExtensions. And it is very standard behavior in windows grids that SHIFT+END selects from the current cursor until the end of the list.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 19, 2013 13:36:13_

> I am not talking about END, I am talking about SHIFT+END.

The Shift+\* behave always behave just like \* but with selecting everything.

> Go to windows explorer, click on the first entry, and do SHIFT+END, it will select everything until the end.

Windows Explorer is not a grid, it is a list with columns. To achieve Windows Explorer behavior, simply turn off grid extensions. Please don't compare apples and oranges.

> ...the current cursor until the end of the list.

to the end of the list, that's correct. But a grid is not a list.

> Go to Word, press SHIFT+END and it selects everything from the cursor to the end.

Not inside a table.

**Comment by vincentparrett** [comment]
_From [Dr.David...@gmail.com](https://code.google.com/u/107471269721655878703/) on December 19, 2013 21:20:50_

Word tables are not a good example. If the entire row is selected in Word, SHIFT+END simply selects the next row. That does not make much sense under any definition.

If you put a TStringGrid on a form, put on goRowSelect and press SHIFT+END it will select to the end of the grid. If goRowSelect is not on, SHIFT+END selects the rest of the columns until the end of the row. That is perfectly consistent and logical behavior.  Maybe that would be a solution?

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 21, 2013 23:41:58_

> Word tables are not a good example

A table compare better to a grid than to a list. The important part here is that SHIFT+END performs an action within the current row too, not within the list.

> If you put a TStringGrid on a form, put on goRowSelect and press SHIFT+END
> it will select to the end of the grid. If goRowSelect is not on, SHIFT+END
> selects the rest of the columns until the end of the row. That is perfectly 
> consistent and logical behavior.  Maybe that would be a solution?

Agreed. With toFullRowSelect turned on it would make sense to change the behavior according. I doubt that there are many VTs in grid mode that have toFullRowSelect turned on, because you will loose again part of the grid features.

**Summary:** Shift+End does not work as expected with toGridExtension + toFullRowSelect options set  <span class="oldvalue"> (was: Shift+End does not work with toGridExtension option set) </span>  
  **Status:** New  
  **Labels:** -Priority-Medium Priority-Low

**Comment by sanjayssk** [comment]
I tested this today on the Grid demo of Advanced project. Even the normal Home and End do not work in toFullRowSelect. Nothing happens. However, if I press Ctrl with Home, End or even Shift-End, it works fine as expected. Any comments?

**Comment by sanjayssk** [comment]
Even the Home and End keys didn't work normally in fullRowSelect. Same fix worked.

**Comment by Dave-Novo** [comment]
Thank you for fixing this. It is great to see that you guys are going through old issues!
