### ISSUE TITLE
Gutter enhancement

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#168]
_From [antoniak...@gmail.com](https://code.google.com/u/116383953624489412477/) on July 22, 2010 00:55:50_

I think it would be really useful to have some mechanism to use gutter with the VT. It seems to be not very difficult to implement (at first look a few virtual methods should be enought - BeforePaint, AfterPaint and PaintCell). What do you think of that?

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=168_

**Comment by vincentparrett** [comment]
_From [antoniak...@gmail.com](https://code.google.com/u/116383953624489412477/) on July 22, 2010 05:48:04_

My proposal of the gutter is shown on the picture

**Attachment:** [VTGutter.png](http://code.google.com/p/virtual-treeview/issues/detail?id=168#hc1)

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on July 22, 2010 13:51:23_

Only required in very rare cases, don't you think? Why not try and implement that outside the official VT sources, in the events you mentioned?

**Comment by vincentparrett** [comment]
_From [antoniak...@gmail.com](https://code.google.com/u/116383953624489412477/) on July 24, 2010 06:27:11_

I do not think so :) In my opinion have some kind of ability to use gutter (I used it twice in my code) is much more interesting (useful) than fixed columns (I have never used it yet) :P But of course it is only my opinion. 
To be honest some time ago I tried to implement the functionality and I have done working one. But it has some limitation and in some cases it does not work as it should. Because of that I was introduce it here as a proposal. 
By the way, does anyone know how to change the type of the issue from Defect to Enhancement?

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on July 25, 2010 05:23:06_

Changing an issue's type is restricted to administrators here at Google Code, so you cannot do so, must be done by Timo or so.

To come back to the proposal: If you think this should really get part of the official sources you should at least provide some practical situations in which such a gutter is needed. I'm failing to find some case - no ideas here. Also I never came across such an idea in the past.

Isn't such a gutter the same as the lines and plus/minus buttons already are for? This way it sounds like duplicating a feature.

Please understand that the sources are huge already and very complex to maintain. A gutter sounds even alone very complex to implement.

I would recommend to watch this issue for some time if it gets more stars/votes than currently (1 is ... not enough I'd say).

**Comment by vincentparrett** [comment]
_From [antoniak...@gmail.com](https://code.google.com/u/116383953624489412477/) on July 26, 2010 16:47:32_

Personally I had two practical situations. The first, when I wanted to show some dependencies between objects stored in the treeview. Some of the objects were linked (sometime more than once) to other (see Dependencies.png). The second situation was when I needed to visualize (in a Delphi style) which objects of the tree were very new (green bars on ChangeFlag.png) and which of them had been changed and not saved yet (red bar). Maybe there is a better way to do it... but I fail to find it. Additionally you may also want to see HeidiSQL.png where I showed a possibility of showing dependencies between tables (foreign keys). 

Get back to my proposal. I understand that process of maintaining sources of so complicated component must be very difficult. Also I understand why you prefer not to implement additional functionality if you are not sure that it could be useful... But IMHO the proposed gutter functionality could be very useful and relatively easy to implement. As I mentioned before, some time ago I implement a part of the functionality but, to be honest, it was rather poor. Mostly because I implemented the functionality in a descendant class... where I had no access to some internal fields (FEffectiveOffsetX and so on) and methods. Because I understand that you (Ansgar, Timo and others) are very busy, and probably you have a lot of other things to fix of implement, so I tried to implement the gutter functionality (see VirtualTrees.zip). Of course my code is not optimal but it works (see VTGutterTest.zip). One thing I just ask you is to look at my code and to consider implementing it after necessary changes in the official sources.

**Attachment:** [Dependencies.png ChangeFlag.png HeidiSQL.png VirtualTrees.zip VTGutterTest.zip](http://code.google.com/p/virtual-treeview/issues/detail?id=168#hc7)

**Comment by vincentparrett** [comment]
_From [antoniak...@gmail.com](https://code.google.com/u/116383953624489412477/) on October 21, 2010 02:22:44_

Has anyone tested the code I included previously?

**Comment by vincentparrett** [comment]
_From [timotegt...@googlemail.com](https://code.google.com/u/100346166526305102504/) on November 24, 2010 23:17:04_

I tested it a bit, but you seem to be the only one interested in this feature.
If more people star this issue, I will consider adding it.

I'm sorry, but a primary goal is to keep the source code maintainable. Once I start to add features for a single person, we will sooner or later end in a maintenance nightmare.

**Labels:** -Type-Defect Type-Enhancement

**Comment by vincentparrett** [comment]
_From [antoniak...@gmail.com](https://code.google.com/u/116383953624489412477/) on November 26, 2010 06:15:09_

That's right ;) So I will wait :)

**Comment by vincentparrett** [comment]
_From [radoslaw...@gmail.com](https://code.google.com/u/112797034000746194769/) on March 20, 2011 06:50:10_

This is a good idea. That functionality would be useful.

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on March 20, 2011 07:16:33_

I still don't think this would ever be used more than a handful of times all over the world. The above screen from HeidiSQL is not the way I would visualize the dependencies of foreign keys as that would be kind of unreadable. Perhaps I would use the normal parent/child mode to do that, but not with some colored, additional lines.

**Comment by vincentparrett** [comment]
_From [antoniak...@gmail.com](https://code.google.com/u/116383953624489412477/) on May 07, 2012 17:48:50_

Wow! Six stars :) I didn't noticed that before :) What's a surprise :)
To Ansgar: Personally I love your HeidiSQL and I would not change anything in it :) The picture from above is just an illustration of a potential use of the gutter:) Don't be angry with me :)

**Comment by joachimmarder** [comment]
Unfortunately all attachments are are lost. I will close this issue for housekeeping. If someone has implemented it or want to implement it, please send a pull request.
