### ISSUE TITLE
ComputeNodeHeight does not calculate properly for column 0

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#174]
_From [peromi...@gmail.com](https://code.google.com/u/102794851957979293666/) on September 04, 2010 07:54:48_

What steps will reproduce the problem? 1. Make 1 column VirtualStringTree, add icon, add very long text, long exactly so that maybe one word wraps at the end of the line.
1. In the VirtualStringTree1MeasureItem do ComputeNodeHeight based on canvas text and set node height to computed value.
2. See here for some screenshots - http://bit.ly/dDtvs7 4. Download demo c++ builder 2010 project on following urls: http://hotfile.com/dl/66829619/179e4d2/VirtualTreeviewBug.zip.html http://www.filesavr.com/hDIEoowi http://www.filedropper.com/virtualtreeviewbug Or use attached file with this issue. What is the expected output? What do you see instead? Expected output is properly wrapped text. Instead a tiny margin is not computed and the text has ellipsis at the end (3 dots - ...) What version of the product are you using? On what operating system? Win XP but can be reproduced on Win 7 too, r277 (latest) Please provide any additional information below.

**Attachment:** [VirtualTreeviewBug.zip](http://code.google.com/p/virtual-treeview/issues/detail?id=174)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=174_

**Comment by vincentparrett** [comment]
_From [timotegt...@googlemail.com](https://code.google.com/u/100346166526305102504/) on September 28, 2010 12:53:00_

Could you provide a Delphi example? I have no BCB license, so I cannot use your example and have no time to convert it do Object Pascal.

**Comment by vincentparrett** [comment]
_From [peromi...@gmail.com](https://code.google.com/u/102794851957979293666/) on September 29, 2010 21:29:28_

Here is a delphi version that shows this.

Also look on forum here: http://support.soft-gems.net/forums/viewtopic.php?p=4969

**Attachment:** [VirtualTreeViewBugsDelphi.zip Untitled-1.png Untitled-2.png](http://code.google.com/p/virtual-treeview/issues/detail?id=174#hc2)

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 23, 2014 13:58:30_

Is the problem still present in V5.5.1?

**Comment by joachimmarder** [comment]
No response from original reporter, all attachments are lost. I guess most likely this issue has meanwhile been corrected. Otherwise issue #369 should cover this too.

So closing this issue for housekeeping.

**Comment by RussIvan** [comment]
I am using Delphi2010 and VirtualTreeView V5.5.3.
Problem still exists. Even most likely, it remained in the version of VirtualTreeView V7.2.0.
How I fixed it:
1)
function TCustomVirtualStringTree.ComputeNodeHeight(Canvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
 S: UnicodeString): Integer; //VirtualTreeView V5.5.3.
var
//...
begin
  //...
  if Column > NoColumn then
  begin
    PaintInfo.CellRect.Right := FHeader.Columns[Column].Width - FTextMargin;
    //PaintInfo.CellRect.Left := FTextMargin + FMargin; // -=It was=-
    PaintInfo.CellRect.Left := FTextMargin + FMargin + GetImageSize(Node,ikNormal,Column).cx; // -=Has become=-
   //...
  //...
end;
2) 
Replaced functions from VirtualTreeView V5.5.3 by functions from VirtualTreeView V7.2.0
function TBaseVirtualTree.GetNodeImageSize(Node: PVirtualNode): TSize;
function TBaseVirtualTree.DoGetImageIndex(Node: PVirtualNode; Kind: TVTImageKind; Column: TColumnIndex;
  var Ghosted: Boolean; var Index: integer): TCustomImageList;
Add functions from VirtualTreeView V7.2.0
function TBaseVirtualTree.GetImageSize(Node: PVirtualNode; Kind: TVTImageKind = TVTImageKind.ikNormal; Column: TColumnIndex = 0; IncludePadding: Boolean = True): TSize; 
function TBaseVirtualTree.ScaledPixels(pPixels: Integer): Integer;
3) 
In new functions, replaced TImageIndex -> integer

**Comment by joachimmarder** [comment]
Possible Repro: Open `Advanced`project, open unit `WindowsXPStyleDemo`, in IDE add `toVariableNodeHeight` to `TreeOptions.MiscOptions`, set `DefaultNodeHeight` to 42,  and in `WindowsXPForm.XPTreeInitNode()` add the line:
`InitialStates := InitialStates + [ivsMultiline];`

**Comment by joachimmarder** [comment]
Solution is using `GetOffests()` introduced for issue #369.
