### ISSUE TITLE
Change unit output directory of packages

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#183]
_From [sglienke@aagon.com](https://code.google.com/u/sglienke@aagon.com/) on October 21, 2010 17:11:38_

There should be some lib directory with version folders in it (similar to how the packages are organized) where the units are compiled to. If you have more than one Delphi version installed it results in conflicts and/or recompiling the units every time.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=183_

**Comment by vincentparrett** [comment]
_From [sglienke@aagon.com](https://code.google.com/u/sglienke@aagon.com/) on January 30, 2012 02:08:14_

Can someone please fix this issue? Virtual treeview is not usable without modifying packages if using more than one Delphi Version.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 18, 2013 13:27:32_

Is this problem still present?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on June 01, 2014 13:19:50_

This should hopefully not be the case any more, at least for the newer Delphi versions. I'm going to close this issue if not a more specific description will be added.

**Comment by joachimmarder** [comment]
Closing this issue as suggested in the last comment.
