### ISSUE TITLE
Painting issue on fixed colums under Windows Vista and above

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#194]
_From [maro...@gmail.com](https://code.google.com/u/100129799653121949468/) on December 18, 2010 02:20:07_

What steps will reproduce the problem? 1. coFixed option in Header.Columns[x]
2. Windows Vista and above (no matter if you set ThemeAware or UseExplorerTheme), and maybe also Windows XP with themes (not tested)
3. Painting issues on fixed columns
4. This is an addition to the already listed issue of wrong painting an empty background of the tree with fixed columns What is the expected output? What do you see instead? Fixed columns have to be seen uncluttered. Fixed columns are painted as if they were scrolled left by horizontal scrollbar. What version of the product are you using? On what operating system? 4.8.5, but the wrong code is the same also in 5.0.0. Please provide any additional information below. Here is the solution - the code in method TBaseVirtualTree.WMPrintClient
must be similar to the code provided in TBaseVirtualTree.Paint, that is fully functional under Windows 2000.
procedure TBaseVirtualTree.WMPrintClient(var Message: TWMPrintClient);

var
  Window: TRect;
  Target: TPoint;
  Canvas: TCanvas;
  Temp: Integer;
begin
  // Draw only if the window is visible or visibility is not required.
  if ((Message.Flags and PRF_CHECKVISIBLE) = 0) or IsWindowVisible(Handle) then
  begin
    // new code
    Canvas := TCanvas.Create;
    try
      Canvas.Handle := Message.DC;

```
  Temp := Header.Columns.GetVisibleFixedWidth;
  if Temp = 0 then
  begin
    Window := ClientRect;
    Target := Window.TopLeft;

    // The clipping rectangle is given in client coordinates of the window. We have to convert it into
    // a sliding window of the tree image.
    OffsetRect(Window, FEffectiveOffsetX, -FOffsetY);
  end
  else
  begin
    // First part, fixed columns
    Window := ClientRect;
    Window.Right := Temp;
    Target := Window.TopLeft;

    OffsetRect(Window,  0, -FOffsetY);
    PaintTree(Canvas, Window, Target, [poBackground, poDrawFocusRect, poDrawDropMark, poDrawSelection, poGridLines]);

    // Second part, other columns
    Window := GetClientRect;

    if Temp > Window.Right then
      Exit;

    Window.Left := Temp;
    Target := Window.TopLeft;

    OffsetRect(Window, FEffectiveOffsetX, -FOffsetY);
  end;

  PaintTree(Canvas, Window, Target, [poBackground, poDrawFocusRect, poDrawDropMark, poDrawSelection, poGridLines]);
finally
  Canvas.Handle := 0;
  Canvas.Free;
end;

(* old code
// Determine area of the entire tree to be displayed in the control.
Window := ClientRect;
Target := Window.TopLeft;

// The Window rectangle is given in client coordinates. We have to convert it into
// a sliding window of the tree image.
OffsetRect(Window, FEffectiveOffsetX, -FOffsetY);

Canvas := TCanvas.Create;
try
  Canvas.Handle := Message.DC;
  PaintTree(Canvas, Window, Target, [poBackground, poDrawFocusRect, poDrawDropMark, poDrawSelection, poGridLines]);
finally
  Canvas.Handle := 0;
  Canvas.Free;
end;
*)
```

  end;
end;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=194_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 23, 2014 13:59:55_

Is this problem still present in V5.5.1?

**Comment by joachimmarder** [comment]
No response from developer, closing this issue.
