### ISSUE TITLE
Refactor TBaseVirtualTree.PaintTree()

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#214]
_From [vvwwxxyy...@gmail.com](https://code.google.com/u/108711936093008839204/) on April 13, 2011 17:48:24_

Could someone refactor TBaseVirtualTree.PaintTree() so that the painting of the treeview, headers and nodes are each done by individual routines.

As it is, it is such a beast of code that it overwhelms not just the uninitiated but the seasoned ones too --case in point I remember asking Mike if he could do it, he replied that it was too complex to do it in reasonable time.

I am hoping someone here can do it so that the posterity will have a better chance to alter/modify/improve that part of the code.

Thank you,

Adem

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=214_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on June 08, 2012 07:22:35_

**Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-Low

**Comment by joachimmarder** [comment]
I am closing this issue after 13 years now. The code is working, some enhancements were made. I don't see a need to have this issue open.
