### ISSUE TITLE
Virtual RootNodeCount?

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#215]
_From [warping....@gmail.com](https://code.google.com/u/102794936523177235283/) on April 18, 2011 20:17:14_

Wish RootNodeCount be requested via an event as per virtual paradigm instead of having to be set explicitly.

Thanks.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=215_

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on April 18, 2011 10:07:57_

If you request such modifications, don't you think you should explain that much deeper, and post some example workflow? And don't forget to describe the problem to this solution. I guess there is no problem?

**Comment by vincentparrett** [comment]
_From [warping....@gmail.com](https://code.google.com/u/102794936523177235283/) on April 19, 2011 02:59:07_

Actually I think my point was clear enough. If you do take advantage of virtual paradigm in this component (reading further probably won't help your understanding if you don't), you typically provide node counts in OnInitChildren event handler with the exception of root node count. Thus you have two places to provide node counts in two different models, namely pull and push models. I wish it were one place and one model, just for consistency and for the convenience of not bothering when to provide RootNodeCount if it is unknown at design time. 

An example workflow, eh? Ok. You:
1. Add the OnInitChildren event handler as usual. 
2. Check the handler's Node parameter to see if it is your treeview's RootNode (or maybe NULL, if the component writer decides not to disclose the RootNode here). 
3. Set the handeler's ChildCount parameter to whatever root node count you need.
4. Enjoy. 

Is there a problem, may I ask you in return?  No, there is no problem for me, given open source and everything. Yet someone else may find the modification useful too.

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on April 19, 2011 09:07:31_

Definitely makes more sense now, thank you. It has gotten such a habit to set the RootNodeCount so I didn't think of it being implemented in a different approach. Well I guess this would still be a heavy change - not for the man who changes the implementation but for the myriad of developers using VT in their projects. Further on I don't think VT should get another TreeOption flag like "UseOnInitChildrenInsteadOfRootNodeCount" or some other interim solution, as that would just make the code more complex. Hmm..

**Comment by vincentparrett** [comment]
_From [warping....@gmail.com](https://code.google.com/u/102794936523177235283/) on April 19, 2011 11:30:13_

Well, e.g. with {$B-} replacing 

"if Assigned(Node) and (Node <> FRoot) and (vsHasChildren in Node.States) then "

with 

"if Assigned(Node) and ((Node <> FRoot) or (toUseOnInitChildrenInsteadOfRootNodeCount in FTreeOptions.FMiscOptions)) and (vsHasChildren in Node.States) then"

would add one option flag lookup per whole tree reinitialization, which is just some additional O(1) time. Is this the complexity you are talking about?

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on April 19, 2011 12:54:43_

No, I meant that developers suddenly don't have to set the RootNodeCount, but are required to move some code into OnInitChildren, for all VT instances they're using.

**Comment by vincentparrett** [comment]
_From [warping....@gmail.com](https://code.google.com/u/102794936523177235283/) on April 19, 2011 13:36:23_

The developers wouldn't be so required if they had an option. What's wrong with the idea to have an option then?

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on April 19, 2011 14:53:44_

An option would not be consistent in my eyes. Your proposal would only be half baked into the code, leaving two different methods of setting the rootnodecount, confusing beginners, making the VT code more complex than it's now. I can't help it, I think would vote against this stuff. But probably we'll get some more opinions here?

**Comment by vincentparrett** [comment]
_From [warping....@gmail.com](https://code.google.com/u/102794936523177235283/) on April 19, 2011 17:09:47_

Beginners may also well get confused by two current approaches that are to be used simultaneously. And I think I addressed the code complexity question earlier. Hope the decision will rely upon reasoning, not upon voting, and VT is not targeted for those going to stay beginners forever.

**Comment by vincentparrett** [comment]
_From [azzaazz...@hotmail.com](https://code.google.com/u/109856590183353766835/) on October 06, 2012 03:55:13_

Hehe - I wouldn't call anyone who uses VirtualTree a "beginner"...
You have to set RootNodeCount, use an OnGetText event, define a TNodeData record, a PNodeData pointer (albeit if you are storing the data in the tree), set a myriad of TreeOptions to get it looking how you want...again not a "beginner"...
I'm not knocking the component - its brilliant and I use it where I don't use a DBGrid...

How about always calling the event passing thru the current value to allow the value to be changed:
...
fValue:=RootNodeCount;
if assigned(GetRootNodeCountEvent) then
  GetRootNodeCountEvent(Self, fValue);
...

If you are so used to setting the RootNodeCount property, this would work...if you want to use the event this would also work - no need to set an option and backward compatible!

You could I suppose use this...
constructor Create;
inherited;
fRootNodeCount:=Cardinal(-1);

...
if fRootNodeCount=Cardinal(-1) then
  GetRootNodeCountEvent(Self, fRootNodeCount);

**Comment by vincentparrett** [comment]
_From [warping....@gmail.com](https://code.google.com/u/102794936523177235283/) on December 11, 2012 06:48:00_

If it has to be a separate GetRootNodeCountEvent (or rather OnInitRootNodes) event, the latter could at least have the same handler type as OnInitChildren, to provide for reusing the handler.

**Comment by vincentparrett** [comment]
_From [merc2012...@gmail.com](https://code.google.com/u/117972860078860397868/) on January 14, 2013 08:23:51_

Vote against. As root nodes never collapse together, we anyway need to notify VTV that RootNodeCount has changed. I think VTV should not fit to someone’s data model, but have its own transparent one.

**Comment by vincentparrett** [comment]
_From [warping....@gmail.com](https://code.google.com/u/102794936523177235283/) on January 15, 2013 01:54:05_

Tree views are made for people, not people for tree views. It's a pain you have to treat root nodes differently in cases when there is nothing inherently specific about them. It's poor usability.

**Comment by joachimmarder** [comment]
> If it has to be a separate GetRootNodeCountEvent (or rather OnInitRootNodes) event, the latter could at least have the same handler type as OnInitChildren, to provide for reusing the handler.

`OnInitChildren` has a parameter for the parent node, which makes no sense for an `OnInitRootNodes` event. I vote against adding a useless parameter to an event signature just for compatibility to some other event. 

I don't know what code should be placed in an `OnInitRootNodes` event except the assignment of the `RootNodeCount` property. Everything else can and should be done in the `OnInitNode` event.

I also vote against breaking changes just because a property assigned could be moved somewhere else. 

Since one can add such an event easily in a derived class or use a helper function that bis called in `OnInitChildren` and when the form is shown, such an event is not really necessary. Therefore I am closing this issue.
