### ISSUE TITLE
Add new event for custom image drawing

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#282]
_From [tlama.ex.2@gmail.com](https://code.google.com/u/tlama.ex.2@gmail.com/) on August 31, 2012 17:29:10_

Now you can specify the image index and whether the image should be ghosted in the OnGetImageIndex event. But that's the only customization you can do, when drawing the image by the Images image list.

I know you can overpaint the image drawing in one of the after paint events, however it would be fine to have an event for custom image drawing.

Here is one of the cases that would use such event (and, as far as I remember I've needed this too a long time ago): http://stackoverflow.com/q/12189058/960757 My though was to have the event (something like OnCustomDrawImage) which would fire from the PaintImage method before the image and the overlay are actually drawn.

First time for the image and the second time for the overlay (distinguished by the DrawOverlay boolean parameter) passing all parameters needed for the image paint. Default drawing of the image and its overlay would be then driven by the CustomDraw declared boolean parameter; when you'd return True, default drawing won't be performed, when you keep it False, the image would be drawn as now.

See the attached unit, showing such event in the interposed class.

**Attachment:** [Unit1.pas](http://code.google.com/p/virtual-treeview/issues/detail?id=282)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=282_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on September 06, 2012 03:45:32_

**Labels:** -Type-Defect Type-Enhancement

**Comment by joachimmarder** [comment]
We already have lots of draw events and OnGetImageIndexEx which allows using images from different imagelists. I don't see a need for this.
