### ISSUE TITLE
Touch support - finger panning

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#292]
_From [niem...@chefmail.de](https://code.google.com/u/100260777958271938505/) on October 09, 2012 08:00:31_

What steps will reproduce the problem? 1. Drop a TVirtualStringTree on a VCL project's form
2. Add a more nodes than fit on the displayed area and a vertical 
   scrollbar
3. Run the application on a computer with touch screen (e.g. tablet) What is the expected output? What do you see instead? Expected would be, that I cannot only use the scrollbar to scroll but also tap on the grid itsself and while still have my finger put down move that around and scroll vertically with this. According to MS one doesn't really need to implement WM_TOUCH message handling for this as WM_VSCROLL should work, but in my test on a Win7 Acer Tablet it didn't work. Scrollbar works and when trying to catch WM_TOUCH on the form's canvas I can see that I get those. But not on the VST. What version of the product are you using? On what operating system? VST 5.0.1 (newest stable one) with Delphi XE on a Windows 7 Tablet Please provide any additional information below. I'd only like to have vertical panning with my fingers implemented. Would be sufficient and welcome for me.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=292_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 22, 2012 00:59:37_

**Labels:** -Priority-Medium Priority-Low

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 22, 2012 01:08:19_

**Labels:** -Type-Defect Type-Enhancement

**Comment by vincentparrett** [comment]
_From [niem...@chefmail.de](https://code.google.com/u/100260777958271938505/) on November 03, 2014 12:29:51_

Attached is some unit for getting the touch capabilities from Windows.

**Attachment:** [TouchCompatibility.pas](http://code.google.com/p/virtual-treeview/issues/detail?id=292#hc3)

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on January 02, 2015 06:42:08_

At least in XE7 finger panning seems to be working after setting these Optiuons to True in Delphi's Object Inspector:

Touch.InteractiveGestures.igPan
Touch.InteractiveGestureOptions.igoPanSingleFingerVertical

**Status:** Started  
  **Owner:** joachim....@gmail.com  
  **Labels:** -Priority-Low Priority-Medium

**Comment by joachimmarder** [comment]
Works on Windows 8.1 with these properties set:
Touch.InteractiveGestures.igPan
Touch.InteractiveGestureOptions.igoPanSingleFingerVertical
Touch.InteractiveGestureOptions.igoPanSingleFingerHorizontal

Might not work on older Delphi or Windows version as this feature highly relies on functions of the VCL and the OS, but we are not going to address this.
