### ISSUE TITLE
allows column sorting indicators to be on right

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#297]
_From [leeon...@gmail.com](https://code.google.com/u/106252421877520531418/) on October 24, 2012 07:44:53_

heidisql uses the space on the left side of the column to indicate whether there are any indices or foreign keys present. when the column it sorted, the icon is replaced by the sorting indicator. it would be useful if virtual-treeview allowed positioning of the sort indicators on the right, so both icons can be displayed.

originally requested here https://code.google.com/p/heidisql/issues/detail?id=3000 thanks!

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=297_

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on October 23, 2012 23:59:41_

I guess I need to explain:

We don't talk about the internal sort indicator in Aero style. Heidi displays these sort indicator in multiple columns, which required me to use the Header.Columns[x].ImageIndex property. Column headers of primary keys also use the ImageIndex to display some "key" image, but the sort indicator has priority, so the "key" is gone when I set the ImageIndex for the sort indicator.

Now, the actual request is to leave both images visible, or let's say we want to have multiple images on one column header. I guess leeoniya does not care if it's on the left or on the right.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 29, 2012 14:53:16_

Isn't it possible to achieve this using owner drawing?

**Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-Low

**Comment by joachimmarder** [comment]
This issue is now open for >10 years and no pull request was provided, so I am closing it now.
