### ISSUE TITLE
Enhancement/Replacment of Header.Options coFixed...

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#304]
_From [azzaazz...@hotmail.com](https://code.google.com/u/109856590183353766835/) on December 12, 2012 23:33:46_

While I've tried setting columns 0, 1, 2 and 8 to be coFixed, the last column is not displayed until I scroll right...

Can I suggest replacing the coFixed option for a column (which only seems to handle multiple coFixed columns if each column follows another coFixed one) to these properties:

property Header.FixedLeftCount: Integer;
   eg. 3 would fix columns [0], [1] and [2]

property Header.FixedRightCount: Integer;
  eg. 2 would fix columns [count-2] and [count-1]

...this would then create a "scrollable interior" and should make the code base to handle fixed columns easier.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=304_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 12, 2012 11:19:36_

**Labels:** -Type-Defect Type-Enhancement

**Comment by joachimmarder** [comment]
I vote against this enhancement. If there is still a problem with coFixed, we should open a bug for this. If there is a limitation of coFixed that cannot be easily overcome, we should document it.
