### ISSUE TITLE
Incorrect selection paint when toAutoSpanColumns, toGridExtensions and toExtendedFocus are set

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#310]
_From [alexey.n...@mail.ru](https://code.google.com/u/113860087889812441427/) on December 25, 2012 18:50:30_

What steps will reproduce the problem? 1. Set these three options in VT and add in tree three or more columns
2. Write OnGetText event handler. Assign to CellText empty string for 2nd column and non-empty string for 1st and 3rd column
3. Run project
4. First select the 1st column, then the 3rd column in same node What is the expected output? What do you see instead? After select 1st column, selection expands on 2nd column with empty text. This ok. But after select 3rd column, 2nd are stay selected. What version of the product are you using? On what operating system? VT r449 , Delphi2007, Win7Pro x64

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=310_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 31, 2012 06:05:50_

**Labels:** -Priority-Medium Priority-Low

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on January 09, 2014 12:19:01_

Is this problem still present in V5.3.0?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [alexey.n...@mail.ru](https://code.google.com/u/113860087889812441427/) on January 09, 2014 22:24:00_

Yes. In version 5.3.0 the problem remains.

**Comment by ghost** [comment]
Version 6.3
We are using the same setup and experiences the same problem + others; the problems seems to go away when adding the patch-snippet below in TBaseVirtualTree.HandleMouseDown. Note - all components in our applications uses toAutoSpanColumns/toGridExtensions/toExtendedFocus ie maybe the code-snippet should only run if certain conditions are meet:

```
// ...
  // Handle selection and node focus change.
  if (IsLabelHit or IsCellHit) and
     DoFocusChanging(FFocusedNode, HitInfo.HitNode, FFocusedColumn, Column) then
  begin
    if NewColumn then
    begin
      InvalidateColumn(FFocusedColumn);
      InvalidateColumn(Column);
      FFocusedColumn := Column;
      // patch
      if not NewNode and Assigned(HitInfo.HitNode) then
        InvalidateNode(HitInfo.HitNode);
      // /patch
    end;

```

**Comment by ghost** [comment]
This can be reproduced by making a few changes to GridDemo:

GridDemo.dfm - add the following

```
TreeOptions.AutoOptions = [..., toAutoSpanColumns]
TreeOptions.PaintOptions = [..., toAlwaysHideSelection]

```

(toAlwaysHideSelection is not strictly needed but shows the problem in a better way)

GridDemo.pas - change this procedure

```
procedure TGridForm.VST5GetText(Sender: TBaseVirtualTree; Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType; var CellText: UnicodeString);
begin
  // if Column > 0 then
  if (Column > 0) and (Column <> 2) then  
    CellText := Sender.GetNodeData<TGridData>(Node).Value[Column - 1]
  else
    CellText := '';
end;
```

First click Customer ID 2:
![autospan_1](https://cloud.githubusercontent.com/assets/21412465/18293700/dd6f3348-7494-11e6-98bd-ce3a8f266650.jpg)

Now click on LastName on the same row:
![autospan_2](https://cloud.githubusercontent.com/assets/21412465/18293758/2d753e1e-7495-11e6-9131-4adc3369a95a.jpg)

**Comment by sanjayssk** [comment]
I just committed a fix. Please verify.

**Comment by ghost** [comment]
That solves the autospan issue...

Unfortunately there is another redraw bug when toGridExtensions + toExtendedFocus is used -
my internal-InvalidateNode-hack-patch solved that but I had completely forgotten about it - sorry.

If I click-select the MainColumn-cell (which has an icon):
![rowselect_1](https://cloud.githubusercontent.com/assets/21412465/18415524/5710e9e0-77f5-11e6-8cf8-d802251b945a.jpg)

Now click-select another cell:
![rowselect_3](https://cloud.githubusercontent.com/assets/21412465/18415528/93da6482-77f5-11e6-818e-e8b834b8b5e2.jpg)

What happens next is a bit strange:
If I click-select the same cell and moves the mouse a bit then all cells are cleared.
If a click-select another cell that cell is cleared (and sometimes all cells)...

**Comment by sanjayssk** [comment]
The first picture looks more like a fullrowselect so it's not clear what options you are using. Also, what do you mean by clear--clear the content or clear the selection? If you can give me the changes and the steps to recreate the problem in the grid demo similar to what you gave for the earlier problem, it will save my time in verifying the problem and your fix.  Thanks.

**Comment by ghost** [comment]
The other issue is due to unrelated issues in our derived VT-class => this issue is fixed  - thx!
