### ISSUE TITLE
Missing UnfocusedSelectionTextColor in TVTColors

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#325]
_From [danielfr...@gmail.com](https://code.google.com/u/108157369915788608871/) on February 25, 2013 23:13:49_

FocusedSelectionBorderColor and FocusedSelectionColor (and UnfocusedSelectionBorderColor and UnfocusedSelectionColor) seem to be ambiguously named.  The colors mentioned apply to all selected nodes, the "Focus" part of the description is referring to whether the tree itself is focused or not.  Therefore, "SelectionTextColor" should say "FocusedSelectionTextColor".

Following that rename, there should be another color "UnfocusedSelectionTextColor" as it's currently missing and there is no way to tell VT not to distinguish between colors when the tree itself is focused or not.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=325_

**Comment by vincentparrett** [comment]
_From [danielfr...@gmail.com](https://code.google.com/u/108157369915788608871/) on February 25, 2013 05:00:14_

> there is no way to tell VT not to distinguish between colors when the tree itself is focused or not. 

Found toPopupMode as a workaround.

**Labels:** -Priority-Medium Priority-Low

**Comment by vincentparrett** [comment]
_From [jacques....@gmail.com](https://code.google.com/u/113529752881670322134/) on August 02, 2013 02:47:32_

This would be extremely useful if skinned by an external skin engine.
Beside adding a new colour, two methods need to be fixed (tag FCD):

TCustomVirtualStringTree.InitializeTextProperties:
..
        else
          if vsSelected in Node.States then
          begin
            if (Focused or (toPopupMode in FOptions.FPaintOptions)) and not
               (tsUseExplorerTheme in FStates) then
              Canvas.Font.Color := FColors.SelectionTextColor
            else
              Canvas.Font.Color := fColors.UnfocusedSelectionTextColor; // FCD add else
          end;

And 

TCustomVirtualStringTree.PaintStaticText
...
  with PaintInfo do
  begin
    Canvas.Font := Font;
    if toFullRowSelect in FOptions.FSelectionOptions then
    begin
      if Node = FDropTargetNode then
      begin
        if (FLastDropMode = dmOnNode) or (vsSelected in Node.States) then
          Canvas.Font.Color := FColors.SelectionTextColor
        else
          Canvas.Font.Color := Font.Color;
      end
      else
        if vsSelected in Node.States then
        begin
          if Focused or (toPopupMode in FOptions.FPaintOptions) then
            Canvas.Font.Color := FColors.SelectionTextColor
          else
            Canvas.Font.Color := fColors.UnfocusedSelectionTextColor; // FCD Font.Color;
        end;
    end;

**Comment by joachimmarder** [comment]
> FocusedSelectionBorderColor and FocusedSelectionColor (and UnfocusedSelectionBorderColor and UnfocusedSelectionColor) seem to be ambiguously named. The colors mentioned apply to all selected nodes, the "Focus" part of the description is referring to whether the tree itself is focused or not.

I don' think renaming these properties is worth a breaking change. I added comments to those properties to make this clear.
