### ISSUE TITLE
AutoSpan also for header cells

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#328]
_From [kiter...@gmail.com](https://code.google.com/u/106860676425098349302/) on March 12, 2013 19:37:05_

What steps will reproduce the problem? 1. Create a VST in Grid-mode, 3 columns.
2. OnGetText: First 2 columns show some text, 3rd shows nothing.
3. When you now set "toAutoSpanColumns" then the cells left of the empty cells span also use the empty cells place.
4. If a header cell doesn't hold text the autospanning does not work.
(See attached pix VSTSpan.png) What is the expected output? What do you see instead? \* Header cells should auto-span as well.
See attached pix ColSpan.png What version of the product are you using? On what operating system? Currently 4.8.7, will upgrade to V5.x in a couple of days, we are just releasing a bigger project. WinXP, Win7, Win8 Please provide any additional information below. Originally posted here: https://groups.google.com/forum/?fromgroups=#!topic/virtual-treeview/1w7hFxIql0M http://support.soft-gems.net/forums/viewtopic.php?t=2560

**Attachment:** [ColSpan.png](http://code.google.com/p/virtual-treeview/issues/detail?id=328)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=328_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on March 13, 2013 12:54:39_

Wouldn't it make sense to provide a column header text for those cells? At least you are showing values in this column and typically you do provide a column header then.

I guess this approach is a bit unusual and may explain why this is currently not supported.

**Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-Low

**Comment by vincentparrett** [comment]
_From [kiter...@gmail.com](https://code.google.com/u/106860676425098349302/) on March 14, 2013 01:05:24_

I attach a real-world screenshot of functionality I have to reproduce.
As you see merged summary cells do make sense.

**Comment by joachimmarder** [comment]
There was no pull request in the past 11 years, so I am closing this issue now. PR can still be sent.
