### ISSUE TITLE
InternalConnectNode: AdjustTotalHeight not called if Node not FullyVisible

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#362]
_From [adrian.b...@gmail.com](https://code.google.com/u/105480350981203748337/) on August 26, 2013 12:14:46_

During insertion of a node as child of a parent node which is expanded but not currently visible (for example because its parent is collapsed) InternalConnectNode() does not call AdjustTotalHeight() to adjust parents TotalHeight because of the condition FullyVisible:

if FullyVisible[Node] then
begin
  AdjustTotalHeight(...
  Inc(FVisibleCount,...
end;

Because of this, the TotalHeight of the parent is too small - after the parent gets visible (for example by expanding its parent) RangeY is too small and therefore the scroll area does not contain the whole tree.
- Grandparent (Collapsed)
  - Parent (Expanded) (TotalHeight: Height(Parent) + Height(Child 1))
    - Child 1

! InsertNode(Parent,amAddChildLast,...) => Child 2
- Grandparent (Collapsed)
  - Parent (Expanded) (TotalHeight: Height(Parent) + Height(Child 1) // Unchanged)
    - Child 1
    - Child 2

! Expand Grandparent

RangeY smaller than real tree height

Recommendet fix:
Remove the AdjustTotalHeight calls from the four "Case Mode of" branches and insert the following if-then-statment after the "Case Mode of" statement:

If (Mode <> amNoWhere) and (Node^.Parent <> Nil) and (vsExpanded in Node^.Parent^.States) Then Begin
  AdjustTotalHeight(Node^.Parent,Node.TotalHeight,True);
end;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=362_

**Comment by vincentparrett** [comment]
_From [adrian.b...@gmail.com](https://code.google.com/u/105480350981203748337/) on August 25, 2013 19:18:21_

Version: 5.2.0

**Comment by vincentparrett** [comment]
_From [a.hesse...@gmail.com](https://code.google.com/u/107934026450034526346/) on October 21, 2014 05:27:48_

It is really a major bug and should be fixed!

The logic for AdjustTotalHeight should be the same as in InternalDisconnectNode():

 AdjustHeight := (vsExpanded in Parent.States) and (vsVisible in Node.States);

and not:
          // Add the new node's height only if its parent is expanded.
          if FullyVisible[Node] then

See, the comment describes the right behaviour but the code is using the wrong one.

**Comment by vincentparrett** [comment]
_From [a.hesse...@gmail.com](https://code.google.com/u/107934026450034526346/) on October 21, 2014 05:37:43_

or use this code:

```
      // Add the new node's height only if its parent is expanded.
      if Assigned(Node.Parent) and (vsExpanded in Node.Parent.States) and (vsVisible in Node.States) then
```

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 03, 2014 11:16:26_

**Labels:** -Priority-Medium Priority-High

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on January 12, 2015 01:06:45_

Is this problem still present in V5.5.3?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [adrian.b...@gmail.com](https://code.google.com/u/105480350981203748337/) on January 14, 2015 22:40:49_

The code of InternalConnectNode was not changed since 5.2.0 and contains still the wrong conditions for the AdjustTotalHeight call - so there is no reason for me to test it.

**Comment by joachimmarder** [comment]
Should be fixed now using more or less the suggested fix. I did not manage to quickly create a sample project, but the suggested fix makes a lot of sense.
