### ISSUE TITLE
Enhancement: Scrollbars status, if they are visible and what width they are

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#367]
_From [Arioch...@gmail.com](https://code.google.com/u/101175546080106411874/) on September 06, 2013 19:50:04_

Part of https://groups.google.com/forum/?hl=ru#!topic/virtual-treeview/84WAMRb299E To calculate space, available for the node content, application may have to know whether scrollbars are shown, and if they are - how much do they subtract from .ClientRect/.ClientWidth/.ClientHeight

I propose the following changes:

{$If CompilerVersion < 23 } // or which one introduced it ?
const CM_STYLECHANGED = CM_THEMECHANGED;
{$IfEnd}

type
 TVirtualStringTree = class(VirtualTrees.TVirtualStringTree)
 protected
    FScrollBarsBands: TSize;
    procedure DoShowScrollbar(Bar: Integer; Show: Boolean); override;

```
procedure CMStyleChanged(var Message: TMessage); message CM_STYLECHANGED; // declared for ALL compiler versions!!!

procedure CMSystemParametersChanged(var Message: TMessage); message CM_WININICHANGE;

procedure QueryScrollBarsSizes;
```

 public
    property ScrollBarVisibleWidth: integer read FScrollBarsBands.cx;
    property ScrollBarVisibleHeight: integer read FScrollBarsBands.cx;
 end;

procedure TVirtualStringTree.DoShowScrollbar(Bar: Integer; Show: Boolean);
var _H, _V: boolean;
begin
   inherited;

   _H := Bar in [SB_HORZ, SB_BOTH];
   _V := Bar in [SB_VERT, SB_BOTH];

  if Show then begin
      if _H then FScrollBarsBands.cx := GetSystemMetrics(SM_CXHSCROLL);
      if _V then FScrollBarsBands.cy := GetSystemMetrics(SM_CXVSCROLL);
  end else begin
     if _H then FScrollBarsBands.cx := 0;
     if _V then FScrollBarsBands.cy := 0;
  end;
end;

procedure TVirtualStringTree.QueryScrollBarsSizes;
begin
  if FScrollBarsBands.cx > 0 then
     FScrollBarsBands.cx := GetSystemMetrics(SM_CXHSCROLL);
  if FScrollBarsBands.cy > 0 then
     FScrollBarsBands.cy := GetSystemMetrics(SM_CXVSCROLL);
end;

procedure TVirtualStringTree.CMSystemParametersChanged;
begin
   inherited;
   QueryScrollBarsSizes;
end;

procedure TVirtualStringTree.CMStyleChanged;
begin
   inherited;
   QueryScrollBarsSizes; 
{$If CompilerVersion >= 23}
/// current code to call VclStylesChanged
{$IfEnd} 
end;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=367_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on September 09, 2013 11:54:20_

**Labels:** -Type-Defect Type-Enhancement

**Comment by joachimmarder** [comment]
Several improvements have been made since this issue was reported. Most likely it is no more present. In case my assumption is wrong, please open a new issue and include repro steps or a sample project.
