### ISSUE TITLE
Drop below not allowed when hovering mouse over ownerdrawn (?) pixels.

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#375]
_From [barrystaes](https://code.google.com/u/barrystaes/) on September 25, 2013 20:13:18_

What steps will reproduce the problem? 1. Use TVirtualDrawTree.OnDrawNode.
2. Draw a cell using DrawTextW(), it works OK.
3. Draw a cell using TImageList.Draw() and BitBlt() to see problem.

See screenshot. 
(Column 1 and 4 are using TImageList.Draw(), Column 2 is using BitBlt(), Column 3 is using DrawTextW()) What is the expected output? What do you see instead? Step 2 is OK, step 3 shows the problem. What version of the product are you using? On what operating system? Virtual Treeview v5.2 (SVN revision 534 ), on Windows 8 x64.

Sorry i am unable to provide a example code right now, i'll come back on this later.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=375_

**Comment by vincentparrett** [comment]
_From [barrystaes](https://code.google.com/u/barrystaes/) on September 25, 2013 03:14:55_

I forgot to add step 4, use OnDragDrop and log Mode parameter.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on September 30, 2013 12:08:45_

Can this be replicated with the "Advanced" sample project that ships with VirtualTreeView?

**Comment by joachimmarder** [comment]
Never received sample code from reporter. I am closing this old issue imported from Google code. Please open a new one in case the problem still exists.
