### ISSUE TITLE
Background image is ripped and moved during collapse/expand animation

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#381]
_From [jeanmil...@gmail.com](https://code.google.com/u/113242627612841963550/) on October 23, 2013 00:34:48_

What steps will reproduce the problem? 1. Add a Virtual Draw Tree component on a form
2. Add background image that cover entirely the component client rect
3. In the tree, add nodes to create a hierarchy
4. In TreeOptions, activate AnimationOptions.toAnimatedToggle
5. Try to collapse/expand a node What is the expected output? What do you see instead? The node animation should leave the background quiet. But here the background image is ripped and moved during the node animation. What version of the product are you using? On what operating system? Version 5.2.0 (August 2013) Please provide any additional information below. Unfortunately it was not possible to attach the demo project, I permanently received a 404 error when I tried submit issue with the zip file attached. I can send this project on demand, if you give an email (please write to jean_milost@hotmail).

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=381_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 22, 2013 13:14:17_

Can you attach a screenshot?
Do you have a suggestion how to fix the problem?

**Comment by vincentparrett** [comment]
_From [jeanmil...@gmail.com](https://code.google.com/u/113242627612841963550/) on October 23, 2013 06:15:08_

Here is a screenshot of the issue. Further, I sent the demo project that I couldn't attach to the report above to this email: joachim....@gmail.com

To solve the problem, I guess it would take more or less something like this:
1 - determine whether or not the background should be drawn (e.g. it's useless to draw it if all the nodes cover it)
2 - if the background should be drawn, draw it, possibly by optimizing to draw only the rectangle occupied by the background (in this case offsets must be calculated, to draw the correct part of the background)
3 - draw the nodes normally above the background

I am available for any further questions

Regards

**Attachment:** [Animation_Issue.png](http://code.google.com/p/virtual-treeview/issues/detail?id=381#hc2)

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 25, 2013 01:43:29_

I have not yet worked in this part of the code. In case you can supply a patch, I will be happy to include it. Otherwise, it will take some time until this bug will be fixed.

**Labels:** -Priority-Medium Priority-Low

**Comment by sanjayssk** [comment]
The whole slice including the background image is animated. Not possible to fix in the current design. Added a usage comment not to use toAnimatedToggle with a background image.
