### ISSUE TITLE
Invalid line wrapping for multliline nodes (... instead of wrapping)

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#385]
_From [eng...@gmail.com](https://code.google.com/u/116966593084232382571/) on November 07, 2013 00:00:01_

Invalid line wrapping for multiline nodes when toShowVertGridLines in PaintOptions. The line is not splitted into two lines and ... are shown instead.

See example in attachment and the patch.

**Attachment:** [Multiline.zip VirtualTrees.pas.patch](http://code.google.com/p/virtual-treeview/issues/detail?id=385)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=385_

**Comment by joachimmarder** [comment]
The problem still seems to be there. Unfortunately the patch was lost when the project was migrated from Google Code. It would be great if you could provide it again.

**Comment by sanjayssk** [comment]
Can't reproduce the problem. Tried multiline nodes testing with all the following variations:
-- NodeHeight forced high.
-- Long line that is wrappable
-- Line with forced line breaks
-- NodeHeight calculated by variable node height.
