### ISSUE TITLE
Changing between a VCL style and the "Windows" style leads to an invalid window handle error

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#390]
_From [sebastia...@googlemail.com](https://code.google.com/u/109415937787803047522/) on November 15, 2013 23:28:22_

What steps will reproduce the problem? I have a form that has two VSTs and is styled. When i change the style to "windows" at runtime and then back to another style, i get an "invalid window handle" error. What version of the product are you using? On what operating system? Windows 7 64Bit, Delphi XE2, VirtualTreeViewV5.2.2 Please provide any additional information below. FVertScrollBarWindow has the wrong handle due to the style change and the changing of the window handles. Changing to "windows" style does not destroy the TVclStyleScrollBarsHook and so the old handles are still in action if i change to another style.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=390_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on November 24, 2013 12:03:27_

If anyone suggests a fix I will be happy to include it.

**Summary:** Changing between a VCL style and the "Windows" style leads to an invalid window handle error  <span class="oldvalue"> (was: Changing between styles and "windows" lead to an invalid window handle error) </span>

**Comment by joachimmarder** [comment]
Could not reproduce that. I am pretty sure this has been fixed or that this was an XE2 problem which is no longer supported.

**Comment by stbie** [comment]
Hello,

after a long debugging and test, I can reproduce the issue with a minimal demo program now.

While I can not upload the demo project as a zip file I try to describe it....

Create a new project.
Add some styles to the project. I choose "Luna", "Auric".
Add a panel with Align= alTop, and three buttons there.

Add some event handlers to the buttons:
First Button OnClick: TStyleManager.TrySetStyle('Windows');
Secont Button : TStyleManager.TrySetStyle('Luna');
Third Button : TStyleManager.TrySetStyle('Auric');

Place a TPageControl with two TabSheets there:
Place a TVirtualStringTree on one TabSheet.

run the program:
- go to the TabSheet with TVirtualStringTree on it.
- press a button to change the style to **non "Windows"**
- select the other TabSheet
- change **to the "Windows" style**
- change the style to a **non "Windows" style**
- select the TabSheet with TVirtualStringTree 
--> you got the the error 1400 invalid windows handle

What I found out so far:
Problem ist located in "VirtualTrees.StyleHooks"
- If this unit will be removed from "VirtualTrees" and the constant CM_UPDATE_VCLSTYLE_SCROLLBARS is copied the unit "VirtualTrees" --> no error message, but also no style

- In case of error: mostly  in the debugger stops in "TVclStyleScrollBarsHook.UpdateScrollBarWindow" at a call of "ShowWindow".

MSDN says:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-showwindow
SW_HIDE  Hides the window and activates another window. 
Maybe the "activates another window" is the problem ...?

I tried out different things:
Add a combination of xxxScrollBarWindow.Visible and xxxScrollbarWindow.HandleAccocated but this results in complete unlogic behaviour.
If xxxScrollbarWindow.HandleAccocated = False the xxxScrollbarWindow.Handle is still not "0".
The function "HandleAccocated" calls 
function TWinControl.HandleAllocated: Boolean;
begin
  Result := WindowHandle <> 0;
end;
So it seems that the handles of the scrollbars are not correctly refreshed in some circumstances.

I digged not depper for that till now ... not sure how to do that ... 
... Maybe is workerthread involved? ... in debugging mode I got different behaviours ..

I tried out the following workaround with using vcl-styles-utils:
- removing ""VirtualTrees.StyleHooks" from "VirtualTrees" and copy the constant CM_UPDATE_VCLSTYLE_SCROLLBARS to the unit "VirtualTrees"
Add "Vcl.Styles.Utils.Forms" to the form with the "TVirtualStringTree" --> everythings seems to work fine.
I didn't test this with frames and in the real applicaiton till now......

**Comment by joachimmarder** [comment]
> While I can not upload the demo project as a zip file

What exactly prevents you from that? Can you send through another way?

**Comment by joachimmarder** [comment]
Which version of Virtual Treeview did you use?

**Comment by stbie** [comment]
> What exactly prevents you from that? Can you send through another way?

Sorry, my fault. 
I tried to upload via FireFox and I recieved always the following error message from GitHub:
"Something went really wrong, and we can’t process that file. Try again."

Now, I changed to Opera ... seems to work.

[VstBug.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/3122369/VstBug.zip)

> Which version of Virtual Treeview did you use?

My latest version was downloaded on 19th April.
Text from file "changes.txt": V7.2.1: (07 Mar 2019)

Uploaded demo was created with Delphi Tokyo on Windows 10. 
Same issue with Delphi Rio on Windows 7.

**Comment by joachimmarder** [comment]
Strange, Firefox used to work with GitHub uploads. Thanks for sending the sample project. I can reproduce the problem but have no idea what causes it.

The code of the unit `VirtualTrees.StyleHooks` was contributed by someone else when the XE2 release of Virtual TreeView was made. It has a lot of copied code from the base class. VCL themes are not my area of expertise as I don't use them due to their lack of high dpi capabilities.

**Comment by esmilen** [comment]
Delphi 10.4 brings better high-dpi support for styles, so more people might suffer from this bug. I am one of them, but unfortunately I don't have much experience with themes.

It would be great if someone is able to fix the bug.

**Comment by joachimmarder** [comment]
I just tried the sample project with RAD Studio 10.4 and was unable to replicate the issue. Can someone confirm?

**Comment by esmilen** [comment]
I was able to replicate it by switching between a hand full of themes.

**Comment by joachimmarder** [comment]
> I was able to replicate it by switching between a hand full of themes.

I wasn't. Can you provide more detailed repro steps?

**Comment by esmilen** [comment]
I am running it on a mixed high dpi monitor setup (main 200% and the other 150%). Maybe that triggers it.

**Comment by esmilen** [comment]
In Vcl.Forms, TScrollingStyleHook.UpdateScroll calls InitScrollBars to recreate the TScrollWindow instances. I think that is missing in the VirtualTrees.StyleHooks implementation.

**Comment by joachimmarder** [comment]
> I am running it on a mixed high dpi monitor setup (main 200% and the other 150%).

Same here (laptop @ 150% + 27" TFT @ 125%). 

As long as I can't reproduce the bug I can't work on a fix. Please feel free to send a pull request.

**Comment by esmilen** [comment]
Since my last post here, I was forced to disabled theme support for the scrollbars. I just tried with the most recent version from here, and I got the same issue immediately.

The treeview is recreated due to the style change, but TScrollingStyleHook.FVertScrollWnd still refers to the old handle.

**Comment by joachimmarder** [comment]
In the `Advanced` demo project I added a button with the code:

```
  if TStyleManager.ActiveStyle.IsSystemStyle  then
    TStyleManager.TrySetStyle('Glow')
  else
    TStyleManager.TrySetStyle('Windows');

```
I tried it on several pages and pressed this button multiple times, but no error occurred (RAD Studio 10.4.1, Windows 10 1909). Please provide a sample project that allows to replicate the issue or a pull request that fixes the issue.

**Comment by esmilen** [comment]
Well,  while trying to come up with a sample project I am now no longer able to reproduce the issue. I will try it again in the next couple of weeks and will get back to you if I can get a reproducible sample project.

**Comment by esmilen** [comment]
It seems related to call in an override of:

      procedure CMFontChanged(var Message: TMessage); message CM_FONTCHANGED;

I then calculate a new DefaultNodeHeight based on new font settings. I also use Canvas.Handle and change Canvas.Font settings. When I comment the line which uses Canvas.Handle it no longer crashes. Hope this helps.

**Comment by esmilen** [comment]
I have made a sample project that will crash if you click the buttons a couple of times. It seems the issue is related to a combination of Treeview and LMD dock panels. The error occurs when you change style and font.

https://lmd.de/products/vcl/lmddockpack/

I will also report this issue at the LMD.

[TreeviewThemeIssue.zip](https://github.com/JAM-Software/Virtual-TreeView/files/5743018/TreeviewThemeIssue.zip)

**Comment by esmilen** [comment]
Here is feedback from LMD:

FVertScrollWnd is asked for Handle, but Handle is not allocated. On-the-fly Handle creation process fails, because FVertScrollWnd has no Parent, but instead it has assigned value to its ParentWindow property, which refers to old (already non-existing) handle.

So, at this point:

1) FVertScrollWnd.Parent is null.
2) FVertScrollWnd.ParentWindow is not null.
3) IsWindow(FVertScrollWnd.ParentWindow) returns False.

![image](https://user-images.githubusercontent.com/67381261/103159518-c2142c80-47ca-11eb-8dab-d1ec9305447e.png)

**Comment by joachimmarder** [comment]
> It seems related to call in an override of CMFontChanged
> I then calculate a new DefaultNodeHeight based on new font settings. 

Why not use the toAutoScale flag instead? Does it not work as expected?

> I have made a sample project that will crash if you click the buttons a couple of times. It seems the issue is related to a combination of Treeview and LMD dock panels.

I can't compile the sample project as it requires LMD.

> FVertScrollWnd is asked for Handle, but Handle is not allocated.

Please post the full call stack of the exception.

**Comment by esmilen** [comment]
> > It seems related to call in an override of CMFontChanged
> > I then calculate a new DefaultNodeHeight based on new font settings.
> 
> Why not use the toAutoScale flag instead? Does it not work as expected?

That was not the issue after all, but we have custom node heights that need to be recalculated after a font change.

> > I have made a sample project that will crash if you click the buttons a couple of times. It seems the issue is related to a combination of Treeview and LMD dock panels.
> 
> I can't compile the sample project as it requires LMD.

I think the demo would work, even though it does not contain source code.

> > FVertScrollWnd is asked for Handle, but Handle is not allocated.
> 
> Please post the full call stack of the exception.

See my next post.

**Comment by esmilen** [comment]
exception class    : EOSError
exception message  : System Error. Code: 1400. Invalid window handle.

thread $50bc:
004577bb +007 TreeviewIssue.exe System.SysUtils         26337   +0 RaiseLastOSError
005d9785 +11d TreeviewIssue.exe Vcl.Controls             9761  +47 TWinControl.CreateWnd
005d9c5e +016 TreeviewIssue.exe Vcl.Controls             9908   +3 TWinControl.CreateHandle
005ddfec +01c TreeviewIssue.exe Vcl.Controls            12541   +4 TWinControl.HandleNeeded
005ddff9 +005 TreeviewIssue.exe Vcl.Controls            12547   +1 TWinControl.GetHandle
0069c4c1 +0f9 TreeviewIssue.exe VirtualTrees.StyleHooks   378  +28 TVclStyleScrollBarsHook.UpdateScroll
0069d4cf +02b TreeviewIssue.exe VirtualTrees.StyleHooks   866   +4 TVclStyleScrollBarsHook.WMMove
0069d4fa +012 TreeviewIssue.exe VirtualTrees.StyleHooks   874   +1 TVclStyleScrollBarsHook.WMPosChanged
00631b66 +14a TreeviewIssue.exe Vcl.Themes               7394  +38 TStyleHook.WndProc
00631d5c +000 TreeviewIssue.exe Vcl.Themes               7502   +0 TMouseTrackControlStyleHook.WndProc
0069218c +000 TreeviewIssue.exe Vcl.Forms               14423   +0 TScrollingStyleHook.WndProc
0063138a +066 TreeviewIssue.exe Vcl.Themes               7107  +20 TStyleHook.HandleMessage
0075bfd2 +09a TreeviewIssue.exe Vcl.Styles               3598  +22 TStyleEngine.HandleMessage
0062e418 +054 TreeviewIssue.exe Vcl.Themes               5662  +11 TStyleManager.HandleMessage
005d8fab +00f TreeviewIssue.exe Vcl.Controls             9344   +0 TWinControl.DoHandleStyleMessage
005da672 +066 TreeviewIssue.exe Vcl.Controls            10256   +1 TWinControl.WndProc
006f1420 +11c TreeviewIssue.exe VirtualTrees            25798  +32 TBaseVirtualTree.WndProc
005da214 +02c TreeviewIssue.exe Vcl.Controls            10120   +3 TWinControl.MainWndProc
004f2738 +014 TreeviewIssue.exe System.Classes          17989   +8 StdWndProc
77dc600b +04b ntdll.dll                                            KiUserCallbackDispatcher
005e51ff +0ab TreeviewIssue.exe Vcl.Controls            16987  +12 TMargins.SetControlBounds
005d83a9 +319 TreeviewIssue.exe Vcl.Controls             8899  +78 TWinControl.ArrangeControl
005d86e9 +039 TreeviewIssue.exe Vcl.Controls             8949   +1 DoPosition
005d8869 +171 TreeviewIssue.exe Vcl.Controls             9106  +29 DoAlign
005d8d33 +10b TreeviewIssue.exe Vcl.Controls             9250  +33 TWinControl.AlignControls
007b2f5a +04e TreeviewIssue.exe LMDDckSite               3770   +7 TLMDDockPanel.AlignControls
005d8e66 +062 TreeviewIssue.exe Vcl.Controls             9292   +9 TWinControl.AlignControl
005d8ec2 +002 TreeviewIssue.exe Vcl.Controls             9316   +0 TWinControl.Realign
007b3cb4 +20c TreeviewIssue.exe LMDDckSite               4184  +40 TLMDDockPanel.UpdateLayout
007b5163 +077 TreeviewIssue.exe LMDDckSite               4844   +7 TLMDDockZone.UpdatePanelZn
007b632c +044 TreeviewIssue.exe LMDDckSite               5245   +5 TLMDDockZone.UpdateLayout
007b62de +01a TreeviewIssue.exe LMDDckSite               5237   +2 UpdateChild
007b63ba +0d2 TreeviewIssue.exe LMDDckSite               5255  +15 TLMDDockZone.UpdateLayout
007b8590 +1e4 TreeviewIssue.exe LMDDckSite               6289  +35 TLMDDockZoneTree.UpdateLayout
007bc5e5 +099 TreeviewIssue.exe LMDDckSite               8407  +16 TLMDDockSite.UpdateLayout
007b8cda +01e TreeviewIssue.exe LMDDckSite               6540   +2 TLMDDockSite.CMFontChanged
005d5daa +2be TreeviewIssue.exe Vcl.Controls             7480  +91 TControl.WndProc
005dac9b +68f TreeviewIssue.exe Vcl.Controls            10424 +169 TWinControl.WndProc
005d59e4 +024 TreeviewIssue.exe Vcl.Controls             7258  +10 TControl.Perform
005d4601 +03d TreeviewIssue.exe Vcl.Controls             6410   +8 TControl.FontChanged
005a560b +00f TreeviewIssue.exe Vcl.Graphics             2357   +1 TGraphicsObject.Changed
005a5b15 +005 TreeviewIssue.exe Vcl.Graphics             2510   +1 TFont.Changed
005a5431 +049 TreeviewIssue.exe Vcl.Graphics             2034  +10 TResourceManager.AssignResource
005a5b88 +05c TreeviewIssue.exe Vcl.Graphics             2538  +19 TFont.Assign
005d460d +005 TreeviewIssue.exe Vcl.Controls             6422   +0 TControl.SetFont
005d6baf +023 TreeviewIssue.exe Vcl.Controls             7937   +6 TControl.CMParentFontChanged
005d5daa +2be TreeviewIssue.exe Vcl.Controls             7480  +91 TControl.WndProc
005dac9b +68f TreeviewIssue.exe Vcl.Controls            10424 +169 TWinControl.WndProc
00682355 +691 TreeviewIssue.exe Vcl.Forms                4784 +213 TCustomForm.WndProc
005d9415 +02d TreeviewIssue.exe Vcl.Controls             9529   +3 TWinControl.Broadcast
005d9475 +01d TreeviewIssue.exe Vcl.Controls             9555   +9 TWinControl.NotifyControls
005dd167 +033 TreeviewIssue.exe Vcl.Controls            11906   +3 TWinControl.CMFontChanged
0068367d +005 TreeviewIssue.exe Vcl.Forms                5532   +1 TCustomForm.CMFontChanged
005d5daa +2be TreeviewIssue.exe Vcl.Controls             7480  +91 TControl.WndProc
00631b66 +14a TreeviewIssue.exe Vcl.Themes               7394  +38 TStyleHook.WndProc
00631d5c +000 TreeviewIssue.exe Vcl.Themes               7502   +0 TMouseTrackControlStyleHook.WndProc
00699641 +031 TreeviewIssue.exe Vcl.Forms               17838   +7 TFormStyleHook.WndProc
0063138a +066 TreeviewIssue.exe Vcl.Themes               7107  +20 TStyleHook.HandleMessage
0075bfd2 +09a TreeviewIssue.exe Vcl.Styles               3598  +22 TStyleEngine.HandleMessage
0062e418 +054 TreeviewIssue.exe Vcl.Themes               5662  +11 TStyleManager.HandleMessage
005d8fab +00f TreeviewIssue.exe Vcl.Controls             9344   +0 TWinControl.DoHandleStyleMessage
005d59e4 +024 TreeviewIssue.exe Vcl.Controls             7258  +10 TControl.Perform
005d4601 +03d TreeviewIssue.exe Vcl.Controls             6410   +8 TControl.FontChanged
005a560b +00f TreeviewIssue.exe Vcl.Graphics             2357   +1 TGraphicsObject.Changed
005a5b15 +005 TreeviewIssue.exe Vcl.Graphics             2510   +1 TFont.Changed
005a53a8 +04c TreeviewIssue.exe Vcl.Graphics             1976  +11 TResourceManager.ChangeResource
005a5c42 +02a TreeviewIssue.exe Vcl.Graphics             2577   +3 TFont.SetData
005a5f2d +025 TreeviewIssue.exe Vcl.Graphics             2722  +12 TFont.SetHeight
005a5fe4 +018 TreeviewIssue.exe Vcl.Graphics             2766   +1 TFont.SetSize
007c5ba0 +028 TreeviewIssue.exe TreeviewThemeIssue         46   +2 TForm1.Button2Click
005d6303 +073 TreeviewIssue.exe Vcl.Controls             7596   +9 TControl.Click
005eef46 +01e TreeviewIssue.exe Vcl.StdCtrls             5602   +3 TCustomButton.Click
005f00c4 +00c TreeviewIssue.exe Vcl.StdCtrls             6237   +1 TCustomButton.CNCommand
005d5daa +2be TreeviewIssue.exe Vcl.Controls             7480  +91 TControl.WndProc
005dac9b +68f TreeviewIssue.exe Vcl.Controls            10424 +169 TWinControl.WndProc
005eeba0 +06c TreeviewIssue.exe Vcl.StdCtrls             5432  +13 TButtonControl.WndProc
005d59e4 +024 TreeviewIssue.exe Vcl.Controls             7258  +10 TControl.Perform
005dadfb +023 TreeviewIssue.exe Vcl.Controls            10493  +12 DoControlMsg
005db9f3 +00b TreeviewIssue.exe Vcl.Controls            10770   +1 TWinControl.WMCommand
00685999 +045 TreeviewIssue.exe Vcl.Forms                6689   +6 TCustomForm.WMCommand
005d5daa +2be TreeviewIssue.exe Vcl.Controls             7480  +91 TControl.WndProc
005dac9b +68f TreeviewIssue.exe Vcl.Controls            10424 +169 TWinControl.WndProc
00682355 +691 TreeviewIssue.exe Vcl.Forms                4784 +213 TCustomForm.WndProc
005da214 +02c TreeviewIssue.exe Vcl.Controls            10120   +3 TWinControl.MainWndProc
004f2738 +014 TreeviewIssue.exe System.Classes          17989   +8 StdWndProc
77dc600b +04b ntdll.dll                                            KiUserCallbackDispatcher
76ac6d3e +07e USER32.dll                                           SendMessageW
76ac6e2a +07a USER32.dll                                           CallWindowProcW
005dada6 +0e6 TreeviewIssue.exe Vcl.Controls            10465  +30 TWinControl.DefaultHandler
005d6750 +010 TreeviewIssue.exe Vcl.Controls             7729   +1 TControl.WMLButtonUp
005d5daa +2be TreeviewIssue.exe Vcl.Controls             7480  +91 TControl.WndProc
005dac9b +68f TreeviewIssue.exe Vcl.Controls            10424 +169 TWinControl.WndProc
005eeba0 +06c TreeviewIssue.exe Vcl.StdCtrls             5432  +13 TButtonControl.WndProc
005da214 +02c TreeviewIssue.exe Vcl.Controls            10120   +3 TWinControl.MainWndProc
004f2738 +014 TreeviewIssue.exe System.Classes          17989   +8 StdWndProc
76ac660b +00b USER32.dll                                           DispatchMessageW
0068c09f +0f3 TreeviewIssue.exe Vcl.Forms               11005  +23 TApplication.ProcessMessage
0068c0e2 +00a TreeviewIssue.exe Vcl.Forms               11035   +1 TApplication.HandleMessage
0068c415 +0c9 TreeviewIssue.exe Vcl.Forms               11173  +26 TApplication.Run
007d1ab5 +049 TreeviewIssue.exe TreeviewIssue              16   +4 initialization
75f76707 +017 KERNEL32.DLL                                         BaseThreadInitThunk

**Comment by joachimmarder** [comment]
After the font changed The LMD controls call `UpdateLayout()` / `RequestAlign()` even if the window handle is not created. Other  VCL controls don't do that. That's what makes it difficult to replicate the issue without using LMD controls. And I'm not sure if this is entirely correct.

But checking `HandleAllocated` on our side is not a problem. Please confirm that the recent commit fixes you issue. If not, please reopen the issue and post the new call stack again.

**Comment by esmilen** [comment]
Yes, that solves the problem. Thank you for taking the time to look into it.

**Comment by esmilen** [comment]
It seems the added code always returns false, so the scrollbars are no longer painted style aware.
This check does work:

`if IsWindow(FVertScrollWnd.ParentWindow) then`

**Comment by joachimmarder** [comment]
Interesting. It works in some cases, and the base class contains very similar code in `TScrollingStyleHook.UpdateScroll()` that also checks `FVertScrollWnd.HandleAllocated`.

**Comment by joachimmarder** [comment]
Please try my improved fix and confirm that it fixes both issues. Thanks.

**Comment by esmilen** [comment]
No, it generates the same error.

**Comment by joachimmarder** [comment]
> No, it generates the same error.

The original error or the unthemed scrollbars?
Can you supply a sample project?

> This check does work:
> `if IsWindow(FVertScrollWnd.ParentWindow) then`

Can you explain this code and the difference to the current code?

**Comment by esmilen** [comment]
It generates the same error:
System Error. Code: 1400. Invalid window handle.

Control.HandleAllocated returns True (Control.WindowHandle = 4590400)
IsWindow(FVertScrollWnd.ParentWindow) returns False (FVertScrollWnd.ParentWindow = 13436506)

**Comment by joachimmarder** [comment]
While `IsWindow(FVertScrollWnd.ParentWindow)` might cure a symptom, I don't think it fixes the root cause, which must be a deeper problem. Not yet sure if this is in VCL, LMD or Virtual TreeView. I opened #1016 for further work on this. I would be happy to receive a sample project without dependency on LMD.

**Comment by esmilen** [comment]
You are likely right, but I do not know how to come up with an isolated sample project.

**Comment by Daniel-Tr** [comment]
I was able to reproduce this issue in a sample project using the VirtualTree and VCL-Controls only. It requires an invisible tree with window handle though (which may eventually happen if the application uses tabcontrols, and/or configures the header/columns on startup):
[TestProject.zip](https://github.com/JAM-Software/Virtual-TreeView/files/5780573/TestProject.zip) - just compile, run, and hit the button twice (to change the style)

The problem seems to be that the scrollbar-windows used with the hook are not being recreated in this situation, still sticking with the old window handle of the parent (which has been recreated when the style changed). This has been fixed in the VCL already, I will commit the changes right away ..

**Comment by Daniel-Tr** [comment]
@esmilen Could you please check these changes with your project with LMD?

**Comment by esmilen** [comment]
Yes, that seems to work just fine. Thank you for taking time to fix this problem.

**Comment by joachimmarder** [comment]
Thank you very much @Daniel-Tr!

**Comment by joachimmarder** [comment]
Today we saw a very similar problem with this call stack:

```
exception class    : EOSError
exception message  : Systemfehler. Code: 1400. Ungültiges Fensterhandle.

thread $2270:
0049347d TreeSize.exe System.SysUtils                             RaiseLastOSError
007169cb TreeSize.exe Vcl.Controls                                TWinControl.CreateWnd
007170fe TreeSize.exe Vcl.Controls                                TWinControl.CreateHandle
0071752e TreeSize.exe Vcl.Controls                                TWinControl.UpdateShowing
00717709 TreeSize.exe Vcl.Controls                                TWinControl.UpdateControlState
0071beaf TreeSize.exe Vcl.Controls                                TWinControl.CMVisibleChanged
00410142 TreeSize.exe System                                      TObject.Dispatch
007114ed TreeSize.exe Vcl.Controls                                TControl.WndProc
0071874b TreeSize.exe Vcl.Controls                                TWinControl.WndProc
00710fe0 TreeSize.exe Vcl.Controls                                TControl.Perform
0070ef00 TreeSize.exe Vcl.Controls                                TControl.SetVisible
017d3094 TreeSize.exe VirtualTrees.StyleHooks             154  +3 CalcHorizontalRects
017d3107 TreeSize.exe VirtualTrees.StyleHooks             160  +2 TVclStyleScrollBarsHook.CalcScrollBarsRect
017d45d3 TreeSize.exe VirtualTrees.StyleHooks             482  +1 TVclStyleScrollBarsHook.CMUpdateVclStyleScrollbars
00410142 TreeSize.exe System                                      TObject.Dispatch
008571c3 TreeSize.exe Vcl.Themes                                  TStyleHook.WndProc
00857554 TreeSize.exe Vcl.Themes                                  TMouseTrackControlStyleHook.WndProc
008e9cc4 TreeSize.exe Vcl.Forms                                   TScrollingStyleHook.WndProc
008564e9 TreeSize.exe Vcl.Themes                                  TStyleHook.HandleMessage
02130b7e TreeSize.exe Vcl.Styles                                  TStyleEngine.HandleMessage
00851fec TreeSize.exe Vcl.Themes                                  TStyleManager.HandleMessage
00715e14 TreeSize.exe Vcl.Controls                                TWinControl.DoHandleStyleMessage
00717e84 TreeSize.exe Vcl.Controls                                TWinControl.WndProc
018382a3 TreeSize.exe VirtualTrees                      25788 +32 TBaseVirtualTree.WndProc
00710fe0 TreeSize.exe Vcl.Controls                                TControl.Perform
01846a70 TreeSize.exe VirtualTrees                      32723  +5 TBaseVirtualTree.UpdateScrollBars
0183a74a TreeSize.exe VirtualTrees                      26854 +26 TBaseVirtualTree.EndUpdate

```

I will therefore move the code that recreates the scroll wnds inside `CalcScrollBarsRect()` so that it is called in the original call stack and in the new one.
