### ISSUE TITLE
Change property HotNode: Add a setter

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#391]
_From [salvado...@gmail.com](https://code.google.com/u/112227403241462834612/) on November 20, 2013 23:30:26_

I make a patch, to change property HotNode, in like manner FocusedNode. I attach it in this issue. I hope to apply this patch in vst sources.

Thank you

**Attachment:** [VirtualTrees_hottrack.patch](http://code.google.com/p/virtual-treeview/issues/detail?id=391)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=391_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on November 24, 2013 11:59:59_

What version or revision is this patch based on? The patch file states revision 49 .

**Summary:** Change property HotNode: Add a setter  <span class="oldvalue"> (was: Change property HotNode) </span>  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by vincentparrett** [comment]
_From [salvado...@gmail.com](https://code.google.com/u/112227403241462834612/) on November 24, 2013 15:26:05_

Sorry, I make patch using my personal repository. Anyway my patch based on revision 576 , lastest revision.

**Comment by sanjayssk** [comment]
Can't see the patch. Not clear in the absence of patch. What is the purpose? The referred example FocusedNode generates an event in the setter on any value change. For HotNode, an event occurs for not all value changes and has varying conditions at difference place in the code. Hence, generalizing this setter is not straightforward. I request that a usage example be given stating what behavior is expected of the setter.

**Comment by joachimmarder** [comment]
I vote for simply adding a setter to the property `HotNode`, but not to raise any event. If this is needed, a new issue can be opened.

**Comment by joachimmarder** [comment]
Should we call Invalidate() in the setter?
