### ISSUE TITLE
Paint artifacts leftover for a gradient when scrolling horizontally

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#394]
_From [azzaazz...@hotmail.com](https://code.google.com/u/109856590183353766835/) on November 29, 2013 03:32:48_

What steps will reproduce the problem? 1. Assign a BeforeItemEraseEvent
  PaintGrad(TargetCanvas, ItemRect, $AAAAAA, $DDDDDD, False);
  EraseAction:=eaNone; What is the expected output? What do you see instead? See attachment. What version of the product are you using? On what operating system? 5.2.2 Please provide any additional information below. You won't see a problem if you use a solid colour!

**Attachment:** [paintartifacts.png](http://code.google.com/p/virtual-treeview/issues/detail?id=394)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=394_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 01, 2013 12:19:59_

**Labels:** -Priority-Medium Priority-Low

**Comment by joachimmarder** [comment]
I used this code with V6.6 and was unable to replicate the problem:

`  GradientFillCanvas(TargetCanvas,  $AAAAAA, $DDDDDD, ItemRect, TGradientDirection.gdVertical);
  EraseAction := TItemEraseAction.eaNone;
`
