### ISSUE TITLE
Incorrect ClipCanvas behavior in PaintTree().

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#395]
_From [goobit....@gmail.com](https://code.google.com/u/102550060985554663110/) on November 30, 2013 00:20:51_

The problem occurs when poUnbuffered is set in PaintOptions. This code (line 31914 in r576 ):

  . . .
  else
  begin
    SetCanvasOrigin(PaintInfo.Canvas, -TargetRect.Left + Window.Left, -TargetRect.Top);
    ClipCanvas(PaintInfo.Canvas, Rect(TargetRect.Left, TargetRect.Top, TargetRect.Right,
    Min(TargetRect.Bottom, MaximumBottom)));
  end;

Problem that SetCanvasOrigin() calls before ClipCanvas(), which uses coordinates without taking into account previously changed canvas origin. 

Simplest way to fix it is just swap this lines: 

  . . .
  else
  begin
    ClipCanvas(PaintInfo.Canvas, Rect(TargetRect.Left, TargetRect.Top, TargetRect.Right,
    SetCanvasOrigin(PaintInfo.Canvas, -TargetRect.Left + Window.Left, -TargetRect.Top);
    Min(TargetRect.Bottom, MaximumBottom)));
  end;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=395_

**Comment by vincentparrett** [comment]
_From [goobit....@gmail.com](https://code.google.com/u/102550060985554663110/) on November 29, 2013 05:30:49_

Sorry, I'm wrong, simple lines swap not helps. We need to fix coordinates in ClipCanvas():

  . . .
  else
  begin
    SetCanvasOrigin(PaintInfo.Canvas, -TargetRect.Left + Window.Left, -TargetRect.Top);
    ClipCanvas(PaintInfo.Canvas, Rect(0, 0, TargetRect.Right - TargetRect.Left,
               Min(TargetRect.Bottom - TargetRect.Top, MaximumBottom - TargetRect.Top)));
  end;

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 12, 2013 13:37:45_

Is it sufficient to set toUnbuffered in PAintOptions to reproduce this bug?
May I ask why you use toUnbuffered?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 12, 2013 13:37:46_

Is it sufficient to set toUnbuffered in PAintOptions to reproduce this bug?
May I ask why you use toUnbuffered?

**Comment by vincentparrett** [comment]
_From [goobit....@gmail.com](https://code.google.com/u/102550060985554663110/) on December 13, 2013 03:11:41_

I use toUnbuffered since I use TBitmap32 for back buffer instead of TBitmap and use it in DoPaintNode for directly drawing thumbnails and icons that stored also as TBitmap32 (actually DoPaintNode checks that uses back buffer for painting, otherwise it uses standard TCanvas methods). 

This bug starts from r289 where poUnbuffered was added. Before that painting was always buffered and because of this it always starts at position (0, 0) on the buffer. But adding poUnbuffered didn't fix all paint cases and it normally paints only when TargetRect.TopLeft = (0, 0). In much cases it's enough since poUnbuffered commonly used for painting whole visible tree, but it's not enough when you replace back buffer and PaintTree() processes all partial paintings called by InvalidateRect.

I think that it would be nice to have some general TCustomPaintBuffer and standard inheritor TBitmapPaintBuffer that allow access to internal bitmap directly. But it general idea and I'm not sure that such generalization will be flexible and useful. Currently I didn't found a way how to "insensibly" replace NodeBitmap in PaintTree so I forced to use poUnbuffered to do this.

I must notice that suggested patch didn't fix all problems with poUnbuffered. Due extremely lack of time I still didn't built simple test project that just uses default TImage control and calls PaintTree with Target = (20, 20). Using different background colors for different TreeView parts will display all problems with scrolling and invalidating. So this patch should be deferred before problem will be investigated completely.

**Comment by vincentparrett** [comment]
_From [goobit....@gmail.com](https://code.google.com/u/102550060985554663110/) on January 10, 2014 02:36:38_

Finally I prepare test project that shows incorrect painting with poUnbuffered option. It recursively calls PaintTree() with additional poUnbuffered option and internal TestBuffer.Canvas. TestBuffer is a TBitmap that has size equals to GetTreeRect() size with additional 20 pixel border around.

Main form lets change tree view size (splitter above "spacer" panel), resize columns in header etc, and bitmap immediately reflects all painting problems with poUnbuffered option. Form also includes additional check boxes:
1. Restore brush: if uncheck this checkbox then all painting will be processed with diagonal brush style since PaintTree() doesn't reset it to bsSolid. I think it may sense to reset all using canvas properties to default state.
2. Paint rectangles: Draw over bitmap latest paint rectangles that takes from "Window" parameter of PaintTree() when it calls with poUnbuffered option. It let's see what rectangle actually requested for repaint.
3. Clipping: calls IntersectClipRect() with "Window" rectangle before calling PaintTree() with poUnbuffered option. Actually it not works as expected since in line 32181 ( r591 ) clipping rectangle always resets. Perhaps it also needs to be fixed to preserve initial clipping region.
4. Repaint image border: before calling PaintTree() with poUnbuffered option border always fills with diagonal brush. In other case it paints only when TestBuffer bitmap enlarges.

Currently I haven't complex patch that solves all bugs (my suggestion in this issue is just a tip of the iceberg). I try to do it but due lack of time don't know when it will be ready.

**Attachment:** [TestVTUnbuffered.zip](http://code.google.com/p/virtual-treeview/issues/detail?id=395#hc5)

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on June 20, 2014 12:12:50_

Issue 421 has been merged into this issue.

**Comment by joachimmarder** [comment]
I'm sorry, but it seems that the test project got lost when we moved from Google to GitHub. Is there any chance that you re-submit the test project?

I couldn't find any place where the toUnbuffered flag is ever set in the Virtual TreeView code. That might be the reason why this code is not maintained very well. One important question is: If the toUnbuffered flag is effectivly not used, is it better to fix it or better to remove it?

**Comment by joachimmarder** [comment]
toUnbuffered was removed=> Close
