### ISSUE TITLE
Custom Drag Image support for OLE drag?

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#405]
_From [mailtoA...@gmail.com](https://code.google.com/u/107399094749411851411/) on December 31, 2013 00:39:43_

I've traced the drag start stack:
MouseMove->DoDragging->PrepareDragImage->TVTDragImage.PrepareDrag
and I didn't find branches for custom drag image support.
there should be event like 
PrepareDragImage->DoPrepareOleDragImage->OnPrepareOLEDragImage event.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=405_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 30, 2013 12:56:49_

**Labels:** -Type-Defect Ty4

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 30, 2013 13:02:39_

Maybe it is possible to supply a custom drag image by implementing an IDragSourceHelper COM object.

**Labels:** -Ty4 Type-Enhancement

**Comment by joachimmarder** [comment]
Set property `DragImageKind` to `diNoImage`, in your event handler `OnCreateDataObject` call `VirtualTrees.Utils.ApplyDragImage()` with your `IDataObject` and your bitmap.
