### ISSUE TITLE
unexpected behaviour of functions "GetPreviousVisible()" and "GetNextVisible()"

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#406]
_From [renehoff...@googlemail.com](https://code.google.com/u/105273895307816536488/) on January 09, 2014 19:24:37_

What steps will reproduce the problem? 1. Hide a node with some siblings, which was visible before.
2. Try to determine the next or previous visible node by calling "GetNextVisible()" or "GetPreviousVisible()" for the just hidden node. What is the expected output? What do you see instead? - I expected to get the immediate (visible) neighbor of the just hidden node.
- Instead, I get the parent's first child node when calling "GetNextVisible()" and its last child node when calling "GetPreviousVisible()". What version of the product are you using? On what operating system? Im using VT 5.3.0 ( revision 591 ) with Delphi XE4 on Windows 7 (x64). Please provide any additional information below. /

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=406_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on January 09, 2014 12:18:13_

Can you provide a sample project or describe how to replicate this issue using the Advanced sample project?

**Comment by vincentparrett** [comment]
_From [renehoff...@googlemail.com](https://code.google.com/u/105273895307816536488/) on January 13, 2014 00:37:01_

To replicate this issue:
1. Take the Advanced sample project and change 'TVisibilityForm.RadioGroup1Click' to this:

procedure TVisibilityForm.RadioGroup1Click(Sender: TObject);
begin
  with Sender as TRadioGroup do
  begin
    VST1.BeginUpdate;
    try
      VST1.IterateSubtree(nil, HideNodes, Pointer(ItemIndex), [], True);
    finally
      VST1.FocusedNode := VST1.GetPreviousVisible(VST1.FocusedNode);
      VST1.EndUpdate;
    end;
  end;
end;
1. Set a breakpoint on the line where VST1.FocusedNode is set. (Actually, the focus won't be visibly changed.)
2. Start the demo application, change to visibility demo and select "Node Level 0, Index 2". Now select "hide every second node". On the breakpoint inspect the properties of VST1.FocusedNode ("Index" is still "2".) and do one step to the next line of code. Inspect the properties of VST1.FocusedNode again ("Index should now be "0".), everything is fine.
3. Show all Nodes.
4. Repeat step 3 while selecting "Node Level 0, Index 1" at the beginning. You will probably notice that, after passing the breakpoint, VST1.FocusedNode.Index won't be "0" (as I'd expect it) but "4".

Those steps apply to GetNextVisible as well resulting with opposite directions.

**Comment by Fr0sT-Brutal** [comment]
This was made by design

``` pascal
      // If the given node is not visible then look for a parent node which is visible, otherwise we will
      // likely go unnecessarily through a whole bunch of invisible nodes.
      if not FullyVisible[Result] then
        Result := GetVisibleParent(Result, True);
```

I believe that commenting these lines out will solve the issue but could slow down some other iterations.

**Comment by joachimmarder** [comment]
I am closing this very old issue imported from Google Code. Please open a new one if it still applies.
