### ISSUE TITLE
Select All sometimes fails with toLevelSelectConstraint

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#413]
_From [Ian.Gol...@gmail.com](https://code.google.com/u/104187522429169134478/) on January 29, 2014 20:53:18_

What steps will reproduce the problem? 1. Set toLevelSelectConstraint, toSiblingSelectConstraing, and toMultiSelect.
2. Load treeview with 3 siblings at level 1 or greater, one of which is selected.
3. Click on the selected node.
4. Invoke tree.SelectAll(False). What is the expected output? What do you see instead? Expected to see all siblings selected. In fact the node that was originally selected remained selected but its siblings were not selected. What version of the product are you using? On what operating system? V5.3.0 on Windows 7. Please provide any additional information below. I believe the cause is as follows:

When the node is clicked (step 3) TBaseVirtualTree.HandleMouseDown calls InternalClearSelection (line 24295), which clears the selection and sets 

FLastSelectionLevel := -1.

It then calls InternalAddToSelection(HitInfo.HitNode, True). The True parameter means the ForceInsert path is taken, which leaves FLastSelectionLevel 

set to -1. I think this is the bug.

When I then invoke SelectAll(False), it calls InternalAddToSelection() once more, with a list of all nodes in the tree. This time we take the 'not 

ForceInsert' path. Since FLastSelectionLevel is -1 it sets it to GetNodeLevel(NewItems[0]), but this is 0, the level of the root node of the tree. So 

all nodes in NewItems fail the test for being allowed in the selection: The nodes with the right parent fail the level-equality test (because 

FLastSelectionLevel is wrong) and the nodes that (wrongly) pass the level test fail the parent test. So none are added to the selection.

Workaround:

Remove toLevelSelectConstraint from the selection options.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=413_

**Comment by joachimmarder** [comment]
I am closing this issue now after almost 11 years. Either this issue is solved or it is totally irrelevant.
