### ISSUE TITLE
Cannot resize column if columns on both sides are not resizable

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#414]
_From [sternenf...@gmail.com](https://code.google.com/u/107835618413455988021/) on January 30, 2014 00:47:12_

What steps will reproduce the problem? 1. Go to advanced demo, there into the AlignDemo
2. Disable coResizeable and enable coFixed options of 0th ("english") and 2nd ("hebrew") column
3. Run the demo, try to resize 1st ("greek") column which still is resizable What is the expected output? What do you see instead? You can't resize the column although its coResizable is true and coFixed is false, also the mouse pointer does not change to the "resize" pointer at neither of both edges of this column What version of the product are you using? On what operating system? Win 7 Professional, SP 1, all patches applied
Delphi XE 3
VTV r593 Please provide any additional information below.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=414_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on February 05, 2014 13:22:37_

Reason lies in function HSPlitterHit(), a subfunction of TVTHeader.HandleMessage().

**Owner:** joachim....@gmail.com  
  **Labels:** -Priority-Medium Priority-Low

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on February 05, 2014 13:31:14_

sub-function IsNearBy() makes a difference between fixed and non-fixed column which I currently don't understand and which seems to responsible for the different behavior.

As a workaround, remove flag coFixed.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on March 10, 2014 14:24:36_

**Owner:** risingba...@gmail.com

**Comment by joachimmarder** [comment]
I am closing this issue now after 10 years. Either this issue is solved or it is totally irrelevant.
