### ISSUE TITLE
MainColumn invisible, other columns reject focus, full row select - Home/End not working

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#418]
_From [fr0st.br...@gmail.com](https://code.google.com/u/108120151676755512560/) on February 07, 2014 02:15:41_

What steps will reproduce the problem? 1. Create new VST
2. Create 2 or more columns for it
3. Unset 1st column's coVisible
4. Unset other columns' coAllowFocus
5. Set VST's toFullRowSelect
6. Press HOME/END What is the expected output? What do you see instead? Expected normal HOME/END scroll to 1st/last node. But they just do nothing. What version of the product are you using? On what operating system? Latest SVN @ Win7 Please provide any additional information below. I agree this is abnormal set of options nevertheless UP/DOWN and PGUP/PGDOWN do perform as usual so HOME/END's malfunction is confusing.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=418_

**Comment by vincentparrett** [comment]
_From [fr0st.br...@gmail.com](https://code.google.com/u/108120151676755512560/) on February 06, 2014 07:16:35_

Fix:
line
1. Set other columns' coAllowFocus
   must be
   1. **Unset** other columns' coAllowFocus

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on February 07, 2014 14:11:48_

**Labels:** -Priority-Medium Priority-Low

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on March 10, 2014 14:14:56_

This set of options is so exotic that I doubt this issue will ever be addressed.  Please supply a patch.

**Comment by sanjayssk** [comment]
Cam not reproduce the problem: Changed Grid of Advanced Demo to set the exact options described while putting the grid mode off. Can not reproduce the problem. The Home and End keys work well even with main column off and other columns not allowing focus.

The problem of Home/End key not working was there in Grid Mode. That was fixed with issue 161.

**Comment by Fr0sT-Brutal** [comment]
Confirm, the bug has gone
