### ISSUE TITLE
Incorrect header behavior/painting with BiDiMode right to left

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#427]
_From [risingba...@gmail.com](https://code.google.com/u/102720342954031217016/) on March 29, 2014 23:43:04_

When a right-to-left BiDiMode is enabled the header fails to draw correctly.

Issues:
- gripper missing for left-most column
- vertical line not drawn for left-most column, but for right-most column (which is incorrect)
- overdraw (which fills the unused header area) draw at the wrong side of the header

Screenshots attached. Can be reproduced easily, same for themed/non-themed modes iirc.

Working on several other issues right now, so if someone could get on this it'd be great.

**Attachment:** [bidi mode, missing gripper for left-most column.png bidi mode, incorrect header overdraw, top right.png](http://code.google.com/p/virtual-treeview/issues/detail?id=427)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=427_

**Comment by mbnoimi** [comment]
+1

I suffer from this bug too and I found it very annoying (I wonder why it took so long to fix!). Any way in the attachments you can find a screenshot for this bug (the attachments above don't work):

Before applying Bidimode:
![before applying bidi](https://cloud.githubusercontent.com/assets/284547/6997064/e54b1fd4-dbb4-11e4-9ed0-5d818bee25ec.JPG)

After applying Bidimode:
![after applying bidi](https://cloud.githubusercontent.com/assets/284547/6997065/f124bab8-dbb4-11e4-8dc4-6753c0053d42.JPG)

**Comment by mbnoimi** [comment]
I made a tiny project for better describing this bug:
https://mega.co.nz/#!jh5jwQgB!2YV3KrVr2tfinfONPQQlFK0nllesIKjULWl6WRXAIIE

**Comment by sanjayssk** [comment]
The problem can be recreated by changing BidiMode of the Advanced Demo--Grid. The fix for issue #544 also fixed this problem.
