### ISSUE TITLE
Header is not painted + workaround

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#439]
_From [r...@ees.hu](https://code.google.com/u/116420674790351193060/) on May 22, 2014 01:37:29_

I experience header painting problems on windows 7 and 2008 server from version 5.0, I tested the latest available version 5.4, which still has the issue.

On some controls header is not painted, it does not even leave space for the header, so the first node is on the very top.
When I move the mouse over the header or resizing one of the columns, it kind of painting, but also repainted by the first node. When I resize the column, that the overall width of columns exceed the width of the tree, the header starts appearing normally. This is the way I came to the conclusion to call header.RecalculateHeader. After calling this method, header starts painting correctly.

I broke down the method and found that calling
    SetWindowPos(Handle, 0, 0, 0, 0, 0, SWP_FRAMECHANGED or SWP_NOMOVE or SWP_NOACTIVATE or SWP_NOOWNERZORDER or
      SWP_NOSENDCHANGING or SWP_NOSIZE or SWP_NOZORDER);

solves the problem. I think a call to header.RecalculateHeader is missing from somewhere, or UpdateHeaderRect is called instead of header.RecalculateHeader. Someone could figure it out, who knows the design of the tree better.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=439_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on May 23, 2014 01:13:03_

I never saw this behavior so far. Can you send a project that allows us to replicate the problem? Or can you describe how to modify one of the sample projects so that the issue occurs?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on June 20, 2014 11:37:44_

Please provide more information, otherwise I need to close this bug as Invalid. I cannot create a fix without having a repro. Can you send a project that allows us to replicate the problem? Or can you describe how to modify one of the sample projects so that the issue occurs?

**Comment by joachimmarder** [comment]
Ne repro steps, no reply from reporter. Suggested code is already there. So closing this issue.
