### ISSUE TITLE
Wrong scrollbar when using nodes with variable node height.

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#447]
_Skipping this issue number to maintain synchronization with Google Code issue IDs._

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=447_

**Comment by joachimmarder** [comment]
To fix this issue, `SetChildCount()` now calls `DoMeasureItem()` instead of using `DefaultNodeHeight`, in case the flag `toVaribaleNodeHieght`is set. This was changed in V5.5 in Sep 2014.
