### ISSUE TITLE
Proper sort column header theming when tsUseExplorerTheme is set to true

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#451]
_From [stevecod...@gmail.com](https://code.google.com/u/108861890102507120184/) on July 25, 2014 23:17:09_

This is the revisitation of an old issue, see: https://code.google.com/p/virtual-treeview/issues/detail?id=93 In short, if you compare Windows Explorer (Vista and above) to VirtualTreeview with tsUseExplorerTheme set to true, you'll notice that Explorer sets the background of the sort column header to a hot color. Also, the sort arrow is in the central-top position, while VirtualTreeview has it after the column text - Windows XP style.

I've ported the solution from the above link (credits to lightnin...@imgburn.com) to the latest VT version.

The attached fix is for the V5.4.1 release.

Please consider including it in the next release.

**Attachment:** [VirtualTrees.pas](http://code.google.com/p/virtual-treeview/issues/detail?id=451)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=451_

**Comment by joachimmarder** [comment]
When themedVirtual TreeView tries to mock the appearance of a Windows ListView common control and uses the ListView Windows theme to do so. The right pane of the Windows 7+ Explorer is a different control that Microsoft does not make available as custom control. 

> Explorer sets the background of the sort column header to a hot color.

At least for Windows 8 and Windows 10 this is not the case. But you can easily achieve that using `TVirtualTreeColumn.Color`.

> The attached fix is for the V5.4.1 release.

Unfortunately the file is lost during migration from Google Code to GitHub. If you provide a fix, please include a patch/diff file, which can easily be applied to later versions of the source.. Our Wiki explains how to create one.

I am going to close this issue. Please open a new issue if you feel that something should be changed.
