### ISSUE TITLE
Hottrack selection rectangle stays there incorrectly when moving mouse over sortcolumn with toUseExplorerTheme

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#452]
_From [stevecod...@gmail.com](https://code.google.com/u/108861890102507120184/) on July 25, 2014 23:25:51_

If toUseExplorerTheme is true, then with Vista and above, VirtualTreeview will correctly display a selection tracking rectangle above the hot nodes.

But if you move the mouse from the topmost node to the header, this tracking rectangle incorrectly stays there and only gets removed when you move the mouse out of the area of the VT. See attached screenshot.

Unlike VT in its current state, Explorer will remove the tracking rectangle upon hovering the mouse over the header area.

I've included a fix for this issue for the V5.4.1 release.

Please consider including it in the next release.

**Attachment:** [ScBug1.png VirtualTrees.pas](http://code.google.com/p/virtual-treeview/issues/detail?id=452)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=452_

**Comment by the-Arioch** [comment]
no attachments, no original reporter e-mail...

at least in Advanced Demo on "WinXP painting" page run on Win10 compiled by XE2 the hot tracking ( all-row one ) is correctly removed when mouse is hovering to the header...

**Comment by joachimmarder** [comment]
> no attachments, no original reporter e-mail...

Yes, unfortunately. Google Code import didn't work well regarding these aspects. I guess I will have to close many of these old issue.

**Comment by the-Arioch** [comment]
dunno... maybe special tag and low priority would be better

some of them may be still real issues that maybe one day will give insights....

**Comment by joachimmarder** [comment]
Closing this issue in favor of #626, which seems to be the same issue.
