### ISSUE TITLE
Enhancement: drawing multiple selection rectangles like Explorer

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#454]
_From [stevecod...@gmail.com](https://code.google.com/u/108861890102507120184/) on July 25, 2014 23:44:46_

If toUseExplorerTheme is set to true, and multiple nodes are selected, where the selection rectangles meet the bottom/top line is duplicated, which makes it look quite ugly.

Windows Explorer draws this differently and makes the two rectangles overlap in one point. (see attached screenshot for comparison)

It would be good to have an option to draw this like Explorer does. (Note: other MS apps doesn't seem to respect this kind of drawing either.)

I've tried to find a fix but it seems to be too complicated. Maybe somebody has already done this...

**Attachment:** [ScEnh1.png](http://code.google.com/p/virtual-treeview/issues/detail?id=454)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=454_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 09, 2014 11:35:24_

**Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-Low

**Comment by joachimmarder** [comment]
No pull request was submitted in the past 10 years. The screenshot is lost. I am not sure what actually should be done here. So I am closing this issue.
