### ISSUE TITLE
Vertical scrollbar is drawn in the wrong place

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#455]
_From [stevecod...@gmail.com](https://code.google.com/u/108861890102507120184/) on July 25, 2014 23:51:49_

Historically, VT draws the vertical scrollbar below the header area.

Explorer and the standard TListView draws it next to the header area.

It would be really nice to have an option to put the scrollbar next to the header.

Maybe somebody has a fix for this?

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=455_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on July 28, 2014 14:07:26_

**Labels:** -Type-Defect Type-Enhancement

**Comment by joachimmarder** [comment]
This would require a major refactorings and I honestly don't think that the achieved benefit is worth this effort. There were no similar requests except this. So I am closing this old issue imported from Google Code.
