### ISSUE TITLE
Incorrect triangle button drawing

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#456]
_From [mazi...@gmail.com](https://code.google.com/u/107578846770274151854/) on July 27, 2014 09:17:34_

Revision: 671
OS: Windows 7 x86
Delphi: 2010

Steps to reproduce:
add TVirtualStringTree to a form
Change TreeOptions->PaintOptions include toUseExplorerTheme
Change Font->Name to 'Segoe UI'

add some child nodes and Run

**Attachment:** [triangle_drawing_problem.png VirtualTreeTest.zip](http://code.google.com/p/virtual-treeview/issues/detail?id=456)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=456_

**Comment by vincentparrett** [comment]
_From [mazi...@gmail.com](https://code.google.com/u/107578846770274151854/) on August 11, 2014 00:26:04_

Added correction patch

**Attachment:** [TriangleNodeButton.patch](http://code.google.com/p/virtual-treeview/issues/detail?id=456#hc1)

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 09, 2014 11:34:22_

**Owner:** risingba...@gmail.com

**Comment by joachimmarder** [comment]
The patch and the screenshot were lost when importing the issue from Google Code. Most likely this issue has been fixed in the meanwhile. In case not, please open a new issue.
