### ISSUE TITLE
If the Virtual TreeView control is placed on a control that has the StyleEx flag WS_EX_COMPOSITED set, horizontal scrolloing does not update the header

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#458]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on August 08, 2014 01:13:01_

Seen on Windows 8.1 with V5.4.0. Will add repro later.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=458_

**Comment by SaschaSchaefer** [comment]
I found the reason for this behavior. 
Some interestiong posts regarding similar problems that I found during my research are:
"http://forums.codeguru.com/showthread.php?525163-GDI-Problem-BitBlt()-Doesn-t-Seem-To-Be-Doing-Anything" and "http://stackoverflow.com/questions/1842377/double-buffer-common-controls".

The virtual tree draws the header when it receives a WM_NCPAINT message. During the actual drawing, it creates a bitmap first and then uses BitBlt to copy the bitmap to the canvas, using GetDCEx to obtain the device context.
However, I found that all painting via a HDC needs to be done in WM_PAINT (source: https://groups.google.com/forum/#!topic/microsoft.public.win32.programmer.ui/hZer0Xidf3A)

Using that info, I moved the code to draw the header to TBaseVirtualTree.WMPaint() for testing purposes, which effectively resovled the issue of the non-updating header. See below for example code that I moved to the end of WMPaint:

``` delphi

procedure TBaseVirtualTree.WMPaint(var Message: TWMPaint);
   ...
   R := FHeaderRect;
   Flags := DCX_CACHE or DCX_CLIPSIBLINGS or DCX_WINDOW or DCX_VALIDATE;
   DC := GetDCEx(Handle, 0, Flags);
   FHeader.FColumns.PaintHeader(DC, R, -FEffectiveOffsetX);
   ReleaseDC(Handle, DC);
end;
```
