### ISSUE TITLE
Text widths incorrectly calculated when font quality is set to fqClearTypeNatural

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#465]
_From [crystalartsoftware@gmail.com](https://code.google.com/u/crystalartsoftware@gmail.com/) on September 09, 2014 21:17:40_

If you have VTV.parentFont set to TRUE, and set the forms font.quality property to fqClearTypeNatural in the forms onCreate event, then VTV will incorrectly calculate the width of the text in the VTV columns, resulting in wrongly placed text ellipsis cuttings.

The reason seems to be that the GetTextExtentPoint32 function used by VTV to get the text widths, doesn't support the "fqClearTypeNatural" quality setting.

Replacing GetTextExtentPoint32 with the following code to calculate the widths, seems to fix the problem :

r.create(0, 0, maxInt, maxInt); // r = tRect
drawText(canvas.handle, text, length(text), r, DT_CALCRECT);
width := r.right;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=465_

**Comment by vincentparrett** [comment]
_From [crystalartsoftware@gmail.com](https://code.google.com/u/crystalartsoftware@gmail.com/) on September 09, 2014 04:25:40_

Small correction.

In the fix, 

drawText(canvas.handle, text, length(text), r, DT_CALCRECT);

should be replaced with ...

drawText(canvas.handle, text, length(text), r, DT_CALCRECT or DT_NOPREFIX);

**Comment by vincentparrett** [comment]
_From [crystalartsoftware@gmail.com](https://code.google.com/u/crystalartsoftware@gmail.com/) on September 09, 2014 05:49:21_

One more thing :)

On my system, calling GetTextExtentPoint32 is ~30 times faster than doing the DrawText call, so it might be a good idea - for performance reasons - only to use drawText to get the width when the font quality is set to fqClearTypeNatural.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on September 09, 2014 08:39:18_

Is it just a pixel or two that it is wrong?
Can you attach a screenshot?
Can this be replicated with the "Advanced" sample project?

**Comment by sanjayssk** [comment]
[Sample.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1423893/Sample.zip)
I created a small project (attached) but can't reproduce this problem on Windows 7. Please modify the project to show the problem.
