### ISSUE TITLE
Incorrect behavior with toLevelSelectConstraint and ctrl+A

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#499]
_From [danielde...@gmail.com](https://code.google.com/u/103856956397880610131/) on November 28, 2014 19:30:42_

On a tree with 2 level and level selection constraint.
-Select a node of level 1
-press ctrl+a=>all nodes of level 1 are selected : OK
-click a selected node of level 1 : clear selection is called, setting FLastSelectionLevel to -1.But new selected node being already selected, AddToSelection is not called and FLastSelectionLevel  is kept at -1
-press ctrl+a again : nodes of level 0 are selected instead of nodes of level 1 because FLastSelectionLevel   has the wrong value.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=499_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 01, 2014 11:22:58_

I personally never used toLevelSelectConstraint or edited code related to this feature. In case you are able to supply a patch, I will be happy to include it.

**Comment by vincentparrett** [comment]
_From [danielde...@gmail.com](https://code.google.com/u/103856956397880610131/) on December 03, 2014 23:13:22_

Adding:
//------------
  if Value and (FSelectionCount=0) then
    flastSelectionLevel := getnodeLevel(Node);
//-------------
at the beginning of TBaseVirtualTree.SetSelected seems to work so far for me, but I might be more a quickfix than an actual correction of the LevelSelectConstraint mechanism.

**Comment by sanjayssk** [comment]
Fixed.
