### ISSUE TITLE
Issue with node selection "from code" if toLevelSelectConstraint is activated and some nodes are disabled 

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#500]
_From [danielde...@gmail.com](https://code.google.com/u/103856956397880610131/) on November 28, 2014 21:45:57_

If you click a disabled node it won't be selected(which is ok), but FLastSelectionLevel is set to disabled node level anyway.

As a result, atempting to later select nodes of other levels "from code" (calling tree.selected[node] := True;)  fails because FLastSelectionLevel is different from -1 (and different from the level of the node we want to select). Even if there is no node actually selected at any level. 
Even calling ClearSelection before setting selection does not work, as it detects that selectioncout=0 and do nothing.

Selection "from click" still works however as WMKeyDown do set FLastSelectionLevel to clicked node level.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=500_

**Comment by sanjayssk** [comment]
Fixed.
