### ISSUE TITLE
VT hintwindow crashes in XE7 release mode (VCL.Styles problem)

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#501]
_From [dirk.car...@gmail.com](https://code.google.com/u/115286209605021703301/) on December 04, 2014 21:47:12_

Strange error in VT hintwindow with styles enabled:

crashes in XE7 update1 with VCL.Styles enabled & release mode. 
If i change "StyleServices.GetElementDetails(tttStandardNormal)" to local variable everything work as expected but style is lost.

Here is the patch:

Index: VirtualTrees.pas
# 

--- VirtualTrees.pas    ( Revision 800 )
+++ VirtualTrees.pas    (Arbeitskopie)
@@ -7593,12 +7593,16 @@
                (toUseExplorerTheme in Tree.TreeOptions.PaintOptions)) then
             begin
               if toUseExplorerTheme in Tree.TreeOptions.PaintOptions then // ToolTip style
-                StyleServices.DrawElement(Canvas.Handle, StyleServices.GetElementDetails(tttStandardNormal), R)
-                begin
-                  LDetails:= StyleServices.GetElementDetails(tttStandardNormal);
-                  StyleServices.DrawElement(Canvas.Handle, LDetails, R);
-                end
             else
               begin // Hint style
                 LClipRect := R;
                 InflateRect(R, 4, 4);
-                  StyleServices.DrawElement(Handle, StyleServices.GetElementDetails(tttStandardNormal), R, @LClipRect);
-                  LDetails:= StyleServices.GetElementDetails(tttStandardNormal);
-                  StyleServices.DrawElement(Handle, LDetails, R, @LClipRect);
                 R := LClipRect;
                 StyleServices.DrawEdge(Handle, StyleServices.GetElementDetails(twWindowRoot), R, [eeRaisedOuter], [efRect]);
               end;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=501_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 09, 2014 13:12:31_

Which version of VirtualTreeView are you using (V5.5.2 or trunk)?
Did it work before installing update 1 of XE7?
Could you please supply the actual exception which occurs and the full call stack?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 23, 2014 13:56:43_

Is anyone else experiencing this problem?

**Comment by joachimmarder** [comment]
No reply or similar reports -> Close.
