### ISSUE TITLE
After calling SortTree: MoveTo no longer work

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#504]
_From [dirk.car...@gmail.com](https://code.google.com/u/115286209605021703301/) on December 19, 2014 19:31:06_

Hello, i have written a TVirtualStringTree descandant and can not longer move the nodes after sorting the tree on header click.
I use latest revision.

This is my sorting method:

procedure MyTreeView.DoHeaderClick(HitInfo: TVTHeaderHitInfo);
begin
  inherited DoHeaderClick(HitInfo);

  if HitInfo.Button = mbLeft then
  begin
    if (Header.SortColumn = NoColumn) or (Header.SortColumn <> HitInfo.Column) then
    begin
      Header.SortColumn := HitInfo.Column;
      Header.SortDirection := sdAscending;
    end
    else
      if Header.SortDirection = sdAscending then
        Header.SortDirection := sdDescending
      else
        Header.SortDirection := sdAscending;
    SortTree(Header.SortColumn, Header.SortDirection, False);
  end;
end;

And this is my Move method (Up/Down):

procedure TMyTreeView.MoveSelected(const ADown: Boolean);
var
  Node, Next: PVirtualNode;
begin
  BeginUpdate;
  try
    if ADown then
      begin
        // move selected items down
        Node := GetLast;
        while Assigned(Node) do
        begin
          if vsSelected in Node.States then
          begin
            Next := GetNext(Node);
            if Assigned(Next) and not (vsSelected in Next.States) then
              MoveTo(Node, Next, amInsertAfter, False);
          end;
          Node := GetPrevious(Node);
        end;
      end
    else
      begin
        // move selected items up
        Node:= GetFirstSelected;
        while Assigned(Node) do
          begin
            MoveTo(Node, GetPrevious(Node), amInsertBefore, False);
            Node:= GetNextSelected(Node);
          end;
      end;
    // scroll first selected into view
    Node:= GetFirstSelected;
    if Assigned(Node) then
      ScrollIntoView(Node, False);
  finally
    EndUpdate;
  end;
end;

Steps: 
- Call MoveSelected(True), MoveSelected(False). This works as expected.
- Click on header column to sort the nodes
- Call MoveSelected(True), MoveSelected(False). Nothing happens.

Best regards
Dirk Carstensen

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=504_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 23, 2014 13:54:42_

Can this be reproduced with one of the sample projects?

Do you have assigned an OnCompare event handler?

**Comment by joachimmarder** [comment]
No reply from reporter, no complete sample project. Closing this issue to tidy up.
