### ISSUE TITLE
Use of With

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#510]
I don't think I've ever see so much use of the With statment, even worse, the use of With and multiple identfiers. 

Is anyone going to get upset if I start removing them? It's just painful when refactoring, trying to figure out which method on which object is being called etc.

**Comment by joachimmarder** [comment]
> Is anyone going to get upset 

Nope. Although I think there are more important things to be done.

**Comment by joachimmarder** [comment]
Is anyone volunteering to implement this issue? Otherwise I would like to close it.
