### ISSUE TITLE
Refactoring Ideas?

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#512]
Just wanted to start a discussion on Refactoring the code. Currently VirtualTrees.pas is 38K lines long, which beats the pants off any other source file I have ever worked on! 

Splitting it up is difficult, I made a start with pull request #511 but tried to avoid making any major breaking changes.  I tried to move anything that didn't need to be in the main unit, which resulted in a reduction of 3K lines (still too large to diff on github/googlecode etc).  

The code is heavily intertwined, making it difficult to split up. It makes extensive use of the 'friend' feature in delphi to access private fields in other classes in the same unit. It also make more use of tje With statement than I have ever seen before, in many case with multiple identfiers, which makes the code very hard to understand and refactor. I plan to remove them in any areas of code as I work on them.

Anyone have any thoughts on refactoring, ideas, suggestions etc?

**Comment by joachimmarder** [comment]
Some work is done, but I feel we won't resolve this issue for V6.0.0, so I remove it from the milestone.

**Comment by Fr0sT-Brutal** [comment]
Separating ContentTo\* is quite easy, requires minor changes and allows to reduce main unit by ~1.2k lines. I made a quick test [here](https://github.com/Fr0sT-Brutal/VirtualTreeView_mod/tree/fr0st_sep-export) (consider last commit only)

**Comment by Fr0sT-Brutal** [comment]
https://github.com/Virtual-TreeView/Virtual-TreeView/pull/535

**Comment by the-Arioch** [comment]
Somewhere around v 4.x i made a patch to highlight focused column and/or row so that user could easily see what exactly he is going to edit/copy/etc

**Comment by joachimmarder** [comment]
I am closing this issue for cleanup purposes. We should open more specific issues. Discussion is still possible within this issue.
