### ISSUE TITLE
VCL Themes and the Plus/Minus buttons

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#513]
Does anyone have a clue how to theme the Plus/Minus buttons (and hot versions) using VCL Themes? It seems to me that VCL Themes does not really support theming non standard controls. It certainly doesn't have any support for tree controls in the style designer. 

The bitmap style designer does allow you to add style objects, but you cannot name them (WTF!), so you are stuck with names like StyleObject1 etc. If you go down that route, you need to make sure that you create them in the same order in every theme, so that they get the same names! 

So, my current is solution is to add an OnPrepareButtonImages event. If this event is assigned, it will completely override the generation of the button images and allow you to load or paint then yourself.

I'm not particularly happy with this approach, as I'd need to then hook it up on every VT instance in my application, but at least I can make it look right.

I'm open to suggestions.

**Comment by joachimmarder** [comment]
We are struggling with this problem too just at the moment. Our first approach is: We already had our own derivation of TVirtualStringTree and made the properties PlusBM, MinusBM public and use DirectoryTree.PlusBM.LoadFromResourceName() in our presenter classes or TForm.OnShow events to assign new bitmaps. This approach shares shares the same advantage: We need to do this very every instance.
We will do some more research today if the buttons can be changed using the bitmap styles editor and a custom theme.

**Comment by joachimmarder** [comment]
It seems that, once a VCL theme is active, the VCL TTreeView control also falls back to the unthemed Windows expand / collapse buttons (from the Windows classic style) and does not use those included in the theme bitmaps. Did Embarcadero simply forget the expand / collapse buttons when they implemented the VCL styles?

**Comment by joachimmarder** [comment]
This code

```
StyleServices.GetElementSize(FPlusBM.Canvas.Handle, 
  StyleServices.GetElementDetails(tcbCategoryGlyphClosed), TElementSize.esActual, Size);
```

returns (0,0) if a VCL theme is active, and useful values like (9,9) if the Windows style is active. Seems like a bug in the VCL to me.

**Comment by vincentparrett** [comment]
"Did Embarcadero simply forget the expand / collapse buttons when they implemented the VCL styles?" 

Yep, looks like that to me. Notice how if you look at the bitmap style designer there is no mention of TreeView? I think I'm just going to go ahead and use the event I added, not perfect but it will work.

**Comment by vincentparrett** [comment]
Joachim, I just pushed my event addition to my pull request #511 - can you take a look at the pr and merge if it's ok?

**Comment by joachimmarder** [comment]
Hi Vincent.

This pull request consists of 35,381 additions and 38,424 deletions. It
would take some time if I perform a honest code review before accepting.
The commit for #513 in this pull request is small, but I guess I cannot
accept only this part of the pull request?

I will re-configure the Jenkins project for Virtual-Treeview later, at
least I want to have this running if larger pull requests are merged into
the master.

Best regards,

Joachim

2015-01-28 13:58 GMT+01:00 Vincent Parrett notifications@github.com:

**Comment by vincentparrett** [comment]
Yes it looks like a lot of changes but it isn't really, I mostly just moved code from VirtualTrees.pas to other units. I tried not to make any risky changes, my main aim was to reduce the size of VirtualTrees.pas. I'll set it up to build here on our CI server as well.. We can also update the status of a pr or branch based on the build status - see https://www.finalbuilder.com/resources/blogs/postid/700/building-github-pull-requests-with-continua-ci

**Comment by joachimmarder** [comment]
> We can also update the status of a pr or branch based on the build status

Interesting. But I have to set up a new CI project or re-configure an
existing one if I want to know if the automatic Merge builds succesfully -
right? This would be manual step and means some extra work if you mainain a
lot of projects and receive many PRs. It would be great if a PR could
trigger the CI build of the result of its automatic merge automatically.

2015-01-28 22:44 GMT+01:00 Vincent Parrett notifications@github.com:

**Comment by vincentparrett** [comment]
Pull requests can be treated like branches.. but you have to fetch them into your local copy to be able to build them. That's what I do in that article. I have DUnitX setup to build pull requests (and other branches) here and update the status of the pull request on gh. Have a look here at the open pr  - https://github.com/VSoftTechnologies/DUnitX/pulls - if you hover over the tick you will see its status.

**Comment by joachimmarder** [comment]
> Pull requests can be treated like branches.

Yes that is clear. The difference for me is that we typically have only 2
or 3 active branches: The stable/release branch, the development/unstable
branch, and in rare cases a 3rd one.

So we have set up 2 or 3 CI projects for these branches and do not have to
touch the CI config for quite a while.

Regarding pull requests: You typically have much more of them than we
currently have branches, and as far as I understood, one needs to touch the
CI config to fetch each pull request into a local copy?

By the way: What can you recommend to review a pull request? The GitHib
page? Or Atlassian SourceTree?

Best regards,

Joachim

2015-01-28 23:19 GMT+01:00 Vincent Parrett notifications@github.com:

**Comment by vincentparrett** [comment]
I just use github.. although that is not really an option with virtualtrees.pas due to it's size! 

For building pull requests, Continua CI as a property on the Git Repo, called "Fetch Other refs" which allows you to specify a refespec that will fetch the pull requests down to the local copy (ie the ci server's local clone). So I don't need to do anything special in my CI project/configuration to build pull requests. I don't use pull reqests to build my applications though, just compile the library and run unit tests.

**Comment by vincentparrett** [comment]
Closing as I closed the pull request and submitted another one that solves the line ending issue I was having.
