### ISSUE TITLE
The splitter area in the column header should be configurable

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#514]
Currently the size of the area in which a column can resized around the column separator is hard-coded in `TVTHeader.DetermineSplitterIndex()`. This size should be configurable through a property, it is e.g. way to small for touch optimized UIs. Suggested name for the new property: 

```
TVTHeader.SplitterArea: Integer default 8;
```

**Comment by vincentparrett** [comment]
I would go with SplitterWidth,  since that's what it really is, SplitterArea would imply to me that it affects width and height.

**Comment by joachimmarder** [comment]
I was thinking about the property name quite a while. I agree that "area" implies a width and height and so is not optimal. "SplitterWidth" implies for me the width of the splitter as it is displayed. Previous developers used "Tolerance"  for naming local variables or parameters.

Just in case it is not clear what I want to make configurable here: The area left and right of the column separator which is "sensitive" for column resizing. Any further ideas for the property name?

**Comment by vincentparrett** [comment]
Hmm.. perhaps something like SplitterTolerance or SplitterHitTolerance then.
