### ISSUE TITLE
Raising an exception upon the destruction of TBaseVirtualTree ( 5.5.3 ) with Delphi 7

### ISSUE THREAD

**Issue by zptcool** [JAM-Software/Virtual-TreeView#518]
When calling for the destruction of the TpsTree component ( TCustomVirtualStringTree ), we randomly get an access violation error. Even with the use of Eurekalog in order to  trace the problem  we are unable to fix the problem. Could you help us fixing this issue ?

EurekaLog 7.1.1.0  
## Exception:

  2.2 Address: 0040560D
  2.5 Type   : EAccessViolation
  2.6 Message: Violation d'accès à l'adresse 0040560D dans le module 'APPS.exe'. Lecture de l'adresse 1459B9D4.
  2.7 ID     : E3550000
  2.11 Sent  : 0
## |Methods |Details|Stack   |Address |Module        |Offset  |Unit                |Class                   |Procedure/Method                   |Line      |

|*Exception Thread: ID=3316; Parent=0; Priority=0                                                                                                       |
|Class=; Name=MAIN                                                                                                                                      |
|DeadLock=0; Wait Chain=                                                                                                                                |
|Comment=                                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|03     |00000000|0040560D|APPS.exe      |0000560D|System              |                        |_LStrToString                      |          |
|00000020|04     |0018FA14|004499D3|APPS.exe      |000499D3|Classes             |TComponent              |RemoveComponent                    |9837[3]   |
|00000020|04     |0018FA28|0044979C|APPS.exe      |0004979C|Classes             |TComponent              |Destroy                            |9758[9]   |
|00000020|04     |0018FA3C|0052C50B|APPS.exe      |0012C50B|Controls            |TControl                |Destroy                            |3242[15]  |
|00000020|03     |0018FA48|004047E2|APPS.exe      |000047E2|System              |                        |_ClassDestroy                      |          |
|00000020|04     |0018FA4C|004B68E2|APPS.exe      |000B68E2|Graphics            |TBrush                  |Destroy                            |1841[1]   |
|00000020|04     |0018FA78|00A10775|APPS.exe      |00610775|VirtualTrees        |TBaseVirtualTree        |Destroy                            |14352[43] |
|00000020|03     |0018FA8C|00A2FB70|APPS.exe      |0062FB70|VirtualTrees        |TCustomVirtualStringTree|Destroy                            |          |
|00000020|04     |0018FA9C|00A393A2|APPS.exe      |006393A2|psTree              |TpsTree                 |Destroy                            |1155[21]  |
|00000020|04     |0018FAB0|0052FB36|APPS.exe      |0012FB36|Controls            |TWinControl             |Destroy                            |5429[16]  |
|00000020|04     |0018FAC0|0054723C|APPS.exe      |0014723C|Forms               |TScrollingWinControl    |Destroy                            |2076[3]   |
|00000020|04     |0018FACC|00548237|APPS.exe      |00148237|Forms               |TCustomForm             |Destroy                            |2638[10]  |
|00000020|04     |0018FAE8|00DB6012|APPS.exe      |009B6012|UAbstractBaseForm   |TAbstractBaseForm       |Destroy                            |175[51]   |
|00000020|03     |0018FB20|004047E2|APPS.exe      |000047E2|System              |                        |_ClassDestroy                      |          |
|00000020|04     |0018FB24|0043F23F|APPS.exe      |0003F23F|Classes             |TList                   |Destroy                            |2747[1]   |
|00000020|03     |0018FB34|00404418|APPS.exe      |00004418|System              |TObject                 |Free                               |          |
|00000020|04     |0018FB38|0052BBC8|APPS.exe      |0012BBC8|Controls            |                        |ListRemove                         |2916[4]   |
|00000020|04     |0018FB4C|0052FB36|APPS.exe      |0012FB36|Controls            |TWinControl             |Destroy                            |5429[16]  |
|00000020|04     |0018FB5C|00535A59|APPS.exe      |00135A59|Controls            |TCustomControl          |Destroy                            |8901[2]   |
|00000020|04     |0018FB68|0052FB36|APPS.exe      |0012FB36|Controls            |TWinControl             |Destroy                            |5429[16]  |
|00000020|04     |0018FB94|0054723C|APPS.exe      |0014723C|Forms               |TScrollingWinControl    |Destroy                            |2076[3]   |
|00000020|04     |0018FBA0|00548237|APPS.exe      |00148237|Forms               |TCustomForm             |Destroy                            |2638[10]  |
|00000020|04     |0018FBBC|00DB6012|APPS.exe      |009B6012|UAbstractBaseForm   |TAbstractBaseForm       |Destroy                            |175[51]   |
|00000020|03     |0018FC20|00404418|APPS.exe      |00004418|System              |TObject                 |Free                               |          |
|00000020|04     |0018FC24|0054BEEF|APPS.exe      |0014BEEF|Forms               |TCustomForm             |CMRelease                          |4566[0]   |
|00000020|04     |0018FC28|0052E75C|APPS.exe      |0012E75C|Controls            |TControl                |WndProc                            |4645[53]  |
|00000020|04     |0018FD50|005317C7|APPS.exe      |001317C7|Controls            |TWinControl             |WndProc                            |6342[33]  |
|00000020|04     |0018FD70|0054916D|APPS.exe      |0014916D|Forms               |TCustomForm             |WndProc                            |3097[103] |
|00000020|04     |0018FD98|00531444|APPS.exe      |00131444|Controls            |TWinControl             |MainWndProc                        |6237[3]   |
|00000020|04     |0018FDAC|0053146E|APPS.exe      |0013146E|Controls            |TWinControl             |MainWndProc                        |6240[6]   |
|00000020|04     |0018FDC8|0044AF3C|APPS.exe      |0004AF3C|Classes             |                        |StdWndProc                         |10966[8]  |
|00000020|03     |0018FDE0|766762F7|user32.dll    |000162F7|user32              |                        | (possible gapfnScSendMessage+815) |          |
|00000020|03     |0018FE0C|76676D35|user32.dll    |00016D35|user32              |                        | (possible DefWindowProcW+672)     |          |
|00000020|03     |0018FE84|766777BF|user32.dll    |000177BF|user32              |                        | (possible DefWindowProcW+3370)    |          |
|00000020|03     |0018FEE4|76677BC5|user32.dll    |00017BC5|user32              |                        | (possible DefWindowProcW+4400)    |          |
|00000020|04     |0018FEF4|0054F866|APPS.exe      |0014F866|Forms               |TApplication            |ProcessMessage                     |6872[13]  |
|00000020|04     |0018FF0C|0054F89A|APPS.exe      |0014F89A|Forms               |TApplication            |HandleMessage                      |6891[1]   |
|00000020|04     |0018FF30|0054FABA|APPS.exe      |0014FABA|Forms               |TApplication            |Run                                |6975[16]  |
|00000020|04     |0018FF60|00DF48D5|APPS.exe      |009F48D5|APPS                |                        |Initialization                     |1445[31]  |
|00000020|03     |0018FF8C|74A43388|kernel32.dll  |00013388|kernel32            |                        |BaseThreadInitThunk                |          |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                       |
|Running Thread: ID=4484; Parent=3316; Priority=0                                                                                                       |
|Class=TMonitorClient; Name=[Unnamed thread] Kind: TThread. Thread function: OracleMonitor.TMonitorClient.Execute + $0. Thread caller: OracleMonitorIntf.TMonitorThread.Create (OracleMonitor.TMonitorClient.Execute)|
|DeadLock=0; Wait Chain=thread: [ 1184 / 4484 ] is blocked                                                                                              |
|Comment=                                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|03     |00000000|76FCF8D1|ntdll.dll     |0001F8D1|ntdll               |                        |ZwWaitForSingleObject              |          |
|00000020|03     |0774FE74|74A4118F|kernel32.dll  |0001118F|kernel32            |                        |WaitForSingleObjectEx              |          |
|00000020|03     |0774FE8C|74A41143|kernel32.dll  |00011143|kernel32            |                        |WaitForSingleObject                |          |
|00000020|03     |0774FEA0|00C97A92|APPS.exe      |00897A92|OracleMonitor       |TMonitorClient          |Execute                            |          |
|00000020|03     |0775F6C8|760E73A9|KERNELBASE.dll|000373A9|KERNELBASE          |                        | (possible IsNLSDefinedString+2183)|          |
|00000020|03     |0775F6CC|760C1D04|KERNELBASE.dll|00011D04|KERNELBASE          |                        | (possible GetModuleFileNameW+1130)|          |
|00000020|04     |0775FEE4|00417FB4|APPS.exe      |00017FB4|EMemLeaks           |                        |EurekaFreeMem                      |1645[82]  |
|00000020|04     |0775FEF8|00449174|APPS.exe      |00049174|Classes             |                        |ThreadProc                         |9372[7]   |
|00000020|04     |0775FF1C|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|04     |0775FF28|004954C9|APPS.exe      |000954C9|EThreadsManager     |                        |NakedBeginThreadWrapper            |1312[5]   |
|00000020|04     |0775FF38|0055BF48|APPS.exe      |0015BF48|EExceptionManager   |                        |DefaultThreadHandleException       |3566[6]   |
|00000020|04     |0775FF44|0055BF6E|APPS.exe      |0015BF6E|EExceptionManager   |                        |DefaultThreadHandleException       |3568[8]   |
|00000020|04     |0775FF5C|00495EC7|APPS.exe      |00095EC7|EThreadsManager     |                        |ThreadWrapperCT                    |1769[17]  |
|00000020|04     |0775FF74|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|03     |0775FF8C|74A43388|kernel32.dll  |00013388|kernel32            |                        |BaseThreadInitThunk                |          |
|7FFFFFFE|04     |00000000|00C96BED|APPS.exe      |00896BED|OracleMonitorIntf   |TMonitorThread          |Create                             |479[2]    |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                       |
|Running Thread: ID=4488; Parent=3316; Priority=0                                                                                                       |
|Class=TNotifiedTaskManager; Name=[Unnamed thread] Kind: TThread. Thread function: UNotifiedTaskManager.TNotifiedTaskManager.Execute. Thread caller: UNotifiedTaskManager.TNotifiedTaskManager.Create (UNotifiedTaskManager.TNotifiedTaskManager.Execute)|
|DeadLock=0; Wait Chain=thread: [ 1188 / 4488 ] is blocked                                                                                              |
|Comment=                                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|03     |00000000|76FCF8D1|ntdll.dll     |0001F8D1|ntdll               |                        |ZwWaitForSingleObject              |          |
|00000020|03     |0A61FE6C|74A4118F|kernel32.dll  |0001118F|kernel32            |                        |WaitForSingleObjectEx              |          |
|00000020|03     |0A61FE84|74A41143|kernel32.dll  |00011143|kernel32            |                        |WaitForSingleObject                |          |
|00000020|04     |0A61FE98|004494F4|APPS.exe      |000494F4|Classes             |TThread                 |Synchronize                        |9583[24]  |
|00000020|04     |0A61FEDC|00449588|APPS.exe      |00049588|Classes             |TThread                 |Synchronize                        |9608[4]   |
|00000020|04     |0A61FEE4|00D9A35C|APPS.exe      |0099A35C|UNotifiedTaskManager|TNotifiedTaskManager    |Execute                            |169[3]    |
|00000020|04     |0A61FEF0|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|04     |0A61FEF8|00449174|APPS.exe      |00049174|Classes             |                        |ThreadProc                         |9372[7]   |
|00000020|04     |0A61FF1C|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|04     |0A61FF28|004954C9|APPS.exe      |000954C9|EThreadsManager     |                        |NakedBeginThreadWrapper            |1312[5]   |
|00000020|04     |0A61FF38|0055BF48|APPS.exe      |0015BF48|EExceptionManager   |                        |DefaultThreadHandleException       |3566[6]   |
|00000020|04     |0A61FF44|0055BF6E|APPS.exe      |0015BF6E|EExceptionManager   |                        |DefaultThreadHandleException       |3568[8]   |
|00000020|04     |0A61FF5C|00495EC7|APPS.exe      |00095EC7|EThreadsManager     |                        |ThreadWrapperCT                    |1769[17]  |
|00000020|04     |0A61FF74|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|03     |0A61FF8C|74A43388|kernel32.dll  |00013388|kernel32            |                        |BaseThreadInitThunk                |          |
|7FFFFFFE|04     |00000000|00D9A2DB|APPS.exe      |0099A2DB|UNotifiedTaskManager|TNotifiedTaskManager    |Create                             |131[4]    |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                       |
|Running Thread: ID=4536; Parent=3316; Priority=0                                                                                                       |
|Class=TWorkerThread; Name=[Unnamed thread] Kind: TThread. Thread function: VirtualTrees.TWorkerThread.Execute. Thread caller: VirtualTrees.TWorkerThread.Create (VirtualTrees.TWorkerThread.Execute)|
|DeadLock=0; Wait Chain=thread: [ 11B8 / 4536 ] is blocked                                                                                              |
|Comment=                                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|03     |00000000|76FCF8D1|ntdll.dll     |0001F8D1|ntdll               |                        |ZwWaitForSingleObject              |          |
|00000020|03     |0688FEB0|74A4118F|kernel32.dll  |0001118F|kernel32            |                        |WaitForSingleObjectEx              |          |
|00000020|03     |0688FEC8|74A41143|kernel32.dll  |00011143|kernel32            |                        |WaitForSingleObject                |          |
|00000020|04     |0688FEDC|00A04573|APPS.exe      |00604573|VirtualTrees        |TWorkerThread           |Execute                            |6399[4]   |
|00000020|04     |0688FEE8|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|04     |0688FEF8|00449174|APPS.exe      |00049174|Classes             |                        |ThreadProc                         |9372[7]   |
|00000020|04     |0688FF1C|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|04     |0688FF28|004954C9|APPS.exe      |000954C9|EThreadsManager     |                        |NakedBeginThreadWrapper            |1312[5]   |
|00000020|04     |0688FF38|0055BF48|APPS.exe      |0015BF48|EExceptionManager   |                        |DefaultThreadHandleException       |3566[6]   |
|00000020|04     |0688FF44|0055BF6E|APPS.exe      |0015BF6E|EExceptionManager   |                        |DefaultThreadHandleException       |3568[8]   |
|00000020|04     |0688FF5C|00495EC7|APPS.exe      |00095EC7|EThreadsManager     |                        |ThreadWrapperCT                    |1769[17]  |
|00000020|04     |0688FF74|004954A5|APPS.exe      |000954A5|EThreadsManager     |                        |ThreadDataUnlock                   |1297[2]   |
|00000020|03     |0688FF8C|74A43388|kernel32.dll  |00013388|kernel32            |                        |BaseThreadInitThunk                |          |
## Assembler Information:

; Base Address: $405000, Allocation Base: $400000, Region Size: 10420224
; Allocation Protect: PAGE_EXECUTE_WRITECOPY, Protect: PAGE_EXECUTE_READ
; State: MEM_COMMIT, Type: MEM_IMAGE
; 
;
; System._LStrFromWArray (Line=0 - Offset=18)
; -------------------------------------------
004055EA  5F          POP  EDI
004055EB  E9ACFEFFFF  JMP  -$0154       ; ($0040549C) System._LStrFromPWCharLen
004055F0  C3          RET
004055F1  8D4000      LEA  EAX, [EAX]
004055F4  31C9        XOR  ECX, ECX
004055F6  85D2        TEST EDX, EDX
004055F8  7405        JZ   +5           ; ($004055FF->0040549C) System._LStrFromPWCharLen
004055FA  8B4AFC      MOV  ECX, [EDX-4]
004055FD  D1E9        SHR  ECX, 1
004055FF  E998FEFFFF  JMP  -$0168       ; ($0040549C) System._LStrFromPWCharLen
00405604  C3          RET
00405605  8D4000      LEA  EAX, [EAX]
00405608  53          PUSH EBX
00405609  85D2        TEST EDX, EDX
0040560B  7418        JZ   +$18         ; ($00405625) System._LStrToString (Line=0)
;
; System._LStrToString (Line=0 - Offset=5)
; ----------------------------------------
0040560D  8B5AFC      MOV  EBX, [EDX-4]  ; <-- EXCEPTION
00405610  85DB        TEST EBX, EBX
00405612  7411        JZ   +$11         ; ($00405625) System._LStrToString (Line=0)
00405614  39D9        CMP  ECX, EBX
00405616  7C02        JL   +2           ; ($0040561A) System._LStrToString (Line=0)
00405618  89D9        MOV  ECX, EBX
0040561A  8808        MOV  [EAX], CL
0040561C  40          INC  EAX
0040561D  92          XCHG EAX, EDX
0040561E  E811D9FFFF  CALL -$26EF       ; ($00402F34) System.Move
00405623  5B          POP  EBX

**Comment by joachimmarder** [comment]
The call stack includes at line 14352 in TBaseVirtualTree.Destroy() which does not match V5.5.3.

I don't think we will be able to help unless you can provide a reliable repro that also works in a newer version of Delphi.

**Comment by zptcool** [comment]
Thanks for reply, i changed the line 14311 because Foptions = nil

destructor TBaseVirtualTree.Destroy;

begin
  InterruptValidation();
  // 22/01/15 : Correction bug
  if Assigned(FOptions) then
  Exclude(FOptions.FMiscOptions, toReadOnly);
  ReleaseThreadReference(Self);
  StopWheelPanning;
  CancelEditNode;

  // Just in case it didn't happen already release the edit link.
  FEditLink := nil;
  FClipboardFormats.Free;
  // Clear will also free the drag manager if it is still alive.
  Clear;
  FDragImage.Free;
  FColors.Free;
  FBackground.Free;
  FImageChangeLink.Free;
  FStateChangeLink.Free;
  FCustomCheckChangeLink.Free;
  FScrollBarOptions.Free;

  // The window handle must be destroyed before the header is freed because it is needed in WM_NCDESTROY.
  if HandleAllocated then
    DestroyWindowHandle;

  // Release FDottedBrush in case WM_NCDESTROY hasn't been triggered.
  if FDottedBrush <> 0 then
    DeleteObject(FDottedBrush);
  FDottedBrush := 0;

  FHeader.Free;
  FHeader := nil; // Do not use FreeAndNil() before checking issue #497

  FreeAndNil(FOptions); // WM_NCDESTROY accesses FOptions

  FreeMem(FRoot);

  FPlusBM.Free;
  FHotPlusBM.Free;
  FMinusBM.Free;
  FHotMinusBM.Free;

  inherited;
end;

**Comment by joachimmarder** [comment]
That would point us to the line "inherited;". This call won't help to track down the issue, and I don't think it is within V5.5.3, otherwise we would have had similar reports.

What we need is a sample project which allows us to replicate the problem in Delphi XE2 or higher. Alternatively you may analyze the problem and send suggestions for a patch.
