### ISSUE TITLE
Plus/Minus buttons - hot painting option?

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#519]
The Plus/Minus buttons only hot track if PaintOptions toHotTrack is true. At the moment it's an all or nothing scenario, ie either hot track everything or nothing. I think this should either be a separate option (toHotTrackButtons) or should always be true.  

Thoughts?

**Comment by joachimmarder** [comment]
On one hand there is no immediate connection between both and so it could make sense to separate them. On the other hand Virtual TreeView already has so many options that it is hard for users to find the correct one and to maintain the existing in all scenarios. This is why I am always a bit reluctant to add new options.

**Comment by vincentparrett** [comment]
I'm for making it always on, I'm not sure why anyone would turn it off. I agree there are too many options, especially around themes etc. Working out how they all interact is a challenge.

**Comment by joachimmarder** [comment]
> I'm for making it always on, I'm not sure why anyone would turn it off.

Those people could assign the normal bitmap to the hot bitmap (using you new event) to turn off the effect.

**Comment by vincentparrett** [comment]
Yes,the way It's coded at the moment the hot bitmaps usually default to the non hot versions anyway. Will submit a pull request today. Also, VT doesn't have a notion of hot and selected on the plus/minus buttons. I added 2 more bitmaps and some logic for this. I will add them to the event, I know we don't like to change event sigs, but it's a new event, I doubt many (other than myself) are using it yet

**Comment by joachimmarder** [comment]
> I know we don't like to change event sigs, but it's a new event

+1. As long as there was no official release, I don't see any problem in changing event sigs, V6 is work in progress.
