### ISSUE TITLE
Plus/Minus buttons - hot painting not correct.

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#520]
When hot tracking is enabled, hot painting of the plus minus buttons does not seem quite right. The Hit test area for deciding to hot paint the button should be the same as it is when clicking on the button. At the moment, that's not the case. In TBaseVirtualTree.HandleHotTrack

``` delphi
ButtonIsHit := (hiOnItemButtonExact in HitInfo.HitPositions) and (toHotTrack in FOptions.FPaintOptions);
```

This line makes it only invalidate the node if the mouse is exactly over the button. 

The positioning of the hot tracking is off even for hiOnItemButtonExact, this video shows what happens - https://drive.google.com/file/d/0B4sAoc6VBf0PZ3R3Q2d2aTRzVUU/view?usp=sharing 

Notice the mouse is half way through the button before the button is hot. The red rectangles are the outline of the button bitmap (9x9).  

A work around for me is to change the ButtonIsHit test to 

``` delphi
ButtonIsHit := ((hiOnItemButtonExact in HitInfo.HitPositions) or (hiOnItemButton in HitInfo.HitPositions))
                 and (toHotTrack in FOptions.FPaintOptions);
```

But I suspect this may have consequences. The real fix would probably be figure out what is wrong with the hit testings in the first place.

**Comment by joachimmarder** [comment]
> The real fix would probably be figure out what is wrong with the hit testings in the first place. 

+1. 
I guess the reason is a wrong calculation of the left margin, issue #369 targets similar problems. The code for the left margin calculation often duplicated / copied in the code.

**Comment by joachimmarder** [comment]
@vincentparrett: Do you use a VCL theme that has a hot expand button?
Do you have set the `toUseExplorerTheme`?

There is code in `HandleHotTrack()` that does hot tracking for expand/collapse buttons only in case `toUseExplorerTheme` is set.
