### ISSUE TITLE
License misconception

### ISSUE THREAD

**Issue by ghost** [JAM-Software/Virtual-TreeView#522]
The official website at http://www.jam-software.de/virtual-treeview/ and the CHM help in the source says that the code is under the LGPL ("GNU Lesser General Public License") but the readme at the GitHub website (https://github.com/Virtual-TreeView/Virtual-TreeView/blob/master/README.md) says "GPL 2.0". Is this a mistake or does the license has changed to the more restrictive GPL license?

**Comment by joachimmarder** [comment]
Not sure how this happened, it is corrected now.
