### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by mauxion2** [JAM-Software/Virtual-TreeView#525]
![virtualtreeerror](https://cloud.githubusercontent.com/assets/11186464/6364055/61552bde-bca1-11e4-8d7e-08b42a2e1965.jpg)

VirtualTreesCR.bpl installs without errors on Embarcadero XE7 but VirtualTreesCD.bpl rises this exeption.
Compilation of both bpl's completes succesfuly.

**Comment by romankassebaum** [comment]
I made the CBuilder packages compilable and changed the 'R' package to a runtime package (which was definitely) a bug.
Can you please try to install the designtime package again?

**Comment by mauxion2** [comment]
Tanks is works
