### ISSUE TITLE
removing toFullRepaintOnResize and toAcceptOleDrop in MiscOptions result in leaking TVTDragManager

### ISSUE THREAD

**Issue by Memnarch** [JAM-Software/Virtual-TreeView#527]
when toFullRepaintOnResize and toAcceptOLEDrop are removed from MiscOptions, TVTDragManager leaks.

The problem:
changes made to toFullRepaintOnResize trigger a RecreateWND. This triggers WMNCDestroy.
WMNCDestroy is supposed to unregister from OleDragDrop. However in this special case it does not, because of:
if not (csDesigning in ComponentState) and (toAcceptOLEDrop in FOptions.FMiscOptions) then
    RevokeDragDrop(Handle);

FMiscOptions is checked if it includes toAcceptOleDrop, however at this point, this flag is already removed. So it won't unregister and the DragManager is still registered within the Windows-Sybsystem keeping RefCount >= 1

The Problem is SetMiscOptions. The first thing it does(before triggering anything) is
FMiscOptions := Value

AFAIK, this needs to be moved to the last line of the Setter

**Comment by joachimmarder** [comment]
Does this only occur if you do these changes at runtime, or also if you set these properties at designtime and then run the project?

Can you attach a sample project? (e.g. a modified Advanced sample project)

I improved the code order in the master (V6.0), but I am unable to quickly verify if it solves the problem.

**Comment by Memnarch** [comment]
As far as i can see it occurs at runtime.
(No Delphi here so i'll write the significant source to reproduce):
New Project, Place a TreeView, Place a Button, within Button.OnClick do the following:

MyTreeView.TreeOptions.MiscOptions := MyTreeView.TreeOptions.MiscOptions - [toAcceptOldeDrop, toFullRepaintOnResize]

For leak reporting i use the BorlandMM-Replacement DLL of FastMM4 (so project needs Sharemem as first uses). Do not use the precompiled BorlandMM.dll of FastMM4 as the leak Dialog will mostly show "Unknown" as classname, otherwhise.

SImply start the Program, Press the button, and close it. The Dialog should show(for the older Version) that one TVTDragManager is leaking.

**Comment by Memnarch** [comment]
~~I don't think your line fixes it. Before recreating the Handle it seems to be ALWAYS required to revoke DragAndDrop. Case for the listed commit:
Keep toAcceptOleDrop, but change(add or remove) toFullRepaintOnResize. In this case DragAndDrop is not revoked but the handle is recreated(which means we can't revoke it at a later time). That's why i modified the WMNCDestroy method.~~
Edit: Nevermind, in the case i wrote, WMNCDestroy revokes DragDrop so everything is fine

PS: I'll attach a sample project tommorrow at work

**Comment by joachimmarder** [comment]
>  in the case i wrote, WMNCDestroy revokes DragDrop so everything is fine

So can we consider this issue as fixed?

**Comment by Memnarch** [comment]
I hope so, a TestProject to verify is attached. 
Recompile and butt both dlls into the same folder as the compiled exe
Start->Press Button1->Exit (Leak)
Start->Press Button2->Exit (might leak)

IDE needs to run, otherwhise the LeakDialog is not displayed(and only a txt is created)

PS: it doesn't allow me to attach anything but picturefiles, so i renamed the zip file!
![treeviewleaktest zip](https://cloud.githubusercontent.com/assets/1398184/6620966/2051694c-c8d4-11e4-9217-8bb2722ce566.png)

**Comment by joachimmarder** [comment]
Why did you add the unit ShareMem to the DPR? It seems to prevent Delphi's leak reporting.

Anyway, I did not get any leak reports with this sample project using the latest source code. So I consider this issue fixed.

**Comment by Memnarch** [comment]
The BolandMM ist a replacement DLL from Delphi from FastMM4 inclduing the FastMM4 MemoryManager with extended DebugFunctionality ;).
LeakReporting is handled entirely by FastMM4
