### ISSUE TITLE
problem refresh selected

### ISSUE THREAD

**Issue by mauxion2** [JAM-Software/Virtual-TreeView#528]
![image](https://cloud.githubusercontent.com/assets/11186464/6740584/663705c2-ce81-11e4-83d2-19f1dad23a63.jpg)
Code " 
void __fastcall Tform::TreeDeselect(void)
{
    TVirtualNode\* node = TreeView->GetFirst();
    while (node != NULL)
    {
     TTreeDataN\* const dataN = static_cast<TTreeDataN*>(TreeView->GetNodeData(node));
           dataN->FImage = 11;
      TreeView->InvalidateNode(node);
      node = TreeView->GetNext(node);
    }
}
void __fastcall Tform::TreeViewKeyDown(TObject *Sender, WORD &Key, TShiftState Shift)
{
      TreeDeselect(); // deselect all nodes and reset default image = 11

```
TVirtualNode* node = TreeView->FocusedNode;
    TTreeDataN* const dataN = static_cast<TTreeDataN*>(TreeView->GetNodeData(node));
dataN->FImage = 0;
TreeView->InvalidateNode(node);
```

}
" end code
Focus lags 1 position behind selection when navigating tree with keyboard

**Comment by joachimmarder** [comment]
Are you using V5.5 or V6?
If V6, which revision?
Can this behavior be reproduced with one of the included sample projects?

**Comment by mauxion2** [comment]
I'm using v6 last downloads in day 19-03-2015.
I have not checked dis in samples , I'm using component in Embarcadero XE7, I write application in C++.

**Comment by joachimmarder** [comment]
You need to use the KeyUp event.
