### ISSUE TITLE
Request to add code to component

### ISSUE THREAD

**Issue by mauxion2** [JAM-Software/Virtual-TreeView#529]
public
       function GetNodeByIndex (index: Cardinal): PVirtualNode;

//-----------------------------------------------------------------------------------
function TBaseVirtualTree.GetNodebyIndex(index:Cardinal): PVirtualNode;
var
   tmpNode: PVirtualNode;
begin
  Result := nil;
  tmpNode := GetFirst;
  while Assigned(tmpNode) do
    begin
      if AbsoluteIndex(tmpNode) = index then
        begin
          Result := tmpNode;
          break;
        end;
      tmpNode := GetNext(tmpNode);
    end;
end;

return node from AbsoluteIndex

**Comment by joachimmarder** [comment]
May I ask why you need that?

It contradicts a little with the virtual pradigma. Furthermore the abolute index of a node is highly volatile. And this function as it is implemented here has a complexity of O(n^2), because AbsoluteIndex() also contains a loop over the nodes.

**Comment by mauxion2** [comment]
VirtualTree I use to visualize the structure of the file.
I modify Nodes without user intervention, handy to be such functionality.

**Comment by joachimmarder** [comment]
What about the other things I wrote?
Why do you store/use the index and not PVirtualNode?

**Comment by mauxion2** [comment]
So how select node without clicking or ANY OTHER USER INTERVENTION ?

**Comment by joachimmarder** [comment]
> So how select node without clicking

Please note that this is not a support forum. Usually you get good support from the community e.g. at StackOverflow.com.
