### ISSUE TITLE
Breaking change of DeleteNode behavior

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [JAM-Software/Virtual-TreeView#533]
Change introduced in 0859575f1a8a4a64b146671c4880364a5d9d758a breaks DeleteNode behavior - it doesn't reindex anymore so all code relying on Node.Index becomes invalid after a single node deletion.

**Comment by joachimmarder** [comment]
Sorry, stupid mistake, I got the old default parameter of DeleteNode() wrong.
