### ISSUE TITLE
Add export event that is triggered for each cell

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#536]
Proposed signature:

TVTCellExportEvent   = procedure(Sender: TBaseVirtualTree; ExportType: TVTExportType; Node: PVirtualNode; Column: TVirtualTreeColumn; var Text: string): Boolean of object;

Should be called before writing the text of the cell. The parameter Text will contain the text returned by GetText().

**Comment by romankassebaum** [comment]
I've a question: Would it make sense to work with anonymous methods instead of the old events?

**Comment by joachimmarder** [comment]
You don't have design time support for anonymous methods like you have them for good old events.

However, you can [use anonymous methods as event handler using some small helper classes](http://stackoverflow.com/questions/8025481/vcl-events-with-anonymous-methods-what-do-you-think-about-this-implementation).

**Comment by romankassebaum** [comment]
Thanks for the link. I like Stefan's solution. :-)

**Comment by joachimmarder** [comment]
I think I will merge the proposed event and the OnPaintText event in a new event, as they have much in common. I will start using an EventArgs record like it is common in .Net.
