### ISSUE TITLE
Simple enhancement request: Execute Loaded method at runtime

### ISSUE THREAD

**Issue by iankrigsman** [JAM-Software/Virtual-TreeView#539]
I have had need to instantiate a VT at runtime. In doing so, the Loaded method does not get called. Rather than surface TBaseVirtualTree.Loaded to public, I have created a DoLoaded method. (This is based on other recommendations, although making Loaded public might be the preferred option).

Example:

```
  TBaseVirtualTree = class(TCustomControl)
...
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
    procedure DoLoaded;  // << INSERT
...
procedure TBaseVirtualTree.DoLoaded; // << INSERT METHOD
begin
  Loaded;
end;
```

**Comment by joachimmarder** [comment]
> I have had need to instantiate a VT at runtime. In doing so, the Loaded method does not get called. 

This is by design and common for all VCL controls. On which code in Loaded() do you rely? In my opinion the correct solution for a problem like this is to ensure that code is executed when needed. Not to expose protected methods so that they can be called as a workaround.

Did you use V5.5 or V6.0?

**Comment by iankrigsman** [comment]
Thanks for your response.

> Did you use V5.5 or V6.0?

I git cloned it, so I have the latest I believe. CHANGES.txt starts with:
V6.0 (beta, scheduled for release on 10 Apr 2015)

More explanation...
TBaseVirtualTree.Loaded is called after the dfm is streamed. This includes several important initialization code such as VclStyleChanged...

If I create a VT in code...

```
fMyVT := TVirtualStringTree.Create(Self);
fMyVT.Parent := Panel1;
etc.
```

the Loaded procedure will _not_ be called and the resulting behaviour incomplete. (Eg. styling not done)

> On which code in Loaded() do you rely?

All of it...? Certainly the call to VclStyleChanged and probably the RegisterDragDrop() part. Setting child counts, etc. might only be relevant if it only applies to design time items streamed in.

> In my opinion the correct solution for a problem like this is to ensure that code is executed when needed.

I'm no expert in component writing so open to advice on how I can execute the Loaded() code by some other means. Is the problem solved by moving those particular initialization parts to something like AfterConstruction? At the very least, VclStyleChanged should not be dependent on design time creation. I think you're right that I shouldn't need to expose protected methods and would prefer not to take any additional action at all.

This describes my problem well...
http://stackoverflow.com/questions/9439279/alternative-to-calling-the-loaded-method-explicitly-for-dynamically-created-inst

also...
http://stackoverflow.com/questions/12251431/why-loaded-method-is-ignored

cheers

## 

Ian

**Comment by joachimmarder** [comment]
> This describes my problem well...

Yes, and the answer is quite clear: "If you need to call Loaded in your code you're doing it wrong."
I fully agree.

> TBaseVirtualTree.Loaded is called after the dfm is streamed. 
> This includes several important initialization code

This is correct, but most of the code is executed elsewhere even if Loaded() is not called, e.g. in CreateWnd() or the property setters. An example is RegisterDragDrop()

> initialization code such as VclStyleChanged

Yes, I guess we need to move this call to the constructor.

**Comment by iankrigsman** [comment]
> > initialization code such as VclStyleChanged
> > Yes, I guess we need to move this call to the constructor.

From memory (it was a while ago), this was the main issue for me. :-)

**Comment by iankrigsman** [comment]
Thanks Joachim, I'll update my copy and check it out.
