### ISSUE TITLE
Duplicate call of EndEdit()

### ISSUE THREAD

**Issue by greengl** [JAM-Software/Virtual-TreeView#541]
if in demos "Demos\Advanced"
in file "Editors.pas"
change method TPropertyEditLink.EndEdit:

function TPropertyEditLink.EndEdit: Boolean;

var
  Data: PPropertyData;
  Buffer: array[0..1024] of Char;
  S: UnicodeString;

begin
  Result := True;

  Data := FTree.GetNodeData(FNode);
  if FEdit is TComboBox then
    S := TComboBox(FEdit).Text
  else
  begin
    GetWindowText(FEdit.Handle, Buffer, 1024);
    S := Buffer;
  end;

  //Added this:
  if S='q' then
  begin
    Result:=false;
    ShowMessage('Don''t Enter "q"!');
    FEdit.SetFocus;
    exit;
  end;

  if S <> Data.Value then
  begin
    Data.Value := S;
    Data.Changed := True;
    FTree.InvalidateNode(FNode);
  end;
  FEdit.Hide;
  FTree.SetFocus;
end;

then afte execute project and select "Property tree simulation" 
start edit property of Node and set value as "q"
click mouse on other node.
In result two message "Don't Enter "q"" was showed .

My variant of solution:
Change 
procedure TBaseVirtualTree.HandleMouseDown(var Message: TWMMouse; var HitInfo: THitInfo);

instead of 

  if (tsEditing in FStates) then
    DoEndEdit;

use

  if (tsEditing in FStates) then
    if not DoEndEdit then
       exit;

**Comment by joachimmarder** [comment]
I tried your repro steps with Delphi XE8 and the latest VT source but was unable to replicate the duplicate message. Which version of Virtual Treeview did you use?

**Comment by greengl** [comment]
Windows 8 (x64), Windows XP(32)
Delphi XE5
Tried version:
V5.5.3: (08 Jan 2015)
V6.0 (unstable)
V6.0 (official release)
Double message only mouse click on another node (but when click on focused node, one message showed).
When press up/down arrow buttons double message too.

**Comment by greengl** [comment]
Also replace:
TBaseVirtualTree.WMKeyDown

VK_UP:
            begin
              // scrolling without selection change
              if ssCtrl in Shift then
                SetOffsetY(FOffsetY + Integer(FDefaultNodeHeight))
              else
              begin
                if FFocusedNode = nil then
                  Node := GetLastVisible(nil, True)
                else
                  Node := GetPreviousVisible(FFocusedNode, True);

```
            if Assigned(Node) then
            begin
              if not EndEditNode then //Also replace
                exit;
              if HandleMultiSelect and (CompareNodePositions(LastFocused, FRangeAnchor) > 0) and
                Assigned(FFocusedNode) then
                RemoveFromSelection(FFocusedNode);
              if FFocusedColumn <= NoColumn then
                FFocusedColumn := FHeader.MainColumn;
              FocusedNode := Node;
            end
            else
              if Assigned(FFocusedNode) then
                InvalidateNode(FFocusedNode);
          end;
        end;
```

**Comment by joachimmarder** [comment]
Done
