### ISSUE TITLE
AllocateInternalDataArea seriously broken

### ISSUE THREAD

**Issue by ralfjunker** [JAM-Software/Virtual-TreeView#542]
39cffd8d4955a858b25ad6786bfbc620773c3246 seriously breaks TBaseVirtualTree.AllocateInternalDataArea.

By turning it into a class function, alongside with FTotalInternalDataSize becomming a class variable, totally independent trees may change each others FTotalInternalDataSize unpredictably.

Also, by removing the addition of existing FTotalInternalDataSizes values already summed up from base classes, there is now just one FTotalInternalDataSize value for all classes.

Before the change, each instance maintained its own FTotalInternalDataSize. With the change, there is just a single FTotalInternalDataSize for all TBaseVirtualTree descendants. Which, because all classes descend from TBaseVirtualTree, in fact means all trees.

In a worst-case scenario, a tree with millions of small nodes may run out of memory because another tree with few nodes increases FTotalInternalDataSize just slightly.

**Comment by joachimmarder** [comment]
After revisiting the code I now better understand the mechanism behind AllocateInternalDataArea(), I did not realize the fact that this method was intended to be called by descendant classes. I'm sorry for this broken feature.

 I still think it makes sense to have the user node data at a fix offset, which allows to access the user node data in a simpler and clearer way, as it is done in the new member functions of the TVirtualNode record.

So I would like to propose to place the internal data after the user data. As long as the InternalData/() function is used to access the internal data, this should not be a breaking change.
