### ISSUE TITLE
toShowStaticText not rendered correctly

### ISSUE THREAD

**Issue by 7even11** [JAM-Software/Virtual-TreeView#546]
A bug with RepaintNode:

toShowStaticText must be enabled.

1) Set initial state - font - non-bold, StaticText = empty

2) change state - font - bold, StaticText = some text - do RepaintNode() to refresh it

3) After RepaintNode, node does not take Bold into calculation, if it would not be Bold, it would be OK

4) after clicking away and clicking back to node it is correctly repainted.

![vstbug1](https://cloud.githubusercontent.com/assets/2266850/7456195/da3119b6-f282-11e4-93fa-0c878d1b2687.png)

**Comment by joachimmarder** [comment]
Which version of Virtual Treeview do you use?

A repro for one of the included sample projects would be appreciated.

**Comment by joachimmarder** [comment]
The sample project "Advanced" contains a very similar tree on the page "General abilities and features". It does not show this behavior. How do I need to modify this project so that the behavior appears?

**Comment by 7even11** [comment]
1. Create new project
2. Add **VirtualStringTree** and **Button** on the form
3. Use the code below

**Note:** It behaves differently when node is selected and when it is not selected. The problem manifests when node is selected and does not when it is not selected. You can try commenting and uncommenting the line...

``` delphi
VirtualStringTree1.Selected[Node] := True;
```

...in the **TForm1.Button1Click** procedure to see the difference. Tested with **V5.5.3** because I don't have the ability to use 6.0 because I use D2010.

For a start, leave the line as it is and test like that. To see the difference, comment the line (then it should repaint as it is supposed to). So, in other words, while the line is uncommented (the node is selected) the redraw is incorrect.

To test the issue, simply click **repeatedly**  Button1.

The code:

``` delphi
unit Unit1;
interface
uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, VirtualTrees, StdCtrls;

type
  TForm1 = class(TForm)
    VirtualStringTree1: TVirtualStringTree;
    Button1: TButton;
    procedure Button1Click(Sender: TObject);
    procedure FormCreate(Sender: TObject);
    procedure VirtualStringTree1GetText(Sender: TBaseVirtualTree;
      Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType;
      var CellText: string);
    procedure VirtualStringTree1PaintText(Sender: TBaseVirtualTree;
      const TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
      TextType: TVSTTextType);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation
{$R *.dfm}

type
  PTreeData = ^TTreeData;
  TTreeData = record
    MainTxt:   String;
    StaticTxt: String;
    OnOff:     Integer;
  end;

procedure TForm1.FormCreate(Sender: TObject);
var
  Node: PVirtualNode;
  Data: PTreeData;
begin
  VirtualStringTree1.NodeDataSize              := SizeOf(TTreeData);
  VirtualStringTree1.TreeOptions.StringOptions := VirtualStringTree1.TreeOptions.StringOptions + [toShowStaticText];

  Node           := VirtualStringTree1.AddChild(nil);
  Data           := VirtualStringTree1.GetNodeData(Node);
  Data.MainTxt   := 'Sample Text';
  Data.StaticTxt := '(1234)';
end;

procedure TForm1.VirtualStringTree1GetText(Sender: TBaseVirtualTree;
  Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType;
  var CellText: string);
var
  Data: PTreeData;
begin
  Data := Sender.GetNodeData(Node);
  case TextType of
    ttNormal: CellText := Data^.MainTxt;
    ttStatic: CellText := Data^.StaticTxt;
  end;
end;

procedure TForm1.VirtualStringTree1PaintText(Sender: TBaseVirtualTree;
  const TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
  TextType: TVSTTextType);
var
  Data: PTreeData;
begin
  Data := Sender.GetNodeData(Node);
  case TextType of
    ttNormal:   if Data.OnOff mod 2 = 0 then
                  TargetCanvas.Font.Style := TargetCanvas.Font.Style + [fsBold]
                else
                  TargetCanvas.Font.Style := TargetCanvas.Font.Style - [fsBold];
    ttStatic: TargetCanvas.Font.Color := clBlue;
  end;
end;

procedure TForm1.Button1Click(Sender: TObject);
var
  Node: PVirtualNode;
  Data: PTreeData;
begin
  Node := VirtualStringTree1.GetFirst;
  Data := VirtualStringTree1.GetNodeData(Node);

  VirtualStringTree1.Selected[Node] := True;

  if Data.OnOff = 0
  then
    Data.OnOff := 1
  else
    Data.OnOff := 0;

  VirtualStringTree1.RepaintNode(Node);
end;

end.
```

**Comment by sanjayssk** [comment]
Hi Joachim,

Facing severe internet outage today. Hope to connect properly by evening.
Sending this through mobile network.

Regards,
Sanjay

**Comment by joachimmarder** [comment]
No problem. None of this stuff is urgent, as the issue submission dates may
indicate. Can you give me a rough estimate how many hours you have worked
so far?

You may address these issues when it is convenient for you, in exchange for
a reduced rate.

Best regards,

Joachim


2016-07-14 8:33 GMT+02:00 sanjayssk <notifications@github.com>:

**Comment by sanjayssk** [comment]
I think, it's incorrect to call RepaintNode. One should call InvalidateNode instead. Then it works without any problem.
