### ISSUE TITLE
VCL Themes: Drawing issue with toCheckSupport an toExtendedFocus

### ISSUE THREAD

**Issue by Delphichem** [JAM-Software/Virtual-TreeView#549]
Hi,
when I set toCheckSupport, toGridExtensions, toShowHorzGridLines, toShowVertGridLines, toExtendedFocus and toFullRowSelect, selection still visible on all the columns.
![vtv issue](https://cloud.githubusercontent.com/assets/12384176/7555792/81917af0-f74e-11e4-95e5-1eb696054420.png)

Delphi XE8, Windows 7 64 bits, Virtualtree 6.0

**Comment by joachimmarder** [comment]
Are you using a VCL theme?
If so, does this problem also occur with the default Windows theme?

**Comment by Delphichem** [comment]
Yes, I use VCL theme.
No, it does'nt occur with the default widows theme and it doesn't occur on VCL theme with uncheked toCheckSupport.

**Comment by joachimmarder** [comment]
Could you please check if the problem is still there in V6.2?

**Comment by Delphichem** [comment]
Tested, same with V6.2
