### ISSUE TITLE
"Ghosted" state cannot be applied to a treenode and its overlay separately

### ISSUE THREAD

**Issue by SaschaSchaefer** [JAM-Software/Virtual-TreeView#551]
I want to use TVirtualStringTree.GetImageIndexEx(Sender: TBaseVirtualTree; Node: PVirtualNode; Kind: TVTImageKind; Column: TColumnIndex; var Ghosted: Boolean; var ImageIndex: Integer; var ImageList: TCustomImageList); to add an overlay to a tree node as shown here:
![clipboard02](https://cloud.githubusercontent.com/assets/11809274/7956093/ee224662-09dd-11e5-8072-4bf708cfad0b.png)

My goal is to have the directory icon grayed out, but not the overlay (the warning symbol).
The following scenario, however will either gray out both, or none:

What I tried to do was to check the "Kind" parameter in the GetImageIndexEx-Event and use a different image for ikOverlay and the other cases. To have an item grayed out, I set the Ghosted var:
If Kind = ikOverlay then I set Ghosted := false. In all other cases I set Ghosted := true.

The result, however, shows both the node itself and the overlay in a Ghosted state: ![clipboard](https://cloud.githubusercontent.com/assets/11809274/7956151/50ae1112-09de-11e5-80e9-6e4d4157c014.png) It doesn't seem to be possible to set either individually.

**Comment by joachimmarder** [comment]
Overlay images with an index <= 15 are not drawn ghosted, those with an index > 15 are drawn ghosted. I am going to unify this behavior to that of the Windows Explorer, which does not draw overlay images ghosted.
