### ISSUE TITLE
Why not  V6.0 support the old Delphi version?

### ISSUE THREAD

**Issue by mksjgj** [JAM-Software/Virtual-TreeView#552]
Hi, as you know, VirtualTreeView is an OLD, Native Windows Control, many developers had used it in their native windows program, like me.  most of them are stayed in Delphi 7 - XE. 

so we  want to know, why your new version don't support them? Is it a matter of workload or technic? can you give me some suggest for maintaining  a XE supported version which   base on you vew version?

**Comment by joachimmarder** [comment]
This was discussed in issue #503
