### ISSUE TITLE
painting failure with variable NodeHeight

### ISSUE THREAD

**Issue by landrix** [JAM-Software/Virtual-TreeView#553]
i use a treeview with variable NodeHeight

selected Node Height 50
unselected Node Height 18

procedure TForm.vstMeasureItem(Sender: TBaseVirtualTree;
  TargetCanvas: TCanvas; Node: PVirtualNode; var NodeHeight: Integer);
begin
  NodeHeight := vst.DefaultNodeHeight;
  if Node = nil then
    exit;
  if Sender.Selected[Node] then
    NodeHeight := 50
end;

when i select a node with mouse cursor, all works fine

when i select a node with keyboard up and down, the nodeheight isn't computed correct
all selected nodes become height 50 and switch not back

**Comment by joachimmarder** [comment]
Which version of Virtual Treeview are you using?

I'm not sure if this approach is a good idea: I think the original implementation allowed each node to have an individual height, but assumes that this is constant after calling OnMeasureItem, becuase it is cached internally.

**Comment by landrix** [comment]
i use the current version from master

**Comment by joachimmarder** [comment]
I was able to fix this issue, the previously selected node was removed from the selection later when using the keyboard, compare to the mouse- this is why the if-condition failed. I'm still not sure if the implementation is designed for heavily changing node heights.
