### ISSUE TITLE
Virtual String Tree PrepareBitmaps under high DPI

### ISSUE THREAD

**Issue by Matterdor** [JAM-Software/Virtual-TreeView#554]
Presently PrepareBitmaps makes use of windows themes but ignores the size of the returned theme images as it overwrites that size when it calls LoadBitmap later on in the routine. It would be better to do something like the code below in PrepareBitmaps. All of the theme code should go together in one place. This is just edited in the ticket as it's just moving the code around but it should be fine. I will update the code once I have updated to the latest version.

Code removed for clarity...

**Comment by joachimmarder** [comment]
Would you mind sending a pull request or a diff-file based on the current code in master?

Please be advised that markdown syntax is supported in GitHub issues, the above is hard to read.

**Comment by Matterdor** [comment]
Apologies, the issue is fixed in this version of VST. I missed the checks in the source code for `if Theme = 0 then'. It was fixed as part of issue #347 and merged into the release of 6.1.
