### ISSUE TITLE
Variable height and more than 1 level give incorrect RangeY

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#556]
Hello,

In our application, we use variable height nodes and multiple levels in a tree.
We recently upgraded to the latest git revision and started noticing that the scrollbars on our treeviews were too short, they don't allow to scroll to the last element anymore.
Tracing back history, I could determine that it comes from revision 2fa5699cd25964322234c04eeed819e424df93e7 on 2014/12/22 where DoMeasureItem was modified to make sure it calls InitNode.
Removing that call allows us to go back to a normal behavior.
You will find a sample application showing the issue here:

http://obones.free.fr/vtv/scrollbars.zip

Reading the log, I can't see why the call to InitNode was added, but I believe there must be a good reason for it.
How can we thus leave it in and still fix the issue when using variable node heights?

**Comment by joachimmarder** [comment]
> Reading the log, I can't see why the call to InitNode was added,
> but I believe there must be a good reason for it.

It was a request by another user, which I found quite obvious. How should a node's height be determined if it is not initialized? This is what the user wrote:

> It happens when DoMeasureItem is called in SetChildCount. When I look at AddChild 
> (arround line 27300), this happens before the userdata is assigned to the new nodes Data.
> My userdata is simple:
> `TBSNodeRecord = packed record
>     Data : TBSTreeNode;
>   end;`
> [...]
> In order to have DoMeasureItem called, I have to add toVariableNodeHeight to MiscOptions.
> Unfortunately DoMeasureItem is called to early now: It's called before "UserData" of the 
> node is set, so Node.Data is not valid in DoMeasureItem.
> I keep an object for each node and map all Tree methods I need to that objects (virtual) method

**Comment by obones** [comment]
This seems clearly logical, hence my request to leave it and still find a way to have variable node heights be properly taken into account with multiple levels.

**Comment by joachimmarder** [comment]
The problem only occurs in case ivsExpanded is used. IT can also be seen in the "Advanced" sample project on the second page "General abilities".

**Comment by joachimmarder** [comment]
> Removing that call allows us to go back to a normal behavior.

I cannot confirm this. After pressing fill, the scroll position is somewhere in the middle, and increasing the root node count to 13 shows other odd behavior when scrolling down.

**Comment by joachimmarder** [comment]
The problem even occurs if we always pass DefaultNodeHeight  in the OnMeasureItem event, so effectively having different node heights is not important for the problem becoming visible. Removing the toVaribleNodeHeight flag makes the problem disappear.

**Comment by joachimmarder** [comment]
I just committed a fix which solved the issue at least for your demo project.

**Comment by obones** [comment]
Thanks, it does fix the issue
