### ISSUE TITLE
Using isFiltered in InitNode leads to integer overflows or bogus rendering

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#557]
Hello,

In our application, we use nodes that are filtered when initialized.
We recently upgraded to the latest git revision and started receiving integer overflow exceptions in debug and bogus display in release.
Tracing back history, I could determine that reverting revision 2fa5699 on 2014/12/22 where DoMeasureItem was modified to make sure it calls InitNode sort of fixes the issue.
I mean, it prevents the integer overflows from happening, but clearly, the rendering is not correct.
You will find a sample application showing the issue here:

http://obones.free.fr/vtv/isFiltered.zip

Using variable node heights is a sure way to trigger the integer overflows. If you remove that, there are no exceptions, but the rendering is bogus, one cannot scroll to the first items.
I tried to change FVisibleCount to be an Int64 instead of a Cardinal, and sure enough, there no longer are any overflows, but the rendering still has the same problem.

In what direction should I look to try a fix?
Regards

**Comment by joachimmarder** [comment]
With toVaribaleNodeHight the OnInitNode event is fired earlier, then FVisibleCount is first decremented then incremented. Starting with an empty tree, FVisibleCount will be <0 for a short moment. There are two quickfixes:
- Turn off overflow checking
- Use a signed type instead of an unsigned, e.g. NativeInt.

**Comment by obones** [comment]
I already tried option 2, by using Int64 but it does not help with the rendering issue, the scroll bar is way off.
And there actually is no need for variable node heights to have the bogus rendering.

**Comment by joachimmarder** [comment]
Overflow is fixed, rendering not. Removing the call to InitNode() in DoMeasureItem() does not fix the rendering for me. Since I don't use filtering I am not very experienced in this part of the code.

**Comment by obones** [comment]
Hello,

Do you have the complete details for issue #447?
I'm looking at a potential fix but it changes lines that were specifically made for this issue and I'd like to understand what it was all about

**Comment by joachimmarder** [comment]
> Do you have the complete details for issue #447?

It seems that #447 was deleted in Google Code and so not imported to GitHub. What is your exact interest in #447?

**Comment by obones** [comment]
Well, it changed lines inside SetChildCount so that, initially, GetNodeHeight was called to get the height. This, in turn, called InitNode if needed. 
That initial change, on 2014-07-15 (a4866273530cd34f40df9a63552a1d73afca78ce) looks quite justified to me because the total height does depend on the variable node heights.
Three days later, on 2014-07-18 (ec83591533693986f55b68183587f834994720ad) the call to GetNodeHeight was replaced by a direct call to DoMeasureItem to avoid superfluous calls to AdjustTotalHeight. I have no idea what issues those calls were creating, but I suspect it has to do with filtering/and or visibility. Also, this avoids calling InitNode too early, thus keeping the virtual aspect of the tree.
However, now that DoMeasureItem also calls InitNode, I don't see the point of not calling GetNodeHeight anymore, especially considering that my experiments to find a fix for the filtering issue lead strongly in that direction.
That's why I wanted to have a clear picture of what's required for this code to work in all cases, as I wouldn't want to reintroduce a bug that was fixed earlier.

**Comment by joachimmarder** [comment]
OK, I understand. It's very bad that #442 has disappeared. I checked my old e-mails and the issues that this commit resolved were submitted by other users of Virtual TreeView, and they afterwards confirmed that the issue were resolved.

Can you suggest a change that fixes the issues for you?

> However, now that DoMeasureItem also calls InitNode, I don't see the point of not calling GetNodeHeight anymore

GetNodeHeight () involves more code and so is slower. AdjustTotalHeight() is implicitly called for each node although it should be possible to summarize this in one call to AdjustTotalHeight() here.

> Also, this avoids calling InitNode too early, thus keeping the virtual aspect of the tree.

When working with ivsExpanded and ivsExpanded like in your sample, you need to choose your poison: correct scrollbars or more virtual paradigm. In the end, the node height of all nodes is needed for displaying correct scrollbars.

**Comment by obones** [comment]
Here is a pull request for this issue:
https://github.com/Virtual-TreeView/Virtual-TreeView/pull/559

It fixes all the various combinations that I tried here.

**Comment by joachimmarder** [comment]
Thanks for the pull request, I've just merged it.

**Comment by sanjayssk** [comment]
Reopening this issue as the fix seems to be causing problems mentioned in #675.

**Comment by obones** [comment]
AddChild use is not recommended and will eventually suffer from changes that are needed to have the pure virtual mode to work properly.
Now, if you find a way to have both work ok, please help us.

**Comment by sanjayssk** [comment]
I went back to the release where Integer Overflows were occurring. Then I just removed the code that I pointed out above in SetChildCount that is causing the problem. It fixed the overflows.

However, I need to confirm what the rendering problem is to see if that too is because of the above change. 

The main problem is that #447 is missing for which that original change was made. It will take time to find all repercussions like the integer overflow. Let me confirm what the rendering problem mentioned is and then trace forward to all related changes made. Then I will report my findings here.

>>AddChild use is not recommended and will eventually suffer from changes
I would say, this is a grey area. I had a long text here. Updating: Sometimes initializing the expanded nodes later is too slow depending on the type of child data and from where it is coming. Many applications might simply fill the whole tree. The reason is to use the High capacity and Speed features of the virtual tree rather than expand-time-init of the children. Such applications will break as far as the speed is concerned. The code causing the break is not in this issue but from issue 447 which is missing.

**Comment by sanjayssk** [comment]
[TestIsFiltered.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/665473/TestIsFiltered.zip)

@obones 
I went back to an old release, 6.2, just to see what original problems were faced. I saw the integer overflow problem and then made the change of reverting 2fa5699 on 2014/12/22 as described at the top. As per that discussion, this solves the integer overflow which it did. But what I don't understand is what kind of "rendering" problem this refers to. There is no other description. I'm attaching the compiled EXE here with the above change. Please check and tell me what rendering problem this refers to. I need to understand it if I have to retrace all the related changes to understand them. I don't see a rendering problem yet. Thanks.

**Comment by sanjayssk** [comment]
Oops. Forgot to attach the file in previous reply. Done.

**Comment by sanjayssk** [comment]
I'm going to close this issue and add another one to describe the problem that I still see in the latest version with the given demo. This code mentioned in this issue is supposed to have solved the earlier rendering problem (not described) so it must be different from the one that I'm seeing.
