### ISSUE TITLE
Scrolling doesn't work when use method AddChild

### ISSUE THREAD

**Issue by salvadorbs** [JAM-Software/Virtual-TreeView#566]
When use method AddChild, VirtualTree doesn't show vertical scrollbar and scrolling (using keyboard's arrow keys) doesn't work

![2015-07-15_14-24-18](https://cloud.githubusercontent.com/assets/3731721/8698311/35c239d8-2afd-11e5-99ad-b03df689c441.png)

Sample project https://www.dropbox.com/s/w26eq2jo66envtl/VirtualTree_Scrollbar_bug.7z?dl=0
Delphi XE8 + VirtualTreeView (Git Master)

**Comment by salvadorbs** [comment]
Using tool **Git Bisect** seems this bug is caused by commit 911e2e9.

**Comment by joachimmarder** [comment]
Agreed, thanks for reporting.
@obones: This bug was introduced  by merging pull request #559.
Reverted this commit.

**Comment by obones** [comment]
Well, sure, but then again, the other bug is back...
We must find a way for both to work fine, but as a side note, AddChild was never the recommended way to add children in a treeview...

**Comment by obones** [comment]
Please see my latest pull request
