### ISSUE TITLE
AddChild and Synchronize() deadlock

### ISSUE THREAD

**Issue by LVbug1** [JAM-Software/Virtual-TreeView#570]
Hello, There ara example of deadlock BUG.
(Using delphi 7, 5.5.3 VLT)
Full sources are included here 
https://www.sendspace.com/file/t0johe

I started 2 TThread with Synchronize method (Resume buttons). Application freezed.  

unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, VirtualTrees;

type
  TForm1 = class(TForm)
    VirtualStringTree1: TVirtualStringTree;
    Button1: TButton;
    Edit1: TEdit;
    Pause: TButton;
    Stop: TButton;
    Button2: TButton;
    Button3: TButton;
    procedure VirtualStringTree1GetNodeDataSize(Sender: TBaseVirtualTree;
      var NodeDataSize: Integer);
    procedure Button1Click(Sender: TObject);
    procedure VirtualStringTree1GetText(Sender: TBaseVirtualTree;
      Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType;
      var CellText: WideString);
    procedure FormCreate(Sender: TObject);
    procedure StopClick(Sender: TObject);
    procedure PauseClick(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure Button3Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

 function wsprintfW      ( S: PWideChar; Format: PWideChar): Integer;    cdecl varargs;
             external user32;

function wsprintfA      ( S: PChar; Format: PChar): Integer;    cdecl varargs;
             external user32;

```
         type TNode1 = packed record
                         Text1W:array [0..100] of WCHAR;
                         Text2W:array [0..100] of WCHAR;
                         Now:TDateTime;
                        end;
            PNode1 = ^TNode1;
```

TNoopsThread=class(TThread)
  private
    public
  pMemoStringW:PWideChar;

  nnn:integer;

  DoExitNoopsThread:Boolean;
  IsClientThread:Boolean;
  protected

   procedure Execute;override;
   procedure Add ;

 end;

implementation

{$R *.dfm}

 var Noops1, Noops2:TNoopsThread;

function PrintDateTimeW(StrW:PWideChar; FtTime:system.TDateTime):PWideChar;
var ST:windows.TSystemTime;
begin
Result:= StrW;

DateTimeToSystemTime(FtTime, st);

with ST do wsprintfW(StrW, '%.4d.%.2d.%.2d - %.2d.%.2d.%.2d',
                                wYear, wMonth , wDay,wHour ,wMinute , wSecond
                          );

end;

procedure TForm1.VirtualStringTree1GetNodeDataSize(Sender: TBaseVirtualTree;
  var NodeDataSize: Integer);
begin
 NodeDataSize:=SizeOf(TNode1);
end;

procedure TForm1.Button1Click(Sender: TObject);
var i, k:Integer;
str, s2:array [0..100] of WCHAR;
Node:PVirtualNode;
pmy:PNode1;
begin

k:=StrToInt(edit1.text );

for i:=0 to k do
begin

```
 Node:=VirtualStringTree1.AddChild(nil);
 pmy:=VirtualStringTree1.GetNodeData(Node);
 pmy^.Now:=Now;
 PrintDateTimeW(pmy^.Text1W, pmy^.Now);
 wsprintfw(pmy^.Text2W,' Node %.4d', i);
```

end;

end;

procedure TForm1.VirtualStringTree1GetText(Sender: TBaseVirtualTree;
  Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType;
  var CellText: WideString);
  var pmy:PNode1;
begin
  pmy:=Sender.GetNodeData(Node);
 case Column of
 0:  CellText :=pmy^.Text1W;
 1:  CellText :=pmy^.Text2W;
 end;
end;

procedure TNoopsThread.Add;
 var
str, s2:array [0..100] of WCHAR;
Node:PVirtualNode;
pmy:PNode1;
begin
     Node:=FOrm1.VirtualStringTree1.AddChild(nil);
     pmy:=FOrm1.VirtualStringTree1.GetNodeData(Node);
     pmy^.Now:=Now;
     PrintDateTimeW(pmy^.Text1W, pmy^.Now);
     wsprintfw(pmy^.Text2W,' Node TREAD %i', nnn);
     Inc(nnn);
end;

procedure TNoopsThread.Execute;
begin
 while not DoExitNoopsThread do
 begin
  Synchronize( Add );

 end;

 end;

procedure TForm1.FormCreate(Sender: TObject);
begin
Noops1:=TNoopsThread.Create(true);
Noops1.nnn:=0;
Noops1.DoExitNoopsThread:=false;

Noops2:=TNoopsThread.Create(true);
Noops2.nnn:=0;
Noops2.DoExitNoopsThread:=false;

end;

procedure TForm1.StopClick(Sender: TObject);
begin
if Noops1.Suspended then Noops1.Resume;
end;

procedure TForm1.PauseClick(Sender: TObject);
begin
Noops1.Suspend;

end;

procedure TForm1.Button2Click(Sender: TObject);
begin
if Noops2.Suspended then Noops2.Resume;
end;

procedure TForm1.Button3Click(Sender: TObject);
begin
Noops2.Suspend;
end;

end.

**Comment by joachimmarder** [comment]
TThread.Suspend() is deprecated since many years for good reasons. Are you able to replicate the deadlock without using Suspend()?

**Comment by LVbug1** [comment]
"Are you able to replicate the deadlock without using Suspend()?"
Yes, In my application I used TNoopsThread.Create(false); (false == start after create). 

I added additional synchronization function:

procedure TNoopsThread.MySyynchronize(method:TThreadMethod);
begin
WaitForSingleObject(hSync1, 10000);
  Synchronize( method );
  ReleaseSemaphore(hSync1, 1, nil);
end;

And using

procedure TNoopsThread.Execute;
begin
while not DoExitNoopsThread do
begin
MySynchronize( Add );
end;
end;

It is work, but i doubt for this method...

**Comment by joachimmarder** [comment]
What I do see here is a frozen UI. I do not see a deadlock here in V6 / XE8: When I set a breakpoint on TBaseVirtualTree.AddChild(), the breakpoint is hit. The UI is frozen because your are flooding it with Synchronize calls that add sinngel tree nodes, this approach is extremely inefficient. When I add Sleep(200) in the while-loop of the thread, the application is working.
