### ISSUE TITLE
Grid mode and extended selection leads to drawing inconsistencies

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#571]
Hello,

I have uploaded a sample here: http://obones.free.fr/vtv/DancingText.zip
In that sample, you will see a string tree configured in grid mode with extended focus which means that you can select any cell in the grid, not just the leftmost one.
Here are the steps to trigger a rendering issue:
1. Click on Fill
2. Click on the first cell inside Column 2
3. Click on the first cell inside Column 1

You will now notice that the entire text in Column 2 is shifted one pixel to the right and the grid line between Column 3 and Column 4 is missing.
If you now move the mouse pointer over each cell inside Column 2, you will see that it gets redrawn, the text goes back to its place and the grid line reappears.

I traced into the code to see where this could come from and ended up inside `TBaseVirtualTree.PaintTree`
In that procedure, right before preparing the background and focus rect (call to `PrepareCell`), there is a code that draws the vertical line via a call to `DrawDottedVLine`.
If I remove the two `Dec` calls that are located right after, the text is no longer shifted to the right, but the grid line itself is still "eaten". And that's the thing I can't figure out. I initially thought the drawing bitmap was too small but increasing `PaintWidth` value does not help.

As anyone seen this?
Does anyone have suggestions for me to try?

**Comment by obones** [comment]
I went a bit further and traced how the rects are updated inside `TBaseVirtualTree.PaintTree` when it comes to grid lines. I noticed that it all comes down to the two Dec calls being made or not and so added trace points in the following locations:

One called "Vert decision" right before `if not ((hoAutoResize in FHeader.FOptions) and CellIsInLastColumn) then` 
One called "After vert" right before the call to `PrepareCell`

Here is a log extract:

[05:21.003] 1:3 Vert decision: FALSE TRUE FALSE into 0; 0; 661; 215
[05:21.003] 1:3 After vert: 300; 0; 399; 17
[05:23.489] 1:3 Vert decision: FALSE TRUE FALSE into 0; 18; 661; 36
[05:23.489] 1:3 After vert: 300; 0; 399; 17
[05:27.473] 1:3 Vert decision: TRUE TRUE FALSE into 200; 0; 400; 215
[05:27.473] 1:3 After vert: 300; 0; 400; 17
[05:51.421] 1:3 Vert decision: FALSE TRUE FALSE into 0; 18; 661; 36
[05:51.422] 1:3 After vert: 300; 0; 399; 17

At 05:21, it's the initial display
At 05:23, I select the first cell
At 05:27, I select (with the mouse) the second cell, the bug is showing
At 05:51, I move over the affected cell and it gets restored to a proper display

On the trace log, for the Vert decision, the three booleans are the values for `CellIsTouchingClientRight`, `CellIsInLastColumn` and `ColumnIsFixed` while the integer values are those from the `Window`parameter
For the "After vert", the integer values are those from `PaintInfo.CellRect`

Analyzing this, I see that the bogus display occurs when the tree is partially redrawn which leads to `CellIsTouchingClientRight` being True when it should not be.

Going into `TBaseVirtualTree.WMPaint` and forcing `FUpdateRect` to be always equal to `ClientRect` solves the issue at the cost of unnecessary repaints.

Any suggestion as to where the `GetUpdateRect` call is getting its values from?

**Comment by obones** [comment]
Ok, reading the MSDN documentation lead me to trace all calls to `InvalidateRect` and I found the culprit, it's inside `TBaseVirtualTree.InvalidateColumn`
So, inside that method, I decided to increment R.Right if it's lower than ClientRect.Right so that the painting code does not set `CellIsTouchingClientRight` to True when it shouldn't.

That fixes the issue, but I'm wondering if it's correct because there are other cases where partial invalidation takes place which would thus lead to another way to trigger the bug.

In the end, I believe it's the code that sets `CellIsTouchingClientRight` that should be modified from this:

```
CellIsTouchingClientRight := PaintInfo.CellRect.Right = Window.Right;
```

to this:

```
CellIsTouchingClientRight := PaintInfo.CellRect.Right = ClientRect.Right;
```

This fixes the issue and does not seem to have any impact on performance.

I have submitted the following pull request for this: https://github.com/Virtual-TreeView/Virtual-TreeView/pull/574

**Comment by obones** [comment]
Ok, rereading the comment right below where `CellIsTouchingClientRight` gets its value leads me to think that my fix will not work for spanning cells.
But I don't see how the original code would work either, the window is not an indicator of the area a cell is taking up.

**Comment by obones** [comment]
Well, I have checked this and it does not introduce a bug with autospanning cells, I thus believe this fix is good

**Comment by joachimmarder** [comment]
Merged. Thanks for your pull requests.
