### ISSUE TITLE
VirtualStringTree does not reset the saved width when changing the node count

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#572]
Hello,

`TCustomVirtualStringTree` stores each nodes text width inside the node's data and resets it upon changes in the structure of the tree.
However, when setting `RootNodeCount` (or any node count for that matter), the width is not reset and so the previous value is used, leading to display inconsistencies.
To illustrate, I have put a project here:

http://obones.free.fr/vtv/TruncatedText.zip

Here are the steps:
1. Press the Fill button
2. Notice the last three lines are displayed properly
3. Press the Delete button
4. Notice that the "a" line is now showing an ellipsis when there is no need for it

If you restart the application, check the "workaround" checkbox and repeat the steps above, you will see that this no longer happens.
This is why I suggest adding a call to `ReinitNode` at the end of `TBaseVirtualTree.SetChildCount`
I checked, this does not call `OnInitNode` immediately but rather when it's needed, on display. 

Any comments are welcome.

**Comment by obones** [comment]
Here is the pull request: https://github.com/Virtual-TreeView/Virtual-TreeView/pull/573

**Comment by joachimmarder** [comment]
Merged pull request.

**Comment by joachimmarder** [comment]
Attached sample project.

[TruncatedText.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/103693/TruncatedText.zip)
