### ISSUE TITLE
ReinitNode latest change leads to incoherent behavior with children

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#576]
In revision 4714edbb660a5a8ac66118f57bec2f3d68cdbdbf, related to issue #565, the call to `InitNode` was removed from `TBaseVirtualTree.ReinitNode`
While I can understand the rationale behind that change, it introduces an issue when child nodes appear on nodes that did not have children before.
To illustrate what I'm saying, please use the sample here: http://obones.free.fr/vtv/ChildDeep.zip
When first run, the application shows a simple tree with two nodes and one child on that node.
If you use the buttons to add new items at various locations, you would expect the display to get updated to reflect the change.
However, adding a child on node 0 is not reflected in the treeview while it is when adding on node 1.
The only difference is that node 1 already has children, which means that the test inside `TBaseVirtualTree.InitChildren` evaluates to True because `vsHasChildren` already is in `States`

Apart from reintroducing the call to `InitNode` inside `TBaseVirtualTree.ReinitNode`, I'm not sure what can be done here.

Any comments are most welcome.

**Comment by obones** [comment]
Well, calling `InitNode` unconditionally is obviously not desirable but calling it only on nodes that were previously initialized (ie, displayed) should be fine.
This is what I suggest to do in the following pull request: https://github.com/Virtual-TreeView/Virtual-TreeView/pull/577

**Comment by landrix** [comment]
in some cases, i call ReinitNode after Set RootNodeCount := 1, this first Node will not be initialized. this behavior is only since version 6.2.0
