### ISSUE TITLE
Resize Header after Application lost focus : EArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by tris0x** [JAM-Software/Virtual-TreeView#578]
Resizing my header Columns does not work for me at the moment.
VirtualTrees.pas, Line 12536 (has a comment on this issue, too)
1. Open Form including VST With >1 Columns
2. Click onto another window such as a Windows Explorer Window
3. Click onto one of the header borders and Drag it
4. EArgumentOutOfRangeException: Argument out of Range

Any workaround for that available?

**Comment by tris0x** [comment]
found a workaround by setting Allowed := False in HandleOnColumnWidthTracking in case of the given Column being -1

**Comment by joachimmarder** [comment]
Which version of Virtual TreeView are you using? 
I was not able to replicate this behavior with the "Advanced" sample project and the latest source. Are you?

**Comment by tris0x** [comment]
the version iam using currently is v5.5, however i was able to locate the comment in the most recent sources still, so i guess its still persistent.

I've been testing around since yesterday for quite a while and i noticed that all other trees in my application work except for this single one. however, i was not able to find any differences in any of our handles or Tree/header settings.

**Comment by joachimmarder** [comment]
Can you post the line number of that comment in the latest source here? Or even better the method name and the relative line number?

Are you able to update to V6 and try if it fixes the issue?

**Comment by tris0x** [comment]
Sorry for not replying for a while, have been quite busy.

It's in VirtualTrees.pas, Line 10374
If you can't find it, search for "10/2013" in the sources

I'll try to upgrade to V6 - however i think the issue might have to do with windows Messages not being received in the correct order - resulting in having no columnIndex yet.

Edit: Mentioned Line fails due to the FTrackIndex being -1

**Comment by joachimmarder** [comment]
> I'll try to upgrade to V6

Did upgrading to the latest version solve the problem?

**Comment by joachimmarder** [comment]
Any new on this issue?

**Comment by joachimmarder** [comment]
No working repro for V6, no response, so closing this issue.
