### ISSUE TITLE
Support Delphinus

### ISSUE THREAD

**Issue by salvadorbs** [JAM-Software/Virtual-TreeView#580]
Delphinus is a new open source package manager (similar to Embarcadero's GetIt). It is nice to have VirtualTree package in Delphinus list. :smile: 

For more information:
https://github.com/Memnarch/Delphinus
https://github.com/Memnarch/Delphinus/wiki

**Comment by joachimmarder** [comment]
Done, However Delphinus tells me that the json file is corrupt, two JSON validators tell that it is OK.

**Comment by Memnarch** [comment]
You can not add a comma after the last element of an object. In case of the Delphinus.Info.Json, it's the comma after  the "compiler_min" element. http://jsonlint.com/ and https://jsonformatter.curiousconcept.com/ report this as invalid JSon. And thats what's causing Delphi to fail with parsing(when i report that its "corrupt", it means the TJSonObject.ParseJSonValue method failed)

**Comment by joachimmarder** [comment]
Sorry, since the file-iopen-dialog made me pick the Install.json file I checked only this.

**Comment by Memnarch** [comment]
I am sorry, i have to admit the Dialog is abit cumbersome, as you select the file but it uses the directory to gather all information.
(However, the installlog should have stated that the Delphi.Info.Json is corrupt o.O)

**Comment by joachimmarder** [comment]
It is working now except for the uninstall. It reports that no uninstallation file was found.

**Comment by Memnarch** [comment]
strange. Just tested on XE6 and it worked o.O. Can you look into your component direktory how your folder looks like?

**Comment by joachimmarder** [comment]
Maybe the problem occurred due to my previous testing or because it was done using a local directory. After clearing everything, it is now working for me as well.

**Comment by salvadorbs** [comment]
On my computer, Delphinus can't install VirtualTrees. I have this error message:
![](http://i.imgur.com/8hc5p8D.png)

Seems Delphi 10 can't find VirtualTreesD23.bpl. So I checked Delphi 10's bpl folder and I have only two VirtualTree's bpl:
- VirtualTreesR23.bpl
- VirtualTreesD2.bpl (:exclamation:)

P.S.: Sorry for my bad english. ^^"

**Comment by joachimmarder** [comment]
Thanks for letting me know, there was a digit missing in the LibSuffix. I also added "first_version" field now.
