### ISSUE TITLE
EditNode fails in V6.0.0 release and up

### ISSUE THREAD

**Issue by ghost** [JAM-Software/Virtual-TreeView#581]
The CanEdit  in V6.0.0 is expanded with extra checks (and ((Column < 0) or (coEditable in FHeader.Columns[Column].Options));)

Why is this? If you invoke the EditNode method for a focused node and a real column nr. (e.g. column 1), the statement (and (Column<0)) will always fail and you will not be able to edit the node.

Is this correct? What am I missing here?

**Comment by ghost** [comment]
I came from version 5.3.0 and noticed it in version 6. I now see that the extra code line is implemented somewhere in between 5.3.0 and 6.0.0.

**Comment by joachimmarder** [comment]
If no columns are defined `Column` will be < 0. If columns are defined for the tree, the column needs to be flagged as `coEditable` so that the user can edit it.

**Comment by ghost** [comment]
OK, thanks!
