### ISSUE TITLE
Delphinus: after releasing the next version, please specify first_version in Delphinus.Info.Json

### ISSUE THREAD

**Issue by Memnarch** [JAM-Software/Virtual-TreeView#583]
When the next release of VST goes live, it'll be the first to show up in Delphinus.
When Delphinus pulls info from a Repository, it checks all releases for Delphinus support(i know, i should stop on the first not supported release, that's something i'll add later). If first_version is specified, it checks only from the most recent downto the version specified there and ignores all older ones. This helps to reduce api calls to Github.

You can specify this property after releasing the new version if you want, as this information is pulled from head.

**Comment by joachimmarder** [comment]
I guess you meant "Delphinus.Info.json", which was done.

**Comment by Memnarch** [comment]
Yes, i am sorry that i didn't update the issue.
