### ISSUE TITLE
added vsInitializing breaks vst

### ISSUE THREAD

**Issue by landrix** [JAM-Software/Virtual-TreeView#584]
i switched from 6.1.0 to 6.2.0

in some cases on closing the formular with a vst there are access violations on freeing objects

here:
FreeMem(FRoot);

After several hours searching I've found the cause: the new TVirtualNodeState vsInitializing 

after removing all according code (not much), it works

**Comment by joachimmarder** [comment]
This flag was introduced by @obones with commit 69f483c in pull request #559 for issue #557.

**Comment by obones** [comment]
Please provide an example so that I can have a look at it.

**Comment by landrix** [comment]
At the moment I can not comprehend it in an small example. I try it more.

**Comment by landrix** [comment]
i found it at my own source code, thanks for the attention
