### ISSUE TITLE
Drag node without focussing it

### ISSUE THREAD

**Issue by x3mike** [JAM-Software/Virtual-TreeView#589]
Hello, 
how can I drag a node without focussing it? If it is not possible yet, please consider this as an extension  - Thanks.

x3mike

**Comment by joachimmarder** [comment]
Typically a mouse click focuses a node. You can't drag anything without clicking it. What is your use case?

**Comment by x3mike** [comment]
The tree is bound to some content which is displayed side by side. Now I want to let users drag an other node into the current content, without changing the content.

**Comment by joachimmarder** [comment]
> Now I want to let users drag an other node into the current content

And how is the user supposed to do this without clicking the node?
If the user clicks the node, selection and focus changes. This seems correct and intended to me.

>  without changing the content.

The Virtual TreeView won't change this content. I guess it is code in the OnChnage event handler that does this, and this code is under your control.

**Comment by x3mike** [comment]
that is right, my handler displays the content. But I cannot checkout if the user is starting a drag operation or not. That can only be done by the tree control.

**Comment by joachimmarder** [comment]
> But I cannot checkout if the user is starting a drag operation or not.

That is not correct. The property TreeStates will contain tsVCLDragging, tsOLEDragging or something similar. And before the drag operation the OnGetDataObject is fired, at least for OLE drag&drop.
