### ISSUE TITLE
Allow to store InternalData also for (internal) root node

### ISSUE THREAD

**Issue by romankassebaum** [JAM-Software/Virtual-TreeView#590]
For the TCustomVirtualExplorerTree which is part of the MustangPeakComponents, I need internal data for the root node.

The current implementation

{code: Delphi}
function TCustomVirtualStringTree.InternalData(Node: PVirtualNode): Pointer;
begin
  if (Node = FRoot) or (Node = nil) or (FInternalDataOffset = 0) then
    Result := nil
  else
    Result := PByte(Node) + Self.NodeDataSize + FInternalDataOffset;
end;
{code}

returns always nil for the root node. Since the memory for the internal data is allocated, there is no need to do so.
From my point of view the implementation should be changed to

{code: Delphi}
function TCustomVirtualStringTree.InternalData(Node: PVirtualNode): Pointer;
begin
  if (Node = nil) or (FInternalDataOffset = 0) then
    Result := nil
  else
    Result := PByte(Node) + Self.NodeDataSize + FInternalDataOffset;
end;
{code}

**Comment by joachimmarder** [comment]
The code was like this for years as far as I know. But there's nothing that comes to my mind that contradicts this change.

**Comment by romankassebaum** [comment]
The changeset could break existing code but I think it is unlikely that someone relies on the fact that the internal data for the root node are always nil.

**Comment by studylamp** [comment]
I am pretty sure I have recursive functions that check the data on a node and use nil as an exit condition. I don't see a reason to change this, and you will definitely break code with it.

**Comment by romankassebaum** [comment]
Just to explain it, we are talking about the internal data, not the data.

If you derive from the TCustomVirtualStringTree you can save some additional data for your component.
This has nothing to do with the data property you can use in your applications.

TCustomVirtualExplorerTree is derived from TCustomVirtualStringTree  and needs the internal data.
In the past it has the InternalData method overridden.

**Comment by studylamp** [comment]
Aha, thank you, now I understand. Yes, I agree this change should not cause a problem.  Either way it would not be difficult to fix.
