### ISSUE TITLE
C++ Builder XE7 project issues

### ISSUE THREAD

**Issue by dcembala** [JAM-Software/Virtual-TreeView#596]
We have been succesfully using version 5.1 in our application for some time now. We wanted to update to current version and see what changed but we encountered following issues (We are using C++ Builder XE7 Update1, same effect on 2 different PCs):

Trying to compile VirtualTreesCR.cbproj gives error:
[DCC Fatal Error] VirtualTrees.pas(3894): F1026 File not found: 'VTHeaderPopup.dcu'

After adding VTHeaderPopup.pas to project it succesfully compiles and VirtualTreesCD installs but while placing new TVirtualStringTree component on a form in new clean project it gives nasty acces violation:
![error_virtual](https://cloud.githubusercontent.com/assets/13776914/11680748/a0f9a508-9e5a-11e5-918d-8ea5aaee4941.png)

**Comment by joachimmarder** [comment]
Did you use V5.1 with C++ Builder XE7, or with an earlier version of C++ Builder?

Using the package VirtualTreesD.dproj will work, but is only possible if you also have the Delphi personality installed and loaded.

**Comment by dcembala** [comment]
Yes in XE7, we created our own .cbproj to compile and install it in C++ but our project with updated sources give exact same effect as the one here.
We dont have Delphi personality only C++ so we cant use .dproj :(

**Comment by joachimmarder** [comment]
@romankassebaum confirmed this issue to me. We think it could be a linker error in the C++ Builder linker, which is triggered by a certain source code change in Virtual TreeView in the apst.

The problem is that I don't use C++ Builder. It would be great if you could manage to find the last working version of Virtual Treeview. If we could identify the source code change that triggered the linker error, we could try to find a workaround.

**Comment by dcembala** [comment]
Last working version for us is 5.5.3 since 6.0 we get the the error like in the screen above.

**Comment by dcembala** [comment]
commit 4f0cad5 - last working commit, it seems that there is a problem when R package is set to runtime only, after changing back to design time even current version works fine in c++ builder. no idea why, R should be runtime only but something makes it impossible to work that way in c++

**Comment by joachimmarder** [comment]
I removed the dependency of the designtime package on the runtime package, that way the runtime package can stay a runtime package. I my tests with C++ Builder XE7 and XE8 it was now working again at designtime, compile-time and runtime.

**Comment by joachimmarder** [comment]
Another C++ Builder user just confirmed that these changes fixed the problem for him. The version was XE7.

**Comment by dcembala** [comment]
Yes i can confirm it's working here too.

**Comment by dcembala** [comment]
Although this project and plain virtual tree works i think there is still something wrong with this package configuration. The problem shows when i try to make my own tree component whitch inherits from virtual stringtree in separate package. Whent i try to install new package there is an error:

![vt_err](https://cloud.githubusercontent.com/assets/13776914/11972042/c9cb7e10-a946-11e5-8f8e-c0f9678d5e70.png)

I think it's because all the units from R package are also in D package and that makes impossible to make another package with component inherited from virtual tree.

**Comment by joachimmarder** [comment]
This is a result of the workaround I used. It should work you make you designtime package depend on VirtualTreeCD, _not_ VirtualTreesCR.

**Comment by dcembala** [comment]
I tryied that but i get the same error just insetead 'VirtualTreesCR' there is my package name. The funny thing is i dont even include Virtualtrees.classes in my project i only use #include "VIrtualTrees.hpp" and add VirtualTreeCD as reference in requires section of project

**Comment by joachimmarder** [comment]
I'm sorry, but I myself don't use C++ Builder and the original problem is a bug in C++ Builder. Please try to get support from Embarcadero. Everything is working if you use Delphi packages, but this is only possible if you have a license of RAD Studio.
