### ISSUE TITLE
Vertical Scrollbar Position and Height not correct

### ISSUE THREAD

**Issue by landrix** [JAM-Software/Virtual-TreeView#597]
I thought, this helps, but it does not help 
https://github.com/Virtual-TreeView/Virtual-TreeView/issues/556

if i add many nodes to a vst, the calculated vertical scrollbar does not fit to added nodes. if i scroll down to the end of the list, the scrollbarposition is recalculated and the slider jumps up. This I can do several times, until I reach the right end. 

here a simple code example:

  VirtualStringTree1.RootNodeCount := 1;
//  VirtualStringTree1.ReinitNode(VirtualStringTree1.RootNode,true); does not help

procedure TForm1.VirtualStringTree1InitNode(Sender: TBaseVirtualTree; ParentNode, Node: PVirtualNode;
  var InitialStates: TVirtualNodeInitStates);
begin
  case Sender.GetNodeLevel(Node) of
    0 :
    begin
      Sender.ChildCount[Node] := 100;
      Include(InitialStates,ivsHasChildren);
      Include(InitialStates,ivsExpanded);
    end;
    1 :
    begin
      Sender.ChildCount[Node] := 100;
      Include(InitialStates,ivsHasChildren);
      Include(InitialStates,ivsExpanded);
    end;
    2 :
    begin
      Sender.ChildCount[Node] := 100;
      Include(InitialStates,ivsHasChildren);
      //Include(InitialStates,ivsExpanded);
    end;
  end;
end;

procedure TForm1.VirtualStringTree1GetText(Sender: TBaseVirtualTree; Node: PVirtualNode; Column: TColumnIndex;
  TextType: TVSTTextType; var CellText: string);
begin
  Celltext := Sender.GetNodeLevel(Node).ToString + ' '+Node.Index.ToString;
end;

**Comment by joachimmarder** [comment]
This issue is related to `ivsExpanded`, it can also be replicated using the Advanced sample project: Go to the page "General abilities"  and scroll down.

The "problem" is that the `ivsExpanded` initial state is evaluated when a node is initialized. A node is initialized when it comes into the view or when it is sorted. The first case applies in the above repro steps.

Changing this could lead to a cascade of node initializations on startup which would thwarth / neglect the virtual paradigm.

As a workaround one can force node initialization. 

I would be very interested in hearing some more opinions on this issue.

**Comment by landrix** [comment]
How can i force node initialization?

**Comment by joachimmarder** [comment]
By calling the method InitNode() with the node to be initialized.

**Comment by landrix** [comment]
Is it conceivable to introduce a procedure like this?

procedure TBaseVirtualTree.InitNode(Node: PVirtualNode; RecursiveToSubNodeLevel: Cardinal)

RecursiveToSubNodeLevel means the initialisation depth starting from Node.

if not, you can close this issue, thanks

**Comment by joachimmarder** [comment]
I just added InitRecursive() to GitHub repo, let me know what you think.

**Comment by landrix** [comment]
yes, it works, great

here an optimized version
- i think, already initialized nodes should not reinitialized
- if node = nil, then set rootnode and start with the same level again

strangely, in my example above, it's enough to call InitRecursive(nil,2) for an correct scrollbar. I thought it would be 3. RootNode = 3, NodeLevel 0 = 2, NodeLevel 1 = 1, NodeLevel 2 = 0

procedure TBaseVirtualTree.InitRecursive(Node: PVirtualNode; Levels: Cardinal; pVisibleOnly: Boolean);
// Initializes a node and optionally its children up to a certain level.
var
  Run: PVirtualNode;
begin
  if not Assigned(Node) then
  begin
    InitRecursive(FRoot,Levels,pVisibleOnly);
    exit;
  end;

  if (Node <> FRoot) then
  if not (vsInitialized in Node.States) then
    InitNode(Node);
  if (Levels = 0) or (pVisibleOnly and not (vsExpanded in Node.States))  then
    exit;
  Run := Node.FirstChild;

  while Assigned(Run) do
  begin
    InitRecursive(Run, Levels - 1);
    Run := Run.NextSibling;
  end;
end;

**Comment by joachimmarder** [comment]
> i think, already initialized nodes should not reinitialized

Agreed / changed. I was under the wrong impression that InitNode() already checks that.

> if node = nil, then set rootnode and start with the same level again

Why do you think this is an optimization?

**Comment by landrix** [comment]
new version, Now Level and visibility are evaluated, if Node = nil

procedure TBaseVirtualTree.InitRecursive(Node: PVirtualNode; Levels: Cardinal; pVisibleOnly: Boolean);
// Initializes a node and optionally its children up to a certain level.
var
  Run: PVirtualNode;
begin
  if not Assigned(Node) then
    Node := FRoot;

if (Node <> FRoot) then
if not (vsInitialized in Node.States) then
InitNode(Node);
if (Levels = 0) or (pVisibleOnly and not (vsExpanded in Node.States)) then
exit;
Run := Node.FirstChild;

while Assigned(Run) do
begin
InitRecursive(Run, Levels - 1);
Run := Run.NextSibling;
end;
end;

**Comment by landrix** [comment]
the current version skips 1 Level, if Node is initialy nil

so
InitRecursive(nil)
InitRecursive(vst.RootNode)
have different results, if levels = 0 or RootNode is not expanded and pVisibleOnly = true

**Comment by landrix** [comment]
https://github.com/Virtual-TreeView/Virtual-TreeView/pull/600

**Comment by landrix** [comment]
i should be done

**Comment by attikov** [comment]
I don't know, AddChild() initializes the Node and sets vsInitialized, but ToggleNode() in this InitNode() does not measures the Heights through OnMeasureItem, as the node has no Childs at the time.
Also, setting the NodeHeight in the OnInitNode event does not help.

After adding the nodes, InitRecursive does not do anything because of 
"and not (vsInitialized in Node.States)".

This is perhaps just a workaround for a treeview with default nodeheights, not sure though how should it work.
