### ISSUE TITLE
Dangling WM_Timer and doubled OnChange calls 

### ISSUE THREAD

**Issue by Memnarch** [JAM-Software/Virtual-TreeView#602]
Warning: Hope i observed it right!

Everywhere, where DoChange is called (outside from Change), it checks for tsChangePending. This check however is NOT applied within the WM_TIMER method before calling it.

When can this be problematic(depending on the application compexity)?:
- ChangeDelay is set (so changetimers are active)
- I start to Drag an unselected node (selection changes, ChangeTimer is set)
- i Drop the node 
  - it is important that change events have fired before doing the code in dropevent!
  - to ensure this, i call BeginSyncEndSync before i proceed which will trigger pending changevents and stop the timer
- After the drop event, the OnChange event is triggered again
  - Why? stopping the timer will not remove posted WM_TIMER messages
  - Pending WM_TIMER message is processed
  - DoChange/OnChange is triggered, without any changes actually being present

And it seems, that its possible that the dangling WM_TIMER message is even processed between a DragDrop and StructureChange (Event)Call.

So without timers its
DragDrop
StructureChange

and with timers its
DragDrop
Sometimes Change
StructureChange

**Comment by joachimmarder** [comment]
I agree: If the WM_TIMER message is already in the message queue, StopTimer() won't remove it and it will be processed. Checking for tsChangePending before doing so should improve the situation.

Regarding drag&drop: It could make sense to call BeginSynch() / EndSynch() internally in this case as it does the necessary stuff: stop the ChnageTimer and handle an active tsChangePending flag.
