### ISSUE TITLE
Using isFiltered in InitNode leads to integer overflows or bogus rendering when reiniting

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#603]
Hello,

Issue #557 dealt with a totally similar situation where using `isFiltered` in `InitNode` lead to bogus rendering. While this has been solved, the issue still exists when reiniting a tree and some nodes are no longer filtered.
The following sample shows the issue:

http://obones.free.fr/vtv/multiple_isFiltered.zip

Initially all nodes are filtered out.
Pressing the first button makes them all unfiltered during the `ReinitNode` call
Pressing the second button filters out some of them.

Once you have pressed that second button, you will notice that the scrollbar on the right is absent when clearly there is a need for it.
In extreme cases, this leads to `FRoot.TotalHeight` being negative (well, if cast to an integer) which gives range checks errors inside `SetNodeCount` if activated.

This is because `AdjustTotalHeight` is called inside `TBaseVirtualTree.SetFiltered` with an absolute value of 0 if the node is being initialized. This, however, means that we remove the node children's height twice when the node has already been initialized once.

A pull request will be made shortly to address the issue.

**Comment by joachimmarder** [comment]
Thanks for the pull request!
