### ISSUE TITLE
If a new node is selected by left click, OnChnage event should not fire with `nil` inbetween

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#605]
Currently, if the user left clicks a different node using the left mouse button, the OnChange event is fired twice. The first time with `Node=nil` as a result of the call to `ClearSelection()`, then with the new node. This can cause unnecessary updates in the UI, as consumers of the event cannot know if the selection was truly cleared, or if another OnChange will follow.

**Comment by joachimmarder** [comment]
Proposed solution: Create overloaded protected `ClearSelection()` with additonal paramter that allows to control whether or not the OnChange even is fired (with `nil`).

**Comment by romankassebaum** [comment]
You could also set the OnChange event to nil before you call ClearSelection. Something like

{code: Delphi}
lOnChange := FOnChange;
FOnChange := nil;
try
  ClearSelection;
finally
  FOnChange := lOnChnage;
end;
{code}

But maybe your solution is more beautiful.
