### ISSUE TITLE
High DPI Inheritance of Form

### ISSUE THREAD

**Issue by PetrDaricek** [JAM-Software/Virtual-TreeView#606]
Hello,
  I created FormAncestor and place on it VirtualTree component. Second I Created FormChild, it is inherited from FormAncestor. I Modified some properties of VirtualTree (I don't know if this step is required). All I develop on Windows 7 with standard 96DPI.
  When I run this program on Windows 8.1. with 192 DPI (200%) header and rows are to big. I searched why and I recognize this algorithms:
1) When loading FormAncestor DFM, then from TCustomForm.ReadState(Reader: TReader) method is called ScaleControls - > VirtualTree.ChangeScale -> VirtualHeader.ChangeScale. Height of Header has been changed too **19(Default) \* 2 (192/96 DPI)**.
2) When loading FormChild DFM, then from TCustomForm.ReadState(Reader: TReader) method is called ScaleControls - > VirtualTree.ChangeScale -> VirtualHeader.ChangeScale again. Heigh of Header has been changed too*\* 38 \* 2 (192/96 DPI).**

So Header is more bigger than should be.
I see in VCL units are flags to Rescale and rescale is performed only when this flag is set. For example, when I Load from dfm with of TButton, than in SetWidth method is set rescale flag to witdh. In TButton.ChangeScale is change with only if this flag is set, and on end of changescale is Flags unset. 
This mechanism ensures that the calling of Cahgnscale on with is only once.

I think it is bug in Virtual Tree.
I tested it on Delphi 10 Seatle with Subscription Update 1, Windows 7 64b (96DPI), and Windows 8.1  64b (192 DPI).

**Comment by joachimmarder** [comment]
I agree, this sounds like a bug.
