### ISSUE TITLE
Horizontal lines paint bug on scroll

### ISSUE THREAD

**Issue by delphinotes** [JAM-Software/Virtual-TreeView#608]
At the time of the horizontal scroll - horizontal lines are drawn incorrectly:

![h_dot_line_on_h_scroll](https://cloud.githubusercontent.com/assets/3316307/13374532/8ba48e84-dd98-11e5-9be3-204233693a00.png)

To fix this, just change line
SetBrushOrigin(Canvas, BrushOrigin.X, BrushOrigin.Y);
to
SetBrushOrgEx(Canvas.Handle, BrushOrigin.X, BrushOrigin.Y, nil);

(as it was in 4.8.6 version)

**Comment by joachimmarder** [comment]
This was changed in 2010 in commit [e0faa14](https://github.com/Virtual-TreeView/Virtual-TreeView/commit/e0faa1476478385cac8c276bf4f961a1e89e961e).  

I don't think it is wise to simply revert this change after a long time. Can this issue be reproduced with any of the included sample projects?

**Comment by delphinotes** [comment]
You can take demo project [MVCDemo](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos/Objects)
Stpes:
- reduce the width of the window (that there was a horizontal scroll bar) and click several times on the button:
  ![1](https://cloud.githubusercontent.com/assets/3316307/13375705/f4eb6222-ddb7-11e5-9e58-d59b720de0f5.png)
- if you zoom it, you will see the rendering artifacts:
  ![2](https://cloud.githubusercontent.com/assets/3316307/13375724/4df9677e-ddb8-11e5-8a25-4df0f259ef8b.png)
- if the scroll bar to scroll smoothly, artifacts are more pronounced:
  ![3](https://cloud.githubusercontent.com/assets/3316307/13375727/85893476-ddb8-11e5-9882-31ec57ac5039.png)

**Comment by delphinotes** [comment]
> commit e0faa14.

This commit contains two functions: SetCanvasOrigin and SetBrushOrigin, they were moved from the common code and they added LPtoDP function.
It seems that for SetBrushOrigin this was done by inertia and in fact it is not necessary.

**Comment by joachimmarder** [comment]
> and click several times on the button:

That did not show the artefacts, but using the slider did. 

> It seems that for SetBrushOrigin this was done by inertia and in fact it is not necessary.

This is quite possible, this change is indeed missing in the commit message.
