### ISSUE TITLE
Commit 0aded66 breaks ScrollBar drawing.

### ISSUE THREAD

**Issue by MarcusCalidus** [JAM-Software/Virtual-TreeView#613]
Hi,

Commit 0aded66 (issue #611) breaks ScrollBar drawing under certain circumstances. 

Line 30591 was changed from 
`NodeBitmap.Width := TargetRect.Right - TargetRect.Left;` 
to 
`Width := TargetRect.Right - TargetRect.Left;`
this leaves us with access violations and flickering none drawing scrollbars. please reverse that. thx.

cheers
Marco

**Comment by joachimmarder** [comment]
I'm very sorry, this was no an intended change.
