### ISSUE TITLE
SortTree() is called during EndUpdate() even if SortColumn = -1

### ISSUE THREAD

**Issue by SaschaSchaefer** [JAM-Software/Virtual-TreeView#617]
TBaseVirtaulTree.EndUpdate() calls SortTree if the option toAutoSort is set. If the sort column is set to -1, however, this should not be necessary. No actual sorting is performed, but we still iterate all nodes, which may cause some performance overhead.

**Comment by joachimmarder** [comment]
If there are no columns, we still need to sort in this case. 

If there are columns, we should indeed consider not to auto-sort if SortColumn is -1 as most likely no actual change will be performed. manual sorting would still be possible in this case.

**Comment by joachimmarder** [comment]
After reconsidering this I decided not to change anything. Even if there a columns and SortColumn is -1, a sort order might apply due to other application settings and a feature like toAutoSort should trigger sorting. If this is unwanted, toAutoSort can be removed until a SortColumn is defined.
