### ISSUE TITLE
bug in ShortenString (VirtualTrees.Utils.pas)(V6.2.3)

### ISSUE THREAD

**Issue by mksjgj** [JAM-Software/Virtual-TreeView#618]
procedure TForm5.Button1Click(Sender: TObject);
var
  rst:string;
begin
  rst:= ShortenString(self.Canvas.Handle,'A',99999);
  Assert(rst='A...');  -->this will failure, because rst actually is '...'-- a obvious error
end;

the bug lies in:  Result := Copy(S, 1,            L                         ) + '...';
it should be       Result := Copy(S, 1,            L  +   1                ) + '...';

**Comment by joachimmarder** [comment]
I finally started writing unit tests and added tests for ShortenString(). 

@mksjgj: I tried (and committed) your solution, but it does not pass all tests. Need to look into this later.
