### ISSUE TITLE
It is not possible to paint a background that covers the entire control

### ISSUE THREAD

**Issue by DRAMA22** [JAM-Software/Virtual-TreeView#619]
when i try to remove the node background color using onbeforecellpaint like this  

```
TargetCanvas.Brush.Style := bsClear;
TargetCanvas.FillRect(CellRect);
```

white background of node did not removed

**Comment by joachimmarder** [comment]
Well, with a brush set to bsClear then what's already there won't change. This like a +0 operation. Can you please comment more detailed why you think this is a bug? Can you attach a small sample project that illustrates the problem?

**Comment by DRAMA22** [comment]
well i tried to set the brush to clear to remove  node white back ground but it didnt remove it see the current project try to add gif image and see the node  white background did not removed and the transparent gif has white background too see this sample
[mm.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/208501/mm.zip)

**Comment by DRAMA22** [comment]
to be more specif column header color  comes over the gradient back ground and so on

**Comment by joachimmarder** [comment]
> virtualstringtree background to gradient so i tried to remove the 
> node bg white color to get the same look of the background

Problem is: The rect passed to the OnPaintBackground event covers only the area that is not filled by treenodes. This gets more visible if you use a vertical gradient and make this area smaller by adding more nodes or reducing the form's height. I am not sure if this behavior is intended by the original developers. But I agree that this looks more like a bug than a feature.

I will rephrase the issue title.

**Comment by DRAMA22** [comment]
also if you notice transparent gif images does not shows fully transparent it got some ugly white on the  gif background even that gif set to transparent .

**Comment by joachimmarder** [comment]
> The rect passed to the OnPaintBackground event covers only the area that is not filled by treenodes.
>  I am not sure if this behavior is intended by the original developers. 

After inspecting the code I have to say: This is intentional. I don't see a quick fix to achieve what you want. This requires a larger refactoring.

**Comment by DRAMA22** [comment]
hmmm i was thinking can i set the columns color to transparent ?

**Comment by joachimmarder** [comment]
For testing I put the painting of the gradient into TBaseVirtualTree.WMEraseBkgnd(). However, so far I did not manage to keep it visible and let the VST paint transparent over it.

**Comment by DRAMA22** [comment]
i see some TVirtualStringTree control in action doing it but how i dont know here is image for proof http://www.mediafire.com/convkey/aa84/9tbjvrug435zowbzg.jpg?size_id=4

**Comment by DRAMA22** [comment]
so i found a way by set the cell to gradient too . but any solve for gif image ?

**Comment by joachimmarder** [comment]
> but any solve for gif image ?

Can you attach a screenshot please? Since it is not VTV drawing the image, I'm not sure what we could do to improve the situation.

**Comment by DRAMA22** [comment]
yes sure screenshot attached , i did not found any way to solve it . if you check my attached project above you will see that i already set gifs to transparent
![img](https://cloud.githubusercontent.com/assets/11210592/14386438/12140cca-fda5-11e5-9a4c-db5f00e8b5d1.jpg)

**Comment by joachimmarder** [comment]
Sorry, I have no idea what could be the reason. And so far I don't see a reason why a a transparency  issue when painting a GIF on a TCanvas is related to Virtual TreeView. Have you tried transparent PNGs? Which version of Delphi are you using?

Please attach the updated project including the GIFs.

**Comment by DRAMA22** [comment]
here is the project i am using delphi xe7 i used same transparent gifs on normal Tlistview they works normal without this ugly white background
[mm.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/211130/mm.zip)

**Comment by joachimmarder** [comment]
These GIFs of your are animated GIFs. Animated GIFs are not supported in Virtual TreeView. I tried with some other transparent GIFs and they work as expected:

![2016-04-12 23_29_14-mm](https://cloud.githubusercontent.com/assets/10615289/14476194/963794ae-0106-11e6-8cc2-8c4d0b72e197.png)

Your GIFs are working too if they are not animated:
![2016-04-12 23_33_48-open image](https://cloud.githubusercontent.com/assets/10615289/14476318/47f2752e-0107-11e6-82fc-a1ab39597757.png)
