### ISSUE TITLE
check states - typos and helper

### ISSUE THREAD

**Issue by the-Arioch** [JAM-Software/Virtual-TreeView#620]
1) csMixedDiabled     // disabled 3-state checkbox

==> csMixedDiSSSSSSSSSSabled     // disabled 3-state checkbox

2)   csCheckedDisbaled,  // disabled checkbox, not uncheckable

==>   csCheckedDisABABABABled,  // disabled checkbox, not uncheckable

3) IsDisabled is handy - but it is not the only "what class of state is" check that is being used in real application codes. I suggest
3.1) to mark IsDisabled as "inline" - no point to waiste stack frames on it
3.2) add five counterpart functions

```
    function IsDisabled(): Boolean; inline;
    function IsNormal():   Boolean; inline;
    function IsPressed():  Boolean; inline;

    function IsChecked():   Boolean; inline;
    function IsUnChecked(): Boolean; inline;
    function IsMixed():     Boolean; inline;

function TCheckState.IsDisabled: Boolean;
begin
  Result := Value >= csUncheckedDisabled;
end;

function TCheckState.IsNormal: Boolean;
begin
  Result := Value in [csCheckedNormal, csUncheckedNormal, csMixedNormal];
end;

function TCheckState.IsPressed: Boolean;
begin
  Result := Value in [csCheckedPressed, csUncheckedPressed, csMixedPressed];
end;

function TCheckState.IsChecked: Boolean;
begin
  Result := Value in [csCheckedNormal, csCheckedPressed, csCheckedDisabled];
end;

function TCheckState.IsUnChecked: Boolean;
begin
  Result := Value in [csUnCheckedNormal, csUnCheckedPressed, csUnCheckedDisabled];
end;

function TCheckState.IsMixed: Boolean;
begin
  Result := Value in [csMixedNormal, csMixedPressed, csMixedDisabled];
end;
```

4) functions `GetPressed()` and `GetUnpressed` also are a single array XLAT oneliner - must be turned into "inline" as well

5) function `GetToggled()` is better also to be turned into inline array lookup. Currently it has two issues
5.1 it does not use `IsDisabled` function, which is bad for future maintainability
5.2 it mis-toggles `csCheckedPressed` => `csCheckedNormal` !!!

6) Since CheckState is but a Cartesian superposition between unrelated `[Checked,Unchecked,Mixed]` and `[Normal,Pressed,Disabled]` state classes, I think those to be extracted into separate types. Previously `CheckState` was memory-constrained and both those sets got packed them into one byte, more so done it was in a kind of random order (all disabled states in the end, normal and pressed interlined) instead of using bitfields.... Now with type helpers that byte-packing can be kept but writeable separated-concerns properties be introduced: like in `CheckStateVar.Mark := csChecked` and `CheckStateVar.UIState := csDisabled`

UPD. item 6 can not be writeable properties for the same reason as you converted SetXXX procedures into GetXXX copy-constructors. So it should be the same set of functions then... State-querying and COWing...

**Comment by the-Arioch** [comment]
Inlining of aforementioned function would take moving XLAT array consts into interface section.
Afterall that would be a good move - since those arrays are critically dependent upon the order of enumeration(s) they better be kept together, as close to one another s possible. Namespace then to be maintained by putting those constant arrays into `strict private` section of the record helper.

**Comment by the-Arioch** [comment]
looking at the CASE stmt in `function TBaseVirtualTree.GetCheckImage`
- csUncheckedDisabled => csUncheckedNormal
- csCheckedDisabled     => csCheckedNormal
- csMixedDiabled           => csMixedPressed

What? Why suddenly Normal changed to Pressed in the last line ?

---

Before the CASE there is that usual typo in comments

```
// Use disABled images, map ImgCheckState value from disabled to normal
```

---

The IF-condition with new helper can be more concise and no more needing intention-comment

Was:   `if ImgCheckState >= csUncheckedDisabled then begin // disabled image?`
To be: `if TCheckState(ImgCheckState).IsDisabled then begin`

**Comment by the-Arioch** [comment]
All in all i see it something like that (with XE2 conversion of record helper to advanced record ):

```
  (*** XE2 backport start **)

  // The check states include both, transient and fluent (temporary) states. The only temporary state defined so
  // far is the pressed state.
  TCheckStateEnum = (
    csUncheckedNormal,  // unchecked and not pressed
    csUncheckedPressed, // unchecked and pressed
    csCheckedNormal,    // checked and not pressed
    csCheckedPressed,   // checked and pressed
    csMixedNormal,      // 3-state check box and not pressed
    csMixedPressed,     // 3-state check box and pressed
    csUncheckedDisabled,// disabled checkbox, not checkable
    csCheckedDisabled,  // disabled checkbox, not uncheckable
    csMixedDisabled     // disabled 3-state checkbox
  );

  TCheckStateMarkKind = (csmUnchecked, csmChecked, csmMixed);
  TCheckStateUIState  = (csuDisabled,  csuNormal,  csuPressed);

  TCheckStateSet = set of TCheckStateEnum;

  TCheckState = record
    Value: TCheckStateEnum;
    class operator Implicit(const from: TCheckStateEnum): TCheckState; inline;
    class operator Implicit(const from: TCheckState): TCheckStateEnum; inline;

    class operator Equal(const a: TCheckState; const b: TCheckStateEnum): boolean; inline;
    class operator NotEqual(const a: TCheckState; const b: TCheckStateEnum): boolean; inline;

    // gotcha - http://stackoverflow.com/questions/8045635/delphi-in-operator-overload-on-a-set
    // class operator In(a: TCheckState; b: TCheckStateSet): boolean; inline;

//    const csUncheckedNormal   = csUncheckedNormal; // compatibility with TBaseVirtualTree.GetCheckImage 
//    const csUncheckedPressed  = csUncheckedPressed;
//    const csCheckedNormal     = csCheckedNormal;
//    const csCheckedPressed    = csCheckedPressed;
//    const csMixedNormal       = csMixedNormal;
//    const csMixedPressed      = csMixedPressed;
//    const csUncheckedDisabled = csUncheckedDisabled;
//    const csCheckedDisabled   = csCheckedDisabled;
//    const csMixedDisabled     = csMixedDisabled;

    function GetPressed(): TCheckState;   inline;
    function GetUnpressed(): TCheckState; inline;
    function GetToggled(): TCheckState;   inline;

    function IsDisabled(): Boolean; inline;
    function IsNormal():   Boolean; inline;
    function IsPressed():  Boolean; inline;

    function IsChecked():   Boolean; inline;
    function IsUnChecked(): Boolean; inline;
    function IsMixed():     Boolean; inline;

    constructor Create(const Mark: TCheckStateMarkKind; const State: TCheckStateUIState);

    function GetWithMarkKind(const Value: TCheckStateMarkKind): TCheckState;
    function GetWithUIState(const Value: TCheckStateUIState): TCheckState;
    function MarkKind: TCheckStateMarkKind; inline;
    function UIState:  TCheckStateUIState;  inline;

  strict private const
  // Lookup to quickly convert a specific check state into its (un-)pressed counterpart and vice versa.
  PressedState: array[TCheckStateEnum] of TCheckStateEnum = (
    csUncheckedPressed, csUncheckedPressed, csCheckedPressed,
    csCheckedPressed, csMixedPressed, csMixedPressed,
    csUncheckedDisabled, csCheckedDisabled, csMixedDisabled
  );
  UnpressedState: array[TCheckStateEnum] of TCheckStateEnum = (
    csUncheckedNormal, csUncheckedNormal, csCheckedNormal, csCheckedNormal, csMixedNormal, csMixedNormal,
    csUncheckedDisabled, csCheckedDisabled, csMixedDisabled
  );
  ToggledState: array[TCheckStateEnum] of TCheckStateEnum = (
    csCheckedNormal,   csCheckedNormal   { csCheckedPressed???? },
    csUnCheckedNormal, csUnCheckedNormal { csUnCheckedPressed???? },
    csCheckedNormal,   csCheckedNormal   { csCheckedPressed???? },
    csUncheckedDisabled, csCheckedDisabled, csMixedDisabled
  );
  MarkKinds: array[TCheckStateEnum] of TCheckStateMarkKind = (
    csmUnchecked, csmUnchecked,
    csmChecked,   csmChecked,
    csmMixed,     csmMixed,
    csmUnchecked, csmChecked, csmMixed
  );
  UIStates: array[TCheckStateEnum] of TCheckStateUIState = (
    csuNormal, csuPressed,
    csuNormal, csuPressed,
    csuNormal, csuPressed,
    csuDisabled, csuDisabled, csuDisabled
  );
  PackSets: array[TCheckStateMarkKind,TCheckStateUIState] of TCheckStateEnum =
    ((csUncheckedDisabled, csUncheckedNormal, csUncheckedPressed),
     (csCheckedDisabled,   csCheckedNormal,   csCheckedPressed),
     (csMixedDisabled,     csMixedNormal,     csMixedPressed));
  end;

.....

{ TCheckState }

function TCheckState.IsDisabled: Boolean;
begin
  Result := Value >= csUncheckedDisabled;
end;

function TCheckState.IsNormal: Boolean;
begin
  Result := Value in [csCheckedNormal, csUncheckedNormal, csMixedNormal];
end;

function TCheckState.IsPressed: Boolean;
begin
  Result := Value in [csCheckedPressed, csUncheckedPressed, csMixedPressed];
end;

function TCheckState.IsChecked: Boolean;
begin
  Result := Value in [csCheckedNormal, csCheckedPressed, csCheckedDisabled];
end;

function TCheckState.IsUnChecked: Boolean;
begin
  Result := Value in [csUnCheckedNormal, csUnCheckedPressed, csUnCheckedDisabled];
end;

function TCheckState.IsMixed: Boolean;
begin
  Result := Value in [csMixedNormal, csMixedPressed, csMixedDisabled];
end;

function TCheckState.GetPressed(): TCheckState;
begin
  Result := Self.PressedState[TCheckStateEnum(Self)];
end;

function TCheckState.GetUnpressed(): TCheckState;
begin
  Result := Self.UnpressedState[TCheckStateEnum(Self)];
end;


function TCheckState.GetToggled(): TCheckState;
begin
  Result := Self.ToggledState[TCheckStateEnum(Self)];
//  if Self = csCheckedNormal then
//    Result := csUncheckedNormal
//  else if not IsDisabled() then // do not modify disabled checkboxes
//    Result := csCheckedNormal
//  else
//    Result := Self;
end;

class operator TCheckState.Implicit(const from: TCheckState): TCheckStateEnum;
begin
  Result := from.value;
end;

class operator TCheckState.Implicit(const from: TCheckStateEnum): TCheckState;
begin
  Result.Value := from;
end;

function TCheckState.MarkKind: TCheckStateMarkKind;
begin
  Result := Self.MarkKinds[TCheckStateEnum(Self)];
end;

function TCheckState.UIState: TCheckStateUIState;
begin
  Result := Self.uiStates[TCheckStateEnum(Self)];
end;

constructor TCheckState.Create(const Mark: TCheckStateMarkKind;
  const State: TCheckStateUIState);
begin
  Self.Value := Self.PackSets[Mark,State];
end;

function TCheckState.GetWithMarkKind(
  const Value: TCheckStateMarkKind): TCheckState;
begin
  Result := TCheckState.Create( Value, Self.UIState);
end;

function TCheckState.GetWithUIState(
  const Value: TCheckStateUIState): TCheckState;
begin
  Result := TCheckState.Create( Self.MarkKind, Value);
end;

```

**Comment by the-Arioch** [comment]
I am somewhat surprised that `GetToggled()` converts xxxPressed into yyyNormal
I think if that is by-design it is to be documented in comments there, why it should happen that way, so the function would not be used for wrong goals.

**Comment by the-Arioch** [comment]
Tester for the new unbound states
Perhaps to be included into Advanced Demo ?

[Unit12.dfm.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/227944/Unit12.dfm.txt)
[Unit12.pas.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/227943/Unit12.pas.txt)

**Comment by joachimmarder** [comment]
Thanks you sharing your ideas, I adapted most of them.

**Comment by the-Arioch** [comment]
what about "CASE stmt in  function TBaseVirtualTree.GetCheckImage " ? Why is it so ?

I still think making MarkKind and UIState separate non-related enums as they logically are is needed to be done.

**Comment by joachimmarder** [comment]
> what about "CASE stmt in function TBaseVirtualTree.GetCheckImage " ? Why is it so ?

I have now replaced it by a function of TCheckStateHelper as well.

> I still think making MarkKind and UIState separate non-related enums 

I agree, but it was that way with pressed since I know VTV, and changing this meant a breaking change that I wanted to avoid.

**Comment by the-Arioch** [comment]
there is no breaking changes needed - that is exactly what advanced records and record helpers are about - introducing syntactic sugar without changes to the "engine"

see how it is implemented in my code above and in the testing form - it is made like virtual properties, like those very GetPressed and friends, Like I said in the topmost message here, in point 6 - 

> Now with type helpers that _byte-packing can be kept_ but writeable separated-concerns properties be introduced

**Comment by joachimmarder** [comment]
Yes, your code looks promising. I admit that I did not think that this could be done without breaking changes. I will reopen the issue and revisit that topic next month.

**Comment by the-Arioch** [comment]
For example `.GetEnabled` function in those terms would look like `.GetWithUIState(csuNormal)`. 

OTOH the direct inline implementation of `.GetEnabled` with a dedicated array and a single lookup is surely faster. Yet I thought someone mentioned Knuth... :-P

**Comment by the-Arioch** [comment]
This whole talk though made me finally reflex about another consequent change.

I could not completely switch form enumeration to enumeration-containing record for - AFAIR - two reasons. TCheckState was used as published property - and its constants were used for default parameters in some functions.

_And I wonder why on Earth `TVirtualTreeColumn` has checkstate as Published property - where and why is it needed like that_

Since Delphi does not allow records as published properties - I had to change them to enumerations there, which in turn enforced it for getter and setter routines. Which in turn made me do few explicit typecasts, because Delphi type inferring is next to non-existing and implicit typecasting works far from always...

Another DCC limitation, that with constants as default parameters, may be trivially worked around by inline overloaded functions. Or - in other terms - by adding plenty of boilerplate. Whether it would in the end simplify things or made them harder I ain't quite sure. If only Delphi had this limited tail-call optimization to make overloaded functions merely adding last default params into just different entrypoints for the main function body...

This de-coupling of UI state and mark state made me think about implementing a property editor allowing matrix-like selection of the value, and consequently if I even would need those properties published after that. Maybe I can live them `public`. Streaming them to/from DFM is trivial, adding to Object Inspector though would be....

**Comment by joachimmarder** [comment]
> And I wonder why on Earth `TVirtualTreeColumn` has checkstate as Published property - where and why is it needed like that

I think it was already there when I started contributing to VTV. I use it in the first columnas a kind of master checkbox:
![mastercheckbox](https://cloud.githubusercontent.com/assets/10615289/14760616/0ff05d54-0949-11e6-86d1-e04e93162246.png) ![mastercheckbox2](https://cloud.githubusercontent.com/assets/10615289/14760620/349ce276-0949-11e6-8c6e-ecff86ee5915.png)

**Comment by joachimmarder** [comment]
> Whether it would in the end simplify things or made them harder I ain't quite sure.

After reading your comment I am also not sure. The ratio of effort+boilerplate-code and and benefit does not look good for me.

**Comment by the-Arioch** [comment]
yes, I remembered the published properties was the main reason why I used enumeration, and then implementing enhanced property editor seems anyway needed and easy solution. After reviewing VTV source I found it was a false memory, mostly that approach of mine was because of default arguments to methods.

I guess your screenshot shows runtime work, but the issue of Published properties is them being seen in Object Inspector and DFM. And that is what made me wonder - not that the column can have the "aggregated" checkbox, but why it was made _published_ there, in the only single place in all VTV

**Comment by joachimmarder** [comment]
> but why it was made published there, in the only single place in all VTV

The columns are the only objects in VTV which can be defined as designtime and that can have a checkbox. If an object can be altered at designtime, I think it is not uncommon to allow designing the visibility and state of a checkbox as well. OK, the state is not so important and most likely nobody would miss it if it wouldn't be published, but it is that way for ages.

**Comment by the-Arioch** [comment]
Exactly the `state` here is kind of missing the aim, because you set the state of specific tree items in `.OnInitNode` event and then it is the accumulated set of all nodes is what defines the aggregated state of the column, it is bottom-up propagation, not top-down enforcement.

Reading the state from the DFM before any node even exist would make sense if the state of particular nodes to be created was enforced by column setting in DFM - but that is against VTV spirit and I hope is not taking place.

So while I agree `that way for ages` it still left me confused :-)

**Comment by joachimmarder** [comment]
> Exactly the state here is kind of missing the aim, because you set the state of specific tree items in .OnInitNode event and then it is the accumulated set of all nodes is what defines the aggregated state of the column

This is true for my use case. But those column checkboxes are being used for different use cases by other developers. E.g. they are used to define which columns are exported. Then the check state set at designtime would define a default setting which columns are exported, the columns to export can be altered at runtime by the user.

**Comment by joachimmarder** [comment]
After rethinking I came to the conclusion that the ratio of effort + boilerplate-code + minimal breking changes and and benefit does not look too good for me. There are more important issue I think. Maybe one day you will update your RAD Studio and will be able to send a pull request for this.  ;-)
