### ISSUE TITLE
GetHint calculates wrong width for HintText

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#623]
Using the OnGetHint event with a custom HintText (in the following example: 'abcdefghijklmnopqrstuvwxyz') causes the hint/tooltip to be calculated wrongly.
If HintMode is set to hmTooltip the width is calculated based on the actual CellText.
If HintMode is set to hmHint the width is calculated almost correct, but with some strange space on the right.
I didn't notice those problems with an older 5.2 version I previously used.

![vtv-hint](https://cloud.githubusercontent.com/assets/703571/15002712/833b7e5c-11a4-11e6-979c-20213e7dd492.png)

VTV 6.2.3
Delphi XE
Windows 7

**Comment by joachimmarder** [comment]
Issue with `hmTooltip` can be reproduced in newer Delphi versions as well.

Possible repro: Use Advanced sample project, open unit "PropertiesDemo", change property `HintMode` to `hmTooltip`, run project, open page "Properties tree", make columns small, hover over shortened value.

**Comment by sanjayssk** [comment]
This is now done and tested.

**Comment by sanjayssk** [comment]
Short issue description for changes.txt:
Hint rectangle width fixed for custom hint text in the Tooltip hint mode.
