### ISSUE TITLE
Wrong y-postion of checkboxes in high-dpi display mode

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#624]
Checkboxes are not properly vertically centered at 175% display scaling.
![2016-05-04 20_53_27-virtual treeview features demo](https://cloud.githubusercontent.com/assets/10615289/15025645/8c6f421a-123a-11e6-8c3a-aa8fc17c4097.png)

Screenshot taken from Advanced demo project, page "General Abilities", compiled with XE8 on Windows 10x64.

**Comment by sanjayssk** [comment]
I can't reproduce this problem on Windows 10 and Windows 8.1. Has this been fixed?

**Comment by joachimmarder** [comment]
No, it has not been Fixed. New Screenshot of GitHub master, Advanced demo project, page "General Abilities", compiled with 10.1 Berlin on Windows 10x64 @175%:

![2016-09-12 21_14_13-virtual treeview features demo](https://cloud.githubusercontent.com/assets/10615289/18449213/9ef568aa-792e-11e6-8d10-1a757eb726af.png)

**Comment by sanjayssk** [comment]
Here is what I see on the same, compiled with XE4 and on Win 10x64 @175% on
1920 X 1080. What can be different? Can you send me your EXE file to test?
Thanks.

[image: Inline image 1]

**Comment by joachimmarder** [comment]
Reason is that position is always calculated based on non-themed checkbox sizes retrieved through `GetSystemMetrics(SM_CXMENUCHECK)` done in `CreateSystemImageSet()`. But those are larger than the themed checkboxes (e.g. 29px vs. 20px at 175% on Windows 10). The Y-position is calculated in `AdjustImageBorder()`.

**Comment by joachimmarder** [comment]
Reason is that position is always calculated based on non-themed checkbox sizes retrieved through `GetSystemMetrics(SM_CXMENUCHECK)` done in `CreateSystemImageSet()`. But those are larger than the themed checkboxes (e.g. 29px vs. 20px at 175% on Windows 10). The Y-position is calculated in `AdjustImageBorder()`.
