### ISSUE TITLE
Access Violation in function TBaseVirtualTree.GetImageSize 

### ISSUE THREAD

**Issue by bamsey2k1** [JAM-Software/Virtual-TreeView#629]
Revision: 925
Line: 21773
sometimes lImageList = nil 

Acces Violation can occur in these lines: 

ilImageList := DoGetImageIndex(Node, Kind, Column, Ghosted, Index);
  if Index >= 0 then begin       //here
    if IncludePadding then
      Result.cx := lImageList.Width + ScaledPixels(2)           //lImageList = nil
    else
      Result.cx := lImageList.Width;            //lImageList = nil
    Result.cy := lImageList.Height;             //lImageList = nil
  end
  else begin
    Result.cx := 0;
    Result.cy := 0;
  end;

i suggest to change statement like beneath:
if Index >= 0 then begin

to:

if (Index >= 0) and (Assigned(lImageList)) then begin

**Comment by bamsey2k1** [comment]
i suggest to change statement like beneath:
if Index >= 0 then begin    

to: 

if (Index >= 0) and (Assigned(lImageList)) then begin

**Comment by joachimmarder** [comment]
> if (Index >= 0) and (Assigned(lImageList)) then begin

Well, why should someone make the effort to assign an imageindex while having no imagelist assigned? That doesn't make sense to me in a control working according to the virtual paradigm.

I see that this may happen in daily work and that an EAccessVilolation is not the best outcome for this inconsistency. We should consider raising an EInvalidOpException with a meaningful exception message instead.

**Comment by bamsey2k1** [comment]
imagelist is assigned, the problem began to occur since one of latest revisions

**Comment by joachimmarder** [comment]
> imagelist is assigned

But you wrote:

> sometimes lImageList = nil 

What value does `Kind` have in this case?

That this is AV now occurs is most liklely a result of the fixes implemented for issue #627:

> the problem began to occur since one of latest revisions

**Comment by landrix** [comment]
i have the same issue, Kind has value ikState

function TBaseVirtualTree.GetImageSize(Node: PVirtualNode; Kind: TVTImageKind = TVTImageKind.ikNormal; Column: TColumnIndex = 0; IncludePadding: Boolean = True): TSize;
...
  lImageList := DoGetImageIndex(Node, Kind, Column, Ghosted, Index);

DoGetImageIndex returns nil (Self.StateImages)

StateImages is never been set

**Comment by joachimmarder** [comment]
> StateImages is never been set

But why do you supply an imageindex for ikState if you don't have StateImages assigned?

**Comment by landrix** [comment]
i should take a look, i have only updated to current vst, my application isn't changed for years

is this a breaking change?

**Comment by joachimmarder** [comment]
> is this a breaking change?

I guess yes. It was introduced to fix issue #627. I could add an assertion or raise an EInvalidOperation exception with an informative error message instead of running into the AV. In the end it makes no sense to determine an imageindex whithout having an ImageList assigned.

**Comment by landrix** [comment]
ok, this works for older code with only ImageList

procedure TForm.vstKWGetImageIndex(Sender: TBaseVirtualTree;
  Node: PVirtualNode; Kind: TVTImageKind; Column: TColumnIndex;
  var Ghosted: Boolean; var ImageIndex: System.UITypes.TImageIndex);
begin
  if Kind in [ikNormal,ikSelected] then
    ImageIndex := .....
end;

**Comment by joachimmarder** [comment]
I have added an assertion now.
