### ISSUE TITLE
node.GetData and treeview.GetNodeData(node) returning wrong pointer

### ISSUE THREAD

**Issue by nocxsville** [JAM-Software/Virtual-TreeView#630]
Hi,

It seems that the "node.GetData" and "treeview.GetNodeData(node)" methods returning the wrong pointer. Here my example code:

```
type
  TMyObject = class
  public
    Value : String;
  end;

// ...

procedure TForm1.FormCreate(Sender: TObject);
var
  pL_Node : PVirtualNode;
  tL_MyObj1,
  tL_MyObj2 : TMyObject;
begin
  virtualTV.BeginUpdate;
  try
    tL_MyObj1 := (TMyObject.Create);
    tL_MyObj1.Value := ('Wello World');

    pL_Node := (virtualTV.AddChild(NIL, tL_MyObj1));
  finally
    virtualTV.EndUpdate;
  end;

  tL_MyObj2 := (TMyObject(pL_Node.GetData));
  tL_MyObj2 := (TMyObject(virtualTV.GetNodeData(pL_Node)));
end;
```

"tL_Object2" is pointing to a different address than "tL_MyObj1". However, I might doing something wrong.

tL_Object1.Value = 'Hello World'
tL_Object2.Value = ''

Thanks in advance :)

**Comment by joachimmarder** [comment]
`pL_Node.GetData()` gives you the pointer to the node data, you need to dereference it to get the pointer to your object. You need to chnage your code to:

```
tL_MyObj2 := (TMyObject(pL_Node.GetData^));
```

Or even better use the generic version:

```
tL_MyObj2 := pL_Node.GetData<TMyObject>;
```

I've just added a unit test for this code:
https://github.com/Virtual-TreeView/Virtual-TreeView/blob/master/Tests/VirtualStringTreeTests.pas
