### ISSUE TITLE
NodeHeight does not scale in high-dpi mode, if RootNodeCount is set before scaling happens

### ISSUE THREAD

**Issue by ottigeda** [JAM-Software/Virtual-TreeView#633]
See attached example project
If pressing Button1
- on a screen with font size = 100% the VirtualStringTree can show approx 9 nodes at once (correct)
- on a screen with font size = 125% the VirtualStringTree can show approx 11 nodes at once (too many)
- on a screen with font size = 200% the Node Text does start to overlap
  If pressing Button2 however it works as expected: regardless whats the font size the VirtualStringTree can show about 9 nodes at once

The difference between Button1 and Button2 is the position where the RootNodeCount is set.

[Projects.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/370129/Projects.zip)

Tested on Windows 10 (version1511), using Delphi 10.1 Berlin + Version 6.3.0 of VirtualStringTree.

**Comment by joachimmarder** [comment]
The problem behind "Button2" was that scaling was performed twice: First within `CreateWnd()` and `CMFontChaged()`, which call `AutoScale()` that detected that the current `DefaultNodeHeight` is too small for the current font. Then setting the parent control triggered a call to `ChangeScale()` which scaled the DefaultNodeHeight (again). This has now been fixed.

**Comment by joachimmarder** [comment]
The problem behind "Button1" is that `SetDefaultNodeHeight()` does not change the node height of existing nodes. This behavior is currently by design. The issue seen here can be circumvented easily by not creating nodes that early, but when the control is part of a form.

For changing the behavior of `SetDefaultNodeHeight()` a separate issue should be created, if truly a need for change is seen here.

**Comment by ottigeda** [comment]
I tried to do an component which derives from VirtualStringTree, which shows some static text, which the user can configure at design time. Due to nodes already get set while loading the component, I have a problem on how to circumvent this. It is because I cannot see a point where I could create the nodes later. If you have some hint for me on what I am doing wrong or how this could be circumvented, it would be very much appreciated. Anyway thanks a lot for your input! See attached component:
[VirtualTextTree.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/371301/VirtualTextTree.zip)

**Comment by joachimmarder** [comment]
> It is because I cannot see a point where I could create the nodes later. If you have some hint for me on what I am doing wrong or how this could be circumvented

You should add nodes by overriding `CreateWnd()` (after calling inherited) and not do that earlier. This applies more or less to all VCL controls. 
Please note that this is not a support forum, Asking such questions e.g. at stackoverflow.com is more suitable and might generate quicker responses.

**Comment by ottigeda** [comment]
I understand, will do. Thanks a lot for your help again!
