### ISSUE TITLE
Item height too small in high-dpi-aware application

### ISSUE THREAD

**Issue by BjHe** [JAM-Software/Virtual-TreeView#636]
If the high-dpi-aware flag in the manifest file is set, the default item height is too small when running in an high-dpi environment.

This can be reproduced with the Minimal-Demo by setting the high-dpi flag for the manifest file in the project options. 

Following screenshots have been made with 200% dpi under Windows 10, projects were compiled with Delphi 10.1 Berlin:

**Not high-dpi-aware:**
![low](https://cloud.githubusercontent.com/assets/20663899/17141767/bc4f1632-534d-11e6-9faf-38f409e70f60.png)

**High-dpi-aware:**
![high](https://cloud.githubusercontent.com/assets/20663899/17141771/c0a35aa4-534d-11e6-9119-eb5f458b5465.png)

**Comment by joachimmarder** [comment]
Which version of Virtual TreeView are you using?

**Comment by BjHe** [comment]
I tried with v6.2.2, v6.3.0 and current trunk.

**Comment by joachimmarder** [comment]
In trunk I was able to replicate the behavior in high-dpi builds only in case `toAutoChangeScale` was not set in `TreeOptions.AutoOptions`. But this is expected behavior then.

Do you have set `toAutoChangeScale` in your case?

**Comment by BjHe** [comment]
Sometimes the solution can be so simple... TreeOptions.AutoOptions set to toAutoChangeScale works great.
Thanks.
