### ISSUE TITLE
Tree inside frame inside tabsheet with constraints is squished

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#637]
Let's consider the following conditions:

A tree is inside a frame that is created at runtime whose parent is not visible immediately
The tree has minheight/width constraints that conflict with other controls constraint

Upon displaying the tree, its constraints will be set to very small values instead of resizing the frame, thus leading to a "squished" appearance. 

This comes from the fact that  `TVTHeader.RescaleHeader` calls `TVTHeader.RecalculateHeader` which triggers the `WM_WINDOWPOSCHANGED` message with "no change" flags set so that only the non client area is recomputed.
Unfortunately, inside `TControl.WMWindowPosChanged` there is a code that changes the constraints values to the current size of the control, thus overriding what has been set for those properties at design time.

You can get a test application here: http://obones.free.fr/vtv/Constraints.zip

A pull request with workaround will soon be submitted.

**Comment by obones** [comment]
Here is the pull request: https://github.com/Virtual-TreeView/Virtual-TreeView/pull/638

**Comment by joachimmarder** [comment]
Attached the sample project:
[Constraints.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/392594/Constraints.zip)

**Comment by joachimmarder** [comment]
In your sample frame you have aligned both controls as `alClient`. This is something you should not do. If I set the `Align` property of the VSTree to `alTop` the problem no longer exists.

**Comment by joachimmarder** [comment]
If I replace the `TVirtualStringTree` in your project with a `TListView` the exact same issue occurs. This shows that this is not an issue of `TVirtualStringTree` alone and so should not be fixed in Virtual TreeView code.
