### ISSUE TITLE
Single code base for Lazarus (Free Pascal) and Delphi

### ISSUE THREAD

**Issue by maciej-izak** [JAM-Software/Virtual-TreeView#641]
I think is good idea to merge https://github.com/blikblum/VirtualTreeView-Lazarus into original Virtual-TreeView repository to keep single and clear code base for Delphi and Lazarus.

**Comment by joachimmarder** [comment]
Isn't that what forks are for? The connection to the original source is still there and people who actually use Lazarus maintain the source for it.

I am happy to accept issues with pull request, but I don't think that this issue makes any sense.

**Comment by maciej-izak** [comment]
I think not github fork :) - sooner or later any fork should be merged into main project by pull request (of course "pull request" for more personal fork has no sense, but this fork is very important for the community). The code base is not small and keeping up-to-date fork is not simple task. For better compatibility is worth to merge mentioned fork.

For example I have few bug fix and patches but for Lazarus version - sending my improvements for Lazarus fork and later for this main project is problematic. 

I can help with single code base for Lazarus and Delphi. Virtual-TreeView is very important for me. I'd like to add this project as new component for http://newpascal.org and I prefer to use official source of Virtual-TreeView (with latest changes) instead of fork (but at the moment we have almost 2 different code base).

This issue is more like discussion.

**Comment by joachimmarder** [comment]
First we need to make the code bases more similar. I don't think it is a good idea to do this with a single monster pull request. Instead we should do that with subsequent pull requests, each of them should have a clear focus and appropriate commit messages. Once we have a similar code base, we can try to continue with a single code base.

> sending my improvements for Lazarus fork and later for this main project is problematic. 

Why? If you are forking from blikblum/VirtualTreeView-Lazarus and this one was forked from Virtual-TreeView/Virtual-TreeView then it should work that send a pull request to blikblum/VirtualTreeView-Lazarus and from there a pull request can be sent to Virtual-TreeView/Virtual-TreeView.

**Comment by maciej-izak** [comment]
Soon I will try to split blikblum work on small parts in my own branch (+ my patches). I am glad to hear that Virtual-TreeView is open for Lazarus modifications :)

**Comment by joachimmarder** [comment]
Will still accept pull requests and issue that make porting easier, but I am reluctant to merge changes for Lazarus or Firemonkey into the original repository, as I don't use them. The code should be maintained by someone that actually uses these frameworks / IDEs.
