### ISSUE TITLE
Build issue (C++ Builder 10 Seattle)

### ISSUE THREAD

**Issue by Eecee** [JAM-Software/Virtual-TreeView#642]
Hello!
We're experiencing build issue with the latest available build (V6.3, 17 May 2016).

First scenario (Debug configuration, Win32):
1. CBuilder 10 project was built and installed successfully with C++ Builder 10 Seattle (without Delphi personality);
2. All paths were added to the environment;
3. New VCL project with VirtualDrawTree was created (Simple drag and drop of the component);
4. Build + start results in access violation.

Second scenario (Debug configuration, Win32):
1. CBuilder XE7 project was built and installed successfully with C++ Builder 10 Seattle (without Delphi personality);
2. All paths were added to the environment;
3. New VCL project with VirtualDrawTree was created (Simple drag and drop of the component);
4. Linker produces error: Unable to open VirtualTrees.obj;
5. Manual copying of all the *.obj files to the build directory resolved this issue;
6. Application has been started successfully.

Can you, please clarify what we're doing wrong?

**Comment by joachimmarder** [comment]
> 1. Build + start results in access violation.

Could you please post the full call stack of this exception?

> 1. CBuilder XE7 project was built and installed successfully with C++ Builder 10 Seattle 

There is also a package folder named "CBuilder 10". this should be used with RAD Studio 10 Seattle.

**Comment by Eecee** [comment]
Access violation call stack:

:50034e65 BORLNDMM.@Borlndmm@SysGetMem$qqri + 0x2d
:0036675d ; ___CRTL_MEM_Revector
:003666b1 _malloc + 0xD
:0036a3f0 __unlockLocale + 0x14
:0036f981 ; __startupd
:002e1d4a ; Vtheaderpopup
:77915c71 ; ntdll.dll
:779161a5 ; ntdll.dll
:779160a7 ntdll.LdrQueryImageFileKeyOption + 0xd5
:77913659 ntdll.LdrInitializeThunk + 0x10

I can attach full proccess dump if you'd like.

**Comment by joachimmarder** [comment]
The call stack is not very readable. Is there a chance that you generate a readable using MadExcept or EurekaLog?

**Comment by Eecee** [comment]
Tried both with no luck.
Seems like installed handlers does not get any chance to catch this exception, because it happens before them. 

But, i have discovered two interesting things:
1) Another AV :) Don't worry, this is not so obscure, as the previous one. So, i have my environment (C++ Builder 10 Seattle) with installed VirtualTrees component, and simple VCL app with VirtualDrawTree on it.
This AV happens when I close my IDE completely, and reopen my simple VCL app. AV fires immediately, telling me that there is invalid write of address 00000011, and suggesting to delete VirtualDrawTree from my form.
To hunt this one, I've attached another instance of IDE to faulty one and got the following stack trace:

```
:50155e5f rtl230.@System@Classes@TList@Add$qqrpv + 0x7
:0FC26331 Virtualtrees::Clipboard::RegisterVTClipboardFormat(Description=????, TreeClass=:0FC3A798, Priority=50, tymed=1, ptd=????, dwAspect=1, lindex=-1)
:0FC4AD5C Virtualtrees::InitializeGlobalStructures()
:0FC5C014 Virtualtrees::TBaseVirtualTree::TBaseVirtualTree(Self=:0A586FB0, AOwner=:12C8CBB0, $598835220=:0CD48780)
:5016174c ; C:\Program Files\Embarcadero\Studio\17.0\bin\rtl230.bpl
:50161979 rtl230.@System@Classes@TReader@ReadComponent$qqrp25System@Classes@TComponent + 0x8d
:50161c4e rtl230.@System@Classes@TReader@ReadDataInner$qqrxp25System@Classes@TComponent + 0x8e
:50161b8d rtl230.@System@Classes@TReader@ReadData$qqrxp25System@Classes@TComponent + 0x3d
:5017004a rtl230.@System@Classes@TComponent@ReadState$qqrp22System@Classes@TReader + 0x6
:50ad24fe vcl230.@Vcl@Forms@TCustomForm@ReadState$qqrp22System@Classes@TReader + 0x6a
```

more precisely 

```
class procedure TClipboardFormatList.Add(const FormatString: string; AClass: TVirtualTreeClass; Priority: Cardinal; AFormatEtc: TFormatEtc);

// Adds the given data to the internal list. The priority value is used to sort formats for importance. Larger priority
// values mean less priority.

var
  Entry: PClipboardFormatListEntry;

begin
  New(Entry);
  Entry.Description := FormatString;
  Entry.TreeClass := AClass;
  Entry.Priority := Priority;
  Entry.FormatEtc := AFormatEtc;
  FList.Add(Entry); **<-- This line causes AV on project load.**

  Sort;
end;
```

Seems like FList is not initialized. I was unable to hit following line in my debugging session:

```
//Note - not using class constructors as they are not supported on C++ Builder.
initialization
  TClipboardFormatList.FList := TList.Create; **<-- This one**
finalization
  TClipboardFormatList.Clear;
  TClipboardFormatList.FList.Free;
end.
```

So, I attempted to remedy this AV with simple code snippet, before the adding occurs:

```
if Assigned(FList) = false then
begin
  FList := TList.Create;
end;
```

And whoala, AV is gone!
I'm not Delphi dev, and don't know all the specifics of bpl and stuff, but maybe you will find this link useful:
http://stackoverflow.com/questions/4618650/delphi-unit-initialization-not-always-called/4619000#4619000

2) This one relates to my original problem. Recently, I've come across this link: https://www.c-plusplus.net/forum/332728-full
Guy has amazingly similar call stack, also relating to borlandmm.dll. My knowledge of German language is a bit dusty, but third message states, that I have to link dynamically with RTL if code exchanges complex data types with some DLL. So, I attempted to rebuild VirtualTrees (CR230 + CD230) with "Link with dynamic RTL" checkbox set to true and BAM! No more AV! 

If you can somehow comment on this topics, it would be great. Should I leave my fixes as the are, or maybe you will investigate further? Seems like I'm the only one with those kind of problems.

**Comment by joachimmarder** [comment]
> I was unable to hit following line in my debugging session:

I analyzed some similar cases with @romankassebaum in the past in which C++ Builder did not execute the initialization part of units, which seems to be a bug in C++ Builder. We tried to report them to Embarcadero without success. We never observed something similar with the Delphi Personality.

I tried to work around this problem by not having any code in the initialization part of the units, but it seems that I missed the unit "VirtualTrees.Clpbrd". I will add a lazy getter and a class destructor to TClipboardFormatList.

I will also switch C++ Builder project files to dynamic linking. Thanks for your research and feedback!

**Comment by joachimmarder** [comment]
The code in the initialization section of unit `VirtualTrees.Clpbrd` has been removed now.

I tested this with the latest code from GitHub master on C++ Builder 10.1 Berlin with a hello-world-project and it is working fine for me now.
