### ISSUE TITLE
its not really issue but i try to draw nodes side by side can i do that ?

### ISSUE THREAD

**Issue by DRAMA22** [JAM-Software/Virtual-TreeView#644]
i asked question about it here 

http://stackoverflow.com/questions/38809201/how-to-draw-nodes-inline-in-tvirualtree/38812358

but i did not got really suitable answer i saw a a project using Tvirtuaildrawtree to draw nodes side by side

how can i do that in coding ?

**Comment by joachimmarder** [comment]
I'm sorry, but this is not a support forum, this is a bug tracker. StackOverflow.com is the best place to get support. For your task TvirtualDrawTree does not seem to be the best match. VCL's TFlowPanel could maybe do this job.
