### ISSUE TITLE
Can't link 64 bit VCL app with VirtualTreeView in C++ Builder 10.1 Berlin

### ISSUE THREAD

**Issue by eggieggi** [JAM-Software/Virtual-TreeView#645]
I am considering upgrading an app written in C++ Builder XE 2 to C++ Builder 10.1 Berlin.  As a first step, I installed VirtualTreeView as per the instructions and created a dummy VCL app with a single VirtualTree in the main form.  Ran it and everything worked fine.  Then I added a 64 bit target and I get a linker error because VirtualTreesR.lib can't be found.  There is a VirtualTreesR.lib in C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp\ (presumably the 32 bit version) but in the Win64 subdirectory there is only a VirtualTreesR.a file
I can't find anything about this issue on Google.  Does VirtualTreeView support the 64 bit compiler in 10.1?

**Comment by joachimmarder** [comment]
If you target Win64 you need to build VirtualTreesR*.bpl also for the platform "Win64". Did you do that?
Which version of Virtual TreeView are you using?
Are you using the RAD Studio Packages (.dproj) or the pure C++ Builder packages (.cbproj) of Virtual TreeView?

**Comment by eggieggi** [comment]
Thank you for the reply.  Yes I built the 32 bit and 64 bit versions of the VirtualTreesR.bpl files.  I have tried both version 6.3 and the trunk version off github.
I did not see the CBuilder package, and I assumed that since I was running RAD Studio, I only had to use the RAD studio package.  So I tried again.  Since the 30 day demo of RAD Studio had expired, I got a new serial and did a clean reinstall of RAD Studio and VirtualTreeView on a new machine.
I first tried installing the CBuilder 10.1\VirtualTreeView.groupproj according to the instructions.  When I tried building VirtualTreesCR.cbproj, I got an error saying that '....\source\hpp\Win32\Release\VTAccessibilityFactory.hpp' could not be created.  I created '....\source\hpp\Win32\Release\' and '....\source\hpp\Win64\Release\' and tried again.  This time I got "Unable to open file 'VIRTUALTREESCR.BPI'" when I tried building a dummy project.
So I tried installing the Rad Studio 10.1 version and then the CBuilder 10.1 version on top.  Both installed OK, but when I created a new project, I got an error saying that it was not possible to load package 'VirtualTreesR24' because it contains 'VirtualTrees.Utils' which is also contained in package VirtualTreesCR240'.  
Next I uninstalled both packages and reinstalled the CBuilder one and now I could create and build a project with a virtualtree but on linking I got the missing VirtualTreesR.lib error again.

**Comment by joachimmarder** [comment]
I don't use C++ Builder and I currently do not have a C++ Builder installation that I could use for testing. I guess that just the installation steps for C++ Builder are incomplete. I would appreciate if an experienced C++ Builder developer could check them.

> but on linking I got the missing VirtualTreesR.lib error again.

Is this file present on your disk? If yes, then most likely this path is missing in your library path.
Does this happen for both Win32 and Win64?

> I did not see the CBuilder package, and I assumed that since I was running RAD Studio, I only had to use the RAD studio package. 

This is correct, the RAD Studio package should work too. I was asking to see which part of the installation could be wrong.

> So I tried installing the Rad Studio 10.1 version and then the CBuilder 10.1 version on top.

You cannot install a package two times.

**Comment by eggieggi** [comment]
> > but on linking I got the missing VirtualTreesR.lib error again.
> > Is this file present on your disk? If yes, then most likely this path is missing in your library path.
> > Does this happen for both Win32 and Win64?

There is a VirtualTreesR.lib in C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp but none in the Win64 subdirectory.  VirtualTreeView works fine in 32 bit mode, so I'm guessing that if I had a VirtualTreesR.lib in ...\18.0\Dcp\Win64, it would work for 64 bit too.

**Comment by joachimmarder** [comment]
> There is a VirtualTreesR.lib in C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp but none in the Win64 subdirectory.

Is there a file `VirtualTreesR.a` in the `Win64` subfolder? If not, what files are there?

**Comment by eggieggi** [comment]
Yes, there is.  VirtualTreesR.a, VirtualTreesR.bpi and VirtualTreesR.dcp

**Comment by joachimmarder** [comment]
> Yes, there is. VirtualTreesR.a

For some reason C++ Builder seems to use the extension `.a` for Win64 builds instead of the traditional `.lib`. So we need to tell the linker for what files to look for. 

Another user wrote me that replacing

```
{$HPPEMIT '#pragma link "VirtualTreesR.lib"'} 
```

with 

```
{$HPPEMIT '#pragma comment(lib, "VirtualTreesR")'}
```

solved the problem for him. Could you please test that?

**Comment by eggieggi** [comment]
YES, YES, YES (and no).  It did not quite work, I got the same "missing virtualtreesr.lib" linker error, but if I changed it to 
`
{$HPPEMIT '#pragma comment(lib, "VirtualTreesR.a")'}
`
I got a linker error that Shell32.lib was missing.  I then commented out the 
`
{$HPPEMIT '#pragma link "Shell32.lib"'}
`
line below it, reinstalled the library and now my dummy project links and runs in 64 bit mode.  If I try to link the 32 bit version, I get an error
`
[ilink32 Error] Fatal: Unable to open file 'VIRTUALTREESR.A'
`
but since I don't plan to build a 32 bit version of my app, I personally don't care.  However, if you want to patch this in a way that works for both platforms, I'd by happy to test it, of course

**Comment by joachimmarder** [comment]
>  It did not quite work, I got the same "missing virtualtreesr.lib" linker error,

This is really strange, Embarcadero's suggest that it should work:
http://docwiki.embarcadero.com/RADStudio/Seattle/en/Upgrading_Existing_C%2B%2B_Projects_to_64-bit_Windows#.23pragma_link

>  {$HPPEMIT '#pragma comment(lib, "VirtualTreesR.a")'} 

The point according to this web page is that one should not use a file extensions. Well, I guess I will change this according to the docs.
