### ISSUE TITLE
Free Pascal compatibility

### ISSUE THREAD

**Issue by PascalRiekenberg** [JAM-Software/Virtual-TreeView#646]
Is there a chance of making Virtual-TreeView Free Pascal compatible?

**Comment by salvadorbs** [comment]
Try https://github.com/blikblum/VirtualTreeView-Lazarus

**Comment by joachimmarder** [comment]
Duplicate, see #641

**Comment by PascalRiekenberg** [comment]
Sorry. I didn't search for lazarus!
