### ISSUE TITLE
ContextMenu in MainColumn

### ISSUE THREAD

**Issue by ghost** [JAM-Software/Virtual-TreeView#651]
Version: 6.3 (using toGridExtensions and toExtendedFocus)

Right-click in !MainColumn cell => hello Mr. ContextMenu
Right-click in MainColumn cell (Image but no text) => the row is selected; you have to keep on clicking until it eventually appears... I have a patch for this for version 4.8.3 but it's really messy...

**Comment by joachimmarder** [comment]
In GitHub master I just extended the `GridDemo` of the demo project "Advanced" with a popup menu trying to replicate this issue, but without success.

**Comment by ghost** [comment]
Sorry should have been more detailed; we are using a component derived from TCustomVirtualStringTree with a GetPopupMenu override and toRightClickSelect activated (and toGridExtensions and toExtendedFocus)
If toRightClickSelect is on => GetPopupMenu is not called
If toRightClickSelect is off => GetPopupMenu is called but the FocusedNode is wrong

Right click should work like Windows Explorer ie select the node and show the context menu but that is not the case, at least not with the setup above.

**Comment by ghost** [comment]
OK, I'm able to workaround this; if I drop toRightClickSelect and do a WMContextMenu override
it's seems to work nicely aka close this issue if you like...

```
void __fastcall TCoreObjectVirtualTree::WMContextMenu(TWMContextMenu& aMsg) {
  TPoint pt(aMsg.XPos, aMsg.YPos);
  pt = ScreenToClient(pt);

  THitInfo hitInfo;
  GetHitTestInfoAt(pt.x, pt.y, true, hitInfo);
  SetFocusedNodeAndColumn(hitInfo.HitNode, hitInfo.HitColumn);
  SUPER::Dispatch(&aMsg);
}
```

**Comment by joachimmarder** [comment]
> If toRightClickSelect is on => GetPopupMenu is not called

I'm sorry, but I was not able to replicate this behavior here.

> ...close this issue if you like

OK.
