### ISSUE TITLE
Error GetCheckImageListFor on install in XE7

### ISSUE THREAD

**Issue by RicardoBer** [JAM-Software/Virtual-TreeView#655]
I just download commit f45adc0 for test issue 248, and raise an error on build VirtualtreesD21.bpl.

Line 347 on VirtualTreesReg,

ImageList := TVirtualTreeCast.GetCheckImageListFor(CheckKind);

Undeclared identifier GetCheckImageListFor.

**Comment by RicardoBer** [comment]
I found that class function
"class function TBaseVirtualTree.GetCheckImageListFor(Kind: TCheckImageKind): TCustomImageList;" disappear from VirtualTrees.pas

**Comment by joachimmarder** [comment]
I'm very sorry, this was die to issue #622. I missed to recompile the designtime package and the config of our continuous build system had a typo in my email address. Should not happen again.
