### ISSUE TITLE
Bug in minimal demo

### ISSUE THREAD

**Issue by jaclas** [JAM-Software/Virtual-TreeView#661]
I try TreeView demo: Minimal. After compiled I click several times on tree and get except:

![ashampoo_snap_2016 09 26_19h24m51s_001_](https://cloud.githubusercontent.com/assets/17312717/18845753/41befd9a-8423-11e6-892b-e8eeaee9b9eb.png)

This demo works at all bad, it is not possible selection of first visible items. 
Is errors relate to the TreeView or just this demo?

I tested on Delphi Berlin 10.1

**Comment by sanjayssk** [comment]
Problem 2) Selection problem of visible node items.
Solution: This is a problem in demo form. Please change the RootNodeCount of the tree to 0 and run. 

Problem 1) Error message. This still comes sometimes and I need to look into it some more. That's why I have not committed the above fix yet.
