### ISSUE TITLE
Bugfix: Exception when pressing return on an item with no additional columns

### ISSUE THREAD

**Issue by whookie1** [JAM-Software/Virtual-TreeView#663]
There is an exception raised, when using VirtualStringTree as a tree only (no additional columns) and pressing return-key after editing a tree-item @ the following line (VirtualTrees.pas::32867):

`Column := Tree.Header.Columns[Tree.FocusedColumn];
`

this is, because Tree.FocusedColumn is -1 at that moment!

You can fix this by changing lines 32867 to 32877:

``` pascal
          Column := Tree.Header.Columns[Tree.FocusedColumn];           <-EXCEPTION
          if Column.EditOptions <> toDefaultEdit then
            EditOptions := Column.EditOptions
          else
            EditOptions := Tree.TreeOptions.EditOptions;

         // next column candidate for toVerticalEdit and toHorizontalEdit
         if Column.EditNextColumn <> -1 then
            ColumnCandidate := Column.EditNextColumn
          else
            ColumnCandidate := -1;
```

with the following block:

``` pascal
          EditOptions := Tree.TreeOptions.EditOptions; // default
          ColumnCandidate := -1;
          if Tree.Header.Columns.Count > 0 then  // are there any columns?
          begin
            Column := Tree.Header.Columns[Tree.FocusedColumn];
            if Column.EditOptions <> toDefaultEdit then
              EditOptions := Column.EditOptions;

            // next column candidate for toVerticalEdit and toHorizontalEdit
            if Column.EditNextColumn <> -1 then
              ColumnCandidate := Column.EditNextColumn;
          end;
```

**Comment by joachimmarder** [comment]
Which version of Virtual TreeView are you using?
Are there repro steps for this issue with one of our demo projects?
Can you send a pull request or a patch file?

**Comment by whookie1** [comment]
I'm using the latest version (6.4) and I couldn't reproduce the error with one of the demo apps (maybe because they are to sophisticated). I've attached a mini-demo ripped out of my application.

I couldn't make a pull request because of the lack of rights but made one to my forked repo (but I'm fairly new to git stuff - so there is room for improvement).
[Test.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/509597/Test.zip)

**Comment by joachimmarder** [comment]
Do you have any idea if this issue was introduced in V6.4 or already existed before?

> I couldn't make a pull request because of the lack of rights but made one to my forked repo

It should be possible to create a pull request from your forked GitHub repo.

**Comment by whookie1** [comment]
Ok, the pull-request seems to work from the web-interface (tried do it with the desktop-client first).
Im not quit sure when the error occured - because that project wasn't change for a while. I started to update VirtualStringTree about 14 days ago and had another problem which was fixed a few days later. But as the error only occurs when pressing return (one can just click on another node and the changed text will be used without an error) I'm not 100% sure when that problem was introduced.

**Comment by joachimmarder** [comment]
Sorry, but something went wrong with the pull request. It did not include actual changes compared to the current state of the main repo. I guess you included the wrong commits in the pull request.

**Comment by whookie1** [comment]
Tried it again, I think this time it reflects the changes. I definitly have to use git command line instead of the GitHub-App...

**Comment by blikblum** [comment]
@joachimmarder the bug seems to be introduced in https://github.com/Virtual-TreeView/Virtual-TreeView/pull/647
