### ISSUE TITLE
Problems with item-selection

### ISSUE THREAD

**Issue by whookie1** [JAM-Software/Virtual-TreeView#667]
I was about looking into issue #626  and stumbled across very strange behavior of the tree just using original minimal-demo (without any modification):
1. Run minimal demo.
2. Left-click on '11' of the "Level 0, Index 11" item -> nothing is selected (this isn't necessary to reproduce the problem but seems to be an issue too?).
3. Click on the "Level" section of the same line.
4. The tree item "jumps away" up (don't know if this is indented but I wouldn't like it).
5. Now left-click once one row above and behind of that item (into the white space, behind "Index 10").
6. Now move the mouse back to the "Level" - part of the tree und move it up and down across the whole tree.  There seems to be a "selection" moving with the mouse - which seems to be a bug too. It's not always deterministic I had situations where some text of the items was cut off when selected (only the first 3 letters of "Level" where visible, sometimes a few rows between where left unselected).
7. Now click on any items text (eg. "Level 0, Index 16") 
8. Move the mouse to the left and click into the white space und you get a 
   'Pending and direct clearance are mutual exclusive!' assertion.

**Comment by sanjayssk** [comment]
1. This is because of the option toCenterScrollIntoView. On second thought that option doesn't belong in Minimal Demo as it causes confusing behavior. Will remove.

Other problems fixed already. See issue #661.

**Comment by whookie1** [comment]
Good point, so I removed toCenterScrollIntoView but get the same sort of errors. For easier understanding I captured what I do:

[minimal2.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/519634/minimal2.zip)

You need BZip2 support to uncompress (I'm using 7z)

**Comment by sanjayssk** [comment]
Did you take the latest Minimal demo that was committed recently? It's not in 6.4. Please do that and then see if the problem still exists. Your zip file can not be extracted properly.

**Comment by whookie1** [comment]
Ok, my repo wasn't uptodate now I can see that the problem was in Minimal demo Main.pas VSTStartDrag event.

**Comment by sanjayssk** [comment]
There is another fix in DFM too in case you are merging manually.
