### ISSUE TITLE
{$HPPEMIT '#include <ShlObj.hpp>'}

### ISSUE THREAD

**Issue by ghost** [JAM-Software/Virtual-TreeView#668]
C++Builder10.1#1/VirtualTree6.4

I'm in the process of moving away from legacy headers (aka ERROR_LEGACY_HEADER_USAGE) - could you please change:
VirtualTrees.pas
{$HPPEMIT '#include <ShlObj.hpp>'}
to
{$HPPEMIT '#include <WinApi.ShlObj.hpp>'}
or perhaps remove it (Winapi.ShlObj is in the uses section)...

**Comment by ghost** [comment]
Grrr 
{$HPPEMIT '#include &lt;ShlObj.hpp&gt;'}
to
{$HPPEMIT '#include &lt;Winapi.ShlObj.hpp&gt;'}

**Comment by joachimmarder** [comment]
> `{$HPPEMIT '#include <Winapi.ShlObj.hpp>'}`

I have no idea if the the new style including the namespace could have any negative side effects for other users, so I am putting this to discussion.

> or perhaps remove it (Winapi.ShlObj is in the uses section)...

I am aware that it should not be necessary and it would be the best solution.. But there was a C++  Builder version that did not compile properly without this $HPPEMIT. Maybe we can give it a try.

**Comment by ghost** [comment]
Well if you check the generated .hpp-file it contains:

#include &lt;Winapi.ShlObj.hpp&gt;
...
#include &lt;ShlObj.hpp&gt;

ie either you have &lt;Winapi.ShlObj.hpp&gt; or the build will fail (or am I missing something)?!?

**Comment by joachimmarder** [comment]
> Well if you check the generated .hpp-file it contains
> `#include <Winapi.ShlObj.hpp>`

For which version of RAD Studio? The solution need to work proper in XE3 (and higher).

**Comment by ghost** [comment]
> For which version of RAD Studio?
> See original comment aka Berlin10.1#Update1 aka latest version...

**Comment by joachimmarder** [comment]
> See original comment aka Berlin10.1#Update1 aka latest version...

I know, the important question is from which version of C++ Builder on your suggested change is compatible. That means, from which version on C++ Builder generates `#include <Winapi.ShlObj.hpp>` with namespaces. We don't want to break projects that are built using older versions of C++ Builder. As I don't actively use C++ Builder, this question if difficult for me to answer.

Still it might be worth trying to remove the `$HPPEMIT` as it should not be necessary at all if C++ Builder works as designed.

**Comment by ghost** [comment]
ShlObj is in the list for XE2 for what's it worth (ShlObj = Winapi.ShlObj):
http://docwiki.embarcadero.com/RADStudio/XE2/en/Unit_Names_Alphabetical_List_with_Unit_Scopes
