### ISSUE TITLE
Create sample project for C++ Builder

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#669]
It would be good to have a small sample project for C++ Builder that can be used for demonstration and testing purposes, e.g. for issues like #668.

It would br great if an active C++ Builder developer would volunteer to create and maintain such a project.

**Comment by sanjayssk** [comment]
I have made the project for Minimal in C++ Builder 10.2. It works fine in standalone mode. But if run time packages are switched on, this causes an AppCrash and the details point to BORLANDMM.DLL. This does not happen with Delphi project. It works both in Stand Alone and Run time packages mode. 

I further tried it on a simple test project. The run time package error in C++ Builder happens only if VirtualStringTree is used in the form. It doesn't happen with other VCL controls. So something is wrong in the runtime package of VTV when used with C++ Builder. Any ideas as to where should I start looking?

**Comment by joachimmarder** [comment]
This could be related to issue #695 or #642. We had some similar issues in
the past. Since I don't use C++ Builder, I can't tell you much about it.
But that should not prevent you from committing the sample project.

**Comment by sanjayssk** [comment]
Since we are going to add just one demo for our testing purposes, I will
make this folder as CBuilderMinimal under Demos itself instead of changing
the whole tree structure to make Demos/Delphi or Demos/CBuilder. Just FYI.
