### ISSUE TITLE
Error compiling VirtualTreesR18.bpl in RAD Studio XE4

### ISSUE THREAD

**Issue by pableras** [JAM-Software/Virtual-TreeView#672]
When compiling I get this error:

`[Fatal Error] The following changes are necessary to make this package compatible with other installed packages.`
`Add vclimg`

Effectively if I add _vclimg_ to the _requires_ section, the error is gone out. Please solve it into the trunk.

Thanks for your great work!

**Comment by joachimmarder** [comment]
This will be fixed soon, please use official releases only to avoid such problems.
