### ISSUE TITLE
LGPL to LGPL with static linking exception

### ISSUE THREAD

**Issue by maciej-izak** [JAM-Software/Virtual-TreeView#673]
Hi,

could we change LGPL to LGPL with static linking exception? For components/code like Virtual-TreeView regular LGPL works almost like GPL.

LGPL with static linking exception works much better for open source projects like mORMot, Lazarus and FPC. Pure LGPL is block for Lazarus integration. More info:

http://synopse.info/forum/viewtopic.php?id=2919
http://synopse.info/files/html/Synopse%20mORMot%20Framework%20SAD%201.18.html#TITL_34

**Comment by joachimmarder** [comment]
Well, I wouldn't mind changing the license, but I am not the original developer, I just adopted the project a few years ago. 

And I don't understand why MPL or LGPL should be a problem. Can you post some links that discuss this topic please?

**Comment by maciej-izak** [comment]
The problem with VTV was raised in private mailing list of core dev team of Lazarus. We are talking about including VTV as default component into Lazarus for example as basic component for online package manager (I have also few plans with VTV for Lazarus). The reason is very simple:

1. Lazarus has very strict policy about licences
2. MPL is incompatible with other Lazarus standard components and policy. MPL can't be used here
3. LGPL is often used by mistake for many open source projects (we are programmers not lawyers). LGPL **without** static linking exceptions works almost like GPL. For example VTV with "pure LGPL" could be distributed only as *.bpl or *.dll or *.so file. Can't be legally linked into final exe without complications, please read more here:

http://stackoverflow.com/questions/10130143/gpl-lgpl-and-static-linking

**Comment by joachimmarder** [comment]
OK, seems you are right, I found this on https://copyleft.org/guide/comprehensive-gpl-guidech11.html#x14-9700010.1:

> LGPLv2.1 §6(a) is the option to use when, for some reason, a shared library mechanism cannot be used. It requires that the source for the library be included, in the typical GPL fashion, but it also has a requirement beyond that. The user must be able to exercise her freedom to modify the library to its fullest extent, and that means recombining it with the “work based on the library.” If the full binary is linked without a shared library mechanism, the user must have available the object code for the “work based on the library,” so that the user can relink the application and build a new binary. 

I was not aware of that.

**Comment by mike-lischke** [comment]
If Joachim agrees we can release all future versions under a more permissive license (e.g. BSD or MIT). I don't think we can change the license for existing versions. @joachimmarder feel free to change the license to whatever you feel is appropriate, provided it's still an open source license.

**Comment by joachimmarder** [comment]
I don't really care which open source license we choose. I found the suggested "LGPL with static link exception" good because it is a "minimal invasive" change. I will leave this open for discussion for a few days and then change the license.
