### ISSUE TITLE
VCL themed scrollbar does not update correctly after adding children

### ISSUE THREAD

**Issue by ly212002** [JAM-Software/Virtual-TreeView#676]
VirtualTree component vertical scrollbar no refresh after Add node or remove node. Hope to Solve the problem

**Comment by joachimmarder** [comment]
Can be reproduced with the sample project "Advanced" on the 1st page.

**Comment by joachimmarder** [comment]
Most likely a result of the commit for #639.

**Comment by ly212002** [comment]
VirtualTree component vertical scrollbar no refresh with vcl skin, after Add node or remove node .

**Comment by ly212002** [comment]
My project can be reproduced. I upload Screenshot later.

**Comment by ly212002** [comment]
Step:
1.form with vcl skin ,Selected first node.
2.show model window,input some text,and add new node to last.
3.add new node and select and focus this new node.And then scrollbar position error.
4.problembe reproduced.

![bug](https://cloud.githubusercontent.com/assets/24491512/21102630/ea68d42a-c0b9-11e6-8649-8893cf41a181.png)

**Comment by ly212002** [comment]
Hope to solve,thanks.

**Comment by ly212002** [comment]
Advanced demo also have this problem.
My os is win7 SP1. delphi is XE10.
![bug2](https://cloud.githubusercontent.com/assets/24491512/21103852/0a615fb8-c0bf-11e6-8d5d-05bcfa8cd04e.png)

**Comment by joachimmarder** [comment]
> Advanced demo also have this problem.

Yes, see my 1st comment above.

**Comment by ly212002** [comment]
What time can fix about, please?thank you again.

**Comment by joachimmarder** [comment]
You can simply go back to an earlier version if this is urgent.
