### ISSUE TITLE
Can not install package - Undeclared identifier: 'DefaultScalingFlags'

### ISSUE THREAD

**Issue by ThomasJaeger** [JAM-Software/Virtual-TreeView#683]
I'm trying to install the latest package under **Delphi XE4** and get the following compile error:

[dcc32 Error] VirtualTrees.pas(18481): E2003 Undeclared identifier: 'DefaultScalingFlags'

Any help is appreciated.

**Comment by joachimmarder** [comment]
Thanks for reporting this. `TControl.DefaultScalingFlags` was indeed introduced in XE6:
http://docwiki.embarcadero.com/Libraries/XE6/en/Vcl.Controls.TControl.DefaultScalingFlags
