### ISSUE TITLE
Undeclared identifier 'CM_UPDATE_VCLSTYLE_SCROLLBARS'

### ISSUE THREAD

**Issue by pableras** [JAM-Software/Virtual-TreeView#684]
Dear sir

After last code update I get this error compilation:

`[dcc32 Error] VirtualTrees.pas(32657): E2003 Undeclared identifier: 'CM_UPDATE_VCLSTYLE_SCROLLBARS'`

I'm using RAD Studio XE4.

Thanks for your work!

Sincerely yours,
Pablo

**Comment by joachimmarder** [comment]
`CM_UPDATE_VCLSTYLE_SCROLLBARS` is defined in unit `VirtualTrees.StyleHooks.pas`. Most likely you have a mix of old a new VirtualTree units in your Delphi search path.

**Comment by pableras** [comment]
You're right, for some strange reason my working copy has left to synchronize with trunk and I had to delete it and download it again.

Thanks for your help.

Sincerely yours,
Pablo
