### ISSUE TITLE
Small resource leak in PrepareBitmaps

### ISSUE THREAD

**Issue by GerbenAbbink** [JAM-Software/Virtual-TreeView#686]
Theme := OpenThemeData(Handle, 'TREEVIEW');

on line 14074

is not closed with a call to CloseThemeData()

which results in a resource leak.

**Comment by joachimmarder** [comment]
The is a call to `CloseTheme()` in line 14209.

May I ask if you found the leak using a leak checking tool or through code review? At least MadExcept did not report a leak here.

**Comment by GerbenAbbink** [comment]
Actually, i found it using MadExcept. But now, i cannot reproduce the leak.
Please ignore my original message. If i see it again i will write a new
message.
