### ISSUE TITLE
DeleteNode performance issue related to re-indexing

### ISSUE THREAD

**Issue by spiril** [JAM-Software/Virtual-TreeView#687]
Executing the following code takes a long time, using the latest release of VTV :

```
procedure TForm1.Button1Click(Sender: TObject);
var li   : tList<pVirtualNode>;
    node : pVirtualNode;
begin
  vtv.rootNodeCount := 100 * 1000;
  li := tList<pVirtualNode>.create;
    node := vtv.getFirst;
    while assigned(node) do begin
      if node.index mod 2 = 0 then
        li.add(node);
      node := vtv.getNext(node);
    end;
    vtv.beginUpdate;
      // ---------
      // SLOW PART
      // ---------
      for node in li do
        vtv.deleteNode(node);
    vtv.endUpdate;
  li.free;
  showmessage('done');
end;

```

The reason for the slowness, is that DeleteNode re-indexes the tree-nodes after each function call. 

If I change the VTV DeleteNode function, so it doesn't re-index, the above code executes almost instantly.

Would it be possible to change the DeleteNode function, is it doesn't automatically re-index nodes while FUpdateCount > 0 ?

**Comment by joachimmarder** [comment]
> using the latest release of VTV :

Which version have you been using before?


> The reason for the slowness, is that DeleteNode re-indexes the tree-nodes after each function call.

I don't think that this has been changed recently.


> If I change the VTV DeleteNode function, so it doesn't re-index, the above code executes almost instantly.

But don't you have wrong indices in your TVirtualNode then?


> Would it be possible to change the DeleteNode function, is it doesn't automatically re-index nodes while FUpdateCount > 0 ?

Difficult. That would require to do reindexing in `EndUpdate()`. Since we don't know here which nodes have changed we would need to reindex all nodes, even if just a few of millions have been deleted.

Deleting entire branches in the tree using `DeleteChildren()` does not reindex the nodes. Maybe this helps when deleting lots of nodes.

**Comment by spiril** [comment]
Hi Joachim.

> Which version have you been using before?

5.5.0

> I don't think that this has been changed recently.

In 5.5.0 it was possible to call `DeleteNode()` with an optional parameter to skip reindexing.

> But don't you have wrong indices in your TVirtualNode then?

No, for the specific VTV where I use `DeleteNode()` extensively, it's not a problem.

> Deleting entire branches in the tree using `DeleteChildren()` does not reindex the nodes. Maybe this helps when deleting lots of nodes.

I don't think that will work, as the nodes that have to be deleted are all direct children to the root node (?)

Maybe a solution would be to make reindexing optional when calling `DeleteNode()` again ?

Or perhaps implement a `DeleteNodes(const nodes : tNodeArray)` method that works similarly to `DeleteSelectedNodes()` ?

**Comment by joachimmarder** [comment]
> Or perhaps implement a `DeleteNodes(const nodes : tNodeArray)` method that works similarly to `DeleteSelectedNodes()` ?

I like that idea, the necessary code can be extracted from `DeleteSelectedNodes()`.
