### ISSUE TITLE
HitInfo for OnNodeClick event may differ much from HandleMouseDown

### ISSUE THREAD

**Issue by hermannoffen** [JAM-Software/Virtual-TreeView#692]
In methods `TBaseVirtualTree.WMLButtonDown` and `TBaseVirtualTree.WMLButtonUp` (and some other method pairs) a local `HitInfo` is determined by calling `GetHitTestInfoAt`. As display may change in `HandleMouseDown` (e.g. through `ToggleNode`) it can easily occur that `XPos` and `YPos` do not describe the clicked position anymore, when `WM_LBUTTONDOWN` is handled and therefore `GetHitTestInfoAt` is called again.

I this to be considered a bug? I'm not sure if it is, but it gave me a lot of unexpected behavior when handling node click events.

My idea of a solution to this would be to memorize the `HitInfo` in `TBaseVirtualTree.WMLButtonDown` and use the very same in `TBaseVirtualTree.WMLButtonUp`.

**Comment by joachimmarder** [comment]
> As display may change in `HandleMouseDown` (e.g. through `ToggleNode`) it can easily occur that `XPos` and `YPos` do not describe the clicked position anymore

Can this be reproduced with one of the sample project? If so, could you provide the steps to do so?


> My idea of a solution to this would be to memorize the `HitInfo` in `TBaseVirtualTree.WMLButtonDown` and use the very same in `TBaseVirtualTree.WMLButtonUp`.

The mouse have been moved between down and up of the button, and `HitInfo` then would be wrong.

**Comment by hermannoffen** [comment]
1. Add this method to the _Minimal_ demo project and use it as the treeview's `OnNodeClick` event handler.
````
procedure TMainForm.VSTNodeClick(Sender: TBaseVirtualTree;
  const HitInfo: THitInfo);
var
  LHitNodeData: PMyRec;
begin
  LHitNodeData := Sender.GetNodeData(HitInfo.HitNode);

  ShowMessage(Format('Did you click Node "%s"?', [LHitNodeData.Caption]));
end;
````

2. Compile and start the program.

3. Select node _Level 0, Index 9_ by clicking on it.

4. See the message box. The view has been scrolled but the **correct** node is referenced in the message.

5. Add 5 nodes as children to node _Level 0, Index 9_. The node will be expanded.

6. Collapse node _Level 0, Index 9_.

7. Scroll to the very top.

8. Now expand node _Level 0, Index 9_.

9. See the message box. The view has been scrolled to fit all children in view and the message now incorrectly references another node (should be one of the children).

**Comment by joachimmarder** [comment]
OK, I see what you mean. This is the result of some auto-scrolling. But this is performed in `HandleMouseDown()`, and the `OnNodeClick` is fired by `HandleMouseUp()`.

The easiest solution would be to fire the `OnNodeClick` event in `HandleMouseDown()`, before doing auto-scrolling, but it is unusual to fire OnClick events and to show dialogs on mouse-down. So maybe caching the original `HitInfo` for using it later in the `OnClick` event might be the best solution.

**Comment by hermannoffen** [comment]
>> My idea of a solution to this would be to memorize the HitInfo in TBaseVirtualTree.WMLButtonDown and use the very same in TBaseVirtualTree.WMLButtonUp.

> The mouse have been moved between down and up of the button, and HitInfo then would be wrong.

One could refresh the memorized `HitInfo` on `MouseMove`. Thus it would be correct, when the user moved the cursor himself.

**Comment by joachimmarder** [comment]
My first comment applied to `OnMouseUp` that you initially referenced. The sample code you sent later was for `OnNodeClick` and I think caching `HitInfo` makes sense here, see my previous comment.

**Comment by czarau** [comment]
I think the below code now also needs to be added to procedure TBaseVirtualTree.DoFreeNode
`
  if Node = FLastHitInfo.HitNode then
    FLastHitInfo.HitNode := nil;
`

**Comment by punker76** [comment]
@joachimmarder @hermannoffen @czarau My question is maybe not related to this issue. But, how can I prevent a NodeClick event after Drag&Drop operation? I have a TVirtualStringTree and use it like a Grid with Row rearranging. If I click on a Cell I want to do some magic. But with the current implementation this magic code will also be executed after a drag&drop operation which I don't want. Any suggestions?Thx.

**Comment by joachimmarder** [comment]
@punker76 : Is this OLE or VCL dragging that you perform? From inside the tree or from another control / window?

I agree that `OnNodeClick` should not be fired in this case.
