### ISSUE TITLE
OnChange not fired when unselecting nodes

### ISSUE THREAD

**Issue by IvanLlanas** [JAM-Software/Virtual-TreeView#697]
Clicking over the empty area to unselect all selected nodes does not fire the OnChange event.
First tried to workaround it calling the OnChange event from OnClick. It worked with the left button, but not with the right one.
I'm finally fixing it with calling the OnChangeEvent from OnMouseUp.

**Comment by joachimmarder** [comment]
Which version of Virtual TreeView are you using?

**Comment by IvanLlanas** [comment]
Just updated to the last one, 6.5, a couple of hours ago when I found the issue in version 6.3. Version 6.5 had it too.

**Comment by joachimmarder** [comment]
Can be easily reproduced in Minimal demo. In `TBaseVirtualTree.HandleMouseDown()` the method `ClearSelection()` is called with `pFireChnageEvent == False`. Changing this to `True` should fix the problem.
