### ISSUE TITLE
I have not set up toMultiSelect, why is it multiple choice?

### ISSUE THREAD

**Issue by wg0517** [JAM-Software/Virtual-TreeView#704]
Why I did not set multiple elections, and compiled out of the program will appear multiple choice, and did not press Ctrl or Shift?

CB 10.1.2
VTVersion = '6.5.0';
2017-3-27 Retrieved from github

**Comment by wg0517** [comment]
Looks like # 690, it seems to wait 6.6

**Comment by joachimmarder** [comment]
> it seems to wait 6.6

Have you tried current GitHub master?
https://github.com/Virtual-TreeView/Virtual-TreeView/archive/master.zip

**Comment by wg0517** [comment]
Git once again today without this problem

**Comment by joachimmarder** [comment]
thanks for letting us know.
