### ISSUE TITLE
Integer overflow in DetermineScrollDirections when timeGetTime wraps

### ISSUE THREAD

**Issue by tweibert** [JAM-Software/Virtual-TreeView#706]
The following code in DetermineScrollDirections may cause an Integer Overflow error after an system uptime of 49.7 days, that is, when the 32-bit return value of timeGetTime wraps:

      if (Result <> []) and
        ((Assigned(FDragManager) and DragManager.IsDropTarget) or
        (FindDragTarget(Point(X, Y), False) = Self)) then
      begin
        if FDragScrollStart = 0 then
          FDragScrollStart := timeGetTime;
        // Reset any scroll direction to avoid scroll in the case the user is dragging and the auto scroll time has not
        // yet elapsed.
        if ((timeGetTime - FDragScrollStart) < FAutoScrollDelay) then
          Result := [];
      end;

Not sure, but a possible solution could be to turn off overflow checking, as demonstrated in this SO thread: https://stackoverflow.com/questions/2417919/delphi-how-to-avoid-eintoverflow-underflow-when-subtracting

**Comment by tweibert** [comment]
On a side note, the Animate procedure may have the same issue.

**Comment by joachimmarder** [comment]
> The following code in DetermineScrollDirections may cause an Integer Overflow error after an system uptime of 49.7 days

But only in case drag&drop operation is performed exactly then when the time wraps arounds, which seems extremely unlikely. Or am I missing something?

One solution could be to use GetTickCount64() once we drop XP support.

**Comment by tweibert** [comment]
FDragScrollStart is only reset to 0 in DragEnter - but that is only for **OLE** dragging, right?

Looking at the madExcept bug report, it seems that the Integer Overflow occured during a **VCL** drag operation (call stack: CMDrag -> DoAutoScroll -> DetermineScrollDirection). In that case, FDragScrollStart is never reset before the first call to DetermineScrollDirection.

In other words, the error occurs when you have an OLE drag operation, then the counter wraps, and then you have a VCL drag operation.

A possible solution would be to change the code CMDrag from

            if DragMessage = dmDragEnter then
              DoStateChange([tsVCLDragging]);

to this:

            if DragMessage = dmDragEnter then
            begin
              FDragScrollStart := 0;
              DoStateChange([tsVCLDragging]);
            end;
