### ISSUE TITLE
Strange behaviour of AutoFitColumns

### ISSUE THREAD

**Issue by Georg82** [JAM-Software/Virtual-TreeView#712]
Hello,

I'm not sure if it is a bug or a feature but the behaviour seems too strange that it could be a feature.
I want to resize all columns by `AutoFitColumns` to their full size. When I filled the component with data everything is fine, but when I want to changed afterwards the content of the cell in the first column nothing happens. The column isn't resizing. I found out that when invalidating the node before `AutoFitColumns` that the column resize correctly. I used Delphi 10.1 Berlin with version 6.5.0 (GetIt Package) of the component.

```
unit Unit2;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, VirtualTrees, Vcl.StdCtrls;

type
  TMyDataSet = record
    Name: String;
    Desc: String;
  end;
  PMyDataSet = ^TMyDataSet;

type
  TForm2 = class(TForm)
    vstTable: TVirtualStringTree;
    Button1: TButton;
    procedure FormCreate(Sender: TObject);
    procedure vstTableGetText(Sender: TBaseVirtualTree; Node: PVirtualNode;
      Column: TColumnIndex; TextType: TVSTTextType; var CellText: string);
    procedure Button1Click(Sender: TObject);
  private
    { Private-Deklarationen }
  public
    { Public-Deklarationen }
  end;

var
  Form2: TForm2;

implementation

{$R *.dfm}

procedure TForm2.Button1Click(Sender: TObject);
var
  Node: PVirtualNode;
  Data: PMyDataSet;
  
begin

  ShowMessage(IntToStr(vstTable.GetMaxColumnWidth(0, False)));  //62px
  ShowMessage(IntToStr(vstTable.GetMaxColumnWidth(1, False)));  //77px

  vstTable.BeginUpdate;
  
  Node := vstTable.FocusedNode;
  if Assigned(Node) then
  begin
    Data := vstTable.GetNodeData(Node);
    if Assigned(Data) then
    begin
      Data.Name := Data.Name + 'xyz 12345';
      Data.Desc := Data.Desc + 'xyz 12345';
    end;
  end;

  vstTable.EndUpdate;

  //Workaround or musst have?
 vstTable.InvalidateNode(Node);

  ShowMessage(IntToStr(vstTable.GetMaxColumnWidth(0, False))); //62px and 106px with the "workaround"
  ShowMessage(IntToStr(vstTable.GetMaxColumnWidth(1, False))); //127px  

  vstTable.Header.AutoFitColumns(False, smaAllColumns);
  
end;

procedure TForm2.FormCreate(Sender: TObject);
var
  Node: PVirtualNode;
  Data: PMyDataSet;
  Index: Integer;  
  
begin

  vstTable.NodeDataSize := SizeOf(TMyDataSet);
  vstTable.BeginUpdate;

  for Index := 1 to 10 do
  begin
    Node := vstTable.AddChild(nil);
    Data := vstTable.GetNodeData(Node);
    if Assigned(Data) then
    begin
      Data.Name := IntToStr(Index)+'. Bla bla';
      Data.Desc := 'Bla bla bla bla';
    end;
  end;

  vstTable.EndUpdate;

  vstTable.Header.AutoFitColumns(False, smaAllColumns); //Everything is fine, all columns have their right size
  
end;

procedure TForm2.vstTableGetText(Sender: TBaseVirtualTree; Node: PVirtualNode;
  Column: TColumnIndex; TextType: TVSTTextType; var CellText: string);
var
  Data: PMyDataSet;
  
begin
  Data := vstTable.GetNodeData(Node);
  if Assigned(Data) then
  begin
    case Column of
      0: CellText := Data.Name;  
      1: CellText := Data.Desc;
    end;
  end;
  
end;

end.
```

**Comment by joachimmarder** [comment]
> Delphi 10.1 Berlin with version 6.5.0 (GetIt Package) 

I see only V6.2.0 in GetIt. Are you sure you are using V6.5.0? Can your try if V6.6.0 fixes the problem? If not, can you please the sample project as ZIP to this issue?

**Comment by Georg82** [comment]
Yes, you're right in GetIt it's V6.2.0 but `VTVersion` in VirtualTrees.pas says 6.5.0 

I'm sorry I can't try it with V6.6.0 but please find attached sample project below.

[VST_TEST.ZIP](https://github.com/Virtual-TreeView/Virtual-TreeView/files/895369/VST_TEST.ZIP)

**Comment by romankassebaum** [comment]
I just updated the TurboPack version to V6.6.0 and asked Marco Cantu to update GetIt.

**Comment by sanjayssk** [comment]
Last week, I had analyzed this. This happens for the Main column. The reason is that Virtual String Tree stores the width of the main column in the Data pointer and there is no way to reset it except by doing InitNode recursively that calls ResetInternalData, a method specific to the derived Virtual String Tree. The solution I have in mind is to get control on BeforeAutoFitColumns event in VirtualStringTree and set a flag so that the width is recalculated in DoGetNodeWidth. Doing a ResetInternalData recursive at the beginning of a loop is another solution but it is not a good idea because it will be too expensive as it will do it for all the nodes, even those not visible.

**Comment by sanjayssk** [comment]
Fixed.
