### ISSUE TITLE
EInvalidOperation using VirtualStringTree in MDI application

### ISSUE THREAD

**Issue by MPannier** [JAM-Software/Virtual-TreeView#713]
Hello,

I get EInvalidOperation "Formular kann nicht erstellt werden. Aktuell sind keine MDI-Formulare aktiv" if I close my MDI application.

Description (see also attachment -> https://www.dropbox.com/s/qcf8hv89j630xe6/FormInFormVirtualTreeViewTest.zip?dl=0):

- I have 3 forms
- Form1.FormStyle = fsMDIForm
- Form2.FormStyle = fsMDIChild
- Form3.FormStyle = fsNormal
- on Form3 there is a TVirtualStringTree component (just dropped on the form, no properties changed, no events assigned, no data within the tree)
- Form1 creates and shows Form2
```
procedure TForm1.FormActivate(Sender: TObject);
begin
  TForm2.Create(Application.MainForm).Show;
end;
```
- Form2 creates and shows Form3 (form in form)
```
procedure TForm2.FormCreate(Sender: TObject);
begin
  F := TForm3.Create(nil);
  F.Parent := Self;
  F.Show;
end;

procedure TForm2.FormDestroy(Sender: TObject);
begin
  F.Free;
end;
```
- If the main form (Form1) is closed (system icon; application close) I get the AV
- If I remove the TVirtualStringTree component I don't get the AV
- If I close Form2 manually I don't get the AV

This is tested with the following versions:

Delphi XE3
VirtualStringTree Version V5.1.1 and V6.6
32Bit

Delphi Berlin 10.1 Update 2
VirtualStringTree Version V5.5 and V6.6
32Bit

Regards
M. Pannier

**Comment by joachimmarder** [comment]
What happens if you use  Delphi's TTreeView instead of TVirtualStringTree?
Can you post the call stack of the exception please?

**Comment by MPannier** [comment]
Hello,

thanks for Your reply.

What happens if you use Delphi's TTreeView instead of TVirtualStringTree? --> I get the same AV. 

Can you post the call stack of the exception please? --> 

:75fb4878 KERNELBASE.RaiseException + 0x48
Vcl.Forms.TCustomForm.CreateWindowHandle(???)
Vcl.Controls.TWinControl.CreateWnd
Vcl.Forms.TScrollingWinControl.CreateWnd
Vcl.Forms.TCustomForm.CreateWnd
Vcl.Controls.TWinControl.CreateHandle
Vcl.Controls.TWinControl.HandleNeeded
Vcl.Controls.TWinControl.GetHandle
Vcl.Forms.TCustomForm.SetWindowFocus
Vcl.Forms.TCustomForm.SetActiveControl(???)
Vcl.Forms.TCustomForm.DefocusControl($2944600,???)
Vcl.Controls.TWinControl.RemoveFocus(False)
Vcl.Controls.TWinControl.CMVisibleChanged(???)
Vcl.Controls.TControl.WndProc((45067, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Controls.TWinControl.WndProc((45067, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Forms.TCustomForm.WndProc((45067, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Controls.TControl.Perform(???,???,0)
Vcl.Controls.TControl.SetVisible(False)
Vcl.Forms.TCustomForm.SetVisible(False)
Vcl.Forms.TCustomForm.Hide
Vcl.Forms.TCustomForm.BeforeDestruction
System._BeforeDestruction(???,???)
:0051a6d3 TControl.SetVisible + $2B
System.TObject.Free
Unit2.TForm2.FormDestroy($29441E0)
Vcl.Forms.TCustomForm.DoDestroy
Vcl.Forms.TCustomForm.BeforeDestruction
System._BeforeDestruction(???,???)
:005b8103 TCustomForm.BeforeDestruction + $73
System.TObject.Free
System.Classes.TComponent.DestroyComponents
System.Classes.TComponent.Destroy
Vcl.Controls.TControl.Destroy
Vcl.Controls.TWinControl.Destroy
Vcl.Forms.TScrollingWinControl.Destroy
Vcl.Forms.TCustomForm.Destroy
System.TObject.Free
System.Classes.TComponent.DestroyComponents
Vcl.Forms.DoneApplication
System.SysUtils.DoExitProc
System._Halt0

Regards
Mathias Pannier

**Comment by joachimmarder** [comment]
> What happens if you use Delphi's TTreeView instead of TVirtualStringTree? --> I get the same AV.

Well, in this case the AV is not most likely related to the TVirtualStringTree control.

**Comment by MPannier** [comment]
OK. Thanks. I have create an issue here: https://quality.embarcadero.com/browse/RSP-17819

**Comment by joachimmarder** [comment]
You may also try to post http://www.stackoverflow.com
