### ISSUE TITLE
Tab key navigation does not work properly with Auto Span Columns

### ISSUE THREAD

**Issue by sanjayssk** [JAM-Software/Virtual-TreeView#716]
Tab key has exactly the same problem mentioned in issue 649 but the code is entirely different, hence a new issue. **UPDATE, May 21: Even Home and End key will get this problem if the merged columns are first or last.**

This problem was found when fixing issue 649. But the code for VK_TAB uses a completely different approach. It makes a function pointer GetNextColumn for going to the next column and assigns either the GetPreviousVisibleColumn or GetNextVisibleColumn functions to it and then uses a common logic using GetNextColumn. 

The function looks like this
`    function GetPreviousVisibleColumn(Column: TColumnIndex; ConsiderAllowFocus: Boolean = False): TColumnIndex;`

I plan to add another default parameter considerAutoSpan: Boolean = false to this and to the GetNextVisibleColumn and then implement my new logic in that flag. This will ensure 3 things:

- All the places where this function is called will continue working as before because default parameter will be off.

- I will use the third flag only for VK_TAB logic.

- This will also help reuse the same functions in earlier fixes related to autospan where local functions were introduced to do special processing. Surprisingly, this kind of function pointer logic was not used in other places otherwise, I would have caught this sooner.

**Comment by sanjayssk** [comment]
In order to test Auto Span related problems, the grid Advanced demo is to be modified often. To save time for all future issues related to AutoSpan, I'm documenting the steps to change the demo for AutoSpan.

**What Auto Span option means:** The comment in VirtualTrees.pas explains it as "Large entries continue into next column(s) if there's no text in them (no clipping)."

**Steps to change griddemo unit in Advanced Demo for Auto Span:**
1) For the tree VST5, include toAutoSpanColumns in Auto options in object inspector.

2) In VST5GetText event function, comment the existing code and put the following in its place.

```
 if column = 2 then
  begin
    cellText := 'This is a spanning line across.';
    exit;
  end;
  //No text is shown for column 3 in addition to column 0 as in original code
  if (Column > 0) and (Column <> 3) then
    CellText := Sender.GetNodeData<TGridData>(Node).Value[Column - 1]
  else
    CellText := '';
```

**How it works:**
This additionally makes the text of column 3 blank so that column 2 now auto spans to column 3.

**Comment by joachimmarder** [comment]
How about adding a checkbox to this sample that toggles between the original and the AutoSpan mode?

**Comment by sanjayssk** [comment]
Good idea. Noted.

**Comment by sanjayssk** [comment]
I have modified the grid demo to see the effect of Auto Span by a check box. Also fixed the Tab and Shift-Tab navigation for Auto Spanned column. But the original Tab logic has another problem that it doesn't proceed to next row after the last column that any grid should do. Seeing if this is something that can be fixed.

**Comment by sanjayssk** [comment]
Even the normal Tab key navigation didn't go to next row as it should for a grid. Fixed.
