### ISSUE TITLE
Node has a collapse/expand icon even if all of its children are hidden

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#717]
In a tree with two levels the first level nodes have collapse icons (+/- or an arrow) if they have children.
However, if all of their children are hidden (`VST.IsVisible[ChildNode] := False`) the collapse icon is still there without any functionality (except changing the collapse state icon).

In my case there's a user defined filter that might cause all children of a node to be hidden. In that case the collapse icon should be hidden as well (making it look like that node doesn't contain any child-nodes at all). 

Currently it's very confusing for the user, because they expect to be able to expand that node if that icon is there.

Please add an option that hides the collapse icons of that parent-node if there are no visible child-nodes.
Thank you!

**Comment by joachimmarder** [comment]
This could be related to #701. Are you using the latest V6.6 of Virtual-TreeView?

**Comment by IgitBuh** [comment]
Yes, this is present in the latest version 6.6.
Probably distantly related to #701, but definitely a different problem.
Thanks for planning it in for v6.7!

**Comment by sanjayssk** [comment]
Looked at it today and found that there is an option toAutoHideButtons in AutoOptions to get the behavior wanted. By default, this option is OFF, probably to give indication as to which nodes have children irrespective of whether all children are hidden. So the solution is to use the above option.

**Comment by joachimmarder** [comment]
> ... and found that there is an option toAutoHideButtons in AutoOptions to get the behavior wanted. By default, this option is OFF, 

Could it make sense to turn this option on by default?

**Comment by IgitBuh** [comment]
I'm afraid, but toAutoHideButtons does not work as expected. Either it's a bug or it was meant to cover a different use case. It hides not only the collapse/expand icon but also the tree lines. See fourth node in this screenshot:
![vtvhiddennodeicon](https://cloud.githubusercontent.com/assets/703571/26284973/b31d3b86-3e46-11e7-824f-39ba84448db6.png)

**Comment by sanjayssk** [comment]
@IgitBuh In my testing, this works fine with normal hiding of nodes (not filters). I suspect that your problem may be related to the filter bug. Do the same hiding with IsVisible property and then see how toAutoHideButtons works. But if you are facing the problem with IsVisible hiding itself, please send me a sample test project that shows this problem.

**Comment by sanjayssk** [comment]
> Could it make sense to turn this option on by default?

Yes, not showing the button when no children seems more intuitive.

**Comment by IgitBuh** [comment]
I'm hiding the nodes with IsVisible (see my initial posting). I've created a new project to test this from scratch and noticed that the described problem only occurs if `toUseExplorerTheme` is set to `True`. If it's set to `False` then the tree lines are drawn correctly. With this information you should be able to easily reproduce it. (My OS in this test is Win7 with the default theme.)

**Comment by sanjayssk** [comment]
Thanks for the details. I will check.

**Comment by sanjayssk** [comment]
I tested this and found that lines are not drawn around the button in Explorer theme anyway. Please see this zoomed screenshot:

![image](https://cloud.githubusercontent.com/assets/20315846/26343740/cadb8a96-3fba-11e7-8592-a21716f0ba80.png)

So when the button is removed, the background has no lines anyway. So it has something to do with the theme and may be it can't be fixed.

**Comment by IgitBuh** [comment]
I'm sorry but I don't understand what your screenshot or your comment are supposed to tell. I don't see the problem that I've described in your screenshot. I've tested it on Win7 with basic and Areo theme, and additionally on Win10.
The area left of "Level 0, Index 3" is empty which is definitely not supposed to be like that.
![hiddennodewin10](https://cloud.githubusercontent.com/assets/703571/26344838/4a6e069a-3fa1-11e7-8555-bf3dd6f95c4d.png)

I'd like to attach the demo project as a zip file, but I'm getting an error that this file type is not supported (although zip is listed). So I'm posting the relevant parts directly here.

```
TreeOptions.AutoOptions = [toAutoDropExpand, toAutoScrollOnExpand, toAutoSort, toAutoTristateTracking, toAutoHideButtons, toAutoDeleteMovedNodes, toDisableAutoscrollOnFocus, toAutoChangeScale]
TreeOptions.PaintOptions = [toShowButtons, toShowDropmark, toShowRoot, toShowTreeLines, toThemeAware, toUseBlendedImages, toUseExplorerTheme]
```

```
procedure TForm1.FormCreate(Sender: TObject);
var
  Node: PVirtualNode;
begin
  Node := VST.AddChild(nil);
  Node := VST.AddChild(Node);
  Node := VST.AddChild(nil);
  Node := VST.AddChild(Node);
  Node := VST.AddChild(nil);
  Node := VST.AddChild(nil);
  Node := VST.AddChild(Node);
  VST.IsVisible[Node] := False;
  Node := VST.AddChild(nil);
  Node := VST.AddChild(nil);
end;

procedure TForm1.VSTGetText(Sender: TBaseVirtualTree; Node: PVirtualNode;
  Column: TColumnIndex; TextType: TVSTTextType; var CellText: string);
begin
  CellText := 'Level ' + IntToStr(VST.GetNodeLevel(Node)) + ', Index ' + IntToStr(Node.Index);
end;
```

**Comment by sanjayssk** [comment]
What I mean is, it's not some bug where the "lines are removed along with the button." Instead, it's a design issue with the explorer theme where the theme background for a node with buttons is all empty. You can see that in your screenshot too. There are no lines entering the area in the node that has a button. Neither is there a line going from the button to the caption. Compare that to a regular plus, minus button node in regular mode. This is more of a design issue with the theme background code and will need more effort to diagnose and solve.

**Comment by IgitBuh** [comment]
Why not treat/draw the node with all hidden subnodes as if it doesn't have any subnodes at all? Then the design would automatically be correct.

**Comment by sanjayssk** [comment]
Instead of introducing new code, I would rather find the place that is "avoiding" to draw the lines to support the theme for any node with children. Once I find it, the condition for the auto hide option can be introduced--hopefully, in my next fixing session.

**Comment by sanjayssk** [comment]
Fixed.

**Comment by IgitBuh** [comment]
Works for me. Thank you!

**Comment by Nashev** [comment]
I have related issue or question: Can virtual tree view automatically do not display a parent node at all, when all it's child are hidden/filtered? I have easy condition to hide/filter leaf, but now I feel need to make extra loop by parents like that:
```
  vstTree.BeginUpdate;
  try
    lNode := vstTree.GetFirst;
    while lNode <> nil do
      begin
        lData := PNodeData(lNode.GetData);

        vstTree.IsFiltered[lNode] := ....;

        lNode := vstTree.GetNext(lNode);
      end;

    // Extra loop by parents to hide parents with all hidden leafs:
    vstTree.DetermineHiddenChildrenFlagAllNodes;
    lNode := vstTree.GetLast;
    while lNode <> nil do
      begin
        if (lNode.ChildCount > 0) and (vsAllChildrenHidden in lNode.States) then
          vstTree.IsFiltered[lNode] := True;
        vstTree.DetermineHiddenChildrenFlag(lNode.Parent);

        lNode := vstTree.GetPrevious(lNode);
      end;
  finally
    vstTree.EndUpdate;
  end;
```
for hide them after hiding leafs.

**Comment by joachimmarder** [comment]
> Can virtual tree view automatically do not display a parent node at all, when all it's child are hidden/filtered?

No.
