### ISSUE TITLE
Assert error in TBaseVirtualTree.DoGetImageIndex

### ISSUE THREAD

**Issue by JoeS1904** [JAM-Software/Virtual-TreeView#719]
Using Version6.6 for Delphi 10.2
The form was designed using an earlier version of TVirtualStringTree.  I uninstalled the components and installed the new package per instructions. I deleted the old events and recoded them (ongetImageIndex had changed its parameters).

[TreeTest2 Unit Code.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/988529/TreeTest2.Unit.Code.txt)

[TreeTest2_udfm.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/988552/TreeTest2_udfm.txt)

I have created a `TVirtualstringTree` and am attempting to assign images using its `ongetimageindex` event.
The VCL Form program contains the tree with two columns, the first generates captions, the second is intended to display icons reflecting the status contained in the nodeRecord.

```
> procedure TForm1.VSTGetImageIndex(Sender: TBaseVirtualTree; Node: PVirtualNode;
>   Kind: TVTImageKind; Column: TColumnIndex; var Ghosted: Boolean;
>   var ImageIndex: TImageIndex);
> var
>   NodeRec: PNodeRec;
> begin
>   showmessage ('GetImage Entered');
>   NodeRec := Sender.GetNodeData(Node);
>           if Column = 1 then
>             begin
>               case NodeRec.Status of
>                 dstOK:
>                   begin
>                     ImageIndex := 2;
>                    //showmessage ('dstOK');
>                   end;
>                 dstUpdate: ImageIndex := 3;
>                 dstOrphan: ImageIndex := 4;
>                 dstMissingParent: ImageIndex := 5;
>               else
>                 imageIndex := 0;
>               end;
>             end;
> end;
```

When I run the program, it does not display the images. Apparently `getimageIndex` is not called during initiation. If I move the mouse into the column the assert error is generated.  
 I have traced the flow through  `TBaseVirtualTree.DoGetImageIndex` to the bottom line - `FOnGetImage(Self, Node, Kind, Column, Ghosted, Index);`  

I am a bit confused by the logic in the code. ` FOngetImage` is returning the correct index (2) for the image in the imagelist and in the next line the assert is testing index < 0, a false statement to generate the assert.  If I comment out the assert I get an "access error at address ..." message.

**Comment by JoeS1904** [comment]
This assert failure also occurs when the advance demo /general page is run.

**Comment by joachimmarder** [comment]
> This assert failure also occurs when the advance demo /general page is run.

I cannot reproduce that. Did you perhaps use an old version of the project with a new version of the virtual tree? Can you please post the call stack?

**Comment by joachimmarder** [comment]
As the exception message indicates, your code does not regard the parameter `Kind`. You are providing image indices for image types for that you do not provide an image list (e.g. StateImages).

>  If I comment out the assert I get an "access error at address ..." message.

If the image list is `nil`, you will of course get an access violation.
