### ISSUE TITLE
Review initialization of a new Node for more useful default values of members like CheckType

### ISSUE THREAD

**Issue by sanjayssk** [JAM-Software/Virtual-TreeView#721]
This came from a discussion in the Issue #708, "it would be a good idea to initialize the fields CheckStateand CheckType of a new node in TBaseVirtualTree.MakeNewNode with some useful values instead of leaving them uninitialized."

The original idea was why can't checkboxes be shown just by switching on that Option. It requires additional code in the Node Initialization event. If CheckType of a node is initialized to ctCheckType as a default value then it's possible. But then, why didn't the original developer do it? There might be a reason. We should be careful before making a change.

All ideas are welcome.

**Comment by joachimmarder** [comment]
I vote for initializing `CheckState` with `csUncheckedNormal` and `CheckType` with `ctCheckBox`.

**Comment by sanjayssk** [comment]
I have done a study of the Demos from this point of view. After looking at some of the Demos, I think we should not do it because we might break some existing application. In Advanced demo, at least 3 demo forms show check boxes conditionally only for certain tree levels.  Although, by chance, they do not break because their conditions do not break with this change in my tests.

But after looking at these demos, I can now very well imagine an application that shows check box options only at the 2nd level. The root nodes only show group headings and are designed not to show check boxes. Such application will break with this modification because it will start showing check boxes even on root items. I quickly made such a test case by using Speed Demo and verified that such an application will break.

So I think, we should leave the node initialization as it is. Instead we should have an additional comment with the option toCheckSupport that suggests setting the CheckType in the event OnInitNode. The CheckState is already initialized to csUncheckedNormal as suggested by Joachim.

**Comment by joachimmarder** [comment]
> at least 3 demo forms show check boxes conditionally only for certain tree levels. Although, by chance, they do not break because their conditions do not break with this change in my tests.

But then `CheckType` must be initialized somehow, but I could not find an explicit initialization. We can discuss the initial value, but I vote doing an explicit initialization of that member.

**Comment by sanjayssk** [comment]
In MakeNewNode, the memory obtained is zeroed. Since CheckType is an Enum, the zero value gets ctNone automatically. If we want to show ctNone initialization explicitly, we can do that in InitNode before calling DoInitNode.

**Comment by joachimmarder** [comment]
> In MakeNewNode, the memory obtained is zeroed.

OK, I was not aware that `AllocMem()` zeroes the allocated memory. I think then we can close this issue.
