### ISSUE TITLE
Simplify custom header drawing while keeping default drawing

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#722]
See https://stackoverflow.com/questions/44255873/tvirtualstringtree-how-to-draw-on-header-columns-without-using-ownerdraw

**Comment by sanjayssk** [comment]
Joachim,

I have recreated the issue in one of the demos and then tried the fix. It
works. I guess, I will keep the changes local till you make a branch?

Another bug: I made a test case above where I draw some text in red to the
right. It now works fine. But except for the main column, the other columns
do not paint the text it in red. May be one of the column settings. I will
see tomorrow. Meanwhile, if you have an idea, please let me know.

Thanks,
Sanjay

**Comment by joachimmarder** [comment]
> I guess, I will keep the changes local till you make a branch?

Yes. You may create a patch file and attach it to the bug:
https://github.com/Virtual-TreeView/Virtual-TreeView/wiki/Create-a-Patch

>  Meanwhile, if you have an idea, please let me know.

Sorry, no. Never had to use custom header drawing.
