### ISSUE TITLE
Incorrect header hot painting

### ISSUE THREAD

**Issue by jackdorsey** [JAM-Software/Virtual-TreeView#726]
When there are tooltips hovering over column headers does not highlight them. Worse is the fact that another column headers stays highlighted.

**Comment by joachimmarder** [comment]
Can you attach a screenshot and supply a sample project?

**Comment by jackdorsey** [comment]
[HeaderBug.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1272888/HeaderBug.zip)
Attached is a sample.
Hover over a column header until the tooltip appears - sometimes it does not appear - you have to hover again - another issue.
Once it appears hover over another column header - the tooltip is displayed, but the highlight stays at the old location.

**Comment by joachimmarder** [comment]
> sometimes it does not appear

We should only cover one actual bug per issue. Please open a new one for this.

> Once it appears hover over another column header - the tooltip is displayed, but the highlight stays at the old location.

Confirmed. My first guesses: Either `TVTHeader.HandleMessage()`is not called for `WM_NCMOUSEMOVE`,  or `AdjustHoverColumn()` does not work as expected.

**Comment by joachimmarder** [comment]
There is an interesting comment in the code for `WM_NCMOUSEMOVE`:
```
          // We need a mouse leave detection from here for the non client area.
          // TODO: The best solution available would be the TrackMouseEvent API.
          // With the drop of the support of Win95 totally and WinNT4 we should replace the timer.
```
Maybe this is the solution for this issue.
