### ISSUE TITLE
Header not repainted after loading from stream

### ISSUE THREAD

**Issue by jackdorsey** [JAM-Software/Virtual-TreeView#727]
VirtualStringTree: Header.LoadFromStream(FileStream);
leaves the table without header.
Most likely related to other header paint issues introduced with the new header painting routines.

**Comment by joachimmarder** [comment]
Please include a sample project that allows us to quickly reproduce the bug. This can also be one of the demo projects that come with Virtual Treeview, modified to show the bug.

>Most likely related to other header paint issues introduced with the new header painting routines.

To which versions or issues do your refer exactly?

**Comment by jackdorsey** [comment]
To this:
https://github.com/Virtual-TreeView/Virtual-TreeView/issues/726

Changelog reads:   * Fixed issue #722: Simplify custom header drawing while keeping default drawing
Not sure if it is related.

**Comment by joachimmarder** [comment]
Looking at the diff I don't see why #722 should be related. But this is easy to test if there is a sample that allows to reproduce the reported bug.

It tried this:

```
var
  FileStream: TFileStream;
begin
  FileStream := TFileStream.Create('Header.vst', fmOpenReadWrite or fmCreate);
  VST2.Header.SaveToStream(FileStream);
  FileStream.Free;
  FileStream := TFileStream.Create('Header.vst', fmOpenReadWrite);
  VST2.Header.LoadFromStream(FileStream);
  FileStream.Free;
```

But the header is painted. So please respect our rules for submitting bug your can read them on the [homepage ](https://github.com/Virtual-TreeView/Virtual-TreeView) of this project and provide a sample project.

**Comment by jackdorsey** [comment]
Hello
yes I tested that too and it seems related to something else. I will investigate further and report.

**Comment by jackdorsey** [comment]
This is obsolete see my next comment
> This issue is related to Delphi due to changed event parameters that strangely were not reported on full rebuild. 
> GetImageIndexEx had a changed parameter: ImageIndex: TImageIndex changed from Integer.

**Comment by jackdorsey** [comment]
[HeaderBug.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1273883/HeaderBug.zip)
Actually I managed to reproduce this issue and it turns out to be an issue in the component.
If data is added to the tree before calling Header.LoadFromStream - the header is hidden and not repainted.
1. Start the demo - header displayed properly
2. Save the header settings - click Save buttom
3. Close and restart the app - header loading is called on statup - **the header is now missing**
4. If you click the "Resize Header" button that sets the header height the header is repainted so it is not a loading issue - it is a repainting issue.
No painting method I could find to force the header to repaint.

**Comment by joachimmarder** [comment]
There might be an asymmetry between `TVirtualTreeColumns.LoadFromStream()`/`SaveToStream()`. Those binary formats are tricky to debug, I need to see when I find time to address this.

**Comment by jackdorsey** [comment]
Hello
Please see point 4. - I believe this is a repainting issue rather than loading.

**Comment by joachimmarder** [comment]
>  I believe this is a repainting issue rather than loading.

I don't think it is that simple: A call to `Repaint()` or `Invalidate()` does not resolve the situation, and the space for the header is missing on top:

![2017-09-07 20_03_40-form1](https://user-images.githubusercontent.com/10615289/30177980-c36201f4-9407-11e7-89b5-531b691260c8.png)

**Comment by joachimmarder** [comment]
Added a call to `RecalculateHeader()` at the end of `TVTHeader.LoadFromStream()` resolves the problem. I would be grateful ifyou could do some more testing on the fix I just committed.

**Comment by jackdorsey** [comment]
I do confirm that this issue is fixed.
Thank you.
