### ISSUE TITLE
Selecting a single Node sets FocusedNode despite toMultiSelect being set

### ISSUE THREAD

**Issue by Candesco** [JAM-Software/Virtual-TreeView#729]
The error happens in TBaseVirtualTree.AddToSelection.
While TBaseVirtualTree.SetSelected checks for toMultiSelect, AddToSelection doesn't.

Current code:
`if (SelectedCount = 1) then` @ around 18280 (I have some edits in there, so I'm not sure about the exact location)

Suggested fix:
`if (SelectedCount = 1) and not (toMultiSelect in FOptions.SelectionOptions) then`

**Comment by joachimmarder** [comment]
`SetSelected()` is public accessible and so must take `toMultiSelect` into account,  `AddToSelection()` on the other hand is only protected. I don't think it is a wise decision to change this after so many years, there might be situations in which existing code relies on this implementation detail. 

It might be a good idea though to add the fact to the documentation, that `AddToSelection()` does not check for `toMultiSelect`, and so the caller must do. 

Did you find any code in Virtual Treeview that does not check for `toMultiSelect` before calling `AddToSelection()`, or did you encounter this in your own derived class?

**Comment by Candesco** [comment]
This behavior is NEW. It wasn't there in an earlier version and introduced a bug in my software. This is why I reported it.

And furthermore: SetSelected _calls_ AddToSelection, which is where this problem starts.

**Comment by joachimmarder** [comment]
> This behavior is NEW

This is an important fact to know. Please respect our rules for reporting bugs that are shown on the [project's homepage](https://github.com/Virtual-TreeView/Virtual-TreeView), they save us a lot of time. Which version are you using now and which version have you been using previously?

> SetSelected calls AddToSelection, which is where this problem starts.

This is only problem if it does not respect `toMultiSelect`. And of course I looked into the latest code of `SetSelected()` before writing my comment, and there i found:
```
     if not (toMultiSelect in FOptions.FSelectionOptions) then
            ClearSelection;
```

**Comment by Candesco** [comment]
I shouldn't have written the "new" in upper case. Just wanted to make it more visible. I think it came across as aggressive, sorry for that.

The change was introduced in 6.2.2, 6.2.1 didn't have this behavior.
The problem basically is, that it is no longer possible to select a node without the FocusNode being set since that version. Thereby executing OnFocusChanged whenever code tries to select nodes.

> This is only problem if it does not respect toMultiSelect.

It is a problem whenever you want to select multiple nodes in your code, starting from a tree that hasn't selected any nodes. If there is no selection, the number of selected nodes doesn't matter.

**Comment by joachimmarder** [comment]
> The change was introduced in 6.2.2, 6.2.1 didn't have this behavior.

Yes, the change is listed in the changelog of V6.2.2

I'm sorry, but I don't get the problem. If there is only one node selected, which node, if not the selected one, should be the focused node? What is the use case to have a focused node that differs from the only selected node?

And if there is only one node selected, I don't think the Virtual TreeView should behave differently whether or not the `toMultiSelect` flag is set in regards which node it makes the focused node.

**Comment by Candesco** [comment]
I understand where you're going with this. Of course, when the user selects a node, that node should be focused.
But when I select (multiple) nodes in my code, with the push of a button, the FocusedNode should not be set. Why? Because setting the focus raises an event which includes code that must not execute during that selection. In the past, that wasn't a problem. Now I have to do something so that the code in OnFocusChanged isn't called.

In the past, toAlwaysSelectNode was introduced for a similar scenario, just the other way around. It was accepted that having a FocusedNode should not necessarily mean that a Node has to be selected.

**Comment by joachimmarder** [comment]
> But when I select (multiple) nodes in my code, with the push of a button, the FocusedNode should not be set.

This sounds odd, and there are best practices for user interface design and accessibility that suggest that there should always be a focused item in such a scenario, especially if there are selected items one should be focused. E.g.: https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/accessibility-best-practices

_one item should always have keyboard focus._

> Because setting the focus raises an event which includes code that must not execute during that selection. 

Honestly, it shouldn't be diffcult to avoid that code from being executed: Temporarily set the event to `nil` or use a boolean flag to exit the event handler when doing your selection stuff. It would also help to know what exactly you are doing in that event handler.

> In the past, toAlwaysSelectNode was introduced for a similar scenario

The main motivation was to mock the behavior of a Windows common treeview / listview control or the Windows Explorer: If the (last) selected element is deleted, another element is selected automatically. It is difficult to do this using only event handlers in the application, and the change was too invasive to do it without an option.

Virtual TreeView already has so many options, I want to avoid adding options that are not of general interest or that can be achieved easily in a different way.

**Comment by Candesco** [comment]
> one item should always have keyboard focus.

There is a focus, but that doesn't match what will be selected and should not change when the code selects something.

> It would also help to know what exactly you are doing in that event handler.

Well, in the event handler of OnFocusChanged, the current selection is cleared and specific nodes are selected, which is why I have the issue in the first place.
I wish I could just give you a snippet, but the project is large, very complicated and I'm not at liberty to share its code. Sorry about that.

> Honestly, it shouldn't be diffcult to avoid that code from being executed

That is true, but it's something I wouldn't want to do at several places just because of a behavioral change that, quite honestly, doesn't make sense to me.
Furthermore, I wouldn't just have to deactivate the event, I would need to store and restore the FocusNode after the selection code ran. Let me give you a quick insight (PseudoCode):

`var`
`  OldNode,`
`  RunNode: PVirtualNode;`
`begin`
`  OldNode := Tree.FocusNode;`
`  Tree.OnFocusChanged := nil;`
`  try`
`    Tree.ClearSelection;`
`    RunNode := Tree.GetFirstNoInit;`
`    while Assigned(RunNode) do`
`    begin    `
`      Tree.NodeSelected[RunNode] := MatchesCriteria(RunNode);`
`      RunNode := RunNode.NextSibling;`
`    end;`
`  finally`
`    Tree.FocusNode := OldNode;`
`    Tree.OnFocusChanged := TreeOnFocusChanged;`
`  end;`

See what I mean? Sure, it's not hard to do at all, but it's quite some overhead for something so simple.

**Comment by joachimmarder** [comment]
> ... change that, quite honestly, doesn't make sense to me.

Well, at least in the past 18 months nobody else complained and I think I explained why it makes sense as default behavior.

So the remaining question to me is if this use case, which is till quite unclear, is so generic that it justifies another tree option. I flagged this issue as "Open for discussion" earlier to get the opinion of other users.

Another option is to derive your own class. I do this too in TreeSize in order to keep some of my specific needs out of the general code, which would make it even more difficult to maintain.

> in the event handler of OnFocusChanged, the current selection is cleared and specific nodes are selected

I would have expected such code in the OnClick or OnChnage event.

**Comment by Candesco** [comment]
> I think I explained why it makes sense as default behavior.

Well, you explained why it makes sense when the user is interacting with the UI and I totally agree with you there. However, I rather dislike it when a component does more than it is supposed to when I do something as a developer. If I, as a developer, want to change the FocusNode, I do so. Currently, I have that taken away from me when working with selections.
A good way to determine if it is a user interaction or code would be to use BeginUpdate / EndUpdate.

> I would have expected such code in the OnClick or OnChnage event.

OnFocusChanged provides the Node that is now focused. The selection is based on that node.

> Another option is to derive your own class.

Sure, there are several options. I've already changed the project to use another solution. But I still think that this is a valid point and should not be ignored. That's why I posted this issue.

**Comment by joachimmarder** [comment]
> But I still think that this is a valid point and should not be ignored. 

What matters is, if this is of general interest. Yes, we could add another option, and there were dozens of similar cases in the past in which we could have added an option too. But honestly: Do you think Virtual TreeView would have truly benefited if we did so? And someone in the end has to maintain the code and make sure that every combination of options works as expected.

> A good way to determine if it is a user interaction or code would be to use BeginUpdate / EndUpdate.

That sounds interesting. I wonder: Is in your scenario, after you updated the selection, the focused node among the selected nodes, or is the focused node unselected?

**Comment by Candesco** [comment]
Well, I'm not completely sure (the code in question wasn't my design, but that of a coworker), but I think it's unselected.

**Comment by joachimmarder** [comment]
Sorry, but i sounds rather odd to have focused and selected out of sync that way. I vote against adding special code or options to achieve this, as this violates best practices for UI design and accessibility and seems rather specific. I will leave this issue open for some weeks to allow other comments.

**Comment by joachimmarder** [comment]
I verified that using `Selected[]` to select a node does not fire the `OnFocusChnage` event if a multi-selection is performed. I therefore think everything works as designed.
