### ISSUE TITLE
Remove property HintAnimation

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#730]
I don't think it makes sense to have those fancy hint animations in Virtual TreeView that no other Windows or VCL control has. The code needed is old and looks not very cleanly designed. I guess many of the methods of TVirtualTreeHintWindow don't need to be overriden any more if hints are not animated but can simply rely on the base class THintWindow.

**Comment by freimatz** [comment]
Never uses. Remove this unneccessary s... :-)

**Comment by IgitBuh** [comment]
I see absolutely no sense in custom hint animations. To me they're irritating.

**Comment by pyscripter** [comment]
Go ahead and remove it.  There are way too many options in VT.

**Comment by joachimmarder** [comment]
It would also make sense to move `TVirtualTreeHintWindow` to a new unit. Maybe one day we can get rid of this stuff and just use the VCL `THintWindowClass`.

**Comment by joachimmarder** [comment]
Not possible to move TVirtualTreeHintWindow to other unit, It access protected symbols HintMode, DoGetHintKind, DoDrawHint, VclStyleEnabled, FStates, DoStateChange, DoPaintText,  DoGetNodeToolTip, DoGetNodeHint, TextMargin, Margin, FLastHintRect, ...
