### ISSUE TITLE
DefaultText property ignored in 6.7.0

### ISSUE THREAD

**Issue by raelb** [JAM-Software/Virtual-TreeView#734]
Set RootNodeCount = 30. Run App.

Result:
![image](https://user-images.githubusercontent.com/13108198/31782240-b1bf5046-b4fa-11e7-8bd0-4486cf2a1bc9.png)

Occurs in XE4 and Tokyo.
6.7.0

**Comment by sanjayssk** [comment]
Made a fix such that making CellText empty should also work in case someone intentionally wants to display empty cell there.
