### ISSUE TITLE
Export problem when OnBeforeNodeExport is not assigned

### ISSUE THREAD

**Issue by Brnoch** [JAM-Software/Virtual-TreeView#737]
the line 313 of VirtualTrees.Export causes a problem when the event is not defined:

`CrackTree.OnBeforeNodeExport(CrackTree, etHTML, Run);`

if I add a condition, everything's fine 👍 
```
      if Assigned(CrackTree.OnBeforeNodeExport) then
        CrackTree.OnBeforeNodeExport(CrackTree, etHTML, Run);
```

**Comment by joachimmarder** [comment]
Thanks for reporting this. The if condition 5 lines above looks strange too, here is a check for `Assigned(CrackTree.OnBeforeNodeExport)` but it does not make much sense here.

**Comment by Brnoch** [comment]
Thanks a lot for the fast fix.
