### ISSUE TITLE
Ugly drawing of selection in report mode when VCL Styles are used

### ISSUE THREAD

**Issue by luebbe** [JAM-Software/Virtual-TreeView#743]
When VCL styles are enabled, the highlight/selection of the treeview looks very ugly in report mode.

![2017-11-29 11_29_38-demo](https://user-images.githubusercontent.com/3872576/33371965-ac707a62-d4fc-11e7-8a58-9d5c1fa5a6b0.png)
I'm specifically talking about the black/white rectangles around the indivdual columns and the selection

It looks like the general behaviour doesn't depend on the particular VCL style. Only the colors change. I have attached a demo project that uses 'Amakrits' and the result is just the same, only the rectangles are white now.

![2017-11-29 12_07_39-form4](https://user-images.githubusercontent.com/3872576/33372382-2149aa92-d4fe-11e7-8768-f32ef030878f.png)

Test Project: [vstTest.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1513541/vstTest.zip)

**Comment by luebbe** [comment]
I submitted a PR that fixes the "white rectangle" problem when VCL styles are enabled for both screenshots above. The black rectangles in the first screenshot were caused by using a "too old" version of VirtualTreeView in my test application.

**Comment by joachimmarder** [comment]
Thanks for the PR, grid mode looks much better now with VCL themes.

**Comment by luebbe** [comment]
As a sidenote, I might also take a look at the highlight font when VCL Styles are enabled. I guess the real highlight font in Amakrits is not the same, almost unreadable, gray as the normal font.
