### ISSUE TITLE
Is toEditOnDblClick meant to work?

### ISSUE THREAD

**Issue by raelb** [JAM-Software/Virtual-TreeView#747]
Hi,

I have set `toEditOnDblClick` to True, and `toEditOnClick` to False. In this case Editing of node does not work.

![image](https://user-images.githubusercontent.com/13108198/33850548-df475400-debc-11e7-841d-24608052e34f.png)

Has this actually not been implemented?

Attached Test Project (using 6.7)

[VST DblClick Edit.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1549171/VST.DblClick.Edit.zip)

**Comment by joachimmarder** [comment]
You have also set `toToogleOnDblClick`, which has higher priority than `toEditOnDblClick`. You need to decide.

I am going to clear `toToogleOnDblClick` in case  `toEditOnDblClick` is newly set, that should avoid such confusion.
