### ISSUE TITLE
Per Monitor Dpi Scaling - Scrollbar Not Correct after Dpi Change

### ISSUE THREAD

**Issue by rgdawson** [JAM-Software/Virtual-TreeView#748]
Using VirtualTreeView 6.7 and Delphi 10.2.1.  After a virtual TreeView scales on Dpi changed, the scaled VirtualTreeView does not scroll correctly.  To see, run the Simple Virtual Treeview demo as is (Enable High DPI is enabled).  It starts up with 20 items in its list: "Level 0, Index 0 .. "Level 0, Index 19".  When I drag the window to a monitor set at 150%, the treeview scales, but the scrollbar no longer allows me to scroll from top to bottom.  It seems as though the vertical range of the scrollbar is off.

**Comment by joachimmarder** [comment]
Confirmed.

**Comment by rgdawson** [comment]
Yeah!  That was fast.  That fixed it.
