### ISSUE TITLE
Build Error with XE3 packages

### ISSUE THREAD

**Issue by kalapanga** [JAM-Software/Virtual-TreeView#749]
From INSTALL.txt:
1. Open the project group "Packages\RAD Studio XE*\VirtualTreeView.groupproj"
2. Right click on "VirtualTreesD*.bpl" and click "Install"

After these steps, I get an error:
[dcc32 Fatal Error] VirtualTreesR.dpk(1): E2225 Never-build package 'VirtualTreesR' must be recompiled
[dcc32 Fatal Error] VirtualTreesD.dpk(36): E2202 Required package 'VirtualTreesR' not found

Delphi XE3, Virtual Treeview V6.7 and V7.0

**Comment by joachimmarder** [comment]
I don't have XE3 installed at the moment. The XE3 packages worked as expected in newer Delphi versions, so it might be a bug in XE3.

Obvious workaround: After step 1. right click on `VirtualTreesR.dpk and choose "Build".

**Comment by kalapanga** [comment]
After successfully building the VirtualTreesR.dpk, I get the same error when I try to install the VirtualTreesD.bpl
I think the problem is in the properties of packages.

**Comment by joachimmarder** [comment]
I edited the `VirtualTreesR.dproj` file. Would you mind trying again the GitHub master?

**Comment by kalapanga** [comment]
Negative result. Same error.

**Comment by kalapanga** [comment]
The problem is solved by adding in local options of both packages "$(BDSCOMMONDIR)\dcp" to the Search path (in additional to "..\\..\source").
