### ISSUE TITLE
Broken load from version V5.2.2

### ISSUE THREAD

**Issue by jackdorsey** [JAM-Software/Virtual-TreeView#751]
Can not load old streams.

**Comment by jackdorsey** [comment]
The issue seems to be in this code:

        // Load base chunk's body (chunk header has already been consumed).
        if Version > 1 then
          Stream.Read(ChunkBody, SizeOf(ChunkBody))

ChunkBody is 2 bytes larger. Have not checked which field has grown yet.

**Comment by jackdorsey** [comment]
// Be careful when adding new states as this might change the size of the type which in turn
  // changes the alignment in the node record as well as the stream chunks.
  // Do not reorder the states and always add new states at the end of this enumeration in order to avoid
  // breaking existing code.
  TVirtualNodeState = (

I believe someone was not reading the comments and added this: **vsInitializing**

**Comment by jackdorsey** [comment]
Yeah great:
https://github.com/Virtual-TreeView/Virtual-TreeView/commit/69f483c179eef236b5b82cd3af03dac55684ee64#diff-f0e42fc71610dd3d1ac9a5e4a9cdde2f

**Comment by jackdorsey** [comment]
How to fix this now? :(
TVirtualNodeStates has grown 2 bytes because of that and we have to keep forward compatibility too.

**Comment by joachimmarder** [comment]
Isn't this a duplicate of #724?

Does this report apply for V6.7.0 or for GitHub master?

**Comment by jackdorsey** [comment]
Hello Joachim
No it is not.
I managed to load the old stream by hardcoding some variable sizes. This is necessary as the new structures may be and are different and SIZEOF can not be used:
          if Version = 2 then
          begin
            Stream.Read(ChunkBody, 10);
//here we skip the new 2 bytes
            Stream.Read(ChunkBody.Align,1);
            Stream.Read(ChunkBody.CheckState,1);
            Stream.Read(ChunkBody.CheckType,1);
            Stream.Read(ChunkBody.Reserved,4);
          end
          else
          begin
            Stream.Read(ChunkBody, SizeOf(ChunkBody));
          end;

This loads old streams fine, but as I noted the stream version is not changed at the time this issue was introduced and there is no way to distinguish between the 2 streams.
I will either add a class member as a flag or a default variable bUseOldStreamFormatInLoad so that one can use the above code when needed. The flag should be used instead of the version check above.
I recommend using the TREE VERSION variable as the stream version as this will prevent such situations from happening again as the version for every build will be different and even if something is broken backward compatibility can be easily achieved by adding some code that handles the old version. I personally do this for other streams and it works quite well in such situations.

**Comment by joachimmarder** [comment]
I'm sorry, I had a typo in my comment, I meant #724 not #729,

**Comment by joachimmarder** [comment]
> I recommend using the TREE VERSION variable as the stream version as this will prevent such situations from happening again

A unit test that covers streaming a virtual tree would be the best solution, as ensures that it is effectively working. Other changes might break streaming support as well. It would be great if someone that actually uses the streaming support could add this unit test to the existing project.

**Comment by jackdorsey** [comment]
Hello  Joachim
this is not duplicate (I see you added label) - I just commented in the commit where this issue was introduced. This should stay as BUG.
I have already fixed it and I will attach the file or shall I commit via a PULL request? I do not use github much.

**Comment by joachimmarder** [comment]
Hi Jack.

> this is not duplicate

Both bugs state that streaming format became incompatible due to the introduction of `vsInitializing`. Can you explain the difference please?

Sorry, but I never used that code and never took a look at it after taking over the project.

> shall I commit via a PULL request?

A pull request is much appreciated. A patch-file based on the latest code is also fine, I've compiled some  instructions how to create this: https://github.com/Virtual-TreeView/Virtual-TreeView/wiki/Create-a-Patch

**Comment by jackdorsey** [comment]
This is the "feature" that broke the code and where I commented:
https://github.com/Virtual-TreeView/Virtual-TreeView/commit/69f483c179eef236b5b82cd3af03dac55684ee64#diff-f0e42fc71610dd3d1ac9a5e4a9cdde2f

while this thread is a BUG report. 
Closing this one or marking it as duplicate will loose the bug report as this issue is not resolved.

**Comment by joachimmarder** [comment]
You got me wrong, I was not referring to the commit: I am quite sure bug #724 is the same as this bug.

**Comment by jackdorsey** [comment]
Hello
yes this is a duplicate indeed. I was going to make a pull request, but I see this was already fixed:
https://github.com/Virtual-TreeView/Virtual-TreeView/commit/c22f4c0f75dfdcce6de90ce216c7eec02d6003cc
I like that fix better than mine as it does not require any flags. Good code from  [Candesco](https://github.com/Candesco)
Thank you!
