### ISSUE TITLE
TBaseVirtualTree.DoGetImageIndex assertion

### ISSUE THREAD

**Issue by nminkov** [JAM-Software/Virtual-TreeView#755]
Hello, 

At the end of TBaseVirtualTree.DoGetImageIndex there is an assertion that enforces valid image list to be returned if ImageIndex is not negative. In reality it enforces VirtualTree.Images and StateImages to be both set if ImageIndex is set which is not always wanted from upper lever code. 

E.g. In some cases Images is set, but not StateImages, because we don't care about it (or the other way around). Some times both image lists are not set because code is still in work, or image lists are not ready for production (or never will be).

Anyway, this enforcing is very interesting, but depends from actual use case. Best is to have VirtualTree property (disabled by default) that will enforce it, if user request it. That is, one use case does not apply to everyone.

Here is my patch disabling the assertion and also fixing TBaseVirtualTree.GetImageSize() which expects valid ImageList.

[getimageindexpatch.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1698318/getimageindexpatch.txt)

**Comment by joachimmarder** [comment]
> At the end of TBaseVirtualTree.DoGetImageIndex there is an assertion that enforces valid image list to be returned if ImageIndex is not negative. In reality it enforces VirtualTree.Images and StateImages to be both set if ImageIndex is set which is not always wanted from upper lever code.

No, it only enforces that you to not supply an images index >= 0 if no ImageList is availbale for that ImageKind. What sense does it make to calculate an ImageIndex if there is no ImageList?

**Comment by nminkov** [comment]
No, but it can happen that GetImageIndex() is set but tree.Images not, or tree.Images set but not tree.StateImages. Its not normal to assert in that case. Its more of warning situation, but not an assertion.

**Comment by joachimmarder** [comment]
> No, but it can happen that GetImageIndex() is set but tree.Images no

The assertion does not check whether or not OnGetImageIndex is assigned. It just checks if the event handler returned inconsistent data, e.g. an ImageIndex with an ImageList `nil`.

>  Its more of warning situation, but not an assertion.

It is only an assertion that is not compiled into release builds.

**Comment by nminkov** [comment]
Not really, if State image is requested and StateImages is not set, because OnGetImageIndex() does not check what kind of image is needed, because it just set and cares about "Images" and does not want to deal/care with/about "StateImages", code will assert because "ImageIndex" is set, but "StateImages" is not set. That's my case. I have existing codebases that has that issue on several occasions.

This assertion currently forces code to  deal with actual kind, code that previously considered that if not setting StateImages, dealt with that already. 

Again, I understand very well the utility the assertion, but it must be optional.  Assertions are for show conditions, programming errors. This is not the case.

One way eventually fix it, is to declare some kind of StrictMode, if in strict mode, all this kind of checks, requirements can be enforced.

Thanks

**Comment by joachimmarder** [comment]
> does not want to deal/care with/about "StateImages", code will assert because "ImageIndex" is set, but "StateImages" is not set

But your code does care by setting a StateImageIndex instead of simply not taking care of that ImageKind.

The main reason why this assertion is that we had many support cases and opened issues because people did not take the ImageKind into account in their code and got unexpected results because wrong / too many images were painted.

The by far simplest and cleanest way to fix this is code like this in the first line of your event handler:
`if ImageKind in [ikState, ikOverlay] then exit;`

**Comment by nminkov** [comment]
I understand the reason you put the code there, but for me it's like using a hammer to kill a fly. Assertion are not made for that. Just not the right tool for the problem. You can use debug logging for that purpose. That is, logging to debug console will be better. 

At the base of my issues, is that it forces me to change my existing code base, that is, I can't just plug&play the VirtualTree. I very much appreciated the previous flexibility, but again, understand it can bring confusion.

Thanks Joachim

**Comment by nminkov** [comment]
Another issue. If the assertion is only in Debug (correct?) , that means TBaseVirtualTree.GetImageSize()  will cause access violation in release without the change I posted.

**Comment by joachimmarder** [comment]
> Assertion are not made for that. 

Assertion are made to discover inconsistent states. And to request that ImageIndex 4 of ImageeList `nil` is painted is clearly an inconsistent state.

> At the base of my issues, is that it forces me to change my existing code base,

We are talking about one additional line of clean and easy code here.

**Comment by joachimmarder** [comment]
> Another issue. If the assertion is only in Debug (correct?) , that means TBaseVirtualTree.GetImageSize() will cause access violation in release.

Well, if you return an ImageIndex >= 0 for `TImageKind.ikState` but supply `nil` as StateImages then this would happen. 

So it could make sense to change the assertions to an exception.

**Comment by nminkov** [comment]
(This forces me to change many projects, which may may not have state images, so I must always check that in the code, its way too strict for my taste)

**Comment by nminkov** [comment]
Actually its a bigger of issue, I can't test if StateImages is assigned from OnGetImageIndex(TBaseVirtualTree* pSender....) because StateImages  is protected under TBaseVirtualTree.  So I specifically must cast to the right tree and that's not good because this function must be independent from that.

The entire point of this bug report is that this assertion brings more trouble that it fixes, at least for me and probably any old tree user.

**Comment by joachimmarder** [comment]
> This forces me to change many projects

This change was made a long time ago. And the necessary change made those projects who needed it actually better, because they no longer calculate image indexes that are not needed.

> because StateImages is protected under TBaseVirtualTree

You logic should not depend on whether or not a property is assigned in a control.

> The entire point of this bug report is that this assertion brings more trouble that it fixes, at least for me and probably any old tree user.

I'm sorry for that. But I disagree when looking at the whole picture. E.g. those beginner support requests about wrongly painted images decreased to zero.
