### ISSUE TITLE
Header popup menu opens twice

### ISSUE THREAD

**Issue by nminkov** [JAM-Software/Virtual-TreeView#757]
Me again.

We found that the header popup menu is opened twice when right clicked.

In WM_NCRBUTTONUP handler,  FColumns.HandleClick(P, mbRight, True, False); is called which opens the menu once , then few lines down Menu.Popup(XCursor, YCursor); opens it a second time.

**Comment by joachimmarder** [comment]
We should merge the code from `WM_NCRBUTTONUP` into `TVirtualTreeColumns.HandleClick()`

**Comment by nminkov** [comment]
Agree, it seems to be the best way
Thanks

**Comment by joachimmarder** [comment]
Done. Would you mind to test the fix? I tested it in our TreeSize Professional and there it worked without problems.

**Comment by nminkov** [comment]
It works ask expected. Thanks!
