### ISSUE TITLE
AutoFitColumns should not make column smaller than header caption

### ISSUE THREAD

**Issue by alexmitev81** [JAM-Software/Virtual-TreeView#763]
AutoFitColumns determines the new width of the column(s) based on the width of the items in the tree only, which can result in a partially or fully invisible column header text. 
I think the new column width should not be less than the space required to display the full column header text and sorting image.

**Comment by joachimmarder** [comment]
Maybe we need to make this an option, I am not sure if everybody agrees to that.

**Comment by alexmitev81** [comment]
Three more arguments to my point:
1. this is the behaviour of Windows Explorer
2. the sort image might also get hidden, making it hard to determine which column is currently sorted
3. when the tree is empty, auto-resizing a column or all columns makes them too small (hiding the sort image also). While if we take into account column text and sort images, auto-resizing will look much better in this case.

**Comment by IgitBuh** [comment]
If you do this, please make it optional. In some cases it's more important to get as many columns as possible into view than to see the full headers. But I understand that in other cases the full column headers might be more important.
Regarding your arguments 2 & 3: Just set Header.Columns.MinWidth to a value that doesn't hide the images.

**Comment by lyynxx** [comment]
I agree with @alexmitev81 that this would be a very helpful feature. 
In my local copy of VST, I've added this feature as part of the header options so it can be easily activated/deactivated. Took less than 20 lines of code in total.
It would be great to see this in the official repo.

**Comment by joachimmarder** [comment]
> It would be great to see this in the official repo.

Why not send a pull request?

**Comment by lyynxx** [comment]
Change suggested and was pulled into the master branch.
Thanks @joachimmarder
