### ISSUE TITLE
When toAlwaysSelectNode is on, no node is auto-selected after the tree is cleared

### ISSUE THREAD

**Issue by alexmitev81** [JAM-Software/Virtual-TreeView#764]
I have two remarks about the toAlwaysSelectNode option:
1. When it is on, and I fill the tree with data, the first node is auto-selected, which is OK. Howver when I clear the tree and fill it with data again, the first node doesn't get auto-selected. I think this is a bug.
2. I think clicking below the last node should clear the selection even when toAlwaysSelectNode is on. This is the behaviour of Windows Explorer.

**Comment by joachimmarder** [comment]
1. Agreed
2. Disagreed. The idea of this option is that the developer can be sure that _always_ a node is selected. My Windows 10 Explorer keeps the selected folder selected if I click in the white-space below the bottom-most treenode.

**Comment by alexmitev81** [comment]
2. I guess in depends on the usage. I'm using the component as a list view, in which case Explorer removes the selection from the right pane. Maybe we can use the toReportMode option to decide whether to clear the selection?

**Comment by joachimmarder** [comment]
>  I'm using the component as a list view, in which case Explorer removes the selection from the right pane.

Well, Windows Explorer's right pane does not seem to be in a kind of "always select node" mode, it does not even auto-select the first node. So you are comparing apples and oranges. The left pane of the Windows Explorer is more a template for this.

> Maybe we can use the toReportMode option to decide whether to clear the selection?

In most cases it won't make a difference for this option whether or not the tree has columns.

And this would contradict the meaning of the option to**Always**SelectedNode. If you use this option just to select the first node after filling the list, as you wrote in your first comment, then this can also be achieved using a single line of code. It would be far more difficult to ensure that always a node is selected if you have a tree with columns and the option would behave like you suggested.

**Comment by alexmitev81** [comment]
Ok, I agree on this. Now I remembered why I started using the toAlwaysSelectedNode - because the tree doesn't select the next node after deleting the currently selected node. So, to summarise, we have 2 independent bugs:
1. when toAlwaysSelectNode is on, no node is auto-selected after the tree is cleared
2. when toAlwaysSelectNode is off and the selected node is deleted, no node gets selected

**Comment by joachimmarder** [comment]
> because the tree doesn't select the next node after deleting the currently selected node. 

Yes, this is the long time standard behavior of Virtual TreeView and was the main motivation for me to introduce the `toAlwaysSelectedNode` flag.

> when toAlwaysSelectNode is on, no node is auto-selected after the tree is cleared

OK, we should use this issue to address this bug.

> when toAlwaysSelectNode is off and the selected node is deleted, no node gets selected

I don't think that is a bug but the expected and default behavior.

**Comment by alexmitev81** [comment]
> when toAlwaysSelectNode is off and the selected node is deleted, no node gets selected
> 
> I don't think that is a bug but the expected and default behavior.

Then maybe we should add a new flag (named e.g. `toAutoSelectNode`) that will auto select a node when the selected node gets deleted and `toAlwaysSelectNode` is off.

I also noticed a 3rd issue:

3. when `toAlwaysSelectNode` is off, I think clicking below the nodes in the tree should clear the selection

**Comment by joachimmarder** [comment]
> then maybe we should add a new flag (named e.g. `toAutoSelectNode`)

Sorry, but I strongly vote against further flags that differ only slightly from existing flags. VTV already has a confusing number of flags that are hard to understand and it is difficult to respect all combinations properly in the code.

> when toAlwaysSelectNode is off, I think clicking below the nodes in the tree should clear the selection

Agreed. Please open a new bug, we should not mix different bugs in one issue.

**Comment by joachimmarder** [comment]
Easy repro: Use unit `SpeedDemo` of `Advanced` sample, set `toAlwaysSelectNode` to `True`. Fill roots, clear the list, fill roots.

**Comment by transmogrifix** [comment]
The apparent solution for this issue has introduced a regression. 
The call to UpdateNextNodeToSelect will call GetFirstChild, which in turn will call InitChildren ( which will call OnInitChildren ) for a node with vsHasChildren in Node.States. 

This behavior is unacceptable for several reasons, but the biggest one is that the tree will call Clear on destruction and Clear will attempt to initialize children of the node. 

For example, look at this stack trace of a form being closed:
```
Mm.Client.CategoryListNew.TcatListNewF.vstInitChildren($7FD1C190,$7E8CAF40,0)
VirtualTrees.TBaseVirtualTree.DoInitChildren($7E8CAF40,0)
VirtualTrees.TBaseVirtualTree.InitChildren($7E8CAF40)
VirtualTrees.TBaseVirtualTree.GetFirstChild($7E8CAF40)
VirtualTrees.TBaseVirtualTree.UpdateNextNodeToSelect($7E8CAF40)
VirtualTrees.TBaseVirtualTree.DoFreeNode($7E8CAF40)
VirtualTrees.TBaseVirtualTree.DeleteNode($7E8CAF40,False,True)
VirtualTrees.TBaseVirtualTree.DeleteChildren($7F9940A0,True)
VirtualTrees.TBaseVirtualTree.Clear
VirtualTrees.TBaseVirtualTree.Destroy
VirtualTrees.TCustomVirtualStringTree.Destroy
Vcl.Controls.TWinControl.Destroy
Vcl.Forms.TScrollingWinControl.Destroy
Vcl.Forms.TCustomForm.Destroy
```
At that point, all the data which was used to populate the VST is already freed so it can not be used to initialize children again, and why would it, the form is being destroyed.

**Comment by joachimmarder** [comment]
Yes, it obviously does not make sense to choose one of the children of a node as next node to select if the node is about to be deleted. We could check the node for the `vsDeleting` flag.
