### ISSUE TITLE
Incorrect HotTrack with Touch-Scrolling

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#766]
To reproduce this problem you'll need a touchscreen.
Open the PropertiesDemo in the Advanced project in the latest version.
Enable these VTV-PaintOptions:
* toHotTrack
* toUseExplorerTheme
* toDisbaleDrawSelection

Enable these Touch options:
* igoPanSingleFingerVertical
* (igoPanInertia)
* igPan
* igPressAndTap

Run the demo, make the window smaller (so there's more to scroll), ~~place the mouse over the VTV control~~ move the mouse cursor away from the VTV, tap once on a node in the VTV control to focus it, then scroll with your finger.

The result is, HotTrack now highlights the line at the position where it was used the last time (e.g. from a previous tap), no matter where you scroll. I've created a small gif animation to visualize the problem:
![tvt-touch-hottrack](https://user-images.githubusercontent.com/703571/36620229-51cc68a2-18f2-11e8-91eb-91bf17216000.gif)

I guess, the best solution would be to hide the HotTrack completely as soon as a touch gesture is initialized on the VTV. There's no need for hottracking when touch input is in progress.

**Comment by joachimmarder** [comment]
The behavior does not differ much from the case when using the mouse wheel, so I don't see a high priority here.

> I guess, the best solution would be to hide the HotTrack completely as soon as a touch gesture is initialized on the VTV. There's no need for hottracking when touch input is in progress.

Agreed.

**Comment by IgitBuh** [comment]
> The behavior does not differ much from the case when using the mouse wheel

Actually, it does! When scrolling with the mouse wheel, the mouse cursor remains at the same position, so it makes sense that the node it's pointing at is highlighted.
When touch scrolling however, the finger moves, so there is nothing pointing at the hottracked node. In fact, it looks like nodes get randomly selected. If you happen to have a touch device, try it. You'll see how confusing it is.

**Comment by joachimmarder** [comment]
>  In fact, it looks like nodes get randomly selected.

I don't see that here and I don't see that in your video. It seems that the Y-posotion that determines the hot node does not change during scrolling. But of course the nodes at that position change due to scrolling, but the mouse position does not change because of the scroll gesture. So all in all this is similar to mouse-wheel scrolling.

**Comment by IgitBuh** [comment]
> but the mouse position does not change because of the scroll gesture

There is no mouse cursor at the tree. The mouse cursor is somewhere else on the screen. There is nothing pointing at the nodes that get highlighted/hottracked.

**Comment by joachimmarder** [comment]
> There is no mouse cursor at the tree. . The mouse cursor is somewhere else on the screen.

Interesting, in this case I don't see any hot-tracking.  I also placed a breakpoint in `HandleHotTrack()` and it was never reached if the mouse cursor was not over the tree.

**Comment by IgitBuh** [comment]
I've re-read my reproduction steps and I realized that I've descriped one step incorrectly. My apologies!
It is necessary to tap once on a node to focus it (as in the animation it was the "Page count" node). I guess that's the moment the HotTrack position is set as well. Then, scrolling with the finger up and down will create the described and gif-captured result.

Specifically in this PropertiesDemo this problem leads to even worse behavior, because the tree automatically scrolls the selected note to the middle (I don't use this option in my own application, so I didn't experience this additional problem before). If you now tap different nodes (instead of touch-scrolling the toCenterScrollIntoView will do the scrolling) random** other nodes will be hottrack-highlighted. In this capture I'm simply tapping different nodes after each other (the tapped node becomes the darker blue one):
![tvt-touch-hottrack2](https://user-images.githubusercontent.com/703571/36645645-51df3ac4-1a6c-11e8-8f01-018f3bc94f03.gif)
 ** = I guess it's somehow resulting from the distance of the old and new focused node. But it's probably not worth finding that out in detail, because this problem will be solved as well with hiding hottrack on touch input.

**Comment by joachimmarder** [comment]
>  to tap once on a node to focus it . I guess that's the moment the HotTrack position is set as well.

This typically sets the mouse cursor to the tapped position. So I still don't see a difference to clicking with the left button and then using the mouse-wheel.

 >  If you now tap different nodes (instead of touch-scrolling the toCenterScrollIntoView will do the scrolling) random** other nodes will be hottrack-highlighted. 

It should be the node on the tapped position that his highlighted (hot-tracked), which would be the expected behavior. The node that was originally on the tapped node should be selected in the center. Again, I don't think there is a difference to doing this with the mouse.

**Comment by IgitBuh** [comment]
> So I still don't see a difference to clicking with the left button and then using the mouse-wheel.

Windows 10 hides the mouse cursor as soon as there's touch input. In result, there's no visible element causing the hottrack highlight. When you use the mouse-wheel there's the mouse cursor hovering over the VTV and therefore the hottrack highlight makes sense.

Or to put it in other words: Hottracking without a (visible) mouse cursor does not make any sense and in practice it's confusing to the user.

To make the problem even clearer: The Windows file explorer has a treeview on the left side with hottrack for the mouse cursor. Touch input does not create the described visual problems as VTV does.

I see this as a usability/UI bug that can be solved by not drawing the hottrack highlight on touch input or if the mouse cursor is hidden.

**Comment by IgitBuh** [comment]
I've prepared this short code snippet to test if the mouse cursor is visible:
```
function IsMouseCursorVisible: Boolean;
var
  CI: TCursorInfo;
begin
  CI.cbSize := SizeOf(CI);
  GetCursorInfo(CI);
  Result := CI.flags = CURSOR_SHOWING;
  // 0                     Hidden
  // CURSOR_SHOWING (1)    Visible
  // CURSOR_SUPPRESSED (2) Touch/Pen Input (Windows 8+)
end;
```

This could be used in HandleHotTrack() at the very beginning:
```
if not IsMouseCursorVisible then
begin
  if Assigned(FCurrentHotNode) then
    InvalidateNode(FCurrentHotNode)
  else
    Exit;
end;
```

**Comment by joachimmarder** [comment]
> Hottracking without a (visible) mouse cursor does not make any sense 

Agreed. It was not my aim to question the bug report / change request, I just wanted to define its priority correctly.

**Comment by joachimmarder** [comment]
>   if Assigned(FCurrentHotNode) then
>    InvalidateNode(FCurrentHotNode)

I guess you want to invalidate `FCurrentHotNode` in order to clear its hot state, right? If so, I guess we need to set `FCurrentHotNode` to `nil`.

**Comment by IgitBuh** [comment]
> I guess you want to invalidate FCurrentHotNode in order to clear its hot state, right? If so, I guess we need to set FCurrentHotNode to nil.

Exactly, thank you!

Minor note: Your commit says `"Returns Tree"` ... That typo makes it sound like somebody is bringing back a plant to a tree rental. :smile:

**Comment by IgitBuh** [comment]
I gave it another thought and in case you didn't finish it already, this would be my improved suggestion:
```
  if not IsMouseCursorVisible then
  begin
    if Assigned(FCurrentHotNode) then
    begin
      InvalidateNode(FCurrentHotNode);
      FCurrentHotNode := nil;
    end;
    Exit;
  end;
```

This should be the most performant solution, because the rest of the code is then definitely skipped if the mouse cursor isn't visible (even if there's a hot state to be cleared).
