### ISSUE TITLE
C++ Builder 10.2 - VirtualTreeView 6.7 - VT_NODEIMAGES corrupted

### ISSUE THREAD

**Issue by ghost** [JAM-Software/Virtual-TreeView#768]
Hi, i just upgraded from XE2 to Tokyo and also updated the VirtualTreeView components to latest version on my laptop and desktop as well.

I have a huge project maintained with XE2 and when i opened in on my laptop it compiled like expected. when i do the same on my desktop it compiles also but when run it throws an access violation (Write of address 000000011). When debugging it says "Project xxx raised exception class EAssertionFailed with message 'Internal image "VT_NODEIMAGES" is missing or corrupt.".

I uninstalled and reinstalled the components without success. 

The curious thing is when I create a new project with some VST it runs without any problems. 

![2018-02-27 08_39_54-client exe](https://user-images.githubusercontent.com/24462409/36716246-e4821c10-1b99-11e8-93fa-eb3b93e6b5f4.png)

**Comment by ghost** [comment]
Hmm okay, when i add **virtualtrees.res** to my project, it runs. So seems to be a configuration failure of my desktop. Can be :closed_lock_with_key:

**Comment by joachimmarder** [comment]
Please follow our guidelines for submitting bugs as shown on the project homepage.
