### ISSUE TITLE
GetImageSize Fails if kind ikState and not assigned( StateImages )

### ISSUE THREAD

**Issue by LindenWrath** [JAM-Software/Virtual-TreeView#769]
VirtualTree.pas near 22120 in GetImageSize

  if not Assigned(OnGetImageIndexEx) and (((Kind = TVTImageKind.ikNormal) and not Assigned(fImages))
    or ((Kind = TVTImageKind.ikNormal) and not Assigned(fImages))) then

Strikes me that this is VERY wrong guessing the second line should be
    or ((Kind = TVTImageKind.ikState) and not Assigned(fStateImages))) then

**Comment by joachimmarder** [comment]
I guess you are right.
