### ISSUE TITLE
Scaling of Header was done incorrect on point size of font

### ISSUE THREAD

**Issue by ritsaert** [JAM-Software/Virtual-TreeView#771]
When using a virtual tree using default font size in a 4K monitor and setting the application to DPI aware, the fornt size is blown up to 16Pt (instead of the configured 8Pt). Size the font size of the header is expressed as Points and not pixels, it should not be scaled.

The patch below fixes the issue:

```
Index: VirtualTrees.pas
===================================================================
--- VirtualTrees.pas	(revision 1040)
+++ VirtualTrees.pas	(working copy)
@@ -10056,7 +10056,7 @@
   // This method is only executed if toAutoChangeScale is set
   Self.Height := MulDiv(FHeight, M, D);
   if not ParentFont then
-    FFont.Size := MulDiv(FFont.Size, M, D);
+    ; //FFont.Size := MulDiv(FFont.Size, M, D);
   // Scale the columns widths too
   for I := 0 to FColumns.Count - 1 do
   begin

```

**Comment by joachimmarder** [comment]
So your solution is to not scale the font at all? Do you think that will fit for all other user's needs?

**Comment by ritsaert** [comment]
Font size can be set in two ways: height (which is the character height in pixels) and size (which is the size in points). When using the size property you use a DPI aware method to set the font size. Hence correcting that would correct the font size double. So you should either 1. correct the font height, or 2. not correct the font size. 

Above fix did solve the header font size for me on both HD and UHD screens. I must admit I usually do not specify a header font at all or specify the header font size and not the header font height.

**Comment by joachimmarder** [comment]
I looked into `TControl.ChangeScale()` of RAD Studio 10.2.2 and they do scale the font, but they do it using the `Height` property.

>  I usually do not specify a header font at all 

In that case `TVTHeader.ParentFont` should be set to `True` and no scaling will take place.

I tried to replicate this issue, but so far was unable to see any unexpected behavior. I was using RAD Studio 10.2.2. Can you please supply more information or even better a sample project?

**Comment by joachimmarder** [comment]
I just committed a fix and would be interested to know if it fixes the issue you observed.

**Comment by ritsaert** [comment]
Tested and confirmed. This works correctly on all displays, UHD and normal ones. Thanks for the quick change.
