### ISSUE TITLE
Sort TreeOptions property alphabetically

### ISSUE THREAD

**Issue by alexmitev81** [JAM-Software/Virtual-TreeView#772]
I think it would be easier to find an option in the long list of options if they are sorted alphabetically in the definitions.

**Comment by joachimmarder** [comment]
I agree, but we first need to carefully check if this is a breaking change at some place.

**Comment by alexmitev81** [comment]
The different options are sets, so there is no way to break code. AFAIK, there's even no way to find the order of an element in a set.
I'm wondering why the Delphi IDE doesn't auto-sort them.

**Comment by joachimmarder** [comment]
> The different options are sets, so there is no way to break code.

I didn't mean the code, I meant DFMs and especially binary serialized class instances. See #724 for an example what can go wrong.

**Comment by CodehunterWorks** [comment]
> I'm wondering why the Delphi IDE doesn't auto-sort them.

I think the better way is to open a feature request at Embarcadero to configure the OI to sort set items alphabetically. Sorting the entries at source code level isn't a good idea. Imagine you want to add an entry like "toAAutoWasCrashedOnTheRoad" to the set. You need to re-order all of the following entries, line-breaks and so on.

**Comment by alexmitev81** [comment]
No need to reorder the following entries, but just insert your in the correct place.
