### ISSUE TITLE
OnGetText is fired after VirtualStringTree is cleared

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#773]
After a  call to VirtualStringTree.Clear is completed and exited the OnGetText event fires as a result of PaintTree.  The Node passed to the OnGetText event has the vsDeleting state and the RootNode as parent, but the tree RootNodeCount is 0 and the RootNode has no children.

How can this happen?  
Should users check for vsDeleting state in OnGetText, OnGetImageIndex events?
Aren't all nodes freed after a call to VirtualStringTree.Clear?

**Comment by joachimmarder** [comment]
We had no similar reports so far and did not observe this in our projects. Can you send a demo project or at least a call stack?

> How can this happen?

Hopefully the above will tell us. There is a common mistake that can lead to this behavior:
Accessing the VTV control from another thread than the UI (main) thread.

> Should users check for vsDeleting state in OnGetText, OnGetImageIndex events?

No, because
* if this is truly necessary, it should be done centrally in the TBaseVirtualTree.
* if `Clear()` was called then the memory for the nodes has been freed and accessing freed memory will cause AVs.

**Comment by pyscripter** [comment]
Thanks for the quick response.  Your guess is partially correct.  The Clear method is called by a timer (TTimer) event handler.  But AFAIK  timer events are executed in the main thread.  
The call stacks do not reveal much since the error occurs in the normal paint message call chain.  (PaintTree, DoPaintNode, DoGetText, OnGetText)
```
Tree.Clear;
OutputDebugString('Tree cleared');
```
OutputDebugString confirms the error occurs after the tree is cleared.
When I break inside the OnGetText handler before the error occurs with a conditional breakpoint, I can inspect the state of the tree and the node.  The Node passed to the OnGetText event has the vsDeleting state and the RootNode as parent, but the tree RootNodeCount is 0 and the RootNode has no children.

Further info that may be relevant.  VCL styles are used and the timer event handler is implemented with an anonymous procedure.  Also Header.AutoSizeIndex = 1 and Header.MainColumn = 1.

The only explanation I can think of is that Tree.Clear is called after the Paint message call chain has started.   Is there an implicit call to Application.ProcessMessages or a delayed execution within the paint call chain?  If not, then Application.ProcessMessages is triggered by one of the Tree event handlers (OnGetText, OnGetImageIndex) I am providing to the tree and which are called during the paint process.

If there is no implicit call to Application.ProcessMessages or a delayed execution within the paint call chain then please close the issue.

**Comment by luebbe** [comment]
I had trouble with Virtual Treeview + AutoSizeIndex <> 0 + VCL Styles.
Is this possibly related to https://github.com/Virtual-TreeView/Virtual-TreeView/issues/774?

**Comment by pyscripter** [comment]
Actually in my case the problem was caused by code inside OnGetText triggering Application.ProcessMessages

I am closing this issue.  
Morale:  Keep the code inside events handles (OnGetText, OnGetImageIndex ) triggered during painting as simple as possible.
