### ISSUE TITLE
Index out of bounds error when Header AutoSizeIndex and/or MainColumn <> 0

### ISSUE THREAD

**Issue by luebbe** [JAM-Software/Virtual-TreeView#774]
This is a rather strange issue, which is triggered when VCL Styles are enabled. I guess the reason under the hood is that switching to a VCL Style cause the forms/components to be re-created.

Steps to reproduce: Set vst.Header.AutosizeIndex and/or vst.Header.MainColumn to a value <> 0 at design time. Activate VCL Styles and load one (in your .dpr).

The application then crashes with a long stack trace in:
```
:7439cbb2 KERNELBASE.RaiseException + 0x62
System.Generics.Collections.TListHelper.CheckItemRange(0)
System.Classes.TCollection.GetItem(2)
VirtualTrees.TVirtualTreeColumns.GetItem(2)
VirtualTrees.FillBitmap($7982208)
VirtualTrees.TBaseVirtualTree.PrepareBitmaps(True,True)
VirtualTrees.TBaseVirtualTree.CreateWnd
...
Vcl.Forms.TCustomFrame.Create(???)
...
Vcl.Forms.TApplication.ProcessMessage(???)
```

The exception message is:

> Im Projekt TestVisual.exe ist eine Exception der Klasse EReadError mit der Meldung 'Fehler beim Lesen von TVirtualTreeColumn.Width: Argument außerhalb des Bereichs' aufgetreten.

Note that the `2` in `System.Classes.TCollection.GetItem(2)` is the AutoSizeIndex that I set at design time to provoke the error. 

Vcl Styles can be active, but the error is only triggered when a style is loaded at run time.

My current remedy for the problem is to leave AutoSizeIndex and MainColumn at their default values at design time and to set them to the desired Values in FormCreate.

**Comment by joachimmarder** [comment]
Are you using V6.7.0 or the current GitHub master branch?

>  the error is only triggered when a style is loaded at run time.

I guess you mean when the form is already visible? All styles are loaded at runtime.

> Steps to reproduce: Set vst.Header.AutosizeIndex and/or vst.Header.MainColumn to a value <> 0 at design time. Activate VCL Styles and load one (in your .dpr).

I tried with GitHub master + Advanced sample project, but without success.

**Comment by luebbe** [comment]
> Are you using V6.7.0 or the current GitHub master branch?

Sorry, my mistake. We're on an in between version of the master branch to which I updated during the second half of 2017. I'll try to figure out the exact version and I'll retry with current master.

>   >  the error is only triggered when a style is loaded at run time.
> 
> I guess you mean when the form is already visible? All styles are loaded at runtime.

That wasn't well phrased. What I actually meant was: It's not sufficient to activate VCL Styles in the project options. You also have to load the Styles and call `TStyleManager.TrySetStyle('...')` at some point. Without TrySetStyle nothing wrong happens. I do this almost as the first thing in the .dpr, before any form is created.

Maybe the problem is caused by the vst residing on a frame? The call stack looks like the exception happens while the components are streamed in and everything is build up. I can attach the full call stack if you like.

>   > Steps to reproduce: Set vst.Header.AutosizeIndex and/or vst.Header.MainColumn to a value <> 0 at design time. Activate VCL Styles and load one (in your .dpr).
> 
> I tried with GitHub master + Advanced sample project, but without success.

I'll try with GitHub master too and report back.

**Comment by luebbe** [comment]
My research so far
- My complex test application also crashes with GitHub master (VCL Styles + frame with vst and some more stuff created at run-time)
- A minimal example (VCL Styles + frame with just vst created at run-time) doesn't crash
- I try to figure out if there are more (vst) properties involved

The complete call stack looks like this:
```
:741acbb2 KERNELBASE.RaiseException + 0x62
System.Generics.Collections.TListHelper.CheckItemRange(0)
System.Classes.TCollection.GetItem(2)
VirtualTrees.TVirtualTreeColumns.GetItem(2)
VirtualTrees.FillBitmap($77CA9D8)
VirtualTrees.TBaseVirtualTree.PrepareBitmaps(True,True)
VirtualTrees.TBaseVirtualTree.CreateWnd
Vcl.Controls.TWinControl.CreateHandle
Vcl.Controls.TWinControl.HandleNeeded
Vcl.Controls.TWinControl.GetHandle
Vcl.Controls.TWinControl.GetClientRect
:00551904 TWinControl.CreateHandle + $1C
System.TypInfo.SetOrdProp(???,???,???)
System.Classes.TReader.ReadPropValue($48FBA30,$997595)
System.Classes.TReader.ReadProperty($48FBA30)
System.Classes.TReader.ReadCollection($4A026C0)
VirtualTrees.TVTHeader.ReadColumns($49CF5C0)
System.Classes.TReader.DefineProperty(???,(VirtualTrees.TVTHeader.ReadColumns,$77D44A0),(VirtualTrees.TVTHeader.WriteColumns,$77D44A0),???)
VirtualTrees.TBaseVirtualTree.DefineProperties($49CF5C0)
VirtualTrees.TCustomVirtualStringTree.DefineProperties($49CF5C0)
System.Classes.TReader.ReadProperty($7840E00)
System.Classes.TReader.ReadDataInner($7840E00)
System.Classes.TReader.ReadData($7840E00)
System.Classes.TComponent.ReadState(???)
Vcl.Controls.TControl.ReadState($49CF5C0)
Vcl.Controls.TWinControl.ReadState($49CF5C0)
System.Classes.TReader.ReadComponent(nil)
System.Classes.TReader.ReadDataInner(???)
System.Classes.TReader.ReadData($774F250)
System.Classes.TComponent.ReadState(???)
Vcl.Controls.TControl.ReadState($49CF5C0)
Vcl.Controls.TWinControl.ReadState($49CF5C0)
System.Classes.TReader.ReadComponent(nil)
System.Classes.TReader.ReadDataInner(???)
System.Classes.TReader.ReadData($774EF70)
System.Classes.TComponent.ReadState(???)
Vcl.Controls.TControl.ReadState($49CF5C0)
Vcl.Controls.TWinControl.ReadState($49CF5C0)
System.Classes.TReader.ReadComponent(nil)
System.Classes.TReader.ReadDataInner(???)
System.Classes.TReader.ReadData($491D2C0)
System.Classes.TComponent.ReadState(???)
Vcl.Controls.TControl.ReadState($49CF5C0)
Vcl.Controls.TWinControl.ReadState($49CF5C0)
System.Classes.TReader.ReadRootComponent($491D2C0)
System.Classes.TStream.ReadComponent($491D2C0)
System.Classes.InternalReadComponentRes(???,???,$491D2C0)
System.Classes.InitComponent(TfrBaseVisual)
System.Classes.InitComponent(TfrBaseVisualXy)
System.Classes.InitComponent(TfrVisualTest)
System.Classes.InitInheritedComponent($491D2C0,TFrame)
Vcl.Forms.TCustomFrame.Create(???)
GTFrame.TGTFrame.Create($4906180)
BaseFrame.TfrBase.Create($4906180)
BaseVisual.TfrBaseVisual.Create($4906180)
BaseVisualXy.TfrBaseVisualXy.Create($4906180)
MainVisual.TfmMainSample.acVisualizationAddExecute($4E9B9E0)
System.Classes.TBasicAction.Execute
Vcl.ActnList.TCustomAction.Execute
System.Classes.TBasicActionLink.Execute(???)
Vcl.Controls.TControl.Click
Vcl.ComCtrls.TToolButton.Click
Vcl.Controls.TControl.WMLButtonUp((514, (), 0, (), 16, 17, (), (16, 17), (), 0))
Vcl.Controls.TControl.WndProc((514, 0, 1114128, 0, 0, 0, (), 16, 17, (), 0, 0, ()))
Vcl.Controls.TControl.Perform(???,???,1114128)
Vcl.Controls.TWinControl.IsControlMouseMsg((514, (), 0, (), 16, 17, (), (16, 17), (), 0))
Vcl.Controls.TWinControl.WndProc((514, 0, 1114128, 0, 0, 0, (), 16, 17, (), 0, 0, ()))
Vcl.ComCtrls.TToolBar.WndProc((514, 0, 1114128, 0, 0, 0, (), 16, 17, (), 0, 0, ()))
Vcl.Controls.TWinControl.MainWndProc(???)
System.Classes.StdWndProc(1380038,514,0,1114128)
:74dc342b ; C:\WINDOWS\SysWOW64\user32.dll
:74db5893 ; C:\WINDOWS\SysWOW64\user32.dll
:74db5222 ; C:\WINDOWS\SysWOW64\user32.dll
:74db4ff0 user32.DispatchMessageW + 0x10
Vcl.Forms.TApplication.ProcessMessage(???)
```

**Comment by luebbe** [comment]
OK, now I have an example which is about as minimal as it can get. I copied the vst from my test application into an empty application and tried to get all properties back to their default values. There are still some non-default values and I haven't found out, which combination triggers the exception, apart from Header.MainColumn > 0.
Compiled with 10.1 Berlin.

The application has two panels. The left one contains an uVstFrame from the start, on the right one an uVstFrame will be placed if you click the button. I wanted to find out if it makes a difference when/from where the frame is created. Looks like it doesn't.

If you set Header.MainColumn to 0 in uVstFrame, everything runs fine. If you set it to a value > 0 it crashes. AutoSizeIndex doesn't seem to play a role as I first thought.

If you uncomment  TStyleManager.TrySetStyle('Amakrits');, everything runs fine too.

[vstCrash.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1802975/vstCrash.zip)

**Comment by pyscripter** [comment]
In TVTHeader.SetMainColumn  (see below),  I think the first statement needs to be changed to:

` if (csLoading in Treeview.ComponentState) or (hsLoading in FStates) then

````
procedure TVTHeader.SetMainColumn(Value: TColumnIndex);
begin
  if csLoading in Treeview.ComponentState then
    FMainColumn := Value
  else
  begin
    if Value < 0 then
      Value := 0;
    if Value > FColumns.Count - 1 then
      Value := FColumns.Count - 1;
    if Value <> FMainColumn then
    begin
      FMainColumn := Value;
      if not (csLoading in Treeview.ComponentState) then
      begin
        Treeview.MainColumnChanged;
        if not (toExtendedFocus in Treeview.FOptions.FSelectionOptions) then
          Treeview.FocusedColumn := FMainColumn;
        Treeview.Invalidate;
      end;
    end;
  end;
end;
```

**Comment by pyscripter** [comment]
The problem lies in TVirtualTreeColumn.SetWidth which contains the following statements:

```
        TotalFixedMinWidth := IfThen(FMaxWidthPercent > 0,
                                     Min((ClientWidth * FMaxWidthPercent) div 100, TotalFixedMinWidth),
                                     TotalFixedMinWidth);
        TotalFixedMaxWidth := IfThen(FMinWidthPercent > 0,
                                     Max((ClientWidth * FMinWidthPercent) div 100, TotalFixedMaxWidth),
                                     TotalFixedMaxWidth);
```
The use of IfThen is a **_bad idea_** because it evaluates ClientWidth even when FMaxWidthPercent  is 0.  This forces the creation of the window handle in the middle of loading the tree, which in this case causes the crash.

**Please replace the IfThen with a simple if statement:**
```
        If FMaxWidthPercent > 0 then
          TotalFixedMinWidth:= Min((ClientWidth * FMaxWidthPercent) div 100, TotalFixedMinWidth);
        If FMinWidthPercent > 0 then
          TotalFixedMaxWidth := Max((ClientWidth * FMinWidthPercent) div 100, TotalFixedMaxWidth);
```
With the above safe change your program runs fine.

But I am not sure if problems may arise if MaxWidthPercent etc. are <> 0.   ClientWidth will be evaluated and the Window handle created in the middle of loading the tree.  In general this does not seem to create problems.  See following point.

It is also worth-noting that when you use the VirtualStringTree inside a frame positioned in another form and not created dynamically (which should be better),  the VirtualStringTree properties are effectively loaded twice.  Once when reading the main form and once when reading the inherited VST from the frame.  ReadColumns for instance is called twice.  In your project, if you remove the frame from the main form and you just create it dynamically with your button it works fine without the above fix.

Finally, it is not clear to me why setting the MainColumn to <> 0 makes such a difference.

**Comment by joachimmarder** [comment]
> The use of IfThen is a bad idea because it evaluates ClientWidth even when FMaxWidthPercent is 0

+1, I changed that according to your proposed code. Thanks digging into this.

It is generally a good idea to delay the creation of the window handle until the control is fully loaded, but that would require some larger refactoring here. 

@luebbe: Does your large application work without exception with the latest source that includes the above patch?

**Comment by luebbe** [comment]
Yes it does. Thanks to @pyscripter for fixing the issue!
I think that MainColumn <> 0 plays a role because the Header columns are not yet (re)loaded/(re)created when this property is set while the form is loaded. I have the impression that using VCL Styles forces a recreation of all forms/frames, which seems to screw up the expected initialization order in some cases.

**Comment by pyscripter** [comment]
This is one is not a fault of VCL Styles.  If you look at you dfm files, Columns is stored twice.
