### ISSUE TITLE
Allow getting positioning details of cell content (TVTPaintInfo)

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#775]
I would like to do some additional custom painting after the cell has been painted. 
Unfortunately, `OnAfterCellPaint(Sender: TBaseVirtualTree; TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex; CellRect: TRect);` doesn’t provide any positioning details other than the full cell dimensions. If the cell contains more than just the text, that’s a problem. One could try to calculate the positions by using `VTV.Images.Width` and `VTV.TextMargin`. The first cell however also contains the tree lines. That’s where my problem kicks in. I don’t see a way to calculate where the actual cell content starts, because `CellRect` includes everything, including tree lines, checkbox, etc.

![vtv-cell](https://user-images.githubusercontent.com/703571/37207661-415ace62-239e-11e8-926f-eac5fb3c89b0.png)

After inspecting the source code, I found that `TVTPaintInfo` seems to contains all the required details, but I don’t see the possibility to obtain it when needed and it's not provided in `OnAfterCellPaint()` or any other paint event method.

Would it be possible to have something like this?
`function GetPaintInfo(Node: PVirtualNode; Column: TColumnIndex): TVTPaintInfo;`

**Comment by joachimmarder** [comment]
> One could try to calculate the positions by using VTV.Images.Width and VTV.TextMargin. The first cell however also contains the tree lines. That’s where my problem kicks in.

You can use the newly introduced function ´GetOffset()` introduced to fix #369.

**Comment by IgitBuh** [comment]
Indeed, this would solve the major part of the problem. 
But what about the image and text positions if there's a checkbox?

**Comment by joachimmarder** [comment]
> But what about the image and text positions if there's a checkbox?

For the first column, checkboxes are considered correctly, other columns don't have checkboxes.. Please test the function and report back specific problems.

**Comment by IgitBuh** [comment]
You are right. GetOffset() does more than I initially anticipated. 
It's probably too late, but in my opinion `GetRect({Checkbox, Image, Text, etc.})` would have been more flexible instead. That way, it would be easier to get the whole area of any cell part (incl. vertical positions). The offset GetOffset provides would then simply be R.Left.

During my test I noticed that the offset is probably off by 1px. Or I'm misunderstanding something.
OnVST3AfterCellPaint:
```
    Data := Sender.GetNodeData(Node);
    R := CellRect;
    R.Left := VST3.GetOffset(ofsCheckBox, Node); //same problem for ofsImage
    TargetCanvas.Brush.Color := clRed;
    TargetCanvas.FrameRect(R);
```
![vst-offset1](https://user-images.githubusercontent.com/703571/37311590-28d50090-2648-11e8-8687-dd49efa08eb5.png)
Notice, that the checkbox and the folder icon are cut off 1px on the left.

I also don't understand what ofsRightOfText is supposed to be. I would have expected it to be at the right of the text.
![vst-offset2](https://user-images.githubusercontent.com/703571/37311593-2d6c99f6-2648-11e8-9131-b6841a7f6723.png)

**Comment by luebbe** [comment]
your image of ofsRightOfText looks like it correctly calculates the indentation for Treelines+icon+checkbox and adds som arbitrary constant to it. Probably the length of some text in the tree ;)

**Comment by joachimmarder** [comment]
> Notice, that the checkbox and the folder icon are cut off 1px on the left.

Indeed, in TBaseVirtualTree.AdjustImageBorder() there is a -1, not sure what that is for.

**Comment by joachimmarder** [comment]
> I also don't understand what ofsRightOfText is supposed to be. I would have expected it to be at the right of the text.

You expected correctly, but there is a condition missing in `TCustomVirtualStringTree.DoGetNodeWidth()`. I am correcting this now.

**Comment by joachimmarder** [comment]
> It's probably too late, but in my opinion GetRect({Checkbox, Image, Text, etc.}) would have been more flexible instead. 

Typically the events provide the necessary Rect as parameter.  Using a `GetRect()` would so do a lot of work twice, as the Rect is typically already calculated for other purposes. Please provide a more specific use case.
