### ISSUE TITLE
Overlay Images with Index < 15 not drawn when OnGetImageIndexEx is used

### ISSUE THREAD

**Issue by CodehunterWorks** [JAM-Software/Virtual-TreeView#779]
Hello!

I've found an bug in procedure TBaseVirtualTree.PaintImage in conjunction with OnGetImageIndexEx and the scenario thats all overlay images resides in a separate ImageList provided by the ImageList parameter of OnGetImageIndexEx. Please have a look at this corresponding discussion at [DelphiPraxis (german).](https://www.delphipraxis.net/195726-virtualtreeview-ongetimageindexex-und-overlayimages.html)

Greets
Cody 

@joachimmarder

**Comment by joachimmarder** [comment]
Seems that this case (OverlayIndex <0 but seperate ImageList) was forgotten when "Ex" version of `OnGetImageIndex` was introduced.

**Comment by joachimmarder** [comment]
I fixed the issue, but I did not have the time to build a sample project to verify it. Could you please test the fix in your project?
