### ISSUE TITLE
Overlay image not drawn when using two ImageLists in OnGetImageIndexEx

### ISSUE THREAD

**Issue by CodehunterWorks** [JAM-Software/Virtual-TreeView#780]
Hello!

I've found a bug in VST when i'm determine the ImageIndex via OnGetImageIndexEx and passing the first ImageList for Kind = ikNormal or Kind = ikSelected and passing the second ImageList if Kind = ikOverlay. In this case the overlay is not drawn, as long as the ImageIndex is < 16. I think the problem is at Virtualtrees.pas:24459 .. 24465. I've tested it with D10.2.3 and TImageList as well as TPngImageList. Same in both cases.

As a temporary workaround I've placed 15 empty images at the beginning of ImageList2 to force ImageIndex > 15.

I suggest to remove the differentiation for drawing Overlays with ImageIndex < 15 with system internal overlay drawing and custom drawing for each other Overlay with ImageIndex >= 16. 

Please have also a look at the corresponding discussion at [DelphiPraxis](https://www.delphipraxis.net/195726-virtualtreeview-ongetimageindexex-und-overlayimages.html).

Greets
Cody

PS: I had already posted this issue yesterday evening but cant see it today anymore. So i posted it once again.

**Comment by joachimmarder** [comment]
> PS: I had already posted this issue yesterday evening but cant see it today anymore. So i posted it once again.

This is because the issue #779 has been fixed and so closed, closed issues do not disappear on GitHub, you can view them again at any time e.g. using their number or by removing the filter for closed issues.

**Comment by CodehunterWorks** [comment]
Ah, Too early in the morning ;-) Thanks for this lightning speed bugfix!

**Comment by joachimmarder** [comment]
So does the fix work for you?

**Comment by CodehunterWorks** [comment]
> So does the fix work for you?

Yes works good.
