### ISSUE TITLE
"~" not working on German keyboard

### ISSUE THREAD

**Issue by weka1** [JAM-Software/Virtual-TreeView#781]
The ` "~" key (Alt Gr "+*~")` is not working as expected on a German keyboard. Instead it triggers some automatic arrangements of the columns.

**Comment by weka1** [comment]
I'm not convinded that the implemented solution is really working.
The line after the modification tests for ´ssShift´.

 if Shift = [ssCtrl] then
                 if (toReverseFullExpandHotKey in TreeOptions.MiscOptions) xor (ssShift in Shift) then
                   FullExpand

**Comment by joachimmarder** [comment]
OK, the fix is more complicated than I assumed after a quick look.  A review of the revised fix is appreciated.
