### ISSUE TITLE
Version 6.X InitNode issue

### ISSUE THREAD

**Issue by mnelsen3** [JAM-Software/Virtual-TreeView#782]
The Node index when InitNode is first called starts at one not zero. I have an install on Delphi 7 and it starts at zero.
Here's my sample for the code in the InitNode(Sender: TBaseVirtualTree; ParentNode,
  Node: PVirtualNode; var InitialStates: TVirtualNodeInitStates) procedure. It's the same in both D7 and XE7

var
 nData: TPIMInfo;
begin
  nData := vstPIM.GetNodeData(Node);

  with dmPros.qyEmpMsg do
   begin
    if Node.Index = 0 then
     First
    else
      Next;

    nData^.BookMark    := GetBookmark;
    nData^.MsgThread   := FieldByName('Message Thread').AsInteger;
    nData^.MsgKey      := FieldByName('Message Key').AsInteger;
    nData^.Deleted     := FieldByName('Deleted').AsString = 'Y';
    nData^.Read        := not FieldByName('Date Read').IsNull;
    nData^.Locked      := FieldByName('Locked').AsString = 'Y';
    nData^.Priority    := FieldByName('Priority').AsString;
    nData^.TicketKey   := FieldByName('Ticket Key').AsString;

    if FieldByName('Priority_1').AsString <> '' then
     nData^.TixPriority := FieldByName('Priority_1').AsInteger;
   end;

  Node.CheckType  := ctCheckBox;

**Comment by joachimmarder** [comment]
> The Node index when InitNode is first called starts at one not zero.

Some quick tests did not confirm that. In case Node.Index was non-zero, the Node.PrevSibling was not nil. In case Node.Index was 0, Node.PrevSiblings was nil.
Please respect our guidelines for submitting bugs and attach a sample project or describe how to replicate the issue with one of the VT sample project.

**Comment by pyscripter** [comment]
This has been working as designed for me.

**Comment by mnelsen3** [comment]
Sorry about not adhering to the procedures. Not sure why it would think that there is PrevSibling. I called Clear just before I set the RootNodeCount. Also when stepping through the IniNode the index starts at one then goes to zero then two.

Martin Nelsen
Porter Lee Corporation
847.985.2060 x319 | martin.nelsen@porterlee.com<mailto:martin.nelsen@porterlee.com> | www.porterlee.com<http://www.porterlee.com/>

**Comment by joachimmarder** [comment]
> Also when stepping through the IniNode the index starts at one then goes to zero then two.

This is not necessarily wrong, it depends on the parent node and the current viewport, etc. But this is a bug tracker, not a support forum. Please review our guidelines for support and submitting bugs on the project homepage.
