### ISSUE TITLE
GetOffsets incorrectly calculates image sizes.

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#784]
In TBaseVirtualTree.GetOffsets the calls to GetImageSize omit the Column parameter, which defaults to 0 (not sure why).  If there are no columns or for other columns the mage size would be incorrect.

The solution is to include the column in the calls.  i.e.

```
  // right of left image, left of normal image
  pOffsets[TVTElement.ofsImage] := pOffsets[TVTElement.ofsStateImage] + GetImageSize(pNode, TVTImageKind.ikState, pColumn).cx;
  if pElement = TVTElement.ofsImage then
    exit;
  // label
  pOffsets[TVTElement.ofsLabel] := pOffsets[TVTElement.ofsStateImage] + GetImageSize(pNode, TVTImageKind.ikNormal, pColumn).cx;


```

**Comment by joachimmarder** [comment]
Thanks. I added column support to `GetOffsets()` just recently and missed these lines.

**Comment by pyscripter** [comment]
Thanks for the quick fix!
