### ISSUE TITLE
TBaseVirtualTree.CMHintShow unscaled value

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#785]
Minor issue.
In TBaseVirtualTree.CMHintShow there is the following statement in line 16329.
`
                  HintPos.Y := Max(HintPos.Y, ClientToScreen(CursorRect.BottomRight).Y) + 2;
`
The 2 needs to be DPI scaled.

**Comment by joachimmarder** [comment]
Agreed and fixed.
