### ISSUE TITLE
Issues with toHideSelection

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#789]
HideSelection is a property of many Delphi controls (TMemo, TListView, TTreeView ect.) and is True by default.  I suggest that toHideSelection is added to DefaultPaintOptions.

The problem with toHideSelection is that it is not respected. The painting of an item as selected is controlled by the paint option poDrawSelection.   poDrawSelection is correctly set in PaintTree as
```
        if (toAlwaysHideSelection in FOptions.FPaintOptions) or
          (not Focused and (toHideSelection in FOptions.FPaintOptions)) then
          Exclude(PaintOptions, poDrawSelection);
```
So far, so good.  However further down, PaintTree calls DoPaintNode, which calls PaintNormalText, which calls InitializeTextProperties,  In that last procedure another check is made about whether the control is focused without considering toHideSelection.  This second check is not needed and should be removed.  
```
    // Change the font color only if the node also is drawn in selected style.
    if poDrawSelection in PaintOptions then
    begin
      if (Column = FFocusedColumn) or (toFullRowSelect in FOptions.FSelectionOptions) then
      begin
        if Node = FDropTargetNode then
        begin
          if ((FLastDropMode = dmOnNode) or (vsSelected in Node.States)) and not
             (tsUseExplorerTheme in FStates) then
            Canvas.Font.Color := FColors.SelectionTextColor;
        end
        else
          if vsSelected in Node.States then
          begin
            if (Focused or (toPopupMode in FOptions.FPaintOptions)) and not  //<-- Here is the problem 
               (tsUseExplorerTheme in FStates) then
            Canvas.Font.Color := FColors.SelectionTextColor;
          end;
      end;
    end;
```

There is another related issue.  DoDrawBackground called by PaintTree correctly sets  the background colors if paDrawSelection is in PaintOptions:
```
            if Focused or (toPopupMode in FOptions.FPaintOptions) then
            begin
              Brush.Color := FColors.FocusedSelectionColor;
              Pen.Color := FColors.FocusedSelectionBorderColor;
            end
            else
            begin
              Brush.Color := FColors.UnfocusedSelectionColor;
              Pen.Color := FColors.UnfocusedSelectionBorderColor;
            end;
```
The UnfocusedSelectionColor and UnfocusedSelectionBorderColor are only used for selected nodes that are not focused when toHideSelection is not present.   But these colors correspond to the same colors as unselected nodes.  Instead they should default to clHighlight.

Finally,  GetColor has a few issues with VCL Styles enabled.  
A:  In code such as the one below GetElemenetColor does not touch result if it returns False and in the second condition Result is undetermined.
```
          if not StyleServices.GetElementColor(StyleServices.GetElementDetails(ttItemHot), ecTextColor, Result) or
            (Result <> clWindowText) then
            Result := NodeFontColor;
```
B.  Code such as this
```
        if FColors[Index] = clHighlight then
          Result := StyleServices.GetSystemColor(clHighlight)
        else
          Result := FColors[Index];
```
should be better written as 
```
          Result := StyleServices.GetSystemColor(FColors[Index]);
```
since if GetSystemColor(Color) returns Color if it is not a system color and when you use VCL styles and you specify a color as a system color you most likely want it converted to the corresponding color in the active style.

I have implemented the above changes in the attached file and you can review the changes with a diff viewer.   If you prefer I can submit a diff file or a PR.

[VirtualTrees.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1870316/VirtualTrees.zip) 
(Please ignore and use the patch file below, which contains further refinements)

**Comment by joachimmarder** [comment]
It would be great if you could create and send a patch-file. In the wiki we describe how to do this: https://github.com/Virtual-TreeView/Virtual-TreeView/wiki/Create-a-Patch

**Comment by luebbe** [comment]
@pyscripter :Thanks for the input about GetColor. I have tried to fix some issues with PRs on my part already, but I was unsure why things were done like this in case A), so I didn't touch the underlying logic. Didn't know that B) could be simplified. Learned something again

**Comment by pyscripter** [comment]
Here is the patch file.
[diff.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1871339/diff.txt)

**Comment by pyscripter** [comment]
A note should be made that this may be a breaking change.  If toHideSelection was not present, Virtual Trees would behave as if it was present.   Now that this is fixed, toHideSelection needs to be added to PaintOptions for the virtual tree to behave as before and as it should be.

**Comment by pyscripter** [comment]
Here is the patch.  I tried to keep the changes outside GetLine to minimum.   The changes to GetLine have no impact on appearance. 
[diff.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1872955/diff.txt)

**Comment by joachimmarder** [comment]
The file has an unusual format, Tortoise is not able to apply the patch. It seems that it is in diff-format, not in patch-format. Did you follow the instructions in the Wiki?

Applying the diff manually is too error prone.

**Comment by pyscripter** [comment]
Sorry, I did put a diff file.
I do not have TortoiseSVN installed but I use TortoiseGit on a clone of Virtual-Treeview.  In TortoiseGit there is a Create Patch Serial command.  Would this do?

**Comment by pyscripter** [comment]
Will this do?  You may have to change the file extension.
[0001-toHideSelection-issues.patch.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1887969/0001-toHideSelection-issues.patch.txt)

**Comment by joachimmarder** [comment]
> In TortoiseGit there is a Create Patch Serial command. Would this do?

Yes, that works. Since we use SVN at work, I have only installed TortoiseGit. Would you mind writing a step-by-step tutorial for TortoiseGit that I can put in the Wiki?

**Comment by joachimmarder** [comment]
> Here is the patch. I tried to keep the changes outside GetLine to minimum. The changes to GetLine have no impact on appearance.

I guess you mean `GetColor()`not `GetLine()`? I don't use VCL themeing, so I will rely on you regarding those changes.

What is the exact reason to change `clBtnFace` to `clGray` for `UnfocusedSelectionColor`?

**Comment by pyscripter** [comment]
Instructions for creating a patch with TortoiseGit.

> If you work with TortoiseGit and a clone of Virtual-TreeView you can create a patch. with the following steps.
> 1.  Commit your changes locally.
> 2.  Right-click on the project folder in Windows Explrorer and select TortoiseGit, "Create patch serial..."
> 3.  In the "Version" section of the dialog box select "Since" and from the drop-down list select "remotes/origin/master"
> 4. Press OK and your patch will be generated.

**Comment by pyscripter** [comment]
Yes I meant GetColor.

Regarding UnfocusedSelectionColor:
Native Treeview shows a grayish color when a node is selected but not focused and HideSelection is False.  This grayish color is probably clButtonFace or close to it under the default Windows theme.
However with Vcl Styles and dark themes`
 StyleServices.GetSystemColor(clButtonFace)`;  
returns a colour which is undistinguishable form the tree background and toHideSelection would appear to have no effect.  The choice of clGray is probably not perfect, but it works reasonably well with both unthemed, and styled Virtual-Trees (light and dark styles included).  The user can change that color anyway in the Form designer and when Vcl styles are not used it is quite close to clBtnFace.

**Comment by joachimmarder** [comment]
Thanks for TortoiseGit instructions, I added them to the Wiki,

And I applied the patch except: 

>  I suggest that toHideSelection is added to DefaultPaintOptions.

I don't see a true need to change this.

**Comment by pyscripter** [comment]
Thanks.
HideSelection is the default options in Delphi controls but it is not on in Windows Explorer, so it is OK to leave it out of DefaultPaintOptions.
