### ISSUE TITLE
OnNodeDblClick Issue

### ISSUE THREAD

**Issue by rgdawson** [JAM-Software/Virtual-TreeView#791]
When OnNodeDblClick is defined to bring up a form or dialog, after you close the form, clicking on 'X' to close main window does not work first time.

To reproduce, open the demo "Minimal". 
1. Add an event handler for OnNodeDblClick for the VST.
2. Add the code, ShowMessage('OnNodeDblClick');
3. Run the program
4. DoubleClick on a node.
5. Press OK to close message Box
6.  Press the 'X' (or Close button) to close the main Window
7.  Result is that nothing happens
8.  Pressing 'X' (or Close button) a second time, will close the main window.

Additional info:  Alternatively, after step 5 above, if you hover mouse over edit field it does not show the edit cursor.  Clicking on the edit field causes the VST to select Node "level 0, Index 19", to it seems that the VST is processing the next mouse click after returning from the message box.

I am running the latest version on GitHub as of 3/2/18 and Delphi 10.2.3.

**Comment by rgdawson** [comment]
I can work around the problem by using a timer.  So in OnNodeDblClick instead of executing ShowMessage, I turn on a timer that executes ShowMessage.  (Even with a very small delay intrval like 10ms).  Then things work after closing message box.

**Comment by pyscripter** [comment]
Try the following:
```
TThread.ForceQueue(nil, procedure
  begin
    ShowMessage('...');
  end);
```

**Comment by rgdawson** [comment]
Yes, I used:
  TThread.CurrentThread.ForceQueue(nil,
    procedure
    begin
      ShowMessage('...');
    end);
And that works.  I've never seen Forcequeue and I would not have thought of that on my own.  Very interesting function.
