### ISSUE TITLE
"Invalid window handle" when using styles

### ISSUE THREAD

**Issue by stbie** [JAM-Software/Virtual-TreeView#792]
When using styles sometime an error "invalid window handle" comes up.
After some debugging I think a wrong if statement is the problem.
The wrong scrollbar was asked for "HandleAllocated".

Unit VirtualTrees.StyleHooks.pas
starting at line 456

  **if FVertScrollBarWindow.HandleAllocated then begin**
    F**Horz**ScrollBarWindow.Repaint;
    RedrawWindow(F**Horz**ScrollBarWindow.Handle, nil, 0, RDW_FRAME or RDW_INVALIDATE);
  end;

should be changed to 
  **if FHorzScrollBarWindow.HandleAllocated then begin**
    F**Horz**ScrollBarWindow.Repaint;
    RedrawWindow(F**Horz**ScrollBarWindow.Handle, nil, 0, RDW_FRAME or RDW_INVALIDATE); // Fixes issue #698
  end;

Maybe this is also a solution for
https://github.com/Virtual-TreeView/Virtual-TreeView/issues/532

**Comment by joachimmarder** [comment]
Thanks for providing the fix.
