### ISSUE TITLE
Header of auto-resize column is blank (not re-painted correctly) after form resizing.

### ISSUE THREAD

**Issue by edwinyzh** [JAM-Software/Virtual-TreeView#793]
The attached screenshot illustrate the issue in details.
![2018-04-11_11h37_44](https://user-images.githubusercontent.com/541197/38595340-ce4cbc7e-3d7d-11e8-95ff-3a7eafb7e6ef.png)

```
object treeAccounts: TVirtualStringTreeDescendant
  AlignWithMargins = True
  Margins.Left = 0
  Margins.Top = 0
  Margins.Right = 0
  Margins.Bottom = 0
  Align = alClient
  BorderStyle = bsNone
  ChangeDelay = 20
  Color = clBtnFace
  Colors.UnfocusedSelectionColor = 16762508
  Colors.UnfocusedSelectionBorderColor = clHighlight
  DefaultNodeHeight = 30
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = 'Segoe UI'
  Font.Style = []
  Header.AutoSizeIndex = -1
  Header.Height = 30
  Header.Options = [hoColumnResize, hoDrag, hoShowSortGlyphs, hoVisible]
  ParentFont = False
  ScrollBarOptions.ScrollBars = ssVertical
  TabOrder = 0
  TreeOptions.PaintOptions = [toHideFocusRect, toShowBackground, toThemeAware, toUseBlendedImages, toUseBlendedSelection]
  TreeOptions.SelectionOptions = [toFullRowSelect, toRightClickSelect, toAlwaysSelectNode]
  OnChange = treeAccountsChange
  OnGetText = treeAccountsGetText
  OnGetImageIndexEx = treeAccountsGetImageIndexEx
  OnInitNode = treeAccountsInitNode
  Columns = <
    item
      MinWidth = 20
      Position = 0
      Width = 20
      WideText = 'aaaaaaaaa'
    end
    item
      Position = 1
      Width = 210
      WideText = 'bbbbbbbbb'
    end
    item
      Alignment = taCenter
      MinWidth = 20
      Position = 2
      Width = 20
      WideText = 'ccccccccccccc'
    end>
end
```
Some related code snippets
===
```
  //ensure treeAccountsGetImageIndexEx() will be called
  treeAccounts.Images := dmGlobal.Animated16x16;
  // make the log msg column autosize
  treeAccounts.Header.AutoSizeIndex := cStatusColumn;
  treeAccounts.Header.Columns[cAccountNameColumn].MinWidth := 150;
  treeAccounts.Header.Options := treeAccounts.Header.Options + [hoAutoResize];
  treeAccounts.Header.MainColumn := cAccountNameColumn;
  treeAccounts.EnableHtmlTags := False;
```

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting bugs written on the project homepage. Please include which version you are using and a working project that allows to replicate the problem, or steps how to replicate the problem with one of the included sample projects.

**Comment by joachimmarder** [comment]
Any new regarding demo project and used version?

**Comment by edwinyzh** [comment]
Oh sorry for my late reply. I assumed I will receive email notifications whenever there is an update to this post, but I didn't, and I don't know why.

I'm using this revision submitted on Apr 7, 2018:
https://github.com/Virtual-TreeView/Virtual-TreeView/commit/ebd5a484ed5ff537f3eec85a173d80a83d431ed4

I don't have a sample project that I can share at the moment, but I will when  I'm able to compose one.

**Comment by joachimmarder** [comment]
Email notifications typically work, please check your GitHub preferences and your spam filter.
Regarding the sample project: It would be sufficient to tell us how to replicate this with one of the VT demo projects.

**Comment by edwinyzh** [comment]
Hello, this is an update -

The issue is confirmed to be coming from Virtual Treeview, and after reverted to "Commits on Jul 21, 2017", the issue's gone.

Thanks.

**Comment by joachimmarder** [comment]
> and after reverted to "Commits on Jul 21, 2017", the issue's gone.

Sorry, only the exact commit that caused the problem will help, you can use bisecting to identify the commit. Or of course a sample project that allows us to replicate the problem will help.

**Comment by transmogrifix** [comment]
This may be fixed by 9afdab818e7dd94fd9574abe8883db64b21b87a6 which was merged on June 2. I suggest you update and test again.

**Comment by joachimmarder** [comment]
Any news here? Otherwise I am going to close the issue.

**Comment by joachimmarder** [comment]
Closing this issue as reported supplied no additional information.
