### ISSUE TITLE
ScrollIntoView: do not Center (better left align column)

### ISSUE THREAD

**Issue by ahesse** [JAM-Software/Virtual-TreeView#797]
Behaviour Change: 
After some last changes the nodes are now default centered when focused.
(must use toFullRowSelect to get old behaviour)

I realy don't like centered columns. More readability is to use left aligned columns.

Is it possible to get a left aligned scroll-into-view behaviour?

**Comment by pyscripter** [comment]
I will have another look.  Do you have toCenterScorllIntoView on?  Do you have columns defined?  **Are you using the very latest version after commit https://github.com/Virtual-TreeView/Virtual-TreeView/commit/629c410abba0d5d6f6cf17ecfa0aa23abf035091?**  With columns defined the code should be exactly equivalent to what it has always been.

**Comment by pyscripter** [comment]
Can you also post some simple demo that reproduces the issue or at least some pictures?

**Comment by joachimmarder** [comment]
Could be a result of the fix supplied for issue #794.

**Comment by pyscripter** [comment]
I don't think so.   I think instead  ahesse is using code before that fix.  Let's wait for his feedback.

**Comment by ahesse** [comment]
I'm using actual code from repo.
The change was between 2017-09-04 and now (2018-04-10).

![vt_beforefocus](https://user-images.githubusercontent.com/14077190/39191018-351d1356-47d6-11e8-854a-ce7d984c7404.png)

Old behaviour when focus (no horizontal moving):
![vt_afterfocus_old](https://user-images.githubusercontent.com/14077190/39191016-35000b9e-47d6-11e8-91b0-b42936f1d012.png)

New behaviour (alwas center):
![vt_afterfocus_new](https://user-images.githubusercontent.com/14077190/39191019-3539cc62-47d6-11e8-9545-68e575cecb94.png)

**Comment by ahesse** [comment]
After updating to actual version the focused node is now right aligned!

![vt_afterfocus_actual](https://user-images.githubusercontent.com/14077190/39191527-673fff3c-47d7-11e8-8dce-ad0739cecc10.png)

**Comment by joachimmarder** [comment]
What is the exact call you are doing?
Can you attach this sample project?

**Comment by ahesse** [comment]
Only creating a TVirtualStringTree with default options.
Add some root nodes. 
Focus a node by mouse.


[vt.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/1943404/vt.zip)

**Comment by pyscripter** [comment]
Could you please try an one-line change in the following routine and report back whether it works as expected?
The deleted line is commented out and the line below is inserted.
```
function TBaseVirtualTree.ScrollIntoView(Column: TColumnIndex; Center: Boolean; Node: PVirtualNode = nil): Boolean;

// Scrolls the columns so that the given column is in the client area and returns True if the columns really have been
// scrolled (e.g. to avoid further updates) else returns False.

var
  ColumnLeft,
  ColumnRight: Integer;
  NewOffset: Integer;
  R: TRect;

begin
  Result := False;

  if FHeader.UseColumns and FHeader.Columns.IsValidColumn(Column) then begin
    ColumnLeft := Header.Columns.Items[Column].Left;
    ColumnRight := ColumnLeft + Header.Columns.Items[Column].Width;
  end else if Assigned(Node) then begin
    R := GetDisplayRect(Node, NoColumn, not (toGridExtensions in FOptions.FMiscOptions));
    ColumnLeft := R.Left;
    ColumnRight := R.Right;
  end else
    Exit;

  NewOffset := FEffectiveOffsetX;
  if not (FHeader.UseColumns and (coFixed in Header.Columns[Column].Options)) and (not Center) then
  begin
    if ColumnRight > ClientWidth then
//      NewOffset := FEffectiveOffsetX + (ColumnRight - ClientWidth)
      NewOffset := FEffectiveOffsetX - (Header.Columns.GetVisibleFixedWidth - ColumnLeft)
    else if ColumnLeft < Header.Columns.GetVisibleFixedWidth then
      NewOffset := FEffectiveOffsetX - (Header.Columns.GetVisibleFixedWidth - ColumnLeft);
    if NewOffset <> FEffectiveOffsetX then
    begin
      if UseRightToLeftAlignment then
        SetOffsetX(-Integer(FRangeX) + ClientWidth + NewOffset)
      else
        SetOffsetX(-NewOffset);
    end;
    Result := True;
  end
  else if Center then
  begin
    NewOffset := FEffectiveOffsetX + ColumnLeft - (Header.Columns.GetVisibleFixedWidth div 2) - (ClientWidth div 2) + ((ColumnRight - ColumnLeft) div 2);
    if NewOffset <> FEffectiveOffsetX then
    begin
      if UseRightToLeftAlignment then
        SetOffsetX(-Integer(FRangeX) + ClientWidth + NewOffset)
      else
        SetOffsetX(-NewOffset);
    end;
    Result := True;
  end
end;
```

**Comment by pyscripter** [comment]
Scrolling when there are no columns was introduced by my PR in relation to #776.   The above one-line change makes the code 100% the same to what it was before when there are columns.  

If we want to completely disable scrolling when there are no columns defined then one more one-line change can be made to the 6th line of the routine.

 ` end else if Assigned(Node) and (toCenterScrollIntoView in FOptions.SelectionOptions) then begin`

So if the user has not set toCenterScrollIntoView then no horizontal scrolling will take place automatically as it was the case before my patch.

Sorry for the trouble...

**Comment by ahesse** [comment]
The first change will center the node (not right aligned anymore).
The second change will not change the horizontal position.
I will use this changes.

**Comment by pyscripter** [comment]
With the second change Isn't this the old behaviour?

**Comment by ahesse** [comment]
With the second change it is the old behaviour.
The horizontal position do not change when focus a node.
That is as expected.

**Comment by pyscripter** [comment]
This is an improved version.  Still old behaviour if no toCenterScrollIntoView is not set to keep old users happy.  But please try it with toCenterScrollIntoView and report whether this is better to no scrolling, when the horizontal space is limited.   The change is still confined to the same statement as above. 

```
function TBaseVirtualTree.ScrollIntoView(Column: TColumnIndex; Center: Boolean; Node: PVirtualNode = nil): Boolean;

// Scrolls the columns so that the given column is in the client area and returns True if the columns really have been
// scrolled (e.g. to avoid further updates) else returns False.

var
  ColumnLeft,
  ColumnRight: Integer;
  NewOffset: Integer;
  R: TRect;

begin
  Result := False;

  if FHeader.UseColumns and FHeader.Columns.IsValidColumn(Column) then begin
    ColumnLeft := Header.Columns.Items[Column].Left;
    ColumnRight := ColumnLeft + Header.Columns.Items[Column].Width;
  end else if Assigned(Node) and (toCenterScrollIntoView in FOptions.SelectionOptions) then begin
    R := GetDisplayRect(Node, NoColumn, not (toGridExtensions in FOptions.FMiscOptions));
    ColumnLeft := R.Left;
    ColumnRight := R.Right;
  end else
    Exit;

  NewOffset := FEffectiveOffsetX;
  if not (FHeader.UseColumns and (coFixed in Header.Columns[Column].Options)) and (not Center) then
  begin
    if ColumnRight > ClientWidth then
      NewOffset := FEffectiveOffsetX + Min(ColumnRight - ClientWidth,
       - (Header.Columns.GetVisibleFixedWidth - ColumnLeft))
    else if ColumnLeft < Header.Columns.GetVisibleFixedWidth then
      NewOffset := FEffectiveOffsetX - (Header.Columns.GetVisibleFixedWidth - ColumnLeft);
    if NewOffset <> FEffectiveOffsetX then
    begin
      if UseRightToLeftAlignment then
        SetOffsetX(-Integer(FRangeX) + ClientWidth + NewOffset)
      else
        SetOffsetX(-NewOffset);
    end;
    Result := True;
  end
  else if Center then
  begin
    NewOffset := FEffectiveOffsetX + ColumnLeft - (Header.Columns.GetVisibleFixedWidth div 2) - (ClientWidth div 2) + ((ColumnRight - ColumnLeft) div 2);
    if NewOffset <> FEffectiveOffsetX then
    begin
      if UseRightToLeftAlignment then
        SetOffsetX(-Integer(FRangeX) + ClientWidth + NewOffset)
      else
        SetOffsetX(-NewOffset);
    end;
    Result := True;
  end
end;

```

**Comment by ahesse** [comment]
No, always centering.

**Comment by pyscripter** [comment]
Could you please check with a  breakpoint which  part of the code gets executed.  Is the changed statement hit when you click on a node?

**Comment by pyscripter** [comment]
I got it.  You select with the keyboard and not the mouse.   TBaseVirtualTree.DoFocusNode has this strange statement and behaves differently when you focus with the mouse rather than the keyboard or programatically.  What is the purpose of this??

```
        ScrollIntoView(FFocusedNode, (toCenterScrollIntoView in FOptions.SelectionOptions) and
          (MouseButtonDown * FStates = []), not (toFullRowSelect in FOptions.SelectionOptions) );
```
Last try.  One line added
`Center := false `
if there are no columns.  Could you  please give that a try, if possible in a real application also where different nodes have different size text some of which may or may not fit?


```
function TBaseVirtualTree.ScrollIntoView(Column: TColumnIndex; Center: Boolean; Node: PVirtualNode = nil): Boolean;

// Scrolls the columns so that the given column is in the client area and returns True if the columns really have been
// scrolled (e.g. to avoid further updates) else returns False.

var
  ColumnLeft,
  ColumnRight: Integer;
  NewOffset: Integer;
  R: TRect;

begin
  Result := False;

  if FHeader.UseColumns and FHeader.Columns.IsValidColumn(Column) then begin
    ColumnLeft := Header.Columns.Items[Column].Left;
    ColumnRight := ColumnLeft + Header.Columns.Items[Column].Width;
  end else if Assigned(Node) and (toCenterScrollIntoView in FOptions.SelectionOptions) then begin
    Center := False;
    R := GetDisplayRect(Node, NoColumn, not (toGridExtensions in FOptions.FMiscOptions));
    ColumnLeft := R.Left;
    ColumnRight := R.Right;
  end else
    Exit;

  NewOffset := FEffectiveOffsetX;
  if not (FHeader.UseColumns and (coFixed in Header.Columns[Column].Options)) and (not Center) then
  begin
    if ColumnRight > ClientWidth then
      NewOffset := FEffectiveOffsetX + Min(ColumnRight - ClientWidth,
       - (Header.Columns.GetVisibleFixedWidth - ColumnLeft))
    else if ColumnLeft < Header.Columns.GetVisibleFixedWidth then
      NewOffset := FEffectiveOffsetX - (Header.Columns.GetVisibleFixedWidth - ColumnLeft);
    if NewOffset <> FEffectiveOffsetX then
    begin
      if UseRightToLeftAlignment then
        SetOffsetX(-Integer(FRangeX) + ClientWidth + NewOffset)
      else
        SetOffsetX(-NewOffset);
    end;
    Result := True;
  end
  else if Center then
  begin
    NewOffset := FEffectiveOffsetX + ColumnLeft - (Header.Columns.GetVisibleFixedWidth div 2) - (ClientWidth div 2) + ((ColumnRight - ColumnLeft) div 2);
    if NewOffset <> FEffectiveOffsetX then
    begin
      if UseRightToLeftAlignment then
        SetOffsetX(-Integer(FRangeX) + ClientWidth + NewOffset)
      else
        SetOffsetX(-NewOffset);
    end;
    Result := True;
  end
end;

```

**Comment by ahesse** [comment]
Without toCenterScrollIntoView the position is unchanged.
With toCenterScrollIntoView the tree nodes are now left aligned.
For me it is now working well.

The question is, if this behaviour ist what others expect too?

**Comment by pyscripter** [comment]
Let me summarize:

Tree with Columns:   works exactly as it always has.  No change to old behaviour.
Tree without Columns, toCenterScrollIntoView not set (the default):  No change to old behaviour.  
Tree without Columns, toCenterScrollIntoView set:
- if the text fits no scrolling
- if the text does not fit horizontal scrolling takes place.   The amount of horizontal scrolling is the **minimum** of what is needed to
a. make the right part of the text visible.
b. make the text left-aligned.

To Joachim.   I propose that this last version is committed.

**Comment by joachimmarder** [comment]
I just merged the last proposed code. Thanks to both of you for your contribution.
