### ISSUE TITLE
Improvement: new OnNodeFilter property

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#8]
_From [d.atama...@gmail.com](https://code.google.com/u/114510614586066939078/) on June 22, 2009 21:40:54_

New OnNodeFilter property needed for simplifying filtering nodes:

type
  TVTNodeFilter = procedure(Sender: TBaseVirtualTree; Node: PVirtualNode;
Column: TColumnIndex; var Filtered: Boolean) of object;

And GetFirstFiltered, GetLastFiltered, etc. functions.

What is your opinion ?

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=8_

**Comment by vincentparrett** [comment]
_From [timotegt...@googlemail.com](https://code.google.com/u/100346166526305102504/) on June 22, 2009 09:31:21_

The idea of a callback is quite interesting.
I implemented the filtering without a callback as a callback would impose a 
performance penalty and additionally it would be quite hard to determine how many 
nodes are actually to be displayed without querying for every existing node.

Implementing iterators for filtered nodes seem to be a good idea and would obviously 
cause no harm, so I see nothing against it.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on May 16, 2013 14:03:51_

**Labels:** -Type-Defect Type-Enhancement

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 10, 2013 12:48:31_

**Labels:** -Priority-Medium Priority-Low

**Comment by joachimmarder** [comment]
Issue is more than 7 years old and imported, closing for cleanup purposes.
