### ISSUE TITLE
the "Shift+=" can not expend the node 

### ISSUE THREAD

**Issue by mksjgj** [JAM-Software/Virtual-TreeView#801]
in version 7, the node can not be expanded by press "Shift+=",  but the number pad pluse key("+") is still ok.
in version 6.x, both of them are available.

**Comment by mksjgj** [comment]
by code Comparison, i think the reason is here:

[vk_add_bug.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2045521/vk_add_bug.txt)

**Comment by joachimmarder** [comment]
> in version 7, the node can not be expanded by press "Shift+=",

Sorry, but I don't think that was ever intended to work, and it seems a rather unusual keyboard shortcut for a treeview control for the expand operation.

**Comment by joachimmarder** [comment]
>`               else if Shift = [] then begin  ----------> it should be:  else if ssShift in Shift then begin`
>`                 if Assigned(FFocusedNode) and not (vsExpanded in FFocusedNode.States) then`
>`                 ToggleNode(FFocusedNode);`

Windows Explorer expands a node without the Shift key pressed, so does Virtual TreeView.

**Comment by joachimmarder** [comment]
>` if ((toReverseFullExpandHotKey in TreeOptions.MiscOptions) and (Shift = [ssCtrl])) xor (Shift = [ssCtrl, ssShift]) then  ------> xor should be or, I guess this is a misspellings`
>`   FullExpand`

No, I think this is correct. 

Please describe the repro steps and the state of the `toReverseFullExpandHotKey` flag, the expected and the observed behavior.

**Comment by joachimmarder** [comment]
Any news here?

**Comment by mksjgj** [comment]
about the Shift+= can not expand the node,  you opinion is  it is by design, but how about a user without a number pad, i.e. a laptop

**Comment by mksjgj** [comment]
line 170??:
              if ssCtrl in Shift then
                if (toReverseFullExpandHotKey in TreeOptions.MiscOptions) xor (ssShift in Shift) then
                  FullCollapse
                else
                  FHeader.RestoreColumns
              else
                if Assigned(FFocusedNode) and (vsExpanded in FFocusedNode.States) then
                  ToggleNode(FFocusedNode);

i think i will never understand the usage of "XOR", What exactly does it mean to express? can you REWRITE it by AND, OR, NOT?

**Comment by joachimmarder** [comment]
> i think i will never understand the usage of "XOR", can you REWRITE it by AND, OR, NOT?

Seriously?! 
A xor B = (A and not B) or (B and not A)
Please use Google to find more on XOR.

**Comment by joachimmarder** [comment]
> about the Shift+= can not expand

I still think it is a rather unusual keyboard shortcut.

> but how about a user without a number pad, i.e. a laptop

Cursor-right expands a single node. You are free to add your own behavior to the OnKeyDown event. Windows Explorer only handles num-pad too, so this seems to be a good default behavior for Virtual TreeView

**Comment by mksjgj** [comment]
about the Shift+= can not expand 

I agree with you, if you think so, I mean it is by design

**Comment by mksjgj** [comment]
about the XOR

it is true i had never used XOR on logical operation in my everyday programing, the  true xor true get false make me crazy. i always use  A<>B ,...
but if you sure it express you logic, i agree with you again.
thank you for you work on this greate  TreeView
