### ISSUE TITLE
Simplify code for changing the checkstate

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#805]
The code when a node is checked is overly complex, because Virtual Treeview supports pending check state changes both for keyboard and for mouse. This causes problems like #790 and #285 or makes feature request like #745 unnecessary complex to implements. Neither Windows Explorer nor the Windows ListView common control has or supports these pending check states. 

I don't see a significant benefit in them and vote for removing them and making the behavior similar to Windows Explorer and the ListView common control.

Proposed changes:
- Remove `tskeyCheckPending` and  `tsMouseCheckPending`
- Remove `FCheckNode` and `FPendingCheckState`
- Apply check state change on key / mouse button down

**Comment by pyscripter** [comment]
+1

**Comment by sanjayssk** [comment]
+1
