### ISSUE TITLE
OnChange works differently by the mouse and the keyboard

### ISSUE THREAD

**Issue by supasoft** [JAM-Software/Virtual-TreeView#808]
Changing the focus by the mouse:
1 call: Node is nil
2 call: Node is not nil (new focus)

Changing the focus by the keyboard:
1 call: Node is not nil (old focus)
2 call: Node is not nil (new focus)

**Comment by joachimmarder** [comment]
The code that handles the left mouse button calls `ClearSelection()` if no multiselect should take place.

The code that handles the cursor keys calls `RemoveFromSelection(FFocusedNode)` if no multiselect should take place.

To make this consistent, we could call `ClearSelection()`in the keyboard case as well if no multiselection is required.

**Comment by supasoft** [comment]
It is rigth. How to determine that the focus is removing from the node?

**Comment by joachimmarder** [comment]
> How to determine that the focus is removing from the node?

Have you tried the `OnFocusChanging` and the  `OnFocusChanged` event?

**Comment by supasoft** [comment]
I have not. Thank you.

**Comment by supasoft** [comment]
I would like to have an event for change a focus of a row. I used OnChange for this.
