### ISSUE TITLE
Stream data corrupt. A node's anchor chunk is missing

### ISSUE THREAD

**Issue by alexpenkov** [JAM-Software/Virtual-TreeView#809]
Getting the following error trying to load the tree from a stream:
---------------------------
Debugger Exception Notification
---------------------------
Project *.exe raised exception class EVirtualTreeError with message 'Stream data corrupt. A node's anchor chunk is missing.'.

Data was saved by older version (4 or early 5)
[model_1.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2153698/model_1.zip)

**Checked with 6.7 and 5.5.3**

**Comment by joachimmarder** [comment]
Can you please check with the latest source code (GitHub master)?
This report seems to be a duplicate of #724.

**Comment by alexpenkov** [comment]
Yes, in the current master the problem is solved. Thank you.
