### ISSUE TITLE
Root toggle node buttons are partially drawn even if toShowRoot is False.

### ISSUE THREAD

**Issue by transmogrifix** [JAM-Software/Virtual-TreeView#811]
Hi,

Commit ad586ea9a67af57276a150095aa2f4417ddaf667 has introduced a regression in drawing of toggle node buttons. When toShowRoot is turned off, the toggle buttons of root nodes should not be visible, but currently they are partially visible.

To reproduce, run the provided example and have a look at the leftmost column.
[example.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2163875/wrong_edit_position.zip)

The issue seems to be in TBaseVirtualTree.PaintTree, before the mentioned commit an offset (ofsControlMargin) was being applied :
`PaintNodeButton(Canvas, Node, Column, CellRect, Offsets[ofsToggleButton] - Offsets[ofsControlMargin], ButtonY, BidiMode);`
and after the commit it's not:
`PaintNodeButton(Canvas, Node, Column, CellRect, Offsets[ofsToggleButton], ButtonY, BidiMode); `

The master branch no longer contains ofsControlMargin, so I assume this offset should be applied in some other way?

**Comment by joachimmarder** [comment]
> The master branch no longer contains ofsControlMargin

This was introduced for #369 and has been renamed to `ofsMargin`, as it needs to be applied to every column.

#369 was a major refactoring in several steps. Thanks to #369 it should hopefully be easy to fix this in `GetOffsets()`.

**Comment by joachimmarder** [comment]
>  the toggle buttons of root nodes should not be visible, but currently they are partially visible.

I compiled your project with Delphi 10.2.3 and the latest VTV source from GitHub master but could not see any partially painted toggle buttons. Can you please submit a screenshot?

**Comment by transmogrifix** [comment]
![toggle-buttons](https://user-images.githubusercontent.com/25490028/42423945-855e428c-8303-11e8-8f9b-6cdd59e8565b.png)

I am using Delphi 10.2.1 and the latest master.

**Comment by joachimmarder** [comment]
Here's my screenshot: 
![grafik](https://user-images.githubusercontent.com/10615289/42424203-733a2328-8308-11e8-9039-0df4eb665964.png)

**Comment by joachimmarder** [comment]
It seems that there is an additional 1 pixel offset in your screenshot that could be a result of the refactorings for #369. Increasing the value of the property `Margin` to 8 makes the problem appear for sure

Actually the toggle buttons should not be painted at all, but previous version just properly painted them outside the viewport.

**Comment by transmogrifix** [comment]
Yes, it seems that there is some additional offset. Also, I agree, they shouldn't be painted at all. I found that curious as well :)

But I don't really understand why you don't see it. My first screenshot was on Windows 8.1, here is another on Windows 7 (with basic theme) :
![toggle-buttons2](https://user-images.githubusercontent.com/25490028/42424280-34a586c8-830a-11e8-8f0a-08be77ced47b.png)
I don't have any other versions to test on.

**Comment by transmogrifix** [comment]
That fixed it, thanks!
