### ISSUE TITLE
toDisableAutoscrollOnFocus is on by default

### ISSUE THREAD

**Issue by supasoft** [JAM-Software/Virtual-TreeView#812]
toDisableAutoscrollOnFocus is on by default.
it's bug.

**Comment by joachimmarder** [comment]
Which version of VTV are you using? This seems not correct for the current GitHub master.

**Comment by supasoft** [comment]
Version 6.7.

**Comment by joachimmarder** [comment]
Updating to the latest GitHub master, which is an RC of V7.0, should fix the issue.
