### ISSUE TITLE
OnChnage event may get fired for empty tree

### ISSUE THREAD

**Issue by supasoft** [JAM-Software/Virtual-TreeView#815]
If sets toFullRowDrag and no selected nodes, clicking in an empty area calls vtChange..

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting bug reports as shown on the project homepage.

**Comment by supasoft** [comment]
Source. Click in the empty area of VT,  please.
[VirtualTreeView OnChange.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2179292/VirtualTreeView.OnChange.zip)

**Comment by supasoft** [comment]
RootNodeCount may be > 0. Check, please. Sourse included.
[VirtualTreeView OnChange2.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2181808/VirtualTreeView.OnChange2.zip)

**Comment by supasoft** [comment]
do I create a new report?

**Comment by joachimmarder** [comment]
Sorry, closed the wrong issue.
