### ISSUE TITLE
Need UnfocusedSelectionTextColor

### ISSUE THREAD

**Issue by supasoft** [JAM-Software/Virtual-TreeView#816]
Need Colors.UnfocusedSelectionTextColor

**Comment by joachimmarder** [comment]
I don't think the text color of selected elements differs between focused and unfocused state. So you should be able to use `FColors.SelectionTextColor`.

**Comment by supasoft** [comment]
![vt7unfocused](https://user-images.githubusercontent.com/40602544/42496501-f342cd78-842e-11e8-8b57-bc4b33070968.png)

**Comment by joachimmarder** [comment]
As I wrote in my last comment and as your screenshot shows, in V7 the font color of a selected element does not differ wether or not the control is focused. So you should be able to use `FColors.SelectionTextColor`.

**Comment by supasoft** [comment]
I understood. Thank you.
