### ISSUE TITLE
EditNode overlays node icon

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#817]
Calling Vst.EditNode(Node, 0); creates an edit box in the node. Unfortunately, it doesn't consider any existing icons in that node. The icon is still drawn, but hidden behind the edit box.

If the node contains an icon, the edit box should be placed besides the icon.
1. This would be a more natural usability, because if this is used to edit a node text, the text position shouldn't jump to the left while being edited.
2. This is how Windows handles it as well:
![vtv-nodeediticon](https://user-images.githubusercontent.com/703571/42879980-d878be52-8a92-11e8-94e8-4d8d2d538636.png)

**Comment by IgitBuh** [comment]
I have to correct myself and appologize for not having prepared a description of the required steps to reproduce this problem. Otherwise I would have noticed the actual reason for the problem.

The actual problem is that `GetImageIndex` detects the image size for the position of the edit box with `Column=-1`. I have multiple columns with individual images. Therefore in my `GetImageIndex` I'm assigning `ImageIndex` based on `Column` and `Kind`. Since there is no case for `Column=-1` the edit box is positioned without considering the image in that cell.

To reproduce the problem you can use the Advanced demo:
1. Open the SpeedDemo
2. Assign an ImageList to the VTV and add an image to it
3. Set toEditable=True
4. Open Header.Columns and add 2 columns.
5. Assign this code to OnGetImageIndex:
```
  case Column of
    0:
    begin
      if Kind in [ikNormal, ikSelected] then
        ImageIndex := 0;
    end;
  end;
```
6. Run the demo, add nodes to the SpeedDemo, select a node, click F2.

**Comment by joachimmarder** [comment]
I recently accepted pull request #813. Would you mind testing if this has caused the issue?

**Comment by IgitBuh** [comment]
My VTV version is from May this year, so before this change.

**Comment by transmogrifix** [comment]
With the latest master the position seems correct. I have modified the speed demo per your instructions.
![vst_editing_with_icon](https://user-images.githubusercontent.com/25490028/43084291-ad60c804-8e98-11e8-81f8-58df3d23c72e.png)

**Comment by joachimmarder** [comment]
Great! Thanks for testing.
