### ISSUE TITLE
InternalAddToSelection is buggy if any nodes get excluded (level or sibling constraint, disabled)

### ISSUE THREAD

**Issue by ElminsterAU** [JAM-Software/Virtual-TreeView#819]
This seems to be the result of a half done move from using "AddedNodesIndexes" to "PackArray".

I fixed it in 5e0921230a00cb88a142d3a7f265af00b375aed9 (but you don't want to pull that as is because it just commends out the faulty code instead of completely removing it).

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting bugs as stated on the project homepage: When reporting a bug please include a sample project that allows us to quickly reproduce the bug. This can also be one of the demo projects that come with Virtual Treeview, modified to show the bug. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug.

**Comment by joachimmarder** [comment]
Can you supply any further details here?

**Comment by ElminsterAU** [comment]
If you look at the code, you can easily see that the code uses 2 different methods to pick out only the entries from NewItems that are actually "selectable".

One method is using AddedNodesIndexes to remember indices into the unmodified NewItems, and then later iterate over that array with indices and using them to access NewItems.

The other method is to increment the pointers for the invalid entries in the array by 1 (using `Inc(PAnsiChar(NewItems[I]))`) and then calling PackArray to compact the array, removing all such entries with an odd value.

After the packing, the indices stored in AddedNodesIndexes  have become invalid (because everything has been moved around) and unnecessary, because NewItems now only contains valid entries.

but the code in "post process added nodes" uses that AddedNodesIndexes as indices into the now compacted NewItems  and everything blows up.

**Comment by joachimmarder** [comment]
OK, I see, thanks. Not sure why the index was stored in `AddedNodesIndexes[]` instead of the `PVirtualNodes`, doing so should solve the problem.

**Comment by ElminsterAU** [comment]
The index that's stored inside `AddedNodesIndexes` is an offset into the `NewItems` array. It has only ephemeral meaning during that single call to `InternalAddToSelection`. And it's only purpose is to be able to later iterate only over the "valid" newly selected nodes in `NewItems`.

And because of the use of `PackArray` to remove all invalid entries from `NewItems` the use of `AddedNodesIndexes` is simply completely redundant, because by the time `// post process added nodes` needs to iterate over only the valid new entries, NewItems already only contains the valid entries.

As using PackArray is required anyway to be able to use QuickSort and then merge the new nodes into the existing (sorted) FSelection, the easiest way to fix this is to simply completely remove `AddedNodesIndexes` as it's totally unnecessary.

**Comment by joachimmarder** [comment]
OK, so far I never cared what `PackArray()` is doing exactly. That the array is passed as `const` in both methods is a bit misleading. I will revise the fix tomorrow and remove `AddedNodesIndexes` tomorrow.

**Comment by ElminsterAU** [comment]
`PackArray` does not change the "array" (which is a pointer into the heap, and which would change if the array reallocated because it's length is changed). This is why PackArray returns the new length as a parameter instead of changing the length of the actual array.

It does change the CONTENTS of the array. 

If you consider something like:

```pascal
procedure DoSomething(const p: Pointer);
begin
  FillChar(p^, 50, 0);
end;
```

The const is fine and correctly, because p is never changed. It's only the memory p points to that is changed. Same with a dynamic array passed as const.

Passing the dynamic array as const prevents unnecessary reference counting and implicit try/finally blocks.

**Comment by joachimmarder** [comment]
> Passing the dynamic array as const prevents unnecessary reference counting and implicit try/finally blocks.

I know, but isn't that also true for passing it as `var` paramter? It might be habit of mine, but I use `const`only if the parameter value remains truly unchanged. Anyway, it does not matter here and the original issue should be fixed now. Thanks for reporting it.
