### ISSUE TITLE
toDisableAutoscrollOnFocus

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#82]
_From [wangef...@gmail.com](https://code.google.com/u/117456768515259494957/) on November 23, 2009 23:42:34_

Sorry if I sound frustraded, but what have you done? You have changed the 
spec of toDisableAutoscrollOnFocus from:
- Disable scrolling a column entirely into view if it gets focused

to 
- Disable scrolling a node or column into view if it gets focused.

You are breaking backwards compability.

These may be related, but are not the same. I have set 
toDisableAutoscrollOnFocus = false everywhere in my applications because 
my users didn't like it when the tree was suddenly jumping horizontally. 
It was very disturbing, trees in general don't do that. So i disable...

This does not mean that i don't want the focused row not to be vertically 
scrolled into view, trees in general does this.

If somebody does not want the tree to scroll vertically you should add a 
new property toDisableVerticalAutoscrollOnFocus or something to support 
this behaviour, not break the old one.

Regards,

Magnus

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=82_

**Comment by vincentparrett** [comment]
_From [wangef...@gmail.com](https://code.google.com/u/117456768515259494957/) on June 15, 2010 02:00:43_

Bump.

**Comment by vincentparrett** [comment]
_From [a...@anse.de](https://code.google.com/u/109183940118681839166/) on June 15, 2010 09:40:39_

Well, the property is named perfectly right: toDisableAutoscrollOnFocus. It's not toDisableAutoscrollNodeOnFocus . Btw, are you sure you didn't mix up column and node in your above description? Anyway, I think you want nodes to be autoscrolled, but not columns. For me that sounds wrong - I want horizontal and vertical autoscrolling.

> trees in general don't do [horizonatal scrolling]

That's not true. Even my Windows Explorer tree does that (running Vista here).

**Comment by vincentparrett** [comment]
_From [wangef...@gmail.com](https://code.google.com/u/117456768515259494957/) on September 29, 2010 01:13:26_

I beg to disagree. 

The property has been named for several years and has had a specific behaviour, documented in the source. So don't say the naming suddenly is "perfectly right", unless you at the same time say that the property has been wrongly named since inception.

I still claim trees in general don't.
- Vista: Yes, but not as simple as in current virtual treeview but still annoying since:
- Windows 7: no
- XP: no.
- Delphi IDE: mixed, some do, most don't.

**Comment by vincentparrett** [comment]
_From [wangef...@gmail.com](https://code.google.com/u/117456768515259494957/) on September 29, 2010 01:21:22_

What you want:

> I want horizontal and vertical autoscrolling

Was possible before, and is still possible, and I have never claimed this should not be an option.

What I want, and the way windows explorer works. Vertical autoscrolling, but not horizontal. Is no longer possible.

With the new implemention, when you want to get rid of automatic horizontal scrolling, you also loose vertical scrolling. Why would anyone want to disable that??? Of course the property is from the beginning named toDisableAutoscrollOnFocus without reference to horizontal/vertial/node/column is, because the idea of turning off vertical scrolling is very unusual, so there is no need to choose a name which indicates that vertical scrolling is not included.

**Comment by vincentparrett** [comment]
_From [wils...@tampabay.rr.com](https://code.google.com/u/114460648300953792750/) on July 31, 2013 10:42:01_

In the documentation it says "Disable scrolling a column entirely into view if it gets focused." another quote "New option toDisableAutoscrollOnFocus introduced, to prevent a tree from scrolling horizontally after a column received the focus, but was not fully visible." This sounds perfect to me. So why does it disable the Vertical Scrolling ? That's my 2 cents worth!

**Comment by joachimmarder** [comment]
I vote for closing this issue as WONTFIX. If we change the behavior now after 7 years, this would be a breaking change again.

**Comment by joachimmarder** [comment]
As proposed closing this as WONTFIX. Please open a new bug if you still feel this should be changed, because some stuff was lost when importing from Google Code.
