### ISSUE TITLE
CheckBox state propagation slow for large number of nodes

### ISSUE THREAD

**Issue by GoranDespalatovic** [JAM-Software/Virtual-TreeView#820]
Steps to reproduce :

1. Create grid with 5 nodes each having 250000 child nodes, set all node's checkType to triStateCheckBox.
2. Check root node, grid will select all nodes just fine
3. Expand any of those 5 nodes, deselect checkBox. Grid takes much more time to set check states.

Suggestion :

change following methods

procedure TBaseVirtualTree.WMKeyUp(var Message: TWMKeyUp);
procedure TBaseVirtualTree.HandleMouseUp(var Message: TWMMouse; const HitInfo: THitInfo);

replace

`              DoCheckClick(FCheckNode, FPendingCheckState);`

with
```
            BeginUpdate;
            try
              DoCheckClick(FCheckNode, FPendingCheckState);
            finally
              EndUpdate;
            end;

```
I'm not shure if it will break something because of issue #805 but it's worth considering. After code change grid selects checkboxes allmost immediately even on million child nodes.

**Comment by joachimmarder** [comment]
The `BeginUpdate() / EndUpdate()` would fit better in `ChangeCheckState()`, which is called from `DoCheckClick()`. It should only be called if `FCheckPropagationCount = 0`. That way any code path to `DoCheckClick()` benefits.
