### ISSUE TITLE
Programatic selection of node should always happen without timers

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#821]
We have the flag `tsSynchMode` in Virtual TreeView that allows to perform operation without using timers. We should use this to avoid the use of timers if a node is selected programatically. I don't see a point in delaying the notification the selection change through the `OnChnage` event in this case, and the use of timer here can cause very strange runtime behavior.

**Comment by obones** [comment]
I'm not doing this, but maybe someone, somewhere is recreating the underlying nodes when a change occurs, meaning that the `PVirtualNode` instance disappears before the code that triggered the change has finished.
If this is done inside a keyboard event from the virtual tree itself, it may very well try to access a destroyed node, with the consequences that everyone can imagine.
The usual way to circumvent this is to post a message and do the "suicide" code inside the handler, but it can also be done with timers. Maybe this is the reason why they are here, even if I dislike them as much as you do.
