### ISSUE TITLE
Performance problem after Update

### ISSUE THREAD

**Issue by MatthiasErlemeyer** [JAM-Software/Virtual-TreeView#824]
Hello,
before the update to version 7 we use the version 5.5 with Delphi2007. Now we use Delphi 10.2 Tokyo.
After the update, we notice, that the call of "AddChild(nil)" for e.g. 19000 Childs (TVirtualStringTree) has a duration about 20sec. By the old Version was the duration 6sec. Have you any idea why the newer Version is slower than the actual version?

**Comment by joachimmarder** [comment]
> before the update to version 7 we use the version 5.5 with Delphi2007. Now we use Delphi 10.2 Tokyo.
> Have you any idea why the newer Version is slower than the actual version?

Well, that's a large step with several years and hundreds of commit inbetween. 

> ... the call of "AddChild(nil)" for e.g. 19000 Childs

You should set `RootNodeCount` to 19000 instead, as demonstrated in the "SpeedDemo" sample project.

> has a duration about 20sec. 

I see 39secs only if I don't use `BeginUpdate()` / `EndUpdate()`. With `BeginUpdate()` / `EndUpdate()` i see 18ms.

**Comment by MatthiasErlemeyer** [comment]
Thank you for the quick response. We normaly use BeginUpdate() / EndUpdate(), but in this case it dosn't help.
I suspect that an event already called EndUpdate() before all nodes have been added. How can I best check this assumption?

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting bugs on the project homeage:
> When reporting a bug please include a sample project that allows us to quickly reproduce the bug. This can also be one of the demo projects that come with Virtual Treeview, modified to show the bug. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. If you already have a solution, please supply a patch file or make a pull request. If you used a previous version that did not have the bug, please include this version number in your report. Please do not use the issue tracker for getting support, only for reporting true bugs.
