### ISSUE TITLE
Remove GetBounds() from interface IVTEditLink

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#825]
`GetBounds()` isn't called anywhere. Remove it also from sample implementations.

**Comment by obones** [comment]
Please don't do this, we are using it in our subclasses to adjust the edit bounds in some very special cases.

**Comment by joachimmarder** [comment]
> we are using it in our subclasses to adjust the edit bounds in some very special cases.

@obones: Which members are you using here exactly?

**Comment by obones** [comment]
We are doing something like this:

    if (toAutoSpanColumns in TreeOptions.AutoOptions) and Header.UseColumns then
    begin
      R := EditLink.GetBounds;
      // adjust R according to various rules
      EditLink.SetBounds(R);
    end;

This code was added back in 2014 in our overridden `UpdateEditBounds` method to make sure the edit control would be as wide as a cell if it spans multiple columns.
But maybe this "fix" is no longer needed, I haven't checked.

**Comment by joachimmarder** [comment]
But I don't see any member of TVirtualNode being used here?!

**Comment by obones** [comment]
Well no, but this ticket is about removing `ITVEditLink.GetBounds` which is what we use and the reason for my comment. 
Did I miss something?

**Comment by joachimmarder** [comment]
> but this ticket is about removing ITVEditLink.GetBounds 

Sorry, my fault, I mixed up two issues.

> But maybe this "fix" is no longer needed, I haven't checked.

That would be good. The use case a having a method in an interface just to fix a bug seems not sufficient to me. Do you have your own editor implementation of do you use the included `TStringEditLink`?

**Comment by obones** [comment]
We definitely have our own editors, to show combo boxes, multiple selections, all with our own custom controls.

**Comment by joachimmarder** [comment]
> We definitely have our own editors

Then your editors can implements their own interfaces, including one that has a `GetBounds()` function.
