### ISSUE TITLE
AutoFitColumns size calculation problem

### ISSUE THREAD

**Issue by Brnoch** [JAM-Software/Virtual-TreeView#827]
When I use icons inside several columns of a VST, the size necessary to display the content of the displayed nodes is often not calculated properly.
Here is by example what I obtain:
![image](https://user-images.githubusercontent.com/8734788/45353011-107d6d00-b5ba-11e8-9d5a-36b6b942594b.png)

It seems that the VST calcuates the width required for the main column (=0) instead of the different columns.
All seems to be OK when including the column index in the GetOffset function (l.13550 sq):

`function TBaseVirtualTree.GetOffset(pElement: TVTElement; pNode: PVirtualNode; pColumn: Integer = NoColumn): integer;
// Calculates the offset of the given element
var
  lOffsets: TVTOffsets;
begin
  GetOffsets(pNode, lOffsets, pElement, pColumn);
  Exit(lOffsets[pElement]);
end;`

...and then using it in the GetMaxColumnWidth function 
line 28214 : `TextLeft := GetOffset(TVTElement.ofsLabel, Run, Column);`

**Comment by joachimmarder** [comment]
Thanks for reporting. Could you please verify the fix?
