### ISSUE TITLE
Walking tree up and GetNodeData

### ISSUE THREAD

**Issue by Proman6** [JAM-Software/Virtual-TreeView#831]
Normaly if I want to walk up in tree I do:
```
while n <> nil do
 n := n.Parent;
```

But this like can walk over the tree... It's stupid... An now:
```
while n <> nil do
begin
 vst.GetNodeData(n);
 n := n.Parent;
end;
```

If I do this for RootNode, ale is ok (`GetNodeData` return nil and function don't change anything). But what happen next? `RootNode` still have `Parent` and `GetNodeData` for this (it's not a node!) change some propertys like for Node element.

Ok, I can check no  `n <> nil` but `n <> vst.RootNode`. But component herself don't check this!

**Comment by joachimmarder** [comment]
You should not use TVirtualNode.Parent but the NodeParent[] property of the virtual treeview control. It will return nil for the topmost elements, as one would expect. 
The members of TVirtualNode are considered internal data structure and should not be used directly. I guess I need to make them private at some point.
