### ISSUE TITLE
HasImage is deprecated and suggests inexistent GetImageWidth 

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#834]
The `HasImage` and `GetNodeImageSize` methods are both marked with a `deprecated` message that suggests to use `GetImageWidth`
However, that method is nowhere to be seen in the current `VirtualTrees.pas` file.
Is there another method to call? Or should those deprecation messages be removed?

**Comment by joachimmarder** [comment]
Sorry, should have been `GetImageSize()`
