### ISSUE TITLE
HasImage should get the same parameters as GetImageSize and not be deprecated

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#835]
With the current source, `HasImage` is deprecated and suggests using `GetImageSize` and this is good because the latter allows specifying the `IncludePadding` parameter.
However, replacing one by the other is not trivial because `HasImage` is often used in `if` statements, meaning that one would have to change a lot of code everywhere to ensure the `TSize` returned by the function is not empty.
Sure, one could replace this existing code

    if Tree.HasImage(Node, Kind, Column) then

by this one: 

    if not Tree.GetImageSize(Node, Kind, Column).IsZero then

But this means one cannot do a simple "Search/Replace" because the condition has to be reversed and `IsZero` must be appended. And this assumes the `TSize` record has the `IsZero` method on all supported editions of Delphi (I have not checked this).

However, if the existing `HasImage` would be changed to get the `IncludePadding` parameter and its code changed to call `GetImageSize`, then there would be no change required in user applications. The deprecation marker could then be removed and `HasImage` could even be made inline so that it has no impact on the final linked code.

What do you think of this? Did I miss something? Or should I submit a pull request?

**Comment by joachimmarder** [comment]
In the few cases I saw where HasImage() was used the call of HasImage() was typically followed by a call to GetImageSize() or something similar, and so quite complex code behind DoGetImageIndex() for retrieving images was executed twice, which is very inefficient. This is why I made HasImage() deprecated.

**Comment by obones** [comment]
Ah yes, I see the issue with double calls.
Well, the only use case we have here does not fit this pattern here, so maybe we'll add it in our own derived classes then.
