### ISSUE TITLE
Editors are shifted to the right

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#838]
Hello,

I recently merged the latest GIT content into our working and since then, I noticed that all our editors are shifted to the right, like this:
![image](https://user-images.githubusercontent.com/1314739/47911791-b18bf400-de96-11e8-82f7-fe54ef3be0ab.png)

Debugging the code, I see that it comes from this code inside `TBaseVirtualTree.UpdateEditBounds`

        if offsets[ofsToggleButton] < 0 then
          Inc(offset, offsets[ofsToggleButton]);

Here, the value is `-12` which results in an offset of `-10` because `offsets[ofsLabel]` value is `2`
And 10 pixels is clearly the offset I'm seeing in our applications.

Have I missed a new property that needs to be set?

**Comment by joachimmarder** [comment]
Can this issue be reproduced with the Advanced demo project, Properties page?

**Comment by obones** [comment]
Here are the instructions:

In `VST3.Options.PaintOptions`, remove `toShowRoot`
Make column 1 the Main column
Add `coAllowFocus` in `Options` for `columns[1]` (Values)
Modify `TPropertiesForm.VST3InitNode` to add this code in the `ParentNode = nil` branch:

    Data := Sender.GetNodeData(Node);
    Data.ValueType := vtString;
    Data.Value := 'Hello';

Modify `TPropertiesForm.VST3Editing` to remove the test on `Node.Parent`

Now, start the application, set the focus on the top right `Hello` and press F2. You should get the following result:

![image](https://user-images.githubusercontent.com/1314739/47920148-a2ff0600-deb1-11e8-8f73-78852df43ca1.png)

As you can see, the edit is too far to the left, it overlaps the previous column.
Note that in our case, there are no tree lines because all we ever have are first level nodes.
We are also seeing it with a single column, in which case the editor left part is completely invisible as it is outside the client area.

**Comment by joachimmarder** [comment]
Those two lines in `UpdateEditBounds()` indeed look strange and I currently cannot explain why they are there. I commented them and the effect is gone. Can you please check on your side?

**Comment by obones** [comment]
Yes, removing them fixes the issue, but like you, I can't see why they were needed. Maybe the original author of revision f9a13957aba665ab7f0fca255bc2713a678915ce can shed some light on this?

**Comment by joachimmarder** [comment]
I asked him in his commit. I consider this issue solved now.
