### ISSUE TITLE
Image list returned by DoGetImageIndex is not used anymore

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#840]
`TBaseVirtualTree` defines the virtual `DoGetImageIndex` method and uses it to retrieve information about the image that should be painted for a given node and column.
In one of our derived classes, we override this method and have it return a custom image list under some conditions.
However, that image list is not used and no image is painted because, looking at the source, `ShowImages` is set to `False` inside `TBaseVirtualTree.PaintTree` with this code:

    ShowImages := Assigned(FImages) or Assigned(OnGetImageIndexEx);

And this does not take into account the value returned by our derived `DoGetImageIndex` method.
We discovered this while testing version 7.0.0, but I believe that this is a quite old bug because similar code is already present in 6.2.0.
Note that there is a comment inside `TBaseVirtualTree.CollectSelectedNodesRTL` that says this: 

    // Don't check the events here as descendant trees might have overriden the DoGetImageIndex method.

But it does not apply to the code right beneath it and has no impact on the `PaintTree` method. It's just interesting to see that someone, in the past, already had this in mind, even if it was not followed by any effect.

The easiest workaround is to give an empty image list instance for the `Images` property, but still, it would be nice if one did not have to remember this.

**Comment by joachimmarder** [comment]
I guess the code

`ShowImages := Assigned(FImages) or Assigned(OnGetImageIndexEx);`

is from the time when Virtual TreeView did not support multiple images lists. We may need to merge `CalculateVerticalAlignments()` and `TVTPaintInfo.AdjustImageCoordinates()`. As a first step, we should move the local var VAlign to the record `TVTPaintInfo`.

This refactoring will get a little tricky and for now you should stick with the workaround having an empty imagelist assigned.

**Comment by obones** [comment]
Yes, I agree, this is tricky to refactor and the workaround is fine by me.
I created the issue mostly as a "reminder" should someone else trip on it.

**Comment by joachimmarder** [comment]
This should now hopefully be fixed. I have no sample project with an overridden `DoGetImageIndex()` for testing.
