### ISSUE TITLE
EArgumentOutOfRangeException in PrepareDrag

### ISSUE THREAD

**Issue by tim-lebedkov** [JAM-Software/Virtual-TreeView#842]
There seems to be a bug in 5.5. I don't know how to reproduce it, but here is the stack trace

Argument out of range (EArgumentOutOfRangeException)
[004E0EF7] System.Classes.{System.Generics.Collections}TList<System.Classes.TCollectionItem>.GetItem
[009698E0] VirtualTrees.TVTHeader.PrepareDrag (Line 13068, "VirtualTrees.pas")
[00968394] VirtualTrees.TVTHeader.HandleHeaderMouseMove (Line 12566, "VirtualTrees.pas")
[009695CE] VirtualTrees.TVTHeader.HandleMessage (Line 12965, "VirtualTrees.pas")
[00987C75] VirtualTrees.TBaseVirtualTree.WndProc (Line 27342, "VirtualTrees.pas")
[0055D924] Vcl.Controls.TWinControl.MainWndProc
[004DBEF8] System.Classes.StdWndProc

This is probably the last line here:

procedure TVTHeader.PrepareDrag(P, Start: TPoint);

// Initializes dragging of the header, P is the current mouse postion and Start the initial mouse position.

var
  Image: TBitmap;
  ImagePos: TPoint;
  DragColumn: TVirtualTreeColumn;
  RTLOffset: Integer;

begin
  // Determine initial position of drag image (screen coordinates).
  FColumns.FDropTarget := NoColumn;
  Start := Treeview.ScreenToClient(Start);
  Inc(Start.Y, FHeight);
  FColumns.FDragIndex := FColumns.ColumnFromPosition(Start);
  DragColumn := FColumns[FColumns.FDragIndex];

**Comment by joachimmarder** [comment]
> There seems to be a bug in 5.5. 

Sorry, but I am no longer maintaining V5.5, because we are already on V7. Any chance that you upgrade?

**Comment by tim-lebedkov** [comment]
I would upgrade, although the corresponding code seems to be the same in 7. Can it be that ColumnFromPosition returns -1 and FColumns[...] fails or is this more complicated than this?

**Comment by joachimmarder** [comment]
> Can it be that ColumnFromPosition returns -1 and FColumns[...] fails or is this more complicated than this?

I can't tell if you don't supply a sample project that allows me to reproduce the problem. I don't remember any similar problems in the path months.

**Comment by joachimmarder** [comment]
Any news here regarding the update to V7 or the sample project?

**Comment by tim-lebedkov** [comment]
I replaced the code by V7, but it is not shipped yet and it is not reproducible on my computer.

**Comment by joachimmarder** [comment]
OK, please reopen the issue in case the problem still occurs.
