### ISSUE TITLE
Placing vertical scrollbar on right or left side

### ISSUE THREAD

**Issue by Saeid2016** [JAM-Software/Virtual-TreeView#846]
Hello,
Now the vertical scroll bar position in Virtual TreeView and all Windows controls is determined based on the type of language. In other words, if the language is a left to right language, the scroll bar is placed on the right of the control, yet if the language is written from right to left, the scroll bar is placed on the left. However, I think it would be better to determine the scroll bar position based on left- or right-handedness; namely, a right-handed person prefers to use the scroll bar on his right when using the mouse, while a left-handed person prefers the opposite. This can be added as a property to the Virtual TreeView so that the user selects the position based on his/her preference.

I look forward to receiving your feedback.

**Comment by joachimmarder** [comment]
> a right-handed person prefers to use the scroll bar on his right when using the mouse, while a left-handed person prefers the opposite.

Sorry, but I don't think so. Especially it would not make sense to change this for just one type of control, while all other controls and applications do it differently.

You may implement this in your own derived class, let me know if you need any method declared virtual for this.

**Comment by Saeid2016** [comment]
Hello, Thanks for answer. Now I use the following code to place VirtualTreeView vertical scrollbar on the right side in the RightToLeft bidimode (for right-handed person) and place it on the left side in the LeftToRight mode. (left-handed person)
```
procedure TForm1.Button2Click(Sender: TObject);
const
  LSB = WS_EX_LEFTSCROLLBAR;
var
  ExStyle: LONG_PTR;
begin
  ExStyle := GetWindowLongPtr(AVTV.Handle, GWL_EXSTYLE);

  // Check if RTL alignment specified for you component
  if AVTV.BiDiMode = bdRightToLeft then
  begin
    // If so, then exclude LSB-constant and allow Windows place 
    // scrollbar on the right side of window
    if (ExStyle and LSB) = LSB then
      SetWindowLongPtr(AVTV.Handle, GWL_EXSTYLE, ExStyle and not LSB);
  end
  else
  if AVTV.BiDiMode = bdLeftToRight then
  begin
    // The same as operation above but for LTR order
    if (ExStyle and LSB) <> LSB then
      SetWindowLongPtr(AVTV.Handle, GWL_EXSTYLE, ExStyle or LSB);
  end;
end;
```

It works correctly but there is a problem when tree is in grid mode and has header columns. Please see the screenshot.
![vst](https://user-images.githubusercontent.com/25425826/48966443-dfbca980-efe6-11e8-9a6f-f40db1bd9bcf.png)

**Comment by joachimmarder** [comment]
Having the scrollbar on the left on a LTR system is not a supported feature.

**Comment by Saeid2016** [comment]
> 
> 
> Having the scrollbar on the left on a LTR system is not a supported feature.

Thank you for your reply. What about having the scroll bar on the right in an RTL system? Is it possible to do so?

Thank you in advance.

**Comment by joachimmarder** [comment]
> What about having the scroll bar on the right in an RTL system? Is it possible to do so?

It should work. I never tested it after taking over Virtual TreeView, because I don't have a RTL system for testing.

**Comment by Saeid2016** [comment]
> 
> 
> It should work.

How I should place the vertical scrollbar on the right in RightToLeft bidimode? with my above code or another way? the above code works correctly but there is a problem when tree in grid mode and has header columns.

**Comment by joachimmarder** [comment]
This is a bug tracker and not a support forum. Please respect the guidelines on our homepage.
