### ISSUE TITLE
Error in building for 64-bit delphi

### ISSUE THREAD

**Issue by Logistes** [JAM-Software/Virtual-TreeView#847]
Hi

This is an ongoing problem. I am using Delphi 10.1 Berlin with Update 1. I just reinstalled Virtual Trees, downloaded from github. I followed the instructions and it all seemed to install correctly. I can compile and build our app in windows 32, but when I try to build it for 64-bit windows, a problem I have been having for a while continues: after processing about 82,000 lines I get
[dcc64 Fatal Error] ChEducationData.pas(7): F2613 Unit 'VirtualTrees' not found.
Clicking Find declaration does nothing in 64-bit but in 32-bit it takes me to the file.

IN both win32 and win64 modes, when I look at the Delphi Options Library Path, the source directory is included.

Can anyone offer any insights?

TIA,
Mark

**Comment by joachimmarder** [comment]
This is a bug tracker and not a support forum. Please respect the guidelines for submitting bugs on the project homepage.

This seems to be an issue with your Delphi installation, not with Virtual Treeview.
