### ISSUE TITLE
Current VST breaks checksupport

### ISSUE THREAD

**Issue by landrix** [JAM-Software/Virtual-TreeView#848]
current vst introduce in

`procedure AddSystemImage(IL: TImageList; Index: Integer);
`
this code

```
    if StyleServices.Enabled and StyleServices.IsSystemStyle then
      DrawThemeBackground(Theme, BM.Canvas.Handle, Details.Part, Details.State, Rect(0, 0, BM.Width, BM.Height), nil)
    else
      DrawFrameControl(BM.Canvas.Handle, Rect(0, 0, BM.Width, BM.Height), DFC_BUTTON, ButtonType or ButtonState);
```

this breakes checksupport, if checkboxes are placed in another column then 0. checkbox isn't clickable anymore. the code bevor works fine

`    DrawFrameControl(BM.Canvas.Handle, Rect(0, 0, BM.Width, BM.Height), DFC_BUTTON, ButtonType or ButtonState);
`

**Comment by joachimmarder** [comment]
Please respect the guidelines for submitting bugs on the project homepage and include detailed repro steps or a sample project. It is not obvious why using a different paint method breaks the click support.

> the code bevor works fine

From which version exactly was this code.

**Comment by landrix** [comment]
please see this sample

....sample.zip

I do not remember the previous version. I gradually took over the new code. That was the last piece after it stopped working.

**Comment by joachimmarder** [comment]
[sample.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2629844/sample.zip)

**Comment by joachimmarder** [comment]
This was introduced with pull request #830 .
@lorenzo-montesi : Can you comment please? And send a revised PR?

**Comment by lorenzo-montesi** [comment]
The problem is due to the option toThemeAware disabled. I'm trying the solution to set the correct part.
The main column different from 0 is not the reason.

**Comment by joachimmarder** [comment]
@landrix : Can you please confirm the fix?

**Comment by landrix** [comment]
thanks, now it works
