### ISSUE TITLE
Setting DefaultText to an empty string doesn't work

### ISSUE THREAD

**Issue by landrix** [JAM-Software/Virtual-TreeView#849]
Why was the saving of DefaultText removed?

```
procedure TCustomVirtualStringTree.DefineProperties(Filer: TFiler);
begin
  Filer.DefineProperty('WideDefaultText', ReadText, nil, False);
end;

```
i delete DefaultText in my forms, but now it is no longer considered. The value Node is set every time and i need to empty celltext every time.

the old setting:

`Filer.DefineProperty('WideDefaultText', ReadText, WriteText, FDefaultText <> 'Node');`

**Comment by joachimmarder** [comment]
Only the saving of the redundant `WideDefaultText` property was removed, please see and discuss in issue #828.

**Comment by landrix** [comment]
OK, in other words, setting DefaultText to an empty string doesn't work.

Simply add a VST on a form, set RootNodeCount > 0 and DefaultText to '' and start the application. 'Node' as Celltext is shown.

**Comment by joachimmarder** [comment]
Does your VTV code already include commit 0838277?

**Comment by landrix** [comment]
yes, now, but it don't helps

**Comment by joachimmarder** [comment]
Did you recompile the VTV designtime package and re-save the DFM?

**Comment by landrix** [comment]
Yes
you can also switch from dfm designer view to text view and back, DefaultText is reset to 'Node'
if you set DefaultText = '' manually in dfm text view and switch to design view and back to text view, the entry is going away.

**Comment by landrix** [comment]
The solution:

you should reintroduce TCustomVirtualStringTree.WriteText

and change this

```
procedure TCustomVirtualStringTree.DefineProperties(Filer: TFiler);
begin
  inherited;
  // Delphi still cannot handle wide strings properly while streaming
  //Filer.DefineProperty('WideDefaultText', ReadText, nil, False);
  Filer.DefineProperty('WideDefaultText', ReadText, WriteText, IsDefaultTextStored);
  Filer.DefineProperty('StringOptions', ReadOldStringOptions, nil, False);
end;

```
The property name WideDefaultText is bad luck.
But required for backward compatibility.

**Comment by joachimmarder** [comment]
> But required for backward compatibility.

Why exactly?

**Comment by landrix** [comment]
If you rename the property to DefaultText, all old ones are ignored

Not?

I must replace all WideDefaultText values in my dfm files. Right?

**Comment by joachimmarder** [comment]
No, if the reader finds the `WideDefaultText` property, it still calls `ReadText()`.

**Comment by joachimmarder** [comment]
Closing this issue, because as far as I can see it everything works as intended.

**Comment by landrix** [comment]
I do not think I'll send you an e-mail in German, maybe we misunderstood.

**Comment by joachimmarder** [comment]
So you are saying that a `WideDefaultText` virtual property value is not correctly converted into a `DefaultText` property? Can you send a sample project and include your Delphi version? I tested this on 10.2 and it was working.

**Comment by landrix** [comment]
my problem is, when i set DefaultText in form designer to an empty value, it isn't saved in dfm...
Node will be set as celltext again when the application is started. It is not empty.

Whether there is any WideDefaultText property involved or not, I can not see exactly. the latest version from here works different from my previous one.

**Comment by joachimmarder** [comment]
OK, I just re-checked the original issue and it seems that there is a bug in Delphi which does not store the empty string although `IsDefaultTextStored` returns `True`. It works if I use a string that consists of a single space. May I ask what is your use case for the empty string?

**Comment by landrix** [comment]
In the past, I always emptied DefaultText. And Celltext filled only when needed. If no solution is possible, I have to go through the many OnGetText events. Thank you

**Comment by joachimmarder** [comment]
OK, it seems to work if I define the property in code. Just committed this fix but I have only limited time to test today.

**Comment by landrix** [comment]
Yes, thanks, this fixes the issue.
