### ISSUE TITLE
TVirtualStringTree node image doesn't scale in high dpi display

### ISSUE THREAD

**Issue by Saeid2016** [JAM-Software/Virtual-TreeView#851]
Hello,
In 4K monitor node image doesn't scale. See the demo screenshot.
![vtree](https://user-images.githubusercontent.com/25425826/49460210-0dcf9400-f806-11e8-851e-164c6bec8836.png)

**Comment by joachimmarder** [comment]
If you want larger images, you need to use a larger ImageList. In Delphi 10.3 Rio this can be achieved conveniently using the new TVirtualImageList / TImageCollection.
TTreeView, TListView and TComboBoxEx for example behave the same way, so this is not a bug or limitation of Virtual TreeView.
