### ISSUE TITLE
Scrollbars are painted incorrectly using styles and PerMonitorV2

### ISSUE THREAD

**Issue by Daniel-Tr** [JAM-Software/Virtual-TreeView#852]
Repro from: https://quality.embarcadero.com/browse/RSP-

(Environment) Recent Windows 10 (like version 1709)
(Environment) two monitors with different scalings (like one at 100%, one at 200%)
Create a form with a TScrollBox and a TScrollBar and a VirtualTree
Activate PerMonitorV2 awarenes in custom manifest
Set a custom style in Application -> Appearance
Run application and move to the other monitor
Expected: All scrollbars are scaled correctly
Actual: Only TScrollBar seems to be scaled correctly. The scrollbars of the TScrollBox are drawn as scaled for the primary monitor (either not filling the complete controls area or drawing out of this area)

Bug has been fixed for Vcl components with Delphi 10.3,  but still occurs with the VirtualTree: 
![grafik](https://user-images.githubusercontent.com/22791435/49511439-77de4c80-f88b-11e8-9691-41017677e20d.png)

**Comment by pyscripter** [comment]
Vcl.Styles cannot be used in Delphi DPI Aware applications.  This has not been fixed in Delphi 10.3.  See for example https://quality.embarcadero.com/browse/RSP-22230.  In the comments you will see a workaround to create system DPI aware applications (not per Monitor).  I am using this workaround and I have no issues with VirtualTreeView scrollbars.

**Comment by joachimmarder** [comment]
Can be replicated using the `Advanced` sample project, a "PerMonitorV2" manifest and by moving the form to the other monitor. It does not occur for other scrollbars, so there might be an issue in the unit "VirtualTrees.StyleHooks".

**Comment by joachimmarder** [comment]
Can be replicated using the `Advanced` sample project, a "PerMonitorV2" manifest and by moving the form to the other monitor. It does not occur for other scrollbars, so there might be an issue in the unit "VirtualTrees.StyleHooks".

**Comment by joachimmarder** [comment]
Seems that the scrollbars are simply painted too small and the default drawing is visible in the background. Maybe some dimensions are not scaled properly according to the current monitor.

**Comment by pyscripter** [comment]
The VCL style images are not scaled.  You do not need a second monito to see that, the issue also occurs with one high-DPI monitor and DPI Awareness set to system.  It is not just the scrollbars, checkboxes, radio buttons etc are not scaled.  This is a known issue.  

https://github.com/pyscripter/pyscripter/blob/master/Source/VCL.Styles.DPIAware.pas  provides a work around by scaling all style bitmaps.  PyScripter  is System DPI aware and VirtualTrees show fine, including scrollbars.

**Comment by joachimmarder** [comment]
I am aware that VCL styles do not scale well. Still Virtual TreeView should not look that worse compared to other standard VCL controls, which look quite OK at 125% and 150% with Carbon theme or the dark Window 10 theme.
