### ISSUE TITLE
Hint window is too high and too narrow

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#853]
As I'm in the process of updating our copy of VTV, I'm trying to get the same behavior as I was having before. Most times, it's my code that needs changing, but I'm running in a issue where hints went from this:

![image](https://user-images.githubusercontent.com/1314739/49643350-bd2e8580-fa15-11e8-87e2-b87567bc93a0.png)

to this:

![image](https://user-images.githubusercontent.com/1314739/49643366-c6b7ed80-fa15-11e8-876f-811f463e278b.png)

Clearly, the original version was suffering from Issue #623 but now it is both too narrow and too high.
Debugging it, I discovered that `TVirtualTreeHintWindow` lost its `ActivateHint` override and so now, it's the one from the VCL that is called.
However, inside `THintWindow.ActivateHint`, one of the very first things that gets done is this:

    Inc(Rect.Bottom, 4);

I checked in the IDEs I have installed here, this is present in D2007, XE7, Seattle and Tokyo but I don't understand the rationale behind this code.
To workaround this code, I suggest removing 4 from the `Result.Bottom` value, the easiest location being where it already is increased by 6 in the "non tooltip" case of `TVirtualTreeHintWindow.CalcHintRect` because I'm not observing this in the `hmToolTip` case.
And to fix the width issue that appears in all cases here, I suggest adding the same 4 pixels to the `Result.Right` value, both in the `hmToolTip` and `else` branches, for example in the code that already adds `Tree.FTextMargin + Tree.FMargin` to it.

If that seems right to you, I'll create a pull request.

**Comment by joachimmarder** [comment]
This sounds like a good workaround and I would be happy to receive a tested PR. You may need to use ScaledPixels(4) instead of a hard coded 4 pixels so that this works in high-dpi scenarios.

**Comment by obones** [comment]
Here you go:
https://github.com/Virtual-TreeView/Virtual-TreeView/pull/854

**Comment by joachimmarder** [comment]
Thanks for the PR.
