### ISSUE TITLE
Fixed colors in GetColor

### ISSUE THREAD

**Issue by luebbe** [JAM-Software/Virtual-TreeView#858]
@pyscripter @joachimmarder 

After a long pause, I have just updated VirtualTreeView to the current head revision and noticed that the inactive/disabled colors don't work properly anymore.

The patch for #789 introduced a regression. The change from clBtnFace to clGray makes `StyleServices.GetSystemColor(FColors[Index]);` always return $808080, because clGray is not a system color.

You always have to take care to choose a matching pair of text/background. If one is fixed, this is not going to work. So I suggest trying to find a pair of matching system colors.

Also clGray doesn't match the default values of the published properties, which are still clBtnFace.

In addition I think that the else case in GetColor() `Result := StyleServices.GetSystemColor(FColors[Index]);` is an oversimplification. The previous implementation, which checked whether the color was default or user defined, returned better results, at least for our VCL Styles.

I will think this through and try to come up with a PR.

**Comment by pyscripter** [comment]
You can always remove toHideSelection to go back to the previous behaviour. (before the patch, toHideSelection was not respected).

clGray was chosen because it kind of works OK with most backgrounds dark or light.
It would be nice if you could come up with a better solution that works with all VCL styles.  I couldn't.

**Comment by luebbe** [comment]
Ok, after looking into it a bit further, I have a few more bits of information.
In my concrete case we disable the treeview while data is being fetched to prevent the user from selecting a new node in the mean time. Unfortunately the disabled SysColor of our VCL Styles is very close to clGray, which makes the disabled selection invisible during this time.

I have also noticed that UnfocusedColor isn't used anywhere in VirtualTreeViews. Does anyone know what the original intention of UnfocusedColor was? My guess is that it should have been the color of unfocused selection text.

My proposal is to use the pair UnfocusedColor/UnfocusedSelection*Color for text/background of unfocused selected nodes, even if they are disabled. As default colors I would suggest the system colors clInactiveCaptionText/clInactiveCaption. This should always return readable text, if the VCL Style is configured properly

If I don't change the behavior for disabled Text Color of unfocused nodes, the combination 
Text = clBtnShadow
Background = clnactiveCaption 
works reasonably well for the VCL styles that we use. I could just make the smaller change with the colors and leave the behaviour as it is.

**Comment by pyscripter** [comment]
>I have also noticed that UnfocusedColor isn't used anywhere in VirtualTreeViews. Does anyone know what the original intention of UnfocusedColor was? My guess is that it should have been the color of unfocused selection text.

Indeed

>I would suggest the system colors clInactiveCaptionText/clInactiveCaption.

This is what is used for the Window Caption (title).   You will find that for most VCL styles it does not provide suitable colors.  (I did try that).

>If I don't change the behavior for disabled Text Color of unfocused nodes, the combination
Text = clBtnShadow
Background = clnactiveCaption

For dark styles say "Windows 10 Dark" clBtnShadow is clBlack making it indistinguishable from the background of the VirtualTree.  Which stlyes do you use by the way?

**Comment by joachimmarder** [comment]
@pyscripter : Would you mind taking a look at the current state after merging the PR? Are your use cases working as expected?

**Comment by pyscripter** [comment]
As mentioned above clInactiveCaptionText/clInactiveCaption  are indented for another purpose than showing inactive selected list items. They are used for the inactive Window Caption (title). 

After the latest commits, for dark styles, I see no difference in the background color between unfocused selected and unfocused unselected nodes.   So these commits break existing behaviour.  I will look into these commits in more detailt and report back as to what goes wrong.

**Comment by joachimmarder** [comment]
@pyscripter: Thanks. I don't use VCL styles in my projects so I lack a little experience here when it comes to the details.

@luebbe: Have you tried this with a dark style like Carbon?

**Comment by pyscripter** [comment]
After looking at the code in some detail...
- Overall the changes introduced by @luebbe are useful and make the code a lot cleaner.  
- The only question is about the default values of some of the colors.
- UnfocusedColor is used as the font color of unfocused selected nodes, so it should probably be renamed to UnfocusedSelectionTextColor
- In Windows Explorer the text color of focused and unfocused selected items is the same (clHighlightText).  This is also true in the dark theme of Windows Explorer available with the Windows October update.  (by the way have you tried that?).  It should probably also be the default in VT.
- clInactiveCaption/clInactiveCaptionText  works well in many themes including a few dark styles.
- However, in many dark styles clInactiveCaption is the same as clWindow  and in some clInactiveCaptionText is the same as clWindowText (eg. Windows10 Dark).  This effectively hides the selection when unfocused. 
- I can get the previous appearance by setting UnfocusedSelectionColor and UnfocusedSelectionBorderColor to clGray and UnfocusedColor to clHighlightText.  This is almost by accident since clHighlightText is white in most styles.  (note that in the last update StyleServices.GetSystemColor is not called for colors different to default colors - I am not sure about this @luebbe - what was the purpose of this change?).

**Comment by luebbe** [comment]
> After looking at the code in some detail...
> 
>     * Overall the changes introduced by @luebbe are useful and make the code a lot cleaner.

So we got a good starting point here :)

>     * The only question is about the default values of some of the colors.
> 
>     * UnfocusedColor is used as the font color of unfocused selected nodes, so it should probably be renamed to UnfocusedSelectionTextColor
I thought the same, but wouldn't this break streaming the dfm file to/from disk? So I didn't touch it.

>     * In Windows Explorer the text color of focused and unfocused selected items is the same (clHighlightText).  This is also true in the dark theme of Windows Explorer available with the Windows October update.  (by the way have you tried that?).  It should probably also be the default in VT.
No, I haven't tried that. If clHighlightText is the official default, we can change back to using SelectionTextColor instead of UnfocusedColor and don't distinguish between focused and unfocused selected node text.
I had the problem that clHighlightText (white) got almost invisible on our light style which has a light gray for unfocused selection.
![image](https://user-images.githubusercontent.com/3872576/50507786-3f432480-0a7f-11e9-8eb6-ad2558a0cd1c.png)
Using SelectionTextColor

![image](https://user-images.githubusercontent.com/3872576/50507769-30f50880-0a7f-11e9-83ae-064fe02f2ea8.png)
Using UnfocusedSelection

This is the reason why I was looking for a different pair of contrast colors. In that case I have to talk to our designers to get a different unfocused highlight background.

>     * clInactiveCaption/clInactiveCaptionText  works well in many themes including a few dark styles.
> 
>     * However, in many dark styles clInactiveCaption is the same as clWindow  and in some clInactiveCaptionText is the same as clWindowText (eg. Windows10 Dark).  This effectively hides the selection when unfocused.
OK, that means I have to add more styles to my test project. But doesn't that also mean that the VCL style in question is flawed? clInactiveCaptionText should always be readable on clInactiveCaption. Same as clWindowText should always be readable on clWindow. I guess the style designer forgot to check the SysColors before saving the Style.
 
>     * I can get the previous appearance by setting UnfocusedSelectionColor and UnfocusedSelectionBorderColor to clGray and UnfocusedColor to clHighlightText.  This is almost by accident since clHighlightText is white in most styles. 
I still recommend not using fixed colors at all, because clGray will be clGray no matter if you choose a red, green or blue VCL style.

The following screenshot shows the original use case, which triggered this issue, after my PR has been applied. 
![image](https://user-images.githubusercontent.com/3872576/50507931-e45dfd00-0a7f-11e9-888a-afbca7741ec2.png)
The state of the node is focused + disabled while data is being fetched. The text got 95% invisible (on light and dark design), because clGray was used before.

> (note that in the last update StyleServices.GetSystemColor is not called for colors different to default colors - I am not sure about this @luebbe - what was the purpose of this change?).

My reasoning was that I either have a user defined color or a default color. 

- User defined should have precedence over everything. 
- A default color right now always is a system color. Calling StyleServices.GetSystemColor only makes sense if the source is a system color and style services are enabled.

But you are right. If the user chooses system colors which are different from the default, calling StyleServices.GetSystemColor still makes sense. I will revert this check.

If we revert to SelectionTextColor instead of UnfocusedColor, UnfocusedColor becomes obsolete again. I have no problem with that. Probably my case can also be remedied by adjusting the VCL style, but it may be better to have a separate text/background color pair for this case. So I'd still vote for using UnfocusedColor.

**Comment by pyscripter** [comment]
@luebbe Wow! A designer produced Vcl Style! Thanks for the PR #864.

**Comment by luebbe** [comment]
> @luebbe Wow! A designer produced Vcl Style! Thanks for the PR #864.

Yes, we try to keep the appearance of our applications consistent across dev environments and frameworks. So the C# Tools (should) look similar to the Delphi ones.

**Comment by pyscripter** [comment]
I think it does no harm to keep UnfocusedColor and possibly at some point renaming it to UnfocusedSelectionTextColor.  A comment in the code as to way this color is used would be helpful to users that browse the code.

The combo UnfocusedColor-UnfocusedSelectionColor/UnfocusedSelectionBorderColor indeed produces readable text and it is a minor issue that with some styles is indistinguishable from unselected nodes.

Changing the colors to clHighlightText, clGray/clGray  at design time results in the previous behaviour and in my experience gives reasonably good results and mimics to an extent Windows Explorer. 

GetColor can at some point be refined to check whether the style is dark or light and provide color values that mimic Windows Explorer unfocused selection more closely.

So overall I think we can put the issue at rest for now.

**Comment by joachimmarder** [comment]
OK, thanks for your efforts here!

**Comment by luebbe** [comment]
@pyscripter Thanks for your review!

**Comment by joachimmarder** [comment]
@luebbe @pyscripter: Would you mind taking a look at ´the new issue #868? It is also related to colors and maybe your experience when fixing this issue helps there too. Thanks in advance.
