### ISSUE TITLE
Is there a default format settings config for Virtual-TreeView?

### ISSUE THREAD

**Issue by luebbe** [JAM-Software/Virtual-TreeView#859]
Every time I work on VTV, I have to be extremely careful not to hit Ctrl+D when editing in order to avoid reformatting everything. 
Are you using one of the standard format settings distributed with Delphi or are you using your own?
If there is a format settings config, could you please append it to the developer guide in the Wiki in order to facilitate contributions?

**Comment by joachimmarder** [comment]
No, this project has evolved over 20 years and got contributions by dozens of developers. Someone started to write guidelines in the [Wiki](https://github.com/Virtual-TreeView/Virtual-TreeView/wiki/Developer-Guidelines) a while ago, but these are neither final nor enforced.

But who will take the time to reformat all that code? And doing so will require a monster commit that breaks the history / blame for the files.

**Comment by luebbe** [comment]
Hmm, I'll try the standard format settings that come with Delphi and see how big the diff becomes. Maybe I can minimise it.

**Comment by luebbe** [comment]
Hi Folks,
Would you mind trying out the attached formatter config on VirtualTress.pas?

Rename the file from .config.txt to .config. I added the .txt extension in order to be able to upload it to GH.
[Formatter_VirtualTreeView.config.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2714973/Formatter_VirtualTreeView.config.txt)

There are obviously capitalization, indentation and whitespace changes. If you turn off highlighting of whitespace changes in your diff tool, there are only around 200 changed lines. Not bad for a file with almost 35K lines.

Some things are better after running the formatter, some are worse, because they were manually adjusted. We have to decide if the consistency gain outweighs the tradeoff.

**Comment by joachimmarder** [comment]
> If you turn off highlighting of whitespace changes in your diff tool, 

Well, for Git and blame such a line has changed anyway, even if you turn off this option in your diff tool.

> there are only around 200 changed lines. 

WinMerge reports 1773 differences here, I guess that the number of changed lines is much higher.

And working with multiple formatter configs does not seem very convenient to me.

**Comment by luebbe** [comment]
> And working with multiple formatter configs does not seem very convenient to me.

Yes, that would also be the killer for me ...
We can close this.
