### ISSUE TITLE
Proposal: change the color number in TVTColors to enum

### ISSUE THREAD

**Issue by luebbe** [JAM-Software/Virtual-TreeView#860]
Is there any reason not to change the color numbers 0..16 in TVTColors to an enum e.g.:
```
    TVTColorEnum =(cDisabledColor, cDropMarkColor, cDropTargetColor, cFocusedSelectionColor,
      cGridLineColor, cTreeLineColor, cUnfocusedSelectionColor, cBorderColor, cHotColor,
      cFocusedSelectionBorderColor, cUnfocusedSelectionBorderColor, cDropTargetBorderColor,
      cSelectionRectangleBlendColor, cSelectionRectangleBorderColor, cHeaderHotColor,
      cSelectionTextColor, cUnfocusedColor);

```
and use this instead of the numbers? (Backwards compatibility, persistence, ...)?
It would save some comments and you always know which color you are currently referencing.

**Comment by joachimmarder** [comment]
A good reason not to use an enum does not come to my mind.

**Comment by luebbe** [comment]
Ok, then I'll do this in a separate PR
