### ISSUE TITLE
Autoscale only changes node height in nodes visible on screen

### ISSUE THREAD

**Issue by tfrost** [JAM-Software/Virtual-TreeView#861]
If I move my application window to a screen with different resolution,  the visible nodes scale correctly, but when I next scroll the tree vertically, the nodes that scroll into view still have the node height that that they would have had on the former screen.

SetNodeHeight called from ChangeScale appears not to care about adjusting the height of non-visible nodes, but I cannot seem to find a way to modify it so that it works for all nodes.  My workaround is to add a separate FormAfterMonitorDpiChanged function to walk the tree and set all the node heights and adjust the scrollbar.

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting bugs on the project homepage and include a sample projects that allows to reproduce the issue, or provide steps how to modify one of our demo projects.

> SetNodeHeight called from ChangeScale appears not to care about adjusting the height of non-visible node

Looking at `SetNodeHeight()` I see only one condition that could prevent the assignment of the given value: `toReadOnly in FOptions.FMiscOptions`

Is this the case for you? 

This condition does not make much sense to me.

**Comment by tfrost** [comment]
Thanks for your swift response.  I can create a demo project if you are unable to verify this issue, although the effect should be visible in almost any tree if you have the ability to change screen DPI after program startup.  No, the `toReadOnly ` option is not set.  Yes, the height assignment is correctly made, and all the nodes visible in the window change height as expected when the main window has been moved to another monitor with different DPI.  But on scrolling the tree contents on the new monitor, the nodes scrolled into view do not have the correct height: they are either too high or the text is truncated with only the top of each character shown

As I said, there is a simple workaround, but it would be better if the change of DPI operation in the VT component handled this internally, by preparing ALL existing nodes for the correct DPI, ready for when they next become visible.

**Comment by joachimmarder** [comment]
> I can create a demo project if you are unable to verify this issue, although the effect should be visible in almost any tree if you have the ability to change screen DPI after program startup. 

Well, in this case it would not be necessary to create a sample project, but you can, as I wrote in my previous post and on the project homepage, just write that it occurs with the `Advanced` project. But of course I tried that before responding. I also checked our current TreeSize nightly build for the problem, but all looks good. Please also include the Delphi and the Virtual TreeView version that you are suing.

>  Yes, the height assignment is correctly made, 

If this is true, what does your workaround make differently compared to `TBaseVirtualTree.ChangeScale()`?

**Comment by tfrost** [comment]
Thanks to your insights. I now know what is happening.  The difference between ChangeScale and my workaround is that the former iterates using GetNextInitialized and that later is using recursive GetNextSibling.  When I first open the program and then move the window to another screen, I have discovered that only the visible nodes are initialized.  If I scroll down slowly with down-arrow, each node height is displayed correctly.  If I spin the mouse wheel to scroll, a few dozen are correct, then uninitialized items start to appear; after this has happened there are no more correct-height items on scrolling down.  With a very simple test application displaying only a node caption, it is hard to scroll fast enough to catch any uninitialized items.

I am happy to stay with my workaround because it is simple and plenty fast enough to set a single value in 4000 or so nodes.  Apologies for not stating the issue clearly enough from the start, and thanks again.

**Comment by joachimmarder** [comment]
> I have discovered that only the visible nodes are initialized.

This is done by intention for performance reasons. It should not matter as the remaining node's height get initialized with the value of `DefaultNodeSize`, which is scaled as well in `ChangeScale()`. 

> With a very simple test application displaying only a node caption, it is hard to scroll fast enough to catch any uninitialized items.

What would you say is the relevant difference to your project?

> I am happy to stay with my workaround

That's a pity, I would have tried fixing it, but I can't spend hours on seeking a repro. So should I close this issue?

**Comment by tfrost** [comment]
Unfortunately you may have to close, because It is not practical either to let you have the actual program or for me to build a sample one, because it depends on several thousand folders and files.  

I do not know exactly why a simple test program did not demonstrate the issue but our real applications (both stringtree and drawtree) do so.  We do explicitly set the node height to the default on creating each node, which may be unnecessary; and in `OnMeasureItem`, I think because at one time we used different font sizes in different node types. My simple test program did neither of these things.

However I think you may be mistaken that the remaining nodes' heights "should be" initialized with `DefaultNodeSize`.  I experimentally added a line in `TBaseVirtualTree.InitNode()` with `nodeheight := defaultnodeheight;`, and this change immediately appeared to solve the problem: it fixed the height of all the nodes I scrolled into view after moving the window to another monitor.  Unfortunately this one-line change is not a complete solution, because my workaround recursive loop also fixes the `totalheight` of the node and then updates the scroll bar.  Without doing this my tree is either truncated or ends up with blank space at the foot, depending on direction of movement.  And since all of our applications using VT have a uniform node height for all nodes, I have no simple means of testing whether this would all work with different node heights, or with the many, more complex, node options which we do not use.

**Comment by joachimmarder** [comment]
> I experimentally added a line in TBaseVirtualTree.InitNode() with nodeheight := defaultnodeheight;, and this change immediately appeared to solve the problem

Indeed, the `DefaultNodeHeight` is assigned in `MakeNewNode()`, not in `InitNode()`. This is done to have a reasonable value assigned to the `NodeHeight` member for scrollbar calculation. So a solution would be to not just scale all initialized node, but all nodes.

**Comment by joachimmarder** [comment]
Would you mind giving the latest GitHub master a try?

**Comment by tfrost** [comment]
Thanks - that seems to have done the trick!  Workaround removed.

**Comment by joachimmarder** [comment]
The code change has some negative side effect: It initializes previously non-initialized nodes and changes the check-states. Can be seen with `Advanced` sample project, page "General Abilities".
