### ISSUE TITLE
Regression - Erratic behaviour of scroll bas with Vcl Styles

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#863]
This is a regression introduced by the fix to #852.
To reproduce: 
- compile and run the Advanced Demo with Vcl styles.  
- in the first demo press "Add nodes to the root"
- try to scroll down with the mouse by grabbing the slider.

Issue:  The scrollbar jumps to the end ahead of the mouse.
The problem appears in trees with many items.

**Comment by joachimmarder** [comment]
I don't understand why much code was copied from the VCL class `TScrollingStyleHook` into the style hook of the Virtual TreeView. It would be important to deduplicate the code, because over time it will differ.

**Comment by joachimmarder** [comment]
@pyscripter : I am now no longer able to reproduce the problem. Could you please make a test too?

**Comment by pyscripter** [comment]
Great!  Thanks.  Now it works like before.  So I am closing the issue.

However, there is a minor issue with the parent TScrollingStyleHook I have just noticed. 
As before;
-  compile and run the Advanced Demo with Vcl styles.
- in the first demo press "Add nodes to the root"

and now:
- press with the mouse the scroll tab
- drag the mouse upwards and above the scroll tab (nothing happens)
- now without releasing the mouse start moving the mouse downwards.   The VT starts scrolling immediately and before the mouse enters the client area. When the mouse enters the client area it is not aligned with the tab.

Do the same with the system style to see the difference or try with the Windows File Explorer.

This is an issue of the parent class.   The previous implementation had the same issue.  

The styled Delphi IDE has the same issue.  Open VirtualTrees.pas and try the above steps with the editor scroll bar.  I will report this to https://quality.embarcadero.com/.

Update: Reported as [RSP-23147](https://quality.embarcadero.com/browse/RSP-23147)
