### ISSUE TITLE
Assigning OnGetImageIndexEx forces ShowImages and ShowStateImages true

### ISSUE THREAD

**Issue by GregStevenson** [JAM-Software/Virtual-TreeView#865]
Prior to Revision 871 ShowImages would only be true if FImages was assigned  and ShowStateImages would only be assigned if FStateImages was assigned. One could assign OnGetImageIndex and still control which images would be assigned. Now having OnGetImageIndex assigned forces ShowImages AND ShowStateImages to True even if this is not desired and there is now way to force either to its original behavior. It seems that there should be two properties like AllowGetImage and AllowGetStateImage that must be true along with OnGetImageIndexEx being assigned inorder for it to enable ShowImages and ShowStateImage respectfully.

**Comment by joachimmarder** [comment]
> Prior to Revision 871 

You mean the commit of June 2016?

> Now having OnGetImageIndex assigned forces ShowImages AND ShowStateImages to True even if this is not desired and there is now way to force either to its original behavior.

That should be possible by implementing the event handler of the `OnGetImageIndex` event accordingly. Here you have full control over which images are displayed, or if no images are displayed.

> there should be two properties like AllowGetImage and AllowGetStateImage that must be true along with OnGetImageIndexEx 

That would be a breaking change for all developers and is a no-go.

**Comment by joachimmarder** [comment]
Closing this issue as the reporter supplied no additional info and the referred commit is quite old.
