### ISSUE TITLE
TBaseVirtualTree.ChangeScale() can cause AV because of destroyed objects

### ISSUE THREAD

**Issue by SvenAbeln** [JAM-Software/Virtual-TreeView#866]
Every VirtualTreeView, configured with CheckImageKind = ckSystemDefault, will have a reference to the global image list 'SystemCheckImages'.
TBaseVirtualTree.ChangeScale() of one tree will now destroy the global list, create a new one and update his own reference, but all other existing VirtualTreeViews will still have a reference to the old and now destroyed list.

Using global image lists will be a problem, when using treeviews on multiple monitors with different scaling, because the image lists are only scaled for one monitor.

**Comment by joachimmarder** [comment]
@SvenAbeln : Would you mind testing the fix? I have no multi-windows application at hand for testing.

**Comment by SvenAbeln** [comment]
I just build a simple test application and it seems to be working now:
- no access violation
- checkboxes for trees on different monitors are scaled correctly
