### ISSUE TITLE
Text color of a selected node does not adapt to the high contrast mode in Windows when using toUseExplorerTheme

### ISSUE THREAD

**Issue by Daniel-Tr** [JAM-Software/Virtual-TreeView#868]
* Activate high contrast mode in Windows Settings
* Start the advanced demo project, tab "Painting like in Windows XP" (where toUseExplorerTheme is set)
* Select a node
-> High contrast mode indicates a black text color, white one is used

![grafik](https://user-images.githubusercontent.com/22791435/51527099-1a4e9100-1e34-11e9-88d6-3259775ba4bf.png)

**Comment by joachimmarder** [comment]
As color of the selected node currently `clWindowText` is used, but I guess it should be `clHighlightText`. This is a result of an if statement in `InitializeTextProperties()` that tests for `tsUseExplorerTheme`.

While having a code path for `tsUseExplorerTheme` works good for the normal Windows theme, it produces wrong results for the high contrast theme, which behaves more like the classic style of Windows 2000. Two solutions come into my mind:
* Take the luminance of the selection background into account and make sure to choose a text color that has enough contrast to that it.
* Find a way to query the selected text color of the Explorer theme from the system. 
* Check if high contrast theme is enabled.

In any case we should centralize the if statements for `tsUseExplorerTheme` in `GetSelectedNodeFontColor()`.
