### ISSUE TITLE
Possible exception with a multiple monitor setup with different dpi scalings

### ISSUE THREAD

**Issue by Daniel-Tr** [JAM-Software/Virtual-TreeView#870]
Repro:
* Set primary monitor to 150% scaling
* Set secondary monitor to 200% scaling
* Move app window with a VirtualTree to secondary monitor
* Show other VirtualTrees (e.g. for a secondary/temporary view)
* At some point, an exception occurs, related to the scaling of the UtilityImages

Observations:
* The check performed in TBaseVirtualTree.ChangeScale doesn't catch this change, as it would only be valid if D = 96 (design time DPI). On second scaling (M = 192, D = 144), the check would expect an image height of 21, instead of 32. 
* The ScaleImageList method only scales up, but never down.
* With each new VirtualTree instance, the image width (and height) of the UtilityImages increases with the scaling factor (double with this setup).

Potential quick fix: 
Replace the two lines (see #796)
`if UtilityImages.Height <> MulDiv(UtilityImageSize, M, D) then ScaleImageList(UtilityImages, M, D);`
with 
`if UtilityImages.Height < MulDiv(UtilityImageSize, M, USER_DEFAULT_SCREEN_DPI) then ScaleImageList(UtilityImages, MulDiv(UtilityImageSize, M, USER_DEFAULT_SCREEN_DPI), UtilityImages.Height);`

(Downside(s) of this solution: 1. The list is still being scaled up only. 2. This check is still only valid if parameter M specifies the absolute DPI value to scale to.)

**Comment by joachimmarder** [comment]
Related to #866 and  #867. I guess we will need to use one ImageList per instance.

**Comment by joachimmarder** [comment]
Removed UtilityImages and replaced them with DrawArrow().
