### ISSUE TITLE
GetChildCount does not check if children were initialized

### ISSUE THREAD

**Issue by Dave-Novo** [JAM-Software/Virtual-TreeView#871]
Hello,
I notice that TBaseVirtualTree.GetChildCount does not check if the passed in Node has called the OnInitChildren event before returning node.ChildCount.  I believe the code could be improved as follows
```

function TBaseVirtualTree.GetChildCount(Node: PVirtualNode): Cardinal;

begin
  if (Node = nil) or (Node = FRoot) then
    Result := FRoot.ChildCount
  else begin
    if not ChildrenInitialized(Node) then     //<-----
      InitChildren(Node)                             //-<----
    Result := Node.ChildCount;
  end
end;
```
Is there any problem with adding the indicated lines above

**Comment by joachimmarder** [comment]
I think this makes sense.

**Comment by Dave-Novo** [comment]
Looking at the code today, I notice there is already a ValidateNode method. So it seems like it might be appropriate to call ValidateNode before getting the ChildCount. However, in order to Validate a current node, I think you would have to make sure the nodes parents are validated. i.e. in order to validate a child node, you often have to refer to the nodes .Index in relation to the parent. So if the parent is not validated, you will not be able to validate yourself.

So I think the idea would be if trying to get a node's childcount, you have to go up and make sure all the immediate parents are valid, then call validateNode on yourself.

**Comment by pyscripter** [comment]
Doesn't this violate the lazy data access principle of VT?   Child count should return the current child count.  For non-initialized nodes this is zero.   You do not want to accidentally initialize child nodes.   This may lead to deep or infinite recursion with some data structures. The user should have control as to when a node is initialized, e.g when expanding a a node etc.

The following can go into user code if needed.

```
   if not ChildrenInitialized(Node) then     //<-----
      InitChildren(Node)                             //-<---- in
```

This is why ivsHasChildren and vsHasChildren exist.  You can mark a node as having children without creating the child nodes.  If you do want to initialize the childrent you include the ivsExpanded in IntialStates.

**Comment by Dave-Novo** [comment]
The lazy access principle is just that, nodes are not initialized until someone **access it**. IMHO It should not matter if the node is **accessed** by expanding it, or the node is **accessed** because a programmer requested the child node count. I would not agree that the node count of a non-initialized node is zero. The child node count is undefined at that point. If the original developers has decided to initialize the node count to -1 as a "uninitialized" value instead of 0 this would be more clear I suppose.

Of course you can mark a node as ivsHasChildren or vsHasChildren. But I am asking for the ChildNodeCount, therefore I would expect the true value to be rerturned. If I just wanted to check if the node was initialized or not, I would check different variables.

**Comment by pyscripter** [comment]
This change may break existing code.  Think for example an event handler (mouse over, image index, hint or whatever) that uses ChildCount.  Suddenly now you get nodes expanding out of the blue.  With due respect, this "obvious" change/addition, was not in the code for a reason.

**Comment by Dave-Novo** [comment]
Calling ValidateNode has nothing to do with expanding it. Nor does my suggestions above for Childcount. They would just initialize the data structures of the node, to return the proper child count, without touching the expanded state at all.

p.s. (off topic) I am really looking forward to trying out your python integration. We already have R integration in our software, and python integration would be awesome

**Comment by joachimmarder** [comment]
> the idea would be if trying to get a node's childcount, you have to go up and make sure all the immediate parents are valid

Actually that should never be needed if you follow the virtual paradigm. How could the child count of a node be of interest if the parent node is not initialized? Can you outline your use case?

And I find it interesting that code like this seemed never necessary in Virtual TreeView in the past 20 years.

**Comment by Dave-Novo** [comment]
The use case is from a testing system. We basically do some stuff to our underlying object model, refresh the VST and then ensure the proper nodes are present.

Looking more closely, it seems the problem stems from differences in the initializing of child nodes during iterating.
For example, you can see that GetFirstChild calls InitChildren directly. So we are okay so far.

But once we are on the first child, we call GetNextSibling. As you can see, GetNextSibling calls InitNode but not InitChildren.

However, looking into InitNode, it seems that InitNode only calls InitChildren if the node is expanded. So checking the childCount of nodes that we obtained by traversing using GetNextSibling are all zero, since the children are not initialized.

I think it should be consistent that traversing the nodes, by anyone of the traversal methods should ensure the children are initialized. It does not make sense that the first node in a branch (obtained using getFirstChild of the parent) should have the children initialized, but the rest of the nodes in the branch (obtained using GetNextSibling) should not have them intialized.

**Comment by joachimmarder** [comment]
Sorry, but in the description of your use case I don't see a point where it would be necessary to initialize parent node recursively. It would be sufficient to `InitChildren()` in `GetChildCout()`. Or did I miss something?

**Comment by Dave-Novo** [comment]
You are correct. Based on my recent understanding above, there is no need to initialize parent recursively. I believe the fix here is to fix GetNextSibling (and all iterator methods) to initialize the children as they are iterating. That way, they all have consistent behavior, and that way you ensure that any nodes that you reach via the iterator methods are initialized properly. You can probably leave GetChildCount alone, (or maybe just raise an exception if the node is not initialized when calling GetChildCount) but if the iterators are fixed, there should be no way of getting to an uninitialized node.

**Comment by joachimmarder** [comment]
> I believe the fix here is to fix GetNextSibling (and all iterator methods) to initialize the children as they are iterating

Sorry, but I disagree. I think children should be initialized when they are actually accessed. That would be in `GetChildCount()`.

**Comment by Dave-Novo** [comment]
Ok, that is fine. Then you should remove the initialization from GetFirstChild. Whatever solution you choose, it should be consistent among the iterators right?

**Comment by joachimmarder** [comment]
One more argument why I think this change was right: Before `HasChildren[Node]` may have returned `True` but `ChildCount[Node]` while returned 0, which looks very inconsistent.
