### ISSUE TITLE
TBaseVirtualTree.AddToSelection changes FocusedNode and can cause an exception

### ISSUE THREAD

**Issue by Memnarch** [JAM-Software/Virtual-TreeView#874]
procedure TBaseVirtualTree.AddToSelection changes FocusedNode, which it didn't before(we updated from V5.x to 7.1). However setting a focused node while the tree has no parent, will cause a "Control has no Parent Window" exception. Because down the line ScrollIntoView is triggered. There are situation where a ui is prepared without being put on the main ui itself.

Maybe FocusedNode in general should not fire that issue in general, but the tree should restore the focused node once the window is created for the first time? Or ScrollIntoView should just not explode, but the tree should scroll into focus when the window is created for the first time and a node is focused?

**Comment by joachimmarder** [comment]
Can you please post the call stack of the exception? I have no repro project at hand.

**Comment by joachimmarder** [comment]
closing this issue for housekeeping as reporter did not provide more details.

**Comment by Memnarch** [comment]
Sorry for not providing something earlier.
This did not crash before. And while it looks strange as an example, it simulates what the issue is. 
```
procedure TForm5.Button1Click(Sender: TObject);
var
  LTree: TVirtualStringTree;
  LNode: PVirtualNode;
begin
  LTree := TVirtualStringTree.Create(nil);
  try
    LNode := LTree.AddChild(nil);
    LTree.AddToSelection(LNode, false);
  finally
    LTree.Free;
  end;
end;
```

**Comment by joachimmarder** [comment]
Exception looks like this:

```
exception class    : EInvalidOperation
exception message  : Control '' has no parent window.

main thread ($61e4):
005b8db3 +0b3 Advanced.exe Vcl.Controls    9551  +13 TWinControl.CreateWnd
006f0e8b +033 Advanced.exe VirtualTrees   18478   +2 TBaseVirtualTree.CreateWnd
005b933a +016 Advanced.exe Vcl.Controls    9732   +3 TWinControl.CreateHandle
005bd2d8 +01c Advanced.exe Vcl.Controls   12360   +4 TWinControl.HandleNeeded
005bd2e5 +005 Advanced.exe Vcl.Controls   12366   +1 TWinControl.GetHandle
005bd475 +009 Advanced.exe Vcl.Controls   12417   +1 TWinControl.GetClientRect
005b3558 +00c Advanced.exe Vcl.Controls    5899   +1 TControl.GetClientWidth
00703255 +159 Advanced.exe VirtualTrees   26814  +40 TBaseVirtualTree.GetDisplayRect
0070be34 +0f4 Advanced.exe VirtualTrees   31422  +18 TBaseVirtualTree.ScrollIntoView
006f3b72 +21e Advanced.exe VirtualTrees   19819  +31 TBaseVirtualTree.DoFocusNode
006e8483 +027 Advanced.exe VirtualTrees   14517   +2 TBaseVirtualTree.SetFocusedNode
006ef4a4 +074 Advanced.exe VirtualTrees   17807   +9 TBaseVirtualTree.AddToSelection
00711c40 +02c Advanced.exe VirtualTrees   34246   +1 TCustomVirtualStringTree.AddToSelection
```

GetDisplayRect() forces handle creation which requires a parent control.

**Comment by Memnarch** [comment]
If get displayrect is the issue, then isn't the second overload of ScrollIntoView potentially affected aswell?

**Comment by joachimmarder** [comment]
Theoretically yes, like any other of the many `GetDisplayRect()` calls. I would like to focus on them that actually make problems.
