### ISSUE TITLE
Severe bug in latest release - basic functionality is broken

### ISSUE THREAD

**Issue by JJD2K** [JAM-Software/Virtual-TreeView#879]
FolderTree.Selected[pNode] := true;

Causese a scary assertion at line 14964 in released version:
         Assert(Assigned(FRangeAnchor), 'We assume that FRangeAnchor is always assigned here. If so, delete the following 2 code lines.');
        if FRangeAnchor = nil then
          FRangeAnchor := Node;

in 
procedure TBaseVirtualTree.SetSelected(Node: PVirtualNode; Value: Boolean);

What the hell is this? Such code should never reach a release.

**Comment by joachimmarder** [comment]
Sorry for that, this has been corrected in the latest source code. I had to refactor ancient and non-commented code and using this assertion I tried to check if further code simplification would be possible.

Compiling without assertion, which is the default setting for release builds, also circumvents the problem.
