### ISSUE TITLE
Draw the dropdown button bigger

### ISSUE THREAD

**Issue by supasoft** [JAM-Software/Virtual-TreeView#887]
plz
![2019-03-26_14-53-44](https://user-images.githubusercontent.com/40602544/54995516-f7795e00-4fd7-11e9-87a4-67561a2e5c7f.png)

**Comment by joachimmarder** [comment]
That was more difficult that it seemed if you want proper dpi scaling and proper VCL theme support. Let me know what you think.

**Comment by supasoft** [comment]
Thank you very much! Can you add a button click animation? it was before.
![2019-03-27_17-20-21](https://user-images.githubusercontent.com/40602544/55083534-bdca5500-50b4-11e9-8b3a-8c5d31e7a5fd.png)

**Comment by supasoft** [comment]
Compared the old and new designs. Old like more. The arrow is gray and the button is larger.
![2019-03-27_17-25-29](https://user-images.githubusercontent.com/40602544/55084415-354cb400-50b6-11e9-9a8f-1e1604f94fa4.png)

**Comment by joachimmarder** [comment]
Well the old one was a fixed sized bitmap which did not dpi-scale at all. The new one is sized according to the size of of checkboxes. I can't make it larger, otherwise it would be painted in the selection:
![grafik](https://user-images.githubusercontent.com/10615289/55093151-26650200-50b4-11e9-81b6-15973579592f.png)

I chaged the color of the arrow to gray.

**Comment by joachimmarder** [comment]
> Can you add a button click animation? 

I tweaked that a little.

**Comment by supasoft** [comment]
Can some elements be moved to the left? Then the button can do more.
![2019-03-27_19-41-27](https://user-images.githubusercontent.com/40602544/55096078-49021580-50ca-11e9-974e-d26d039056d2.png)

**Comment by supasoft** [comment]
> > Can you add a button click animation?
> 
> I tweaked that a little.

The animation works when i am clicking on the text, not the button.

**Comment by joachimmarder** [comment]
> The animation works when i am clicking on the text, not the button.

In my case it worked for both the button and the text. I opened #890 for this.

**Comment by joachimmarder** [comment]
> Can some elements be moved to the left

No, the text is intentionally left-aligned with the expand buttons. The selection rect is slightly larger than the text.

**Comment by supasoft** [comment]
Still, you need to align these elements in the center :)
![2019-03-31_8-27-19](https://user-images.githubusercontent.com/40602544/55285190-3a985000-538f-11e9-8c49-c0a1cd71709f.png)

**Comment by joachimmarder** [comment]
According to the code they should be left-aligned. It seem that the Windows button theme has an extra 1 pixel margin. I just eliminated that and now it looks like this for me:

![grafik](https://user-images.githubusercontent.com/10615289/55293033-c2af4180-53f1-11e9-8894-54153363c149.png)

What kind of theme was active on your screenshot?

**Comment by supasoft** [comment]
Standart theme. Windows 7. It is OK. Thank you!
![2019-04-01_13-02-16](https://user-images.githubusercontent.com/40602544/55319854-837b0200-547e-11e9-94e4-59a17ffa15cb.png)
