### ISSUE TITLE
SortColumn=-1

### ISSUE THREAD

**Issue by tim-lebedkov** [JAM-Software/Virtual-TreeView#888]
I have a performance issue because of SortColumn=-1. The cause is the same as in the (now closed) issue #617. 

It is counter-intuitive to sort if SortColumn=-1. Why should one developer after another fall into the same trap?

Please consider disabling sorting if SortColumn=-1

**Comment by joachimmarder** [comment]
Well, this is basically the same as #617, so no need to open a new issue.

> It is counter-intuitive to sort if SortColumn=-1

But a tree without columns still needs to be sorted, see left pane of Windows Explorer for example. Can we agree on this?

And if a tree is not sorted by a certain column, there are situations in which the order of the nodes should not be random but follow some logic. That would no longer possible.

If you don't want the tree to be sorted, why don't you remove `toAutoSort`? Or use code in the first line like: `if SortColumn <0 then exit(0);`

**Comment by tim-lebedkov** [comment]
I'd expect a tree without additional columns to be on the column 0. This is probably the difference in our views.

![image](https://user-images.githubusercontent.com/831371/55082218-91590d80-50a1-11e9-9dfd-bbf410c4820b.png)


Maybe also the documentation for toAutoSort is a bit misleading:

>     toAutoSort,                 // Sort tree when Header.SortColumn or Header.SortDirection change or sort node if
>                                 // child nodes are added.
> 

Is "tree" here the "tree column" or the whole control?

**Comment by joachimmarder** [comment]
>I'd expect a tree without additional columns to be on the column 0. This is probably the difference in our views.

That was not my view, it is simply the status quo and how it was implemented when I took over the project a few years ago. I don't think changing this now would be a good option. And I still don't think mixing auto-sorting and the sort-column is a good idea.

Having SortColumn = 0 but Columns[SortColumn] being invalid (in case there are no colums) could also cause some irritations.

> Is "tree" here the "tree column" or the whole control?

"tree" of course means the control, not the column. A tree may not even have columns.

> Maybe also the documentation for toAutoSort is a bit misleading:

Can you suggest an improvement?

**Comment by tim-lebedkov** [comment]
> But a tree without columns still needs to be sorted, see left pane of Windows Explorer for example. Can we agree on this?

Yes. This was probably what I didn't realize first.

> Can you suggest an improvement?

Maybe this:

    toAutoSort,                 // Sort tree when Header.SortColumn or Header.SortDirection change or sort node if
                                // child nodes are added. Please note that the tree can be sorted even if Header.SortColumn =NoColumn (-1) .

BTW, is the .chm file really 7 years old?

**Comment by joachimmarder** [comment]
I updated the doc for toAutoSort.

> is the .chm file really 7 years old?

Yes, so far no one volunteered to update it. Any volunteers now?

**Comment by tim-lebedkov** [comment]
I would probably move the documentation for single methods into the source code. I have not found the source file containing this information though. What do you think?

![image](https://user-images.githubusercontent.com/831371/55233416-da879980-5228-11e9-94ad-824bc4f4f45a.png)

**Comment by joachimmarder** [comment]
I would definitely prefer XmlDoc style. It was that way when I took over the project.

**Comment by joachimmarder** [comment]
Using toAutoSort is the solution, its documentation has been enhanced.
