### ISSUE TITLE
Visualize pressed state of checkboxes and radiobuttons

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#890]
When the mouse button is down on a checkbox, radiobutton, or ctButton, use the pressed state to signal this. Not sure when this got lost. Suggested in issue #887.

**Comment by supasoft** [comment]
Visualize of the dropdown button does not work again.

**Comment by joachimmarder** [comment]
I tested with the Advanced demo proeject on Delphi 10.3 and it looks good here:
![grafik](https://user-images.githubusercontent.com/10615289/55262557-7091e300-526e-11e9-917b-8790c7d312d4.png)

**Comment by supasoft** [comment]
I understood. **OnChecked should work after releasing the mouse button!** I have PopupMenu on OnChecked and the animation is not visible.

**Comment by joachimmarder** [comment]
> OnChecked should work after releasing the mouse button!

The checkbox click beahvior has changed due to issue #805. Not sure if the `OnChecked` event should be raised at all for the buttons. Use the `OnMouseUp` or `OnNodeClick` event instead.

**Comment by supasoft** [comment]
This is a bug that **OnChecked works like OnChecking**. OnChecked should work after releasing the button (for all button types). So it is accepted in all WinControls.

**Comment by joachimmarder** [comment]
> OnChecked should work after releasing the button (for all button types).

Buttons typically do not have an OnChecked property. You should not mix up the change of a checkstate and the state of a mouse button: If you want to know when the button is released, us the appropriate event that was made for this, and not some other related event that may just fire at the same moment.

**Comment by supasoft** [comment]
OnMouseUp or OnNodeClick is not convenient to use. Need to additionally write a lot of code. This is the most suitable place to handle a button press event.
For check types btCheckBox и ctRadioButton works wrong too. Event OnCkecked must fired after releasing mouse button.

**Comment by supasoft** [comment]
Take the standard checkbox. Click in the square and holding the mouse button. Move the mouse to the side. Release the button. The event OnClick will not work. This is the usual and correct behavior.

**Comment by joachimmarder** [comment]
I won't revert #805 now. It was flagged as "Open for Discussion" for half a year.

> OnMouseUp or OnNodeClick is not convenient to use. Need to additionally write a lot of code

Why exaclty? `OnChecked` just supplies the tree and the node as paramter. `OnNodeClick` on the other hand supplies the `THitInfo` in addition.

**Comment by supasoft** [comment]
I completely agree with the author #790.

**Comment by joachimmarder** [comment]
> Take the standard checkbox.

I used the Windows ListView common control as template as well as these Windows dialogs, which behave exactly the same:

![grafik](https://user-images.githubusercontent.com/10615289/55350350-2bfb8700-54bc-11e9-985d-1a18fa405a1a.png)
![grafik](https://user-images.githubusercontent.com/10615289/55350365-3cabfd00-54bc-11e9-810d-a6898fd86086.png)

Wouldn't you agree that they are closer to what Virtual TreeView is than a single checkbox?

**Comment by joachimmarder** [comment]
> I completely agree with the author #790.

That's good, because the author closed the issue as invalid.

**Comment by supasoft** [comment]
I agree :(

**Comment by supasoft** [comment]
All the same, I do not agree. Event OnChecked must be after releasing the button. This is the common behavior of many interactive elements. **Pressed the mouse button, changed my mind, move mouse away, released the mouse button**. For buttons including.
In the example you gave, modal dialogs (and even in this case, I do not agree). If the flag is not set there, then you can click Cancel. But there are also non-modal windows, where clicking a flag can lead to some actions. For example, a network profile (public or private). This is not modal dialog. Virtual Treeview may by used in the same situation.
![2019-04-02_17-43-23](https://user-images.githubusercontent.com/40602544/55411948-36c32400-556f-11e9-839b-6071a8c1e17a.png)

**Comment by joachimmarder** [comment]
>  Virtual Treeview may by used in the same situation.

Seriously?!? The sample controls from the Windows UI that I have chosen as template have much more in common with Virtual TreeView or tree-list-controls in general than this one. These are just two plain and simple radio controls. Can we agree at least on that?

Aynway, the main focus of #805 was not to move the check click to MouseDown, it was to remove the overly complex pending check state logic. Virtual TreeView is open source, so change it as you like and send a pull request if you like. As long as you don't bring back the pending check states, I will accept it.

**Comment by supasoft** [comment]
> > OnMouseUp or OnNodeClick is not convenient to use. Need to additionally write a lot of code

> Why exaclty? `OnChecked` just supplies the tree and the node as paramter. `OnNodeClick` on the other hand supplies the `THitInfo` in addition.

THitInfo does not allow you to simply solve the problem. It always returns hiOnItemCheckbox. Even if the mouse button was released in the side of the button.
