### ISSUE TITLE
The static text has bad position in RightToLeft BidiMode

### ISSUE THREAD

**Issue by Saeid2016** [JAM-Software/Virtual-TreeView#891]
Hello, 
In the LeftToRight BidiMode the static text appears correctly on the right beside the normal text but when the BidiMode is RightToLeft it appears on the end of left side of node.
![StaticText](https://user-images.githubusercontent.com/25425826/55134883-c15aec00-5147-11e9-82bf-324f1fed37ba.png)

**Comment by joachimmarder** [comment]
Repro steps:
* Open `Minimal.dpr`
* Set `VST.BiDiMode` to `bdRightToLeft`
* Include `toShowStaticText` in `TreeOptions.StringOptions`
* Add this code to the end of `TMainForm.VSTGetText()`:
```
  if TextType = TVSTTextType.ttStatic then
    CellText := NativeInt(Node).ToString;

```

**Comment by joachimmarder** [comment]
Could you please verify if the fix works for you?

**Comment by Saeid2016** [comment]
> 
> 
> Could you please verify if the fix works for you?

Yes it works. Thank you very much.
