### ISSUE TITLE
Do not mix signed an unsiged types, use integer consequently

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#892]
There are code lines that try to work around the singed and unsigned problems like this:
`Inc(Integer(Run.TotalCount), Difference);`

`TotalCount` is unsigned while `Difference` is signed. Code would be more managable and more solid if we would use unsigned values consistently. 

This could also help the port to FireMonkey, see #839.

**Comment by Fr0sT-Brutal** [comment]
Hmm, weird, I have no warnings at all when I build packages neither in XE2 nor 10.1

**Comment by joachimmarder** [comment]
> I have no warnings at all

Sure, warnings are suppressed by the hard casts.

**Comment by joachimmarder** [comment]
Since the initial port to Firemonkey has made a lot of progress, I am closing this issue. There is no more actual problem to solve.
