### ISSUE TITLE
Odd behaviour of TAB when stringeditor is active

### ISSUE THREAD

**Issue by ericlangedijk** [JAM-Software/Virtual-TreeView#893]
When editing (default TStringEditLink) and pressing the TAB key, the editor goes to the next cell.
Multiselection is off, using the tree as a grid.
But the old cell is still selected, so the focusedcell and selection are out of sync, it seems.
Pressing shift-TAB does not go to the previous cell as I would expect.
When there is no next cell, behaviour is unpredictable.

**Comment by joachimmarder** [comment]
I tried with this with our "Advanced" sample project (sample 5, grid simulation) but was unable to replicate this. Can you?

**Comment by ericlangedijk** [comment]
This test project reproduces the tab-issue.
It reveals another bug: if there is no parent window, the autoselect node fails with an exception.
(see comment in the unit1 mainform).



[vttest.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/3084260/vttest.zip)

**Comment by joachimmarder** [comment]
> It reveals another bug: if there is no parent window, the autoselect node fails with an exception.
> (see comment in the unit1 mainform).

I moved this line to the end of TTestTree.Create() but no exception occurred.

**Comment by joachimmarder** [comment]
> But the old cell is still selected, so the focusedcell and selection are out of sync, it seems.

This has been corrected by changing the selection.

> When there is no next cell, behaviour is unpredictable.

In my tests the control always left the edit mode, which seems a reasonable behavior to me.
> Pressing shift-TAB does not go to the previous cell as I would expect.

This has been chnaged accordingly.

**Comment by ericlangedijk** [comment]
Great!
