### ISSUE TITLE
editing VK_DOWN and VK_UP

### ISSUE THREAD

**Issue by ericlangedijk** [JAM-Software/Virtual-TreeView#894]
Pressing up or down should - in my opionion not map to left and right keys, but end the edit and go to the next cell

**Comment by joachimmarder** [comment]
> Pressing up or down should - in my opionion not map to left and right keys

Windows Explorer and TTreeView behave the same way, so I think it is pretty OK.

> but end the edit and go to the next cell

It does so in grid mode.
