### ISSUE TITLE
Merge DoCancelEdit() and DoEndEdit() in one procedure with boolean parameter

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#896]
They contain almost identical code. Use a boolean parameter instead.
Also merge `IVTEditLink.CancelEdit`and `EndEdit`, they also contain almost identical code.

**Comment by MHumm** [comment]
How would such a procedure and parameter be named? If a good name is found I'd say merge them.

**Comment by joachimmarder** [comment]
I'd suggest to stick with `DoEndEdit`or use `DoTerminateEdit`.

**Comment by MHumm** [comment]
What about "IsCancelled"? If true it's a cancel operation, else it's a normal ending.

**Comment by joachimmarder** [comment]
If editing was canceled then this should be signaled through a parameter of the merged method.
