### ISSUE TITLE
Checkstate and selection no longer independent

### ISSUE THREAD

**Issue by Memnarch** [JAM-Software/Virtual-TreeView#897]
It is no longer possible to check an item, if 2 or more other items are selected.

the code in question is in TBaseVirtualTree.HandleMouseDown and is this block:
```

// check event
  if hiOnItemCheckBox in HitInfo.HitPositions then
  begin
    NewCheckState := DetermineNextCheckState(HitInfo.HitNode.CheckType, HitInfo.HitNode.CheckState);
    if (ssLeft in KeysToShiftState(Message.Keys)) and DoChecking(HitInfo.HitNode, NewCheckState) then
    begin
      if Self.SelectedCount > 1 then
        SetCheckStateForAll(NewCheckState, True)
      else
        DoCheckClick(HitInfo.HitNode, NewCheckState);
    end;//if ssLeft
    Exit;
  end;
```
If you click on a checkbox of an item that is NOT selected, but at least 2 other items are, it will call **SetCheckStateForAll** with **pSelectedOnly** set to **True**. Because our item is not selected, its checkstate is not changed.

**Comment by Memnarch** [comment]
I think the worst part here, is that whatever i clicked, is ignored. On my end, i removed the SelectCheckStateForAll altogether

**Comment by joachimmarder** [comment]
This is a result of issue #745.

> If you click on a checkbox of an item that is NOT selected, but at least 2 other items are

I agree that this scenario was not thought through well. If a non-selected checkbox is clicked, only this checkbox should be toggled.

**Comment by Memnarch** [comment]
Thanks for the fast fix. But i doubt the change will have the desired effect:

```
if (Self.SelectedCount > 1) and (Selected[HitInfo.HitNode]) then
        SetCheckStateForAll(NewCheckState, True)
      else
        DoCheckClick(HitInfo.HitNode, NewCheckState);
```
This will now result in a synced selection if the box i checked is selected. Given i have 5 items selected(none is checked) and i check one of them, all of them will sync up to checked. Or am i missing something?

**Comment by joachimmarder** [comment]
> Given i have 5 items selected(none is checked) and i check one of them, all of them will sync up to checked

Exactly that was the intention of issue #745: Allowing easier multi-checking. Virtual TreeView now behaves like other checkable list controls e.g. in TortoiseGit mor TortoiseSVN.

**Comment by Memnarch** [comment]
But isn't that what the syncmode is intended for? Because the current behaviour is not very windows like and not transparent to the user(and i'm not sure tortoise UIs as good examples for windows). Isn't it possible to make that behaviour an option?

**Comment by luebbe** [comment]
TortoiseSVN is always a good example (SCNR) ;)

**Comment by joachimmarder** [comment]
> But isn't that what the syncmode is intended for?

No, that emulates Windows 10 Explorer checkbox behavior, which is different.

> Because the current behaviour is not very windows like and not transparent to the user(and i'm not sure tortoise UIs as good examples for windows).

Well, there was a challenge: A Virtual TreeView often has a lot of items, and for the user it was very difficult change the check-state of multiple or many items quickly. Can we agree that this was a weak spot of Virtual TreeView?

So I looked around how other software solved this issue and that was the only concept I found. Can you suggest a different solution (except of course putting some buttons for that on the form)?

> ... not transparent to the user

Yes, it is not self-explaining that this feature is there, but the user may know it from other software. If the user does not discover the feature, nothing is lost compared to not having the feature implemented.

>  Isn't it possible to make that behaviour an option?

I guess you know that the answer is yes. But https://github.com/Virtual-TreeView/Virtual-TreeView/wiki/Why-we-can't-make-everthing-an-option

Given that this feature was implemented 9 months ago and this is the first complaint I'm currently reluctant making this an option.

**Comment by Memnarch** [comment]
I do agrre that not everything can be an option. However changes that alter defaultbehavior should.

Otherwhise, at least, it should be easily overridable if someone needs the old behavior. In this case, implementing this behavior is fairly simple by overriding DoCheckClick. The otherway in this case, is not. If i need the old behavior, i need to either make changes directly to the code(therefore i have to reapply all changes over and over whenever i update the tree) or derive from the tree and copy/paste a lot.

**Comment by joachimmarder** [comment]
> However changes that alter defaultbehavior should.

In that case we would have 20+ options more now. I guess you simply did not recognize most of those changes becuase they made the default behaviour more common and more expected.

I thought that this would be the case here too. At least it took 10 months after implementation before I received the first comment on this change, so I might not have been totally wrong here. 

If a user selects 20 unchecked nodes and then presses a checkbox, what else would he expect than that those selected nodes are checked? If his aim was to change a single checkstate only, why would he select multiple items first? Can you sehed some light on your use cases?

> at least, it should be easily overridable if someone needs the old behavior.

Agreed.

> In this case, implementing this behavior is fairly simple by overriding DoCheckClick.

This is correct, but it should not be necessary to override a method in order to get a good defualt behavior for a common use case.

> The otherway in this case, is not. 

It should be possible to use the `OnChecking` event, set `Allow` to `False` and check the node programatically. Could you please try that?

**Comment by Memnarch** [comment]
That event should still work as expected. but afaik what is missing, is which of the nodes is the one the user clicked on. I think that needs some manual work atm?(like checking the node under the cursor)

**Comment by joachimmarder** [comment]
> That event should still work as expected. but afaik what is missing, is which of the nodes is the one the user clicked on.

No, first the event is only fired for the clicked node, which should allow you to override this behavior. Could you please try that?
