### ISSUE TITLE
Last VirtualTreeView + Delphi 7

### ISSUE THREAD

**Issue by Johnyy45** [JAM-Software/Virtual-TreeView#900]
Hello.
I use delphi 7 and VTV 5.5.3, but it is old version.

New versions are valid only for Delphi XE - versions. Is it impossible to install last Virtual-TreeView to delphi 7?

It is one serios bug in 5.5.3 (or in my sources), linked with VCL synchronization and multy-thread application model (OnGetImageIndex, OnGetText events). Some node was deleted in TThread.Execute procedure (with Synchronize () method), but after this calls ecxeption occurs whit deleted node.

I  reinforced the check in Synchronize method (Mutex was added). Exception occurs.

**Comment by joachimmarder** [comment]
Sorry, but within this project Delphi 7 is no longer supported. You may try your luck here: https://github.com/sglienke/Virtual-TreeView
