### ISSUE TITLE
Bug TBaseVirtualTree.ChangeScale with UtilityImageSize

### ISSUE THREAD

**Issue by Johnyy45** [JAM-Software/Virtual-TreeView#902]
Hello.
This is bug in 
procedure TBaseVirtualTree.ChangeScale(M, D: Integer{$if CompilerVersion >= 31}; isDpiChange: Boolean{$ifend});

...
 if UtilityImages.Height <> MulDiv(UtilityImageSize, M, D) then
          ScaleImageList(UtilityImages, M, D);
...
UtilityImageSize is glogal integer and always 16.
To get this bug please perform following steps:
1. Open Windows Control Panel - Display, set 125% text size
2. Relogin to desctop.
3. Create TForm  template with TVirtualStringTree list;
4. Create many TForm  , like
for i:=0 to 1000 do begin MynewForm:=TForm  .Create(); // ChangeScale "first" call
MynewForm.Scale( ); <-- ChangeScale "second" call
end;
6. Look for change UtilityImages.Height on each iteration, but UtilityImageSize not changed (?), and ScaleImageList increase every time.

Thank you.

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting issues on the project homepage and include the version number you are using. 
This seems to be a duplicate of #796.
