### ISSUE TITLE
Exception when deleting clicked node OnNodeClick event

### ISSUE THREAD

**Issue by Johnyy45** [JAM-Software/Virtual-TreeView#906]
Hello, V7.2.1

I have VirtualSringTree in form, and OnNodeClick procedure.
I want to remove "clicked" node. It was no problem in 5.5.3 version, but I have a problem after update.

procedure TForm.ListNodeClick(Sender: TBaseVirtualTree;  const HitInfo: THitInfo);
var nd:PVirtualNode;
begin
nd   :=HitInfo.HitNode;

TVirtualStringTree(Sender).DeleteNode(nd); // after this call HitInfo.HitNode = nil  !!!
// and rase exception: "Node must not be nil." in function TBaseVirtualTree.InvalidateNode(Node: PVirtualNode): TRect;

end;

Is it possible to remove node?

Alternative solution are exists: Use OnMouseDown and calculate Mouse position and active node. But the question with OnNodeClick is actual.

Thank you!

**Comment by joachimmarder** [comment]
Fixed, please verify.
