### ISSUE TITLE
Odd issue on Cocoa: Column separators not drawn (but do work for e.g. resize)

### ISSUE THREAD

**Issue by TommySlokky** [JAM-Software/Virtual-TreeView#907]
On my Mac 10.14.4 (standard theme - not dark) newest Lazarus SVN Cocoa ...

virtual treeview does not draw its column separators (those you grab and drag to resize columns)

I have tried fiddling with treeview.header.options and teeview.treeoptions.paintoptions but no luck.

Can anyone else get these to work? It is a bit confusing for people new to my software. They may think they can not resize the columns (when infact they can - mouse cursor also changes when hovering over the invisible splitter/separator)

**Comment by joachimmarder** [comment]
Sorry, this project is not Lazarus compatible. Please open an issue in the appropriate fork: https://github.com/blikblum/VirtualTreeView-Lazarus
