### ISSUE TITLE
C++ Builder 10.3 and later project files

### ISSUE THREAD

**Issue by markusdonath** [JAM-Software/Virtual-TreeView#911]
There is no package project for C++ Builder 10.3. With the community Edition RAD-Studio package cannot be compiled.
Any solution?

**Comment by joachimmarder** [comment]
Unfortunately there is currently no maintainer for C++ Builder. The 10.2 package should work,

**Comment by markusdonath** [comment]
> 
> 
> Unfortunately there is currently no maintainer for C++ Builder. The 10.2 package should work,

Unfortunately the 10.2 package does not work. My workaround was to install the 30 day trial of RAD Studio 10.3. With this trial I could compile the 10.3 RAD Studio package. Afterwards I copied the binaries to the 10.3 C++ Builder installation.

**Comment by joachimmarder** [comment]
> Unfortunately the 10.2 package does not work.

Can you provide more details, like the error message?

**Comment by markusdonath** [comment]
> 
> 
> > Unfortunately the 10.2 package does not work.
> 
> Can you provide more details, like the error message?

dcc32 command line for "..\..\Source\VirtualTrees.Accessibility.pas"
[DCC Fatal Error] VirtualTrees.Accessibility.pas(12): F2613 Unit 'VirtualTrees' not found.

**Comment by joachimmarder** [comment]
Has anyone else seen this problem? I did not receive any similar reports, so I suspect an issue with the C++ Builder installation.

**Comment by zencode1** [comment]
This can be closed now since PR #1182 and #1181 have been merged containing the new project files.  If it doesn't work correctly for someone then we can address that as a new issue.
