### ISSUE TITLE
Inconsistent line ending style

### ISSUE THREAD

**Issue by jBitHub** [JAM-Software/Virtual-TreeView#917]
Some files have inconsistent line breaks.
CR/LF
LF..

Packages\RAD Studio 10.2\VirtualTreesD.dpk
Packages\RAD Studio 10.3\VirtualTreesD.dpk
source\VirtualTrees.dtx
source\VirtualTrees.Utils.pas
source\VirtualTrees.ClipBoard.pas
source\VirtualTrees.Actions.pas

**Comment by joachimmarder** [comment]
VirtualTrees.dtx is messed up by GitHub, the others should be fixed.
