### ISSUE TITLE
KEY_UP/KEY_DOWN clears entire selection when reversing direction

### ISSUE THREAD

**Issue by lyynxx** [JAM-Software/Virtual-TreeView#926]
When the toMultiSelect option is added and nodes are selected using KEY_UP and KEY_DOWN, I think the behaviour of the node selection is wrong when the direction is changed. The direction change will clear the whole selection and set a new anchor node (the focused node) to start the selection. 

Steps to reproduce: 
1. Select Node
2. Press Shift+KEY_UP a couple of times to select a few nodes
3. Press Shift+KEY_DOWN

In step 3, I would expect that the anchor node remains the node selected in step 1, and the selection is reduced by the node that was last added to the selection in step 2.

**Comment by joachimmarder** [comment]
Confirmed. Can be replicated using the Advanced sample project, page "SpeedDemo",

**Comment by joachimmarder** [comment]
Code that needs to be adapted is in `TBaseVirtualTree.WMKeyDown()` when handling `VK_DOWN`. Works for PgUp / PgDown.

**Comment by lyynxx** [comment]
For VK_UP, I suggest changing lines 16806-16808 :  

      if (not PerformMultiSelect or (CompareNodePositions(LastFocused, FRangeAnchor) > 0)) and Assigned(FFocusedNode) then
        ClearSelection(False);
to 

      if (not PerformMultiSelect or (CompareNodePositions(LastFocused, FRangeAnchor) > 0)) and Assigned(FFocusedNode) then
        if CompareNodePositions(LastFocused, Node) > 0 then
          RemoveFromSelection(LastFocused)
        else
          ClearSelection(False);

And similarly for VK_DOWN. 
Though I haven't tested it thoroughly yet.

**Comment by joachimmarder** [comment]
Sorry, saw your comment too late.
