### ISSUE TITLE
GetSelectedData() may return wrong array

### ISSUE THREAD

**Issue by lyynxx** [JAM-Software/Virtual-TreeView#927]
I've noticed a wrong behaviour when using function `TBaseVirtualTree.GetSelectedData<T>()` in `OnRemoveFromSelection` when selecting nodes with a selection rectangle. When a node is removed from the selection rectangle, `GetSelectedData` will return an array that includes an entry for the removed node, but the value is NIL. 
This is because in `GetSelectedData`, the node has already been removed, but the `FSelectionCount` has not yet been updated.

**Comment by joachimmarder** [comment]
Changing the timing of `DoRemoveFromSelection()` and updated `SelectedCount` will be tricky. But it should be easy to modify `TBaseVirtualTree.GetSelectedData<T>() so that it returns a correct array.

**Comment by lyynxx** [comment]
Yeah that's what I thought. 
Modifying `TBaseVirtualTree.GetSelectedData()` to return the correct array is not difficult, just feels a bit like a hack.
