### ISSUE TITLE
PrepareBitmaps is called before FCurrentPPI is set

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#933]
I am showing a VirtualStringTree in a dialog box and here is the sequence of calls:
-  The form ChangeScale is called
-  TBaseVirtualTree.ChangeScale is called
-  TBaseVirtualTree.UpdateHeaderRect is called from ChangeScale which creates the VT handle via GetBorderDimensions
- TBaseVirtualTree.CreateWnd is called which calls
- PrepareBitmaps
- PrepareBitmaps calls ScaledPixes but **FCurrentPPI is not set to the new value and is 96**
- At the end of TBaseVirtualTree.ChangeScale **inherited ChangeScale is called which is setting FCurrentPPI**

To reproduce just put a styled VT in a dialog box and put breakpoints in the above procedures.

I am not sure what the best solution is.  Initially I tried moving the inherited call at the top of TBaseVirtualTree.ChangeScale is called but this creates other problems.

**Comment by pyscripter** [comment]
Setting FCurrentPPI before calling UpdateHeaderRect in TBaseVirtualTree.ChangeScale, appears to resolve the issue.  However, I am not sure about any issues that may arise by setting FCurrentPPI before calling inherited ChanceScale.

```
        FCurrentPPI := M;
        UpdateHeaderRect();
```

**Comment by joachimmarder** [comment]
Which Delphi version are you using?

**Comment by pyscripter** [comment]
10.3.3 (!).   But there were no changes in Vcl related to this from 10.3.2 (I diffed the vcl).   So I assume the issue is present in 10.3.2.

Question:   As the code stands, at which point PrepareBitmaps is supposed to happen in response to ChangeScale?  In my testing it happens almost accidentally through UpdateHeaderRect, GetBorderDimensions,, CreateWnd.

Also UpdateHeaderRect is called at least 3 times recursively!
- ChangeScale calls **UpdatedHeaderRect** directly
- UpdateHeaderRect results in CreateWnd
- CreateWnd calls RescaleHeader -> RecalculateHeader -> **UpdateHeaderRect**
- then CreateWnd calls **UpdateHeaderRect** in its last statement.

**Comment by joachimmarder** [comment]
I used these repro steps: Sample project "Advanced", in `TMainForm.DemoButtonClick()` comment the 4 lines that re-parent the newly created form. Apply a VCL style.

> TBaseVirtualTree.UpdateHeaderRect is called from ChangeScale which creates the VT handle via GetBorderDimensions

I don't think it is a good idea that `UpdateHeaderRect()` proactively creates the window handle. This is usually avoided if possible using `HandleAllocated`. When doing so `PrepareBitmaps()` sees the correct value for `FCurrentPPI` when called the first time.

**Comment by joachimmarder** [comment]
Can you please how the latest source works for you?

**Comment by pyscripter** [comment]
Works fine now.  Thanks!!
