### ISSUE TITLE
[Question] how to disable/disallow dragging column before/after certain column

### ISSUE THREAD

**Issue by Sorien** [JAM-Software/Virtual-TreeView#936]
I have own column with checkboxes and it has to be the first one all the time, but user can easily drag another one to the first position.

code below is working for me but I don't want to have such hacks in sources
```pascal
procedure TVTHeader.DragTo(P: TPoint);

// Moves the drag image to a new position, which is determined from the passed point P and the previous
// mouse position.

var
  I,
  NewTarget: Integer;
  // optimized drag image move support
  ClientP: TPoint;
  Left,
  Right: Integer;
  NeedRepaint: Boolean; // True if the screen needs an update (changed drop target or drop side)

begin
  // Determine new drop target and which side of it is prefered.
  ClientP := Treeview.ScreenToClient(P);
  // Make coordinates relative to (0, 0) of the non-client area.
  Inc(ClientP.Y, FHeight);
  NewTarget := FColumns.ColumnFromPosition(ClientP);
  if NewTarget = 0 then // change
    Exit;                            //change
```

I see two possible options 
`#1` allow DragTo to be overridable.
`#2` introduce new Column Option like `TVTColumnOption.coNotDropable`
`#3` introduce some kind of event/function that can modify NewTarget

which would you prefer?

**Comment by joachimmarder** [comment]
For now If prefer option 1, which I just committed.

> introduce new Column Option like TVTColumnOption.coNotDropable

See [this article](https://github.com/Virtual-TreeView/Virtual-TreeView/wiki/Why-we-can't-make-everything-an-option). But I think that something like this could make sense and wondered if `TColumnOption.coFixed` should include the requested behavior. What sense could it make to allow dragging a non-Fixed column left of a Fixed column?

**Comment by Sorien** [comment]
thx for changes, I understand that not all can be configurable  ... to your question, I can't try it right now but I think that i saw some code that changes non fixed column to fixed when it's moved to left of fixed column (or between fixed columns) and vice versa.
