### ISSUE TITLE
Workarounds for autoresizing autospring

### ISSUE THREAD

**Issue by ghost** [JAM-Software/Virtual-TreeView#940]
There are two issues when columns are setup to hoAutoSpring. At least when 3 columns are used.

1 - Mirrored resizing, when user resizes last column, but resizing occurs to the opposite side:
![1](https://user-images.githubusercontent.com/58717918/70499238-97770900-1acd-11ea-8cc9-e62906d660a8.png)

Handling two events "fixes" that:
In **OnCanResize** (for the sake of maximize/restore):
`Tree.Header.AutoSizeIndex := 0;`
In **OnColumnWidthTracking**(against the issue):
`Tree.Header.AutoSizeIndex := Column;`

2 - With applied (1) it's possible to resize last column to minwidth now, however, if a window was maximized at that moment, the restoring will leave the column far beyond and horizontal scrollbar appears:
![3](https://user-images.githubusercontent.com/58717918/70499917-115bc200-1acf-11ea-995b-5f0f6742e3c8.png)

Handling in **OnCanResize** additionally:
```
  for I := 0 to Tree.Header.Columns.Count-1 do
    Tree.Header.Columns[I].MaxWidth := NewWidth;
```
![4](https://user-images.githubusercontent.com/58717918/70501173-369dff80-1ad2-11ea-8ffb-8e05e801e848.png)

Either all that wasn't ever handled, or i missed something in setuping virtualtreeview. May be it's just ambigous to understand which column an user is thinking he resizes: left or right? And virtualtreeview decided: always the left one.
[ColumnResize.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/3943285/ColumnResize.zip)

**Comment by joachimmarder** [comment]
>  There are two issues when columns are setup to hoAutoSpring. At least when 3 columns are used.

This is not a result of `hoAutoSpring` but of `hoAutoResize` and the intended behavior in this case. Just exclude `hoAutoResize` if this behavior is unwanted.

**Comment by ghost** [comment]
Thank you for pointing to hoAutoResize. Indeed, however without hoAutoResize it makes horizontal scrollbar appear when columns become wider than client; I've tried to keep it kind of forbidden (all columns always would fit client) as I've seen such behaviour in steam software. With hoAutoResize i return to the issue i've described. That's probably becomes a scope of custom implementation as i suppose now.

**Comment by joachimmarder** [comment]
> (all columns always would fit client) as I've seen such behaviour in steam software. With hoAutoResize i return to the issue i've described.

But that's what is intended to happen here: You make the middle column smaller and still all columns should fill the client area. To achieve this, another columns needs to grow, which is by definition the column `AutoSizeIndex`.
