### ISSUE TITLE
Option scoLimitToMatchedTextAnywhere & MatchTextAnywhere

### ISSUE THREAD

**Issue by jBitHub** [JAM-Software/Virtual-TreeView#941]
For the option »scoLimitToMatchedTextAnywhere« there is the field »MatchTextAnywhere«?
Shouldn't the »MatchTextAnywhere« field also be set in the SetOptions method?

procedure TSynBaseCompletionProposal.SetOptions
Line 2802
Form.MatchTextAnywhere := scoLimitToMatchedTextAnywhere in Value;

![grafik](https://user-images.githubusercontent.com/39560844/70529000-d057c200-1b4f-11ea-9160-461dcd847acc.png)

**Comment by joachimmarder** [comment]
Wrong project?

**Comment by jBitHub** [comment]
Sorry
you're right.
