### ISSUE TITLE
AccessViolation when creating column detached from collection 

### ISSUE THREAD

**Issue by Sorien** [JAM-Software/Virtual-TreeView#943]
I'm dynamically creating own columns like

```pascal
var Col := TMyColumn.Create()
Col.Collection := VST.Header.Columns;
```

it's valid code but it's not possible to do such call couse TVirtualTreeColumn constructor needs owner without any check that leads to AccessViolation

```pascal
constructor TVirtualTreeColumn.Create(Collection: TCollection);

begin
  FMinWidth := 10;
...
  inherited Create(Collection);

  FWidth := Owner.FDefaultWidth; // <--- Owner is nil 
  FLastWidth := Owner.FDefaultWidth;
  FPosition := Owner.Count - 1;
  // Read parent bidi mode and color values as default values.
  ParentBiDiModeChanged;
  ParentColorChanged;
end;
```

these variables `FWidth, FLastWidth, ...` should be protected by if Assigned(Owner) like code inside functions `ParentBiDiModeChanged` and `ParentColorChanged` and `FPosition` should be set when calling SetCollection and so on ...

**Comment by joachimmarder** [comment]
I don't see the advantage of creating the column without owner and then assign the owner. But anyway, doing an assign-check does not harm.

> functions ParentBiDiModeChanged and ParentColorChanged should be set when calling SetCollection

Agreed.

> FPosition should be set when calling SetCollection 

I'm not sure if members like fPosition or fWidth should change just because a (new) collection is assigned.
