### ISSUE TITLE
VirtualTrees.pas(5153,17) Error: Unknown identifier "EBX"

### ISSUE THREAD

**Issue by lucksjb** [JAM-Software/Virtual-TreeView#945]
Hi guys, I try compile and install Virtual-TreeView into a Raspibian (raspberry) to use on lazarus.
and not compile. 
I think that error is related to asm on lazarus...

have solution to it ?

tnx

**Comment by joachimmarder** [comment]
Virtual TreeView is not compatible with Lazarus.
