### ISSUE TITLE
problem with horizontal scroll when ScrollBarOptions.ScrollBars in ssNone

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#95]
_From [pesh...@bk.ru](https://code.google.com/u/100352810089031682488/) on January 15, 2010 19:04:54_

What steps will reproduce the problem? 1. set ScrollBarOptions.ScrollBars in ssNone
2. do change OffsetX by another control What is the expected output? What do you see instead? - when I set ScrollBarOptions.ScrollBars in ssNone and Change OffsetX
using own custom scroll I can't see any changes.
- also when use scroll with mouse (second wheel) grid nodes drawing
  incorrectly
- header position do not changed when scrolling What version of the product are you using? On what operating system? - r246 Please provide any additional information below. - As solution for this propose in TBaseVirtualTree.DoSetOffsetXY remove
  check for (FScrollBarOptions.ScrollBars in [ssHorizontal, ssBoth]) for
  horizontal scroll. Because UpdateHorizontalScrollBar should be started when
  ScrollBars in ssNone, too as for vertical scroll.

OLD:
      if suoUpdateNCArea in Options then
      begin
        if DeltaX <> 0 then
        begin
          if (suoRepaintHeader in Options) and (hoVisible in
FHeader.FOptions) then
            FHeader.Invalidate(nil);
          if not (tsSizing in FStates) and (FScrollBarOptions.ScrollBars in
[ssHorizontal, ssBoth]) then
            UpdateHorizontalScrollBar(suoRepaintScrollbars in Options);
        end;

```
    if (DeltaY \<> 0) and ([tsThumbTracking, tsSizing] * FStates = []) then
    begin
      UpdateVerticalScrollBar(suoRepaintScrollbars in Options);
      if not (FHeader.UseColumns or IsMouseSelecting) and
        (FScrollBarOptions.ScrollBars in [ssHorizontal, ssBoth]) then
        UpdateHorizontalScrollBar(suoRepaintScrollbars in Options);
    end;
  end;
```

NEW:
      if suoUpdateNCArea in Options then
      begin
        if DeltaX <> 0 then
        begin
          if (suoRepaintHeader in Options) and (hoVisible in
FHeader.FOptions) then
            FHeader.Invalidate(nil);
          if not (tsSizing in FStates) then
            UpdateHorizontalScrollBar(suoRepaintScrollbars in Options);
        end;

```
    if (DeltaY \<> 0) and ([tsThumbTracking, tsSizing] * FStates = []) then
    begin
      UpdateVerticalScrollBar(suoRepaintScrollbars in Options);
      if not (FHeader.UseColumns or IsMouseSelecting) then
        UpdateHorizontalScrollBar(suoRepaintScrollbars in Options);
    end;
  end;
```

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=95_

**Comment by vincentparrett** [comment]
_From [jako.gro...@gmail.com](https://code.google.com/u/104896634559527022931/) on December 17, 2012 14:13:31_

Related problem with scrolling when ScrollbarOptions.Scrollbar = ssVertical

The TBaseVirtualTree.DoSetOffsetXY() method has a problem:

  ...
  if suoUpdateNCArea in Options then
  begin
    if DeltaX <> 0 then
    begin
      ...
==>   if not (tsSizing in FStates) and (FScrollBarOptions.ScrollBars in [ssHorizontal, ssBoth]) then
      ...
    end;
    ...
  end;
  ...

The line should read:

```
  ...
```

==>   if not (tsSizing in FStates) then
      ...

This is a very horrible bug for me. I have a project where I need two treeviews, one to keep as an elaborate header grid, and the other a normal grid.

It requires a bit of set up to reproduce so here goes:

Put two treeviews (vst1 on top and vst2 below it) on a form.

Make then the same width.
Align their left sides.
Anchor the top: Left,Top,Right
Anchet the bottom: Left,Top,Right,Bottom
The first treeview set the scrollbars to ssVertical (keeps inside area width same).
The first treeview set the scrollbars AlwaysVisible to true.
The second treeview set the scrollbars to ssBoth.
The second treeview set the scrollbars AlwaysVisible to true.

Next, make the columns the same number and size:

First treeview:
Make the header visible.
Add 20 or so columns.
Add Fixed to the first column options.
Enable ShowVertGridLines, ShowVertGridLines and FullVertGridLines.
Disable ShowRoot.
Enable ExtendedFocus.
Enable GridExtensions.

Second treeview:
Hide the header.
Add same number of columns.
Add Fixed to the first column options.
Enable ShowVertGridLines, ShowVertGridLines and FullVertGridLines.
Disable ShowRoot.
Enable ExtendedFocus.
Enable GridExtensions.

Add an OnScroll event to the second treeview:

procedure TForm1.vst2Scroll(Sender: TBaseVirtualTree; DeltaX, DeltaY: Integer);
begin
  // If the grid scrolls then also force the header grid to scroll.
  if DeltaX <> 0 then
    vst1.OffsetX := vst2.OffsetX;
end;

Now test:

Set RootNodeCount to 4 or more on both.
Scroll the bottom treeview and the top should keep in sync.
Resize the form smaller, past a few columns, and scroll again.
Resize larger and scroll again.
Most of the time you will notice the top columns going out of sync, or not refreshing at all!

To fix:

Edit the VirtualTrees unit, TBaseVirtualTree.DoSetOffsetXY:

Change this line:

if not (tsSizing in FStates) and (FScrollBarOptions.ScrollBars in [ssHorizontal, ssBoth]) then

To this:

if not (tsSizing in FStates) then

Test again! They should keep nicely in sync no matter how you resize or scroll.

**Comment by vincentparrett** [comment]
_From [edwin....@innovationgear.com](https://code.google.com/u/115143382472228750230/) on December 28, 2013 21:30:57_

I'm experiencing the same problem, when Scrollbars is NOT set to ssBoth, wheeling the mouse will cause incorrect painting of the tree view content. I'm using V5.2.2: (30 Oct 2013)

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on February 09, 2014 11:14:47_

**Labels:** -Priority-Medium Priority-High

**Comment by joachimmarder** [comment]
Closing this old issue to tidy up. Please open new one for V6.0 in case the problem is still there.
