### ISSUE TITLE
horizontal synchronous scrolling does not work

### ISSUE THREAD

**Issue by jBitHub** [JAM-Software/Virtual-TreeView#953]
There is an example in the demos where two trees scroll vertically synchronously.
(Hide and show nodes, sync two trees)
I once superimposed two trees. But the horizontal synchronous scrolling does not work.
So I made changes to the unit: **VirtualTrees.pas**. Now it works for me.

Changes to the method: **TBaseVirtualTree.DoSetOffsetXY**

![image](https://user-images.githubusercontent.com/39560844/74332925-2850b600-4d97-11ea-8b81-a00c24ed6f7c.png)

**Comment by joachimmarder** [comment]
Thanks, I applied the changes. But please send a pull request the next time, not a screenshot.

**Comment by jBitHub** [comment]
Thank you for the quick response. I can try the "pull request" thing next time.
