### ISSUE TITLE
toAlwaysSelectNode can cause unintended scrolling

### ISSUE THREAD

**Issue by SaschaSchaefer** [JAM-Software/Virtual-TreeView#954]
I could boil down the scenario to an easy sample appliction, using the following parameters:

- toAlwaysSelectNode must be included in the "SelectionOptions"
- TabStop = "False"
- Disable the first node

Repro:

- Compile and start sample application
_- NOTE: No node is selected initially. This is probably the cause for this_
- Hover over the tree and Scroll down via mouse wheel
- Click a node
**Expected**: Node is selected
**Actual**: View scrolls back to the beginning and selects some node from the beginning of the list

Sample project:
[VirtualTreeViewSampleProject.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/4337546/VirtualTreeViewSampleProject.zip)

I think Embarcadero's form designer in RAD studio shows the same issue. When you use their search box in the top left corner to locate a control, scrolling and clicking can cause the same behavior.

**Comment by joachimmarder** [comment]
I will select the first enabled node in this case, as selecting a disabled node neither makes sense nor is possible.
