### ISSUE TITLE
Checkbox and text overlap problem

### ISSUE THREAD

**Issue by flylink888** [JAM-Software/Virtual-TreeView#955]
Specify a column of data as Checkbox and text, and there is overlap when loading the data. When the mouse passes, it will display normal.
This situation is no problem in the 6.X version.
![12](https://user-images.githubusercontent.com/36130329/77020851-1084d700-69c0-11ea-847b-20bb83493552.png)
![13](https://user-images.githubusercontent.com/36130329/77020857-15498b00-69c0-11ea-94a6-68d3f58ace77.png)

**Comment by joachimmarder** [comment]
We  did not have any similar reports for V7 in the past 2 years. 

When reporting a bug, please respect our guidelines for reporting bugs as written on project homepage: Please provide a sample project that allows us to replicate the bug, or provide in detail how one needs to modify one of the [included sample project](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos) so that the bug occurs.

**Comment by flylink888** [comment]
Thank you for your reply, I added relevant examples, please see the attachment!
[VSTDemo.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/4379140/VSTDemo.zip)

**Comment by joachimmarder** [comment]
You must not access the members of PVirtualNode directly unless you know what you do, see also #832. Chnage the line

    Node.CheckType := ctCheckBox;

to

    Sender.CheckType[Node] := ctCheckBox;

and it works

**Comment by flylink888** [comment]
Thank you!

**Comment by flylink888** [comment]
@joachimmarder 
I follow the method you said:
         ` Sender.CheckType[Node] := ctCheckBox;`
In Demo's code:
       ` for i := 1 to 1000 do .......`
When it loads 1000 pieces of data or more, drag the scroll bar with the mouse and observe that the check box on the right and the text still overlap momentarily.
The same situation, I tested with 6.X version, no problem.

**Comment by joachimmarder** [comment]
>When it loads 1000 pieces of data or more, drag the scroll bar with the mouse and observe that the check box on the right and the text still overlap momentarily.

Sorry, but I don't see this. But the `OnGetText` is a bad place to set the check type, as it occurs during painting. This would better fit in Button1Click() or the OnBeforeGetCheckState event.

**Comment by flylink888** [comment]
@joachimmarder 
I tested to set the check type in Button1Click() . It works very well!
I used the second method, but I couldn't find the OnBeforeGetCheckState event. 
Please forgive me for being serious, ha ha!
