### ISSUE TITLE
Deleting a column using BeginUpdate and EndUpdate will result in an error

### ISSUE THREAD

**Issue by jBitHub** [JAM-Software/Virtual-TreeView#959]
vstMatrix: TVirtualStringTree;

vstMatrix.Header.Columns.BeginUpdate;                               
vstMatrix.Header.Columns.Delete(1);
vstMatrix.Header.Columns.EndUpdate;

Deleting a column using BeginUpdate and EndUpdate will result in an error. Without BeginUpdate and EndUpdate it works. When deleting several columns I would prefer a BeginUpdate & EndUpdate for performance reasons. Deleting from behind does not cause an error.

Before deletion
![grafik](https://user-images.githubusercontent.com/39560844/78540921-220a1380-77f5-11ea-8e7b-66df7e25a821.png)

After deletion (without range check)
![grafik](https://user-images.githubusercontent.com/39560844/78541061-58479300-77f5-11ea-8d70-9aa438d15267.png)

After deletion (range check)
______________________________________________
Benachrichtigung über Debugger-Exception
______________________________________________
Im Projekt XXXXX.exe ist eine Exception der Klasse ERangeError mit der Meldung 'Fehler bei Bereichsprüfung' aufgetreten.
______________________________________________
Anhalten   Fortsetzen   Hilfe   
______________________________________________

**Comment by joachimmarder** [comment]
Can be reproduced with project `Advanvced`, unit `GridDemo`. Add a button and use this code:
```
procedure TGridForm.Button1Click(Sender: TObject);
begin
  VST5.Header.Columns.BeginUpdate;
  VST5.Header.Columns.Delete(1);
  VST5.Header.Columns.EndUpdate;
end;
```

**Comment by joachimmarder** [comment]
Could you please test using the latest GitHub source and confirm that the fix works for you?

**Comment by jBitHub** [comment]
Deletion still does not work. There is no more overflow error, but the display is wrong.

**Before**
![grafik](https://user-images.githubusercontent.com/39560844/78759527-0c752500-7980-11ea-861e-c332d8e2495e.png)

**After**
The column 1 (Customer Id) was deleted.
The column "First Name" is wrong. The heading is no longer correct. The column "Last Name" is at the very last position and has no heading anymore. The column "Order Date" is empty and cannot be selected.
![grafik](https://user-images.githubusercontent.com/39560844/78760134-fe73d400-7980-11ea-95d8-f2e052bed90d.png)

In the TVirtualTreeColumns.FixPositions method, the FPositionToIndex array is incorrect.
![grafik](https://user-images.githubusercontent.com/39560844/78760354-527eb880-7981-11ea-8c69-287143599e1f.png)

**Comment by jBitHub** [comment]
@joachimmarder  Hello, this issue has not been resolved. Unfortunately, I cannot reopen it.

**Comment by joachimmarder** [comment]
@jBitHub : Could you please try again with latest source from master?

**Comment by jBitHub** [comment]
It works for me now. Many thanks for the effort.
