### ISSUE TITLE
drawing errors (RightJustify & Italic)

### ISSUE THREAD

**Issue by jBitHub** [JAM-Software/Virtual-TreeView#960]
The last character is cut off on the right.

![grafik](https://user-images.githubusercontent.com/39560844/78551754-841f4480-7806-11ea-94ff-d143f58c2d33.png)

Settings:
vst.Header.Columns[col].**Alignment = taRightJustify**

Event: **PaintText**(Sender: TBaseVirtualTree; const TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType);
begin
   TargetCanvas.Font.Style := **[fsItalic]**;
end;

**Comment by joachimmarder** [comment]
Can be reproduced with project `Advanced`, unit `GridDemo`. 
This seems to be a limitation of the used Windows API function `GetTextExtentPoint32()`, see for example here: https://www.codeproject.com/Articles/14915/Width-of-Text-in-Italic-Font

The suggested workaround seems quite complex for this edge case. You may at any time use the `OnMeasureTextWidth`event to adjust the calculated value.

**Comment by jBitHub** [comment]
OnMeasureTextWidth Event **does not work**.
1. the width is queried: DoTextMeasuring()   
2. the event DoPaintText() is called -> font is set to italic  [33579]
3. because the font has changed, the width is recalculated with GetTextExtentPoint32W() [33585] and DoTextMeasuring() is discarded

If I call DoTextMeasuring() instead of GetTextExtentPoint32W(), nothing changes. Even if I later change the area to be drawn, everything remains the same.
The text is always cut off.
The problem is due to the Windows function Winapi.Windows.DrawTextW. Because this function draws right-aligned and is faulty, something is always cut off on the right. No matter how big the ClipRect is. The ClipRect then only gets bigger and bigger on the left.

I have found a simple workaround. I always add a space at the end.
![grafik](https://user-images.githubusercontent.com/39560844/78777096-39820180-7999-11ea-8017-9db2e2322666.png)

Thank you for your efforts.

**Comment by joachimmarder** [comment]
Changing the drawing rect did not make any difference, the issue seems indeed to be a Win32 bug. I added your workaround with the trailing space in this specific case.
