### ISSUE TITLE
is there have a foot panel

### ISSUE THREAD

**Issue by liuzg2** [JAM-Software/Virtual-TreeView#962]
is there have a foot panel

**Comment by joachimmarder** [comment]
No. I guess this is a duplicate of #681?

**Comment by eivindbakkestuen** [comment]
I've forked this repo and added footer support here, feedback appreciated, would a pull request be interesting?

https://github.com/eivindbakkestuen/Virtual-TreeView/tree/branch-footers

**Comment by joachimmarder** [comment]
Hi @eivindbakkestuen, this looks interesting, I didn't have much time to review the pull request until now. I made a VTV release last week so that we have a stable release out with the latest bugfixes. 

Can you elaborate on the use cases for this footer please?

**Comment by eivindbakkestuen** [comment]
use cases? it is the same as any other grid or similar control, it displays fixed-at-bottom data for each column. eg, in a financial app you might want sums displayed, in a treeview with checkboxes you might have "x of y selected", etc.
