### ISSUE TITLE
Switching between edited nodes with TAB key is broken

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#968]
1. Open the Advanced demo
2. Open the first page (speed breakthrough)
3. Add nodes to root
4. Select a node by clicking it
5. Press F2 key to start editing it
6. Press TAB key

Expected behavior:
Current node edit ends, the next visible node is selected, focused and editing begins.

Actual behavior in 7.3 (I didn't see any new changes regarding this issue):
The next node is selected, but focus and edit remain on the current node.
![vtv-edit-1](https://user-images.githubusercontent.com/703571/81011822-da5cc300-8e58-11ea-9dc4-551847dd323f.png)
![vtv-edit-2](https://user-images.githubusercontent.com/703571/81011828-dc268680-8e58-11ea-8c43-0633dc9ca0b9.png)

Apparently something broke between version 7.0 and 7.3, because in an earlier build of my application (where I used VTV 7.0), it was working correctly (although not perfect, because while edit and focus moved to the next node, the selection remained on the old node).

Edit: Likewise, Shift+TAB should start editing the previous visible node.

**Comment by joachimmarder** [comment]
Should be fixed now, with improved behavior of the focused node.

**Comment by IgitBuh** [comment]
Well, that was a simple fix! Working now again as expected. Thanks!
