### ISSUE TITLE
Allow to customize StaticText alignment

### ISSUE THREAD

**Issue by brethren70** [JAM-Software/Virtual-TreeView#969]
Please, give me a chance to set the alignment of static text.

VirtualTrees.TCustomVirtualStringTree.PaintStaticText 

in the source, alignment of static text is decided  according to column's alignment.
Thanks in advance.

![image](https://user-images.githubusercontent.com/2011944/81255768-84ab3500-9069-11ea-9d0d-5b14f6ade31c.png)

**Comment by joachimmarder** [comment]
I will extend the `OnGetCellText´ to achieve this. It has to be used instead of the `OnGetText` event. I will change the Advanced project, General Abilities demo to achieve this.

**Comment by joachimmarder** [comment]
Within this issue the, the unused paramter `TextOutFlags` of `PaintStaticText()` was replaced with a new one names `pStaticTextAlignment`. As `PaintStaticText()` is protected, this is a breaking change for derived classes.
