### ISSUE TITLE
Tristate checkbox init without toAutoTristateTracking

### ISSUE THREAD

**Issue by denovosoftware** [JAM-Software/Virtual-TreeView#970]
There seem to be a bug in TBaseVirtualTree.InitNode, which prevents you from setting a check state on a child node (with a tristate checkbox) if such state is different from parent node's check state. This is regardless of presence or absence of toAutoTristateTracking in auto options.

You can see that code in TBaseVirtualTree.InitNode is checking that check type is ctTriStateCheckBox before propagation, but is ignoring auto options completely. So this bug can be fixed by adding an additional check for toAutoTristateTracking option before propagating check state.

Thank you!

**Comment by joachimmarder** [comment]
Fixed as suggested. Please review and test the fix.
