### ISSUE TITLE
the InitNode event

### ISSUE THREAD

**Issue by chenhuan2011** [JAM-Software/Virtual-TreeView#972]
In the initnode event,I can not get noting of data ， through data:= Sender.GetNodeData (node); 

for example ：

//  vsttree is TVirtualStringTree 
// add root ;   
  RootNode := vsttree.AddChild(nil);
  Data := vsttree.GetNodeData(RootNode);
  Data^.Text := 'RootNode';
  Data^.Id := 'RootID';
  Data^.ImageIndex := 0;
  Data^.CheckType := ctTriStateCheckBox;
  Data^.CheckState := csCheckedNormal;

procedure TForm4.vsttreeInitNode(Sender: TBaseVirtualTree; ParentNode,
  Node: PVirtualNode; var InitialStates: TVirtualNodeInitStates);
var
  Data: PMyRec;
begin
     Data := Sender.GetNodeData(Node);
     showmessage(Data^.Text);   //can not get “RootNode”
     Node^.CheckType := Data^.CheckType;
     Node^.CheckState := Data^.CheckState;

 
end;

**Comment by joachimmarder** [comment]
When reporting a bug, please respect our guidelines for reporting bugs as written on project homepage: First make sure to use the [latest version](https://github.com/Virtual-TreeView/Virtual-TreeView/archive/master.zip) of Virtual TreeView. 
And please provide a sample project that allows us to replicate the bug, or provide in detail how one needs to modify one of the [included sample project](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos) so that the bug occurs.

**Comment by chenhuan2011** [comment]
My Virtual-TreeView's version is 7.4.0 ,delphi's version 10.3.3 ，just one  TVirtualStringTree on  the form .

the code like this:

unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, VirtualTrees, ImgList, Menus, System.ImageList, cxGraphics,
  cxControls, cxLookAndFeels, cxLookAndFeelPainters, cxCustomData, cxStyles,
  cxTL, cxTextEdit, cxTLdxBarBuiltInMenu, cxInplaceContainer, Vcl.ComCtrls,
  Super_TreeList, cxCheckBox;

type
  { *------------------------------------------------------------------------------
    首先，先自己定义一个结点所对应的数据结构。
    这一般是一个结构体，内容根据你的需要自己定义
    ------------------------------------------------------------------------------- }
  TMyRec = record
    Text: string; // 结点显示的文本
    ImageIndex: Integer;
    // 结点显示的图片索引。注意：要在结点显示图片必须TreeOptions.MiscOptions包含toCheckSuppot
    Id: string; // 数据Id，可以为数据库记录的Id
    CheckType: TCheckType; // 选择框类型
    CheckState: TCheckState; // 选择框状态
    // ...你还可以自己加
  end;

  { *------------------------------------------------------------------------------
    定义一个上面结构体的指针类型，后面要用到这个东东
    ------------------------------------------------------------------------------- }
  PMyRec = ^TMyRec;

  TForm4 = class(TForm)
    vsttree: TVirtualStringTree;
    procedure FormCreate(Sender: TObject);
    procedure vsttreeFreeNode(Sender: TBaseVirtualTree; Node: PVirtualNode);
    procedure vsttreeGetText(Sender: TBaseVirtualTree; Node: PVirtualNode;
      Column: TColumnIndex; TextType: TVSTTextType; var CellText: string);
    procedure vsttreeNodeClick(Sender: TBaseVirtualTree;
      const HitInfo: THitInfo);
    procedure vsttreeInitNode(Sender: TBaseVirtualTree; ParentNode,
      Node: PVirtualNode; var InitialStates: TVirtualNodeInitStates);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form4: TForm4;

implementation

{$R *.dfm}
procedure TForm4.vsttreeInitNode(Sender: TBaseVirtualTree; ParentNode,
  Node: PVirtualNode; var InitialStates: TVirtualNodeInitStates);
var
  Data: PMyRec;
begin
     Data := Sender.GetNodeData(Node);
     showmessage(Data^.Text);
     Node^.CheckType := Data^.CheckType;
     Node^.CheckState := Data^.CheckState; 

   // Node^.CheckType := ctTriStateCheckBox ;
end;

procedure TForm4.FormCreate(Sender: TObject);
var
  RootNode, ChileNode: PVirtualNode;
  Data: PMyRec;
begin

  // 指定结点数据大小
  vsttree.NodeDataSize := SizeOf(TMyRec);
  // 指定树里要用的图片列表


  // 添加根节点
  RootNode := vsttree.AddChild(nil);
  Data := vsttree.GetNodeData(RootNode);
  Data^.Text := '根结点';
  Data^.Id := 'RootID';
  Data^.ImageIndex := 0;
  Data^.CheckType := ctTriStateCheckBox;
  Data^.CheckState := csCheckedNormal;

  // 添加一个子结点
  ChileNode := vsttree.AddChild(RootNode);
  Data := vsttree.GetNodeData(ChileNode);
  Data^.Text := '子结点1';
  Data^.Id := 'ChildId1';
  Data^.ImageIndex := 1;
  Data^.CheckType := ctTriStateCheckBox;
  Data^.CheckState := csCheckedNormal;
  // 再添加一个子结点
  ChileNode := vsttree.AddChild(RootNode);
  Data := vsttree.GetNodeData(ChileNode);
  Data^.Text := '子结点2';
  Data^.Id := 'ChildId2';
  Data^.ImageIndex := 1;
  Data^.CheckType := ctTriStateCheckBox;
  Data^.CheckState := csCheckedNormal;


  // 默认展开一级结点，这句话要写在初始的最后
  vsttree.Expanded[RootNode] := True;
  {
    注：在这里把数据添加进树后，树里并不能显示出结点
    要在几个事件里写代码才行：
    OnInitNode:在这个事件里初始化结点，如指定复选框以及状态
    OnGetText:在这个事件里指定结点的显示文本
    OnGetPopupMenu:在这个事件里指定下拉菜单
    OnGetImageIndex:指定结点的图片索引
    OnFreeNode:释放结点时您要做的一些释放动作
    通过这些事件，才能把结点的显示情况描述清楚。而您的
    结构体是用来持有您每个结点的数据的。
  }
end;

// 弹出菜单的点击事件
procedure TForm4.vsttreeFreeNode(Sender: TBaseVirtualTree; Node: PVirtualNode);
var
  Data: PMyRec;
begin
  Data := Sender.GetNodeData(Node);
  Finalize(Data^);
end;

procedure TForm4.vsttreeGetText(Sender: TBaseVirtualTree; Node: PVirtualNode;
  Column: TColumnIndex; TextType: TVSTTextType; var CellText: string);
var
  Data: PMyRec;
begin
  Data := Sender.GetNodeData(Node);
  CellText := Data^.Text;
end;



procedure TForm4.vsttreeNodeClick(Sender: TBaseVirtualTree;
  const HitInfo: THitInfo);
var
  CurrentNode: PVirtualNode;
  Data: PMyRec;
  Checked: string;
begin
  { 示例取点击结点的数据。
    注意：TreeOptions.SelectionOptions必须包含toRightClickSelect
  }
  // 取得当前选中结点
  CurrentNode := vsttree.FocusedNode;
  if Assigned(CurrentNode) then
  begin
    Data := vsttree.GetNodeData(CurrentNode);
    if CurrentNode.CheckState = csCheckedNormal then
    begin
      Checked := '是';
    end
    else
    begin
      Checked := '否';
    end;
    ShowMessage('当前结点:' + #13 + 'Id=' + Data^.Id + #13 + 'Text=' + Data^.Text +
      #13 + '是否选中=' + Checked);
  end;
end;

end.

**Comment by joachimmarder** [comment]
Please attach the project as ZIP and don't paste them in the comments.

**Comment by chenhuan2011** [comment]
&nbsp;I'm so sorry for that.&nbsp; &nbsp;The demo is in attachment.&nbsp; The problem is in the&nbsp;InitNode event. I can not get the data&nbsp; of the node&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Joachim Marder"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 凌晨4:05
收件人:&nbsp;"JAM-Software/Virtual-TreeView"<Virtual-TreeView@noreply.github.com&gt;;
抄送:&nbsp;"404551458"<404551458@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JAM-Software/Virtual-TreeView] the InitNode event (#972)





 
Please attach the project as ZIP and don't paste them in the comments.

**Comment by joachimmarder** [comment]
I don't see any file attached to this issue.

Did you set the property `NodeDataSize` correctly?

**Comment by chenhuan2011** [comment]
I did upload the&nbsp;attachment. I&nbsp;set the property&nbsp;NodeDataSize like this : vsttree.NodeDataSize := SizeOf(TMyRec);



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Joachim Marder"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 下午4:56
收件人:&nbsp;"JAM-Software/Virtual-TreeView"<Virtual-TreeView@noreply.github.com&gt;;
抄送:&nbsp;"404551458"<404551458@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JAM-Software/Virtual-TreeView] the InitNode event (#972)





 
I don't see any file attached to this issue.
 
Did you set the property NodeDataSize correctly?

**Comment by joachimmarder** [comment]
I don't see any upload, please check for yourself. And why do your comments contain garbage / HTML text?

**Comment by chenhuan2011** [comment]
[VirtualTreeViewDemo.zip](https://github.com/JAM-Software/Virtual-TreeView/files/4729354/VirtualTreeViewDemo.zip)
I'm sorry , can you find it now?

**Comment by joachimmarder** [comment]
> I'm sorry , can you find it now?

Yes, it is there now.

I needed to remove some 3rd party units from the uses and was able to compile it. There are a lot of garbage chars in the comments and strings, most likely some encoding problems.

When I run the project and click a node, I don't see anything that looks wrong, besides the garbage text.

> In the initnode event,I can not get noting of data 

Can you please describe the problem more detailed? 

I think it is unlikely that there is a bug in Virtual TreeView in such a central place. In any case, this is a bug tracker. A bug report should include at minimum:

- Steps to Reproduce
- Expected Result
- Actual Result

See: https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
