### ISSUE TITLE
10.4 DPROJ Issue

### ISSUE THREAD

**Issue by lancerasmussen** [JAM-Software/Virtual-TreeView#974]
The DPROJ references to the library suffix for 64 bit is pointing to 25 instead of 27, creating inconsistent naming.
My guess is Rio 64 bit is also pointing to 25.

**Comment by joachimmarder** [comment]
I cannot confirm that:
![grafik](https://user-images.githubusercontent.com/10615289/83736711-51e96200-a652-11ea-9c89-0c70a66e44a7.png)

I also checked the .DPROJ file in the text editor.

Where exactly did you see that?

**Comment by joachimmarder** [comment]
Closing issue as repro steps are missing.
