### ISSUE TITLE
RAD Studio 10.4 stores default VirtualTree's default properties in .dfm file

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#975]
Origins from:
- https://stackoverflow.com/questions/62266100/delphi-10-4-stores-default-virtualtrees-default-properties-in-dfm-file
- https://community.idera.com/developer-tools/general-development/f/rad-studio-general/72519/problem-of-the-colors-property-of-tvirtualstringtree-in-delphi-10-4

**Reason**: IsSystemStyle used to return True in former Delphi version, now it returns False.

**Comment by ansgarbecker** [comment]
I'm afraid the form designer still writes these default values to my .dfm files, after recompiling and installing the package. I'm not sure why, as your fix looks correct to me. I suppose the fix works for you?

**Comment by joachimmarder** [comment]
Yes, it is working for. Did you recompile the packages? Please review the code changes in the commit.

**Comment by ansgarbecker** [comment]
Oh, my fault. I was compiling the 64bit version of the VirtualTreesR runtime package, until I just remembered the IDE just uses the 32bit version, even if my project is compiled in 64bit mode. So yes, now it's fine!
