### ISSUE TITLE
Access Violation when changing Windows-Theme while editing

### ISSUE THREAD

**Issue by delphi-sucks** [JAM-Software/Virtual-TreeView#976]
### Description
If you change your Windows-Theme while you're editing a node, the application crashes with an Access Violation at the following Section:

```delphi
procedure TVTEdit.CreateParams(var Params: TCreateParams);

begin
  inherited;

  // Only with multiline style we can use the text formatting rectangle.
  // This does not harm formatting as single line control, if we don't use word wrapping.
  with Params do
  begin
    Style := Style or ES_MULTILINE;
    if vsMultiline in FLink.FNode.States then // <=== HERE
      Style := Style and not (ES_AUTOHSCROLL or WS_HSCROLL) or WS_VSCROLL or ES_AUTOVSCROLL;
```

### Steps to Reproduce
1. Open the project Minimal from the Demos-Folder
2. Compile & Start
3. Select Node and press F2 to edit
4. Go to the Windows Settings (the new one) > Personalization > Themes
5. Select another Theme like _Classic_
=> Should crash with an Access Violation

### Additional Information
Reproduced with the latest release 7.4 and current master-Branch

**Comment by joachimmarder** [comment]
Changing a theme does not show the issue here. I don't have a theme named "Classic". Which Windows version are you using?

An assign.check for `FLink` could be a solution for this corner case.

**Comment by delphi-sucks** [comment]
I'm using Windows 10, but I was able to reproduce it in another way.
When enabling High Contrast in the Windows Settings it also crashes. The Problem is that the Control has to recreate itself, because the background-color (clWindow) changed.

### Steps to Reproduce (English)
1. Open Windows Settings (new Metro one)
2. Search for "Contrast" or go to "Ease of access" and to "high contrast"
3. Open the Minimal-demo
4. Edit a node, but leave the Editor active
5. enable/diable high contrast
-> Should crash

### Steps to Reproduce (German)
1. Öffne die Windows-Einstellungen (die Metro-Variante)
2. Such nach "Kontrast" oder gehe zu "Erleichterte Bedienung" und zu "Hoher Kontrast"
3. Starte die Minmal-Demo
4. Bearbeite eine Node, aber den Editor nicht schließen
5. Hohen Kontrast aktivieren/deaktivieren
-> Sollte abstürzen

### Additional Information
I'm connect via RDP. Maybe there is some weird additional behaviour?

**Comment by joachimmarder** [comment]
> When enabling High Contrast in the Windows Settings it also crashes.

Confirmed
