### ISSUE TITLE
Support Delphi 10.4 DPI aware styles

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#984]
Actually it is quite easy.   All DrawElement methods (there is 9 of them) take an optional DPI parameter.

Example:
Currently:
```pascal
procedure TBaseVirtualTree.PrepareBitmaps
...
    StyleServices.DrawElement(FPlusBM.Canvas.Handle, StyleServices.GetElementDetails(tcbCategoryGlyphClosed), R);
    StyleServices.DrawElement(FMinusBM.Canvas.Handle, StyleServices.GetElementDetails(tcbCategoryGlyphOpened), R);
...
```
change to

```pascal
procedure TBaseVirtualTree.PrepareBitmaps
...
    StyleServices.DrawElement(FPlusBM.Canvas.Handle, StyleServices.GetElementDetails(tcbCategoryGlyphClosed), R
     {$IF CompilerVersion > 33}, nil, FCurrentPPI{$IFEND});
    StyleServices.DrawElement(FMinusBM.Canvas.Handle, StyleServices.GetElementDetails(tcbCategoryGlyphOpened), R 
      {$IF CompilerVersion > 33}, nil, FCurrentPPI{$IFEND});
...
```

StyleElementMembers that take an optional DPI argument:
- DrawEdge- DPI does nothing AFAICS
- DrawElement
- DrawIcon
- DrawText
- GetElementContentRect- DPI does nothing AFAICS
- GetElementMargins- DPI does nothing AFAICS
- GetElementRegion- DPI does nothing AFAICS
- GetElementSize - DPI does nothing AFAICS
- TextExtend 

Also there is the property:
    property ThemeForDPI[Element: TThemedElement; DPI: Integer]: THandle read GetThemeForDPI;

**Comment by joachimmarder** [comment]
Thanks for sending the examples. Just started changing the `StyleServices.DrawElement()` calls.

**Comment by pyscripter** [comment]
In VirtualTrees.StyleHooks use FVertScrollWnd.CurrentPPI instead of FVertScrollWnd.FCurrentPPI

**Comment by pyscripter** [comment]
Also in TBaseVirtualTree.PrepareBitmaps

please replace:

```pascal
  if VclStyleEnabled and (seClient in StyleElements) then
  begin
    Size.cx := ScaledPixels(11);
    Size.cy := ScaledPixels(11);
```
with:
```pascal
  if VclStyleEnabled and (seClient in StyleElements) then
  begin
    if StyleServices.GetElementSize(FPlusBM.Canvas.Handle,
      StyleServices.GetElementDetails(tcbCategoryGlyphClosed), TElementSize.esActual, Size)
    then
      Size.cx := ScaledPixels(Size.cx)
    else
      Size.cx := ScaledPixels(11);
    Size.cy := Size.cx;

```

**Comment by joachimmarder** [comment]
> In VirtualTrees.StyleHooks use FVertScrollWnd.CurrentPPI instead of FVertScrollWnd.FCurrentPPI

Makes sense, but why did you suggest using FCurrentPPI in your initial comment? If it makes sense using the property here, why use the member variable in other cases?

**Comment by joachimmarder** [comment]
> ```pascal
>     if StyleServices.GetElementSize(FPlusBM.Canvas.Handle,
>       StyleServices.GetElementDetails(tcbCategoryGlyphClosed), TElementSize.esActual, Size)
>     then
>       Size.cx := ScaledPixels(Size.cx)
> ```

Are you sure that the returned value is **not** dpi-scaled?

**Comment by pyscripter** [comment]
> Makes sense, but why did you suggest using FCurrentPPI in your initial comment? If it makes sense using the property here, why use the member in other cases?

Using FCurrentPPI is  much faster than using CurrrentPPI.  However it does not work with the stylehook.  The problem is that TVclStyleScrollBarsHook.Create is called after the form is shown and scaled (TCustomForm.ScaleForPPIRect).  So FVertScrollWnd and FVertScrollWnd don't get their FCurrentPPI set.    I think this is only an issue if the initial monitor has DPI > 96.

> Are you sure that the returned value is not dpi-scaled?
This is what is eventually called:
```pascal
class function TUxThemeCategoryButtonElements.GetElementSize(Style: TCustomStyleServices; DC: HDC; Part, State: Integer;
  Rect: PRect; ElementSize: TElementSize; out Size: TSize; DPI: Integer = 0): Boolean;
begin
  Result := False;
  if ElementSize = esActual then
    case TThemedCategoryButtons(State) of
      tcbCategoryGlyphOpened,
      tcbCategoryGlyphClosed:
        begin
          Size := TSize.Create(9, 9);
          Result := True;
        end;
    end;
end;
```

**Comment by joachimmarder** [comment]
> This is what is eventually called:

Looks like a bug to me. It was reported but not taken care of:
https://quality.embarcadero.com/browse/RSP-10869

**Comment by pyscripter** [comment]
To future-proof the code for future versions you could have omitted {$IF CompilerVersion >= 34}CurrentPPI{$IFEND} or replace it with 96 in the StyleServices.GetElementSize call.

**Comment by pyscripter** [comment]
Look at the top of this issue.  DPI is not accounted for in a whole bunch of StyleServices methods.    I wonder whether this is by design.
