### ISSUE TITLE
Compiler errors in Delphi < 10.4

### ISSUE THREAD

**Issue by G-Flow** [JAM-Software/Virtual-TreeView#985]
There's some compiler errors when compiling with Delphi < 10.4 (I'm using 10.2) because some misplaced commas (must be into the IF directive).

Errors are in lines 14004, 14005 and 23931.

Here's the file patch:
[VirtualTrees.pas.zip](https://github.com/JAM-Software/Virtual-TreeView/files/5186605/VirtualTrees.pas.zip)

Thanks!

**Comment by joachimmarder** [comment]
I think this was fixed this morning. Can you please try the latest source?

**Comment by G-Flow** [comment]
Problem solved ;)

Thanks a lot!
