### ISSUE TITLE
VTColors appeared in the DFM file

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#986]
Suddenly VTColors started appearing in the DFM file without me changing the default values.
e,g,
```pascal
+        Colors.BorderColor = 15987699
+        Colors.DisabledColor = clGray
+        Colors.DropMarkColor = 15385233
+        Colors.DropTargetColor = 15385233
+        Colors.DropTargetBorderColor = 15385233
+        Colors.FocusedSelectionColor = 15385233
+        Colors.FocusedSelectionBorderColor = 15385233
+        Colors.GridLineColor = 15987699
+        Colors.HeaderHotColor = clBlack
+        Colors.HotColor = clBlack
+        Colors.SelectionRectangleBlendColor = 15385233
+        Colors.SelectionRectangleBorderColor = 15385233
+        Colors.SelectionTextColor = clBlack
+        Colors.TreeLineColor = 9471874
+        Colors.UnfocusedColor = clGray
+        Colors.UnfocusedSelectionColor = 13421772
+        Colors.UnfocusedSelectionBorderColor = 13421772
```

I am using Delphi 10.4.1.  Is this a Delphi bug?  I suspect it may have something to do with the interception of Widnows GetSysColor to support styles in dialog boxes.

**Comment by pyscripter** [comment]
When I drop a new VirtualStringTree onto a form and look at the Colors this is what I see.  System colors have been replaced with their Color values.  But this is not the case with the Color property.  So it sounds unlikely that this is a Delphi issue.  Also when I change a Color to a system color it comes back as color constant.
![image](https://user-images.githubusercontent.com/1311616/92936344-a6bb2680-f452-11ea-8fbd-c425910a86b4.png)

**Comment by pyscripter** [comment]
OK I think I know what is happening.

VclStyleChanged(); is called from TBaseVirtualTree.Create.  At that time (csDesigning in ComponentState) is false and FVclStyleEnabled is set to True;

GetColor then returns styled colors!

Possible solutions (not tested): 
-  Do not call VclStyleChanged in TBaseVirtualTree.Create
-  Add an extra check in GetColor  
 `
 if FOwner.VclStyleEnabled and not (csDesigning in ComponentState) then`

**Comment by joachimmarder** [comment]
Thanks for reporting this issue and suggesting a solution. I prefer solution one. Please test if it solves your problem.

**Comment by joachimmarder** [comment]
Looks good here now:

![grafik](https://user-images.githubusercontent.com/10615289/93633037-97a61c80-f9ee-11ea-86ec-8b567137d458.png)

**Comment by pyscripter** [comment]
Thanks!  Issue resolved.

**Comment by ErwinDenissen** [comment]
The Colors issue also occurs when you use a Theme in de Delphi IDE.

This code in TVTColors.GetColor should solve it:
  if TreeView.VclStyleEnabled and not (csDesigning in TreeView.ComponentState) then
