### ISSUE TITLE
CreateSystemImageSet is leaking its return value

### ISSUE THREAD

**Issue by obones** [JAM-Software/Virtual-TreeView#987]
Inside `VirtualTrees.pas` there is the `CreateSystemImageSet` function whose return type is `TImageList`
Every time it gets called, it returns a new instance of `TImageList` that gets instantiated using the `CreateSize` constructor.
This one sets the `Owner` to nil, effectively meaning it is the caller's responsibility to free the newly created instance.
Sadly, this is never done anywhere inside the code and it can not be done because the value returned by `CreateSystemImageSet` is immediately assigned to `FCheckImages` which could have been set to something else by the user of VTV.

I see two solutions here:

1. Do not call `CreateSize(lSize.cx, lSize.cy)` but `Create(pControl)` and later change the size of the image list
2. Store the returned value into a global instance that gets freed upon finalization. This would also avoid recreating a new instance every time the `CreateSystemImageSet` is called.

I have a preference for the second one, even if it means a bit more work as it would probably require changing the name of the function to `GetSystemImageSet`
What's your opinion here?

**Comment by joachimmarder** [comment]
> Store the returned value into a global instance that gets freed upon finalization. 

You would at least need one global instance for each size (in pixels) to support multi-monitor / multi-dpi scenarios. And you need to keep all of them alive until the application terminates.

**Comment by joachimmarder** [comment]
> Sadly, this is never done anywhere inside the code 

I don't think this is correct. In `TBaseVirtualTree.Destroy()` there is the code:

```
  if CheckImageKind = ckSystemDefault then
    FCheckImages.Free;
```

I never saw a leak reported in my applications. Can you please provide detailed repro steps or a sample application?

**Comment by pyscripter** [comment]
I have never seen a memory leak.

**Comment by joachimmarder** [comment]
> I have never seen a memory leak.

Then why exactly did you open this issue?

**Comment by pyscripter** [comment]
> Then why exactly did you open this issue?

**I did not**

**Comment by joachimmarder** [comment]
Oh, I'm very sorry. Typically the reporter of the issue replies to my comments and I had in mind that you opened an issue recently, but that was a different one.

**Comment by pyscripter** [comment]
No problem.

**Comment by obones** [comment]
Seriously?
It's an issue I'm having at work, that I reported on a Friday afternoon, and you don't even wait until Monday?

Well, there are multiple issues with that code, leaks being one of them, but hey, never mind, I'll fix it in my own copy and that'll do it.

**Comment by joachimmarder** [comment]
I don't see the problem, we can reopen the issue at any time, that's what the reopen feature is for. But if our guidelines for submitting bugs are not respected and the bug reports contains wrong information ("this is never done anywhere inside the code") then I take the liberty to close such issues for cleaning up. There are simply too many of them.
