### ISSUE TITLE
Make Advanced demo per monitor DPI aware.

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#990]
In the Advanced demo the created embedded forms are not scaled properly.  To reproduce use a two monitor with different PPI setup,  Move the main window to the second monitor and create forms.   Notice the wrong font size and other issues.

Explanation:

TControl.SetParent(AParent: TWinControl) does call ScaleForPPI(GetParentCurrentDpi);
but in
```
procedure TCustomForm.ScaleForPPIRect(NewPPI: Integer; NewRect: PRect);
begin
  if not (csDesigning in ComponentState) and
    ((not HandleAllocated and (Parent <> nil)) or (NewPPI < 30)) then
    Exit;
```
(not HandleAllocated and (Parent <> nil))  is True and no scaling is done.

Solution:

In  TMainForm.DemoButtonClick :
```
    if Assigned(NewDemoClass) then
    begin
      NewDemo := NewDemoClass.Create(Self);
      NewDemo.Hide;
      NewDemo.BorderStyle := bsNone;
      NewDemo.Parent := ContainerPanel;
      NewDemo.Align := alClient;
      NewDemo.Show;
    end;
```
Add the following before the "end"
```
      NewDemo.HandleNeeded;
      NewDemo.ScaleForPPI(FCurrentPPI);
```

**Comment by joachimmarder** [comment]
Calling `HandleNeeded()` after `Show()` does not make any difference, as the handle is already created. I am surprised that it does not seem to get this working as expected without a calling `ScaleForPPI()` explicitly.

**Comment by pyscripter** [comment]
> Calling `HandleNeeded()` after `Show()`
Yes indeed.  You can remove it or move both statements before Show (maybe less flicker but I see no difference).

**Comment by pyscripter** [comment]
> I am surprised that it does not seem to get this working as expected without a calling `ScaleForPPI()`

I was as well.  
I am not sure why ScaleforPPIRect exits when (not HandleAllocated and (Parent <> nil)).

a stranger one is that TContor.SetParent does not scale the child if (csFreeNotifications is in ComponentState).  What do freeNotifications have to do with scaling?
