### ISSUE TITLE
PrepareBitmaps() is called incidentally and at the wrong time in DPI-aware applications

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#991]
Currently PrepareBitmaps is not called directly by TBaseVirtualTree.ChangeScale.
It is called indirectly via TBaseVirtualTree.CMFontChanged, which it triggered by the call to inherited ChangeScale.

If you look at TControl.ChangeScale  
```
if isDpiChange then
    FCurrentPPI := M;
```
is the very last thing done.   So CMFontChanged is called before the FCurrentPPI is changed and ScalePixels applies wrong scaling in PrepareBitmaps.   

You can reproduce this with the Advanced demo with two monitors of different PPI.

Solution:
In TBaseVirtualTree.ChangeScale call PrepareBitmaps immediately after the call to inhered ChangeScale as below:

```
  inherited ChangeScale(M, D{$if CompilerVersion >= 31}, isDpiChange{$ifend});
  if (M<>D) then PrepareBitmaps(True, False);
```

Question:
Does CMFontChanged need to call PrepareBitmaps?  It is not obvious why.

**Comment by joachimmarder** [comment]
> Does CMFontChanged need to call PrepareBitmaps? 

I don't see why, unless you want the Bitmaps size to correspond with the font size. But the font size is not evaluated in `PrepareBitmaps()`.

**Comment by pyscripter** [comment]
If you are trying to reproduce it please note that it still work as is, if ParentFont is set to True, since then the call to CMFontChanged comes after ChangeScale.

**Comment by pyscripter** [comment]
ChangeScale is called sometimes with M=D and DpiScale = False.
There is no need to PrepareBitmaps if M=D.

**Comment by joachimmarder** [comment]
I remember cases @100% dpi-scaling in that `ChnageScale()` was called only once with `M == D`. I was unsure if `PrepareBitmaps()` would then be called, but just recognized the call in `CreateWnd()`.

**Comment by pyscripter** [comment]
Thanks!!
