### ISSUE TITLE
Incorrect scaling of hint font

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#992]
TVirtualTreeHintWindow.Paint and TVirtualTreeHintWindow.CalcHintRect contain the following code:

```
            Canvas.Font := Screen.HintFont;
            Canvas.Font.Height := Tree.ScaledPixels(Canvas.Font.Height);
```

If your main monitor is High-DPI this will lead to double-scaling of the font, since Screen.HintFont is already scaled for the main screen.

**Solution:**
Replace both instances of the above with:
```
            Canvas.Font := Screen.HintFont;
            Canvas.Font.Height := MulDiv(Canvas.Font.Height, Tree.ScaledPixels(96),
              Screen.PixelsPerInch);
```

**Comment by joachimmarder** [comment]
Are you using RAD Studio 10.4 or an older version?

> `Screen.PixelsPerInch`

Shouldn't we use the PPI of the current monitor? This is the PPI of the primary monitor.

**Comment by pyscripter** [comment]
Rad studio 10.4.1
> Shouldn't we use the PPI of the current monitor? This is the PPI of the primary monitor.

This is the whole point.  Sceen.HintFont is already scaled for Screen.PixelsPerInch (easy to check or see the source code).  So if the tree is  and the hint is shown on the main monitor:
`Tree.ScaledPixels(96) = Screen.PixelsPerInch`
and no scaling is taking place, which is what should happen.

If the Tree is positioned in another monitor with a different PPI the appropriate scaling is:

```
Canvas.Font.Height := MulDiv(Canvas.Font.Height, Tree.ScaledPixels(96),
              Screen.PixelsPerInch);
```

Note that Screen.PixelsPerInch (the PPI of the main monitor) could be different to 96.

**Comment by joachimmarder** [comment]
Easy Repro: Advanced sample, Property Tree simulation

**Comment by joachimmarder** [comment]
@pyscripter : Thanks for the fixed code.
