### ISSUE TITLE
With Virtual-TreeView you can do more 。。。

### ISSUE THREAD

**Issue by changyu72** [JAM-Software/Virtual-TreeView#993]
Virtual-TreeView draw project gantt chart。。。 
https://win.projectclouds.cn
<img width="1440" alt="2020-10-09_114609" src="https://user-images.githubusercontent.com/18181509/95541285-92545480-0a25-11eb-8b36-2de6ae4486dc.png">
<img width="1121" alt="everproject-view-timeline" src="https://user-images.githubusercontent.com/18181509/95541305-a9934200-0a25-11eb-9f70-614eb9e0ef70.png">

**Comment by joachimmarder** [comment]
Thanks, I've added it to our [Gallery](https://github.com/JAM-Software/Virtual-TreeView/wiki/Gallery).
