### ISSUE TITLE
Button size not scaled when not using VCL styles

### ISSUE THREAD

**Issue by modersohn** [JAM-Software/Virtual-TreeView#995]
When using the Minimal demo, the button images are not scaled:

![image](https://user-images.githubusercontent.com/44807458/96848574-e06d4d00-1454-11eb-9cb4-f8cbb05c0364.png)

This happens for both with and without PaintOptions.toThemeAware.

The default values for size (9x9) are not scaled (ScaledPixels calls missing) and instead of OpenTheme, OpenThemeDataForDPI should be called. I'll prepare a pull request.

**Comment by joachimmarder** [comment]
Weich Delphi version are you using?

**Comment by modersohn** [comment]
Sorry if that wasn’t clear from my comment above. The screenshots and verification of the fix were done with 10.4.1 Sydney. I’ve only looked in the RTL Source of 10.1 Berlin to see that the new API wasn’t available there. 

Ah now I see that I didn’t comment here but on the pull request. Please have a look at my other comment there

**Comment by joachimmarder** [comment]
I tried to replicate the problem on my PC, using Delphi 10.4.1 and the latest Virtual TreeView source from GitHub on Windows 10, but without success:

![grafik](https://user-images.githubusercontent.com/10615289/97120383-e2663300-1716-11eb-94ae-7065c943d1f5.png)

Which version of Virtual Treeview did you use?
Which manifest did you use?

**Comment by modersohn** [comment]
1. I'm using the sources at the tip of the master branch, i.e. commit ca85e5a with Delphi 10.4.1. 
2. I've got a system where my primary monitor is non-scaled, i.e. at 100% aka 96dpi and my secondary monitor is at 175%. The IDE runs on the primary non-scaled monitor. 
3. If I compile and run the Minimal demo from the IDE, I have to move it to the secondary monitor (by pressing Win+Left), then click "Add node(s) as children - the result is exactly what I posted here as screenshot in my first comment. 
4. Your screenshot looks correct, and mine does look exactly like that, but only if I apply the changes that I posted as pull request. Without these changes, it still looks as incorrect as my original screenshot (I just verified this by reverting the changes of my pull request).

Actually I'm quite surprised it looks okay on your machine, as the code clearly looks like it's not catering for DPI-changes.

Also; I've never run the minimal demo with a previous compiler and because of that, the Minimal demo is compiled with DPI awareness of "Per monitor". Is that the case on your end as well?

**Comment by joachimmarder** [comment]
That does the trick, having differently scaled monitors and doing this on the secondary monitor.

**Comment by modersohn** [comment]
Okay. Great to hear that you could reproduce it now. 

Now what should we do to make the code in my pull request handle older Delphi versions. Quoting my comment on the pull request:

“ I see 2 solutions: either calling the old OpenThemeData for older compilers (and possibly scaling the returned size manually), or importing OpenThemDataForDPI manually via GetProcAddress. Which one would you prefer?”

**Comment by joachimmarder** [comment]
I have already modified your pull request so that it should compile on all Delphi versions, but takes effect only in 10.3 and higher. Older Delphi versions are broken regarding multi monitor dpi awareness anyway.
