### ISSUE TITLE
Commit from 1 Nov 2020 breaks on Windows Server 2016 RDC Session

### ISSUE THREAD

**Issue by landrix** [JAM-Software/Virtual-TreeView#997]
https://github.com/JAM-Software/Virtual-TreeView/commit/94c7cd42e0f82ae014a3eb7d93ba6d07e5e8c8d9

exec. date/time    : 2020-11-10 21:38
version            : 6.0.0.0
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.1.0
callstack crc      : $ec310abf, $537542a8, $537542a8
exception number   : 1
exception class    : EExternalException
exception message  : Externe Exception C06D007F.

thread $3870:
7782c562 +062 KERNELBASE.dll                                RaiseException
0040230d +2a5 StartAF.exe    SysInit                        @_delayLoadHelper2
0047f4d5 +005 StartAF.exe    Winapi.UxTheme                 uxtheme.dll
005da410 +2b0 StartAF.exe    VirtualTrees                   TBaseVirtualTree.PrepareBitmaps
005e2cbd +129 StartAF.exe    VirtualTrees                   TBaseVirtualTree.CreateWnd
50d18d5e +016 vcl260.bpl     Vcl                            Controls.TWinControl.CreateHandle
50d19024 +074 vcl260.bpl     Vcl                            Controls.TWinControl.UpdateShowing
50d19052 +0a2 vcl260.bpl     Vcl                            Controls.TWinControl.UpdateShowing
50d191cc +0bc vcl260.bpl     Vcl                            Controls.TWinControl.UpdateControlState
50d1bf0a +026 vcl260.bpl     Vcl                            Controls.TWinControl.CMVisibleChanged
50d15292 +2be vcl260.bpl     Vcl                            Controls.TControl.WndProc
50d19d47 +63b vcl260.bpl     Vcl                            Controls.TWinControl.WndProc
50e652e1 +64d vcl260.bpl     Vcl                            Forms.TCustomForm.WndProc
50d14ecc +024 vcl260.bpl     Vcl                            Controls.TControl.Perform
50d138ea +026 vcl260.bpl     Vcl                            Controls.TControl.SetVisible
50e64aed +03d vcl260.bpl     Vcl                            Forms.TCustomForm.SetVisible
50e69e1f +007 vcl260.bpl     Vcl                            Forms.TCustomForm.Show
50e6a078 +170 vcl260.bpl     Vcl                            Forms.TCustomForm.ShowModal
00fe084d +29d StartAF.exe    PasswordLoginDlgXPUnit 153 +49 TPasswordLoginDlgXP.LoginDlg
017a3c36 +44a StartAF.exe    StartAF                145 +92 initialization
76e162c2 +022 KERNEL32.DLL                                  BaseThreadInitThunk

![image](https://user-images.githubusercontent.com/3299479/98734815-d038f580-23a2-11eb-83cb-fdb3c975f1f8.png)

![image](https://user-images.githubusercontent.com/3299479/98733570-ffe6fe00-23a0-11eb-964b-009c362ecaec.png)

**Comment by joachimmarder** [comment]
I don't see a connection between this commit and the call stack, the added code it not part of it. What exactly makes you think that it was this commit? Can this be replicated with one of the sample projects?

**Comment by landrix** [comment]
I will try to locate the problem

**Comment by landrix** [comment]
i have put all new changes to my source and placed an empty vst on an empty form

this change is the cause

![image](https://user-images.githubusercontent.com/3299479/99090753-4cb01c00-25cf-11eb-98c0-c9f21f960d4d.png)

**Comment by landrix** [comment]
It seems the minimum requirements are not correct

https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-openthemedatafordpi

**Comment by joachimmarder** [comment]
> this change is the cause

That's a different commit, but makes more sense when looking at the call stack.

> It seems the minimum requirements are not correct

This typically causes other errors. Is this system up to date regarding Windows Updates?

**Comment by pyscripter** [comment]
You need to check for Windows 10, version 1703 before using this API

**Comment by joachimmarder** [comment]
I did so now, please try again.

I'm still surprised: Is this system up to date regarding Windows Updates?

**Comment by landrix** [comment]
The last update is about a year old. I sent the admin a message. Then I'll try again.

**Comment by landrix** [comment]
we have updated the Windows Server 2016 to
![image](https://user-images.githubusercontent.com/3299479/99243424-ee6a7f80-2800-11eb-8bde-a7b2106ad199.png)
OpenThemeDataForDPI isn't available

but your last commit fixes the problem

thanks
